Cargo.lock
dapp/Cargo.toml
dapp/src/lib.rs
dapp/src/solc.rs
dapptools/Cargo.toml
dapptools/src/dapp.rs

* move solidity builder to its own file
* add some basic tracing
* always default to `--allow-paths .`

refactoring: first pass

---

rustfmt.toml

Add suggested options in #31 and run `cargo +nightly fmt`
Closes #31

feat: add rustfmt.toml

---

LICENSE-APACHE
LICENSE-MIT
dapp/Cargo.toml
dapptools/Cargo.toml
seth/Cargo.toml
utils/Cargo.toml

chore: add mit/apache license

---

dapptools/src/dapp_opts.rs

fix(dapp): ensure `build` and `test` subcommands have dedicated about

---

dapp/src/runner.rs
dapptools/src/dapp.rs
evm-adapters/src/blocking_provider.rs
evm-adapters/src/sputnik/forked_backend.rs
evm-adapters/src/sputnik/mod.rs

as title, makes the forking backend a bit more flexible

feat: generalize forking over `B: Backend`

---

Cargo.lock
solc/Cargo.toml
solc/src/lib.rs

* [solmate](https://github.com/Rari-Capital/solmate/) compilation w/o rayon is anywhere from 2.8 to 3.8s
* solmate compilation w/ rayon is consistently 2.1-2.2

feat: parallelize compilation per version with rayon

---

dapptools/src/dapp.rs
evm-adapters/src/blocking_provider.rs
evm-adapters/src/sputnik/forked_backend.rs
solc/src/lib.rs

1. Implements actual caching when making account-state related requests
2. Parallelizes fetching of account balance, nonce and code using tokio::spawn and tokio::try_join

feat: fork caching & parallelization

---

dapp/src/runner.rs
evm-adapters/src/lib.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/src/sputnik/evm.rs
evm-adapters/src/sputnik/forked_backend.rs
utils/src/lib.rs

as title, somewhat part of https://github.com/gakonst/dapptools-rs/issues/22

feat: improve UX when calling functions

---

Cargo.lock
dapp/src/runner.rs
dapptools/src/dapp.rs
evm-adapters/Cargo.toml
evm-adapters/src/evmodin.rs
evm-adapters/src/lib.rs
evm-adapters/src/sputnik/evm.rs
utils/src/lib.rs

feat: handle & print reverts on failing EVM execution 

---

Cargo.lock
dapp/GreetTest.sol
dapp/src/fuzz.rs
dapp/src/runner.rs
evm-adapters/src/sputnik/evm.rs
solc/src/lib.rs

Implements proptest strategies for the remaining param types + Abi encoder v2!

feat: fuzz more types

---

dapp/src/multi_runner.rs
dapp/src/runner.rs
dapptools/src/dapp.rs
dapptools/src/dapp_opts.rs
evm-adapters/src/fuzz.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs

Adds `DAPP_TEST_TIMESTAMP`, `DAPP_TEST_NUMBER`, and `DAPP_TEST_ADDRESS`

feat: expand env vars

---

README.md

Politely taken from https://github.com/dapphub/dapptools/blob/master/src/seth/README.md

chore: actualize seth commands in README.md

---

Cargo.lock
Cargo.toml
dapp/Cargo.toml
dapp/src/multi_runner.rs
dapp/src/runner.rs
dapptools/Cargo.toml
dapptools/src/dapp.rs
dapptools/src/dapp_opts.rs
evm-adapters/Cargo.toml
evm-adapters/src/sputnik/cheatcodes/backend.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs
evm-adapters/src/sputnik/cheatcodes/mod.rs
evm-adapters/src/sputnik/evm.rs
evm-adapters/src/sputnik/forked_backend/cache.rs
evm-adapters/src/sputnik/forked_backend/rpc.rs
evm-adapters/src/sputnik/mod.rs
evm-adapters/src/sputnik/state.rs

A lot of breaking changes in Sputnik, addressed in this PR.
This also enables us to use London & Base Fee!
We temporarily use the patched branch https://github.com/rust-blockchain/evm/pull/85

feat: Update sputnik

---

README.md
dapptools/src/seth.rs
dapptools/src/seth_opts.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
seth/src/lib.rs

```console
➜  dapptools-rs git:(feat/seth-storage) ./target/debug/seth storage 0x00000000219ab540356cbb839cbe05303d7705fa 0x10
Finished dev [unoptimized + debuginfo] target(s) in 0.26s
Running `target/debug/seth storage 0x00000000219ab540356cbb839cbe05303d7705fa 0x10`
0x2d6b099657385b88fbf2c9c4149346816fac6c6779ad2709f01164f590550a26
➜  dapptools-rs git:(feat/seth-storage) ./target/debug/seth storage 0x00000000219ab540356cbb839cbe05303d7705fa 16  
Finished dev [unoptimized + debuginfo] target(s) in 0.26s
Running `target/debug/seth storage 0x00000000219ab540356cbb839cbe05303d7705fa 16`
0x2d6b099657385b88fbf2c9c4149346816fac6c6779ad2709f01164f590550a26
```

feat(seth): storage

---

dapptools/src/seth.rs
dapptools/src/seth_opts.rs
seth/src/lib.rs

Duplicate of: https://github.com/gakonst/dapptools-rs/pull/148.

feat(seth): improve piped input support

---

assets/ContractTemplate.t.sol
cli/src/forge.rs

Similar to what [`dapp init`](https://github.com/dapphub/dapptools/blob/master/src/dapp/libexec/dapp/dapp-init) does.

feat(cli): add test lib to forge init

---

README.md

chore: add --locked param

---

evm-adapters/src/lib.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/testdata/DebugLogs.sol

ref: https://github.com/gakonst/foundry/pull/178

fix: emit console.log events on nested calls

---

cli/src/forge_opts.rs

as title, auto-loads remappings.txt from the root

feat: try to automatically load remappings from remappings.txt

---

cli/src/forge.rs
cli/src/forge_opts.rs
cli/src/utils.rs

1) new `clean` command for force re-compilation
2) some nice aliases
3) adds `--force` to `forge b`

feat: cli improvements

---

cli/README.md
cli/src/forge_opts.rs

chore: Update cli docs with forge init

---

Cargo.toml

Enable debug info in release profile, which should help with tracking down errors/panics

chore: enable debug in release profile

---

cli/src/forge_opts.rs
cli/src/utils.rs

support run command in sub dir

---

evm-adapters/src/fuzz.rs

fuzz string with unchecked bytes instead
ref: #45

fix: fuzz string with unchecked bytes instead

---

Cargo.lock

companion for https://github.com/gakonst/ethers-rs/pull/680

chore: bump ethers

---

forge/src/multi_runner.rs
forge/src/runner.rs

fix bad state reset

---

Cargo.lock

ref: https://github.com/gakonst/ethers-rs/pull/700

feat: bump ethers for new ethabi types

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs
evm-adapters/src/sputnik/cheatcodes/mod.rs
evm-adapters/testdata/CheatCodes.sol

Closes #247 
```solidity
interface Vm {
function prank(address) external;
function prankStart(address) external;
function prankStop() external;
}
contract Prank {
function bar(address expectedMsgSender) public {
require(msg.sender == expectedMsgSender, "bad prank");
InnerPrank inner = new InnerPrank();
inner.bar(address(this));
}
}
contract InnerPrank {
function bar(address expectedMsgSender) public {
require(msg.sender == expectedMsgSender, "bad prank");
}
}
contract MyTest is DSTest {
Vm vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
function testPrank() public {
Prank prank = new Prank();
address new_sender = address(1337);
vm.prank(new_sender);
prank.bar(new_sender);
prank.bar(address(this));
}
function testPrankStart() public {
Prank prank = new Prank();
address new_sender = …
```

feat(forge): prankStart + prankStop cheatcodes

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/src/sputnik/cheatcodes/mod.rs
evm-adapters/testdata/CheatCodes.sol
forge/src/multi_runner.rs

feat: basefee cheatcode

---

cli/src/opts/forge.rs

Improve cli help message for subcommands `verify-contract` and `completions`.

Improve cli help message

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/testdata/CheatCodes.sol

ref  https://github.com/gakonst/foundry/issues/280
added test as well

fix(cheatcode): modify transfer object on prank if necessary

---

evm-adapters/src/fuzz.rs
evm-adapters/testdata/Fuzz.sol
forge/src/runner.rs

fixes https://github.com/gakonst/foundry/issues/269

feat: print revert reason string on failed fuzz tests

---

evm-adapters/src/evmodin.rs
evm-adapters/src/lib.rs
evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs
evm-adapters/src/sputnik/evm.rs
evm-adapters/src/sputnik/mod.rs
forge/src/multi_runner.rs
forge/src/runner.rs
forge/testdata/DebugLogsTest.sol

Capture reverted logs on failed tests

---

evm-adapters/src/call_tracing.rs
evm-adapters/src/fuzz.rs
evm-adapters/src/lib.rs
forge/src/lib.rs
utils/src/lib.rs

fix(forge): fix errors on known function reverts

---

cli/src/cmd/build.rs

Adds error message if the detected source directory does not exist, which can happen if forge is run in a subdirectory.

chore(forge): add error message if source folder does not exist

---

Cargo.lock
cli/src/opts/mod.rs

https://github.com/gakonst/ethers-rs/pull/747

bump ethers & trezor cache

---

forge/README.md

I found this useful, and figured it might be useful for others, so I gave it a quick writeup

update README with console.log details

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

feat(cast): estimate

---

cli/src/cast.rs
cli/src/opts/cast.rs
cli/src/utils.rs

Implementation of feature request #333

feat(cast): wallet

---

cli/src/cast.rs

fix(cast): change default behavior of --from-wei and --to-wei

---

cli/src/cmd/create.rs
cli/src/cmd/mod.rs

as title, doing some refactoring in preparation of fixing the `verify` command

refactor(cli): move logic for reading artifact to helper fn

---

Cargo.lock
cast/Cargo.toml
cast/README.md
cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs
utils/Cargo.toml
utils/src/lib.rs

I'm pretty new to rust, so if anything isn't particularly rustic please point it out and I'd be happy to fix it.

feat: add `cast 4byte` and `cast 4byte-decode`

---

Cargo.lock
cli/Cargo.toml
cli/src/cast.rs
cli/src/opts/cast.rs
cli/src/utils.rs

Vanity wallet generation suggested in #333

feat(cast): wallet vanity

---

evm-adapters/src/fuzz.rs

Closes https://github.com/gakonst/foundry/issues/341 by always generating a U256 and wrapping to the desired size
Question—How can I verify the values being output by the strategy are in the expected range? I did some spot checks with solidity tests but not sure how to get more insight
Also, one thing that's a bit annoying (but I think can be handled in a separate issue) is if you write a test like the below:
```solidity
function testLimits(int40 a) public {
assertGe(a, 0);
}
```
you get a failure case like this, where I'd expect the int to be shown as a negative value instead of a uint as currently shown:
`[FAIL. Reason: . Counterexample: calldata=0x4db19789ffffffffffffffffffffffffffffffffffffffffffffffffffffff8000000000, args=[Int(115792089237316195423570985008687907853269984665640564039 …

fix: fuzzer handles int/uint size generation correctly

---

forge/README.md

- Adds expectEmit to list of cheatcodes
- Adds expectEmit to interface
- Adds example on how to use expectEmit

docs: Add expectEmit cheatcode

---

cli/src/cmd/build.rs
cli/src/forge.rs
cli/src/utils.rs

use latest ethers-solc util functions

chore(forge): use ethers-solc functions

---

cli/src/opts/forge.rs
evm-adapters/src/sputnik/forked_backend/cache.rs
evm-adapters/src/sputnik/forked_backend/rpc.rs
evm-adapters/src/sputnik/mod.rs

fixes https://github.com/gakonst/foundry/issues/336

fix(forge): support --tx-origin with --fork-url

---

Cargo.lock
Cargo.toml
cli/src/cmd/run.rs
ui/src/lib.rs

revised with https://github.com/gakonst/ethers-rs/pull/765

chore: update latest ethers utils

---

Cargo.lock
cli/src/cmd/build.rs
cli/src/cmd/mod.rs
utils/src/lib.rs

Fixes https://github.com/gakonst/foundry/issues/304

Don't suppress warnings

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs

Fixes https://github.com/gakonst/foundry/issues/404.

fix(forge): clear console.logs between test cases

---

cli/src/cmd/create.rs

Rust noob so feedback appreciated. I couldn't figure out how to convert the response from `get_chainid` into the `Chain` enum.

feat(forge/create): deploy legacy for optimism

---

README.md
cli/README.md
cli/src/cmd/mod.rs
cli/src/cmd/remappings.rs
cli/src/forge.rs
cli/src/opts/forge.rs

* move remappings command to standalone cmd
* add section about vscode setup
* fmt readme

docs: add vscode setup docs

---

cli/src/cmd/build.rs
cli/src/cmd/remappings.rs
cli/src/cmd/run.rs
cli/src/cmd/snapshot.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs

we should see even nicer features in the near future. see https://github.com/clap-rs/clap/issues/1232

feat: add clap value hints for improved completion

---

cli/src/cmd/build.rs
cli/src/utils.rs
evm-adapters/Cargo.toml
forge/src/lib.rs
forge/src/multi_runner.rs
forge/src/runner.rs

This should make @brockelmore 's branch brock/par_evm ready to go for #141

Lazily iterate over tests

---

Cargo.lock
cast/Cargo.toml
cast/src/lib.rs
cli/src/cast.rs
cli/src/cmd/verify.rs
cli/src/opts/cast.rs
cli/src/opts/mod.rs
cli/src/utils.rs
utils/Cargo.toml
utils/src/lib.rs
utils/testdata/interfaceTest.sol
utils/testdata/interfaceTestABI.json
utils/testdata/interfaceTestNoName.sol

fixes https://github.com/gakonst/foundry/issues/331

Autogen interfaces from deployed and verified contracts

---

forge/src/multi_runner.rs

fix(forge): filtering in multirunner

---

Cargo.lock

chore(deps): bump ethers with solang fix

---

Cargo.lock
cli/Cargo.toml
cli/src/opts/cast.rs

re: https://github.com/clap-rs/clap/pull/3295

fix cast autocompletion

---

cli/src/cmd/test.rs

Makes `forge test` output smaller when `verbosity > 1`. Previously failed and passed tests were output twice, in this PR they are only output once and traces/emitted logs are printed under the test name.
**Previously (tests passed)**
<details>
<summary>forge test</summary>
```
compiling...
success.
Running 4 tests for StdCheatsTest.json:StdCheatsTest
[PASS] testHoax() (gas: 12061)
[PASS] testHoaxOrigin() (gas: 12227)
[PASS] testStartHoax() (gas: 21464)
[PASS] testStartHoaxOrigin() (gas: 21619)
Running 9 tests for StdErrorsTest.json:StdErrorsTest
[PASS] testExpectArithmetic() (gas: 5652)
[PASS] testExpectAssertion() (gas: 4839)
[PASS] testExpectDiv() (gas: 5533)
[PASS] testExpectEnum() (gas: 5435)
[PASS] testExpectIntern() (gas: 5021)
[PASS] testExpectMem() (gas: 4884)
[PASS] …
```

Output traces and logs under test name

---

foundryup/install

refactor(forgeup): unpack tarball into foundry bin

---

cli/src/cmd/test.rs

Makes `forge test` fail with exit code 1 and print a summary of the failed tests instead of bailing.
Screenshot:
I originally wanted to implement a `.display(&self, verbosity: u8)` for `TestResult` and `TestOutcome` so we could print the full error + trace in the summary, but it would require us installing `ansi_term` in the `forge` crate so I decided against it. Would this still be a better approach?
Also, the error summary does not print the test contract name - should we?
Closes #449

Summarize errors

---

cli/src/forge.rs

fix(cli): commit only relevant files during forge install

---

cli/src/cmd/run.rs

fix(cli): compile target contract instead of trying to compile root dir

---

README.md
cli/src/cmd/build.rs
cli/src/cmd/mod.rs
cli/src/cmd/run.rs
cli/src/cmd/test.rs
cli/src/utils.rs
config/src/lib.rs
config/src/macros.rs
config/src/utils.rs

Add macro to remove boilerplate `From` implementations

feat(config): add macro to impl figment and config converter

---

foundryup/install

was told most ppl would prefer this: https://github.com/gakonst/foundry/issues/502

fix(foundryup): source in bashrc

---

Cargo.lock
cli/Cargo.toml
cli/build.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs
cli/src/utils.rs

Add git short sha and buildtime to `{forge, cast} --version`
`cast 0.1.0 (5bcd61c 2022-01-22T09:59:20.187646+00:00)`
`forge 0.1.0 (5bcd61c 2022-01-22T09:59:20.187646+00:00)`

feat: verbose version message

---

cli/src/cmd/build.rs
config/src/lib.rs

run `Project::cleanup` when creating the project

fix: run project cleanup in config

---

README.md

Add Foundry Support telegram to README.md.

docs: add support telegram

---

Cargo.lock
cli/tests/cmd.rs
config/Cargo.toml
config/src/lib.rs

support both snakecase `eth_rpc_url` and kebab-case `eth-rpc-url` in toml file

feat(config): support kebab-case fields in toml file

---

.github/workflows/release.yml

Fix man pages archive name

---

.github/workflows/release.yml

Checkout sources in release cleanup

---

cli/src/opts/cast.rs

fix(cast): support pending block tags

---

README.md
forge/README.md

Improved Foundry Book tips. Use the call-to-action to make them more encouraging.
Make it easier for new users to get started with Foundry.
Improved the original [Foundry Book](https://onbjerg.github.io/foundry-book) tip and added Forge-specific one in their respective readmes.

Improve Foundry Book mentions

---

cli/src/cmd/test.rs

fix(test): set fuzz runs

---

cli/src/cmd/snapshot.rs
cli/src/cmd/test.rs
cli/src/utils.rs

Closes #555
prefix snapshot tests with their contract: like `WETHTest:testDeposit()`

feat(snapshot): prefix test name with contract

---

evm-adapters/src/evm_opts.rs
forge/src/lib.rs

Default chain ID to 99

---

ui/src/lib.rs

fix(forge): stack view

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
evm-adapters/testdata/CheatCodes.sol

fix(forge): revert on dangling emit

---

cast/README.md

Add a new Foundry Book mention.
Help users with `cast`.
Add a helpful tip to the `cast` docs.

Add a Cast Guide tip

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Adds the ability to do `cast call <addr> <sig> --block <blockTag>`

feat: support block option in cast call

---

cli/src/opts/cast.rs
cli/src/utils.rs

fix cast send argument parsing

---

cast/README.md
cli/src/cast.rs
cli/src/opts/cast.rs

analogous to `seth sig`
```
$ cast sig "transfer(address,uint256)"
0xa9059cbb
```

feat: add `cast sig`

---

cli/src/opts/forge.rs

fix(forge): use rm as alias for forge remove

---

Cargo.lock
Cargo.toml
cast/src/lib.rs
config/README.md
config/src/lib.rs

~~Blocked by https://github.com/gakonst/ethers-rs/pull/868~~
Closes #652
Also bumps ethers
Add support for `OptimizerDetails` in the config

feat(config): support omptimizer details

---

cast/README.md
cast/src/lib.rs
cli/README.md
cli/src/cast.rs
cli/src/opts/cast.rs

Add `cast --to-int256` for converting signed ints into a hex string
```
$ cast --to-int256 -- -100
0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9c
```

feat(cast): add `cast --to-int256`

---

cast/README.md
cli/README.md
cli/src/cast.rs
cli/src/opts/cast.rs
utils/src/lib.rs

Add `cast 4byte-event` for getting the event signature for a topic
```
$ cast 4byte-event 0x133e35e21e24fa1cd40129f5e449f8fe1bffd66bf86383ff2b1f6d39d680d6e1
PlanetProspected(address,uint256)
```

feat(cast): add `cast 4byte-event`

---

cast/README.md
cli/README.md

Forgot to do it previously mb.

Doc: Updated docs for cast index

---

cast/README.md
cast/src/lib.rs
cli/README.md
cli/src/cast.rs
cli/src/opts/cast.rs

Add `cast --from-fix` for converting fixed point numbers into a specified number of decimals
```
$ cast -- --from-fix 18 0.01
10000000000000000
```

feat(cast): add `cast --from-fix`

---

cli/src/forge.rs

… working tree
Lost all my work after running "forge remove"
Add a prompt for the user to confirm action and warn of the consequences

fix: #673 Update remove function to prevent loss of untracked files

---

Cargo.lock
cli/src/forge.rs

feat: register ethers solc reporter

---

Cargo.lock

fixes https://github.com/gakonst/foundry/issues/442, svm-rs now creates a lockfile https://github.com/roynalnaruto/svm-rs/pull/20

fix: bump svm-rs to fix race condition on same version installs of solc

---

cli/src/cmd/build.rs
cli/src/opts/evm.rs
cli/src/opts/forge.rs

fix: remove rustdoc comments

---

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs

Fixes traces not showing logs when fuzzing

fix(forge): fuzz logs in traces

---

Cargo.lock
cli/src/cast.rs
cli/src/opts/cast.rs

Need to address a deserialization error:
```
Deserialization Error: data did not match any variant of untagged enum ResponseData at line 1 column 11172. Response: ...
```
```json
{
"jsonrpc": "2.0",
"id": 0,
"result": {
"address": "0x7ae1d57b58fa6411f32948314badd83583ee0e8c",
"accountProof": [
"0xf90211a087d9ba8f6ab8bc640924f17efbf99aafff3e5630940101578703ff0e788ab814a0a029266fa042a7bfd02a2e5d208d73232364e18e3c04ccfe09ff6351fc5151bca0f1f3de87d4453bc096a3325701dfa83c180a5a30d7e06ab58bc0c29a78af3fa7a0ffbc26dfa7c784789f4d45cef53b7e85a2cedb08aecc6d34aef9ec99782aef63a02ecfe8fb1cc90518c8d4956ec1bde20de0cb05309e4c6c6058986e91d33dc9c3a0f505849b7761b896db4899e8c41b411b6c55f0c01f798b5d22801696b1b6b86fa0c165ed1c33ba0cf84ba636b6333e419a9ac2eff603851d16b54bf19a1ac55061a0d5aef857c03d343d356cca1d2a1d816a …
```

feat(cast/proof): support generating storage proofs

---

cast/src/lib.rs

- Implementing `cast call/send <address> <0xCalldata>` (#29) 
-  Not sure if this is the most idiomatic way to do it, any feedback is appreciated, thanks!

feat(cast): implementing cast call/send <address>  <0xCalldata>

---

evm-adapters/testdata/CheatCodes.sol

this cheat code was added in https://github.com/gakonst/foundry/pull/725

chore: add `assume` to keep CheatCodes.sol up to date

---

forge/README.md

chore: document getCode

---

cli/test-utils/src/util.rs
cli/tests/cmd.rs
config/src/lib.rs

Close #723
Add additional remapping to the source dir which ensures direct imports into the src dir are resolved correctly

fix: add additional remapping to project source dir

---

cast/src/lib.rs
cli/test-utils/src/util.rs
cli/tests/cmd.rs
config/Cargo.toml
config/src/lib.rs
utils/src/lib.rs

Closes #783
check if solc_version is set and install if missing

fix: set solc version in project if explicitly set

---

cli/test-utils/src/util.rs
cli/tests/cmd.rs
config/README.md
config/src/lib.rs

Closes #793
This fixes a bug that resulted in the `optimizer_details` settings being ingored because they should be prefixed with the profile name according to toml standard.
updated docs accordingly

fix(config): support nested tables correctly

---

Cargo.lock
cli/src/cmd/mod.rs

Companion for https://github.com/gakonst/ethers-rs/pull/952

fix: ethers breaking change losslessabi

---

forge/README.md

Add gas report explanation

---

cli/src/cmd/init.rs

Attempting to fix #803
I don't think it works just yet, wanted to get feedback
- check if file exists, yes -> pass no deps, else-> install

fix(test): forge init --force does not work correctly

---

cli/src/cmd/install.rs
cli/src/forge.rs
cli/src/opts/cast.rs

+ minor typo
Fixing #767 + minor typo fix
Left off scoping installs for now and fixed the install first.
lmk of any corrections!

fix(forge install): raise error while installing non-existent repo

---

README.md

Add workaround to readme when facing outdated GLIBC error
Solution to issue #825

Readme update for GLIBC error workaround

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
evm-adapters/Cargo.toml
evm-adapters/src/sputnik/mod.rs
forge/Cargo.toml

Bumping primitive types across the board

chore: bump sputnik + ethers

---

cli/tests/cmd.rs
config/src/lib.rs

investigate https://github.com/gakonst/foundry/issues/842
Closes #842
Add additional test cases. Needs a follow up with a spells-mainnet integration test

test: add additional DAPP_LIBRARIES test cases

---

.github/workflows/cross-platform.yml

these are all failing, temp. disable them so CI failures can be meaningful

fix(ci): disable windows build

---

cli/Cargo.toml
cli/src/cmd/watch.rs
cli/src/utils.rs

Closes #847
keep track of the last modified test files and run those if a non-test file triggered the command.

feat(forge): run last modified test file in watch mode

---

Cargo.lock
fmt/Cargo.toml
fmt/src/formatter.rs
fmt/src/loc.rs

fix(fmt): bump solang and fix breaking changes

---

cli/src/cmd/watch.rs

Ref #868 
- add run-all arg
- don't reconfigure if `--match-contract` provided
Needs followup for spinner #880

feat(watch): improve watch command

---

cli/src/cmd/build.rs
cli/src/cmd/flatten.rs
cli/src/cmd/verify.rs
cli/test-utils/src/util.rs
cli/tests/cmd.rs
config/README.md
config/src/lib.rs

Closes #846
* support `Version` and `Local` installation in config via new enum type
* add `--use` flag, same as https://github.com/dapphub/dapptools/tree/master/src/dapp#solc-version

feat(forge/build): add --use argument

---

Cargo.lock
cli/Cargo.toml
cli/src/cast.rs
cli/src/cmd/mod.rs
cli/src/cmd/test.rs
cli/src/forge.rs
cli/src/term.rs
cli/tests/cmd.rs
forge/src/multi_runner.rs

~~**Blocked By** https://github.com/gakonst/ethers-rs/pull/1000~~
Add Spinner implementation
Closes #868
Add a simple Spinner implementation for `ethers::solc::Reporter`
[![asciicast](https://asciinema.org/a/QJEvHv097eftVNtc6aGwtHFML.svg)](https://asciinema.org/a/QJEvHv097eftVNtc6aGwtHFML)
cc @transmissions11 
Could also use a random spinner.
perhaps this also should be opt-out?

feat: add spinner implementation

---

cli/README.md

Added `forge inspect` documentation to `cli/README.md`.

docs(forge/inspect): Forge Inspect Subcommand Documentation

---

Cargo.lock
cli/src/cmd/snapshot.rs
cli/src/cmd/test.rs
cli/src/utils.rs
cli/test-utils/src/util.rs
cli/tests/cmd.rs

Close #912
Use contract name in addition to sig when comparing snapshot entries

fix(forge/snapshot): use unique ids when comparing snapshot entries

---

cli/src/opts/forge.rs

~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/1024~~
https://github.com/gakonst/foundry/issues/931

chore: bump ethers trim contract args

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Experimenting with access lists, I'd like an easy way to inspect them
This commit adds a `cast access-list` command. It
is similar to `cast call` but also accepts a `--json` flag
to print the result in JSON.
Example usage:
```
$ cast access-list \
0x99c9fc46f92e8a1c0dec1b1747d010903e884be1 \
0x...
gas used: 53942
access list:
- address: 0x9ba6e03d8b90de867373db8cf1a58d2f7f006b3a
keys:
0x0000000000000000000000000000000000000000000000000000000000000000
0x6c9a6c4a39284e37ed1cf53d337577d14212a4870fb976a4366c693b939918d5
- address: 0x34cfac646f301356faa8b21e94227e3583fe3f5f
- address: 0xd5d82b6addc9027b22dca772aa68d5d74cdbdf44
- address: 0x40e0c049f4671846e9cff93aaed88f2b48e527bb
- address: 0xdac17f958d2ee523a2206206994597c13d831ec7
keys: …
```

feat: add `cast access-list`

---

Cargo.lock

chore(deps): bump ethers

---

Cargo.lock
cli/src/term.rs
evm-adapters/src/sputnik/mod.rs

Companion for https://github.com/gakonst/ethers-rs/pull/1029

fix: update reporter trait

---

cli/src/term.rs
cli/tests/cmd.rs

Closes #953
if no tty then use common println!

fix(forge): fallback to stdout out reporter if no tty

---

forge/src/executor/inspector/cheatcodes/ext.rs

REVM: `getCode` cheatcode updates

---

forge/src/executor/inspector/cheatcodes/ext.rs

REVM: FFI cheatcode updates

---

Cargo.lock
cli/src/term.rs

Companion for https://github.com/gakonst/ethers-rs/pull/1043

feat(solc): support for solc io json output

---

Cargo.lock
cli/src/cmd/build.rs
cli/src/cmd/flatten.rs
cli/src/cmd/verify.rs
cli/tests/cmd.rs
config/README.md
config/src/lib.rs

Closes #957
* add --via-ir flag and config value
* bump ethers

feat(forge): add support for viaIR with --via-ir flag

---

cli/src/cmd/mod.rs

Use new `Artifacts` trait helper function

style: use new artifacts function

---

Cargo.lock

Adds https://github.com/gakonst/ethers-rs/pull/1069

chore(deps): bump ethers and svm

---

Cargo.lock
config/Cargo.toml

Companion for https://github.com/gakonst/ethers-rs/pull/1071
Needs ethers bump once merged

chore: use new ethers-solc svm-solc feature

---

cli/src/cmd/forge/test.rs
forge/src/gas_report.rs

Gas reports were not showing because of some issues with the verbosity logic

fix: gas reports

---

cli/src/cmd/forge/build.rs
cli/src/cmd/forge/snapshot.rs
cli/src/cmd/forge/watch.rs
cli/src/forge.rs

Closes #911
and --watch flag for `snapshot`.
Rn there's no reconfigure, everything is run again, if that should be configurable needs a followup.
CC @transmissions11

feat(snapshot/watch): add support for snapshot --watch

---

cli/src/cmd/forge/test.rs
evm/src/executor/fork/backend.rs
evm/src/executor/fork/cache.rs
forge/src/multi_runner.rs

tests are actually run on a new thread.
wait until the test thread finishes which makes sure the cache is flushed

fix(test): wait until test thread finishes to make sure cache is flushed

---

cli/tests/test.rs
evm/src/fuzz/strategies/param.rs
evm/src/fuzz/strategies/state.rs

Closes #1038
generate an array with the fixed length instead of a range for fixed arrays.
keep the panic on encoding err but report that's a bug

fix(test/fuzz): generate fixed arrays in fuzzers

---

foundryup/foundryup

fix: switch to branch before fetch

---

config/README.md
config/src/caching.rs

Cache all endpoints by default

chore(config): make rpc storage cache for all endpoints the default

---

cli/src/cmd/forge/build.rs
cli/tests/cmd.rs
cli/tests/config.rs
config/src/lib.rs

add config roundtrip test to ensure all values can be extracted
* add separate config.rs test file
* fix some config related bugs

test(config): add config roundtrip test

---

evm/src/executor/builder.rs
evm/src/executor/fork/backend.rs

rename `SharedBackend::new` to `SharedBackend::spawn_backend` to make it more clear that this does indeed spawn something.

refactor: rename new to spawn_backend

---

cli/src/opts/mod.rs

Fixes https://github.com/gakonst/foundry/issues/1013
one-line change, 30-line test
If there's a 'rustier' way to fix/test this, LMK

forge: descriptive error messae for illformed wallet private keys

---

.github/workflows/test.yml
cli/Cargo.toml
cli/test-utils/src/util.rs
cli/tests/config.rs

fix wrong into conversion introduced in #1056
also run only integration tests in integration job

fix(cli): wrong SolcReq into and only run integration tests

---

cli/src/cmd/forge/build.rs
cli/src/forge.rs
cli/test-utils/src/util.rs
cli/tests/cmd.rs
config/src/utils.rs

fix(config/clean): use config settings for forge clean

---

cli/src/cmd/forge/init.rs
cli/src/opts/mod.rs
evm/src/fuzz/strategies/param.rs
forge/src/lib.rs
forge/src/multi_runner.rs
utils/src/lib.rs

chore(clippy): make clippy happy

---

evm/src/executor/inspector/cheatcodes/mod.rs

fix: make cheatcodes ignore console addr

---

.github/workflows/test.yml

reverts CI related erroneous changes made #1076 
run all integration tests again

ci: reenable all integration tests in workspace

---

cli/tests/cmd.rs

Updates an integration test to the new `forge test` output

test: update integration tests to new output

---

.github/workflows/test.yml

Should (hopefully) speed up our forking integration tests
Closes #1107

test: cache fork data

---

forge/src/multi_runner.rs

use new `ArtifactId::identifier` consistently

fix: use correct identifier key for source paths

---

.github/workflows/cross-platform.yml
.github/workflows/docker-publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

- Run cross-platform tests for the platforms we target
- Only run cross-platform tests if our main tests pass. We only have a certain number of CI minutes so it's better to conserve them

ci: cross-platform cleanup

---

evm/src/executor/inspector/cheatcodes/expect.rs
testdata/cheats/ExpectEmit.t.sol

fix: ensure number of topics match in expect emit

---

evm/src/executor/fork/backend.rs

remove redundant checks highlighted here https://github.com/gakonst/foundry/pull/1033#discussion_r841124955

chore(evm): remove redundant checks

---

cli/src/cast.rs
cli/src/opts/cast.rs

feat(cast): reuse nonce

---

cli/src/cmd/forge/build.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/verify.rs

feat(config): add --config-path argument

---

evm/src/executor/abi.rs
evm/src/executor/inspector/cheatcodes/env.rs
forge/README.md
testdata/cheats/Cheats.sol
testdata/cheats/GetNonce.t.sol
testdata/cheats/SetNonce.t.sol

feat(cheatCodes): set/getNonce for an account

---

Cargo.toml

add comments for patching local ethers

chore: add comments to patch local ethers

---

Cargo.lock
cli/tests/it/config.rs
config/README.md
config/src/lib.rs
fmt/Cargo.toml
fmt/src/loc.rs
fmt/src/visit.rs

~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/1104~~
closes #1177 
* adds `bytecode_hash` config value and make "none" the default

feat(config): make bytecode_hash = 'none' the default value

---

evm/src/executor/fork/backend.rs

As discovered here https://github.com/gakonst/foundry/pull/1033#discussion_r841299251 the previous exit condition was not deterministic.
There was no guarantee that the handler will be polled again after the shutdown channel was closed, because if the `Receiver` returns a value no waker will be registered.
Return `Ready` after the last sender was dropped, no more connected `SharedBackend`s so it's safe to exit and this branch will always be Hit.

fix(evm): improve exit condition for backend handler

---

cli/src/cmd/forge/create.rs

Adds eyre context if you try to deploy a contract that requires constructor arguments... without constructor arguments.
I am dumb, and tried to run `forge create` on a contract without arguments, only to get this error:
```
[⠒] Compiling...
Error: 
0: Invalid data
```
I wasn't sure what this meant, or how I would go about debugging it.
Now, when you try to run `forge create` on a contract without arguments and hit an error deploying, it adds a bit of context. 
```
Error: 
0: No arguments provided for contract constructor. Consider --constructor-args or --constructor-args-path
1: Failed to deploy contract
2: Invalid data
```

feat: add helpful context to failed deployment in forge

---

Cargo.lock
cli/tests/it/test.rs

~~**BLOCKED BY COMPANION** https://github.com/gakonst/ethers-rs/pull/1111~~
Closes #1205

test: add pre bytecode hash test

---

README.md

correct 'asky' typo

---

Cargo.lock

Closes #1223 
Bump up svm-rs after merging https://github.com/roynalnaruto/svm-rs/pull/37

chore: bump up svm

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/forge/test.rs
cli/src/cmd/forge/watch.rs
cli/tests/it/test.rs

Fixes #1039
* make `--match-path` globs instead of regex
* fix broken watch, test file detection

fix: make --match-path globs and fix watch

---

cli/src/term.rs

chore: indent remappings on unresolved

---

cli/test-utils/src/macros.rs
config/src/lib.rs

Turns out people did not want it anyway

chore: disable ETH_RPC_URL env var

---

rust-toolchain

Ensure everyone uses the intended toolchain
commit a `rust-toolchain` file

feature: rust-toolchain file

---

cast/Cargo.toml
cli/Cargo.toml
cli/test-utils/Cargo.toml
config/Cargo.toml
evm/Cargo.toml
fmt/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml

populate package section of Cargo.toml with
```toml
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/gakonst/foundry"
keywords = ["ethereum", "web3", "evm", "solidity"]
```
where applicable

meta: populate package section

---

Cargo.lock

Closes https://github.com/gakonst/foundry/issues/1116
Bump up `ethers` and `svm`

chore: bump up ethers and svm

---

README.md

Remove crate badge from README.md while we still don't have one, #665.

remove crate badge #665

---

cli/src/cmd/forge/verify.rs

we now support chains by their name. this adds a `--chain` alias consistent with `create`

feat(verify): add chain alias

---

cli/src/cmd/forge/snapshot.rs

chore: improve help text for `forge snapshot`

---

Cargo.lock
config/Cargo.toml
config/src/chain.rs
config/src/lib.rs

Adhere to `#![deny(missing_docs, unsafe_code, unused_crate_dependencies)]` in config

chore(config): add some deny lints

---

Cargo.lock
binder/Cargo.toml
binder/README.md

Ref #1313 #1314
Disable libgit2 default features

chore: disable libgit2 ssh feature by default

---

README.md

Links should use the new url
Update appropriate links to use the new url

chore(docs): update readme with org urls

---

fmt/src/formatter.rs

Previously, we've been restoring statements from source code. Let's start formatting it with block statements first since they're the most common.
Format block statements aka any code blocks inside `{}` such as function bodies, unchecked blocks, etc.

feat(fmt): block statement

---

assets/workflowTemplate.yml

Append workflow name to the top most of the yaml file
Update checkout to use latest major version (v3)
Add explicit forge build step before forge test
Add id fields for individual commands for easier log parsing
Contract Sizes and Contract Tests are grouped in the CI logs by id and output 
Also includes concurrency note for downstream users who may be running multiple workflows / CI pipelines

fix(templates): github action workflow

---

cli/src/cmd/forge/test.rs

feat(forge): add --etherscan-api-key options to forge test

---

cli/src/cast.rs
cli/src/opts/cast.rs

Add zero address and zero hash constants. Feature parity with https://docs.ethers.io/v5/api/utils/constants/#constants-AddressZero

feat(cast): add zero address and zero hash constant

---

Cargo.lock
evm/src/executor/inspector/debugger.rs

includes some changes required for #1037

chore(deps): bump revm

---

utils/src/lib.rs

support `--sig "g(uint256)" 0x64`

feat: support u256 in hex

---

config/src/lib.rs

chore: support FOUNDRY_SOLC_VERSION env var

---

config/src/lib.rs

chore: update config link

---

cli/src/cmd/forge/build.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/verify.rs

Closes #1371
Move `--config-path` to `ProjectPathsArgs` so it's support by `verify` and `flatten`

feat(config): support --config-path in flatten and flatten

---

.github/workflows/docker-publish.yml
CONTRIBUTING.md
Cargo.lock
binder/Cargo.toml
binder/README.md
cast/Cargo.toml
cli/Cargo.toml
cli/src/cmd/forge/run.rs
cli/test-utils/Cargo.toml
common/Cargo.toml
config/Cargo.toml
evm/Cargo.toml
evm/src/fuzz/strategies/state.rs
fmt/Cargo.toml
testdata/fuzz/FuzzNumbers.t.sol
ui/Cargo.toml
utils/Cargo.toml

```diff
- gakonst/foundry
+ foundry-rs/foundry
```

fix(url): update to new org name

---

cli/tests/it/verify.rs

Add a basic test for fantom testnet verification
**NOTE** for some reason this does not work, I tried to debug this for way too long... 
submitting the `std json compiler input` that's sent via `forge verify` [_manually_](https://testnet.ftmscan.com/verifyContract) works, but `forge verify` does not for some reason...
Unfortunately their API is undocumented so it might be that they're expecting something different... https://ftmscan.com/apis

test: add fantom verify test

---

cli/src/cmd/forge/init.rs

Fix failing test introduced in #1409

test: update failing test

---

cli/tests/it/main.rs
cli/tests/it/test_cmd.rs
cli/tests/it/verify.rs

get rid of all warnings during cargo test

chore(test): silence warnings in test

---

cast/src/lib.rs
cast/src/print_utils.rs

Fix #1421 
It implements pretty print for `TransactionReceipt`
before
```
blockHash            "0xbd826adccd631b3aeb1ff0a15a7ff6c2509748dacd798e66ab14ee60924f4203"
blockNumber          "0xa15d7d"
contractAddress      null
cumulativeGasUsed    "0xb425"
effectiveGasPrice    "0xb2e7b009"
gasUsed              "0xb425"
logs                 [{"address":"0x356a7bb15a898e7265f377a71825d21072202123","blockHash":"0xbd826adccd631b3aeb1ff0a15a7ff6c2509748dacd798e66ab14ee60924f4203","blockNumber":"0xa15d7d","data":"0x000000000000000000000000000000000000000000000000000000000000000a","logIndex":"0x0","removed":false,"topics":["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0x00000000000000000000000031c618276f7a4db1c01c22eb56f44fe1edb1af36","0x000000000000000000000000356a7bb15a898e72 …
```

chore(cast): `cast send` pretty print

---

Cargo.lock

Includes https://github.com/gakonst/ethers-rs/pull/1177

chore(test): bump ethers

---

fmt/README.md

We have an umbrella issue https://github.com/foundry-rs/foundry/issues/781 for implementing formatting of different parse tree nodes. This list in README.md can help us keep track of what's left to implement.
List of WIP nodes to implement formatting for.

chore(fmt): add WIP entities to README.md

---

cli/src/cast.rs

feat: enable tracing in cast

---

cli/test-utils/src/util.rs
cli/tests/it/cmd.rs

Adds test mentioned here https://github.com/foundry-rs/foundry/issues/1244#issuecomment-1112158060
couldn't reproduce, but the scenario was probably fixed by https://github.com/gakonst/ethers-rs/pull/1177

test: repeat builds with errors work as expected

---

fmt/README.md
fmt/src/formatter.rs

Formatting of `FunctionAttribute::Override` wasn't implemented.
Implement it.

feat(fmt): override function attribute

---

fmt/README.md
fmt/src/formatter.rs
fmt/src/visit.rs
fmt/testdata/EventDefinition/fmt.sol
fmt/testdata/EventDefinition/original.sol

Formatting of `EventDefinition` wasn't implemented.
Implement it.

feat(fmt): event definition

---

fmt/README.md
fmt/src/formatter.rs
fmt/src/visit.rs
fmt/testdata/ErrorDefinition/fmt.sol
fmt/testdata/ErrorDefinition/original.sol

Formatting of `ErrorDefinition` wasn't implemented.
Implement it.

feat(fmt): error definition

---

Cargo.lock
cli/Cargo.toml
cli/src/cast.rs
cli/src/cmd/utils.rs
cli/src/forge.rs
cli/src/suggestions.rs

provide suggestions if artifact name was not found
* add `suggestions` module with string similarity checks

feat: better read artifacts ux with suggestions

---

evm/src/executor/inspector/debugger.rs

fix: debugger under/overflow in gas calc

---

cli/tests/it/utils.rs
cli/tests/it/verify.rs

adds a successful optimism kovan verify test
Ref #1322

test: add op kovan verify test

---

config/src/lib.rs

Closes #1372
pretty print figment errors before panicking
for missing quote or `FOUNDRY_CONFIG` value that points to non existing file
```console
config error: newline in string found at line 3 column 52 in foundry.toml TOML file
config error: Config file `non-existing-file` set in env var `FOUNDRY_CONFIG` does not exist in TOML file provider
thread 'tests::test_toml_file_parse_failure' panicked at 'failed to extract foundry config', config/src/lib.rs:338:17
```

feat: better error message if config parsing failed

---

cli/README.md
cli/src/cmd/forge/cache.rs
cli/src/cmd/forge/mod.rs
cli/src/forge.rs
cli/src/opts/forge.rs
cli/tests/it/cmd.rs
config/src/lib.rs

❗extending this command with options to specify chain and blocks. first time working in Rust, feedback would be appreciated.
closes #1127 
forked state is now being added to the cache. this state should be easily cleanable.
adding a cli command `forge cache clean` to clean the cache.

feat(cli): add cache clean command

---

Cargo.lock
cli/src/term.rs

**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/1216
update the std json interface to dump multiple files

fix: update std json logger interface

---

README.md
anvil/Cargo.toml
anvil/README.md

docs: update anvil README

---

anvil/src/anvil.rs
anvil/src/config.rs
anvil/src/lib.rs

print version+build on startup

style(anvil): print version on startup

---

cli/tests/it/config.rs
config/src/lib.rs

Closes #1492
this takes into account that `src` can be named differently and adjusts the remapping to nested foundry dirs accordingly

perf: improve resolve nested foundry.toml remapping

---

utils/src/lib.rs

If fourbyte is down (502) simply skip the tests

test: skip fourbyte tests if website down

---

cli/tests/it/config.rs
config/src/lib.rs

This will make sure, that if there's a collision of remappings
1)  `dep/=lib/a/src` 
2) `dep/=lib/a/lib/b/src`
`1)` will always replace `2)`

fix: prioritise closer remappings on collision

---

anvil/src/eth/api.rs

fix(anvil): use zero price if not set in estimate

---

anvil/README.md

There's an additional "Installing from source" line that should be deleted. To solve this, I just deleted the extra line as you can see in my commit

Removed an additional "Installing from source" line

---

binder/src/utils.rs
utils/src/lib.rs

New nightly dropped, new lints dropped
Currently still fails because of some unused lifetimes in abigen

chore: clippy

---

fmt/README.md
fmt/src/formatter.rs
fmt/testdata/UsingDirective/fmt.sol
fmt/testdata/UsingDirective/original.sol

Support formatting `using` directive.
Do it with some restrictions: https://github.com/foundry-rs/foundry/blob/147cc7813597d09ccbf87861a8c5feca79164f13/fmt/README.md?plain=1#L20

feat(fmt): using directive

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/lib.rs

Closes #1529 
Add `-b --blockTime <secs>` argument for interval mining

feat(anvil): add blocktime argument

---

anvil/src/eth/api.rs
anvil/src/eth/backend/db.rs
anvil/src/eth/backend/info.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/anvil.rs
anvil/tests/it/api.rs
evm/src/lib.rs

Closes #1511
Create Pending block on `BlockNumber::Pending`

feat(anvil): support pending block

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs

get rid of some expensive clones

perf(anvil): remove block clones

---

anvil/src/eth/backend/db.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/in_memory_db.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/state.rs

previously state root of a new block was not computed.
if anvil is configured with memdb, compute it based on the accounts and state in memory

feat(anvil): compute state root for memdb

---

evm/src/executor/fork/backend.rs

Solves [anvil hang](https://github.com/foundry-rs/foundry/pull/1037#discussion_r865694469) without performance cost. Closes #1561 
not sure if it is best we can do, but this helps tokio to handle scheduling.

fix(evm/anvil): recover BackedHandler performance

---

cli/src/cmd/forge/test.rs
cli/tests/it/test_cmd.rs
forge/src/multi_runner.rs

Closes https://github.com/foundry-rs/foundry/issues/1420
Check the number of filtered tests before running.

fix(forge/test): issue error when no tests match

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/lib.rs

Closes #1570
add `--host <ipaddr>` option:
`anvil --host 0.0.0.0`
```console
Listening on 0.0.0.0:8545
```

feat(anvil): add --host option

---

cli/src/cmd/forge/verify.rs

closes #1582
Remove check completely, no longer required as paths are now being stripped

fix(verify): remove source dir restriction

---

cli/src/cmd/forge/test.rs
cli/tests/fixtures/suggest_when_no_tests_match.stdout
cli/tests/fixtures/warn_no_tests.stdout
cli/tests/fixtures/warn_no_tests_match.stdout
cli/tests/it/test_cmd.rs

Closes https://github.com/foundry-rs/foundry/issues/1575.
Only provide warning/suggestion, instead of throwing error, when there are no matching tests.

fix(forge/test): issue warning when no test match

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/lib.rs

Closes #1512
Add `--no-mine` flag to boot in `MiningMode::None`

feat(anvil): add --no-mine option

---

evm/src/executor/fork/backend.rs

I'm quickly approaching the lowest (value to foundry)/(PRs to foundry) ratio.

chore(backend.rs): their -> there

---

cli/Cargo.toml

latest pre release contains several fixes and perf improvements

chore(deps): bump watchexec

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

#1605
Add a `--name` optional flag

feat(cast): allow providing a custom interface name

---

anvil/src/eth/pool/mod.rs
anvil/tests/it/transaction.rs

Add tests that execute same tx concurrently to investigate  potential loop
send same tx with same nonce at the same time and expect only one to succeed

test(anvil): add concurrent tx tests

---

anvil/src/config.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs

Closes #1623
fetch dev accounts from fork and only set genesis balance,

fix(anvil): respect existing accounts on fork

---

cli/src/cast.rs

Currently `cast send` cannot use an etherscan api key set in the foundry config. This is because the arguments are encoded before passing the etherscan key to `TxBulder`. Additionally, the ergonomics of using anything involving etherscan in cast is suboptimal since you must explicitly set the chain, instead of having it automatically be fetched using the provider's `eth_chainId`.
Switch the ordering of encoding the args and setting the etherscan key in `cast send`. Additionally auto-fetch the chain using the provider in all cast functions and only use `eth.chain` as a fallback (this is as per the discussion in #1523).

cast(fix): better etherscan handling

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/tests/it/fork.rs

Add additional anvil reset test
Ref #1626
ensure nonce, balance, tx are properly reset to origin after `anvil_reset`

test(anvil): add anvil_reset test

---

cli/tests/fixtures/can_test_repeatedly.stdout
cli/tests/it/test_cmd.rs

Debugging https://github.com/foundry-rs/foundry/issues/1629
ensure we get same output after repeatedly calling `forge test`

test: add test to repeatedly get same output

---

anvil/tests/it/anvil_api.rs
anvil/tests/it/transaction.rs

* ensure `evm_mine` works as expected in mining modes
* add evm_mine tests

test(anvil): add more auto mine tests

---

Cargo.lock
anvil/src/eth/backend/mem/mod.rs
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
cli/tests/it/test_cmd.rs
evm/src/executor/fork/init.rs

Blocked by https://github.com/gakonst/ethers-rs/pull/1273
Closes #1306
Includes latest ethers-solc bump with fix and test against scenario in #1306

test(forge): ensure tests are only run once if version changes

---

cli/src/opts/mod.rs

Fixes: https://github.com/foundry-rs/foundry/issues/1641
working for goerli, rinkeby, arbitrum-testnet, avalanche-fuji, polygon-mumbai, mainnet
```sh
~/CLionProjects/foundry/target/debug/cast etherscan-source -c goerli 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
~/CLionProjects/foundry/target/debug/cast etherscan-source -c rinkeby 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
~/CLionProjects/foundry/target/debug/cast etherscan-source -c arbitrum-testnet 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
~/CLionProjects/foundry/target/debug/cast etherscan-source -c avalanche-fuji 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
~/CLionProjects/foundry/target/debug/cast etherscan-source -c polygon-mumbai 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
~/CLionProjects/foundry/target/debug/cast etherscan-source -c …
```

fix: clapchain possible_values for chains

---

config/README.md
config/src/lib.rs

Closes #891
read `default` values and set them to the selected profile before merging all providers

feat(config): inherit from default profile

---

anvil/src/eth/api.rs
anvil/src/eth/pool/mod.rs
anvil/src/eth/pool/transactions.rs
anvil/tests/it/fork.rs
anvil/tests/it/transaction.rs

closes #1639
if tx not found in storage, check mempool

fix(anvil): check mempool for pending transactions

---

cast/src/print_utils.rs
cast/src/tx.rs

Closes #1650
improve error message when cast failed to determine signature

chore(cast): improve error message when no sig found

---

anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/util.rs

closes #1584
implement `eth_createAccessList` correctly:
* remove precompiles from state
* enforce `return_ok!`
* return `gas_used` with accesslist set

fix(anvil): implement access list generation

---

anvil/src/lib.rs

decrease polling interval to speed up anvil tests, 500ms should still be more than enough in debug mode.

chore(anvil): decrease http polling interval further

---

anvil/src/eth/backend/fork.rs
cli/README.md
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/verify.rs
config/README.md
evm/src/executor/opts.rs
evm/src/fuzz/strategies/uint.rs
evm/src/trace/utils.rs
forge/README.md
foundryup/foundryup
testdata/fork/DssExecLib.sol

There are spelling mistakes
Fix the spelling errors

fix: spelling mistakes

---

evm/src/executor/inspector/cheatcodes/mod.rs

Fixes https://github.com/foundry-rs/foundry/issues/1537

fix mockCall panicking because of OOB access

---

anvil/core/src/eth/call.rs
anvil/core/src/eth/mod.rs
anvil/core/src/eth/subscription.rs
anvil/core/src/eth/trie.rs
anvil/core/src/types.rs
anvil/rpc/src/response.rs
anvil/src/eth/pool/transactions.rs
anvil/src/pubsub.rs
binder/src/utils.rs
config/src/lib.rs
evm/src/trace/mod.rs
fmt/src/formatter.rs

fix new clippy lints on nightly `cargo +nightly clippy --fix --all-features -Z unstable-options`

chore(clippy): fix newest nightly lints

---

cli/src/cmd/forge/create.rs

Improve error message for non utf8 constructor args
Ref #1651

chore: improve invalid utf8 error message

---

README.md

closes #1679
* update instructions to install via cargo
* mention https://github.com/foundry-rs/foundry-toolchain

chore: update readme install instructions

---

anvil/src/eth/backend/mem/mod.rs

temporary fix for #1688
wrap blocking calls in `tokio::block_in_place`.
this solution is to be considered temporary a better solution would be to use tokios sync primitives for storage or refactor the Backendhandler so it can be spawned on its own thread, perhaps the better solution

fix(anvil): use tokio task block in place

---

anvil/core/src/eth/mod.rs
anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/pool/mod.rs
anvil/src/eth/pool/transactions.rs

Ref https://github.com/gakonst/ethers-rs/pull/1286
implement geth txpool rpc api

feat(anvil): add geth txpool rpc api

---

cli/src/cmd/forge/create.rs
config/src/lib.rs

Closes #1683
join paths in modelchecker contracts with the root path so relative paths are supported

fix: support non absolute paths for model checker

---

anvil/tests/it/fork.rs
cli/test-utils/src/lib.rs
cli/test-utils/src/macros.rs
cli/test-utils/src/rpc.rs
cli/tests/it/cast.rs
cli/tests/it/cmd.rs

Closes #1643
rotate various infura+ethalchemy API keys

feat: use rotating api keys in fork unit tests

---

cli/src/cmd/forge/watch.rs

Closes #1708
only watch paths that exists by default

fix(watch): only watch dirs that exists

---

cli/src/cmd/forge/install.rs

Closes https://github.com/foundry-rs/foundry/issues/1684.
Check that working/staging area is clean with `git status --short` when installing as submodule.

fix(forge/install): add git status check before commit

---

cli/tests/fixtures/can_check_snapshot.stdout
cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
cli/tests/fixtures/suggest_when_no_tests_match.stdout
cli/tests/it/cmd.rs

update failing tests due to changed reporter output

test: update failing tests

---

anvil/tests/it/fork.rs

use elapsed time instead of heuristic window

test: fix flaky timestamp test

---

cli/src/cmd/cast/find_block.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/bind.rs
cli/src/cmd/forge/build.rs
cli/src/cmd/forge/cache.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/inspect.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/remappings.rs
cli/src/cmd/forge/run.rs
cli/src/cmd/forge/snapshot.rs
cli/src/cmd/forge/test.rs
cli/src/cmd/forge/tree.rs
cli/src/cmd/forge/verify.rs
cli/src/cmd/forge/watch.rs
cli/src/cmd/utils.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs
cli/src/opts/mod.rs
common/src/evm.rs

Closes: https://github.com/foundry-rs/foundry/issues/917
Is this on the right track?
If so, I'd like to plow through everything else and add `value_name` and `help`
It looks like the help is filled out with the doc comments and so added it explicitly as well.
https://github.com/foundry-rs/foundry/blob/fc534d9f17883519118ea54e0894b6f8ff5a8083/cli/src/cmd/forge/test.rs#L45-L47
Current changes look like this
```sh
➜  ~ ~/CLionProjects/foundry/target/debug/forge test -h
forge-test
Run the project's tests.
USAGE:
forge test [OPTIONS]
OPTIONS:
-m, --match <PATTERN>
Only run test functions matching the specified regex pattern
--match-test <REGEX>
Only run test functions matching the specified regex pattern
--no-match-test <REGEX>
Only run test functions that do not match the specified regex …
```

fix: expressive value_name in clap annotations

---

cli/src/cmd/forge/install.rs

Closes https://github.com/foundry-rs/foundry/issues/1729.
Set proper directory for `git status` command.

fix(forge/install): git status check

---

evm/Cargo.toml
evm/src/executor/fork/backend.rs

enable I/O and time drivers for thread local tokio runtime

fix: enable tokio feature on new runtime

---

Cargo.lock
anvil/Cargo.toml
anvil/src/config.rs

replace colored crate with yansi (used in other foundry crates) in anvil

chore(deps): replace colored with yansi

---

config/README.md
config/src/lib.rs

Add `allow_paths = []` setting in config
Ref #1739

feat(config): add allow paths setting

---

cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/src/forge.rs
cli/src/utils.rs
cli/tests/it/cmd.rs

Closes https://github.com/foundry-rs/foundry/issues/1747.
Add and implement a trait for `std::process::Command` to easily catch command execution errors.

fix(forge): catch command errors

---

anvil/src/eth/api.rs
anvil/tests/it/main.rs
anvil/tests/it/txpool.rs

use tx gas price like geth
unblocks https://github.com/gakonst/ethers-rs/pull/1286

fix(anvil): use tx gas price for geth txpool rpc calls

---

Cargo.lock
evm/src/executor/builder.rs

We've been getting rate limited by Infura/Alchemy, so now we instead detect 429s with the `RetryClient` and do exponential backoff.

feat(evm): use RetryClient for forking provider

---

anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs

use retry provider for the fork's provider

feat(anvil): use retry provider for fork

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs

Supports `trezor` and `ledger` as signers.
Tested successfully on `trezor`. It should work, but if anyone has a `ledger` to test, it would be nice.

feat(forge): add hardware wallet support to `forge script`

---

cli/src/cmd/forge/script/cmd.rs

fix bug highlighted in https://github.com/foundry-rs/foundry/pull/1208#discussion_r884196492

fix(forge): duplicate traces when rerunning with a new deployer on `forge script`

---

cli/src/cmd/forge/build.rs
cli/src/cmd/forge/script/mod.rs
cli/src/opts/multi_wallet.rs
common/src/evm.rs

closes: https://github.com/foundry-rs/foundry/issues/1770
- If the `visible_alias` change is alright, I'll search for more
- For the multi_wallet options, I've just made the value names plural

fix: forge script value_name and visible_alias

---

anvil/src/cmd.rs
cli/src/cmd/cast/wallet.rs
cli/src/cmd/forge/debug.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/test.rs
cli/src/cmd/forge/verify.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs

closes: https://github.com/foundry-rs/foundry/issues/1773
The aliases are not documented anywhere and so added them to help text.
If too much clutter other option would be to just include in foundry book.

fix: aliases visible in help text

---

anvil/src/eth/api.rs

style(anvil): return method not found for debug_traceTransaction

---

cli/src/utils.rs

track the location where the command is executed for better error reporting

chore: track caller when executing commands

---

cli/src/cmd/forge/init.rs
cli/src/cmd/forge/remappings.rs

Print _all_ remappings, not only autodetected, in `forge remappings`

feat(forge): include all remappings in remappings command

---

cli/tests/it/cmd.rs
cli/tests/it/config.rs
config/src/lib.rs
config/src/utils.rs

Closes #1673
if they exist, include remappings for `test` and `script` folder

feat(config): include auto remappings for test and script

---

cli/tests/it/config.rs

only check against auto-detected remappings, which doesn't have any ambiguity.

test: fix flaky remappings test

---

anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/transaction.rs

previously the `BlockNumber` argument was ignored in balance, code, nonce, storage calls
support reading from history with `BlockNumber`

feat(anvil): support historic requests for balance, storage, code, nonce

---

testdata/README.md

Fixing testdata/readme navigation

docs: testdata readme navigation fix

---

Cargo.lock
cli/src/cmd/forge/verify.rs

Blockscout explorer support PR [#1343](https://github.com/gakonst/ethers-rs/pull/1343)
Update ethers package & remove hash sign from contract URL since it's not supported by blockscout

fix(verify): update ethers & fix contract url UX 

---

fmt/src/comments.rs
fmt/src/formatter.rs
fmt/src/solang_ext/loc.rs
fmt/src/visit.rs
fmt/testdata/DocComments/fmt.sol
fmt/testdata/DocComments/original.sol
fmt/testdata/FunctionDefinition/fmt.sol
fmt/testdata/FunctionDefinitionWithComments/fmt.sol
fmt/testdata/FunctionDefinitionWithComments/original.sol
fmt/testdata/FunctionType/fmt.sol
fmt/testdata/FunctionType/original.sol
fmt/testdata/ImportDirective/bracket-spacing.fmt.sol
fmt/testdata/ImportDirective/fmt.sol
fmt/testdata/ModifierDefinition/fmt.sol
fmt/testdata/ModifierDefinition/original.sol
fmt/testdata/SimpleComments/fmt.sol
fmt/testdata/SimpleComments/original.sol
fmt/testdata/UsingDirective/fmt.sol
fmt/testdata/UsingDirective/original.sol

RE: @jpopesculian's comment on [comment](https://github.com/foundry-rs/foundry/pull/1682#issuecomment-1134930455) support PR
Use groups & format buffer for indentation

[wip] feat(fmt): format buffer groups

---

README.md

When I was reading through the `README` again I spotted some small consistencies (eg. dapptools instead of DappTools) & prettify "issues" that's why I quickly fixed those. Not my greatest contribution ofc, but I hope you agree on my suggested changes.

Prettify & `README` consistency

---

anvil/src/eth/api.rs
anvil/src/filter.rs
anvil/tests/it/abi.rs
anvil/tests/it/logs.rs
anvil/tests/it/main.rs
anvil/tests/it/transaction.rs

Closes #1823
also get historic logs when installing a new logs filter
moves event/logs related test to separate module

fix(anvil): respect historic logs in newFilter

---

anvil/src/eth/api.rs

chore(anvil): add missing filter changes info log

---

cli/src/cmd/forge/build.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/test.rs
cli/src/cmd/forge/verify.rs
config/src/lib.rs

closes: https://github.com/foundry-rs/foundry/issues/1800
Still bumbling about trying to understand where to have the logic for https://github.com/foundry-rs/foundry/blob/0e258fb191ad32db70a8a461763053990dc88789/cli/src/compile.rs#L208
Currently have it commented out in: config/src/lib.rs
Any tips appreciated!
add `--silent` flag to supress all output

feat(forge): --silent flag in CoreBuildArgs

---

cli/tests/it/cmd.rs

this should fix a flake in `can_check_snapshot` 
run test exclusively

test: run check snapshot exclusively

---

cli/src/cmd/forge/remappings.rs
config/src/lib.rs

Closes #1849
also convert / slashes in `forge remappings` command

fix(forge): use / slashes in windows remappings

---

anvil/core/src/eth/receipt.rs
anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/mem/mod.rs
cast/src/lib.rs
cli/src/opts/multi_wallet.rs

fix: clippy lint

---

anvil/tests/it/transaction.rs

Ref #1874 check `to` field is set correctly

test: add tx receipt test

---

cli/tests/it/cmd.rs
cli/tests/it/config.rs
cli/tests/it/test_cmd.rs

decrease IT time
remove `serial` for test that don't cause or are affected by side effects related to env/cwd etc.
*Note:* removing the attribute and running fmt, basically reformatted everything

test: remove uneccessary serial tests

---

fmt/src/formatter.rs
fmt/src/visit.rs
fmt/testdata/DoWhileStatement/fmt.sol
fmt/testdata/DoWhileStatement/original.sol
fmt/testdata/ForStatement/fmt.sol
fmt/testdata/ForStatement/original.sol
fmt/testdata/FunctionType/fmt.sol
fmt/testdata/StatementBlock/bracket-spacing.fmt.sol
fmt/testdata/StatementBlock/fmt.sol
fmt/testdata/WhileStatement/fmt.sol
fmt/testdata/WhileStatement/original.sol

Formatter support of `for`, `while` & `do while` statements

feat(fmt): `for`, `while` & `do while` statements

---

cli/test-utils/src/util.rs

this should get rid of a race condition where two separate tests try to install the same missing solc at the same time

test: pre install commonly used solc

---

Cargo.lock
evm/Cargo.toml
testdata/cheats/Roll.t.sol
testdata/core/ContractEnvironment.t.sol
ui/Cargo.toml

Bump revm to v1.5.0

---

anvil/src/eth/error.rs
anvil/tests/it/ganache.rs
anvil/tests/it/main.rs
anvil/tests/it/revert.rs
anvil/tests/it/transaction.rs

Closes #1871
include decoded revert reason in error message:
```console
JsonRpcError {
code: -32003,
message: "execution reverted: !authorized",
data: Some(
String(
"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b21617574686f72697a6564000000000000000000000000000000000000000000",
),
),
},
```

fix(anvil): include revert reason in error message

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/cheats.rs
anvil/tests/it/anvil_api.rs
cli/src/cmd/utils.rs

Closes #1910
* mimic hardhat's behavior in anvil_impersonateAccount 
* use a list for impersonated/unlocked accounts rather a single account that is used for transactions without from field

fix(anvil): implement impersonateAccount correctly

---

anvil/core/src/eth/mod.rs
anvil/src/eth/backend/db.rs
anvil/tests/it/anvil.rs
anvil/tests/it/fork.rs

Closes #1914
also update the code hash when setting the code

fix(anvil): update code hash on setCode

---

anvil/src/eth/api.rs

* handle revert exist reason separately to return revert error message

fix(anvil): add revert branch for error message

---

anvil/core/src/eth/block.rs
anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/src/eth/error.rs
anvil/src/eth/fees.rs
anvil/src/lib.rs
anvil/tests/it/anvil_api.rs
anvil/tests/it/fork.rs
anvil/tests/it/gas.rs
anvil/tests/it/main.rs
anvil/tests/it/transaction.rs

Closes ##1919
Contains various fixes:
* update next base fee when new block mined
* make gas price exclusive pre London
* use fork fee history if forked block requested in `eth_feeHistory`
* reset base fee on fork reset
* validate tx's fee is higher than current base fee

fix(anvil): proper eip-1559 base fee implementation

---

config/Cargo.toml

style: restructure config Cargo.toml

---

anvil/src/eth/backend/mem/storage.rs
anvil/tests/it/traces.rs

Closes #1940
check the return code for `SelfDestruct`

fix(anvil): return suicide type for selfdestruct

---

cli/src/cmd/forge/cache.rs

style: simplify chain cache

---

anvil/core/src/eth/mod.rs

Add `anvil` namespace to calls inherited from evm/ ganache
This PR closes  #1932

chore(anvil): rename evm rpcs

---

fmt/src/formatter.rs
fmt/testdata/IfStatement/fmt.sol
fmt/testdata/IfStatement/original.sol

add support for `if` statement formatting

feat(fmt): if statement

---

evm/src/executor/opts.rs

split evm env config in separate functions

refactor: split evm functions

---

anvil/core/src/eth/mod.rs
anvil/core/src/eth/serde_helpers.rs

Closes #1868
* customize BlockNumber deserialize so int values are supported

feat(anvil): support integer block numbers

---

cli/tests/fixtures/can_set_yul_optimizer.stderr

test: update yul test fixture

---

cli/src/cmd/cast/run.rs

* project aware figment/config loading

fix: use project root path for figment

---

anvil/src/eth/api.rs

use `eth_estimateGas` when determining the gas with a new accesslist

fix(anvil): estimate gas in create-accesslist correctly

---

Dockerfile

since several forge commands depend on git we should include in the image

chore: add git to docker image

---

anvil/tests/it/abi.rs
anvil/tests/it/fork.rs

Add nft test trying to reproduce #1920
~~**Blocked by https://github.com/foundry-rs/foundry/pull/1993**~~

test: add nft test

---

anvil/tests/it/anvil_api.rs

chore: remove leftover dbg

---

.github/workflows/cross-platform.yml

prevent cross platform checks from hanging in CI
try the optimized profile for cross platform checks, this will use opt-3 but less optimized than `release`
#2004 was tested with `--release` profile which took 40m to compile and another 40 to run the tests, not sure why running all tests took that long on release, could just be a runner thing...

ci: use optimized profile in cross platform checks

---

evm/src/executor/fork/backend.rs

get rid of manually dropping the guard

style: improve db locking

---

evm/src/lib.rs

docs: document CALLER

---

anvil/src/service.rs

rewrites the `NodeService` in preparation of #2018 so it can handle async block production
`Backend::mine_block` will be an async function once transitioned to tokio's sync primitives, this PR adds:
* a new Stream type `BlockProducer` that exclusively executes one `Backend::mine_block` at a time by pinning a future that takes ownership of the `Backend`
the service loop does the following:
* mine block (poll queued `Backend::mine_block` to completion)
* get ready transactions from the pool and feed them to the BlockProducer
Note: this does not make `Backend::mine_block` async yet

refactor(anvil): add block producer stream type

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/forge/watch.rs

Closes #2027
upgrade watchexec to newest release
tested manually, should still work the same

chore(deps): upgrade watchexec with breaking changes

---

Cargo.lock

~~wait for pending svm-rs fixes
ref https://github.com/roynalnaruto/svm-rs/pull/45~~
includes solc 0.8.15 fixes

chore(deps): bump ethers with svm fixes

---

anvil/src/config.rs

style: rm unused new function

---

anvil/src/eth/api.rs

nicer way to check return code

style(anvil): use revm return macros in match arms

---

anvil/tests/it/gas.rs

test custom base fee is respected

feat: add --base-fee

---

common/src/evm.rs

adds shorter alias for `block-base-fee-per-gas`

feat: add --base-fee alias

---

Cargo.lock
cli/src/cast.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/fmt.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/opts/wallet.rs
common/Cargo.toml
common/src/errors.rs
common/src/fs.rs
common/src/lib.rs

the std::io::error does not track the path that lead to the error
* add error variants for commonly used fs functions 
* add fs wrapper module

feat: add fs wrapper functions

---

fmt/src/formatter.rs
fmt/testdata/RevertStatement/fmt.sol
fmt/testdata/RevertStatement/original.sol

fmt formatting of `Statement::Revert`

feat(fmt): `revert` stmt

---

cli/src/opts/forge.rs

Closes https://github.com/foundry-rs/foundry/issues/2081
```console
➜  foundry git:(forge-cmds-help) ✗ cargo run --bin forge -- test --help | head -n 10
Finished dev [unoptimized] target(s) in 0.37s
Running `target/debug/forge test --help`
forge-test
Run the project's tests.
USAGE:
forge test [OPTIONS]
OPTIONS:
-m, --match <PATTERN>
Only run test functions matching the specified regex pattern.
```

fix(forge): clap about messages

---

Cargo.lock
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/verify.rs
cli/src/cmd/utils.rs
cli/src/opts/forge.rs

types were moved to ethers https://github.com/gakonst/ethers-rs/pull/1407

refactor: remove ContractInfo struct

---

config/src/error.rs
config/src/lib.rs

move error codes to its own module and add more warning codes

feat(config): more error codes

---

cli/src/cmd/forge/script/build.rs

Attempting to fix #2092 and #2085

fix: canonicalize script contract path

---

evm/src/coverage/visitor.rs

fix: properly detect yul if body

---

cli/src/cmd/forge/test.rs
evm/src/executor/mod.rs
forge/src/multi_runner.rs
forge/src/runner.rs

add more traces used to debug #2106

chore: add more forge traces

---

fmt/src/formatter.rs
fmt/testdata/TryStatement/fmt.sol
fmt/testdata/TryStatement/original.sol

fmt formatting of `Statement::Try`

feat(fmt): `try` stmt

---

fmt/README.md
fmt/src/formatter.rs
fmt/testdata/TernaryExpression/fmt.sol
fmt/testdata/TernaryExpression/original.sol

fmt formatting of `Expression::Ternary`

feat(fmt): ternary expression

---

anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs

some client libs (web3py) may check the last block for max gas limit
include gas limit in genesis block

fix(anvil): include gas limit in genesis block

---

cli/src/cmd/forge/script/mod.rs

Same reasons as https://github.com/foundry-rs/foundry/pull/2102 
> AddressIdentity now saves the identifier [path:contractName] on AddressIdentity.contract, instead of just the name
Since the debugger expects contract names, it was not able to get the corresponding source.
Create a map from `decoder.contracts` with contract names as keys instead.

fix(forge): get contract name from identifier before passing to the debugger

---

anvil/src/config.rs
evm/src/executor/fork/init.rs

Closes #2140
better error message

chore: improve no block found error

---

anvil/src/cmd.rs

previously we reused the clap structs from forge, however we only need a subset
roll a standalone `AnvilEvmArgs` clap struct

chore(anvil): remove unused cli arguments

---

Cargo.lock
cli/src/cmd/forge/script/receipts.rs
cli/src/utils.rs

Blocked by https://github.com/gakonst/ethers-rs/pull/1434
Closes #2166
sort receipts first

fix(script): sort transaction receipts asc

---

cli/src/cmd/forge/fmt.rs

Closes #2178
by default, fmt all project files, including test and script folder

fix(fmt): format all project sol files

---

cast/src/print_utils.rs
common/src/fmt.rs
testdata/cheats/ToString.t.sol

fix: toString() print address with checksum

---

DEBUGGING.md

A small document on some debugging tips

docs: small debugging tips doc

---

cli/assets/.gitignoreTemplate

feat: ignore anvil broadcast logs

---

cli/test-utils/src/util.rs

the preinstall apparently caused some side-effects...

chore: revert 0.8.15 preinstall

---

common/src/fmt.rs

Closes #2187
deserialize hex numbers and display them as numerics

feat(ui): try deserializing additional l2 as numbers

---

Cargo.lock
config/Cargo.toml
config/src/lib.rs

chore(deps): bump paths-slash

---

README.md

README adjustment in order to use `local` profile for installing from source (performance increase).

Use `local` profile for installing from source

---

cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/script/receipts.rs
evm/src/executor/fork/cache.rs

some smol formatting changes and typo fixes
continues merging effort for #1715

chore: formatting and typos

---

Cargo.lock
anvil/Cargo.toml
anvil/server/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
cli/Cargo.toml
evm/Cargo.toml
forge/Cargo.toml
utils/Cargo.toml

unify tokio and tracing dependencies used by most crates
continues merging of #1715

chore(deps): ease tokio and tracing dependencies

---

anvil/src/cmd.rs

allow `anvil -f "<URL>@<blocknumber"` to be compatible with ganache-cli

feat(anvil): add support for trailing fork block number

---

rust-toolchain

bumps rust version to be compatible with latest revmn changes

fix: bump rust toolchain version

---

anvil/src/config.rs

fix(anvil): use correct byzantium hardfork name

---

README.md
cli/tests/it/integration.rs

https://github.com/maple-labs/loan does not exist anymore, hence failing integration tests

chore: rm maple/loan test

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/tests/it/anvil_api.rs

Blocked by #2277 
Closes #2252
add hardfork block table and convert hardfork based on block number

feat(anvil): auto adjust hardforks by block number

---

anvil/src/config.rs

chain id needs to be `None` now initially, missed in 73e5fd2acece10aa7874ed337fe5ebf1a9ce0c77

fix(anvil): default config chain id

---

cli/src/cast.rs

See #2289
Not sure if this checks the sender early enough

cast: check that signed tx matches --from

---

config/README.md

discourage list form of `rpc_endpoints`

docs: only document preferred rpc_endpoints form

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/debug.rs
cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/verify.rs
cli/src/cmd/forge/watch.rs
cli/src/cmd/utils.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/cheatcodes/util.rs

Trying to add retry args to `forge script` for contract verification, from: https://github.com/foundry-rs/foundry/issues/2181

feat(forge) Add RetryArgs to ScriptsArgs

---

cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/receipts.rs
cli/src/cmd/forge/script/sequence.rs

add some script traces to be able to debug things like https://github.com/foundry-rs/foundry/issues/2282

chore(script): add some traces

---

common/src/fmt.rs

add missing array variants for pretty printing unknown fields of (L2) transactions/blocks

chore: add array variants for numeric pretty print

---

cli/tests/fixtures/can_test_repeatedly.stdout

latest forge-std changes apparently affected gas 
https://github.com/foundry-rs/forge-std/commits/master
updated expected gas

test: update expected gas

---

Cargo.lock
cast/src/lib.rs

Ref #2176
parse constructor and convert to function for easy encoding, since signature is not included in the output

feat(cast): support constructors in abi-encode

---

cast/src/lib.rs

misc changes while reviewing cast

misc: some cast simplifications

---

anvil/core/src/eth/receipt.rs

Implementing these traits will allow `TypedReceipt` to be encoded / decoded from RLP bytes, and allow fastrlp traits to be derived on types which contain a `TypedReceipt`.
* derive `fastrlp::Encodable` and `fastrlp::Decodable` for `Log`
* derive `fastrlp::Encodable` and `fastrlp::Decodable` for `EIP658Receipt`
* impl `fastrlp::Encodable` and `fastrlp::Decodable` for `TypedReceipt`
* test encoding and decoding a legacy receipt with data from EIP2481 test vectors

feat(anvil): impl fastrlp traits for TypedReceipt

---

config/README.md

Relative paths are now supported, so the docs should reflect that.

Update model checker config docs to use relative paths.

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs

Closes #2363
add eth_syncing, constant false

feat(anvil): add eth_syncing

---

README.md
cli/tests/it/integration.rs

fix: new solmate url

---

Cargo.lock
config/src/fmt.rs
config/src/lib.rs
fmt/Cargo.toml
fmt/README.md
fmt/src/formatter.rs
fmt/src/lib.rs
fmt/testdata/ContractDefinition/bracket-spacing.fmt.sol
fmt/testdata/EnumDefinition/bracket-spacing.fmt.sol
fmt/testdata/FunctionCallArgsStatement/fmt.sol
fmt/testdata/FunctionDefinition/fmt.sol
fmt/testdata/FunctionDefinition/modifier-single-line.fmt.sol
fmt/testdata/FunctionType/fmt.sol
fmt/testdata/ImportDirective/bracket-spacing.fmt.sol
fmt/testdata/IntTypes/fmt.sol
fmt/testdata/IntTypes/original.sol
fmt/testdata/IntTypes/preserve.fmt.sol
fmt/testdata/IntTypes/short.fmt.sol
fmt/testdata/ModifierDefinition/fmt.sol
fmt/testdata/StatementBlock/bracket-spacing.fmt.sol
fmt/testdata/StructDefinition/bracket-spacing.fmt.sol
fmt/testdata/VariableDefinition/fmt.sol

Implements configuration options for
* implicit or explicit integer types
* multiline function attributes
As well as changes test config option parsing to make it more flexible

feat(fmt): Config options low-hanging fruit

---

evm/src/trace/decoder.rs
evm/src/trace/mod.rs
evm/src/trace/node.rs
forge/src/gas_report.rs

Resolves #977
Use function signature instead of names to record calls.
> NOTE: This also changes traces, is this ok? or is there a better solution for this.

feat(forge): use signature instead of function name

---

cli/src/cmd/cast/run.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/test.rs
config/src/lib.rs
evm/src/executor/opts.rs
forge/src/multi_runner.rs

Closes #2383
Closes #2366
after #1715 cache settings were set improperly.
enable rpc caching correctly

fix: properly enable storage caching

---

anvil/src/eth/backend/mem/mod.rs

chore(anvil): add fee too low warn log

---

cli/tests/it/create.rs

this is another weird cross platform test failure that only happens on cross linux for some reason...
https://github.com/foundry-rs/foundry/runs/7415725804?check_suite_focus=true
run test in serial ref [#https://github.com/foundry-rs/foundry/pull/2392](https://github.com/foundry-rs/foundry/pull/2392)
needs a closer look at what's conflicting here...

fix: use address from dev wallet

---

config/src/lib.rs

Closes #2412
add check for offline before installing

fix: respect offline mode when checking for missing solc

---

evm/src/executor/fork/init.rs

convey reason why initiating a forked env failed

chore: improve error messages when instantiating forked env

---

Dockerfile

As per https://github.com/foundry-rs/foundry/pull/1990, git was added into docker image.
Since its multi stage build, git is found only in build-environment and not in foundry-client which user interacts.

Dockerfile: Add git to foundry-client env

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/mod.rs

perf(forge): cache backend on `forge script`

---

evm/src/executor/fork/backend.rs

Fix regression 
ref #1351 
Panic if we can't receive a valid response to `storage`, `basic` and `block_hash` requests.

fix(evm): panic if we can't successfully query fork state 

---

anvil/core/src/eth/subscription.rs
anvil/server/src/handler.rs
anvil/server/src/lib.rs
anvil/server/src/ws.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/fees.rs
anvil/src/eth/pool/mod.rs

* clean up some verbose traces, mainly due to logging entire request objects in rpc
* make it easier to identify missing rpc endpoints via error logs

chore(anvil): tracing pass

---

config/src/lib.rs

check if the source of the error was the `Toml` provider so we can include that info in the error message

chore: improve config error message

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Implementing https://github.com/foundry-rs/foundry/issues/2394
This new feature will allow to perform bitwise shifting operations from cast.

feat(cast) Add bit shifting utilities

---

evm/src/executor/fork/backend.rs

Closes #2489
don't panic if a blockhash for a block that does not exist is requested like `block.number +1000`
return empty hash, this this is equivalent to what revm returns for number > current number

fix(evm): return empty block hash if block does not exists

---

forge/src/gas_report.rs

Fixes #2431, #2287 partially (couldn't reproduce first part)
Just had to split the complete contract path to get the contract name.

feat(forge): `gas_report` satisfies config values

---

testdata/cheats/Ffi.t.sol

add another ffi example to show string output

test: add ffi string output test

---

Cargo.lock
Cargo.toml
fmt/Cargo.toml
fmt/src/comments.rs
fmt/src/formatter.rs
fmt/src/solang_ext/ast_eq.rs
fmt/src/solang_ext/loc.rs
fmt/src/visit.rs
fmt/testdata/DocComments/fmt.sol

new release of solang-parser `0.1.17`
refine doc comment handling
depends on [ethers-rs#1548](https://github.com/gakonst/ethers-rs/pull/1548)

dep(solang-parser): 0.1.17

---

cli/src/cmd/forge/test/mod.rs

add smol trace when entering with fuzz seed

chore: add fuzz seed trace

---

anvil/src/cmd.rs
anvil/tests/it/api.rs

support named chains `--chain goerli`
use `Chain` instead u64

feat(anvil): support --chain <name>

---

cli/tests/it/test_cmd.rs

add test to run `forge test` on `forge-std`
this is currently failing due to https://github.com/foundry-rs/foundry/issues/2560

test: add forge-std to integration test

---

testdata/fuzz/FuzzInt.t.sol

A follow-up to #2594 with int128 test

Fuzz: added int128 test

---

Cargo.lock
cli/Cargo.toml

some perf improvements in new releases

chore(deps): bump serial test

---

docs/dev/README.md
docs/dev/architecture.md
docs/dev/debugging.md

docs: add basic dev docs folder

---

cli/src/cmd/forge/bind.rs

Ref #2605
run `forge build` before generating bindings
* integrate `forge build` args and compile project if not skipped via `--skip-build`

feat: run forge build by default

---

Cargo.lock

Updated `svm-rs`
Updated `ethers-solc`

chore: update ethers-solc, includes latest svm-rs

---

cli/src/cmd/forge/script/receipts.rs

chore: print full transaction on failure

---

evm/src/executor/inspector/cheatcodes/ext.rs

if ffi stderr is non empty log error trace

chore: add ffi stderr trace

---

cli/src/cast.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/find_block.rs
cli/src/cmd/cast/rpc.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/receipts.rs
cli/src/opts/ethereum.rs
cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs
cli/src/utils.rs
common/src/provider.rs

Closes #2660
use `get_http_provider` from common crate

refactor: use http retry helper

---

fmt/src/formatter.rs

The last_byte_written wasn't taking into account the \r\n file endings and therefore inserting extra characters

fix(fmt): Windows disable fmt tests

---

anvil/src/eth/api.rs

mirror hardhat response for setStorageAt, which always returns true
https://github.com/NomicFoundation/hardhat/blob/c5b6ea42359b8be905bad4072c5556e9b9f43ef6/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L337-L338

fix(anvil): return true of setStorageAt

---

fmt/src/formatter.rs
fmt/testdata/StructDefinition/bracket-spacing.fmt.sol
fmt/testdata/StructDefinition/fmt.sol
fmt/testdata/StructDefinition/original.sol

fix(fmt): struct fields comment indentation

---

Cargo.lock

Update `ethers-solc` after updates in [svm-rs](https://crates.io/crates/svm-rs/0.2.15) and [svm-rs-builds](https://crates.io/crates/svm-rs-builds/0.1.7). Related to the latest push on [`solc-builds`](https://github.com/roynalnaruto/solc-builds/commit/fc7263e8b571b6a4c754d443fa4b7b4236b4735f) which includes v0.8.15 and v0.8.16 using statically linked z3 SMT solver.

chore: update ethers-rs

---

Cargo.lock
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
cli/tests/it/test_cmd.rs
evm/src/executor/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/2549
~~Blocked by https://github.com/gakonst/ethers-rs/pull/1592~~
mark deployed libs as persistent

fix: make deployed libraries persistent

---

cli/src/opts/cast.rs

https://github.com/foundry-rs/foundry/issues/2738
Offer the user guidance

fix: better cast error on large slot numbers

---

cli/assets/CounterTemplate.s.sol
cli/assets/CounterTemplate.sol
cli/assets/CounterTemplate.t.sol
cli/src/cmd/forge/init.rs

Change the defult Contract to Counter

---

evm/src/executor/backend/diagnostic.rs
forge/tests/it/fork.rs
testdata/cheats/RpcUrls.t.sol

Corrected the same typo that appeared in several places.

Fix typos in RevertDiagnostic messages and associated tests

---

cli/assets/CounterTemplate.sol

The indentation of the template code is not aligned and has been corrected.

Fix indent of template code

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Cheats.sol
testdata/cheats/ProjectRoot.t.sol

Hi, first time contributor so please let me know if anything is off.
This PR closes https://github.com/foundry-rs/foundry/issues/2719

feat(forge) add projectRoot cheat code

---

cli/src/opts/multi_wallet.rs
testdata/cheats/Cheats.sol

fix: typos

---

cli/src/cmd/forge/verify/sourcify.rs

fix(verify): remove sourcify log 

---

cli/tests/it/cast.rs

the `cast_run_succeeds` is a bit heavy.
run with `--quick` to just run the single tx

test: use cast run --quick

---

cli/src/cmd/forge/test/mod.rs

chore: fallback on reason: assertion failed

---

anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/inspector.rs
anvil/src/eth/backend/mem/mod.rs
evm/src/executor/inspector/logs.rs
evm/src/executor/inspector/tracer.rs

collect and print `console.sol` logs
add anvil `Inspector` type and print logs after transacting in the evm

feat(anvil): print console.sol logs

---

config/src/lib.rs

feat(forge): output solc metadata by default

---

evm/src/trace/identifier/etherscan.rs

fixes  #2772
after the first `InvalidApiKey` we mark it as invalid and skip further attempts

perf: track invalid etherscan key

---

docs/dev/architecture.md
docs/dev/cheatcodes.md

document how cheat codes are implemented and how to add new onse

docs: document how cheatcodes are implemented

---

cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/debug.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/mod.rs
cli/src/cmd/retry.rs
cli/src/cmd/utils.rs

misc refactoring
* derive Defaults and use `..Default::default()`
* move `Retry` to its own modules

refactor(cli): derive some defaults and extract retry

---

cli/src/cmd/forge/fmt.rs

- output warning if no files detected
- process glob args

feat(fmt): process input from globs and improve warning

---

cli/src/cmd/forge/inspect.rs

Closes #2650
list all possible values for `forge inspect <field>` in the help message

chore: include forge inspect field possible values

---

docs/dev/cheatcodes.md

docs: cheatcode docs typos

---

anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs
evm/src/executor/fork/database.rs

Closes #2837
hardhat_reset resets to latest if blockNumber is None

fix(anvil): reset to latest on none

---

cli/src/cmd/cast/wallet.rs
cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs
common/src/clap_helpers.rs
common/src/lib.rs

auto strip 0x form private key with new clap value parser

feat: add strip_0x_prefix value parser

---

Cargo.lock
Cargo.toml
cast/src/lib.rs
cli/src/cmd/forge/script/broadcast.rs

Use latest `ethers-rs::master` which depends on bumped up `svm-rs` and `svm-rs-builds`

chore: latest ethers-solc (bumped up svm versions)

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/forge/verify/sourcify.rs

feat(forge): optional verifier url

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/genesis.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/genesis.rs
anvil/src/lib.rs
anvil/tests/it/genesis.rs
anvil/tests/it/main.rs
common/src/errors.rs
common/src/fs.rs

Closes #2850
* add geth genesis bindings
* add `--init` cli arg
* apply genesis.json content

feat(anvil): support initializing via geth style genesis.json 

---

Cargo.lock

Includes https://github.com/gakonst/ethers-rs/pull/1630

chore(deps): bump ethers with reqwest retry handling

---

config/README.md
config/src/lib.rs

- The options list in the README file for configuration is out of date.
- Typo
- Update the list with reference to [/config/src/lib.rs](/config/src/lib.rs) and [/cli/tests/it/config.rs](/cli/tests/it/config.rs)
- Fix typo

Update the options list in the configuration README

---

fmt/src/formatter.rs
fmt/testdata/IfStatement/fmt.sol
fmt/testdata/OperatorExpressions/fmt.sol
fmt/testdata/OperatorExpressions/original.sol
fmt/testdata/ReturnStatement/fmt.sol

fix(forge): fmt expression postfix comments

---

evm/src/fuzz/mod.rs

closes #2848 (i know it's not assigned me, but i saw it and seemed like a low hanging fruit)
Add `counterexample` traces to `run_result` if the test fails.

fix(forge): show traces on fuzz test failure

---

Cargo.lock
binder/Cargo.toml
cast/Cargo.toml
cli/Cargo.toml
config/Cargo.toml

bumps a couple of deps to newer releases
```
cast:
Upgrading chrono v0.2 -> v0.4.22
foundry-binder:
Upgrading git2 v0.13 -> v0.15.0
foundry-cli:
Upgrading dialoguer v0.8.0 -> v0.10.2
Upgrading serial_test v0.8.0 -> v0.9.0
Upgrading comfy-table v5.0.0 -> v6.0.0
Upgrading rpassword v5.0.1 -> v7.0.0
```
there are additional crates in the UI crate that can be bumped, but those need closer inspection

chore(deps): cargo upgrade --skip-compatible

---

CONTRIBUTING.md

docs: contributing typo

---

anvil/tests/it/api.rs
anvil/tests/it/fork.rs
cli/src/cmd/cast/send.rs
config/src/lib.rs
forge/tests/it/test_helpers.rs

use the `Config::DEFAULT_SENDER` where applicable

chore: use default config sender

---

anvil/src/eth/backend/mem/cache.rs
anvil/src/genesis.rs
common/src/fs.rs

rm advanced language feature that breaks build: https://github.com/foundry-rs/foundry/runs/7985113658?check_suite_focus=true

fix: rm impl trait argument for generic function

---

config/src/error.rs
config/src/lib.rs

add dedicated error type for failed config extraction

refactor: add extract config error

---

anvil/src/eth/backend/cheats.rs
anvil/tests/it/fork.rs

some refactoring while investigating #2931
this also fixes a bug where repeated impersonateAccount calls on a contract would remove the code indefinitely

refactor(anvil): add dedicated ImpersonatedAccount type

---

Cargo.lock
cli/Cargo.toml

Closes #2873
enable reqwest's `"rustls-native-certs"` feature

feat: support native certs

---

cli/src/cmd/forge/test/mod.rs

fix `TestArgs` fuzz seed initializer

fix: test args fuzz seed

---

anvil/src/genesis.rs
anvil/src/lib.rs

Closes #2885
parse genesis.json private keys and include them in the signer set when configuring the node
cc @tynes

feat(anvil): unlock genesis.json private keys by default

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue2956.t.sol

Closes #2956
replace already loaded accounts on init

fix(forge): replace loaded account on init

---

forge/tests/it/cheats.rs

chore: exclude ffi tests on windows

---

anvil/core/src/eth/transaction/mod.rs

Previously the `to` field of the transaction was being decoded but not consumed, leading to errors such as #2965, where decoding a contract creation transaction would return the `UnexpectedString` error.
Consume the byte and add tests (examples from #2965) confirming that transactions are successfully decoded. Fixes #2965.

fix(anvil): consume tx create byte when decoding

---

evm/src/executor/backend/mod.rs

this fixing an issue that would lead to an underflow of the `depth` value of `JournaledState` if the `Backend` was launched in forking mode directly.
See docs
adjust depth when launched in forking mode

fix: adjust journaled state depth when launched in forking mode

---

.github/workflows/cross-platform.yml
cli/tests/it/script.rs
forge/tests/it/cheats.rs

Supersedes https://github.com/foundry-rs/foundry/pull/2867 (passing)
use nextest for all cross-platform tests
* port unit+integration test step from test.yml
* exclude some CPU intensive tests for integration test step

ci: use nextest for crossplatform

---

cli/src/cmd/forge/mod.rs
cli/src/cmd/forge/update.rs
cli/src/forge.rs
cli/src/opts/forge.rs

move `forge update` code to standalone update cmd module

refactor: move update cmd to submodule

---

cli/src/cmd/cast/run.rs
evm/src/executor/builder.rs
evm/src/executor/inspector/mod.rs

make note that cheatcodes are disabled in `cast run`

docs: document cast run and its evm Executor

---

config/src/lib.rs

ignores `<DAPP|FOUNDRY>_FFI` env var when constructing the `Config`, this prevents setting ffi via env vars entirely

fix(config): ignore <FOUNDRY|DAPP>_FFI env var

---

anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
anvil/tests/it/transaction.rs

add missing check that enforces the transaction was signed with the right chain id

fix(anvil): enforce matching transaction chain id

---

anvil/src/eth/backend/executor.rs

Closes #3004
only count valid transactions when computing the `transaction_index`

fix(anvil): count transaction index correctly

---

anvil/src/eth/backend/executor.rs

chore(anvil): include exit reason in logs

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
anvil/tests/it/sign.rs
anvil/tests/it/transaction.rs

implement checks for https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md for legacy transactions when validating chain id
ref https://github.com/gakonst/ethers-rs/pull/1647

fix(anvil): improve legacy chain id validation

---

cli/src/cmd/forge/script/mod.rs

previously the `ScriptArgs` wasn't a `Provider` so the `etherscan_api_key` wasn't merged into config
turn `ScriptArgs` into provider and merge etherscan key

fix(script): turn script args into provider and merge etherscan key

---

cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout

https://github.com/foundry-rs/forge-std/pull/138 added a new solidity file
update contract number in test fixtures

chore: update test fixtures

---

evm/src/executor/inspector/cheatcodes/util.rs

Closes https://github.com/foundry-rs/foundry/issues/3031
cc @odyslam

fix: use >= instead of > for private key checks

---

config/src/error.rs

* add new error code while debugging test failures

chore: add unnamed return variable error code

---

anvil/src/eth/backend/mem/mod.rs

Closes #3037
add missing predates fork checks

fix(anvil): add missing predates check

---

anvil/src/eth/backend/mem/mod.rs

https://github.com/foundry-rs/foundry/pull/3039 wasn't actually correct, as we need inclusive check since, `Latest` should be fetched via fork, hence some tests started failing

fix(anvil): use inclusive range check for fork

---

cli/tests/it/verify.rs

@joshieDo since internal deployments can take a while to be indexed we verify all CREATE transactions
tested locally

test: fix flaky live test

---

cli/src/cmd/forge/snapshot.rs

parse invariant test entries in snapshots correctly
cc @transmissions11

fix(snapshot): support invariant entry parsing

---

cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs

Adds `--mnemonic-passphrase` option to support BIP39 passphrases for mnemonic wallets.
**Security considerations:**
`--mnemonic-path` option uses path to file instead of a raw mnemonic. Not sure whether it's for convenience or security, because there is a `--private-key` option that accepts private key in raw form. So not sure whether supplying a raw passphrase in the command line is too insecure (although it's definitely very convenient for testing and tinkering).
By the way, maybe we should rename `--mnemonic-path` option to `--mnemonic`, and check if its value is a valid file path then read the file, otherwise treat it as raw mnemonic?

feat(cast): add BIP39 passphrase support to mnemonics

---

evm/src/executor/backend/mod.rs
evm/src/executor/fork/multi.rs
evm/src/executor/opts.rs
forge/src/multi_runner.rs

add more traces tracking down https://github.com/foundry-rs/foundry/issues/3016

chore: add more traces

---

cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/test/mod.rs
common/src/provider.rs
evm/src/executor/opts.rs
forge/tests/it/config.rs

Closes #3048
* improve error when instantiating a forked env failed
* auto correct missing `http` prefix for localhost urls

chore: better url parser error handling

---

evm/src/trace/identifier/signatures.rs

reading a malformed but existing signatures file resulted in this https://github.com/foundry-rs/foundry/issues/3016
make reading signatures file infallible

chore: make reading signatures cache file infallible

---

Cargo.lock
cli/Cargo.toml
cli/tests/it/main.rs
cli/tests/it/svm.rs

closes https://github.com/foundry-rs/foundry/issues/2859
add test that ensures the latest solc release exists in svm for all platforms

test: ensure latest solc is provided by svm

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/fork.rs

the `--fork-retry-backoff` cli options was not actually used
correctly configure it in the config

fix(anvil): configure backoff correctly

---

cli/src/cmd/forge/test/mod.rs
common/src/shell.rs

Closes #3001
install `Shell` in `test` command and only print failures if verbosity is normal
Note: we could also replace all println! with usage of the installed shell but handling json/silent already works with current state..

fix: comply with json mode in forge test

---

evm/src/coverage/analysis.rs
evm/src/coverage/anchors.rs

- Some if statements might emit a lot of `PUSH <x> JUMPI` bytecode (e.g. if the if statement contains specific binary conditional operators) so this fixes that by finding the last of such sequences (refer #2993)
- After fixing the previous issue I was stumped for a long time because it lead to almost no branches being covered. The issue was that the source ranges for some branches include the entirety of all "else if" statements too, so the last push-x-jumpi sequence was actually the very very last one in the last if statement. I've adjusted the source ranges accordingly in the analysis step
Closes #2993

fix(coverage): correct branch source ranges

---

anvil/server/src/ws.rs

Closes #3096
previously we only handled ws text payloads, however some impl, like web3.py apparently send messages as binary, #3096
websocket binary is the payload as-is, but does not enforce utf-8, as does text.
deserialize the request from slice instead
checked against https://github.com/foundry-rs/foundry/issues/3096#issuecomment-1238121486

fix(anvil): support binary websocket messages

---

cli/src/cmd/forge/snapshot.rs

ref https://github.com/foundry-rs/foundry/issues/2484
add `--threshold <pct>` argument to `forge snapshot`
only count as diff if they exceed the given threshold

feat: add snapshot tolerance

---

cli/src/cast.rs
cli/src/cmd/cast/call.rs
cli/src/cmd/cast/mod.rs
cli/src/opts/cast.rs

As title, now allows providing `value`, `gas` etc. to `cast call` as well as enabling `cast call --create`

feat(cast/call): allow providing more overrides

---

evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/util.rs

See https://github.com/foundry-rs/foundry/issues/3051#issuecomment-1238206416.

fix(evm): improve envVar and parseVar cheatcode error messages

---

anvil/src/eth/api.rs

Closes #3115
off by one when calculating the blockrange

fix(anvil): off by one blockcount

---

cli/src/cmd/forge/coverage.rs

add smol traces used for debugging #2915

chore: coverage traces

---

cli/src/cmd/forge/script/sequence.rs

Bug was introduced here https://github.com/foundry-rs/foundry/pull/2840/files#diff-d45dce4265aefe033e62baea9b328dade5e5ed8cbf7f8c3115535dd42e2bd298R415

fix: set correct opcode for calls

---

cast/src/base.rs
cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

ref #3125, only the first and second point in the list

feat(cast): add --to-base, radix/base parsing in base.rs

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/cmd/cast/wallet.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/sourcify.rs
cli/src/opts/cast.rs
cli/tests/it/script.rs

ref #3125, from point 3 onwards. Please make sure that I haven't overwritten any new commits since that PR

refactor(cast): subcommands

---

cli/assets/.gitignoreTemplate
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/sequence.rs

feat(forge): save non-broadcasted script runs under `dry-run` folder 

---

fmt/src/formatter.rs
fmt/src/solang_ext/ast_eq.rs
fmt/testdata/TrailingComma/fmt.sol
fmt/testdata/TrailingComma/original.sol

fix(forge): fmt lenient parameter list commas

---

cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/script/verify.rs
cli/src/cmd/forge/verify/mod.rs

feat(forge): script verifier opts

---

evm/src/executor/inspector/cheatcodes/util.rs

Closes #3197
support non 0x prefixed hex
use another "parse as hex" attempt if parsing as decimal string resulted in an error

fix: support non prefixed hex

---

cli/src/cmd/forge/verify/mod.rs

close #3199. when the verify args construct a project, it has no knowledge about the optimizer settings being passed as cli args and falls back to defaults
https://github.com/foundry-rs/foundry/blob/433be903a02be0e49c37deacd4f3fe4d71b4c97c/cli/src/cmd/forge/verify/etherscan.rs#L178
fix the `figment::Provider` implementation for `VerifyArgs`

fix(verify): provider impl for `VerifyArgs`

---

cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/forge/verify/provider.rs
cli/src/cmd/forge/verify/sourcify.rs

Ref https://github.com/foundry-rs/foundry/issues/3209
improve error message, include payload
* extract provider, move separate module
* include etherscan payload in error message

chore(verify): extract provider and better error

---

cli/src/cmd/forge/script/transaction.rs

better error message with info for debugging

chore: improve failed constructor args decoding error

---

cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/snapshot.rs
cli/src/cmd/forge/test/mod.rs
cli/tests/it/cmd.rs

Closes #3204
better auto install of missing dependencies for forge build+test
* extract install function
* better tracing
* reconfigure config/project if missing dep was installed so remappings are also updated
* added tests for build+test

feat: auto install missing dependencies on test

---

forge/tests/it/cheats.rs
forge/tests/it/config.rs
forge/tests/it/fork.rs
forge/tests/it/fs.rs
forge/tests/it/repros.rs
forge/tests/it/test_helpers.rs

get rid of some boilerplate test code by adding a `TestConfig` struct

refactor: simplify forge testing

---

evm/src/executor/inspector/cheatcodes/ext.rs

ref https://github.com/foundry-rs/foundry/issues/3207
better error handling
serde parses ints larger than `u64::MAX` as floats: `Number(1.8446744073709552e19)` > u64::MAX
perhaps we should try parse these cases as `U256::from_dec_str(value.to_string)` instead?

fix: handle parse json errors

---

evm/src/executor/inspector/cheatcodes/fork.rs
forge/tests/it/config.rs
forge/tests/it/repros.rs
testdata/repros/Issue3223.sol

#3223 
set nonce as corrected before selecting a fork

fix(forge): set nonce as corrected before selecting a fork

---

Cargo.lock

contains infura retry fix https://github.com/gakonst/ethers-rs/pull/1706

chore(deps): bump ethers with infura retry for header not found

---

Cargo.lock
evm/Cargo.toml
evm/src/executor/fork/cache.rs

use correct cache model when deserializing rpc state

fix: deserialize cache correctly

---

fmt/src/formatter.rs
fmt/testdata/SimpleComments/fmt.sol
fmt/testdata/SimpleComments/original.sol

ref #3184 
lookup mapping syntax unit locations

fix(forge): fmt mapping comment location

---

cli/src/cmd/forge/geiger/visitor.rs
config/src/fmt.rs
fmt/src/formatter.rs
fmt/src/visit.rs
fmt/testdata/IfStatement/block-multi.fmt.sol
fmt/testdata/IfStatement/block-single.fmt.sol
fmt/testdata/IfStatement/fmt.sol
fmt/testdata/IfStatement/original.sol
fmt/testdata/OperatorExpressions/fmt.sol
fmt/testdata/ReturnStatement/fmt.sol
fmt/testdata/WhileStatement/block-multi.fmt.sol
fmt/testdata/WhileStatement/block-single.fmt.sol
fmt/testdata/WhileStatement/original.sol

feat(forge): fmt single line blocks option

---

cli/src/cmd/forge/snapshot.rs

Closes #3246
ignore new tests in snapshot diff

fix: ignore new tests in snapshot

---

cli/src/cmd/forge/script/mod.rs
common/src/errors/artifacts.rs
common/src/errors/fs.rs
common/src/errors/mod.rs

ref https://github.com/foundry-rs/foundry/issues/3242
don't panic and add a new error type for unlinked code

chore: add unlinked bytecode error

---

fmt/src/formatter.rs
fmt/testdata/SimpleComments/fmt.sol
fmt/testdata/SimpleComments/original.sol

fix(forge): fmt eof comment

---

cli/src/cmd/forge/script/broadcast.rs

feat(script): add total fee

---

anvil/src/cmd.rs
anvil/src/config.rs

include default ipc path in help message

chore(anvil): include default ipc path in help

---

Cargo.lock
Cargo.toml

chore(deps): rm svm-rs patch

---

Cargo.toml
forge/src/multi_runner.rs

https://github.com/foundry-rs/foundry/issues/3267

fix(forge): source_paths for debugger should be absolute

---

Cargo.lock

contains revm changes and ethers chain id fixes

chore(deps): bump ethers revm

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/fees.rs

Closes #3307
Add a simple `eth_maxPriorityFeePerGas` implementation
Ref https://github.com/ethereum/go-ethereum/issues/23125#issuecomment-872077530

feat(anvil): implement eth_maxPriorityFeePerGas

---

anvil/src/cmd.rs

chore(anvil): add --tracing alias

---

fmt/src/formatter.rs
fmt/testdata/DocComments/fmt.sol
fmt/testdata/DocComments/original.sol

ref https://github.com/foundry-rs/foundry/issues/3184#issuecomment-1251679340
cc @mds1

fix(fmt): loosely preserve doc comment indent

---

cli/assets/CounterTemplate.t.sol

https://github.com/foundry-rs/foundry/blob/61e472ab87949c032b37334de0bf52c46487c31e/cli/assets/CounterTemplate.t.sol is not formatted.
`forge fmt`

forge fmt CounterTemplate.t.sol

---

Cargo.lock
Cargo.toml
anvil/core/Cargo.toml
evm/Cargo.toml
ui/Cargo.toml

Bumping revm to crates version

bump revm to v2.1.0

---

cast/src/errors.rs
cast/src/lib.rs
cast/src/tx.rs

Closes #3340
* remove panic
* better error message
* suggest `withdraw()` if only `withdraw` is provided

chore(cast): improve invalid signature error

---

cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/send.rs
cli/src/cmd/cast/wallet/vanity.rs
cli/src/cmd/forge/cache.rs
cli/src/cmd/forge/fmt.rs
cli/src/cmd/forge/geiger/mod.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/snapshot.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/forge/watch.rs
cli/src/cmd/retry.rs
cli/src/cmd/utils.rs
cli/src/opts/cast.rs
cli/src/opts/chain.rs
cli/src/opts/transaction.rs
common/src/evm.rs

update deprecated clap features to prepare for clap 0.4.0 https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating

chore: upgrade deprecated clap usage

---

config/src/lib.rs

Closes #3359
previously we tried to find a matching alias in the rpc_url table if `eth_rpc_url || etherscan_api_key` were set to an alias, like `mumbai`.
This fixes a bug where the fallback was also `eth_rpc_url || etherscan_api_key`, this resulted in `rpc_url = etherscan_api_key` if `etherscan_api_key` was set but not `eth_rpc_url`...
only use `eth_rpc_url` as fallback

fix: only consider eth_rpc_url if no alias

---

cli/src/cmd/cast/run.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/test/mod.rs
evm/src/trace/identifier/signatures.rs

Closes #3355
Closes #3354
only fetch signatures via API if !offline: `--offline` flag

fix: respect --offline in signatures identifier

---

anvil/src/cmd.rs
anvil/src/config.rs

Closes #3232
make code size limit configurable.

feat(anvil): make code size limit configurable

---

cli/src/cmd/forge/fmt.rs
config/src/fmt.rs

feat(forge): fmt ignore paths

---

cli/src/cmd/forge/build/filter.rs
cli/src/cmd/forge/build/mod.rs

ref https://github.com/foundry-rs/foundry/pull/3370#discussion_r980627083
cc @mds1 
this will also be nicer since you should be able to use shell autocomplete for test,script folder names here

chore: support test,tests and script,scripts as aliases

---

cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/provider.rs
cli/src/cmd/forge/verify/sourcify.rs
cli/tests/it/utils.rs
cli/tests/it/verify.rs

some verify test maintenance and add another arbitrum-goerli test
example verification on blockscout: https://goerli-rollup-explorer.arbitrum.io/address/0xd8509bEE9C9BF012282ad33ABa0d87241bAf5064
ref https://github.com/foundry-rs/foundry/issues/3331

test: update verify test and add arbitrum-goerli

---

evm/src/trace/identifier/signatures.rs

precaution to ensure cache dir is created

chore: ensure chain signatures cache dir is created

---

fmt/src/formatter.rs
fmt/testdata/VariableAssignment/bracket-spacing.fmt.sol

fix(fmt): remove spacing for square brackets 

---

Cargo.lock
cli/tests/it/cmd.rs
common/src/compile.rs

~~Blocked by https://github.com/gakonst/ethers-rs/pull/1752~~
always check all contracts (compiled+cached) if `--sizes`, `--names` is provided

fix: always consider all contracts

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectRevert.t.sol

feat: make ExpectRevert0 accept any revert

---

Cargo.lock
anvil/tests/it/sign.rs

~~Blocked by https://github.com/gakonst/ethers-rs/pull/1756~~
~~Blocked by #3395~~
Closes https://github.com/foundry-rs/foundry/issues/3409
bumps ethers and add another test

fix: decode chain id correctly in typeddata

---

Cargo.lock
cast/src/lib.rs
common/src/abi.rs
evm/src/trace/identifier/etherscan.rs
utils/src/abi.rs

Closes https://github.com/foundry-rs/foundry/issues/3416
use new `raw_abi` function
cc @DaniPopes

fix(cast): use new raw abi api

---

cli/src/opts/dependency.rs

Support github org URLs as dependency, like `"org-git12345678@github.com:my-org/my-repo.git"`
ref https://github.com/foundry-rs/foundry/issues/3321

fix: parse github org-urls

---

common/src/compile.rs

Forgot to parse raw `compiler_version` from etherscan
@mattsse  maybe we should be handling this in `Solc::find_svm_installed_version` instead of just taking in any `AsRef<str>`?

fix: etherscan project version

---

cli/src/cast.rs

fix(cast): max int

---

utils/src/lib.rs

ref https://github.com/foundry-rs/foundry/issues/3442
improve panic message and add traces.
the linking step is a bit hard to understand. 
let's keep the panics for now...

chore: better panic and traces in linking step

---

anvil/tests/it/fork.rs
utils/src/rpc.rs

chore: remove tests for rinkeby

---

cli/src/cmd/forge/test/mod.rs

silence second compiler invocation for the debugger

chore(debug): silence compiler

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/cmd/cast/find_block.rs
cli/src/cmd/cast/rpc.rs
cli/src/cmd/cast/run.rs
cli/src/opts/cast.rs
cli/src/utils.rs

cast tx/receipt/run exit with status 0 with no output when the hash is not found (eg tx from goerli but using mainnet rpc-url, tx dropped from mempool or other errors are just ignored)
also clean up logic in cast tx,receipt with no breaking changes (tx and receipts were printed with sorted keys when using `--json`)

chore(cast): better error handling

---

cli/src/cmd/cast/run.rs

better error instead unwrap
ref https://github.com/foundry-rs/foundry/issues/3486

chore: replace unwrap with error

---

anvil/src/eth/backend/db.rs
anvil/src/eth/backend/mem/fork_db.rs
anvil/src/eth/backend/mem/in_memory_db.rs
anvil/src/eth/backend/mem/mod.rs

ref #3478
clear database on `anvil_reset`

fix(anvil): clear db on reset

---

cli/src/cmd/utils.rs

should close https://github.com/foundry-rs/foundry/issues/3487
new ArbitrumGoerli has a different chain id

fix: check for arbitrum goerli

---

config/src/fmt.rs
fmt/src/formatter.rs
fmt/testdata/VariableDefinition/original.sol
fmt/testdata/VariableDefinition/override-space.fmt.sol

close #3522
add `variable_override_spacing` to `[fmt]` config

feat(fmt): variable override spacing option

---

cli/src/cmd/forge/fourbyte.rs

Be able to upload all function and event selectors to https://sig.eth.samczsun.com/ without specifying contracts one by one.
Upload all non-test function and event selectors to https://sig.eth.samczsun.com/ when `--all` argument is specified.
Upload just for one contract (behaves as before):
```console
➜  contracts git:(main) ✗ ~/Projects/foundry/target/debug/forge upload-selectors TransferSystem
Uploading selectors for TransferSystem...
Duplicated: Function execute(bytes): 0x09c5eabe
Duplicated: Function executeTyped(uint256,uint256): 0x915657fb
Duplicated: Function owner(): 0x8da5cb5b
Selectors successfully uploaded to https://sig.eth.samczsun.com
```
Upload for every non-test contract in the project:
```console
➜  contracts git:(main) ✗ ~/Projects/foundry/target/debug/forge …
```

feat(forge): upload-selectors --all

---

anvil/src/lib.rs
forge/tests/it/config.rs

closes #3530 + extra clippy warning

fix: warnings

---

anvil/tests/it/pubsub.rs

ref https://github.com/foundry-rs/foundry/issues/3537
@krasi-georgiev tried to reproduce this but no didn't encounter missed blocks.
any way to reliably reproduce this?

test(anvil): add block subscription test

---

cli/src/cmd/forge/script/broadcast.rs

replace custom error with eyre and wrap all errors, this should provide more context for gas estimation error: https://github.com/foundry-rs/foundry/issues/2941

refactor: use eyre Error for gas estimation

---

cli/src/cmd/forge/script/broadcast.rs

Ref: https://github.com/foundry-rs/foundry/issues/2941
this ensures the gas field is removed before estimating gas via `estimateGas`

fix(forge): rm already set gas field before estimating gas

---

anvil/src/eth/backend/mem/mod.rs

removes recursive lock that has been added when we encountered some deadlocks that were caused by the sync lock on the `Database` that have since been resolved.

chore(anvil): replace recursive lock with plain lock

---

cast/src/lib.rs

Gnosis mainnet and Chiado testnet
Adding Gnosis mainnet and Chiado testnet genesis hashes
- https://github.com/gakonst/ethers-rs/pull/1809
- https://github.com/gakonst/ethers-rs/pull/1811

Adding gnosis and chiado

---

cli/src/opts/cast.rs

add test used to debug https://github.com/foundry-rs/foundry/issues/3532

chore: add arg parse test

---

cli/src/cmd/forge/verify/etherscan.rs

The `"Contract successfully verified"` output was removed in #3569 
this adds it back with additional traces.

chore: update verify output

---

cli/src/cmd/forge/verify/etherscan.rs

set trace target and dedicated std json trace.

chore: improve verify traces

---

Cargo.lock
evm/Cargo.toml
evm/src/trace/identifier/local.rs

close #3582 
Select the best match instead of first

fix(trace): local contract identification

---

cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout
cli/tests/fixtures/can_test_repeatedly.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
cli/tests/it/test_cmd.rs

update tests after forge-std was bumped

chore: update tests after forge-std 1.0.0

---

fmt/src/inline_config.rs
fmt/testdata/InlineDisable/fmt.sol
fmt/testdata/InlineDisable/original.sol

close #3572 
Add `disable-line` inline config item.
@mds1 could you pls open a separate issue for parsing inline config items within comment content? feel like we need to discuss pros & cons there

feat(fmt): disable line config

---

.gitignore
anvil/Cargo.toml
anvil/core/Cargo.toml
anvil/core/src/eth/block.rs
anvil/core/src/eth/mod.rs
anvil/core/src/eth/receipt.rs
anvil/core/src/eth/serde_helpers.rs
anvil/core/src/eth/state.rs
anvil/core/src/eth/subscription.rs
anvil/core/src/eth/transaction/mod.rs
anvil/core/src/types.rs

feat: add serde feature flag to anvil-core

---

cli/src/cmd/forge/coverage.rs

`forge build` and `forge test` automatically install missing dependencies, but `forge coverage` doesn't
Mirror the implementations used by build/test. One difference is that those had this:
```rust
// need to re-configure here to also catch additional remappings
config = self.load_config();
project = config.project()?;
```
but here we'd immediately reassign `project` so I left out the `config.project()?` line since it didn't seem needed, unless it has some side effects that we need?

feat: install missing deps on 'forge coverage'

---

forge/tests/it/repros.rs
testdata/repros/Issue3616.t.sol

Add test replicating #3616
Instead of failing this will ensure the that balance exists.

test: add test for preexisting balance

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/mod.rs
cli/test-utils/src/script.rs
cli/tests/it/script.rs
cli/tests/it/test_cmd.rs

Closes #3609 
adds `--unlocked` flag for `forge script` for sending via `eth_sendTransaction`
@mds1 could you please try this

feat(script): add --unlocked flag

---

anvil/src/eth/api.rs

Anvil is always calling to fork provider during eth_getTransactionByHash and eth_getTransactionReceipt in case of pending transaction, this is a big overhead in such case
Related to issue: https://github.com/foundry-rs/foundry/issues/3605
Change order in case of eth_getTransactionByHash and add check for pending transaction in case of eth_getTransactionReceipt

Reduce calls to fork provider

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/receipts.rs
cli/src/cmd/utils.rs

chore: bump indicatif

---

cli/src/cmd/retry.rs

increase delay and retries a bit.

chore: bump retry defaults

---

config/src/lib.rs

close #3633 
give preference to explicitly provided `chain` parameter in `get_etherscan_config_with_chain`

fix(config): etherscan chain resolution

---

cli/src/cmd/forge/script/cmd.rs

ref #3646 
replace expect with error

chore: convert panic into error

---

testdata/repros/Issue2956.t.sol
testdata/repros/Issue3221.sol

some flaky forking tests, likely related to how accounts are fetched.

chore: rotate infura keys in test

---

cli/src/cmd/forge/inspect.rs
cli/tests/it/cmd.rs

add test for `forge instepct Counter irOptimized` and some traces.

test: add forge inspect irOptimized test

---

testdata/repros/Issue3223.sol

chore: rotate another flaky infura key

---

common/src/abi.rs

Closes #3657
Improve error when failed to parse token

chore: improve parsing error

---

evm/src/executor/inspector/cheatcodes/mod.rs

Apply cleanup only on the root level

fix: do revert cleanup only at test call level

---

evm/src/executor/inspector/cheatcodes/ext.rs

fix: writeJson should pretty print the Json

---

anvil/src/eth/api.rs

Closes #3700
Add missing `predates_fork` checks for:
* getBalance
* getStorage

fix(anvil): add missing predates fork handlers

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
anvil/tests/it/fork.rs
anvil/tests/it/geth.rs
anvil/tests/it/transaction.rs

Closes #3658
Add missing check for at least 21_000 gas limit

fix(anvil): add gas too low check

---

Dockerfile

Follow-up for https://github.com/foundry-rs/foundry/pull/3727 (sorry). I think we can also cache the cargo target dir. If we do that, we have to copy the built binaries out so they can later be retrieved in the second build stage. But it further speeds up the build.

chore: cache cargo build in docker

---

cli/src/cmd/cast/wallet/mod.rs

Closes #3721
makes it easier to pipe the output of `cast wallet address`

chore: drop Address: prefix for output

---

evm/src/trace/decoder.rs

close #3724 
Properly identify `receive` functions during trace decoding

fix(trace): `receive` decoding

---

anvil/src/eth/api.rs

Closes #3718
adds missing fork check for tx count.

fix(anvil): add missing fork check for tx count

---

Cargo.lock
cast/src/base.rs
evm/Cargo.toml

blocked by https://github.com/gakonst/ethers-rs/pull/1885

chore(deps): bump ethers + revm

---

cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/test/mod.rs
evm/src/trace/decoder.rs
evm/src/trace/node.rs
evm/src/trace/utils.rs

ext cheatcodes can get very very verbose in tracing
Enable tracing for these cheatcodes only for debug-level=5, otherwise hide.

feat: support verbosity levels in tracing decode

---

cli/src/cmd/forge/install.rs
cli/tests/it/cmd.rs

Closes #3733
when taking a dir argument the `current_dir` for the git command was not set correctly.

fix: set current dir to root

---

cli/src/opts/wallet/mod.rs

trim_end instead of \n which is not the same across platforms

chore: trim end

---

evm/src/error.rs
testdata/cheats/File.t.sol

chore: make ERROR_PREFIX 4 bytes long

---

cli/src/cmd/forge/script/mod.rs
evm/src/executor/inspector/tracer.rs
evm/src/trace/identifier/etherscan.rs
evm/src/trace/identifier/local.rs
evm/src/trace/identifier/mod.rs
evm/src/trace/mod.rs

Closes #3767
use `Bytes` which serializes via hex

fix: use hex encoding for raw data

---

fmt/src/solang_ext/ast_eq.rs

chore(fmt): remove dbg & unsafe block

---

evm/src/trace/mod.rs

This is a proposed fix for #3787  
Geth Traces are now constructed by interleaving the traces from various depth levels. This allows interoperability with other tools.
I do not know Rust, so please feel free to critique or suggest changes. Also, if you have good ideas on which tests to add, I could add some. I manually tested it against different contracts.
As described in #3787 the geth traces currently do not reflect the order of execution. This fix is supposed to change that.
The fix recursively combines the different traces into one big trace. Whenever a call is observed, it decends into the child trace.

Fixed Geth Traces

---

testdata/repros/Issue3703.t.sol

Add dedicated polygon alchemy key

chore: add dedicated polygon key

---

cli/test-utils/src/util.rs

don't mark version as installed if there's an error, this should improve flaky cross-tests in as they can be flaky due to file format issues.

test: reinstall on error

---

anvil/src/config.rs
anvil/src/eth/backend/time.rs
binder/src/utils.rs
cast/src/errors.rs
cli/src/cast.rs
cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/utils.rs
cli/tests/it/cmd.rs
cli/tests/it/svm.rs
common/src/abi.rs
config/src/lib.rs
evm/src/executor/backend/diagnostic.rs
evm/src/executor/inspector/cheatcodes/config.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/fuzz/invariant/executor.rs
evm/src/trace/decoder.rs
forge/tests/it/config.rs
forge/tests/it/core.rs
ui/src/lib.rs
utils/src/abi.rs

new clippy fixes 
clippy --fix

chore: clippy fixes

---

.github/workflows/release.yml

Pin ubuntu for linux intel release build ref https://github.com/foundry-rs/foundry/issues/3827

ci: pin ubuntu in release job

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

ci: pin all runners ubuntu 20.04

---

anvil/src/cmd.rs

Closes #3849
unify `with_init_state` calls with a merged `Option`

fix(anvil): unify load state options

---

cli/tests/it/verify.rs

the last tx in verify test can be a bit flaky at times

chore: losen tx count requirement

---

.github/workflows/release.yml

ci: include chisel in release

---

chisel/Cargo.toml

use rustls to fix release build
https://github.com/foundry-rs/foundry/actions/runs/3661653858/jobs/6190056830

fix: disable default reqwest features

---

foundryup/foundryup

nit: update foundryup messaging to include chisel 

---

.github/scripts/prune-prereleases.js

See #3881.
Skip pruning releases created on the first day of the month.

Permanent monthly releases

---

chisel/src/dispatcher.rs

I was getting unexpected "Contract is not verified!" errors when trying to use the !fetch feature. Turns out I had an old API key set as an environment variable and Etherscan was actually complaining about that. But the current error handling interprets any non-JSON `result` value as the contract not being verified.
Etherscan responds `status` == "1" if it was successful, so check for that instead. When `status` != "1", then the `result` field contains a human readable error. So report that if it's present.
Now we get the expected "Invalid API Key" or "Max rate limit reached..." message which makes it clear why it's failing.

fix(chisel): improve Etherscan API error handling

---

cli/src/cmd/forge/script/multi.rs
cli/src/cmd/forge/script/sequence.rs

fix(forge): give proper error when resuming with no previous deployment

---

evm/src/executor/fork/backend.rs

chore: rm redundant block_in_place

---

cli/src/cast.rs
cli/src/opts/cast.rs

Adds `cast sig-event` 
Fix #3926

feat(cast): Generate event signatures from event string

---

anvil/src/eth/backend/mem/mod.rs

Ref #3894
`TimeManager::reset` sets both the start and last timestamp to the same value, however we have 
```rust
if next_timestamp <= last_timestamp {
next_timestamp = last_timestamp + 1;
} 
```
so that the timestamp always increases by one which likely cause the issue raised in #3894
subtract -1 when resetting the timestamp

fix(anvil): off-by one on evm_revert timestamp

---

.github/workflows/cross-platform.yml

pin wsl ubuntu version to fix install issue

ci: pin wsl ubuntu

---

anvil/Cargo.toml
cli/Cargo.toml

force ethers rustls feature, ref #3946
likely related recent ethers pr https://github.com/gakonst/ethers-rs/pull/1961

chore: force rustls feature

---

cli/src/cmd/forge/script/runner.rs

closes #3953
`fs_commit_changed` was previously there for when we executed the script multiple times and avoid writing/modifying  files multiple times.
Since we do not re-execute the script anymore, this needs to go since it's disabling the `fs` operations on the first run

fix(forge): remove fs_commit_changed logic from script

---

cli/tests/it/cast.rs

failing live test
https://t.me/foundry_rs/24463

fix: cast storage live test

---

.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml

meta: add chisel to bug/feature form

---

chisel/src/executor.rs

Fixes an issue where chisel would not map the final statement's program counter correctly if the `run()` function ended in a scoped block (`assembly`, `unchecked`, or a regular `{}`)
@transmissions11 pointed out this bug in #3964 
Chisel's `executor` uses solc's source map to map the REPL contract's source code to program counters within the deployed runtime code. Adds some extra logic that checks if the final statement of `run()` is a block of some kind, finds its last statement, and uses its source location to determine the program counter that the `ChiselInspector` should take a state snapshot at.
closes #3964

fix(chisel): Map PCs correctly if `run()` ends in a scoped block

---

.github/workflows/cross-platform.yml
.github/workflows/test.yml

ci: fix windows wsl installation

---

.github/workflows/test.yml

ci: run cross platform tests only on push

---

.github/workflows/test.yml

Fix cross platform if check #4028
cc @DaniPopes

fix(ci): cross platform if check

---

anvil/core/Cargo.toml
anvil/core/src/eth/mod.rs
anvil/core/src/types.rs

Closes #4040
support hex arguments

feat(anvil): support evm_mine hex args

---

anvil/core/src/types.rs

adhere to the serde feature and put all serde derives behind cfg_attr

fix(anvil): use cfg_attr for serde derives

---

deny.toml

ignore advisory for time crate used by chrono crate for functions not used https://rustsec.org/advisories/RUSTSEC-2020-0071

ci: ignore time crate advisory

---

cli/src/cmd/forge/fmt/find.rs

chore: remove empty fmt file

---

.github/workflows/deny.yml
Cargo.lock
evm/Cargo.toml

Deny check is failing for cli's `openssl` feature as expected.
Disable default `--all-features` on the deny action

fix(ci): deny feature check

---

foundryup/foundryup

- Foundry Setup Script could use a banner with some important information
- Many CLI tools usually have a banner with some art 
1. Addition of simple foundry banner with description and useful links 
2. Monochrome , no ansi escape codes used , this adds bloat to the file size

🔨 Add banner with description and links

---

doc/src/parser/comment.rs

chore: rustfmt

---

cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout

chore: update test fixtures after forge-std release

---

evm/src/trace/identifier/etherscan.rs

Ref #4117 improve error message and include contract+address

chore: better etherscan compile error message

---

Cargo.lock
cli/Cargo.toml
cli/src/utils.rs

replace unmaintained `dotenv` with `dotenvy`: https://github.com/allan2/dotenvy a 
> well maintained fork of dotenv

chore(deps): replace dotenv with dotenvy

---

cli/src/cmd/forge/script/broadcast.rs

To view estimated gas price after running forge script
This pr simply adds a print statement.
Fixes #4064

Add gas price estimate in forge script summary

---

cli/src/cmd/forge/verify/etherscan/mod.rs

Closes #4150
we wrongly configured the `api` URL for `browser_url` URL as well, resulting in wrong address paths.
Use the `browser_url` of the config

fix(verify): configure correct etherscan base url

---

Cargo.lock
doc/Cargo.toml
doc/src/parser/comment.rs
doc/src/parser/mod.rs

chore(forge): doc ignore invalid natspec tags
