foundry-rs/foundry

.github/workflows/ci.yml, Cargo.toml, GreetTest.sol, src/bin/dapp.rs, src/dapp.rs, src/lib.rs
* can call the vm directly w/ solidity(can deploy & interact)
* can follow the dapptools pattern for writing solidity only tests
=> feat: add test runner

Cargo.toml, FooTest.sol, FooTest2.sol, GreetTest.sol, src/dapp.rs
* if a version is not detected locally and is in your contracts, it automatically gets downloaded for you
* it groups contracts by compiler and proceeds to execute them all together
=> feat: support multiple compiler versions

README.md
If users try to build/check the project with an older version of rust, it will fail due to this error: `error[E0658]: use of unstable library feature 'map_into_keys_values'`.
It is fixed with `rustup update`
=> Inform users to update in case of error [E0658]

README.md, dapptools/src/seth.rs, seth/src/lib.rs
Adds support for
* `seth resolve-name`
* `seth lookup-address`
* `seth balance`
Makes `seth call`, `seth balance` and `seth send` accept ENS names (they auto-resolve them internally).
Finally, makes the singleton commands work with `stdin` so that they compose, e.g. you can do `seth
=> feat: ens & balance

Cargo.lock, dapp/src/lib.rs
There seems to be a race condition the first time the compilers are installed which makes later running the compilation step fail with:
```
Installing 0.7.6
Done!
thread 'tests::failing_solidity_unit_test' panicked at '`"/home/runner/.svm/0.7.6/solc-0.7.6"` not found', /home/runner/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/64294d1/ethers-core/src/utils/solc.rs:240:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is fixed by running the compilation step _once_ and then re-using the value across tests.
I wonder why this is happening. Possibly due to some overwrite inside [install](https://github.com/roynalnaruto/svm-rs/blob/master/src/lib.rs#L96) when called multiple times in parallel?
=> test: share compilation step to avoid race condition

Cargo.lock, FooTest.sol, README.md, dapp/Cargo.toml, dapp/src/lib.rs, dapp/src/solc.rs, dapptools/src/dapp.rs
DS-Test uses the pattern seen in `FooTest.sol` where a `failed()` method is called at the end of calls on test contracts to get their status, in case there was a failure. This is useful when you want to make multiple assertions in 1 test.
Corresponding HEVM Code: https://github.com/dapphub/dapptools/blob/74a54da1dc77fe71eab5d8b93ed3f63904f151a1/src/hevm/src/EVM/UnitTest.hs#L197-L213
=> test: allow DS-Test-style failures with assertEq

dapptools/Cargo.toml
Noticed that the docs for the libraries were getting overwritten by the less useful docs for the binaries.
=> Fix docs generation for libraries

Cargo.lock, dapptools/src/seth.rs, dapptools/src/seth_opts.rs, seth/Cargo.toml, seth/src/lib.rs
Adds more Seth commands:
- 425b884 `seth: --to-fix`
- 072670a `seth block-number`
- 08a856a `seth basefee`
- 5470aad `seth chain-id`
- 91000f7 `seth age`
- 734ae41 `seth namehash`
- a2b43af `seth keccak`
- 8efb216 `seth gas-price`
- b6b5953 `seth chain`
- 3314129 `seth --to-wei`
- 4cf8b59 `seth --to-uint256`
- 4364e44 `seth --to-dec`
- fb310df `seth --to-ascii`
=> WIP feat: Seth command parity pt. 1

dapptools/src/seth.rs, dapptools/src/seth_opts.rs, seth/src/lib.rs
dapptools' `seth` allows arbitrarily large numbers for most commands. I don't think we need to support those but we should at least offer the full uint256 range instead of just uint128.
This PR adjusts the currently available seth commands to use U256 instead of u128
=> use U256 instead of u128 for seth helpers

Cargo.lock, ForkTest.sol, dapptools/src/dapp.rs, dapptools/src/dapp_opts.rs, evm-adapters/Cargo.toml, evm-adapters/src/blocking_provider.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/forked_backend.rs, evm-adapters/src/sputnik/mod.rs, evm-adapters/testdata/GreetTest.sol
Allows sputnik to fork state over RPC via any ethers-rs compatible `Middleware`. This means we can run our tests against mainnet / testnet state!
Follow-up work should generalize the provider to instead be possible to work w/ Geth's leveldb etc. This'd work by first extracting the `BlockingProvider`'s calls to a trait, and then implementing that trait.
The CLI allows passing in fork params as below:
```
cargo r --bin dapp test --contracts './ForkTest.sol' --fork-url https://mainnet.infura.io/v3/c60b0bb42f8a4c6481ecd229eddaca27 --fork-block-number 13292582               
```
Forking code modified from @brockelmore's https://github.com/brockelmore/rust-cevm/blob/35cdefb760d41197ccfadc8c446343f20eba9080/src/backend/fork_memory_owned.rs
Part of #25
=> feat: forked rpc provider for SputnikEVM

Cargo.lock, Cargo.toml, dapp/Cargo.toml, dapp/GreetTest.sol, dapp/src/fuzz.rs, dapp/src/lib.rs, dapp/src/multi_runner.rs, dapp/src/runner.rs, dapptools/Cargo.toml, dapptools/src/dapp.rs, evm-adapters/Cargo.toml, evm-adapters/src/blocking_provider.rs, evm-adapters/src/evmodin.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/forked_backend.rs
Closes https://github.com/gakonst/dapptools-rs/issues/16
Introduces fuzzing of solidity test functions with >0 arguments, using the [`proptest`](https://github.com/AltSysrq/proptest) library.
This is done in 2 parts:
1. Defining the fuzzing rules in `fuzz.rs` which basically says "take in an ABI type and generate a fuzzing strategy for it" and then "combine all fuzzing strategies for a certain function to a strategy for fuzzing the function's calldata"
2. Changing `runner.rs` to execute proptest's `TestRunner` if >0 inputs are detected for the current function. 
A requirement of fuzzing was to make the EVM cloneable, since the TestRunner only accepts `Fn`s which cannot mutate their environment, meaning that we had to add a `Clone` restriction on it in the fuzzing-related code. 
(To …
=> feat: fuzzing 

Cargo.lock, Cargo.toml, dapp/src/multi_runner.rs, dapp/src/runner.rs, dapptools/src/dapp.rs, solc/src/lib.rs
Add a temp interior mutability hack until fuzzing is parallelized that doesn't require patches with Clone support.
`RefCell` alone would be sufficient but the `Rc` ensures we don't do anything stupid with this like threading.
=> feat: drop Evm Clone restrictions

solc/src/lib.rs
These need to be updated with every new `solc` release as stated in:
https://github.com/gakonst/dapptools-rs/blob/a189319d233b6a180a6f1c8cb607c33d93a2f382/solc/src/lib.rs#L368-L371
=> fix(tests): update tests to work with `solc` version 0.8.9

utils/src/lib.rs
Noticed this wasn't supported when playing around with seth. Perhaps this should be upstreamed to ethers-rs? Not sure if this should be tested somewhere? New to rust so any feedback appreciated!
=> feat(seth): support 0x prefixed hex args

dapp/src/artifacts.rs, dapp/src/multi_runner.rs
* add `DapptoolsArtifact::read`
* `contract` -> `into_contracts`
* use `BTreeMap` internally in DapptoolsArtifact, could eventually do the same for `solc` so we use `BTreeMap`, but not sure if the solc output has even deterministic order.
=> chore: add artifact convenience read and change contracts fn

dapptools/src/seth.rs, dapptools/src/seth_opts.rs, seth/src/lib.rs
* Add `seth --to-hexdata`
* Add `seth calldata`
The calldata subcommand is not fully on par with OG calldata and lacks proper support for arrays
Also we should think about extracting all subcommand logic to separate modules so that we can test them idividually.
=> feat: add seth --to-hexdata seth calldata

dapp/Cargo.toml, solc/Cargo.toml, solc/src/lib.rs
* Due to usage of just `#[cfg(test)]`, the lock is not used when solc is imported as a 3rd party package. We need to enable the lock via a feature flag so that it actually gets hit.
* Adds the lock inside a non thread-safe test
* Removes the `versions` field and makes all functions immutable by default, to avoid downloading solc's which are downloaded by other instances of the solc builder.
Closes #49, related to https://github.com/gakonst/dapptools-rs/pull/76
Huge thank you to @roynalnaruto for identifying the fixes in https://github.com/gakonst/dapptools-rs/pull/83/commits/00cb8dfe091bb360dfc3283d5520177e47d50e04 and https://github.com/gakonst/dapptools-rs/pull/83/commits/ce94c39c63ed368fdc7e22700fb84174734febdf
=> fix: Solc flaky tests

Cargo.lock, dapp/src/multi_runner.rs, dapp/src/runner.rs, dapptools/src/dapp.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/testdata/CheatCodes.sol, evm-adapters/testdata/DsTest.sol
Apparently because we were doing `borrow_mut()` on the test runner, some tests would not run. This was quite weird to see. 
This test fixes it, as well as adds fuzzing tests usinga both `require` and ds-test style `assertEq`, and resets fuzz test state before a test runs.
This sets our testing infra up for adding any remaining cheat codes.
Note: It'd be nice if we can reset state w/o requiring these large clones. The state diff approach should fix it.
=> fix fuzzer bugs

Cargo.lock, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol
Self-explanatory, `hevm.store` to override storage slots, `hevm.load` to load the value in them
=> feat: store / load cheatcodes

README.md, dapp/GreetTest.sol, dapp/src/multi_runner.rs, dapp/src/runner.rs, dapptools/src/dapp.rs, dapptools/src/dapp_opts.rs, dapptools/src/utils.rs, evm-adapters/src/evmodin.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/evm.rs
This PR Does a few things:
1. bump gas limit by default to u64::MAX
2. allow contracts to be over 24kb
3. when testing, only deploy contracts with 0 constructor arguments and if they have a function that matches`test.*`
4. adds a bunch of extra tracing so that we can make sense of what's going on: `RUST_LOG=dapp=trace,evm_adapters=trace cargo run -- ...`
5. returns a proper error when deployment fails
Here's an example of how tracing looks like now when used with [LootLoose](https://github.com/gakonst/lootloose/)
=> fix: make test suite more robust

dapptools/src/dapp.rs, dapptools/src/dapp_opts.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol, utils/src/lib.rs
* Adds a `ffi(string[])` which allows calling shell commands on the host
* Since this can be used for RCE e.g. if you download a phished test suite, we add a `--ffi` command on the CLI for enabling it explicitly
=> feat: ffi cheatcode

dapptools/src/dapp.rs, evm-adapters/src/sputnik/forked_backend/rpc.rs, solc/src/lib.rs
Was getting `thread 'main' panicked at 'could not transfer funds: OutOfFund'` when I tried to run tests with `fork-url` set otherwise. Based on https://github.com/gakonst/dapptools-rs/pull/92 it seems like `ForkedMemoryBackend` will be replaced soon anyway, so maybe better to do an even more basic stopgap in the meantime?
=> fix(evm-adapters): init forked backend cache with local state

seth/src/lib.rs
Optimism performed a regenesis which updated the genesis
blockhashes for both mainnet and kovan. For `seth chain` and
any other `seth` commands that rely on `seth chain` to work,
the hardcoded genesis blockhashes need to be updated.
The values were fetched using the following commands:
```
$ seth --rpc-url https://mainnet.optimism.io block 0 hash
0x7ca38a1916c42007829c55e69d3e9a73265554b586a499015373241b8a3fa48b
$ seth --rpc-url https://kovan.optimism.io block 0 hash
0x02adc9b449ff5f2467b8c674ece7ff9b21319d76c4ad62a67a70d552655927e5
```
Tested locally with the commands:
```
$ ./target/debug/seth chain --rpc-url https://mainnet.optimism.io
optimism-mainnet
$ ./target/debug/seth chain --rpc-url https://kovan.optimism.io
optimism-kovan
```
PR in `dapphub/dapptools` - …
=> seth: update optimism genesis blockhashes

evm-adapters/src/sputnik/forked_backend/rpc.rs
Actually caches storage 
+ no unused get_account vars 
+ fix bug if we get a basic account from provider but ignore the code and then check if it exists but we hadn't stored the code so we think there is no code for that contract
=> fix provider caching

Cargo.lock, dapp/Cargo.toml, dapptools/Cargo.toml, evm-adapters/Cargo.toml, evm-adapters/src/blocking_provider.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/src/sputnik/mod.rs
i tried to use Executor in async app, these are my hacks to make it work with at least multi-threaded executor.
=> feat(evm-adapters): make Executor work in already running tokio runtime

dapp/src/multi_runner.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/testdata/CheatCodes.sol
Overrides the `transact_create` so that it uses our internal runtime which leverages the cheatcodes.
=> fix: enable cheatcodes in the constructor

dapptools/src/seth.rs, dapptools/src/seth_opts.rs, seth/src/lib.rs
Resolves https://github.com/gakonst/dapptools-rs/issues/143
```console
➜  dapptools-rs git:(feat/piped-input) ✗ echo 'Foundry' | ./target/debug/seth --from-ascii                                 
0x466f756e647279
➜  dapptools-rs git:(feat/piped-input) ✗ echo '0x466f756e647279' | ./target/debug/seth --to-ascii                    
Foundry
➜  dapptools-rs git:(feat/piped-input) ✗ echo '0x466f756e647279' | ./target/debug/seth --to-bytes32                                   
0x466f756e64727900000000000000000000000000000000000000000000000000
➜  dapptools-rs git:(feat/piped-input) ✗ echo '466f756e647279' | ./target/debug/seth --to-hexdata
0x466f756e647279
➜  dapptools-rs git:(feat/piped-input) ✗ echo '0xb7e390864a90b7b923c9f9310c6f98aafe43f707' | ./target/debug/seth --to-checksum-address …
```
=> feat(seth): improve piped input support

dapptools/src/dapp_opts.rs
Solc wasn't compiling library contracts outside of `root` for me w.o. this. Lmk if there's anything i'm missing. 
EDIT: WIP, going to confirm this soon
EDIT 2: ok, updated the change a bit
=> fix(dapptools): explicitly set lib_paths as allowed paths

README.md, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol
deal: sets an address's balance
spoof: perform a call to another address from a different address, 
i.e. current tx.origin && msg.sender == address(1) -> hevm.spoof(address(2), address(3), bytes([0000]) calls address(3) from address(2) with the bytes data. note this changes tx.origin. some debate could be had as to if thats the correct functionality. I believe it is
this is WIP as there are some issues rn and no tests
=> deal + prank cheat codes

assets/ContractTemplate.sol, assets/ContractTemplate.t.sol, cli/src/forge.rs, cli/src/forge_opts.rs
Adds a new CLI command, `init` (alias `forge i`)
`forge init`: If no args are provided, it instantiates an empty project inside the current directory.
`forge init ./my-repo`: instantiates an empty project at `./my-repo`
`forge init ./my-repo --template https://github.com/transmissions11/dapptools-template/`: clones dapptols-template at `./my-repo
=> feat(cli): forge init

cli/src/forge.rs
Replaces the installation logic with `std::command::Command` calls, libgit2 is too low of an API to not shoot yourself in the foot with
=> fix(cli): install with Command vs libgit2

Cargo.lock, evm-adapters/src/evmodin.rs
This fixes the breaking change in evmodin from https://github.com/vorot93/evmodin/commit/767c310aba2e9f8e303af852915ae7a3afc010a2. The tests fail still because we don't have a contract-deployment-enabled host.
If we want proper Evmodin support, we'll need to do something like this repo: https://github.com/guanqun/ethers-forked-evm-provider. This however [copy-pastes a lot of code](https://github.com/guanqun/ethers-forked-evm-provider/tree/master/src/akula) from [Akula](https://github.com/akula-bft/akula) which uses nightly. 
So if we don't want to become a nightly-only project, we'd want to:
1. Refactor Akula's code in non-nightly crates
2. Import Akula's types and most importantly the [opcode eloop](https://github.com/guanqun/ethers-forked-evm-provider/blob/master/src/akula/evm.rs#L293-L5 …
=> evmodin: update and fix breaking changes

Cargo.lock, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
bump ethers and fix latest ethers breaking changes regard Bytes/Vec<u8>
close #171
=> chore: cargo update ethers

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/testdata/ConsoleLogs.sol
Ensures that our own `call_inner` function gets hooked in on nested calls as well
=> fix: emit console.log events on nested calls

forge/src/multi_runner.rs, forge/src/runner.rs, forge/testdata/GreetTest.sol
As title, previously we'd not print the result of functions with the same name (yikes)
=> fix: key tests hashmap by function signature (not name)

.gitmodules
```console
➜  ~ cargo install --git https://github.com/gakonst/foundry --bin forge --locked
Updating git repository `https://github.com/gakonst/foundry`
Updating git submodule `https://github.com/hexonaut/guni-lev/`
error: failed to update submodule `integration-tests/testdata/guni-lev`
Caused by:
failed to fetch submodule `integration-tests/testdata/guni-lev` from https://github.com/hexonaut/guni-lev/
Caused by:
process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/hexonaut/guni-lev/' 'refs/heads/*:refs/remotes/origin/*' 'HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
--- stderr
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
=> chore: fix repo url in .gitmodules

Cargo.lock, Cargo.toml
The compilation broke because the feature was merged upstream and @gakonst deleted the `feat/auto-impl` branch in his fork. This PR removes the patch from Cargo.
=> Use official package for rust-blockchain

Cargo.lock, cli/src/forge.rs, cli/src/forge_opts.rs, cli/src/utils.rs
`remove_dir_all` throws if path does not exists.
only remove them if they exist
Builds  off of #195 to use ethers-solc `project.cleanup`
=> fix(forge): only cleanup dirs if they exists

cli/src/forge.rs
makes it easier to initialize new projects inside a monorepo
=> feat(forge): dont init repo inside existing repo

Cargo.lock, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/forked_backend/rpc.rs, forge/src/multi_runner.rs, forge/src/runner.rs
updates ethers and adds a new check in the multi runner that skips artifacts (libs) that don't have a valid bytecode like lib artifacts (bin = "0x") or unlinked
~~This should probably wait until https://github.com/gakonst/ethers-rs/pull/665 got merged~~
=> chore(deps): bump ethers

cast/src/lib.rs
Adds avalanche mainnet and testnet
mainnet:
https://snowtrace.io/block/0
fuji:
https://testnet.snowtrace.io/block/0
https://testnet.snowtrace.io/block/1
mainnet:
`ETH_RPC_URL=https://api.avax.network/ext/bc/C/rpc cargo run --bin cast chain`
fuji:
`ETH_RPC_URL=https://api.avax-test.network/ext/bc/C/rpc cargo run --bin cast chain`
=> feat(cast): add avalanche and fuji genesis hashes

Cargo.lock, cli/Cargo.toml, cli/src/cast.rs, cli/src/forge.rs
Adds color-eyre crate and initializers to get nicer backtraces from errors that will show you the line number the error originated on.
=> Add color-eyre for automatic line-number backtraces

cli/src/cast_opts.rs
`_` vs `-` were causing clap-rs to panic if some requirements were not met, instead of giving a proper error:
```
ETH_FROM=$ADDR cargo run --bin cast -- send  $ADDR "get()"
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:475:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix(cli): replace underscore for hyphen on wallet cli args

cli/src/cmd/build.rs, cli/src/cmd/test.rs, cli/src/utils.rs
* move TryFrom<BuildArgs> to separate function
* add `--hardhat` flag as shortcut for `--contracts contracts --lib-paths node_modules`
* autodetect workspace layout:
* dapptools style takes precedent, but if `src` / `out` are missing, check for `contracts` and `artifacts` as well
=> perf(forge): improve workspace path autodection

cli/src/cmd/build.rs, cli/src/cmd/test.rs, cli/src/utils.rs
supersedes https://github.com/gakonst/foundry/pull/203
fixes https://github.com/gakonst/foundry/issues/202
also removes duplicate type `EvmVersion`
=> fix: pass through evm version

cast/README.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/cast_opts.rs
=> Add the max_uint subcommand to cast and cli

Cargo.lock, cast/Cargo.toml, cli/src/cast.rs, cli/src/cast_opts.rs
+ bumps ethers
+ enables the trezor feature from ethers-signers
+ adds `--hd-path` for custom derivation paths on hardware wallets
https://github.com/gakonst/ethers-rs/issues/592 this will probably make things less... verbose
`ETH_FROM=$ADDR ETH_RPC_URL=$RPC cargo run --bin cast -- send  $ADDR "totalSupply() returns uint256" -t`
`ETH_FROM=$ADDR ETH_RPC_URL=$RPC cargo run --bin cast -- send  $ADDR "totalSupply() returns uint256" -t --hd-path "m/44'/60'/0'/0" `
=> feat(cast): add trezor signer

Cargo.lock, cli/src/cmd/snapshot.rs, cli/src/cmd/test.rs, evm-adapters/Cargo.toml, evm-adapters/src/fuzz.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/evm.rs, forge/src/lib.rs, forge/src/multi_runner.rs, forge/src/runner.rs
* introduce `TestKind{Standard, Fuzz}`, `Fuzz` stores all test cases (input, gas used)
* `gas_used` doesn't need to be an Option anymore
* updated snapshot output, Should diff compare fuzz cases as well? because there is a high chance, median or mean differ by +-1 or so
Fuzz gas formatting as `(μ: <mean_gas>, ~: <median gas>)`
=> feat: add median and mean gas to fuzz test result

Cargo.lock, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol, forge/README.md
Adds `expectRevert` cheatcode, allowing you do to something like:
```solidity
interface Vm {
function expectRevert(bytes calldata) external;
}
contract Foo {
function bar(uint256 a) public returns (uint256) {
require(a < 100, "My expected revert string");
return a;
}
}
contract MyTest {
Vm vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
function testBarExpectedRevert() public {
vm.expectRevert("My expected revert string");
// This would fail *if* we didnt expect revert. Since we expect the revert,
// it doesn't, unless the revert string is wrong.
foo.bar(101);
}
function testFailBar() public {
// this call would revert, causing this test to pass
foo.bar(101);
}
function testBar() public {
// this test would *fail*
foo.bar(101);
}
}
```
=> feat(forge): Expect Revert cheatcode

cast/src/lib.rs, cli/src/cast.rs, cli/src/cast_opts.rs
Tested by running both `seth code 0x00000000219ab540356cbb839cbe05303d7705fa` and `cargo run --bin cast code --rpc-url $RPC_URL 0x00000000219ab540356cbb839cbe05303d7705fa` and validated that the outputs were equal via diffchecker.
Feedback regarding implementation is welcome as I'm a Rust n00b and if there is more to be desired around test coverage, happy to update accordingly.
=> feat: add code to cast

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol
*BREAKING CHANGE*
Improves the `prank` cheatcode by following the `expectRevert` model of prepare -> call
```solidity
interface Vm {
function prank(address) external;
}
contract Foo {
function bar(address expectedMsgSender) public {
require(msg.sender == expectedMsgSender, "bad prank");
}
}
contract MyTest {
Vm vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
function testBar() public {
vm.prank(address(1337));
foo.bar(address(1337));
foo.bar(address(this));
}
}
```
=> feat(forge): better prank

evm-adapters/src/fuzz.rs
When the first fuzz test fails, no test cases get added and we panic in the mean gas calculation.
=> fix(forge): empty fuzz cases panic

README.md
Dependencies section includes a quick note about the `libudev-dev` requirement. I decided to put it in its own section rather than below the installation example since I think this is a dependency of both Forge and Cargo, and didn't want to have to repeat it in both places.
=> chore: add dependencies section to readme

cli/src/forge.rs
Fix for #231. Now `init` will only `git add/commit` when it creates a new repo.
=> fix(forge): no longer git commit on init when in an existing git repo

cast/README.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
This commit ports the `seth tx` command to `cast`.
It follows the implementation of `cast block` and includes
the feature to print a specific field in the transaction
as well as printing the result in JSON.
```
$ cast tx --rpc-url <url> <tx-hash> [field]
```
The flag `-j`/`--json` is used to print the result
as JSON.
A whitespace is in a docstring is removed (autoformatted on save) and
the `cast` `README` is updated to indicate that the `tx` command was
implemented. Also check off the `code` command as it was previously
implemented.
Open to any stylistic feedback as I'm gaining experience writing Rust :)
The added doctest passes when I run it locally.
=> feat(cast): add tx command

cast/src/lib.rs
After this commit, the return value of `cast call`
will be still be printed even if the ABI type of the
return value is not specified. This matches the
behavior of `seth`.
Example:
```
$ cast call 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D 'WETH()(address)'
0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
$ cast call 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D 'WETH()'
0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
```
Previously, the second command above would print nothing as there
would be no decoded values to iterate over when building the
string output.
This commit also prepends a `0x` to each decoded return type,
which matches the behavior of `seth`.
=> fix(cast): call deserialization

cast/README.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
One thing I was not sure about here was how to handle the default behavior when a unit string is not supplied. In dapptools, it defaults to ether, however this is not consistent with the behavior of both dapptools and foundry for --to-wei, which defaults to wei when no unit string is supplied. I chose to make it default to wei, but can change it to ether if that is preferred.
=> feat: add cast --from-wei

Cargo.lock, cast/src/lib.rs, cli/src/cmd/build.rs, cli/src/forge.rs
Companion for https://github.com/gakonst/ethers-rs/pull/707 to use newer remappings, BLOCKED until merged and updated.
Tested against #221:
=> chore: bump ethers with latest remappings

.github/workflows/unit-tests.yml, Cargo.lock, README.md, cli/Cargo.toml, cli/src/cmd/test.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
Fixes #229:
1. by removing the OpenSSL requirement and using Rustls as the TLS backend.
2. by only conditionally enabling Sha2 assembly instructions (which were not available in other platforms)
3. skips unit test for FFI on windows since that command (`echo`) does not exist on windows
ref:
https://github.com/gakonst/ethers-rs/pull/703
https://github.com/roynalnaruto/svm-rs/pull/11
supersedes https://github.com/gakonst/foundry/pull/218
=> fix: cross-platform build

.gitignore, Makefile, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Tested by validating that both of the following commands output the same number on Ethereum mainnet (521):
- `seth nonce 0x7eD52863829AB99354F3a0503A622e82AcD5F7d3`
- `cargo run --bin cast nonce --rpc-url $RPC_URL 0x7eD52863829AB99354F3a0503A622e82AcD5F7d3`
Also added a few commands to the Makefile which I find helpful for local development. Happy to axe if unnecessary or move into a separate PR if that would be preferred.
=> feat: add nonce to cast

.github/workflows/cross-platform.yml, .github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, Cargo.lock
..by updating ethers-rs to the new ledger/trezor impls which are built on [`rusb`](https://github.com/a1ien/rusb) since https://github.com/joshieDo/rust-trezor-api/pull/2 and https://github.com/summa-tx/bitcoins-rs/pull/90 
it's shown to work by removing the libudev installation steps in CI
=> fix: remove libudev requirement

Cargo.lock, cli/Cargo.toml, cli/src/forge.rs, cli/src/utils.rs
as title - replaces them with native calls to `git`, removes the need to `apt install pkg-config libssl-dev`
=> chore: remove libgit2 / last openssl deps

cli/src/forge.rs
I was seeing the error `git: 'rev-parse,--is-inside-work-tree' is not a git command. See 'git --help'.` when running `forge init`. This should fix it.
=> fix git args

evm-adapters/src/fuzz.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/mod.rs, forge/src/multi_runner.rs, forge/src/runner.rs
Was quite annoying and repetitive and error prone before. This helper function saves us from a lot of pain.
=> tests: use helper fns to instantiate the EVMs

cli/src/cmd/create.rs
Previously, you could only `forge create path/Contract.sol:ContractName`, and if you did `forge create ContractName` it'd panic the first time it runs because there's no such artifact in the cache yet.
With this PR you can just `forge create ContractName`, and if there's 2 with the same ones it proceeds to error out and ask you to provide the full path
=> fix: `forge create Contract`

evm-adapters/src/call_tracing.rs, evm-adapters/testdata/CheatCodes.sol, utils/src/lib.rs
Tries to decode `expectRevert` input data to string or builtin revert codes to match revert output
=> feat(forge): Decode expectRevert in call traces

cli/src/forge.rs
Closes #303 
removes `tracing::instrument` annotation from the main function as the error will be printed anyways.
This gets rid of the duplicated error log, with `#[tracing::instrument(err)]` the error would by printed by forge and also by the tracing subscriber since the error message is logged in the `ERROR` target as well.
=> chore(forge): remove tracing instrument of main

Cargo.lock, cast/Cargo.toml, cast/README.md, cast/src/lib.rs, cli/Cargo.toml, cli/src/cast.rs, cli/src/opts/cast.rs, cli/src/utils.rs
- min-int 
- abi-decode (combines `seth abi-decode` and `seth calldata-decode` into a single command)
=> feat: cast abi-decode, min-int

cli/src/cmd/test.rs
Verbosity == 3: Trace prints for failed tests
Verbosity >= 3: `setUp` trace prints for `failed` tests
Verbosity >   3: Trace prints for all tests
Verbosity >   4: Trace prints for all tests & setUps
This is more inline with dapptools
=> Verbosity changes

cli/src/forge.rs, cli/src/opts/forge.rs
followed instructions from [this SO post](https://stackoverflow.com/questions/55937975/can-i-uninitialize-a-git-submodule) for removing a git submodule from a project. similar structure as the `install()` function. considered naming it `uninstall` but `-u` is already taken so went with `remove`
tested locally with `ds-math`, was able to install, remove, then install again no issues
=> add `remove` command to remove a library from git submodules

cli/src/cmd/mod.rs, cli/src/cmd/run.rs, cli/src/forge.rs, cli/src/opts/forge.rs
supersedes #314, adds `forge run` which will run a contract as a script. defaults to the `run()` function by default, but one can specify a custom function signature in their script if they want. all cheatcodes are enabled, and forking is supported with the standard `--fork-url`  cli arg
Example:
```solidity
pragma solidity ^0.7.6;
interface ERC20 {
function balanceOf(address) external view returns (uint256);
function deposit() payable external;
}
interface VM {
function startPrank(address) external;
}
contract C {
ERC20 weth = ERC20(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
VM constant vm  = VM(address(bytes20(uint160(uint256(keccak256('hevm cheat code'))))));
address who = 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045;
event log_uint(uint256);
function run() external {
// impersonate …
```
=> feat: `forge run`

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol
Closes #310 
This works by grabbing the next emitted event. You specify if you want to match against topics 1-3 and the data in the call. You can expect multiple events by repeatedly doing `vm.expectEvent` then emitting an event prior to a call. After the call, if the expected events are found, it continues execution. Otherwise, if the expected logs aren't found, it reverts.
```solidity
interface Vm {
function expectEmit(bool,bool,bool,bool) external;
}
contract T is DSTest {
Vm vm = Vm(HEVM_ADDRESS);
event Transfer(address indexed from,address indexed to, uint256 amount);
function testExpectEmit() public {
ExpectEmit emitter = new ExpectEmit();
// check topic 1, topic 2, and data are the same as the following emitted event
hevm.expectEmit(true,true,false,true);
emit …
```
=> feat(forge): Add `expectEmit` cheatcode

forge/README.md
I and several others have been confused about failing imports and the need for remappings. In this PR I added a remappings explainer to the forge readme.
=> updated forge readme with remapping explainer

cli/src/cast.rs, cli/src/opts/cast.rs, cli/src/opts/mod.rs
re-uses the `EthereumOpts` which are already supporting all hw wallets / mnemonics etc, and adds `--interactive` for inserting secrets w/o leaking them in the terminal.
This is a bit ugly, but does the job, until we can make the `Signer` object safe. Alternatively, we should create a simple `Signer` enum and impl `Signer` for it.
=> feat: hw support for `cast wallet`

forge/src/runner.rs
Otherwise we may start over from dirty state from a previous unit or fuzz test
and that can break test isolation
this is a follow up PR from https://github.com/gakonst/foundry/pull/226 / https://github.com/gakonst/foundry/issues/225, since the original PRs did not fix the issue with fuzz tests
This was detected in this repo https://github.com/zangGallery/testing/tree/2804d19db0fec7657ae4a0e64fbb2ce808b4354d
=> fix(fuzz): ensure the state is reset to the original before fuzz tests

cast/src/lib.rs, utils/src/lib.rs
To be more compatible with seth call behavior (and more convenient)
+ input address can start with 0x
+ output for uint/int is decimal by default
P.S. just started with rust, sorry for poor or dumb idioms
=> Add some seth compatibility for call with input/output types

cli/src/cast.rs, cli/src/utils.rs, evm-adapters/src/call_tracing.rs, forge/src/runner.rs, utils/src/lib.rs
* we deduplicate our pretty printing functions and now re-use the one from call tracing. 
* using that, we now properly print counterexamples (instead of using the `Token`'s `Debug` impl)
cc @mds1 regarding the formatting issue from #353, now it looks like below (and ints are printed properly, manually tested)
```
[FAIL. Counterexample: calldata=0xe49066450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, "", 0]] testBarFuzzed(uint256,string,uint256) (runs: 0, μ: 0, ~: 0)
```
=> fix: counterexample display

evm-adapters/testdata/CheatCodes.sol
The `vm.sign` cheat code returns data as `(v,r,s)`, not `(r,v,s)` as currently documented
=> chore: fix `vm.sign` comment

cli/src/opts/mod.rs
The CLI description for send is incorrect, it's [the docstring for the Wallet struct](https://github.com/gakonst/foundry/blob/3e8c9979e2b8836fccdb16e10be9a21862a9c81a/cli/src/opts/mod.rs#L87). You can see this by running `cast help send`.
I thought https://github.com/gakonst/foundry/pull/369 introduced the issue, but it seems that there is an [open bug](https://github.com/TeXitoi/structopt/issues/333) in `structopt` that [0cc47662aab7ba4475996c141b9e1d8e64df84f4](https://github.com/gakonst/foundry/commit/0cc47662aab7ba4475996c141b9e1d8e64df84f4) ran into.
This PR implements the [workaround](https://github.com/TeXitoi/structopt/issues/333#issuecomment-712265332) from that issue. If this isn't a good solution, it looks like there might also be a way around by using `clap` directly to …
=> fix(cast): use correct description for send

cli/src/opts/mod.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, forge/src/runner.rs
we weren't using the correct init state for fuzz tests
=> fix(forge): fuzz state reset

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/ConsoleLogs.sol
`console.logInt` is not currently working. This test fails with:
```
left: `["String", "1245", "true"]`,
right: `["String", "1337", "1245", "true"]`
```
=> [Bug] Hardhat console does not log ints

cli/src/opts/forge.rs
Ref #338 cc @wilsoncusack 
I tried to enable `from_occurrences` mode, however this mutually excludes `--verbosity <num>` which is a breaking change
personally, I'd prefer `-vvv` over `--verbosity 3`
maybe we can reduce the levels so that we start with what's now 3, and `-vvv` would be the highest verbosity mode @brockelmore @gakonst
=> feat(forge): use from_occurences for verbosity

Cargo.lock, cli/Cargo.toml, cli/src/cast.rs, cli/src/cmd/build.rs, cli/src/cmd/mod.rs, cli/src/forge.rs
Fixes both https://github.com/gakonst/foundry/issues/378 and https://github.com/gakonst/foundry/issues/360
It changes the output mapping from:
```sh
$ forge remappings
ds-test/=\\?\C:\Users\foo Bar\Projects\zerosnacks\foobar\lib\ds-test\src/
```
to:
```sh
$ forge remappings
ds-test/=C:\Users\foo Bar\Projects\zerosnacks\foobar\lib\ds-test\src/
```
allowing the automatic remapping to work correctly.
=> Use dunce::canonicalize instead of std canonicalize

cli/README.md
It is quite common to have a `remappings.txt` file in DappTools projects but this always required some extra bash scripting to work.
An example can be found here: https://github.com/gakonst/dapptools-template/blob/master/remappings.txt
=> Add note that `remappings.txt` option exists to override automatic remappings

cli/src/opts/mod.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, forge/src/runner.rs
Reverts gakonst/foundry#377
Turns out the Solmate test failure was a false positive. The issue is in dapptools, which doesn't test for 0-length arrays. Forge tests for 0-length ones, which cause the Solmate test to fail (below we see the failing test case):
```solidity
function testFailSafeBatchTransferInsufficientBalanceZeroLen() public {
ERC1155User from = new ERC1155User(token);
uint256[] memory ids = new uint256[](0);
uint256[] memory mintAmounts = new uint256[](0);
uint256[] memory transferAmounts = new uint256[](0);
token.batchMint(address(from), ids, mintAmounts, "");
from.setApprovalForAll(address(this), true);
token.safeBatchTransferFrom(address(from), address(0xBEEF), ids, transferAmounts, "");
}
```
=> Revert "fix(forge): fuzz state reset"

cli/src/cast.rs, cli/src/cmd/create.rs, cli/src/opts/cast.rs, cli/src/opts/mod.rs
Saw this so I thought I'd give it a shot: https://twitter.com/gakonst/status/1478463108100366339.
Sadly, I am missing something with how `structopt` works, since the output is messed up:
```
cast-send 0.1.0
The wallet options can either be: 1. Ledger 2. Trezor 3. Mnemonic (via file path) 4. Keystore (via file path) 5. Private
Key (cleartext in CLI) 6. Private Key (interactively via secure prompt)
USAGE:
cast send [FLAGS] [OPTIONS] <to> <sig> --rpc-url <rpc-url> [args]...
FLAGS:
--flashbots      use the flashbots RPC URL
-h, --help           Prints help information
-i, --interactive    Interactive prompt to insert your private key
```
If you have any thoughts let me know, figured I'd push this up while I try to figure it out.
EDIT: I had a stale cast binary when I started, just bisected …
=> feat(cast): add --flashbots to use flashbots rpc url

cli/src/cmd/test.rs, forge/src/lib.rs, forge/src/multi_runner.rs, forge/src/runner.rs
From issue: #227 
This PR deprecates `forge test --match` and expands the match interface to 
`--match-test`
`--no-match-test`
`--match-contract`
`--no-match-contract`
to allow for more granular test matching.
Internally, test runners have `Regex` replaced with `trait/impl TestFilter` to allow for custom matching logic in client code.
Conflicts have been added between `--match` and the new options to prevent mix/match of these. However, `--match` is effectively aliased to `--match-test` so there are no breaking changes.
Affected tests have been updated.
Any / all input welcome.
=> Expand `forge test --match` interface

Cargo.lock, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs, utils/Cargo.toml, utils/src/lib.rs
In `cast send` and `cast estimate`, if you now just provide the function name, the ABI is fetched from etherscan to encode the calldata. This method was originally proposed in #334
Example usage:
`cast send $DAI transfer ncitron.eth 100`
=> feat(cast): allow sending using just function name

cli/src/forge.rs
Forge update is currently not pulling upstream changes from submodules. Adding the `--remote` flag fixes the issue. More info can be found in the [submodule documentation](https://git-scm.com/book/en/v2/Git-Tools-Submodules).
Tested with my on project and works as expected after the change
=> [Bug] Forge update not pulling upstream changes from submodules

forge/src/runner.rs
Closes #332 
Works by grabbed the failed counterexample bytes, enabling tracing, and doing a raw call. Tested against failing fuzz test in solmate
=> feat(forge): Add fuzz tracing on fail and correct verbosity

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/testdata/CheatCodes.sol
We weren't handling prepare -> create cheatcodes. This now matches the prepare -> call cheatcodes functionality
fixes https://github.com/gakonst/foundry/issues/362
=> fix(forge): prepare -> create cheatcodes work

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs, cli/src/opts/mod.rs
Using the addressbook from #397 , now we can do:
```
cast call dai totalSupply
8927554231883212873269706303
```
```
cast call dai balanceOf 0xd8da6bf26964af9d7eed9e03e53415d37aa96045`
2501000000000000000000
```
We can also compose with other commands:
```
cast call dai balanceOf `cast resolve-name vitalik.eth`
```
This requires 1) Setting the ETH_RPC_URL, 2) Setting the ETHERSCAN_API_KEY
=> feat: `cast call` with ABI resolution and addressbook

Cargo.lock, README.md, cli/Cargo.toml, cli/README.md, cli/src/cast.rs, cli/src/cmd/build.rs, cli/src/cmd/create.rs, cli/src/cmd/mod.rs, cli/src/cmd/run.rs, cli/src/cmd/snapshot.rs, cli/src/cmd/test.rs, cli/src/forge.rs, cli/src/opts/cast.rs, cli/src/opts/forge.rs, cli/src/opts/mod.rs
structopt is deprecated in favor of clap 3
todo:
=> chore: replace structopt with clap3

Cargo.lock, cast/Cargo.toml, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Ports `seth etherscan-source` to `cast`
`$ cast etherscan-source --chain <chain> <contract-address> --etherscan-api-key <api-key>`
Fixes required -
1. Escape sequence characters are not interpreted.
2. Probably better to use `NameOrAddress` type for contract address, but I was unable to figure it out.
Would appreciate any feedback as I am only starting out with rust.
=> feat: add etherscan-source to cast

forge/src/multi_runner.rs, forge/testdata/Abstract.sol
Since Abstract contracts have no bytecode, they should not be deployed at all.
Fixes https://github.com/gakonst/foundry/issues/407
=> Forge: skip `abstract` contracts

cli/src/cmd/build.rs
- Add linked libraries env var
Test PASS:
- `forgeup naszam/foundry add-lib-env-var`
- https://github.com/makerdao/spells-mainnet/pull/213
- `make test-forge block=13779177`
```haskell
Running 13 tests for DssSpellTest.json:DssSpellTest
[PASS] testCastCost() (gas: 2864655)
[PASS] testFailTooEarly() (gas: 3580)
[PASS] testFailTooLate() (gas: 3591)
[PASS] testFailWrongDay() (gas: 3614)
[PASS] testFail_notScheduled() (gas: 7225)
[PASS] testOnTime() (gas: 2863066)
[PASS] testSpellIsCast_GENERAL() (gas: 11711549)
[PASS] testVestTransfer() (gas: 4238332)
[PASS] test_auth() (gas: 18446673704903691396)
[PASS] test_auth_in_sources() (gas: 18446673704895359673)
[PASS] test_bytecode_matches() (gas: 2783386)
[PASS] test_nextCastTime() (gas: 340057)
[PASS] test_use_eta() (gas: 338962)
```
=> feat(forge): add linked libraries env var

cli/README.md, cli/src/cmd/mod.rs, cli/src/opts/forge.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/testdata/CheatCodes.sol, forge/src/multi_runner.rs, ui/src/lib.rs
`skippped` in the terminal output bugged me so here's a very important PR! 😛
(thanks to [typos](https://github.com/crate-ci/typos) crate for finding the other typos here)
=> chore: fix typos

cli/src/cmd/build.rs
i should have caught this but it slipped by. there's an issue with Address::zero() being used as a default in clap. 
```
❯ forge test
error: Invalid value for '--tx-origin <TX_ORIGIN>': Invalid character '…' at position 4
```
=> fix `forge test` -- `Address::zero()` incompatibility

forge/README.md
Noticed this was still called `hevm`  but it was initialized as `vm`. :)
=> Forge(README): change `hevm` to `vm`

cli/src/cmd/run.rs, forge/src/multi_runner.rs
1. Renames `deployed_contracts` for clarity
2. Updates comments in some places
=> chore: Minor cleanup in `brock/par_evm`

cast/src/lib.rs
Adds polygon-mainnet and polygon-mumbai. 
**Genesis Hashes**
mainnet:
https://polygonscan.com/block/0
mumbai:
https://mumbai.polygonscan.com/block/0
**Test**
mainnet:
`ETH_RPC_URL=https://polygon-rpc.com cargo run --bin cast chain`
mumbai:
`ETH_RPC_URL=https://rpc-mumbai.matic.today cargo run --bin cast chain`
Used @joshieDo's [PR as reference](https://github.com/gakonst/foundry/pull/210#issue-1077601230)
=> Adds polygon-mainnet and polygon-mumbai

Cargo.lock, cli/src/cmd/verify.rs, evm-adapters/src/lib.rs
blocked by https://github.com/gakonst/ethers-rs/pull/787
needs `cargo update -p ethers`
=> chore(deps): bump ethabi master

cast/src/lib.rs, cli/src/cast.rs
`cast --to-wei` was using `U256` as the type for the input, causing it to fail when you included a decimal point. I fixed that and also refactored `to_wei` and `from_wei` to use `ethers::utils::parse_uints` and `ethers::utils::format_units` which helps clean things up a bit.
=> fix(cast): --to-wei with decimals

cli/src/cmd/run.rs, forge/src/runner.rs
add `DebugArena` to `TestResult`, use the updated `evm_opts` that forces verbosity
=> fix debugging

evm-adapters/src/fuzz.rs, forge/src/multi_runner.rs, forge/src/runner.rs, forge/testdata/BadSetup.sol
Instead of bailing when a `setUp` fails, we just return a failed test. This allows people to debug the setup via `-vvv` and generally just know why the setup failed.
Closes #433
=> fix(forge): No bail on setup

evm-adapters/src/evm_opts.rs
This is a bit quirky, but the dapptools test contracts are deployed when the sender is at nonce 1, not nonce 0.
Fixes #249 once and for all
=> Achieve dapptools address parity

evm-adapters/src/sputnik/cheatcodes/backend.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol, forge/src/runner.rs
Per title, adds ability to pass two address to prank cheatcodes to enable setting of origin as well.
Also fixes a tracing bug that would display the deployment trace that regressed after parallel evm was merged
=> feat(forge): Pranks can now set tx.origin

.github/workflows/release.yml, cli/Cargo.toml
Adds nightly releases and cleans up the release workflow.
Nightly releases are put under a draft version and the workflow is automatically run every day at midnight GitHub-time.
The release has archive files for macOS, Linux and Windows. Each archive contains both the `forge` and `cast` binaries and nothing else.
The archive files have predictable names that work well with scripts that pull specific versions off of GitHub releases (such as [https://github.com/onbjerg/foundry-action](foundry-action)).
An example release can be seen here: https://github.com/onbjerg/foundry/releases/v0.0.1
As an aside, when we do start releasing stable versions we should probably consider adding a changelog and using that for the release descriptions.
=> Nightly releases

evm-adapters/src/fuzz.rs
Resolves #458 
This should prevent ints that have a value of `type(intN).max + 1` from being generated, by inferring the sign from the overflowing subtraction result instead of having sign as a prop
This has not yet been thoroughly tested. @crisgarner can you `forgeup` to this branch and make sure it fixes your issue?
=> fix: fuzzer now generates ints in correct range

Makefile
Using `git pull --recurse-submodules` updates the submodules to the latest remote commit of the submodule, which is not what we want. Our integration tests are failing because we are updating the `solmate` dependency in Rari's vaults repository which removed a contract that they are still using.
We should instead:
- `git pull` to check for new commits in the testdata
- `git submodule update --recursive` to update the submodules accordingly if they were changed in the testdata repository
=> Fix integration testdata

.github/workflows/release.yml
I'm not entirely sure why it works, but I looked around for other repos that were targetting Apple M1 and it seems like this is the fix. Maybe it's something about being more explicit about the SDK used to cross-compile when we're compiling bindings?
Regardless... behold: https://github.com/onbjerg/foundry/runs/4828392401
(Also can someone with an M1 chip please test I do not own one myself so I don't know if the binary is useable)
Closes #466
=> Build releases for Apple M1

utils/src/lib.rs
There was a double space before `external` when using `cast interface` if we could not determine the mutability of the function. Alternative to this PR we could assume a default mutability, but I'm unsure if that is different depending on the Solidity version used?
Closes #471
=> Fix double space when no mutability is specified

utils/src/lib.rs
It turns out I didn't need to make any changes to ethers-rs, as `implementation` is exposed in the `Metadata` struct returned by `client.contract_source_code`.
=> feat: detect proxies for `cast send` and `cast call`

README.md, foundryup/install
if we have two different sets of binaries on the system both sourced in PATH (.cargo/bin .foundry/bin) one will always take precedent over the other. since the foundryup command itself uses both cargo and manually adding to foundry bin, we need to fix this (https://github.com/gakonst/foundry/pull/480)
the lazy fix is just to move the bins put in cargo bin into the foundry bin dir after running cargo install, which i have impl'd here
=> fix: move cargo forge & cast bins to foundry bin

cast/README.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Adds `publish` to cast letting users send raw transactions to the network.
=> feat: add publish to cast

Cargo.lock
ref: https://github.com/rust-ethereum/ethabi/pull/255
Example:
```
cast call 0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85 nameExpires 1
```
```
cast call 0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85 nameExpires 0.000000000000000001ether
```
```
cast call 0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85 nameExpires 1wei
```
All returning the same: `1588550400`
=> chore: update ethabi for uint unit parsing

utils/src/lib.rs
Follow up on #484 which adds proxy detection, but a the expense of making two etherscan API calls. I also made a slight improvement in the error handling. Before if the contract was not verified, you did not get a good error message.
=> fix: avoid redundant etherscan calls

foundryup/install
When attempting to install foundry, I got the following error: 
```
line 83: unexpected EOF while looking for matching `"'
```
Inspected the file and found the missing `"`. Install works after fix.
=> Missing `"` causes EOF error when installing

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
It uses `LenientTokenizer` from `ethabi` to convert in-between units (`ether`, `gwei`, `nano`, `nanoether` and `wei`).
Imo, should be recommended for using instead of `--to-wei` and `--from-wei`, where the parsing is done through `f64`, which might have some precision issues: https://github.com/rust-ethereum/ethabi/pull/255#discussion_r786490582
I'm trimming the decimal part, if there are only decimal 0s. I think it makes sense for when converting to `wei`, but the rest is debatable I guess.
```
cast---to-unit
convert an ETH amount into a specified unit: ether, gwei or wei (default: wei).
Usage Example:
- 1ether wei     | converts 1 ether to wei
- "1 ether" wei  | converts 1 ether to wei
- 1ether         | converts 1 ether to wei
- 1 gwei         | converts 1 wei to gwei
- 1gwei ether …
```
=> feat/cast: adds --to-unit

Cargo.lock, cli/src/cmd/build.rs, cli/src/cmd/flatten.rs, cli/src/cmd/mod.rs, cli/src/forge.rs, cli/src/opts/forge.rs, cli/src/utils.rs
=> feat(forge): flatten

README.md
clutters up the readme 
ppl will get alerted when they run foundryup now anyway
=> docs: remove warning about libusb

cli/src/cmd/run.rs, cli/src/cmd/test.rs, evm-adapters/src/call_tracing.rs, evm-adapters/src/fuzz.rs, evm-adapters/src/lib.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/forked_backend/rpc.rs, evm-adapters/testdata/CheatCodes.sol, forge/README.md, forge/src/multi_runner.rs, forge/src/runner.rs, utils/src/lib.rs
Primarily, this introduces improvements:
1. Decodes custom errors in call traces as well as fail messages
2. adds overloading of `expectRevert`
3. functions, events, and errors are flattened across all compiled abis to allow for decoding of calls, events, and errors regardless if a particular contract is identified.
Closes #409, Closes #479
=> feat(forge): custom error decode

README.md
It seems that there is a redirect involved when calling `foundry.paradigm.xyz` that needs to be followed so the curl can work properly.
```
curl https://foundry.paradigm.xyz -vvv
*   Trying 2606:4700::6811:1258:443...
* Connected to foundry.paradigm.xyz (2606:4700::6811:1258) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, …
```
=> Follow redirect when installing foundryup

.github/workflows/release.yml, cli/src/opts/cast.rs, cli/src/opts/forge.rs, foundryup/install
I wanted to be able to do `man forge` and `man cast` and now we can. :)
This uses `help2man` a handy tool which creates man pages from the `-h` flag output. In the future, we could make the man pages more comprehensive but I think this is a good start.
Cleaned up some of the attribute placement from clap so that the name in the `-h` flag output is correct (it used to say `foundry-cli` for both `forge` and `cast`) and so that it also now has a `-V, --version` flag (which `help2man` needs). It uses clap's default and reads it from the `Cargo.toml` file.
Extended the GitHub actions to build and publish the man pages, and `foundryup` to either download them or build them if you go the building path.
Edit: you can see the updated release GitHub action tested and working here: …
=> feat(cli): install man pages

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/evm.rs, evm-adapters/src/sputnik/mod.rs, utils/src/lib.rs
This makes the reported gas in `TestResult` actually match closer to the execution costs and matches the `trace` gas usages. Basically we use `gas_used - gas_refund - tx_costs`, where `tx_costs` is calldata cost + base tx cost (21k).
=> fix(forge): Better gas reporting

foundryup/install
Removes the warning because it wasn't really useful and caused unnecessary confusion
=> fix(foundryup): remove help2man warning

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/testdata/CheatCodes.sol
Right now, if you provide `calldata`-  via `expectCall` cheatcode - with more parameters than actual call input, it causes a panic. 
This should be handled gracefully. If no match was found it fails the test anyway.
=> fix(evm-adapters): index out of bounds panic if expected length > input length

.github/workflows/release.yml
Turns out that we were building the binaries correctly but for whatever reason `tar` (defaults to BSD tar) on macOS sometimes corrupts the binaries for LLVM projects (incl. Rust) in GitHub actions. The solution is to use GNU tar.
More info: https://github.com/actions/virtual-environments/issues/2619
Closes #531
=> Fix macOS release archives

Cargo.lock, cli/Cargo.toml
fixes zsh completion bug https://github.com/clap-rs/clap/pull/3295 that first appeared in https://github.com/gakonst/foundry/pull/469
=> chore(cli): update clap, clap-complete

cli/src/cmd/config.rs, cli/src/opts/evm.rs, cli/test-utils/src/util.rs, cli/tests/cmd.rs, evm-adapters/src/evm_opts.rs
add missing rpc url alias for `EmvArgs` -> `EmvOpts` conversion
=> fix: add rpc url alias

cli/README.md
Related to #536
Created a section in `cli/README.md` (not sure if it's the best place) with examples on how to run a subset of tests. Also added common patterns (that I use) and an edge cases.
Not sure if it's in sync with what other people had in mind, feel free to make suggestions or completely discard it.
=> docs: document test-matchers with examples and patterns

cli/src/cmd/build.rs, cli/tests/cmd.rs
the CLI arg is `--no-auto-detect` but the Config var is `auto_detect_solc` which is `! no_auto_detect`
so we need to insert `false` in the figment if `--no-auto-detect` is present
Ref https://github.com/gakonst/foundry/issues/525#issuecomment-1019424812
=> fix: flip autodetect flag

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
Makes `ffi` decoding a bit more robust, as you no longer have to trim new lines and whitespace in the script you're calling out to
=> fix: trim whitespace from ffi output before decoding it

cli/src/cmd/build.rs, cli/tests/cmd.rs, config/src/lib.rs
If you create a `remappings.txt` file after the config then auto-generated remappings are not included, so you can't remap just one dependency. In other words the remappings behave like an "or" (if env is set use that, otherwise use remappings file, otherwise use CLI parameters, otherwise use auto-generated remappings)
This PR re-implements the behavior in https://github.com/gakonst/foundry/pull/519
=> Merge remappings

.github/scripts/move-tag.js, .github/scripts/prune-prereleases.js, .github/workflows/release.yml, foundryup/README.md, foundryup/install
Cleans up the release workflow a bit and keeps 3 nightlies.
Nightlies are now tagged with `nightly-$SHA` as well as `nightly`. To find the latest nightly, you would look up the `nightly` tag and find the release at `nightly-$SHA` where `$SHA` is the commit that `nightly` is pointing to.
The workflow only deletes releases that have `nightly` in the tag of the release, which allows us to release other pre-release versions (betas etc.)
This also adjusts `foundryup` accordingly and there is a PR for `foundry-toolchain` too: https://github.com/onbjerg/foundry-toolchain/pull/2. **This is a breaking change for `foundryup`.**
Closes #472
=> Keep 3 days of nightlies

.github/workflows/release.yml
First few steps that prepare the release are not working since we haven't checked out the sources, so the GH scripts action can't find our script
=> Checkout sources in prepare step

.github/workflows/release.yml
Building the changelog failed without `fetch-depth: 0` which is strange because it didn't on my fork. Perhaps because we only have 1 tag?
=> Fix changelog builder

cli/src/cmd/install.rs, cli/tests/cmd.rs
It was mistakenly renamed to `libs`
=> Fix lib path

.github/scripts/create-tag.js, .github/scripts/prune-prereleases.js, .github/workflows/release.yml
Always maintains an up-to-date release tagged `nightly` so that we don't break existing `foundryup` installations, in addition to 3 nightly releases tagged `nightly-${SHA}` which allows you to roll-back to a previous nightly build if you want to.
@_@
Successful run: https://github.com/onbjerg/foundry/actions/runs/1743111245
=> Nightly backwards compatability

cli/src/cmd/install.rs
add support for passing `--root` flag to `forge install`. this is useful when managing multiple forge packages in a monorepo
=> feat(forge/install): take root flag

.github/ISSUE_TEMPLATE/BUG-FORM.yml, .github/ISSUE_TEMPLATE/FEATURE-FORM.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Adds two issue forms:
- Bug report
- Feature request
**You can see what the forms look like by going to "Files change" and clicking "View file" (accessible by the 3 dots in the top right) on the form**
Also adds:
- A link to the Foundry Support telegram when opening an issue
- A very minimal PR template
- Contributing guidelines (inspired by the one in ethers-rs)
Finally, does a pass on the README with some formatting nits and callouts to read the book.
For more info on the new issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
Anything missing in the forms?
=> Community templates

.github/changelog.json, .github/workflows/release.yml
Currently all of our releases have no description, because our changelog builder action hides uncategorized PRs by default.
This configures the action to show the uncategorized PRs under a special section called "Other", and it also configures the labels required for the other sections of the changelog:
- Feature PRs should now be tagged with `T-feature`
- Bug fix PRs should be tagged with `T-bug` (I also added `T-fix` even though it doesn't exist if we want to add that instead)
- To omit a PR entirely from the changelog, add `L-ignore` to the PR.
Any other PR without any of these labels will end up in the "Other" section of the changelog for the release.
=> Configure changelog

CONTRIBUTING.md
According do the docs, the following command should not throw any error. But `cargo +nightly clippy -all --all-features -- -D warnings` would throw an error as the flag -all is invalid.
`cargo +nightly clippy --all --all-features -- -D warnings` is the right command. ( -all to --all)
Updating the doc with the same.
=> Fixed wrong arguments in cargo +nightly clippy

config/src/lib.rs, evm-adapters/src/evm_opts.rs, evm-adapters/src/sputnik/forked_backend/cache.rs, evm-adapters/src/sputnik/forked_backend/rpc.rs, evm-adapters/src/sputnik/mod.rs, forge/src/lib.rs
DappTools always used chain ID 99, even when forking from a remote RPC, whereas Foundry just falls back to the chain ID of the RPC. The motivation here is DappTools compatability
I made chain ID optional and:
- If we're forking from a remote RPC, we override the chain ID if specified anywhere in the config (`foundry.toml`, CLI arg, environment)
- If we're not using fork mode, but the chain ID has not been specified, we still default to chain ID 1.
Closes #601 and fixes drai integration test
=> Honor `--chain-id` even when using fork mode

Cargo.lock, cast/src/lib.rs, cli/src/cmd/create.rs, cli/src/opts/mod.rs
Mostly good i think but hitting this issue after upgrading ethers-rs with `cargo update -p ethers`
```
cargo run --bin forge           
Compiling ethers-providers v0.6.0 (https://github.com/gakonst/ethers-rs#c22dd8ea)
error[E0433]: failed to resolve: use of undeclared crate or module `http`
--> /Users/tarrence/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/c22dd8e/ethers-providers/src/transports/http.rs:162:27
|
162 |     InvalidHeader(#[from] http::header::InvalidHeaderValue),
|                           ^^^^ use of undeclared crate or module `http`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `ethers-providers` due to previous error
```
=> feat(cast/send): legacy txn sending

CONTRIBUTING.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs, cli/src/opts/mod.rs
1.  Ability to supply gas amount, value, nonce with cast send cmd and value with cast estimate cmd  allows for greater flexibility when dealing with transactions.
2. Ability to specify ETH_KEYSTORE (like dapp) for wallet use allows one to avoid specifying keystore file every time.
1. Added **gas**, **value**, and **nonce** options to **cast send** cmd.
For example -
`
cast send 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 "createProxyWithNonce(address,bytes,uint256)" 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 "" 13 --gas 250000 --value 1 --nonce 7 --private-key PV_KEY
`
2. Added **value** options to **cast estimate** cmd.
For example -
`
cast send 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 "createProxyWithNonce(address,bytes,uint256)" 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 "" 13 --value …
=> feat(cast): adds support for gas, value, nonce for send cmd & value for estimate cmd

cli/src/opts/cast.rs
Currently this just modifies the clap config to allow hyphens for commands that can take negative values as input args. A sanity check that I didn't miss any commands would be appreciated.
Clap also has an option to allow hyphens globally, but only allowing them as-needed is [preferable](https://github.com/clap-rs/clap/issues/1134#issuecomment-356352402).
The commands with the "negative values not yet supported" comment still don't work due to ints not being supported somewhere in the underlying methods. Will get that fixed next before taking this out of draft
=> fix: support ints in cast

cli/src/cmd/create.rs
=> chore: fix `forge create` argument parsing (#473)

config/src/lib.rs
It is possible to specify the block to fork from in DappTools using `DAPP_TEST_NUMBER`. This behavior is not currently replicated in our codebase.
See [here](https://github.com/dapphub/dapptools/blob/e9d454af4953b1f61c7f3fcfad595601c3e14521/src/hevm/README.md#environment-variables) for DappTools docs
Adds backwards support to use `DAPP_TEST_NUMBER` to specify the block to fork from, but only if `DAPP_FORK_BLOCK` is not specified.
Closes #530
=> Support `DAPP_TEST_NUMBER` in fork scenarios

cast/README.md, cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
This commit implements `cast receipt`. If the receipt is not
found, it will poll until it is found. Similar to `seth`,
an optional field can be passed to only print a particular
field on the receipt response. Unlike `seth`, there is a
`--json/-j` flag that will render the receipt as JSON.
Example usage:
```bash
cast receipt --rpc-url https://mainnet.optimism.io \
0xa9fc1761ecad57693d7000b7bd8aea8ae5c3c34a1fcf966097778068c82c86cc
```
=> feat(cast): implement `cast receipt`

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Adds `legacy` option to `SendTx` for `cast send`.
Closes #579
=> add legacy option to `SendTx`

cli/src/cmd/install.rs
Paths to git commands when running `forge install` and `forge init` are broken on Windows.
Make the paths relative to the root of the project where relevant, which fixes the issue - keeping this as a draft until I have tested it on Windows
**Remaining tasks**
Fixes #621 and fixes #631
=> Use relative path for git commands in install cmd

cli/src/cast.rs, cli/src/opts/cast.rs
Adds `cast client` to return details on the current client version, analogous to [`seth client`](https://github.com/dapphub/dapptools/blob/master/src/seth/libexec/seth/seth-client)
=> feat: cast client

cli/src/cmd/run.rs, cli/src/cmd/test.rs, evm-adapters/src/call_tracing.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/debugger.rs, evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol, forge/src/runner.rs
Adds a `label(address,string)` cheatcode that allows users to label an address for use in stack traces. Also removes contract limit in `run` command.
Closes #553
=> feat(forge): label cheatcode

cli/src/cmd/test.rs, config/README.md, config/src/lib.rs, evm-adapters/Cargo.toml, evm-adapters/src/gas_report.rs, evm-adapters/src/lib.rs
Adds `--gas-report` flag to `forge test`.
Adds `gas_reports` into `foundry.toml` which lets the user specify which contracts they want gas reports for, i.e:
```toml
gas_reports = ["MyContract", "MyContractFactory"]
```
or to produce a report for everything:
```toml
gas_reports = ["*"]
```
then if the user does `forge test --gas-report` they will get an output like:
Note: the colors you see here are a bit different than what may show up for you. My terminal theme is a bit off and it shows green as yellow and yellow as green.
Partially addresses #137
=> feat(forge): add gas reports for tests

cli/src/opts/cast.rs
This is a following pr of #636 
now ether value parsing support
```bash
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 123
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 0x123
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 123ether
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 123gwei
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 12.3ether
```
=> feat: more elegant ether value parsing

Cargo.lock, cli/src/cmd/build.rs, cli/src/opts/forge.rs, config/src/lib.rs
ref #611 
It prints into `out/Contract.sol/` the requested output type[s].
~~Requires PR: https://github.com/gakonst/ethers-rs/pull/847~~
---
Usage:
foundry.toml:
```
[default]
optimizer = true
optimizer_runs = 1_000_000
extra_output = ["ir", "ewasm", "irOptimized", "evm.assembly"]
```
or
```
forge build --extra-output evm.assembly --extra-output ir --extra-output irOptimized --extra-output ewasm
```
`$ ls out/C.sol/`
```
C.asm  C.ewasm  C.ir  C.iropt  C.json  ERC20.asm  ERC20.ewasm  ERC20.ir  ERC20.iropt  ERC20.json  VM.asm  VM.ewasm  VM.ir  VM.iropt  VM.json
```
=> feat/forge: add extra output types to config and CompilerArgs on build

config/Cargo.toml, config/README.md, config/src/lib.rs
* Introduce `~/.foundry` as global config dir
* Support `~/.foundry/foundry.toml` 
if `~/.foundry/foundry.toml` exist, merge in into the `Figment`
=> feat(config): add foundry dir and check for global foundry.toml

cli/src/cast.rs, cli/src/opts/cast.rs
now we don't need to specify the function sig to send ether value 
```bash
target/debug/cast send $addr --mnemonic-path ~/mnemonic.txt --value 0.001ether
target/debug/cast send $addr "test()" --mnemonic-path ~/mnemonic.txt --value 0.001ether
target/debug/cast send $addr "test(uint256,bool)" 1 true --mnemonic-path ~/mnemonic.txt --value 0.001ether 
```
=> feat/cast: cast send ether without specify function sig

Cargo.lock, cli/Cargo.toml, cli/src/cmd/bind.rs
- Running bind in an unbuilt project generated no output with no message.
- Running bind outside of a cargo project panicked with no helpful message.
- add an emptiness check that generates a helpful message if no artifacts are found
- add a precondition to bind that locates a cargo manifest, and displays a helpful message if none is found
=> feature: bind precondition & empty checks

foundryup/install
Discard local changes when installing new version of foundry via foundryup when pulling from git.
`Cargo.lock` gets occasionally locally modified when building new version. Thus, when running e.g. `foundryup --branch master` next time, it causes a conflict, preventing the checkout and thus the update.
Instead of doing a pull and checkout, it should fetch and do a force checkout (via `git reset --hard`), discarding any local changes.
=> fix(foundryup): discard any local changes when updating version via git

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Implemented `cast index`
Right now it has the same scope and behaviour as `seth index`. If there can be a better syntax please do comment. 
Note:
- The from_type and to_type is technically not required as `cast abi-encode` ignores the function signature. 
- But `cast abi-encode` requires that the signature matches the input parameters while `seth abi-encode` doesn't. 
-  `seth abi-encode "x(address,address)" 42 42` will work but `cast  abi-encode "x(address,address)" 42 42` won't. Just some observations.
=> feat(cast): Implemented cast index (seth feature parity #29)

cli/src/cmd/create.rs, cli/src/opts/cast.rs, utils/src/lib.rs
I want to be able to deploy a contract with large constructor args. If passed via `argv` they are too large.
It is possible to create a transaction where the
calldata is too large to be passed via `argv`.
See https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLong
for more information on this limitation. To make it
possible to create these large transactions, update
`forge create` so that it can read the calldata
from a file.
A new cli argument is added `--constructor-args-path`
that conflicts with `--constructor-args`. This new
argument should point to a file on the filesystem
that contains a whitespace delimited list of
constructor arguments.
=> feat(forge create): read calldata from file

cli/src/cast.rs
make transaction receipt output as json literal so that we can combine cmd utils like `jq` to pretty print
convert `TransactionReceipt` struct to json
=> feat/cast: transaction receipt print as json literal

cli/src/opts/cast.rs
Currently, the gas price can only be set via environment variable in `cast send`. This diverges from seth and recently caused me quite a bit of confusion. I think that gas price is something users will want to quickly modify, so we should allow the --gas-price flag to work for convenience.
I think the reason that `--gas-price` does not work as a flag even though `long` is specified in clap is due to the presence of an underscore. Explicitly specifying `long = "gas-price" seems to fix it.
=> fix(cast): --gas-price flag in `cast send`

config/src/lib.rs, config/src/utils.rs
the figment parser tries to parse env vars `src/DssSpell.sol:DssExecLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6` as vec
manually parse figment arrays
also bumps ethers
=> fix(config): parse libraries as string

cli/src/cast.rs, cli/src/opts/cast.rs
add support for specifying number of confirmations when using `cast send`
=> feat(cast): support confirmations parameter for cast send

.github/workflows/release.yml
The Windows build is running out of memory which prevents the nightlies from releasing properly. Since `foundryup` does not support Windows anyway, we should disable the Windows nightlies until we find a long-term solution so we don't break all other releases
=> ci: temporarily disable windows nightlies

.github/workflows/release.yml, cli/src/cmd/build.rs
If I read `foundryup` correctly this should already be supported, so this is the only change needed, given Cargo doesn't complain
Closes #684
=> ci: build arm64 linux nightlies

.github/workflows/release.yml, cli/src/cmd/build.rs
Reverts gakonst/foundry#694 as it was not meant to be merged yet (`openssl-sys` is not building on ARM in the current workflow)
=> revert: arm64 linux nightlies

cli/tests/cmd.rs, config/src/lib.rs, config/src/macros.rs
include `root` when deserialising `Config` from `Figment`
=> fix(config): include root argument in deserialization

cli/src/cast.rs
In https://github.com/gakonst/foundry/pull/398, the `call` method was modified to take a from address as an input, and `cast call` was configured to use `eth.sender().await` as the from address. This resulted in every usage of `cast call` prompting the user for a keystore password before executing the call
`cast call` now defaults to using the zero address as the from address, unless one is specified with the `--from` flag. This is consistent with [seth's](https://github.com/dapphub/dapptools/blob/1be7d796a468f52a5eb5b6830591d76a3b4b1c49/src/seth/libexec/seth/seth-call#L60) and [geth's](https://geth.ethereum.org/docs/rpc/ns-eth#eth_call) behavior
=> fix: don't prompt for keystore password on cast call

evm-adapters/src/sputnik/cheatcodes/backend.rs, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/src/sputnik/cheatcodes/mod.rs, evm-adapters/testdata/CheatCodes.sol
When instantiating the environment, the block hashes are [empty](https://github.com/gakonst/foundry/blob/aabfb0ed15a9213f2eb26c9eb6635fdb6aee0a3c/evm-adapters/src/evm_opts.rs#L190). This makes sense as there's no notion of a blockchain in foundry, everything gets done at the evm level
However, this meant that if somebody wanted to get the blockhash at a height, they'd always get 0, e.g. [Ethernaut here](https://github.com/OpenZeppelin/ethernaut/blob/4f80f8afa47793d9133f03b6c247d8b6b0adc673/contracts/contracts/levels/CoinFlip.sol#L18). 
Whenever a call to `roll(...)` is made, we also insert a randomly generated block hash if there was none before. In the above example, assuming the current block number is `num`, the solver of the puzzle would need to `vm.roll(num - 1)` so that the hash is …
=> feat: roll with hash 

cli/src/cmd/build.rs, cli/src/cmd/flatten.rs, config/README.md, config/src/lib.rs
add `--offline` flag and config option for `ethers-rs::solc::Project::offline`
=> feat: support offline mode

.github/workflows/release.yml, utils/Cargo.toml
Follow-up on https://github.com/gakonst/foundry/pull/694
1. Try to address the OpenSSL-Sys issue that @onbjerg wrote in #694 by making `reqwest`'s `default-features = false`. The lockfile didn't change though, so I am inclined to believe that this isn't sufficient. Let's see
2. SVM-rs now supports arm linux builds, ref https://github.com/gakonst/foundry/issues/684#issuecomment-1032575637, https://github.com/nikitastupin/solc, https://github.com/roynalnaruto/svm-rs/pull/17
=> ci: Linux Arm64 Releases

Cargo.lock, cast/Cargo.toml, cast/src/lib.rs, utils/src/lib.rs
ENS resolution is not supported for function parameters in `cast call` and `cast send`. To see this error in actions, run `cast call dai balanceOf ncitron.eth`.
This problem is solved by preprocessing all arguments in `build_tx` to check if the parameter contains the string ".eth". If it does, we automatically attempt to resolve the name.
=> feat(cast): add ENS resolution for function parameters

cli/src/cmd/create.rs
Improve the devex of `forge create`
This commit prints the transaction hash of the deployment
transaction after running `forge create`. This is useful
for looking up the deployment transaction after the fact.
=> feat(forge create): print tx hash after deployment

evm-adapters/src/fuzz.rs
fixes https://github.com/gakonst/foundry/issues/734
Before:
```
forge t -vvvv
compiling...
no files changed, compilation skipped.
Running 1 test for ContractTest.json:ContractTest
[FAIL. Counterexample: calldata=0xda273f4e0000000000000000000000000000000000000000000000000000000000000000, args=[0]] testStateFailure(uint256) (runs: 0, μ: 0, ~: 0)
Traces:
[80337] ContractTest::setUp()
├─ → new Contract@0xce71…c246
│   └─ ← 227 bytes of code
└─ ← ()
[26011] ContractTest::testStateFailure(0)
├─ [20394] Contract::init()
│   └─ ← ()
├─ [2444] Contract::func1(0)
│   └─ ← 0
└─ ← ()
Failed tests:
[FAIL. Counterexample: calldata=0xda273f4e0000000000000000000000000000000000000000000000000000000000000000, args=[0]] testStateFailure(uint256) (runs: 0, μ: 0, ~: 0)
```
--
After
```
[FAIL. Counterexample: …
```
=> fix(fuzz): reset state to pre-test state

Cargo.lock
Updating `ethers-rs` so that https://github.com/gakonst/foundry/pull/682 can be pushed over the line
Bumps `ethers` and associated dependencies to
[faba6e014da854e296d095541679e852e2288eec](https://github.com/gakonst/ethers-rs/commit/faba6e014da854e296d095541679e852e2288eec).
This was done by running the command `cargo update -p ethers-solc`.
=> chore: bump ethers version

cli/src/cmd/init.rs
so that we can use short template url
```
forge init --template ZeframLou/foundry-template
```
=> fix(forge): use short hand template url

cli/src/cast.rs, cli/src/opts/cast.rs
Makes `cast send` receipts default to table view
=> feat(cast/send): output table for receipts

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs, evm-adapters/testdata/CheatCodes.sol
fixes https://github.com/gakonst/foundry/issues/668
Notice emitted a and b values below:
Before:
```
Traces:
[146057] ContractTest::setUp()
├─ → new Contract@0xce71…c246
│   └─ ← 552 bytes of code
├─ [0] VM::deal(0xce71065d4017f316ec606fe4422e11eb2c47c246, 100000000000000000000)
│   └─ ← ()
└─ ← ()
[33730] ContractTest::testExpectEmit()
├─ [0] VM::expectEmit(true, false, false, true)
│   └─ ← ()
├─ emit ZEvent(a: 42893283, b: 4223232, c: 0xb4c79dab8f259c7aee6e5b2aa729821864227e84)
├─ [31091] Contract::testemit(10)
│   ├─ [45] ContractTest::fallback{value: 1}()
│   │   └─ ← ()
│   ├─ emit ZEvent(a: 1, b: 2, c: 0xb4c79dab8f259c7aee6e5b2aa729821864227e84)
│   └─ ← ()
└─ ← ()
```
--
After 
```
[FAIL. Reason: Expected an emit, but no logs were emitted afterward] testExpectEmit() (gas: 33737) …
```
=> fix(forge): expectEmit with call

Cargo.lock, cli/src/cast.rs, cli/src/cmd/verify.rs, cli/src/forge.rs, cli/src/opts/forge.rs, cli/src/utils.rs
fixes https://github.com/gakonst/foundry/issues/311
`verify-contract` command takes a project configuration and build information from arguments, flattens the target contract and submits it for verification.
`verify-check` command takes the verification guid and queries Etherscan API for verification status. 
Next steps would be:
- taking build info (compiler version, number of optimization runs etc) from the artifacts instead of taking it from cli args
- taking raw constructor arguments and ABI encoding them before submission
- renaming `chain_id` argument to `chain` & adding the ability to pass in chain id as well as the chain name.
i.e. `--chain 1` and `--chain mainnet` should both be valid
=> fix(forge): verify

Cargo.lock, cli/src/cmd/build.rs, cli/src/cmd/mod.rs, cli/src/cmd/run.rs, cli/src/opts/forge.rs, cli/test-utils/src/util.rs, cli/tests/cmd.rs, config/src/lib.rs
~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/907~~
Close #705
Close #765
add additional config and cli options to add additional items to the contract artifact and/or emit them as additional file like metadata
`--extra-output <metadata|ir|ir-optimized|...>` will add the provided selection to the contract's json artifact.
`--extra-output-files <metadata|ir|ir-optimized|...>` will emit the provided selection as additional file, eg. `forge build --extra-output-files metadata` will put the `Contract.sol` metadata in `Contract.metadata.json` next to the artifact `Contract.json`
=> feat: make artifact type configurable

utils/src/lib.rs
since it is now handled in ethabi
=> chore(lib): remove 0x prefix stripping

cli/README.md, cli/src/cast.rs, cli/src/opts/cast.rs, utils/src/lib.rs
Implementing `cast pretty-calldata` . Mentioned here #732 
- It will attempt to get signatures from 4byte.directory by default 
- Get's possibilities from 4byte and displays them using a helper struct
Let me know if need to make any changes or any Rust related feedback, thanks!
Example
=> feat(cast): cast pretty-calldata

Cargo.lock, cast/src/lib.rs, cli/Cargo.toml, cli/src/cast.rs, cli/src/opts/cast.rs
It's often useful to find the block number that is closes to a given timestamp
`cast find-block <timestamp>` now binary searches blocks to find the one closest to the provided timestamp
As a rust amateur, I'm almost certain there's ways this code can be improved or cleaned up, so feedback is welcome 🙂
=> feat(cast): add find-block command

Cargo.lock, cli/src/cmd/mod.rs, cli/src/cmd/run.rs, cli/tests/cmd.rs
Use new ethers-solc functions introduced in https://github.com/gakonst/ethers-rs/pull/931 to compile individual files
replace custom compile functions in forge run
=> refactor(forge): use new ethers-solc functions in forge run

CONTRIBUTING.md
While working on https://github.com/gakonst/foundry/pull/791, I wasn't sure how to test the behavior of `cast wallet` after my change.
Add a link to `foundryup` README inside the CONTRIBUTING.md page
=> chore(docs): add link to foundryup in CONTRIBUTING

cli/src/cast.rs
Fixes https://github.com/gakonst/foundry/issues/790
Remove trailing periods from `cast wallet new` and `cast wallet vanity` output.
=> feat(cast): remove periods from wallet new

cli/src/opts/cast.rs
Changed "excluidng" to excluding in the description of abi-encode in cast.
=> Fix(cli/cast): Typo in the description of abi-encode

cli/README.md, cli/src/cmd/mod.rs, cli/src/cmd/test.rs, cli/tests/cmd.rs, forge/src/lib.rs, forge/src/multi_runner.rs
@gakonst this adds streaming for test results. Makes the UI more responsive for large projects / older machines.
=> feat(forge test): stream test results

cli/src/opts/forge.rs
#778 happens when users omit the contract name and only provide a path. 
We return a hopefully clear error when it looks like the user has only included a path to the contract.
=> fix(forge): ContractInfo should reject input when contract name is omitted

cli/src/cmd/build.rs, cli/src/cmd/create.rs, cli/src/cmd/flatten.rs, cli/src/cmd/mod.rs, config/src/lib.rs
I want to know which contracts were compiled when running
`forge build` and the compiler version that was used.
Print the names of the compiled contracts after
running `forge compile`. Its useful to know which
contracts were compiled and the compiler version
that was used.
The output looks like this:
```bash
$ forge build --hardhat --names --sizes
compiling...
Compiling 1 files with 0.5.17
Compiling 79 files with 0.8.11
Compilation finished successfully
Compilation finished successfully
compiled contracts:
compiler version: 0.5.17
- WETH9
compiler version: 0.8.11
- AddressDictator
- ChugSplashDictator
- IL1CrossDomainMessenger
- IL1ERC20Bridge
- IL1StandardBridge
- L1CrossDomainMessenger
- L1StandardBridge
- CanonicalTransactionChain
- ChainStorageContainer
- ICanonicalTransactionChain
- …
```
=> feat(forge compile): print compiled contract names

cli/src/cmd/mod.rs, cli/tests/cmd.rs, forge/src/multi_runner.rs
Sometimes we wouldn't print compiler warnings. This PR addresses it by always printing the compiler output in the else branch, and removing any ad-hoc prints or `println!("success")`
fixes #810
fixes #687
=> fix: print compiler warnings on success

cli/src/cast.rs, cli/src/opts/cast.rs
```sh
$ cast wallet vanity --starts-with c --ends-with c --nonce 0
Starting to generate vanity address...
Successfully found vanity address in 0 seconds.
Contract address: 0xcba76A958E502fdCbBABdE7eE4a50Fe70d11eD7C
Address: 0x76A4A0dc5Cc658901A04c188e69de44d343B4D51
Private Key: 0xf6d3b4f5601b588436dbeb05d32038fc737f6a363a0bec7395213362750db1ab
$ Find a wallet with an address that starts and ends with `c`
$ cast wallet vanity --starts-with c --ends-with c
Starting to generate vanity address...
Successfully found vanity address in 1 seconds.
Address: 0xc4365487aE7d796233E8d615743CD81ce1C8843c
Private Key: 0x15d53501bb1f2cbe0f6c6e5ec58cfc5b50ee8a4c87fdadc6354878959f3b65af
```
Also added the `0x` prefix to the printed private key, which previously was not included
=> Add `cast wallet vanity --nonce <nonce>` to generate wallet that deploys a contract address

cli/src/cmd/install.rs
improves monorepo support. previously foundry would try install all monorepo submodules
=> fix(forge/install): scope to root dir

Cargo.lock, cli/Cargo.toml, cli/src/cmd/build.rs, cli/src/cmd/flatten.rs, cli/src/cmd/mod.rs, cli/src/cmd/test.rs, cli/src/cmd/watch.rs, cli/src/forge.rs, cli/src/utils.rs
Fixes #813
this adds a `forge build -w|--watch` flag which enters watch mode that runs forge build on changes.
`forge test -w` is slightly more complicated because ideally, we want to adjust the match argument. I think I've figured out how to implement this and will try to add this.
`forge test --watch` added, currently it's configured to only run those files/file that was changed, see `forge test --match-path`
This will benefit once we can limit the files we need to compile based on the tests we need to run.
The watchexec API is a bit clunky when it comes to reconfiguring the runtime, but it appears to work.
=> feat(forge): watch mode for forge build

cli/src/cmd/flatten.rs, cli/src/cmd/verify.rs
Unless you read the foundry book, It's easy to accidentally specify `--optimize --optimize-runs=200` in `forge verify-contract` because that's what you use in `forge create`. The actual option is `--num-of-optimizations`. 
AFAIK, most of the options from `BuildArgs` displayed in `forge verify-contract` are not actually used because we're only flattening the contract code. We don't need to display them.
`forge flatten` establishes a precedent of using a subset of `BuildArgs` to flatten the project. We follow that pattern by using the subset of `FlattenArgs`, which is used to establish `BuildArgs`, in `forge verify-contract` 
I have manually tested the `forge create` -> `forge verify-contract` -> `forge verify-check` flow multiple times in this branch and confirmed it works.
---
Current …
=> fix(forge): verify-contract only needs subset of BuildArgs options

cli/src/cmd/verify.rs
`master` branch build was failing, likely due to changes in [cc13c40](https://github.com/gakonst/foundry/commit/cc13c4095ff38bd6adb1f5d853758768f7f6a2de).
Added the missing BuildArg to the `verify` options.
=> fix: add missing watch arg to verify BuildArgs

cli/src/opts/evm.rs, forge/README.md
The documentation around test logging is a bit sparse for newcomers to both solidity development and forge. In a basic `forge test` call, neither log events nor console logs are visible. The documentation is not clear that 2nd level verbosity is required to view the logs in stdout.
Add some simple documentation in the `Console.log` section of the `forge` README.
Update the help message text for the `--verbosity` flag in forge cli.
=> docs(forge readme, forge cli) Add more explicit notes around logging

cli/src/cmd/create.rs
Currently there is no way to specify gas prices when deploying contract with `forge create` nor does `cast send` supports `--create`. Adding `--gas-price` and `--priority-fee` option to `forge create` which users can use to specify the gas prices. Can be relevant when deploying on mainnet and want control over the cost.
Closes https://github.com/gakonst/foundry/issues/836
Adding the options and setting the gas price and priority fee before sending the deploy tx.
=> feat(forge/create): opts for specifying gas price and priority fee

Cargo.lock, Cargo.toml, cli/src/cmd/test.rs, forge/Cargo.toml, forge/src/decode.rs, forge/src/executor/abi.rs, forge/src/executor/builder.rs, forge/src/executor/fuzz/mod.rs, forge/src/executor/inspector/cheatcodes/env.rs, forge/src/executor/inspector/cheatcodes/expect.rs, forge/src/executor/inspector/cheatcodes/ext.rs, forge/src/executor/inspector/cheatcodes/fuzz.rs, forge/src/executor/inspector/cheatcodes/mod.rs, forge/src/executor/inspector/cheatcodes/util.rs, forge/src/executor/inspector/logs.rs, forge/src/executor/inspector/macros.rs, forge/src/executor/inspector/mod.rs, forge/src/executor/inspector/stack.rs, forge/src/executor/mod.rs, forge/src/lib.rs, forge/src/multi_runner.rs
**In draft while I address the remaining items**
Ports all the cheatcodes to REVM in a cheatcode-specific inspector. The cheatcodes have been split up into different modules so we don't end up with a huge file like we had with Sputnik, because we can.
This PR also incldues an update to ethers, which we needed to bump `primitive-types` (needed by `revm`), but it also brought in a lot of other changes. I tried to resolve the breaking changes as best I could, but I'm sure it was changed differently on master.
Also adds `InspectorStack` which is an inspector that calls a bunch of underlying inspectors.
Using my branch of revm until https://github.com/bluealloy/revm/pull/69 is merged.
Remaining items:
Some questions:
- ~~In our `record`/`accesses` test we assert that 2 reads have taken place …
=> REVM cheatcodes

Cargo.lock, cli/src/cast.rs
This PR addresses an issue with the `cast compute-address` subcommand where the computed address is truncated.
Since the computed address from a `cast compute-address` call is printed to console, we need to use debugging format to print the full H160 rather than a truncated `0xXXX...XXX`.
Solution: change the output template string from `{}` to `{:?}`.
=> fix(cast): compute-address ouput not debugged

README.md
Fix installation instructions when using `cargo`.
=> readme: Fix cargo installation instructions

Cargo.lock, cli/src/cmd/build.rs, cli/src/cmd/flatten.rs, cli/src/cmd/verify.rs, config/README.md, config/src/lib.rs
As mentioned in #750 , a user may want to store the cached output from compiling contracts in a different directory.  
`ethers-solc` has an option for this already, so the change is fairly straightforward.
I've added an additional option:`cache_path` to the `BuildArgs` so users can specify the path of the cache.  
I also updated the default config and the docs to reflect this change.
I did not add any new tests.
=> feat(forge): Add `cache-path` option

Cargo.lock, cli/src/cmd/mod.rs, cli/src/cmd/tree.rs, cli/src/forge.rs, cli/src/opts/forge.rs
~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/933~~
add `forge tree`
=> feat(forge): add tree command

cli/src/cast.rs, cli/src/cmd/fmt.rs, cli/src/opts/mod.rs
Fixes #838 
(driveby: default RPC url to http://localhost:8545, cc @tynes)
=> fix(cast): allow using `--from` and `ETH_FROM` with `cast send`

cli/src/cmd/inspect.rs, cli/src/cmd/mod.rs, cli/src/forge.rs, cli/src/opts/forge.rs, cli/tests/cmd.rs
Introduces an `inspect` subcommand for `forge` that outputs one of `{ir, bytecode}` for a given contract as specified by #859 
Implement the following modes for `forge inspect <CONTRACT> <MODE>`
Compilation Suppression
Example compilation output:
Override Compiler Optimization for certain `ContractArtifactFields` variants
Extra Output Fixes
=> feat(forge): forge inspect subcommand

cli/src/cmd/inspect.rs
The `forge inspect` command has inconsistent matching when parsing as a string.
As shown below, there is a mix between kebab-casings, snake-casings, camel-casings, etc etc.
Add verbose matching patterns.
=> fix(forge/inspect): Inconsistent Mode Matching

Cargo.lock, evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
If we wanted to read a Hardhat-tpe artifact, deserialization would fail because the artifact has `"bytecode": "0x1234"` whereas the CompactcontractBytecode artifact has `bytecode: { link objects, source, etc }`
=> fix(cheats): getCode compatibility with hardhat-style artifac

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
Currently, ffi decoding removes the first two characters in the hex string indiscriminately, assuming they are "0x". This is surprising behaviour, which can confuse users. Even for experienced users, this causes inconveniences, since they often have to manually add "0x" to their payloads when using this cheatcode. See https://github.com/gakonst/lootloose/blob/master/scripts/metadata.js#L30 as an example of this behaviour. 
This PR introduces a check to see if the first two characters are indeed "0x" before trimming. This should be backwards compatible 
I tried writing a test but it seems like FFI tests are currently disabled for non-unix systems (is this being fixed?). I did some manual verification and this seems to work with both cases.
=> Make FFI hex string decoding more flexible 

utils/src/lib.rs
Pretty printing is useful even if no sig is found on 4byte. Also we state in the description that we only print signature **if** available, so we shouldn't be failing if no signature found.
Provide default empty vector if no sigs found.
=> feat(cast/pretty-calldata): do not fail if no 4byte sigs found

Cargo.lock, cli/src/term.rs
~~**BLOCKED BY** ~~https://github.com/gakonst/ethers-rs/pull/1026~~ https://github.com/gakonst/ethers-rs/pull/1027~~
To improve user feedback on 
- unresolved imports (indicates misconfigured remappings) also provide the current remappings
- solc install errors
=> chore(solc): provide remappings on unresolved import message

cli/tests/cmd.rs, config/src/lib.rs, evm-adapters/src/sputnik/forked_backend/cache.rs, evm-adapters/src/sputnik/forked_backend/rpc.rs, evm-adapters/src/sputnik/state.rs
Closes #938
Previously we didn't ignore this error by default
* add `SolidityErrorCode` enum
* ignore `SolidityErrorCode::SpdxLicenseNotProvided` by default
=> feat(config): ignore spdx license not provided warning by default

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/cmd/mod.rs, cli/src/cmd/run.rs, cli/src/cmd/test.rs, cli/src/forge.rs, cli/src/opts/evm.rs, cli/src/opts/forge.rs, cli/test-utils/src/util.rs, cli/tests/cmd.rs, forge/src/debugger.rs, forge/src/executor/builder.rs, forge/src/executor/fuzz/mod.rs, forge/src/executor/inspector/debugger.rs, forge/src/executor/inspector/mod.rs, forge/src/executor/inspector/stack.rs, forge/src/executor/inspector/tracer.rs, forge/src/executor/inspector/utils.rs, forge/src/executor/mod.rs, forge/src/executor/opts.rs, forge/src/lib.rs, forge/src/multi_runner.rs, forge/src/runner.rs, ui/Cargo.toml, ui/src/lib.rs
Ports the debugger to the new REVM executor, greys out zero values in the stack and memory, and adds support for running functions with arguments
**To do**
**Nice to have**
Closes #758 
Closes #761
=> REVM debugger

forge/src/multi_runner.rs, forge/src/runner.rs, forge/testdata/WarmColdTest.sol
fixes issues raised in this thread: https://twitter.com/brockjelmore/status/1504117274726342658?s=20&t=rJdFbrrfOeB8DocpF_apwg
since we reuse the evm after setup, the access list wouldnt get reset. so effectively, if you do a bunch of state changes inside setUp, those addresses and slots would be warm instead of cold in a test call
=> fix(forge): Access list not resetting after setUp

Cargo.lock, cli/src/cmd/run.rs, cli/tests/cmd.rs, forge/Cargo.toml, forge/src/executor/fuzz/mod.rs, forge/src/executor/inspector/debugger.rs, forge/src/executor/inspector/tracer.rs, forge/src/executor/inspector/utils.rs, forge/src/executor/mod.rs, forge/src/runner.rs, utils/src/lib.rs
- Accounts for refunds in traces and the debugger
- Removes the gas stipend
- Merges `call_raw` and `call_raw_committing`
There's a weird issue with refunds/stipends that I will have to investigate more. The behaviour can be observed when running tests in https://github.com/anticlimactic/foundry-issue with traces on.
We should also consider upstreaming a flag or similar in REVM that just skips the stipend
Closes #812
=> REVM gas fixes

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/expect.rs, forge/README.md
Tested with https://github.com/onbjerg/foundry-test/blob/master/src/cheats/ExpectRevert.t.sol#L102-L108
Closes #885
=> feat: better ux for expect revert without reason

Cargo.lock, evm/src/executor/inspector/cheatcodes/env.rs, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/debugger.rs, evm/src/executor/inspector/logs.rs, evm/src/executor/inspector/stack.rs, evm/src/executor/inspector/tracer.rs
Correctly apply `msg.sender` prank to both transfers and calls. Previously the sender was changed, but after we had already checked if our previous non-pranked sender had enough funds for any transfers in the call. 
With https://github.com/bluealloy/revm/pull/84 we know apply the prank in `call` and `create` before this check happens. 
Unfortunately, this is also before the call depth is increased, so there is some annoying depth math involved
=> fix: fix prank cheatcode

forge/README.md
The new added hevm cheat code  `label` and `assume` are not updated on the forge readme page.
I appended the new  hevm cheat code  `label` and `assume` under the forge readme's `Cheat codes`
=> Update forge readme with new hevm cheatcode

evm-adapters/src/call_tracing.rs, utils/src/lib.rs
Fondry is not decoding error selectors for `expectRevert(bytes4)` cheatcode.
Sample code:
```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.12;
import { Vm } from "forge-std/Vm.sol";
import { DSTest } from "ds-test/test.sol";
error A();
contract DecodeSelectorTest is DSTest {
Vm internal vm = Vm(HEVM_ADDRESS);
function testExpectRevertBytes4() external {
vm.expectRevert(A.selector);
this.revertA();
}
function revertA() external pure {
revert A();
}
}
```
Current output:
```log
Running 1 test for DecodeSelectorTest.json:DecodeSelectorTest
[PASS] testExpectRevertBytes4() (gas: 3638)
Traces:
[3638] DecodeSelectorTest::testExpectRevertBytes4()
├─ [0] VM::expectRevert(0xf446c1d0)
│   └─ ← ()
├─ [164] DecodeSelectorTest::revertA()
│   └─ ← "A()"
└─ ← ()
```
Decode the …
=> feat(utils): decode `expectRevert(bytes4)` cheatcode

Cargo.lock, Cargo.toml, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/logs.rs, evm/src/executor/inspector/stack.rs, evm/src/executor/inspector/tracer.rs, evm/src/executor/inspector/utils.rs
Uses the `Inspector::log` hook in REVM. Blocked by https://github.com/bluealloy/revm/pull/85
=> refactor: use revm `log` hook

cli/README.md, cli/src/cmd/install.rs, cli/src/opts/forge.rs
In `forge --help` output, the install command description was not sentence cased
1. Capitalize "Installs" in `forge --help` output
2. Update cli/README.md with most recent `forge --help` output
=> Capitalize install in `forge --help`

evm/src/executor/mod.rs, evm/src/fuzz/mod.rs, evm/src/fuzz/strategies/calldata.rs, evm/src/fuzz/strategies/mod.rs, evm/src/fuzz/strategies/param.rs, evm/src/fuzz/strategies/state.rs
Supersedes #731 
Currently some missing things:
Co-authored-by: brockelmore <31553173+brockelmore@users.noreply.github.com>
=> REVM fuzz dictionary

cli/src/cmd/install.rs
`forge install` eats unknown errors and fails silently, reporting a successful install when there wasn't one.
`install_as_submodule` now handles a (common?) error related to `git submodule add` failing when the added path is blocked by `.gitignore`.
In addition a catch-all was added to `install_as_submodule` and `install_as_folder` to report unexpected errors instead of failing silently.
The `--quiet` flag was added to prevent `git` from sending info messages to `stderr`, which is its default behavior.
=> feat(forge): Expand forge install error handling

.dockerignore, Dockerfile, cli/src/cmd/mod.rs
I have tasks that need to run in the cloud where bringing up a K8s pod
that I can attach to with `cast` would be nice. A docker image is required
for this and I'm sure other people would want a docker image so putting
the dockerfile here makes sense.
This commit creates a docker image that includes
both `cast` and `forge`.
It builds off of https://github.com/gakonst/foundry/pull/914.
The image comes out to 26.4MB.
```bash
/ # du -h /usr/local/bin/forge
12.8M   /usr/local/bin/forge
/ # du -h /usr/local/bin/cast
7.1M    /usr/local/bin/cast
```
Example usage:
```bash
$ docker run --rm --entrypoint cast foundry:latest block --rpc-url https://mainnet.optimism.io latest
$ docker run --rm foundry:latest 'cast block --rpc-url https://mainnet.optimism.io latest'
```
Co-authored-by: Abdul Rabbani …
=> feat: alpine based docker image

evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
The stderr output of an FFI process currently gets ignored making it hard to debug FFI commands.
This PR instead pipes the process stderr to forge's stderr. This allows use of `console.error(...)` and equivalents to get output and debug FFI scripts.
=> feat(forge): stderr output for ffi processes

evm/src/fuzz/mod.rs
The fuzzer was failing some fuzz tests in Solmate and I thought it shouldn't, but it turns out that it was correct - the reason the test failed was just incorrectly reported.
Essentially, proptest will run at least 1 more case after it finds a failure in an attempt to find the smallest failure case. This changes the input, which changes the reported calldata. Since we also overwrote `call` every time we ran a case, we would get the incorrect traces, logs and calldata.
See: https://github.com/gakonst/foundry/pull/918#issuecomment-1074973151
=> fix: report correct fuzz failure case

evm/src/executor/fork/backend.rs, evm/src/storage/diskmap.rs
Ensure the program lives longer than the BackendHandler needs to flush storage cache
if the last `SharedSender` is dropped, we tell the BackendHandler to shutdown and await an ack to make sure the BackendHandler can flush Storage cache.
=> fix(evm): gracefully shutdown backendhandler

evm/src/executor/builder.rs, evm/src/executor/mod.rs, evm/src/executor/opts.rs, forge/src/multi_runner.rs
Contains some fixes encountered when running Spells mainnet. We should push out a new nightly as well to make sure this does not affect anyone
Works now, 1 failing test, unsure if unrelated:
```
Failed tests:
[FAIL] test_bytecode_matches() (gas: 2838891)
Encountered a total of 1 failing tests, 19 tests succeeded
```
=> fix: deployment in forks

config/src/lib.rs
Resolves #970 
Resolves #1008
Pass configured `config.test` path  to `ProjectPathsConfig` builder.
Note: it looks like the reason forge finds tests in `src/test` is not because this path is set or inherited from config, but simply because solc will find and compile any contract in any subdirectory of `src`.
=> fix(config): test path configuration

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
* Inspired by etherscan.deth.net, this feature will expand a verified contract's
source code paths to a directory for easy consumption with your favorite
editor / IDE.
* Tested via the following examples that test a few of the edge cases.
> cargo run --bin cast -- etherscan-source 0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63 -d blitmap
This results in a directory tree with all the source files of the contract.
> cargo run --bin cast -- etherscan-source 0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413 -d thedao
This results in a single file output.
> cargo run --bin cast -- etherscan-source 0xb5c31a0e22cae98ac08233e512bd627885aa24e5 -d unverified
This returns an error since the following contract is not verified yet on Etherscan
When learning about smart contracts it is a nice improvement to able …
=> feat(etherscan directory output)

foundryup/foundryup
Moves some foundryup stuff into utility functions and also displays installed versions after running `foundryup`.
Example output:
```
foundryup: installing foundry (version nightly, tag nightly-e881b75ac99687e2a20d9274b67a1e492dec6dd2)
foundryup: downloading latest forge and cast
################################################################# 100,0%
foundryup: downloading manpages
################################################################# 100,0%
foundryup: installed - forge 0.2.0 (e881b75 2022-03-25T00:03:11.855335753+00:00)
foundryup: installed - cast 0.2.0 (e881b75 2022-03-25T00:03:11.855335753+00:00)
foundryup: done
```
Tested locally by overwriting the foundryup script
Closes #936
=> refactor: clean up `foundryup` and print versions

cli/src/cast.rs, cli/src/cmd/cast/find_block.rs, cli/test-utils/src/macros.rs, cli/test-utils/src/util.rs, cli/tests/cast.rs, cli/tests/cmd.rs
`cast find-block` crashes since the Command abstraction introduced a nested tokio runtime bug.
This PR introduces a few small changes to bubble up the future created by querying the rpc for the block. It also adds a unit test for `cast find-block` as well as the supporting `test-utils` functions.
=> fix(cast): Fix Find Block Nested Tokio Runtime

cli/src/opts/cast.rs
On account of https://github.com/onbjerg/foundry-book/pull/134#discussion_r835773938 fixes the typo in the cast cli.
=> docs: fix typo in cast find-block

Cargo.lock, ui/Cargo.toml, ui/src/lib.rs
Showcase memory changes in debugger
Color reads as cyan, soon to overwrite as red, and just overwrote as green. see screenshots:
About to overwrite:
Just overwrote (see previous op is `MSTORE`):
Read:
(ignore that the dimming and such doesnt work on my terminal. weird alacritty settings)
=> feat(forge): colored memory words

foundryup/README.md, foundryup/foundryup
Fixes https://github.com/gakonst/foundry/issues/1054
+ --pr/-P: checks out refs/pull/$PR/head branch
* minor refactoring of the 'compile from sources' path: combine 'checking out for the 1st time'
and 'checkout out for the nth time' flows. The latter used to do `git fetch && git reset --hard`,
they now both do 'git fetch && git checkout'. There should be no good reason for you to have local
changes in ~/.foundry, so there's no point in `git reset --hard`. Less code == better
Would be great to have another pair of hands to **test** this
=> foundryup: --pr (-P) argument to check out a PR

.github/workflows/test.yml
ring is not compatible with current nightly, this pins nightly toolchain to a version prior to that
https://github.com/rust-lang/rust/issues/95267
=> ci: use nightly-2022-03-20 before ring regression

ui/src/lib.rs
We were extremely sensitive to window size. Additionally, when stack and memory were too large, the user couldn't inspect tail elements. Also sometimes the user will store string in memory, where weren't decoded into string.
This adds dynamic sizing and a vertical view. Additionally, the user can now scroll memory and stack elements with `ctrl + j/k` and `shift + j/k`, respectively. Finally, we also add the ability to toggle memory decoding with  `m`.  Any non-null unicode characters are decoded. Null unicode  characters are replaced with  `.`.
Also fixes dimming issues by removing the color specifier in combination with `DIM`. This improves compatibility across terminals.
=> feat(forge/debugger): Dynamic layout, stack & memory scrolling

Cargo.toml
no need for customizing test profile.
opt-level 3 slows testing down so much that testing locally becomes unbearable
=> meta: remove test profile settings

.github/workflows/docker-publish.yml, .github/workflows/release.yml
We should release docker images alongside the binary releases.
Add a new github workflow file that builds, tags, and pushes the foundry docker image. The workflow is called as part of the Release Version pipeline and runs in parallel to the binary releases job matrix. 
The images will be pushed to `ghcr.io/gakonst/foundry:{master,latest}` when run manually and to `ghrc.io/gakonst/foundry:nightly-{sha}` when the nightly builds are run.
Job takes 20-25 min based on my testing. Here's an example [workflow run](https://github.com/dmfxyz/foundry/actions/runs/2045639908), and here is my forked[ ghcr repository](https://github.com/dmfxyz/foundry/pkgs/container/foundry)
=> Docker Pipeline for x86 Images

Cargo.lock, Cargo.toml, cli/src/cmd/forge/run.rs, evm/src/trace/decoder.rs, evm/src/trace/identifier.rs, forge/src/multi_runner.rs, utils/src/lib.rs
Sometimes contracts were not identified in traces because there were multiple contracts with the same name and `known_contracts` (which we use for lookups) was indexed by the contract name and nothing more.
First I thought we could just index by `artifact_id.slug()` but both of these contracts had the same slug as well, so now `known_contracts` is indexed by `ArtifactId`. This required changes in the linking step as well as the debugger.
Another issue mentioned in #1057 was that precompiles were not decoded, which will also be addressed in this PR.
**Remaining tasks**
Closes #1057
=> fix: various trace fixes

cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test.rs, cli/src/forge.rs, forge/src/runner.rs
Closes https://github.com/gakonst/foundry/issues/1081
=> forge: keep fuzz snapshots behind a flag

cli/src/cmd/forge/run.rs
In #1067 we used ArtifactId in forge run, but the condition for finding the target contract is not correct for forge run without target contract.
=> fix(run): use correct condition to compare contract paths

forge/src/gas_report.rs
We still need more robust test contract filtering. It is not possible for us to do what we did before (i.e. filter out contracts that have an `IS_TEST`) because we just access decoded traces directly instead of ABIs.
=> fix: remove `setUp` from gas reports

Cargo.lock, Cargo.toml, config/src/lib.rs, evm/Cargo.toml, evm/src/executor/fork/init.rs, evm/src/executor/opts.rs
Raises the gas limit to a high number again but limits memory expansion to prevent memory allocation errors.
Companion PR: https://github.com/bluealloy/revm/pull/86
=> fix: raise gas limit while limiting evm mem size

evm/src/trace/decoder.rs
Events can share the same topic 0 but have different indexed parameters. This is due to the fact that event 0 is `<event name>(<comma-separated parameter types>)`, e.g. `Transfer(address,address,uint256)`.
The issue with this is that logs that share the same topic 0 might be encoded and decoded in different ways depending on the indexed parameters. For example, ERC720's `Transfer` event has all parameters indexed, but ERC20's `Transfer` event only has the first two parameters indexed.
For codebases that have both ERC20s and ERC721s this presents an issue: only some of the `Transfer` events are decoded.
Solutions I've explored:
Would result in a lot of duplicate events
Consider these events:
```solidity
event MyEvent(
uint256,
uint256 indexed,
uint256 indexed,
uint256 indexed
)
``` …
=> fix: decode different events with same topic 0

cli/src/cmd/forge/run.rs
Follow up on #1089
Closes #1048
=> fix: correctly find contract in `run`

cli/src/cmd/forge/test.rs, forge/src/lib.rs, forge/src/multi_runner.rs, forge/src/runner.rs
Resolves #1004 
Print a summary including pass/fail count and duration after each test suite block.
- `runner.rs`: Refactor map of test names/results to a `SuiteResult` struct that stores run duration and results.
- `test.rs`: Format and print summary following each suite run.
- I am pretty new to Rust, so all comments are very welcome. This is mostly compiler-driven development.
- No ignored count yet.
=> feat(forge/test): testrunner block summary

Cargo.lock, Cargo.toml, cli/src/cmd/forge/test.rs, forge/src/lib.rs, forge/src/multi_runner.rs, testdata/core/DappToolsParity.t.sol
Companion PR: https://github.com/gakonst/ethers-rs/pull/1087
Before and after:
```
~/Projects/github/onbjerg/failures master*
❯ forge test
[⠒] Compiling 3 files with 0.7.0
Running 1 test for ContractTest.json:ContractTest
[PASS] testExample() (gas: 24964)
~/Projects/github/onbjerg/failures master*
❯ forge test
[⠒] Compiling 3 files with 0.7.0
Running 1 test for /home/oliver/Projects/github/onbjerg/failures/src/test/Contract.t.sol:ContractTest
[PASS] testExample() (gas: 24964)
Running 1 test for /home/oliver/Projects/github/onbjerg/failures/src/test/Contract.t.2.sol:ContractTest
[PASS] testExample() (gas: 24964)
```
**Remaining tasks**
Closes #1062 
Closes #392
=> fix: display test results for tests with same name

cli/tests/cmd.rs
8f6d5a57b2e5f0d4 removed ds-test remappings which broke the `can_init_repo_with_config` this resulted in a SIGILL inside the `pretty_assert::assert_eq!`, which was caused by a panic inside a Display impl of a pretty_assert type. 
SIGILL usually happens when there's a panic inside the panic! message formatting. 
update the test to ignore remappings check
=> fix(test): update test to match new init behavior

cli/tests/config.rs
This should prevent some hiccups during solc install when integration tests and can_use_solc by deliberately using a version not used by integration tests.
=> fix: use a different solc version than for testing the --use arg

evm/src/executor/builder.rs, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/mod.rs, evm/src/executor/inspector/stack.rs, evm/src/executor/mod.rs, forge/src/multi_runner.rs, testdata/cheats/Setup.t.sol
Persist cheatcode state from `setUp` and constructor to allow for patterns like:
```solidity
contract MyTest is DSTest {
// ...
function setUp() {
cheats.startPrank(address(1));
}
}
```
=> fix: persist cheatcode state from setup

cli/tests/cmd.rs, cli/tests/config.rs
while pretty_assertions is helpful for debugging locally, it is a constant issue within CI with failing tests and SIGILL, which happens because `pretty_assertions` error messages that get formatted within a panic can panic themselves.
=> chore: remove pretty_assertions in favor of core assert_eq

.github/workflows/test.yml, cli/tests/it/integration.rs
Currently the cache is never rebuilt. Usually you would rebuild if a lockfile changed but we don't really have that, so instead we rebuild the RPC cache if the external integration tests change
=> ci: create rpc cache based on tests

cli/src/cmd/forge/init.rs
When i follow the Official Example on
https://onbjerg.github.io/foundry-book/projects/creating-a-new-project.html
`forge init --template https://github.com/FrankieIsLost/forge-template hello_template`
`forge build`
Forge returns an error
If other libraries are referenced in the template
Forge does not use recursion to clone the entire template
Add `--recursive` flag in `cli/src/cmd/forge/init.rs`
=> Add "--recursive" When use "--template" flag

evm/src/executor/inspector/cheatcodes/expect.rs
If we expect a custom error but a call reverts with a string we get a bunch of replacement characters which is pretty unreadable. See #1007.
Instead of doing `String::from_utf8_lossy` we instead fallback to encoding as hex if we get invalid UTF8. The alternative is passing ABIs to the executor, then to the cheatcode handler, and decoding that way
Closes #1007
=> fix: hex encode if we dont expect a string

Cargo.lock, cli/test-utils/Cargo.toml, cli/test-utils/src/util.rs
fix a race condition related to the cwd.
when creating a new `forgetest!` we acquire the cwd so that we can rest it after the test is dropped so that we can set the cwd in tests (useful for tests working with Config). 
However cwd is a shared across all tests so if we do ` cmd.set_current_dir(prj.root());` the cwd is now the project root, which gets wiped once the project is dropped but tests that get created in the meantime are directed to that dir.
* use the cwd lock before creating a new forgetest! 
* use parking_lot Mutex to prevent that poisoned mutex blows up all tests regardless.
**Note**
as a side-effect, tests that make use of cwd are now effectively executed sequentially
=> fix: proper cwd locking in tests

cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test.rs, cli/src/forge.rs, forge/src/runner.rs
After some discussion with @mds1 we agreed that it would still be useful and cause no harm to always include fuzz test gas estimates in the standard test output. 
Refactored the work done in https://github.com/gakonst/foundry/pull/1086 to be limited only to snapshot exports.
May effect work done in https://github.com/gakonst/foundry/pull/1130 and work planning to be done in https://github.com/gakonst/foundry/issues/1088
=> forge: only hide fuzz tests from snapshots (still show in tests)

forge/README.md
The DOCS are referencing the old `dapp` CLI instead of the `forge` CLI.
=> Fix stale dapp references in forge README

cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test.rs, cli/src/forge.rs, forge/src/multi_runner.rs, forge/src/runner.rs
closes https://github.com/gakonst/foundry/issues/1136
this is a significant speedup for solmate, from ~5.1s -> <1s
=> forge snapshot: don't execute fuzz tests at all by default

foundryup/foundryup
I had a local implementation that already addressed #1135. Putting up for review since it was opened as a feature request,.
This allows for a specific commit to be installed from foundry
Add a new `-C|--commit` arg that checkouts the supplied commit after pulling the desired repo and branch.
=> feat(foundryup): support installing at specific commit

Dockerfile
I fat-fingered the docker file and had "/bin/sh -c" as as single entrypoint command, which prevents the better UX of being able to pass a string of a full foundry command directly to the image via stdin.
Prior Experience
```sh
$> docker run foundry:nightly 'cast --rpc-url $RPC_URL vitalik.eth'
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh -c": stat /bin/sh -c: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled
```
Prior Workaround:
```sh
$> docker run --entrypoint cast foundry:nightly 'resolve-name' --rpc-url $RPC_URL vitalik.eth
0xd8da6bf26964af9d7eed9e03e53415d37aa96045
```
New Experience w/ Fix
```sh 
$>docker run foundry:nightly …
```
=> fix: Docker entrypoint

cli/src/cmd/forge/run.rs
There's a bug in branching. `forge run ./some.sol` won't work without a `--target-contract` being specified even in cases when the sol file would only have one contract. If the whole repo only contains a single solidity file, it'll work, if there are multiple and you happen to start iterating over artifacts on any other contract it will fall into the else branch which assumes target contract is specified and will panic with index out of bounds.
=> fix(forge/run): fix branching for if no target contract specified

foundryup/foundryup
Users often get confused if they previously installed forge/cast via cargo and now run foundryup to seemingly have no effect (because cargo bin takes priority)
Warn users if the location of the forge/cast binaries have cargo in them
=> feat(foundryup): warn users if already installed via cargo

foundryup/install
- resolves https://github.com/gakonst/foundry/issues/1169
- macos users may not have the required `libusb` dependency.
- per comments here: https://github.com/gakonst/foundry/pull/501#discussion_r840603359
This pr checks for mac's darwin os & prints a warning to install libusb if it is currently missing.
Example warning below:
```zsh
Installing foundryup...
###################################################################################################### 100.0%
warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb).
Detected your preferred shell is zsh and added foundryup to PATH. Run 'source ~/.zshrc' or start a new terminal session to use foundryup.
Then, simply run 'foundryup' to install Foundry.
```
=> add libusb warning for users with mac os

evm/src/executor/inspector/tracer.rs
The `prank` cheatcode is only applied to a contract creation after starting the trace which leads to recording the contract address wrongly. And consequently messing up the labeling/decoding further on.
Make sure to update the address on `create_end()`
before:
```
[PASS] testScenario() (gas: 501392)
Traces:
[501392] NestVestTest::testScenario() 
├─ [0] VM::prank(0x0000000000000000000000000000000000001337, 0x0000000000000000000000000000000000001337) 
│   └─ ← ()
├─ [460706] → new NestVest@0xce71065d4017f316ec606fe4422e11eb2c47c246
│   └─ ← 2188 bytes of code
├─ [2625] 0x03f1…73f5::claimable() [staticcall]
│   └─ ← 499999999999999993344000
└─ ← ()
Test result: ok. 1 passed; 0 failed; finished in 867.52ms
```
after:
```
[PASS] testScenario() (gas: 501392)
Traces:
[501392] …
```
=> fix/forge: update address value from trace on `create_end`

Cargo.lock, Cargo.toml, cli/src/term.rs
Resolves #1125 
Print time spent compiling the project.
Print duration passed to `SpinnerReporter`. Depends on [gakonst/ethers-rs/#1098](https://github.com/gakonst/ethers-rs/pull/1098). 
This does look a little odd: when there is a lot of compiler output to display, the spinner will keep spinning for a few seconds, even though compilation is finished. (See the GIF above).
=> feat(forge): print compile time

Cargo.lock, cast/Cargo.toml, cast/src/lib.rs, cast/src/tx.rs, cli/src/cast.rs, utils/src/lib.rs
Refactoring to move away from function-with-hundred-arguments to a Builder pattern
Fixes https://github.com/gakonst/foundry/issues/937
TxBuilder constructs the tx on the fly, that's why the interface is not super consistent (`args()` returns a future result, while other setters return &mut self), and provider needs to be passed to some of the setters. 
Alternatively, I can change TxBuilder to be just a glorified bag-of-arguments, and leave the actual transaction building in lib.tx. The downsides will be: 1) we'll still have 1 gigantic function that need to handle every field in TxBuilder; 2) it'll use a bit more memory
I'm not 100% confident in my Rust, so plz check for dumb things
=> cast: s/build_tx/TxBuilder/

ui/src/lib.rs
It is difficult to scroll large amounts of memory
Add the ability to do `vim` style jumps to memory and stack movement, i.e.: `100 ctrl+j` scrolls memory by 100.
=> feat(forge/debugger): add vim number movement to modified j/k

evm/src/trace/decoder.rs
Decoding a malformed function input was crashing the decoder. eg:
```solidity
pragma solidity 0.8.12;
contract Contract  {
function testme(uint[] memory vars) public { }
function run() public {
address(this).call(abi.encodeWithSelector(this.testme.selector, 1));
}
}
``` 
Results in:
```
Traces:
Message:  bad function input decode: InvalidData
Location: evm/src/trace/decoder.rs:242
Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    60639 IOT instruction (core dumped)  forge run C.sol -vvvv
```
Replace `expect` with `match` and return an empty vector
```
Traces:
[991] Contract::run() 
├─ [242] Contract::testme() 
│   └─ ← ()
└─ ← ()
Script ran successfully.
Gas …
```
=> fix/forge: return empty vector on failing to decode input

forge/src/runner.rs
If you transferred eth in a fuzz test, and it happened to send to `msg.sender` of the test contract, then the test would fail, since the payment would overflow. This happens because we set the balance to `U256::MAX`.
Final bug for https://github.com/Rari-Capital/solmate/issues/182
Set the balance of `msg.sender` for the test contract to `self.initial_balance` in the contract runner. I am not sure if this lines up with DappTools
=> fix: correctly set `msg.sender`'s balance

cli/src/cmd/forge/test.rs, cli/tests/it/config.rs, config/README.md, config/src/lib.rs
add a config value to set sparse compile mode
a `--sparse` argument flag was deliberately not added because eventually we can make this the default. rn it's opt in via config file.
=> feat(config): make sparse mode opt in

forge/README.md
Switch to revm removed foundry's copy of console.log. This updates the readme to point to Hardhat's copy.
=> chore(docs): update console.log link to hardhat repo 

cli/tests/it/cmd.rs
latest BytecodeHash = None feature broke the `inspect` test that was stripping ipfs metadata
=> test: update failing inspect test

evm/src/executor/inspector/cheatcodes/expect.rs, evm/src/executor/inspector/cheatcodes/mod.rs, testdata/cheats/ExpectEmit.t.sol, testdata/cheats/Prank.t.sol
- `call` is called *before* the depth is increased. This effectively means that `depth` in `call` is the depth of the *current* call, and `depth + 1` is the depth of the call we are *about to execute*.
- `call_end` is called *after* the depth is decreased. This effectively means that `depth + 1` is the depth of the call that *just finished executing*
Implications:
- If `depth == 0`, then the *root call* (depth 1 during execution, but depth 0 in `call`/`call_end`) is terminating
- `depth + 1` represents the depth of the *call that is about to execute* in `call`, and the depth of the call that just finished executing in `call_end`
- `depth - 1` represents the depth at which the *current call will terminate* in `call` and `call_end`
- The call that is about to execute will terminate at …
=> fix: cheatcode depth fixes

Cargo.lock, cli/Cargo.toml, evm/Cargo.toml, forge/Cargo.toml
=> bump color eyre and lock tracing-subscriber

config/src/lib.rs
Integration tests were hanging
Because I pulled `--fork-url` from `ETH_RPC_URL` all the integration tests were running as if they were in fork mode :facepalm: So just undo that
=> test: fix integration tests

cli/src/opts/evm.rs, cli/test-utils/src/macros.rs, cli/test-utils/src/util.rs, cli/tests/it/config.rs, config/src/lib.rs
Adds support for `ETH_RPC_URL` in place of `--fork-url`, but does not break integration tests this time
=> fix: enable `ETH_RPC_URL`

cli/src/cmd/forge/run.rs, evm/src/executor/builder.rs, evm/src/executor/fork/backend.rs, evm/src/executor/mod.rs, evm/src/executor/opts.rs, forge/src/lib.rs, forge/src/multi_runner.rs
@mattsse could you please test this?
at least with central tokio runtime inited in main (my setup), it's no problem to rely on BackendHandler::drop.
if it is necessary to distinguish between "all work finished" vs RapidUnscheduledDisassembly, we can set a flag in `poll`.
=> fix(evm): backend shutdown sequence

Cargo.lock, cli/src/cmd/forge/verify.rs
https://github.com/gakonst/foundry/issues/1012
and this bug
https://github.com/gakonst/foundry/issues/1236
This changes will allows `forge` to submit contract verification using `standard-input-json` by default.
It puts the file flattening behind `--flatten` flag.
Example of verified contract https://rinkeby.etherscan.io/address/0x824436cf3d2cd06de925586490aa4c0e83345276#code
--
Blocked by https://github.com/gakonst/ethers-rs/pull/1126
=> feat(forge): Add support for multiple files verification

Cargo.toml
Compiling with release mode is absolutely abysmal because of size optimization, code genunits 1 etc., which makes testing locally with release conditions a bit tedious.
This adds another profile `local` that's more close to the default rust release profile but also allows incremental builds.
this is ~35% faster than release while also being opt.3
=> meta: add local profile

config/README.md, config/src/lib.rs
while bytecode hash None ensures deterministic builds it caused issues with etherscan verify with flattened code.
Since this is no configurable, I suggest we make the default `ipfs` just like solc.
=> chore: make ipfs the default bytecodehash again

cli/src/cmd/forge/create.rs
[## Motivation
Addresses #1255
Add a `--json` argument, matching the behavior for `cast` commands, to the `forge create` args.
Without `--json`
```sh
$> forge create --private-key $PRIVATE_KEY src/Contract.sol:Contract
Deployer: 0x496e09fcb240c33b8fda3b4b74d81697c03b6b3d
Deployed to: 0x878354b96c2736d527ddb40bc3f4f30fc1a71b7c
Transaction hash: 0xefe1577d0b37a6403ea653e2a65f0a7d3f3b5dbf47708fbffcb4595e108a2090
```
With `--json`
```sh
$>  forge create --private-key $PRIVATE_KEY --json src/Contract.sol:Contract
{"deployedTo":"0x3836857cec81c98e105ec0309ddeb0b08e2d7b96","deployer":"0x496e09fcb240c33b8fda3b4b74d81697c03b6b3d","transactionHash":"0x8e07c35e7daf2439663f3283a5d652b9a722ba41c55f461246769aa044ac1b67"}
```
Example usage with `jq` …
=> feat(forge): json output option for forge create

cli/src/cmd/forge/verify.rs
Verify-contract is a bit of a mess.
- use `eyre::WrapErr` to avoid erasing error info
- break complex code out to functions
- add a useful error message for flatten with ipfs bytecodehash
=> refactor: improved verify-contract legibility

cast/src/lib.rs, cast/src/print_utils.rs
cast cli output isn't quite consistent with seth as outlined in [issue 1193](https://github.com/gakonst/foundry/issues/1193).
I've added a simple trait `UIfmt` which has a function `pretty`. `pretty` returns the string that represents the underlying value formatted based on its type. Sounds overly complex, I format the string in the trait impl. 
Most of the code can be found in [print_utils](https://github.com/gakonst/foundry/pull/1253/files#diff-628bbf828c50cd089356578a4e117310ff641d5cf98163a69dc5f8fda2031c0d)
In order to handle similar `field` usage eg. 
```
$ seth block latest timestamp
1649086807
```
I added get_pretty_<>_attr, which just maps from strings to struct properties. Doesn't seem like there is any easy way to dynamically access struct properties without manually managing a …
=> chore(Cast): improve ether_core cli printing #1193

cli/src/cmd/forge/run.rs, cli/src/cmd/forge/test.rs, forge/src/multi_runner.rs, forge/src/runner.rs, testdata/core/MultipleSetup.t.sol
Following conversation on https://github.com/gakonst/foundry/issues/1167 and https://github.com/gakonst/foundry/pull/1276 this PR adds:
- warnings for when there is a single miss-cased `setUp` function
- returns test run error when there are multiple `setUp` functions with different cases
- return single `SuiteResult` if we detect multiple setUp functions
- Added warnings to `SuiteResult` and pushes a warning if there is a single miss-cased `setUp` function
=> Feature: warning for miss-cased setUp function

cast/README.md
Link to Cast section of foundry-book was dead / outdated. (error 404)
See screenshot:
Fix by adding link to: https://book.getfoundry.sh/cast/index.html
=> chore: Fix broken link to cast documentation

cli/src/cmd/forge/create.rs
As some of the chains require custom gasLimit value in some transactions (as the one returned by eth_estimateGas, won't return sufficient value), gasLimit has been added as an overwrite flag to the create command.
Acala EVM+ supports storage rent, which is a deposit a user pays when storing something on chain. We do this to protest against chain data bloat and to motivate developers to clean up after themselves. `eth_estimateGas` RPC call returns values for 'ordinary' transactions, but we need to specify custom `gasLimit` value when deploying a smart contract. We need a way to do this.
The `--gas-limit` flag was added to the `create` call, which sets the custom `gasLimit` value of the transaction.
=> Added gas-limit to Forge create

cli/src/cast.rs, cli/src/cmd/cast/call.rs, cli/src/cmd/forge/bind.rs, cli/src/cmd/forge/build.rs, cli/src/cmd/forge/create.rs, cli/src/cmd/forge/flatten.rs, cli/src/cmd/forge/init.rs, cli/src/cmd/forge/inspect.rs, cli/src/cmd/forge/install.rs, cli/src/cmd/forge/remappings.rs, cli/src/cmd/forge/run.rs, cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test.rs, cli/src/cmd/forge/tree.rs, cli/src/cmd/forge/verify.rs, cli/src/cmd/forge/watch.rs, cli/src/forge.rs, cli/src/opts/cast.rs, cli/src/opts/evm.rs, cli/src/opts/forge.rs, cli/src/opts/mod.rs, cli/src/utils.rs
The output of `-h` and `--help` is inconsistent and sometimes not super helpful.
Goes through all help text and updates the wording. I also move some of the longer-form help text into `long_help` to shorten the output of `-h`.
I'm going through this as I am rewriting the command references in the book.
**Tasks**
=> chore: improve output of `-h/--help`

evm/src/trace/decoder.rs, evm/src/trace/mod.rs, evm/src/trace/node.rs, evm/src/trace/utils.rs, ui/src/lib.rs
the `decode` function was a bit much
split the function in several other functions and move some impl to the `CallTraceNode` itself.
this is still not great but at least the function is a bit smaller now
=> refactor(evm): split trace encoding in several functions

cli/src/opts/forge.rs
- Adds the ability to run `forge install` with git ssh urls (`git@github:`) and `git+` prefixed urls for copy paste reasons as described in this issue (https://github.com/foundry-rs/foundry/issues/924)
- Regex to match the string and pull out the brand name ie "github", "gitlab" and covert it to the `https://` repo url.
- Added tests for the additional cases.
=> feat: added support for git ssh urls

cast/src/lib.rs, cli/tests/it/cast.rs
fixes #1286
Fixes `cast find-block`.
Fixes broken `Cast::timestamp` function. See #1286 for an example.
There's already a unit test that could've caught this regression,`finds_block`. However, it requires `ETH_RPC_URL` and skips if that's missing.
Running `ETH_RPC_URL=<valid url> cargo test` fails before this PR, succeeds after.
=> fix: cast find-block

cli/src/cmd/forge/run.rs, cli/src/cmd/forge/test.rs, evm/src/trace/decoder.rs, evm/src/trace/identifier/local.rs, evm/src/trace/mod.rs
Contracts and libraries with 0 runtime bytecode would not be decoded, and sometimes they are used as "event containers".
Fixes #1309
=> fix: decode events for 0-sized contracts

cli/src/cmd/forge/install.rs, cli/src/forge.rs, cli/src/opts/forge.rs
Fixes #1267 
This changes allows user to install dependency on specific target directory
```
✦ forgedev install solrari=Rari-Capital/solmate
Installing solmate in "/Users/pyk/github/pyk/foundry-test-alias/lib/solrari", (url: https://github.com/Rari-Capital/solmate, tag: None)
Installed solmate
✦ forgedev install --no-git openzeppelin=OpenZeppelin/openzeppelin-contracts
Installing openzeppelin-contracts in "/Users/pyk/github/pyk/foundry-test-alias/lib/openzeppelin", (url: https://github.com/OpenZeppelin/openzeppelin-contracts, tag: None)
Installed openzeppelin-contracts
❯ forgedev remove solrari=Rari-Capital/solmate
Removing solmate in "lib/solrari", (url: https://github.com/Rari-Capital/solmate, tag: None)
Cleared directory 'lib/solrari'
Submodule 'lib/solrari' …
```
=> feat(forge): Add alias on install

fmt/src/formatter.rs, fmt/src/visit.rs
Baby steps
Implement `struct` formatting with copying fields from source code (for now)
=> feat(fmt): format struct (restoring fields from source for now)

cli/tests/it/config.rs, config/src/lib.rs, evm/src/executor/fork/init.rs, evm/src/executor/opts.rs, forge/src/lib.rs
I think 16 MiB is a sane default for most tests, but the symbolic project in #1310 in Solidity broke it.
We could raise the default memory limit, but I think a saner choice is just to make it configurable. Raising the default could slow down fuzz tests in e.g. Solmate that "accidentally"/randomly do `mload`/`mstore` in high memory regions
Closes #1310
=> fix: make memory limit configurable

assets/ContractTemplate.sol, assets/ContractTemplate.t.sol, assets/workflowTemplate.yml, cli/src/cmd/forge/init.rs
Solves some things in #1132 
- Loosens the pragma (and updating it to 0.8.13)
- Moves the test directory out of `src`
- Adds a Github workflow that runs `forge test -vvv` with `FOUNDRY_PROFILE=ci`
The Github workflow does not run by default, see https://github.com/foundry-rs/foundry/issues/1132#issuecomment-1082640211
Stuff missing because it's not in Forge:
- `forge test --sweep` (or similar)
- `forge build --verify-sizes` (or similar)
=> feat: forge init improvements

config/src/lib.rs
`DAPP_TEST_CACHE` is a path to the RPC cache for DappTools, but for us it tries to write it to `cache` which is a boolean
Closes #1187
=> fix: ignore `DAPP_TEST_CACHE`

fmt/src/formatter.rs, fmt/src/visit.rs
Formatter should format variable declarations. They occur in structs only now, but also will be in variable definitions where we should account for multiline case:
```bash
echo 'contract Contract { uint8 public str; }' | prettier --parser solidity-parse --print-width 1
contract Contract
{
uint8
public str;
}
```
Format variable declarations
=> feat(fmt): variable declaration

Cargo.lock, cli/Cargo.toml, cli/src/compile.rs
Closes (most of) https://github.com/foundry-rs/foundry/issues/992, except for the last bullet point in the description.
`forge build --sizes` now behaves as follows:
- Only reports sizes for non-test contracts and contracts with non-zero size. Test contracts are identified by any contract that either has a method that starts with `test` or a method called `IS_TEST`.
- Uses same table style as gas reports.
- Tables cells are highlighted yellow if over 18kB, and red if over the size limit. A margin column displays the difference between the contract size limit and its current size.
- Exits with error if any contracts are above size limit. This is analogous to `forge test` exiting with an error when a test fails, which is a useful behavior for checking sizes in CI
cc'ing @transmissions11 who …
=> feat: improve contract size reporting

Cargo.lock, fmt/Cargo.toml, fmt/src/formatter.rs, fmt/src/loc.rs, fmt/src/visit.rs
Recently, support for user-defined value types was added to Solang parser: https://github.com/hyperledger-labs/solang/pull/747. Let's start formatting it in Foundry.
Format user-defined value type definitions.
=> feat(fmt): user-defined value type definitions

Cargo.lock
Contains some fixes for `console.logBytes` formatting and closes #796 because of https://github.com/gakonst/ethers-rs/pull/1149
=> chore: bump ethers

cli/src/cmd/forge/fmt.rs
Currently, `forge fmt` accepts only files or directories as input for formatting. At least for debugging purposes (but for daily terminal usage too), it may be useful to pass stdin into the formatter.
Also, in `--check` and now in stdin modes we output diffs with changes. It may not be desired behaviour, so let's add a `--raw / -r` option to output raw formatted code.
Accept stdin in `forge fmt` command by piping output of the previous command or passing `-` as a path and introduce "raw" mode.
=> feat(cli, fmt): accept stdin, add "raw" mode with no diff

cli/src/compile.rs
closes https://github.com/foundry-rs/foundry/issues/1331
Went with kB instead of bytes with a comma separator because it was easier to implement and more in line with how I think about contract sizes
=> style: change contract size output table to kB for readability

fmt/src/formatter.rs, fmt/src/visit.rs
`solang::pt::Statement` is a enum, so we better match in in the `visit.rs` and call corresponding hooks for each of the variants.
Create visit function hooks for `solang::pt::Statement` variants, move logic there from one broad `visit_statement` that we've previously had.
=> refactor(fmt): visit functions for statements

.github/workflows/cross-platform.yml, .github/workflows/test.yml, .gitignore, Cargo.lock, Makefile, fmt/Cargo.toml, fmt/src/formatter.rs, fmt/testdata/ContractDefinitions/bracket-spacing.fmt.sol, fmt/testdata/ContractDefinitions/fmt.sol, fmt/testdata/ContractDefinitions/original.sol, fmt/testdata/EnumDefinitions/bracket-spacing.fmt.sol, fmt/testdata/EnumDefinitions/fmt.sol, fmt/testdata/EnumDefinitions/original.sol, fmt/testdata/ImportDirective/bracket-spacing.fmt.sol, fmt/testdata/ImportDirective/fmt.sol, fmt/testdata/ImportDirective/original.sol, fmt/testdata/StatementBlock/bracket-spacing.fmt.sol, fmt/testdata/StatementBlock/fmt.sol, fmt/testdata/StatementBlock/original.sol, fmt/testdata/StructDefinition/bracket-spacing.fmt.sol, fmt/testdata/StructDefinition/fmt.sol, fmt/testdata/StructDefinition/original.sol, fmt/testdata/TypeDefinition/fmt.sol, fmt/testdata/TypeDefinition/original.sol
Previously, we had test cases for formatter borrowed 🦀  from https://github.com/prettier-solidity/prettier-plugin-solidity. While it was a good starting point, there are several issues with that approach:
1. Parsing their snapshots is not obvious since its from JavaScript testing library.
2. We might wanna have our own test cases to cover some aspects of formatter and preserving that JS snapshots style is a pain.
Introduce our own test cases for the nodes that we know how to format continuing borrowing good ones from prettier-plugin-solidity.
=> test(fmt): introduce our own test cases

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/env.rs, forge/README.md, testdata/cheats/Cheats.sol, testdata/cheats/Travel.t.sol
Many contracts I test involve using chain ID so being able to modify it via a cheatcode to simulate e2e tests in foundry is useful.
This PR adds `travel(uint256)` which modifies `block.chainid` to the cheatcodes by modifying `data.env.cfg.chain_id`. Tests pass, though this could interfere with `permit`s and `Sign()` in testing.
Unike #997 #1103, this cheatcode does not persist in `setUp` since it modifies `CfgEnv` & not `BlockEnv`, which would require a much deeper change.
=> feat(cheatcode): chainId() - modify block.chainid

.github/workflows/project.yml
I created a GitHub project to provide a better overview of the issues in the repository, similar to the one for Foundry Book.
It can be found [here](https://github.com/orgs/foundry-rs/projects/2).
I don't expect people to actively use it (it's not a requirement), but I use it myself and find it helpful. The only annoyance is that issues manually need to be added to the project.
Add a workflow that automatically adds issues to the project.
I added my own PAT to the repository secrets with the correct scopes, so it should Just Work:tm:
=> ci: add project workflow

evm/src/executor/fork/backend.rs
When running `forge test` and `forge run` against a fork state, internal RPC failures **meant that the account or storage information was being used as `0` and cached as such.**. I had to bang my head a few times, and turn on tracing before I figured it out. :sweat_smile: 
Also, ref: #1294 
> EVM database interface doesn't support Result
Until then, I think it's better to panic than just to fail silently and use a 0 value.
=> forge(evm): Panic on RPC failure 

foundryup/foundryup
Title :point_up:
Existing docstring `Install a forks main branch` isn't completely correct.
Improve the docstring.
=> Improve docstring for --repo foundryup option.

Cargo.lock, evm/Cargo.toml, forge/Cargo.toml
removes the pin to `0.3.9` which was required because there was a parser issue in tracing's env filter
=> chore(deps): bump tracing-subscriber

Cargo.lock, cli/src/cmd/forge/build.rs, cli/src/cmd/forge/flatten.rs, cli/src/cmd/forge/verify.rs, cli/tests/it/config.rs, config/README.md, config/src/lib.rs
~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/1161~~
Closes #1375
Add `revert_strings` config var and argument
=> feat: add support for revert strings

cli/src/cmd/forge/build.rs, cli/src/cmd/forge/test.rs, cli/src/cmd/forge/watch.rs
cc @mds1 
watch test dir + src dir by default
=> feat(watch): also watch test dir by default

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/expect.rs, evm/src/executor/inspector/cheatcodes/mod.rs, forge/README.md, testdata/cheats/Cheats.sol, testdata/cheats/ExpectEmit.t.sol
https://github.com/foundry-rs/foundry/issues/1264
A second form of `expectEmit(...)` that takes an address to check against the emitting contract in case nested contracts can emit the same event.
Add a second form of `expectEmit(...)` with an address parameter. Internally, the emitting contract's address is forwarded to the log handler and checked against the supplied address.
Also, update docs and tests.
=> feat(forge): add expectEmit(...,address) for specifying emitting contract

cli/src/cast.rs
Fixes the following bug
```
> cast call dai balanceOf vitalik.eth
Message:  Must set ETHERSCAN_API_KEY
Location: /Users/runner/work/foundry/foundry/cast/src/tx.rs:162
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    52218 abort      cast call dai balanceOf vitalik.eth
> cast -V
cast 0.2.0 (92427e7 2022-04-23T00:08:21.719627+00:00)
```
=> Fix `cast call` etherscan bug

evm/src/executor/inspector/cheatcodes/mod.rs
Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
There is a redundant `0x` prefix in the `expectCall` cheatcode. 
Example:
```
[FAIL. Reason: Expected a call to 0x0xefc5…b132 with data 0x01ffc9a70000000000000000000000000000000000000000000000000000000001ffc9a7, but got none] testCreateWorks() (gas: 1668618)
``` 
removed the prefix 🤯
=> Style: Remove redundant 0x prefix

cli/src/opts/forge.rs, cli/test-utils/src/macros.rs, cli/tests/it/config.rs
use `optimizer-runs` consistently so it gets picked up by the config
=> fix: rename optimize-runs to optimizer-runs

cli/src/cmd/forge/install.rs
Fix #1248 
It checks the reference on remote repository via `git ls-remote` before running the installation
```
✦ forgedev install Rari-Capital/solmate@v7
Installing solmate in "/Users/pyk/github/pyk/foundry-install/lib/solmate", (url: https://github.com/Rari-Capital/solmate, tag: Some("v7"))
Error:
0: tag/branch/commit "v7" is not exists
Location:
cli/src/cmd/forge/install.rs:114
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
=> feat(forge): Check tag in forge install

.gitignore, cli/src/cmd/forge/init.rs, cli/tests/it/cmd.rs, cli/tests/it/config.rs, config/src/lib.rs
First time contributor starting with the simplest issues.
Replace dapphub/ds-test library with forge-std
Issue: [#1409](https://github.com/foundry-rs/foundry/issues/1364)
Install and see lib
```bash
➜  foundry git:(master) ✗ cargo install --path ./cli --bins --locked --force
➜  test tree            
.
└── hello_foundry
├── foundry.toml
├── lib
│   └── forge-std
│       ├── LICENSE-APACHE
│       ├── LICENSE-MIT
│       ├── README.md
│       ├── lib
│       │   └── ds-test
│       │       ├── LICENSE
│       │       ├── Makefile
│       │       ├── default.nix
│       │       ├── demo
│       │       │   └── demo.sol
│       │       └── src
│       │           └── test.sol
```
Test results
```bash
➜  foundry git:(master) cargo check --all
Finished dev [unoptimized] target(s) in 1m 09s
➜ …
```
=> replace dapphub/ds-test with forge-std

cli/assets/ContractTemplate.t.sol
Gm,
`forge init` installs Forge Std, but the template still uses DSTest.
Get more users to switch to Forge Std.
```solidity
import "forge-std/Test.sol";
contract ContractTest is Test {
```
=> use `Test` instead of `DSTest` in `ContractTemplate.t.sol`

cli/tests/it/integration.rs
Added new integration tests as my first task, as suggested in the issue #958.
The first run is painfully long but once cached it's all good as expected. Although i don't know if the github actions will benefit from caching.
I just wanted to start contributing and i found this among the older good first issues.
=> chore: add convex shutdown integration test

Cargo.lock, cli/src/cmd/forge/create.rs, cli/tests/it/create.rs, cli/tests/it/main.rs, cli/tests/it/utils.rs, cli/tests/it/verify.rs, config/README.md, config/src/lib.rs, config/src/utils.rs, forge/src/lib.rs
* bump ethers to include https://github.com/gakonst/ethers-rs/pull/1190
* add a dummy test (on goerli) that deploying with linked libs works
ref #1338 
should probably close
=> test: add forge create test with lib linking

fmt/src/formatter.rs, fmt/src/visit.rs
Previously, we've been restoring function attributes from the original source code due to this issue:
https://github.com/foundry-rs/foundry/blob/37452a3644e6a7e356204096232345f8aede53b6/fmt/src/formatter.rs#L662-L665
Let's introduce `Context` which tracks current nodes we're visiting. In this case, we need to know whether we're visiting a contract base or usual modifier.
Current solution isn't perfect because we're copying values instead of storing references to them:
https://github.com/foundry-rs/foundry/blob/f3485c4a703ce9dc4ff6cffb67559e88d2161aee/fmt/src/formatter.rs#L297
https://github.com/foundry-rs/foundry/blob/f3485c4a703ce9dc4ff6cffb67559e88d2161aee/fmt/src/formatter.rs#L547
It's not obvious how to solve it in a zero-copy manner because we can't have both mutable and immutable …
=> feat(fmt): support base in function attributes

cli/src/cast.rs
`cast call` is currently not pulling `ETHERSCAN_API_KEY` from a users config file.
In `cli/src/cast.rs`, use `config.etherscan_api_key` instead of `eth.etherscan_api_key`
=> fix(cast): use config value for `cast call` etherscan key

Cargo.lock, cli/Cargo.toml, cli/src/cast.rs, cli/src/cmd/cast/run.rs, cli/src/cmd/forge/init.rs, cli/src/cmd/forge/install.rs, cli/src/cmd/forge/run.rs, cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test.rs, cli/src/forge.rs, cli/src/term.rs, cli/src/utils.rs, cli/tests/it/cmd.rs, evm/Cargo.toml, evm/src/trace/mod.rs
A couple issues (#1295,#1029) raise the concern of wanting an option to disable colours in the terminal output.
Added a check when `forge` or `cast` is invoked that turns off colours if the terminal is a basic windows terminal, or if `NO_COLOR` is set in env. 
In order to do this I swapped out the `ansi_term` dependency across the whole crate for `yansi`
It has some very simple built in support for the exact feature wanted: [disabling colour on unsupporting windows terminals](https://docs.rs/yansi/latest/yansi/#windows).
It also seems like `ansi-term` is  [not being maintained ](https://github.com/ogham/rust-ansi-term/issues/72) so its not a bad idea to change to a more recently updated crate.
Didn't add any tests but I can confirm  running: 
```
$ NO_COLOR=1 forge test
```
now outputs …
=> Disable coloured logs

cli/src/cmd/forge/create.rs
Noticed that `forge create` wasn't consuming config rpc url.
=> fix(forge): Added config support to `forge create` 

cast/src/lib.rs
Addresses #1439
If the json file has an `abi` key, we know it is an artifact rather than a plain abi file and handle it appropriately.
=> fix(cast): add artifact support to cast interface

cli/src/cmd/forge/install.rs
ds-test wasn't being pulled as a submodule of forge-std while using `forge init project --no-git`
To reproduce: `forge init project --no-git`  and `forge build`
While installing `forge-std` as a dependency, adding a command to pull it's submodules.
=> fix(forge init): making sure ds-test is pulled while using --no-git flag

Cargo.lock, evm/Cargo.toml, ui/Cargo.toml
Finaly published revm version to crates. This is small change switching github url to crates version.
=> chore: use revm crates version

cli/tests/it/create.rs
Adds another forge create test based on https://github.com/foundry-rs/foundry/issues/1338#issuecomment-1113071366
=> test: add additional forge create test

utils/src/lib.rs
The logic to display negative numbers in traces was off by 1.
Just use `I256` from ethers where this logic is already present instead of duplicating it here.
Closes #1427
=> fix: properly display negative numbers in traces

cli/src/cmd/forge/install.rs, cli/src/forge.rs, cli/src/opts/forge.rs
Allows using `forge remove <ALIAS>` where before you would need to use `forge remove <ALIAS>=<DEP>`
Closes #1442
=> feat: allow removing dependencies using their alias

cli/src/forge.rs
`forge remove` assumed that dependencies would always be in `.git/modules/lib` but they may in some situations be in `.git/modules/some-folder/lib`
Closes #1435
=> fix: properly remove submodule in `.git/modules`

cli/src/opts/cast.rs, cli/src/opts/forge.rs
Introduce subcommand abbreviations (similar to what is used in `ip` and other linux core utils). So that instead of
```
cast wallet new
```
A user is able to write
```
cast w n
```
Aliases are not shown on help pages, so they don't clutter the interface and don't interfere with any normal usage.
In this PR I've only implemented `wallet` and its subcommand shortcuts to demonstrate how it works
Before proceeding with the PR I wish to get some feedback whether this feature is considered useful (before merging I'll squash all 'wip' commits in this feature branch). Also we need agree on initial alias table https://hackmd.io/k76BgcD-Qsm_lUQ6lioLMg?view (feel free to edit the table)
I think the guidelines should be
- if multiple commands start from the same letter, the more popular one gets the …
=> Cast subcommand abbreviations

cli/src/cmd/forge/test.rs, cli/tests/it/config.rs, evm/src/executor/builder.rs, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/mod.rs, evm/src/executor/mod.rs, evm/src/executor/opts.rs
Closes #1143
gas_price will be 0 by default, if it's manually set, then this will now also be set in the `Env` used when executing an transaction
=> fix: use provided gas price in env

cli/src/cmd/forge/verify.rs
Ref https://github.com/gakonst/ethers-rs/pull/1212
`optimization` and `runs` are only applicable in single file mode and not for std json compiler input, because that info is already included in the compiler input object.
Ref https://docs.etherscan.io/api-endpoints/contracts#source-code-submission-gist
=> fix(verify): only include optimize infos when single file

cli/src/term.rs
Ref https://github.com/gakonst/ethers-rs/pull/1214
print the solc version on success
=> chore: add missing debug derive and update spinner message

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/env.rs, forge/README.md, testdata/cheats/Bank.t.sol, testdata/cheats/Cheats.sol
This PR adds the cheat code `bank(address)` which sets `block.coinbase` by internally modifying `data.env.block.coinbase`. 
I'm not too familiar with foundry's internals, so I'm not highly confident that this doesn't break something unexpected. But it is a pretty small change and all tests pass.
This is useful for testing contracts that depend on the value of `block.coinbase`.
=> feat(cheatcode): coinbase(address) - modify block.coinbase

anvil/core/src/eth/mod.rs
was reported that `anvil_setBalance` didn't accept numeric values.
add a test to ensure both formats, and the deserde function works. probably an outdated anvil version
=> test(anvil): add sanity test for numeric values

config/src/utils.rs
Ref #1498
resolves symlinks (`std::fs::canonicalize`) when scanning nested foundry.toml libs
=> fix: follow symlinks to libs

anvil/src/eth/api.rs, anvil/src/eth/fees.rs
If no gas_price or max fee per gas was set in eth_call, use 0 for both
=> fix(anvil): use zero price if not set

cli/src/cmd/forge/install.rs
Limit to only refs/tags  and do not show peeled tags or pseudorefs like HEAD in the output.
=> fix(install): use origin refs only

.github/workflows/release.yml
In the release workflow the wrong manpage is generated for anvil.
P.S: GG on anvil!
=> Fix anvil manpage

cli/src/cast.rs, evm/src/debug.rs
`cast sig` is only parsing a single function, so it should use `parse_function()` rather than `parse_abi()`.
=> chore: simplify cast sig command + fix a typo

forge/README.md
Issue: https://github.com/foundry-rs/foundry/issues/1496
Simple forge readme update to point to foundry book CI page: https://book.getfoundry.sh/config/continous-integration.html
=> docs: update forge readme github actions ci

cli/src/cmd/forge/inspect.rs
Adds a `--pretty` flag to `forge inspect` that can pretty print some fields, if supported.
Currently, only storage layout can be pretty printed.
```
$ forge inspect LilGnosis storage-layout --pretty
+----------+--------------------------+------+--------+-------+
| Name     | Type                     | Slot | Offset | Bytes |
+=============================================================+
| nonce    | uint256                  | 0    | 0      | 32    |
|----------+--------------------------+------+--------+-------|
| quorum   | uint256                  | 1    | 0      | 32    |
|----------+--------------------------+------+--------+-------|
| isSigner | mapping(address => bool) | 2    | 0      | 32    |
+----------+--------------------------+------+--------+-------+
```
Closes #610
=> feat: add pretty storage layout

cli/src/cast.rs
Fixes #1522 
Automatically fetch the chain id in `cast call` instead of relying on an environment variable.
=> fix(cast): auto fetch chain id in cast call

anvil/src/eth/backend/mem/mod.rs, anvil/tests/it/transaction.rs
Closes #1514
revm's memdb does store the code separately and if it's None it needs to be loaded via `code_by_hash`.
`code_by_hash` was also made safe for forked db in #1516
=> fix(anvil): load code if not yet loaded

cli/src/cmd/cast/run.rs, cli/src/cmd/forge/run.rs, evm/src/executor/mod.rs, forge/src/runner.rs
Closes #1538
Return `EvmError::Execution` from a failed `executor.deploy` when possible. Had to change to `for _ in x.iter()` to allow for early exiting
before:
```haskell
$ forge test -vvvvvv -m L2MessengerCorrectL1Messenger
[⠔] Compiling...
[⠔] Compiling 11 files with 0.8.10
[⠑] Solc 0.8.10 finished in 5.88s
Compiler run successful (with warnings)
Message:  couldn't deploy:
0: deployment failed: Revert
Location:
/home/runner/work/foundry/foundry/evm/src/executor/mod.rs:465
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: /home/runner/work/foundry/foundry/forge/src/runner.rs:232
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display …
```
=> fix(forge): Better deploy errors

Dockerfile
Was trying to use anvil via docker and found out it's not there yet.
This change adds anvil to PATH of the docker container.
⚠️ I was able to build locally, but had issues when building on docker. I saw the same issue in the CI [here](https://github.com/foundry-rs/foundry/runs/6031912323?check_suite_focus=true). It takes over an hour to build on docker on my machine so I figured someone here (@gakonst?) might already be familiar with the issue and know what to do. Maybe it's just flakiness?
=> feat: add anvil to Docker

anvil/src/cmd.rs, anvil/src/config.rs, anvil/src/eth/backend/fork.rs, anvil/src/eth/backend/mem/fork_db.rs, anvil/tests/it/fork.rs
Closes #1531
* separate local and remote state
* don't commit changes to db that holds remote state
* only flush remote change
=> fix(anvil): keep local changes separate when flushing forked state

cli/src/cmd/forge/install.rs
current check also matched: `"fatal: not a git repository (or any of the parent directories): .git` on non git repo.
propagate exact git error
=> chore: use exact git error

Cargo.lock, cli/src/cmd/forge/install.rs, cli/test-utils/src/util.rs, cli/tests/it/config.rs, config/Cargo.toml, config/src/lib.rs
Closes #1508
if `libs` section of the config does not contain the default library folder `lib`, like : `libs = ["node_modules"]`, automatically add `lib` after `forge install`
* add `Config::update` functions that can be easily extended to additional entries.
=> feat(config): auto update libs section on install

anvil/core/src/eth/transaction/mod.rs, anvil/src/eth/api.rs, anvil/src/eth/backend/cheats.rs, anvil/src/eth/backend/mem/mod.rs, anvil/tests/it/anvil_api.rs
allow `eth_sendTransaction` with impersonated account
* bypass address recovery if sender is impersonated account
=> feat(anvil): support impersonated accounts in eth_sendTransaction

anvil/src/config.rs, anvil/src/eth/sign.rs, anvil/src/lib.rs, anvil/tests/it/anvil.rs
use same key order in `eth_accounts` as logged on output
* dev signer maintains a Vec<Address> of the same addresses shown when `anvil` starts
=> fix: maintain same dev accounts as on logged on output

.github/ISSUE_TEMPLATE/BUG-FORM.yml
In the Operating System section of bug report issue template, both macOS(amd) and macOS(M1) are listed, but macOS(Intel) option is absent.
Change options 
- macOS(amd)
- macOS(M1)
to
- macOS(Intel)
- macOS(Apple Silicon)
=> fix: add missing macOS(Intel) option in bug report issue template

cli/src/cmd/forge/build.rs, cli/src/cmd/forge/inspect.rs, cli/src/opts/forge.rs, cli/tests/it/cmd.rs
Closes #1579 
use `Vec<>` instead `Option<Vec<>>`
=> fix: make extra-output accept multiple values

anvil/core/src/eth/call.rs, anvil/src/eth/api.rs, anvil/src/eth/backend/db.rs, anvil/src/eth/backend/fork.rs, anvil/src/eth/backend/mem/fork_db.rs, anvil/src/eth/backend/mem/in_memory_db.rs, anvil/src/eth/backend/mem/mod.rs, anvil/src/eth/backend/mem/storage.rs, anvil/src/eth/error.rs, anvil/tests/it/ganache.rs, anvil/tests/it/transaction.rs
previously all block number args were ignored, so eth_call was always executed on head state regardless of the paramaeter
* keep previous states in memory, similar to snapshots, and transact_ref on a cached state if the block < head
* also adds range checks for block number args
=> feat(anvil): add support for historic state

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/run.rs, cli/tests/it/cmd.rs, cli/tests/it/config.rs
Issue #1475 requests that `forge run` prints the index, value, and type of each returned value from the function call. This Pull Request includes a change that prints data in the previously mentioned format.
The problem being solved is for developers that execute a function call against a Solidity file and want to see not only the event logs and stack traces, but also what value the function returned.
The solution required an additional field, `returned`, on the `RunResult` defined in the source file for the `forge run` command. This gets the `result` from the `raw_call` being executed against the compiled contract.
Another change was to additionally extract the function to be called from the contract ABI. This allows for the extraction of the exact return types. If this is omitted, every …
=> Return Index Value and Type printed in `forge run`

utils/src/lib.rs
#1588 showed that `cast` will not pad bytes32 arguments in methods like `call`. 
Currently, the solution adds an additional error massaging case to `parse_tokens` that right pads the value to 32 bytes if the param is type `FixedBytes(32)`. 
Some open questions:
- Should we massage other value types? E.g. if an address is not 20 bytes? Obviously a zero padding there makes less intuitive sense. I am not familiar with the intricacies of the `seth` spec but we could match that exactly? Can open a separate issue for this.
- Not sure I am doing to default match case correctly with the no-op.
Before:
```sh
$> cast call 0x5a464c28d19848f44199d003bef5ecc87d090f87 "name(bytes32)(string)" 0x5257413030312d4100000
Error:
0: Failed to parse tokens
1: Invalid data
Location: …
```
=> feat(cast): pad bytes32 hex values if they are short

anvil/src/eth/miner.rs, anvil/src/service.rs, anvil/tests/it/anvil.rs, anvil/tests/it/pubsub.rs
only start mining after first interval elapsed
use `interval_at(now+blocktime)` instead of `interval`, which is ready instantly.
=> fix(anvil): use interval_at to mine after first elapsed interval

Cargo.lock, anvil/Cargo.toml, cli/Cargo.toml, cli/src/cmd/forge/mod.rs, fmt/src/lib.rs
bump latest ethers to https://github.com/gakonst/ethers-rs/commit/eb94e53d1f87dc5fe10f25b7268e977cfad24984 to unblock #1597 #1602
latest ethers includes fixed breaking changes for solang: https://github.com/gakonst/ethers-rs/pull/1256
unfortunately, this broke `fmt` entirely. Since we don't use fmt in forge, I would suggest to disable fmt completely until it is fixed to unblock foundry PRs that depend on a newer ether
cc @shekhirin
=> chore: bump ethers and disable fmt

cli/tests/it/config.rs, config/README.md, config/src/lib.rs
Not sure if this is wanted, but I think it would be cool to have direct access to Solidity's model checker via the Foundry options. This is basically what I'm running locally.
The options are opt-in and not there by default, so it shouldn't bother the default case and Foundry users who don't explicitly add it.
This PR adds the minimum required options to `foundry.toml` (as opt-in) that enable [Soldity's model checker](https://docs.soliditylang.org/en/latest/smtchecker.html).
Solidity has a built-in model checker that can be easy to use on OSX and Linux (the latter needs z3 <=4.8.14 installed system-wide) via compiler options.
The options were added based on a subset of the [tools options](https://docs.soliditylang.org/en/latest/smtchecker.html#smtchecker-options-and-tuning). For now only …
=> Solidity's model checker basic options

anvil/core/src/eth/mod.rs, anvil/core/src/types.rs
Closes #1616
pre #1614 there were actually two bugs, #1614 fixed one and ensured everything is reset, but there was another bug that resulted in the forking params not being decoded, even though decoding was successful...
* add deserialize impl for Forking which supports various forms
tagged 
```json
{ "forking": {...} }
```
untagged
```json
{ {...} }
```
empty
```json
{}
```
=> fix(anvil): decode forking parameters correctly

cli/src/cmd/forge/test.rs, forge/src/multi_runner.rs, forge/src/runner.rs
Similarly to `cargo test -- --list`, it's useful to have a way for the tooling to list existing tests, preferably in a structured way.
The main use-case, and what led me down this, is to integrate a test runner into an IDE such as VC Code. The [rust test runner](https://github.com/swellaby/vscode-rust-test-adapter) itself uses the same approach, which is far cleaner and more efficient than other extensions that try to parse test files themselves.
My main motivation here is to build the actual VS Code extension. When getting started, I was following along how the rust equivalent was doing it, which led me writing this
Adds the ability to run `forge test --list`, which simply lists tests instead of running them
Due to the existing code structure, it also became trivial to make this work …
=> Adds `forge test --list`

anvil/src/eth/miner.rs, anvil/src/eth/pool/transactions.rs, anvil/tests/it/transaction.rs
Fixes a bug that resulted in infinite block mining.
This happened if a tx with the same nonce was replaced, but was already fired via the new ready tx notification stream the auto miner listens on.
The transaction was replaced but the previous implementation of the `ReadyTransactionMiner` polled the pool until it all previously received `ready transactions` were taken from the pool. The miner polled the pool forever since the replaced tx was purged from the pool.
* clear the `ready` buffer of the `ReadyTransactionMiner` once the pool is empty. this gets rid of hashes that are no longer present in the pool.
=> fix(anvil): stop auto mining if pool is empty

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/expect.rs, evm/src/executor/inspector/cheatcodes/mod.rs, forge/README.md, testdata/cheats/Cheats.sol, testdata/cheats/ExpectCall.t.sol, testdata/cheats/MockCall.t.sol
Closes #1568 
Closes #1604 
- Added overloaded `expectCall` with `msg.value`
- Added overloaded `mockCall` with `msg.value
- Fixed `mockCall` partial calldata matching
Implementation for the overloading of `expectCall` was straightforward with a new `struct` that contains the `calldata` and `msg.value`.
For the `mockCall`, `Ord` trait was implemented for `MockCallDataContext` to ensure that partial matching is consistent.
The partial match now allows for the longest prefix in the calldata to be matched if there is no exact match.
There is also a new precedence order, and a more specific calldata precedes a `msg.value` match with a shorter prefix calldata match.
=> feat(forge): overload `expectCall` and `mockCall` with `msg.value`

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/cache.rs
fixes: https://github.com/foundry-rs/foundry/issues/1564
I previously tried using ArgEnum but ran into problems documented on previous pr: https://github.com/foundry-rs/foundry/pull/1581
This fix uses strum on ethers-rs
https://github.com/gakonst/ethers-rs/blob/1271308e06bd4c1b6db271488838e011505fcdfa/ethers-core/src/types/chain.rs#L14-L47
like so:
```rust
#[repr(u64)]
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, Deserialize, EnumVariantNames)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "kebab-case")]
pub enum Chain {
Mainnet = 1,
#[strum(serialize = "xdai")]
XDai = 100,
#[strum(serialize = "bsc")]
BinanceSmartChain = 56,
#[strum(serialize = "bsc-testnet")]
BinanceSmartChainTestnet = 97,
}
```
and we can use `Chain::VARIANTS`
```rust
pub struct CleanArgs {
// TODO …
```
=> fix: unify names of supported chains

config/README.md
The "All Options" section in the config readme does not mention the `etherscan_api_key` option that enables improved error traces, which renders the example incomplete.
Add the `etherscan_api_key` option to the "All Options" config example.
=> Chore: Add `etherscan_api_key` to config README

cli/src/cmd/forge/create.rs
Closes https://github.com/foundry-rs/foundry/issues/1621.
List link references in error message.
Tested with the repo in this [issue comment](https://github.com/foundry-rs/foundry/issues/1338#issuecomment-1113071366), and the following is the output of `forge create Contract`:
```
[⠢] Compiling...
[⠔] Compiling 9 files with 0.8.13
[⠑] Solc 0.8.13 finished in 233.18ms
Error:
0: Dynamic linking not supported in `create` command - deploy the following library contracts first, then provide the address to link at compile time
ChainlinkTWAP: /home/USER/Repos/chainlink-test/src/libraries/ChainlinkTWAP.sol
Location:
cli/src/cmd/forge/create.rs:125
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source …
```
=> fix(forge/create): list unlinked library contracts in error message

cli/src/cmd/cast/run.rs
When `anvil` is running, many of the `cast` commands do not need an explicit `--rpc-url` parameter. `cast run` is a notable exception. This MR copies the logic from these other commands into `cast run`.
=> Automatically fallback to Anvil rpc_url for 'cast run'

anvil/src/eth/api.rs, anvil/tests/it/transaction.rs, cli/src/cmd/cast/run.rs
Closes #1656
check pending transactions from the sender:
* when determining the highest nonce for a transaction
* `eth_getTransactionCount` for pending block number
iterate over all pending tx, if there's a tx from the sender (starting at on-chain nonce), increment the `current nonce`
=> feat(anvil): check tx pool when determining next nonce

anvil/src/config.rs, anvil/src/eth/backend/fork.rs, anvil/src/eth/backend/mem/mod.rs, anvil/src/eth/backend/time.rs, anvil/tests/it/fork.rs
Closes #1630
In fork mode, set the current timestamp to the forked block timestamp by using it as offset
=> fix(anvil): use correct timestamp from fork

cli/tests/it/config.rs, config/src/lib.rs, evm/src/executor/fork/init.rs, evm/src/executor/opts.rs
Closes #1601
make `Config::gas_price` optional so we can determine whether to use the gas price of the remote client or the user's configured gas price
=> refactor: make gas price optional

anvil/src/eth/api.rs
Fixes an off by one error while calculating required marker for raw transactions that resulted in invalid required markers
use correct `required_marker` that's already being used in send_transaction
=> fix(anvil): use correct required marker calc

.github/workflows/test.yml
enable caching in `integration` and standard tests as well (for anvil).
it appears that for whatever reason the rpc cache files are not cached for CI...
the `foundry home dir` is "$HOME/.foundry" 
https://github.com/xdg-rs/dirs/blob/master/dirs/src/lib.rs#L38-L39
=> ci: enable rpc caching in integration tests

evm/src/executor/fork/backend.rs, evm/src/executor/fork/cache.rs
Ref #1688
Moves the flushing behaviour to the sender half, making the `BackendHandler` completely independent.
see docs
=> refactor(evm): move cache flushing to SharedBackend

fmt/src/visit.rs
allow fmt's `Visitor` to be reused in other packages 
added default implementations
cc @mattsse @jpopesculian
=> fix(forge): provide default impls for remaining visitor methods in fmt

anvil/core/src/eth/subscription.rs, cli/src/cmd/forge/bind.rs
Blocked by https://github.com/gakonst/ethers-rs/pull/1301
https://github.com/foundry-rs/foundry/issues/1701
Add `--skip-cargo-toml` option.
=> feat(bind): option to skip Cargo.toml from consistency checks

anvil/src/config.rs, evm/src/executor/fork/backend.rs
Ref 1688
move the fork BackendHandler to its own thread local runtime so it can't interfere with anvil's tasks
=> refactor: spawn backendhandler on background thread

cli/src/cast.rs, cli/src/opts/cast.rs, utils/src/lib.rs
This PR switches the selector database for `4byte`, `4byte-decode`, and `4byte-event` cast commands to use samczsun's [new database](https://sig.eth.samczsun.com) rather than 4byte.directory. See https://github.com/foundry-rs/foundry/issues/1672 for details
- Updated the 4byte bindings utils to use samczsun's service instead
- added few tests ensuring selectors work w/ and w/o 0x prefix
=> Switch selector database to sig.eth.samczsun.com

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/build.rs, cli/src/cmd/forge/fourbyte.rs, cli/src/cmd/forge/mod.rs, cli/src/forge.rs, cli/src/opts/forge.rs
This PR adds a new command to forge `forge upload-selectors` which builds a given contract and uploads the fresh ABI to sig.eth.samczsun.com 4byte selector database. See https://github.com/foundry-rs/foundry/issues/1672
=> Add `forge upload-selectors` command

cli/tests/it/config.rs
`can_update_libs_section` in `cli` integration test is failing because the new logic added [here](https://github.com/foundry-rs/foundry/pull/1696)
Add `--no-commit` option to `forge install`.
=> fix(cli): can_update_libs_section test

anvil/server/src/config.rs, anvil/src/cmd.rs
closes: https://github.com/foundry-rs/foundry/issues/1742
add value_name for anvil for better context
```sh
anvil 0.1.0 (4fcd7e0 2022-05-26T14:13:22.92765Z)
A fast local Ethereum development node
USAGE:
anvil [OPTIONS]
OPTIONS:
-a, --accounts <NUM>                       Number of dev accounts to generate and configure. [default: 10]
-b, --block-time <SECONDS>                 Block time in seconds for interval mining.
--balance <NUM>                        The balance of every dev account in Ether. [default: 10000]
--derivation-path <DERIVATION_PATH>    Sets the derivation path of the child key to be derived. [default: m/44'/60'/0'/0/]
-h, --help                                 Print help information
--hardfork <HARDFORK>                  The EVM hardfork to use. [default: latest]
--host …
```
=> fix: anvil value_name

.github/workflows/test.yml, CONTRIBUTING.md, anvil/tests/it/transaction.rs, cli/test-utils/src/util.rs, cli/tests/fixtures/can_check_snapshot.stdout, cli/tests/it/cmd.rs, cli/tests/it/integration.rs, cli/tests/rpc-cache-keyfile
Closes #1726
Adds 3 new fork only CI jobs to run
* all unit tests that contain `fork`
* integration tests that contain `fork`
* external integration tests that contain `fork`
the previous CI jobs now all skip `fork` tests
Adds a `rpc-cache-keyfile` that's supposed to work as a trigger to invalidate rpc cache in ci
=> ci: add additional ci jobs for forks

cli/test-utils/src/macros.rs, cli/tests/it/cmd.rs, utils/src/rpc.rs
the infura keys we're using don't have access to archive state.
only use alchemy keys in rotation
=> test: use rotating alchemy api keys

ui/src/lib.rs
it is hard to look up shortened addresses referenced in debugger
show full addresses
=> fix: show full addresses in debugger

cli/src/cmd/forge/create.rs
Closes #1051
Adds a flag to manually set the nonce. Does this need to be added to any other commands?
=> feat(forge): flag to manually set nonce in `forge create`

cast/src/lib.rs
Closes #1719.
Split up the formatting for uints and ints, because the `ethereum_types` crate does not decode signed integers correctly. I assume there are some other places where this may need to be fixed?
=> feat(cast) Signed Integer decoding in `cast call`

cli/src/cmd/forge/script/mod.rs
closes: https://github.com/foundry-rs/foundry/issues/1783
while documenting `forge script` found that `--debug` help text needs more info
book pr: https://github.com/foundry-rs/book/pull/335
Current help text for `--debug`
```bash
➜  ~ forge script -h
forge-script
Run a smart contract as a script, building transactions that can be sent onchain.
USAGE:
forge script [OPTIONS] <PATH> [--] [ARGS]...
ARGS:
<PATH>       The contract you want to run. Either the file path or contract name
<ARGS>...    Arguments to pass to the script function
OPTIONS:
--broadcast                          Broadcasts the transactions.
--debug                              Takes precedence over broadcast
-h, --help                               Print help information
```
=> fix: forge script debug flag description

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/receipts.rs, cli/src/cmd/utils.rs
It didn't make much sense on how it was before. 
On top of that, there was an issue sometimes where `--resume` was starting off on a transaction which had been published already, because we didn't wait for all pending transactions.
=> forge(fix): refactor pending transactions from `script`

Cargo.lock, config/Cargo.toml, config/src/lib.rs
Closes #1777
transform non `/` separators in remappings paths to `/` on windows.
=> fix: use consitent slashes in remappings

config/src/lib.rs
closes #1721
if both `lib` and `node_modules` exists, include them both in the default `libs` set
=> feat(config): autodetect node_modules and lib folder

anvil/src/config.rs
Optimism public RPC is currently getting hammered from the airdrop, so right now starting an anvil node from an optimism fork sometimes fails with
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/work/foundry/foundry/anvil/src/config.rs:473:18
```
This is a bit confusing since it seems like an anvil bug, so this just clarifies the error.
=> Clarify error message when RPC fails

cli/src/cmd/forge/debug.rs, cli/src/cmd/forge/script/cmd.rs, cli/src/cmd/forge/script/mod.rs
issue: https://github.com/foundry-rs/foundry/issues/1769
Adding forge script --json
using this to test json output
```bash
forge script ./test/Simple.t.sol --tc SimpleTest --fork-url $GOERLI_RPC_URL
[⠢] Compiling...
[⠰] Compiling 2 files with 0.8.13
[⠔] Solc 0.8.13 finished in 74.99ms
Script ran successfully.
Gas used: 9098
== Return ==
0: uint256 1234
1: bytes32 0x6100000000000000000000000000000000000000000000000000000000000000
2: string "asdf"
== Logs ==
test
```
```solidity
contract SimpleTest is DSTest {
uint256 a = 1234;
bytes32 b = 'a';
string c = "asdf";
function run() public returns (uint, bytes32, string memory){
emit log_string("test");
return (a, b, c);
}
}
```
Current status
```bash
~/CLionProjects/foundry/target/debug/forge script ./test/Simple.t.sol …
```
=> feat(forge): forge script --json

fmt/src/comments.rs, fmt/src/formatter.rs, fmt/src/solang_ext/loc.rs, fmt/src/visit.rs, fmt/testdata/DocComments/fmt.sol, fmt/testdata/DocComments/original.sol, fmt/testdata/FunctionDefinition/fmt.sol, fmt/testdata/FunctionDefinitionWithComments/fmt.sol, fmt/testdata/FunctionDefinitionWithComments/original.sol, fmt/testdata/FunctionType/fmt.sol, fmt/testdata/FunctionType/original.sol, fmt/testdata/ImportDirective/bracket-spacing.fmt.sol, fmt/testdata/ImportDirective/fmt.sol, fmt/testdata/ModifierDefinition/fmt.sol, fmt/testdata/ModifierDefinition/original.sol, fmt/testdata/SimpleComments/fmt.sol, fmt/testdata/SimpleComments/original.sol, fmt/testdata/UsingDirective/fmt.sol, fmt/testdata/UsingDirective/original.sol
So I went a little crazy trying to get comments to work in the scope of function declarations and otherwise... The main crux of this PR (still WIP) is to add a `Chunk` struct that holds the context of comments. You can then format this Chunk or rearrange it or manage its comments in special cases.
This is especially useful in lists for example. We can essentially extract the chunk information first, sort if necessary, use that chunk information to check if it fits, and then rewrite the chunks with commas correctly placed before the postfix comments
The other big change here, this chunk on writing handles its own whitespace. This is just kind of a side effect that it has to handle its own whitespace because its potentially surrounded by comments. 
There's a bunch of minor stuff in here …
=> [wip] feat(fmt): intermediate chunk struct

cli/src/cmd/cast/run.rs, cli/src/cmd/forge/cache.rs, cli/src/cmd/forge/script/mod.rs, cli/src/cmd/forge/test.rs, cli/tests/it/cmd.rs, config/src/cache.rs, config/src/lib.rs
Currently forge cache clean only clears RPC cache, but it would be beneficial to also be able to clear the Etherscan verification status cache.
Solves #1477
This PR:
* Adds the `--etherscan` flag to `forge cache clean`
* Displays the etherscan cache storage with `forge cache ls`:
```
-️ mainnet (6.7 kB)
-️ Block Explorer (0.0 B)
-️ Block 14880985 (3.4 kB)
-️ Block 14881100 (3.3 kB)
```
* Restructures the cache directory structure:
```
cache/
- rpc/{mainnet,...}
- etherscan/{mainnet,...}
```
=> Add option to clear etherscan cache

cast/src/tx.rs
When building transactions using `cast::TxBuilder` the built transaction does not have a `chain_id` value.
Use the provided chain
=> fix(cast): added chain_id to the transaction built by TxBuilder

.github/workflows/test.yml
Clippy and Rustfmt warnings will now show up as annotations in the PR file view, which I think is helpful for newcomers. I didn't let `cargo test` and `cargo build` annotate the PR because it might clutter the view a lot, but it is a possibility as well
=> ci: let clippy and fmt annotate prs

cli/src/cmd/forge/create.rs, cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/build.rs, cli/src/cmd/forge/script/cmd.rs, cli/src/cmd/forge/script/mod.rs, cli/src/cmd/forge/verify.rs, cli/src/cmd/utils.rs, cli/tests/it/utils.rs, cli/tests/it/verify.rs, forge/src/multi_runner.rs, utils/src/lib.rs
There were a couple cases where verifying was not working properly or not giving enough information to the user on `forge script`
* Standalone scripts with `--verify` flag now throw an error, instead of finishing silently. `--verify` flag should only be used with contracts belonging to projects.
* Add `--libraries` to `forge verify-contract`
* Fixed verification of contracts with predeployed libraries. It was just failing silently. Now we properly store the library information on `ScriptSequence` and provide it to `forge verify-contract` through the `--libraries` field.
* Relink contracts on `--resume --script` or `--script` with libraries stored in `ScriptSequence`, before asking for contract verification.
* Strip the build metadata. If a compiler version has too much build data eg. …
=> forge(fix): verification on contracts with predeployed libraries + minor fixes

cli/src/cmd/forge/script/cmd.rs
When using `forge script`, the command line option `--etherscan-api-key` isn't passed into the script run.
Validation appears to work correctly, so if `--verify` is passed the script will terminate if `--etherscan-api-key` isn't provided. However, after providing this key, it is ignored and results in verification silently not occurring.
Setting the `ETHERSCAN_API_KEY` does work properly as it's captured in the Figment creation process. 
Passing the Etherscan key via command line is a documented option and enables easier parameterization than solely allowing environment variables.
I tried to mirror this off of the private key loading process that also loads from the parsed command line arguments. I'm not sure if there is a more idiomatic way (seems like it could go in the Figment …
=> forge: fix Etherscan API key not being read from command line during script runs

Cargo.lock, fmt/Cargo.toml, fmt/src/formatter.rs, fmt/src/lib.rs, fmt/src/visit.rs
It's difficult to separate business logic errors from `fmt::Error`s when error's bubble up
Add a custom error type to the `Visitor` trait
=> feat(fmt): Add custom error to fmt

Cargo.lock, cli/Cargo.toml, cli/src/cast.rs, cli/src/cmd/forge/create.rs, cli/src/cmd/forge/debug.rs, cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/cmd.rs, cli/src/cmd/forge/script/mod.rs, cli/src/cmd/forge/script/receipts.rs, cli/src/cmd/forge/test.rs, cli/src/cmd/utils.rs, cli/src/opts/mod.rs, cli/src/opts/multi_wallet.rs, cli/src/opts/wallet.rs, cli/src/utils.rs
ref #1817 #1816 #1826 #1829
At @mattsse suggestion, I tried separating into two different processes. ~~First send every transaction, and only then, wait for the receipts. Both with `buffered` set at 20.~~
~~1. Get `gas_price` or `eip1559_fees` estimation in the beginning.
2. Send every transaction. It only waits for a valid HTTP response before sending the next one. Collects all `transaction_hashes`.
3. Creates `PendingTransactions` from `transaction_hashes` and waits for the receipts to arrive. in a `.buffered(2)`.~~
--
1. Get `gas_price` or `eip1559_fees` estimation in the beginning.
2. Sign transactions "manually" to skip `eth_createAccessList`
3. Sends transactions in batches of 100. [`buffered(7)`]
4. Waits for the receipts of each batch [`buffer_unordered(10)`], before sending the …
=> forge: split sending and waiting for receipts + buffered 

fmt/src/formatter.rs, fmt/testdata/SimpleComments/fmt.sol
We often have to check if something fits on the same line, and we do that by writing the whole thing and then checking if it fits. This is inefficient and tedious
This PR essentially introduces two helpers `simulate_to_single_line` which gives you a String back if it fits on one line and `try_on_single_line` which tries to write the given output on a single line and reverts if it can't. This is more efficient as the FormatBuffer throws an error if it encounters a newline, short circuiting having to write everything.
=> feat(fmt): Add single line helpers

anvil/src/cmd.rs, anvil/src/config.rs
Adds the `--config-out <out_file>` option to anvil. This writes the same info that anvil writes to stdout, in a more machine-friendly format, as json to the file specified by the user.
https://github.com/foundry-rs/foundry/issues/1718
pretty straightforward, if you include `--config-out <out_file>` it writes the relevant config info to <out_file>. note: it will still write the file it `silent` and `--config-out` are provided since i assumed silent is really referring to stdout/err
=> #1718 - adds option to write anvil config to json file

Cargo.lock, cli/Cargo.toml, cli/test-utils/src/macros.rs, cli/test-utils/src/util.rs, cli/tests/it/cmd.rs, cli/tests/it/config.rs, cli/tests/it/test_cmd.rs
prevent flakes related to Config/current dir manipulation 
use `serial_test` instead of locking current dir by extending all `test!` macros
if this turns out to be stable we can try to phase out more tests that are currently run with `serial_test`
=> test: use serial_test instead of current dir locking

cli/src/cmd/forge/install.rs, config/src/lib.rs
Closes #1834 use lib folder in config as install target
select the first dir in `libs` that is not `node_modules`, by default this will be `lib` but allows other targets like
```toml
libs = ['contracts/solidity/src/lib']
```
=> feat(forge): allow install in config folder

anvil/core/src/eth/mod.rs
some serde annotations were wrong, combination of top level `sequence` + param level `deserialize_number` is not possible
use new `deserialize_number_seq` to match ganache/hardhat numeric arguments: `[1], [0x01], 1`
=> fix(anvil): deserialize numeric params properly

anvil/core/src/eth/mod.rs, anvil/src/eth/api.rs
Anvil is unable to handle`net_listening` calls, which is used by Remix, hence why Anvil is currently not compatible with Remix. 
```
{"method":"net_listening","params":[],"id":43,"jsonrpc":"2.0"}
```
Returns:
```
{"jsonrpc":"2.0","id":43,"error":{"code":-32601,"message":"Method not found"}}
```
This PR adds a `net_listening` method, which returns true if Anvil is listening, and false if not.  
```
net_listening
Returns true if client is actively listening for network connections.
Returns
Promise<boolean> : true when listening, otherwise false.
```
I've used a similar implementation to `is_mining`, aka return True, else False, so this lacks tokio tests. 
Remix now works when selecting Ganache/Hardhat as Environment for Remix.
P.S: I'll also push a PR to Remix in a bit to add Anvil properly …
=> anvil: add `net_listening` call for usage with `Remix`

Cargo.lock, cli/assets/ContractTemplate.s.sol, cli/src/cmd/forge/build.rs, cli/src/cmd/forge/init.rs, config/src/lib.rs
Pending / Ref: https://github.com/gakonst/ethers-rs/pull/1359
```
Currently, our convention on foundry is to have scripts in the script/ folder. 
However, the folder does not actually belong to the project. It may lead to weird issues, 
if there's contracts declared inside when verifying contracts.
Alternatively, we could also add a more generic additional_sources where by default we add the script/ folder.
```
=> forge: add script/ to project paths

fmt/src/formatter.rs, fmt/src/solang_ext/operator.rs, fmt/src/visit.rs, fmt/testdata/DoWhileStatement/fmt.sol, fmt/testdata/ExpressionPrecedence/fmt.sol, fmt/testdata/ExpressionPrecedence/original.sol, fmt/testdata/VariableDefinition/fmt.sol, fmt/testdata/WhileStatement/fmt.sol
We want long same precedence operators to be formatted on separate lines like this
```
epxression1
+ expression2
+ expression3
+ expression4
```
Flatten expressions into lists to figure out how to separate lines
=> feat(fmt): Expression multiline formatting

cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/executor.rs, cli/src/cmd/utils.rs
Provide a correct gas usage if using Arbitrum or Optimism.
Instead of doing `eth_estimateGas` right before broadcasting each transaction, we now do it before we store it on `ScriptSequence`. 
Also allows us to provide (to all chains) an estimation of ETH required for the script.
=> forge(feat): make `estimateGas` for all transactions before broadcast for L2s

anvil/src/eth/backend/mem/mod.rs
When comparing results from `anvil` with `geth` the `cumulative_gas_used` differs. 
The gas of the queried transaction should be included in `cumulative_gas_used`.
=> anvil(fix): include target index in cumulative_gas_used

config/src/chain.rs
Ref #1886 try converting to a known chain first for `From<u64>`
=> chore(config): try converting to named chain first

fmt/src/comments.rs, fmt/src/formatter.rs, fmt/testdata/FunctionDefinition/fmt.sol, fmt/testdata/FunctionDefinition/original.sol
=> fix(fmt): comment indent

cli/src/cmd/forge/mod.rs, cli/src/cmd/forge/remove.rs, cli/src/forge.rs, cli/src/opts/forge.rs, cli/tests/it/cmd.rs
also handle relative paths properly
* move `remove` to cmd module
* support config `lib dir` instead hard coding `lib`
* support `forge rm <dep-name>` and `forge rm lib/dep-name`
* return err if dep does not exist
=> refactor: improve forge remove

anvil/src/eth/pool/mod.rs, anvil/tests/it/geth.rs, anvil/tests/it/main.rs, anvil/tests/it/transaction.rs
the test `can_stream_pending_transactions` in `ethers-rs` led to jobs running forever:
https://github.com/gakonst/ethers-rs/runs/6801222172?check_suite_focus=true
because not all transactions were emitted as "pending" by anvil
* also notify promoted transactions 
* port over `can_stream_pending_transactions`
Ref https://github.com/gakonst/ethers-rs/pull/1365
=> fix(anvil): notify on promoted transactions

cli/src/utils.rs
I have seen user reports that they have to call `--resume` too many times on `forge script`. This comes from `PendingTransaction` trying too many times on a low interval.
For now, I would like to revert this to 7 seconds as it was before.
=> fix(forge): revert provider interval to default 7s on `script`

cli/src/compile.rs
fix exceeds_size_limit annotation error, modify exceeds_size_limit function annotation from `Returns true if all contracts are within the size limit, excluding test contracts.` to `Returns true if any contract exceeds the size limit, excluding test contracts.`
=> fix exceeds_size_limit annotation error

cli/src/cmd/utils.rs
If the artifact didn't have the requested bytecode (eg. interface), it would panic.
Just skip it instead.
=> fix(forge): handle case when there's no bytecode in the artifact

Cargo.lock, fmt/Cargo.toml, fmt/src/formatter.rs, fmt/src/helpers.rs, fmt/src/lib.rs, fmt/src/solang_ext/ast_eq.rs, fmt/src/solang_ext/loc.rs, fmt/src/visit.rs, fmt/testdata/FunctionDefinition/fmt.sol, fmt/testdata/FunctionDefinition/original.sol, fmt/testdata/ModifierDefinition/fmt.sol, fmt/testdata/ModifierDefinition/original.sol, fmt/testdata/UsingDirective/fmt.sol, fmt/testdata/UsingDirective/original.sol, fmt/testdata/VariableDefinition/fmt.sol, fmt/testdata/VariableDefinition/original.sol
=> dep(fmt): update ethers & solang

anvil/src/config.rs, anvil/src/eth/fees.rs, anvil/src/lib.rs
Closes #1863
* use last base fee and current gas price retrieved from the endpoint
* adjust default gas price settings to match hh instead of ganache
needs follow-up to change the `eth_gasPrice` endpoint to match: https://github.com/ethereum/pm/issues/328#issuecomment-853612573
use the base fee of the last fork block by default if not provided via cli
=> fix(anvil): use base fee of fork by default

evm/src/decode.rs, evm/src/executor/abi.rs
In https://github.com/foundry-rs/forge-std/pull/86, `assertEq` overloads were added for testing array equality. They work by hashing the two arrays, and like other assertion helpers they emit an event with the expected vs. actual values if they don't match.
DSTest's `test.sol` does not have any events for arrays, therefore right now these new logs in forge-std only show up in traces. This PR adds these events to the DSTest ABI so they now show up in the `Logs:` section when running tests.
cc @ZeroEkkusu / ref https://github.com/foundry-rs/book/issues/372
=> feat: add additional logs to DSTest abi

Cargo.lock, cli/src/cmd/forge/test.rs, cli/src/cmd/forge/verify.rs, cli/src/cmd/forge/watch.rs, cli/src/compile.rs, cli/tests/fixtures/can_set_yul_optimizer.stderr, config/Cargo.toml, config/src/lib.rs
it was reported that `forge test` hangs for projects that import https://github.com/mangrovedao/mangrove (very large)
I tracked this down to redundante+incorrect usage of `Config::load` in the `TestFilter`
So far, the "filter" loaded the config, which is redundant with the current usage, as a config is also loaded when the filter is used.
the Config -> Filter pipeline is a bit contrary to the intended use of Config, where everything should be merged _into_ Config.
* instead of loading the Config again, reuse it
* also adds some traces used to debug this
=> perf: remove redundant config usage

anvil/src/eth/backend/time.rs, anvil/tests/it/anvil_api.rs
the timestamp's resolution is seconds, if manually set (`evm_setNextBlockTimestamp`), followed by an immediate `evm_mine` both blocks can have the timestamp.
since this is manually set, it would make sense to make sure that the next block will definitely have a newer timestamp.
=> fix(anvil): increase timestamp offset by 1 sec if manually set

README.md
The README linked to 
`https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup` 
instead of 
`https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/install` 
in the installation without redirect instruction.
=> Fix wrong install script link in README

anvil/core/src/eth/mod.rs, anvil/src/eth/api.rs, anvil/src/eth/backend/time.rs, anvil/tests/it/anvil_api.rs
Closes #1930
* adds two new rpc calls
* `anvil_setBlockTimestampInterval` to configure a interval for the block timestamps
* `anvil_removeBlockTimestampInterval` to remove it (alternatively this could be replaced by `anvil_setBlockTimestampInterval(0)`, but perhaps a constant timestamp is useful)
`evm_setNextBlockTimestamp` still works if a interval is enabled
=> feat(anvil): add timestamp interval support

cli/tests/it/cmd.rs
ignores the `check_broadcast_log` that's currently failing on a couple of open PRs (#1946, #1945, #1926)
unfortunately, it's not obvious why this fails, updating the file also did not help, #1941
but looks like this is perhaps due to some regex issues #1938, no idea what this even does, sorry @joshieDo :)
* ignore test until test improved
=> test: disable check_broadcast_log test

Cargo.lock, cast/Cargo.toml, cast/src/tx.rs, cli/src/cast.rs, cli/src/cmd/cast/wallet.rs, cli/src/opts/mod.rs, config/src/chain.rs, utils/src/lib.rs
Closes #1886
* use config `Chain` type which allows both, named and `u64` variants 
* make `--chain` optional so it can be provided by the user as well
the chain id to will now be determined:
use the chain id provided via cli, if nothing provided retrieve via rpc
```rust
let chain: Chain = if let Some(chain) = args.chain {
chain.into()
} else {
provider.get_chainid().await?.into()
};
```
=> fix: allow any chain id in cast

cli/test-utils/src/macros.rs, cli/tests/it/cmd.rs
`forgetest!` macro supports attributes now so separate `forgetest_ignore` macro is obsolete
=> refactor: remove forgetest_ignore macro

cli/tests/it/config.rs, config/src/lib.rs, config/src/rpc.rs
Closes #1935
* adds a new config type where multiple rpc pairs can be defined, including env vars (#1034)
Note: 
* env var format is preliminary and may change, env var parsing is not very sophisticated atm, only looks for `${}`
* this only adds support for declaring them in the config but nothing else, will get integrated in with (https://github.com/foundry-rs/foundry/pull/1715)
=> feat: add RpcEndpoints type

.github/workflows/cross-platform.yml
noticed an uptick in long running cross-platform tests, possibly related to fork test, suggest skipping them.
makes me think that the current backoff impl might need some fine tuning since it currently is exp with the number of requests that are currently ratelimited which can get large real quick
=> ci: skip all fork tests during cross platform test

cli/src/compile.rs
Contracts that are scripts exceeding the contract size limit cause `forge build --sizes` to fail. This PR, in combination with https://github.com/foundry-rs/forge-std/pull/89, update the size checks to ignore scripts by looking for a new `IS_SCRIPT` method
=> feat: exclude IS_SCRIPT contracts from size report

anvil/core/src/eth/mod.rs
add missing `with = "sequence"` attribute so single params are deserialized correctly
=> fix(anvil): add missing sequence deserialize

anvil/tests/it/main.rs, cli/tests/it/main.rs
(semi)ensure we're using a free port ref #1984
a better way would be to use port 0 and let the OS find one but it would be a bit messy returning this from the axum Server object after binding it...
has code duplication, but negligible imo
=> test: check if next port is free

cli/tests/it/script.rs
don't drop the handle and API object
keep them alive for the entirety of the test, I think it should be fine to drop them but just to rule out any side effects for https://github.com/foundry-rs/foundry/issues/1984
=> fix: dont drop anvil server handle

cli/test-utils/src/util.rs
strip code dependent Backtrace info from fixtures correctly
match multiline everything between `Location -> Backtrace` which contains the file and line number
=> fix: match multiline correctly in ignore regex

Cargo.toml
check if this will speed up the forge integration job a bit
it should be acceptable that we'll spend a bit more time compiling foreign deps since these are cached anyways and won't impact local testing significantly
alternatively we could try running with `local` profile (at least for integration test), I think the release profile will  be to demanding and slow things down even more
=> test: set opt-3 level for deps in test profile

cli/assets/ContractTemplate.s.sol
When I want to test something and init a new project, it won't compile if I change the contract name / file name / constructor args in `src/Contract.sol` unless I fix `script/Contract.s.sol` first.
Use the same approach as for the `test/Contract.t.sol`, which does not import / interact with the template contract.
Opinionated: Use `startBroadcast` instead of `broadcast`, as it seems to be used more often.
=> refactor: change script template

cli/src/cmd/utils.rs
Context provided here: https://github.com/foundry-rs/foundry/issues/2002. This change ensures that gas estimation is not underestimated for Optimism.
Following the solution to ensure we don't calculate gas differently for Optimism, as explained here by @mds1 and @joshieDo (thanks for the help! 😄) https://github.com/foundry-rs/foundry/issues/2002#issuecomment-1158936417. I am only addressing the first point in this changeset.
To test, successfully ran the same script with the same contract and args as specified in the [issue](https://github.com/foundry-rs/foundry/issues/2002#issue-1273968058) on anvil forks of optimism and optimism kovan. Also successfully ran a separate deploy script that was previously failing on prod optimism.
=> fix: don't use provider gas estimate for optimism

fmt/README.md, fmt/src/formatter.rs, fmt/src/visit.rs, fmt/testdata/FunctionCallArgsStatement/fmt.sol, fmt/testdata/FunctionCallArgsStatement/original.sol
add support for formatting `Expression::FunctionCall`, `Expression::FunctionCallBlock` & `Statement::Args`
=> feat(fmt): function call args statement

.github/workflows/cross-platform.yml, .github/workflows/docker-publish.yml, .github/workflows/project.yml, .github/workflows/test.yml
Saw some jobs taking more than 2 hours https://github.com/foundry-rs/foundry/runs/6950320447?check_suite_focus=true which means it should be fixed spereately this just adds a safely check to ensure CI execution time is not drained 
GitHub default is 360min which is a lot. Looking at past runs nothing that passes really goes beyond 40mins so having a 60min timeout should give enough room.
=> ci: add 60min timeout

anvil/rpc/src/error.rs, anvil/src/eth/error.rs, anvil/tests/it/geth.rs, anvil/tests/it/revert.rs
Closes #1871
geth returns `code: 3` for revert errors which web3.py expects
https://github.com/ethereum/web3.py/blob/c741e55b8ac95fed72a7135e7bb0e9f0d4a40431/web3/_utils/method_formatters.py#L628
return 3 for revert
cc @[unparalleled-js](https://github.com/unparalleled-js)
=> fix(anvil): use geth compliant error code for reverts

utils/src/selectors.rs
@mds1 reported that `cast 4byte` would also return events that matched the signature (instead of just functions):
```
$ cast 4byte 0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925
Approval(address,address,uint256)
$ cast 4byte-event 0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925
Approval(address,address,uint256)
```
Upon further investigation we were actually just looking up `0x8c5be1e5` with `cast 4byte`, and the function that matches that selector has the signature `Approval(address,address,uint256)`.
This PR is strict about the length of topic 0 and function selectors to avoid confusion.
Another alternative I've considered was to just warn the user and perform the lookup anyway.
```
$ cast 4byte …
```
=> fix: strict selector/topic lengths in cast

cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/mod.rs, cli/src/cmd/utils.rs
ref https://github.com/foundry-rs/foundry/issues/2002#issuecomment-1158188333
>Force --slow on Arbitrum and Optimism. Both of don't have mempools like L1's so if you send multiple txs they get rejected with nonce too low.
> Move RPC gas estimation right before sending the intended tx, and add a note to the output indicating the "total gas/ETH cost estimates" shown beforehand aren't guaranteed to be accurate (since we don't estimate Optimism costs correctly)
--
Also removed the first script gas estimation if we have a RPC present, since it doesn't give any valuable information. Some users were also confused by the [expected] discrepancies on both.
=> fix(forge): force optimism and arbitrum to `--slow` mode

.github/workflows/cross-platform.yml, .github/workflows/release.yml
We originally disabled Windows cross-platform builds and releases because we ran out of memory for some reason. Building from source for Windows might be a non-starter for some (experience/effort/resource constraints) so we should investigate re-adding Windows support.
Re-enable Windows and figure out if it works/why it didn't before. Also fix any cross-platform tests that fail on Windows
Closes #773 and #2021
=> ci: re-enable windows

cli/src/cmd/cast/run.rs, evm/src/trace/node.rs
`cast run` is another command which benefits from the signature identifier. I don't think `forge test` benefits from it, for example.
before:
after:
While adding, I noticed another issue. Since the external databases (4byte and sam) do not specify the function outputs, we were getting an empty list of output tokens.
after fix:
=> feat(cast): add signature identifier to `cast run`

anvil/server/src/lib.rs, anvil/src/config.rs, anvil/src/lib.rs, anvil/src/server/mod.rs, anvil/tests/it/anvil.rs, anvil/tests/it/anvil_api.rs, anvil/tests/it/api.rs, anvil/tests/it/fork.rs, anvil/tests/it/gas.rs, anvil/tests/it/logs.rs, anvil/tests/it/main.rs, anvil/tests/it/pubsub.rs, anvil/tests/it/revert.rs, anvil/tests/it/traces.rs, anvil/tests/it/transaction.rs, anvil/tests/it/txpool.rs, anvil/tests/it/wsapi.rs, cli/test-utils/src/script.rs, cli/tests/it/cmd.rs, cli/tests/it/main.rs, cli/tests/it/script.rs
gets rid of the `next_port` stuff and use port 0 by default so the OS can auto select a port
ref #2045
use proper `axum::Server` type aliases that allows us to retrieve the actual local addr that we need for the `NodeHandle`
=> refactor: use port 0 in tests

anvil/src/config.rs
Ref #2036
depending on the endpoint, `eth_getBlockByNumber` may still return a pending block for the block number returned by `eth_blockNumber
if not set, we find the latest block that has a `hash` field.
we start with "latest" and walk back, but at most 2 blocks, which should be sufficient
=> fix: pick latest fork block safely

cli/src/opts/cast.rs, cli/tests/it/cast.rs
closes #2050
make `cast block` behave as `seth block`  https://github.com/dapphub/dapptools/tree/master/src/seth#seth-block
*breaking change*: remove `--block` and `--field` named arguments
=> refactor!(cast): nameless cast block and field attributes

Cargo.lock, Cargo.toml, cli/src/cmd/forge/coverage.rs, cli/src/cmd/forge/mod.rs, cli/src/cmd/forge/script/executor.rs, cli/src/forge.rs, cli/src/opts/forge.rs, evm/Cargo.toml, evm/src/coverage.rs, evm/src/coverage/mod.rs, evm/src/coverage/visitor.rs, evm/src/executor/builder.rs, evm/src/executor/inspector/coverage.rs, evm/src/executor/inspector/mod.rs, evm/src/executor/inspector/stack.rs, evm/src/executor/mod.rs, evm/src/lib.rs, evm/src/trace/identifier/etherscan.rs, evm/src/trace/identifier/local.rs, evm/src/trace/identifier/mod.rs, forge/src/coverage.rs, forge/src/lib.rs, forge/src/multi_runner.rs, forge/src/result.rs, forge/src/runner.rs
Adds test coverage support to Forge.
> **You cannot currently run this locally easily**
>
> This PR depends on https://github.com/gakonst/ethers-rs/pull/1201, so to run locally you must clone `ethers-rs` from that branch
> and update the patch section in `Cargo.toml` to point to your patched ethers. Then, run `foundryup -p .`.
Simply run `forge coverage` to get a coverage summary.
An LCOV reporter is also included: `forge coverage --report lcov`. Currently the LCOV file is written to `./lcov.info` but this is going to move.
I've had to rewrite this feature many times.. I wrote what I thought would be a good structure, only to find out later that something would not work and/or fit into the current structure, so I scrapped most of it and tried again.
Initially, the thought was to analyse …
=> feat: forge coverage

cli/src/cast.rs, cli/src/opts/cast.rs
Closes #2077
```
$ ./target/local/cast tx 0x8ee80b1fdc814a71aaf11d01b4409c37de43e48b2221251d625d123df221098f --json | jq -r .input | ./target/local/cast 4byte-decode
1) "mint(uint256,bytes)"
1655145740
0xe26b098c2e13597b890be3e99cd4d77d2d2ac222d4097a3c6e3109b8214f53862ee444293619012a112d647143ff8f178983b663db20d7a98c6a0d2bca56150e
```
=> feat: support stdin in `cast 4byte-decode`

cli/src/cmd/forge/inspect.rs
Found this https://github.com/foundry-rs/foundry/issues/610#issuecomment-1067972155 which is super cool. For some reason though it does not contain the contract name which sometimes is useful when checking inheritance chain.
Added the field to the table as it's already present in the non pretty print.
=> feat: add contract to pretty output

cli/src/cmd/cast/run.rs, cli/src/cmd/forge/script/build.rs, cli/src/cmd/forge/script/mod.rs, cli/src/compile.rs, ui/src/lib.rs
There were a couple scenarios where the debugger was not showing the proper source code. This happened because of two different issues:
1. If the script was part of a project, we were still using `compile_files(...)`. However, calling `forge test --debug` would result in a weird project state where source files coming from the artifacts would be having repeated source IDs. Which would then lead to wrong sources being shown on the debugger. [Note: `forge test --debug` --calls-> `forge debug`  --calls-> `forge script --debug`]
2. `run_debugger` was passing to the `Tui` debugger all artifacts (contract_name -> artifact) and sources (source_id -> String) from the project. Contracts with the same name were overwriting each other.
1. Only call `compile_files(...)` if it's a standalone script. …
=> fix(forge): debugger showing wrong sources at times

.github/workflows/cross-platform.yml, .github/workflows/docker-publish.yml, .github/workflows/release.yml, .github/workflows/test.yml
Replaces `cargo test` with `nextest`, and also fixes a potentially flaky port assignment routine.
Benefits of nextest:
- Instead of building 6 times, we build 3 times
- The test runs themselves do not require Rust
- Good integration with coverage tools (see https://github.com/taiki-e/cargo-llvm-cov)
- Nextest can retry and report on flaky tests
- We can partition slower test suites if we want
- Faster than Cargo
Cons:
- While nextest does not require anything special and is 1:1 compatible with Cargo's test runner, it might still be a concern that we use nextest remotely and not necessarily locally
- Since it's super fast a lot of our tests are outed as being super flaky lol
The workflow works like this:
- We build archives of test executables using nextest
- Integration tests, unit tests …
=> ci: use nextest

cli/src/cmd/forge/script/executor.rs
`AddressIdentity` now saves the identifier [path:contractName] on `AddressIdentity.contract`, instead of just the name. This caused `contractName` not to be picked up on `TransactionWithMetadata`.
use `utils::get_contract_name` on the identifier when creating `address_to_abi`
=> fix(forge): `contractName` not showing up on broadcast log

Cargo.lock, cast/Cargo.toml, cast/src/lib.rs, cli/Cargo.toml, cli/src/cast.rs, cli/src/cmd/cast/mod.rs, cli/src/cmd/cast/rpc.rs, cli/src/opts/cast.rs, cli/test-utils/src/util.rs, cli/tests/it/cast.rs
Cast doesn't have any way to interact with non-standard RPC endpoints. The main use case here would be something like `anvil_mine`
Implement a `cast request` subcommand to send raw JSON-RPC requests.
```
cast-request 
Perform a raw JSON-RPC request
USAGE:
cast request [OPTIONS] <METHOD> [PARAMS]...
ARGS:
<METHOD>
RPC method name
<PARAMS>...
RPC parameters
Parameters are interpreted as strings. If you wish to pass a JSON value you can prepend
the value with a ':'. To start a string with a ':' prepend with '::'. For example:
request doThing 123   => {"method": "doThing", "params": ["123"] ... }
request doThing :123  => {"method": "doThing", "params": [123] ... }
request doThing ::123 => {"method": "doThing", "params": [":123"] ... }
OPTIONS:
-h, --help
Print help information
-r, --rpc-url …
```
=> Add a `cast rpc` method for raw JSON-RPC reqs

cli/src/cmd/forge/coverage.rs, evm/src/coverage/mod.rs, evm/src/coverage/visitor.rs
Correctly applies hit data for files with multiple contracts.
The behavior was caused by the fact that the per-contract source maps are indexed with the instruction counter for that contracts bytecode only. This means that you could have multiple source maps for one source file, if you had multiple contracts in that source file. One range of elements in each source map might map to different ranges in the source code - which means that going by instruction counter is not enough.
Hopefully that makes a bit of sense - this PR resolves two issues:
1. Some coverage items were marked as covered multiple times, if there were multiple contracts in a source file.
2. Some coverage items were marked as covered, while they were not, if there were multiple contracts in a source file.
Closes #2103
=> fix: correct hit data for multi-contract files

common/src/errors.rs, common/src/fs.rs, evm/src/executor/inspector/cheatcodes/config.rs, evm/src/executor/inspector/cheatcodes/expect.rs, evm/src/executor/inspector/cheatcodes/ext.rs, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/cheatcodes/util.rs, evm/src/lib.rs, forge/src/multi_runner.rs, testdata/cheats/Cheats.sol, testdata/cheats/File.t.sol
Closes https://github.com/foundry-rs/foundry/issues/2096
1. Collect allowed paths same way we do it for solc compilation.
2. Check every file reading/writing operation against allowed paths and revert if path isn't allowed.
=> feat(forge): filesystem cheatcodes should respect allowed paths

fmt/README.md, fmt/src/formatter.rs, fmt/src/lib.rs, fmt/src/macros.rs, fmt/testdata/RevertNamedArgsStatement/fmt.sol, fmt/testdata/RevertNamedArgsStatement/original.sol
- fmt formatting of `Statement::RevertNamedArgs`
- separate `macros` module
=> feat(fmt): revert named args

cli/src/compile.rs
Closes https://github.com/foundry-rs/foundry/issues/2093
```console
➜  mev-example git:(curve20220521) ls
cache  foundry.toml  interface  lib  out  README.md  remappings.txt  test
```
```console
➜  mev-example git:(curve20220521) forge test --fork-url $ETH_RPC_URL --fork-block-number 14811888 -vvv
Error:
no contracts to compile, contracts folder "/Users/shekhirin/Projects/mev-example/src" does not exist.
Check the configured workspace settings:
root: /Users/shekhirin/Projects/mev-example
contracts: /Users/shekhirin/Projects/mev-example/src
artifacts: /Users/shekhirin/Projects/mev-example/out
tests: /Users/shekhirin/Projects/mev-example/test
scripts: /Users/shekhirin/Projects/mev-example/script
libs:
/Users/shekhirin/Projects/mev-example/lib
remappings: …
```
=> fix(cli): don't check sources directory existance during compilation

anvil/src/eth/api.rs, anvil/tests/it/revert.rs
Closes #1871 (for good)
in the event of a revert while estimating gas we returned the request's data instead of the transaction out data...
while debugging this I also came accross #2117
return revert data correctly
Referenced example in #1871 now prints:
```text
Failed: execution reverted: RevertStringFooBar
```
cc @unparalleled-js
=> fix(anvil): return tx out data correctly on revert

fmt/src/formatter.rs, fmt/src/solang_ext/as_str.rs, fmt/src/solang_ext/loc.rs, fmt/src/solang_ext/mod.rs, fmt/src/solang_ext/to_string.rs, fmt/testdata/ArrayExpressions/fmt.sol, fmt/testdata/ArrayExpressions/original.sol, fmt/testdata/DocComments/fmt.sol, fmt/testdata/NamedFunctionCallExpression/fmt.sol, fmt/testdata/NamedFunctionCallExpression/original.sol, fmt/testdata/ThisExpression/fmt.sol, fmt/testdata/ThisExpression/original.sol, fmt/testdata/UnitExpression/fmt.sol, fmt/testdata/UnitExpression/original.sol
=> feat(fmt): misc expressions

evm/src/decode.rs, evm/src/executor/abi.rs
Same as https://github.com/foundry-rs/foundry/pull/1916 but for `address[]` arrays.
See discussion in https://github.com/foundry-rs/forge-std/pull/95.
=> Document latest "log_array" for address arrays

cast/src/tx.rs, cli/src/cast.rs, cli/src/opts/cast.rs
Expose an option `--priority-gas-price` for setting max priority fee per gas of EIP-1559 transactions.
=> feat(cli/cast): expose option to set max priority fee per gas

cli/tests/it/script.rs, evm/src/executor/inspector/cheatcodes/env.rs, testdata/cheats/Broadcast.t.sol
ref https://github.com/foundry-rs/foundry/issues/2110
Apply the same prehook patch that we use on `broadcast` cheatcodes.
=> fix(forge): correct nonce before vm.getNonce on `script`

cast/src/lib.rs, cli/src/cast.rs, cli/src/opts/cast.rs
The value type in a mapping has no effect whatsoever on the slot it occupies, so to avoid confusion we should remove it.
The slot of all of these mappings are computed using the same command (assuming they occupy the same slot):
```solidity
mapping(address => address);
mapping(address => uint);
mapping(address => T);
```
The command being `cast index address <key> <slot>`.
To get the slot of a nested mapping, e.g. `mapping(k1 => mapping(k2 => T))` you would do:
```
cast index k2 <key 2> $(cast index k1 <key 1> <slot>)
```
`k1` being the type of `key 1` and `k2` being the type of `key 2`. Note how the order is inverted, i.e. the above command would access  `mapping[key 1][key 2]`.
Closes #2141
=> fix: remove `to_type` in `cast index`

cli/src/cmd/forge/coverage.rs, evm/src/coverage/mod.rs, evm/src/coverage/visitor.rs, evm/src/executor/inspector/coverage.rs, evm/src/executor/inspector/debugger.rs, evm/src/utils.rs
Some small refactoring and solution for #1967 
We want good branch coverage in `forge coverage`, which means detecting the following scenarios:
- Calls to `assert` and `require` should result in branching (one branch reverts, the other one doesn't)
- If statements with no else block should have an implicit else
- Else if statements should also be considered a branch
`assert` and `require` require us to inspect the bytecode that the source map identifies as representing them. Generally, this bytecode follows the format:
```
PUSH [PC if condition is true]
JUMPI
[eventually revert]
```
That is, we need to find bytecode that identifies an `assert` or a `require` and look for a JUMPI preceded by a PUSH. The first branch is the instruction directly after JUMPI, because this branch will …
=> feat(coverage): better branch handling

cli/src/cmd/forge/create.rs
Closes https://github.com/foundry-rs/foundry/issues/2123.
I think the issue stems from that when `estimate_gas` call in `provider.fill_transaction` is executed, `value` hasn't been set yet.
Set `value` before calling `provider.fill_transaction`.
=> fix(forge/create): fix forge create tx value setting

Cargo.lock, cli/src/cmd/forge/script/broadcast.rs
Blocked by https://github.com/gakonst/ethers-rs/pull/1427
Closes https://github.com/foundry-rs/foundry/issues/2137
This is mainly a problem for L2s with different gas calc
instead of setting gas limit to 0 which may be interpreted as a desired cap during gas estimation (by anvil), we remove it
=> chore(script): remove gas limit entirely

evm/src/executor/inspector/cheatcodes/util.rs, forge/README.md
Fixes #2158 
I thought about storing the curve order value in another way, like an array of bytes, but i think the marginal perf gain is not worth the less readable code.
=> fix(forge): new error message for vm.addr() when passing invalid private keys

cli/src/cmd/forge/fmt.rs
Thanks to #2177, `forge fmt` now correctly outputs a trailing new line. However, when using the `--raw` flag, `forge` now prints an extra line:
```sh
$ cat Contract.sol | forge fmt --raw
....
....
}
$
```
This PR simply changes `println` to `print` to get rid of the extra empty line.
=> fix(fmt): fix extra empty line on --raw

cli/src/cmd/forge/fmt.rs
Currently when formatting from stdin, the process always exits with code `1` if diffs are found, even when `--check` is not supplied. This should be considered a bug, as in this case an error code should only be used when formatting fails.
This PR adds a check on the `exit()` call for the `--check` flag.
=> fix(fmt): unexpected error exit code without --check

anvil/src/cmd.rs
Allow users to set the bind host of anvil via ANVIL_IP_ADDR environment variable.
Running anvil as a service in Github Actions with the docker container is currently not feasible because it's not possible to bind to all interfaces. Github actions allows setting an entrypoint, but cannot pass arguments to the entrypoint command, so `--host 0.0.0.0` will not work. Setting environment variables with options is possible with `--env ANVIL_IP_ADDR=0.0.0.0`, and would allow jobs in the workflow to access anvil.
Leverage clap to assign the host variable via environment variable if present.
=> feat(anvil): Set bind host with environment variable

cli/src/cmd/forge/fmt.rs
Fixes #2192.
I'm too scared to remove `|| !atty::is(atty::Stream::Stdin)` so I just re-ordered the branches instead.
=> fix(fmt): unexpected use of stdin

fmt/src/formatter.rs, fmt/testdata/SimpleComments/fmt.sol, fmt/testdata/SimpleComments/original.sol
on the block level, simple line comments get formatted as prefix comments
before formatting:
```solidity
contract Format {
constructor() {
uint256 a = 1;
// TODO: do this and that
}
}
```
after first run:
```solidity
contract Format {
constructor() {
uint256 a = 1;
// TODO: do this and that
}
}
```
after second run:
```solidity
contract Format {
constructor() {
uint256 a = 1; // TODO: do this and that
}
}
```
preserve the line comments on the block level
=> fix(fmt): preserve line comments in blocks 

Cargo.lock, anvil/tests/it/ganache.rs, anvil/tests/it/geth.rs, anvil/tests/it/revert.rs, anvil/tests/it/traces.rs, cli/src/cmd/forge/create.rs, cli/src/cmd/forge/fourbyte.rs, cli/src/cmd/forge/inspect.rs, cli/src/cmd/utils.rs, cli/tests/fixtures/can_create_template_contract-2nd.stdout, cli/tests/fixtures/can_create_template_contract.stdout, cli/tests/it/create.rs
~~**Blocked by https://github.com/gakonst/ethers-rs/pull/1449**~~
* fixes a bug where cached artifacts where ignored during create
* use improved ethers-solc getters
* add tests against local anvil
=> fix(create): use cached artifacts correctly

README.md
The Foundry/HH benchmarks image gets squashed as the view width decreases, e.g. it's squashed on mobile.
Specify image `width` instead of `height` to preserve the aspect ratio in those cases.
I kept the size of the image as was.
=> docs: fix benchmarks image

cli/src/cmd/forge/script/sequence.rs
=> chore(script): save transaction pretty formatted

cli/src/cmd/forge/create.rs
Handle whitespace correctly for constructor args file with forge create.
This was flagged in this issue I raised:
https://github.com/foundry-rs/foundry/issues/1384
If the constructor args file has whitespace at the end (ie a new line) then this adds anomalous (and unexpected) whitespace onto the end of the constructor argument string data, which is probably not what the user wanted. However, to make it easier to encode whitespace explicitly, if the constructor args file explicitly ends with a .json extension it interprets the file content as a json encoded array of arguments.
This uses .split_whitespace() instead of the less general .split(' ') to fix the whitespace issue for the non json case.
Otherwise, it uses serde_json on the file for json decoding.
=> Handle whitespace better with forge create constructor args file

evm/src/executor/abi.rs, evm/src/executor/inspector/cheatcodes/env.rs, evm/src/executor/inspector/cheatcodes/mod.rs, testdata/cheats/Cheats.sol, testdata/cheats/RecordLogs.t.sol
The methods `vm.recordLogs()` and `vm.getRecordedLogs()` provide the tester the ability to leverage information from the events emitted during the execution of a transaction.
Ref: https://github.com/foundry-rs/foundry/issues/543
While porting solutions from the CTF Ethernaut to Foundry, got bumped by the fact that when you create a challenge, you are calling the `Ethernaut.sol` contract with the address of the factory of the challenge you want to solve. `Ethernaut.sol` will invoke the factory, deploy a new challenge for you, and return the address of this new contract within an event `LevelInstanceCreatedLog(address indexed player, address instance)`.
In practical terms, one [can just modify the Ethernaut contract](https://github.com/OpenZeppelin/ethernaut/blob/60ba307bf3bc79c93b271d58c584 …
=> feat(forge): add cheatcodes vm.recordLogs() and vm.getRecordedLogs()

Cargo.lock, fmt/Cargo.toml, fmt/src/comments.rs, fmt/src/formatter.rs, fmt/testdata/LiteralExpression/fmt.sol, fmt/testdata/LiteralExpression/original.sol
=> feat(fmt): literal expressions 

.cargo/config.toml
I think this might mess up some hidapi stuff, so I'll merge and try to run a new nightly
=> fix: don't statically link C runtime on windows

cli/src/cmd/forge/install.rs, cli/tests/it/cmd.rs
If an unwitting user mistakenly tries to remove a `lib` using the `rm` command, a project can end up in a "broken" state where the respective dependency can be neither installed, removed nor upgraded. See: https://github.com/foundry-rs/foundry/issues/2207
Use the `--force` flag of the `git submodule add` command to enable a user to reinstall a package even after comitting  above mentioned mistake.
=> Add force flag to add submodule

config/README.md, config/src/lib.rs, config/src/rpc.rs, evm/src/executor/inspector/cheatcodes/config.rs
extends rpc endpoint functionality and documents it
this continues merging effort of #1715
* add another type that represents `ResolvedRpcEndpoints` that is used in `Cheatcodes` to get access to all configured endpoints
=> feat(config): extend rpc endpoint support

cli/src/cmd/forge/inspect.rs, cli/src/compile.rs, cli/tests/it/cmd.rs
`forge inspect` only accepted a Contract name so the entire project had to be compiled to get it.
* allow `<path>:<name>` so we can compile a single file.
* also cleans up some inspect code
=> perf(forge): compile single file if possible

foundryup/foundryup
=> fix: bail if sha lookup fails in foundryup

anvil/src/eth/backend/mem/mod.rs, anvil/tests/it/fork.rs
Closes #2255
previously during validation, the current env was used, but it should use the env of the pending block. This resulted in `anvil_set_next_block_base_fee_per_gas` not taking effect during pre-validation in `eth_sendTransaction`
use env with updated settings during validation
=> fix(anvil): use correct env settings during validation

cli/README.md, cli/src/opts/forge.rs
This PR removes an alias `s` for `script` subcommand since it duplicates with one for `snapshot`.
(Also adds `.` to the end of some subcommand descriptions as with other ones and updates README.md to follow the latest `forge` command for maintenance)
Closes https://github.com/foundry-rs/foundry/issues/2254
```console
$ cargo run --bin forge -- --help
Compiling foundry-cli v0.2.0 (/Users/m-ikeda/src/moricho/foundry/cli)
Finished dev [unoptimized] target(s) in 33.58s
Running `target/debug/forge --help`
forge 0.2.0 (0f6ed04 2022-07-11T16:00:34.562576Z)
Build, test, fuzz, debug and deploy Solidity contracts.
USAGE:
forge <SUBCOMMAND>
OPTIONS:
-h, --help       Print help information
-V, --version    Print version information
SUBCOMMANDS:
bind                Generate Rust bindings for smart …
```
=> fix(forge): Remove an alias for script subcommand

forge/src/multi_runner.rs
updates filter paths to use `path::MAIN_SEPARATOR`, to fix an issue introduced by #1715 where we use test filter like `.*cheats/Fork`
ref https://github.com/foundry-rs/foundry/runs/7299967730?check_suite_focus=true#step:11:208
=> fix: use platform agnostic filter paths for cheat tests

common/src/fmt.rs, testdata/fuzz/Fuzz.t.sol
Closes #2273
use `from_utf8_lossy` as slices are not guaranteed to be utf8 (when fuzzed for example)
=> fix: use utf8 lossy when fmt  byte slices

Cargo.lock, utils/Cargo.toml, utils/src/rpc.rs
shuffles all rpc keys once,
prevent imbalance, where most of the load falls on the first keys
=> test: shuffle rpc keys

cli/src/forge.rs, cli/tests/it/cmd.rs
Currently `forge update` recursively updates nested dependencies which can lead to problems outlined in https://github.com/foundry-rs/foundry/issues/2264
Remove `--recursive` flag from `git submodule` call inside `forge update` subcommand.
=> remove --recursive flag from git submodule call in forge update

anvil/src/config.rs, anvil/tests/it/fork.rs
Closes #2262
when in fork mode, we also used the base fee of the forked block as the _next_ base fee.
calculate and set the next base fee properly based on the forked block
=> fix(anvil): set base fee of next block in fork mode properly

forge/src/multi_runner.rs, forge/src/test_helpers.rs
path separators for windows are `\\`
tested here https://github.com/foundry-rs/foundry/runs/7327839027?check_suite_focus=true
=> fix: use platform dependant regex path separators

common/src/fmt.rs, testdata/cheats/ToString.t.sol
Closes #2306
hex encode bytes32 slices, same as `Bytes`
=> fix: hex encode bytes32 slice

cli/src/cmd/forge/init.rs, cli/src/cmd/forge/install.rs
Resolves #2211
Utilises `git submodules set-branch` feature to pin a submodule to a branch. 
Adds a `-b` option to `forge install` to specify the branch, otherwise looks for tag or commit hash.
Would love to know if there is any other better solution possible.
```bash
lforge install -b rari-capital/fuse-v1@feat/
Installing fuse-v1 in "/Users/sambhavdusad/Projects/testt/lib/fuse-v1" (url: Some("https://github.com/rari-capital/fuse-v1"), tag: Some("feat/"))
There are multiple matching branches:
[0] feat/ (original branch)
[1] feat/contract-packages
[2] feat/add-vulnerability-analysis
[3] feat/add-liquidation-tests
[4] feat/add-deployment-test-flow
Please select a tag (0-4, default: 1): 1
[1] feat/contract-packages selected
Installed fuse-v1
```
Installs fuse-v1 and pin it to branch chosen …
=> pin dependency to a branch

cli/src/cmd/forge/install.rs, cli/src/opts/forge.rs
Closes #2321
previously, parsing deps like `@openzeppelin/contracts-upgradeable` was handled poorly because it identified everything after `@` as the tag
* improve dep parsing
* add alias for `@openzeppelin`
=> fix(forge): support leading @ for org names

Cargo.lock, cli/src/compile.rs, cli/tests/fixtures/warn_no_tests.stdout, cli/tests/fixtures/warn_no_tests_match.stdout, cli/tests/it/test_cmd.rs
~~Blocked by https://github.com/gakonst/ethers-rs/pull/1480~~ bumped ethers
`forge build` can be executed in any dir and it will call `Project::compile` regardless.
running on a regular dir (with no sol files) will output:
```
forge build
```
this will handle the case if there are no sol files in the entire project and exit early with
`Nothing to compile`
=> chore(build): exit early if nothing to compile

cli/src/cmd/forge/config.rs, config/src/lib.rs
Changing the way tomls get parsed for configuration means that users will have to change their configuration files
This PR automates configuration file changes by adding a --fix flag to forge config. This also fixes duplicate warnings emitted for implicit profiles
Alternative to #2270
=> Add forge config --fix

cli/src/cmd/forge/init.rs, cli/src/cmd/forge/install.rs, cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr, cli/tests/it/cmd.rs
Closes #2303
previously it was possible to generate files in an _existing_ and dirty repo and fail once it comes to committing.
ensure area is clear before generating anything
=> fix(forge): check if existing git repo dirty before generating

Cargo.lock, cli/Cargo.toml, cli/test-utils/Cargo.toml, config/Cargo.toml, config/README.md, config/src/lib.rs, config/src/rpc.rs, evm/Cargo.toml, forge/Cargo.toml, forge/src/multi_runner.rs
Closes #2302
support `rpc_endpoints` like
```
goerli = "https://eth-goerli.alchemyapi.io/v2/${GOERLI_API_KEY}"
```
replace all env var placeholders one by one
=> feat: add env var interpolation support

.github/workflows/docker-publish.yml
updates actions deps
uses cache mount via docker buildx for faster rebuild
enforces permissions for id-token
=> ci(docker): improve docker build time

cli/src/opts/cast.rs
Closes #2338
* use `--async`, but keep `--cast-async` alias
* document flag
```
--async
Only print the transaction hash and exit immediately.
```
=> refactor(cast): --cast-async to --async but keep alias

config/README.md, config/src/lib.rs
The [config README](https://github.com/foundry-rs/foundry/tree/37e4376cfbf1d2ce35c0c4eb25f7131c9fc1f8e2/config) references a TOML syntax which causes the following warning in the latest version of `forge`:
> Implied profile [default] found in lib/LIB_NAME/foundry.toml. This notation has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead.
1. Update all stale reference to `[default]` to use `[profile.default`] instead.
2. Change the implicit config file in the test in `lib.rs` to use `[profile.default]`.
=> Fix profile prefix

Cargo.lock, config/Cargo.toml, config/src/chain.rs
We should be able to include `Chain` in types that need to be sent over the wire.
* Derive `Hash` for `Chain`
* Encode and decode `Chain` as a RLP `u64`
=> feat(config): impl fastrlp traits for Chain

Cargo.lock, anvil/core/Cargo.toml, anvil/core/src/eth/transaction/mod.rs
Implementing these traits will allow `TypedTransaction` to be encoded / decoded from RLP bytes, and allow `fastrlp` traits to be derived on types which contain a `TypedTransaction`.
* impl `fastrlp::Encodable` and `fastrlp::Decodable` for `TypedTransaction`
* non-legacy transactions are encoded and decoded with a RLP string header
* add encoding and decoding tests
=> feat(anvil): impl TypedTransaction fastrlp traits

anvil/core/src/eth/block.rs
Implementing these traits will allow `Block` and `Header` to be encoded / decoded from RLP bytes, and allow `fastrlp` traits to be derived on types which contain a `Block` or `Header`.
* impl `fastrlp::Encodable` and `fastrlp::Decodable` for `Header`
* derive `fastrlp::Encodable` and `fastrlp::Decodable` for `Block`
* add tests for `Header` encoding and decoding
* add roundtrip test for `Block` using network data
=> feat(anvil): impl fastrlp traits for Block

cli/src/cmd/forge/create.rs, cli/src/opts/ethereum.rs, cli/tests/fixtures/can_create_using_unlocked-2nd.stdout, cli/tests/fixtures/can_create_using_unlocked.stdout, cli/tests/it/create.rs
Closes #2337
* add `--unlocked` flag that allows sending with `eth_sendTransaction` if `ETH_FROM` is set
=> feat(create): add --unlock for sending with unlocked account

cli/src/cmd/forge/install.rs
The doc comment in `cmd/forge/install.rs` is incorrectly referring to the "Create command":
https://github.com/foundry-rs/foundry/blob/649d7ff42489dd993fa50d094fac8a81710587eb/cli/src/cmd/forge/install.rs#L1
Change the comment to "Install command".
=> Nit: fix doc comment in "forge/install.rs"

cli/src/cmd/forge/install.rs, cli/src/opts/forge.rs
Closes #2388
there was the case where a provided tag was updated to `""` string before checking out which resulted in the behaviour that was reported in #2388
* add more traces
* improve `match_branch` result type
=> fix(forge): don't match empty branches

evm/src/executor/inspector/cheatcodes/expect.rs, evm/src/trace/decoder.rs
Fixes https://github.com/foundry-rs/foundry/issues/2206
Topics can be empty, so naked `topics[0]` accesses can panic.
Check if topics exist before trying to access `topic[0]`
=> Fix anon events tracing and expects

forge/src/runner.rs
Closes https://github.com/foundry-rs/foundry/issues/2390
Ran this against some repos locally without issues, want to make sure CI passes before merging though
=> fix: reduce CALLER balance before executing tests

config/src/lib.rs
https://github.com/foundry-rs/foundry/commit/585e59e76b032b031faa8354f11bf2ff111cdd41 fixed #2412, but didn't update the docs for `ensure_solc` function to explain what happens now when the `offline` flag is enabled.
=> docs: explain `offline` check in `ensure_solc`

forge/src/multi_runner.rs
`test_fuzz` is not executing tests, since the runner does not include a `fuzzer`. Leading to `suite_result` being empty.
Add `fuzzer` and assert that `suite_result` is not empty.
=> fix(forge): `test_fuzz` was not executing the tests

CONTRIBUTING.md
I [spent](https://users.rust-lang.org/t/rustfmt-option-trailing-semicolon-not-respected-by-rust-analyzer/78788/2) hours today trying to figure out why running <kbd>CMD</kbd> + <kbd>S</kbd> in VSCode produced different formatting results compared to running `cargo +nightly fmt` in the CLI.
Other users have bumped into the same issue in the past (image source: the Telegram group "Foundry"):
Document the recommended settings Foundry contributors should have in the VSCode user settings.
=> Add indication about VSCode and rust-analyzer

cli/src/cmd/forge/script/executor.rs, cli/src/cmd/forge/script/runner.rs, evm/src/executor/mod.rs
ref #2474 
And should also close #1902  to my understanding. ( @naps62  )
Increment `block.number` in between calls during the onchain simulation.
=> feat(script): simulate mining on the onchain simulation with `--slow`

cli/src/opts/cast.rs
Minor fix that turns this
Into this
=> Fix long `cast upload-signature` description

cli/src/cmd/forge/test/filter.rs, cli/src/cmd/forge/test/mod.rs, forge/src/multi_runner.rs
the `--match-path` argument takes a glob, commonly `./test/*`, however the leading current path `./` results in mismatches since the matcher is called with `test/Contract.sol`.
also the matcher was compiled on every invocation
closes #2477
* handle `./` case
* add `GlobMatcher` type that compiles the glob regex while parsing, so it can be reused efficiently
* move filter to sub module
=> fix/perf(forge): improve glob path matching

Cargo.lock, anvil/Cargo.toml, anvil/src/anvil.rs
Closes #2445
* add `completions <shell>` subcommand to anvil, analogous to forge and cast
=> feat(anvil): add shell completions subcommand

fmt/src/comments.rs, fmt/src/formatter.rs, fmt/testdata/ArrayExpressions/fmt.sol, fmt/testdata/IntTypes/fmt.sol, fmt/testdata/IntTypes/preserve.fmt.sol, fmt/testdata/IntTypes/short.fmt.sol, fmt/testdata/ReturnStatement/original.sol, fmt/testdata/RevertStatement/fmt.sol, fmt/testdata/SimpleComments/fmt.sol, fmt/testdata/SimpleComments/original.sol
Fixes #2410. This also fixes some behavior within empty lists and comment spacing after parentheses. Lastly this requires that postfix comments must either follow a postfix comment or a piece of code. This simplifies somewhat the logic for postfix/prefix comment distinction
=> Bugfix(fmt): Fix comment spacing in block and comments in lists

ui/src/lib.rs
In certain cases, we could underflow a `Duration` in the debugger, causing a panic.
Use saturating subtraction
=> Prevents underflow in duration calc in debugger

cli/src/cmd/cast/wallet.rs, cli/src/opts/wallet.rs
Often the intended usage for the `cast wallet address` is to get an address for a specific private key different from the ones specified in your environment.
It's natural to specify this private key as a single argument to this command like so `cast wallet address 0x0123...`. This PR preserves previous behavior if no argument is specified, but will override environment wallet settings if the argument is present.
The code I wrote to initialize `Wallet` struct looks too verbose, maybe there is a better way to write it?
=> Add `PRIVATE_KEY` arg to `cast wallet address`

config/src/macros.rs
Add helper macro that also merges the target type itself when converting to `Figment` which is not the case for `impl_figment_convert!`
this will be required for the `TestArgs` for example #1658
=> feat(config): add additional helper macro

config/src/rpc.rs, evm/src/executor/inspector/cheatcodes/config.rs, testdata/cheats/RpcUrls.t.sol
Closes #2514
if we failed to resolve an endpoint with interpolated env vars, we retry again if it is requested
=> feat: retry unresolved env vars

cli/src/cast.rs, cli/src/cmd/cast/wallet.rs, cli/src/opts/ethereum.rs
allows `cast send --chain <name of chain>`
=> refactor: use named Chain for ethereum ops

evm/src/executor/inspector/cheatcodes/ext.rs
* make ffi safer
* support non hex command result
* remove dangerous unsafe call
* add several checks (len, non empty)
* more verbose errors
decode if output is hex otherwise return output as is
=> refactor: safer ffi function and return non hex as string

cli/src/cmd/forge/install.rs, cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr
https://github.com/foundry-rs/foundry/issues/2525#issuecomment-1200301785
"There are changes in your working/staging area. Commit them first or add the `--no-commit` option."
changed to
"This command requires clean working and staging areas, including no untracked files. Modify .gitignore and/or add/commit first, or add the --no-commit option."
(actually it would be even clearer to change that last "add" to "use" ... oh well)
=> proposed error message change per #2525

Cargo.lock, Cargo.toml, anvil/src/eth/backend/db.rs, anvil/src/eth/backend/mem/in_memory_db.rs, anvil/src/eth/backend/mem/mod.rs, evm/Cargo.toml, evm/src/coverage/visitor.rs, evm/src/executor/backend/fuzz.rs, evm/src/executor/backend/in_memory_db.rs, evm/src/executor/backend/mod.rs, evm/src/executor/fork/backend.rs, evm/src/executor/fork/cache.rs, evm/src/executor/fork/database.rs, evm/src/executor/inspector/cheatcodes/env.rs, evm/src/executor/inspector/cheatcodes/mod.rs, evm/src/executor/inspector/coverage.rs, evm/src/executor/inspector/debugger.rs, evm/src/executor/inspector/tracer.rs, evm/src/executor/mod.rs, evm/src/fuzz/strategies/state.rs, evm/src/utils.rs, ui/Cargo.toml
This is a pretty naive port, I think there are some places we can improve it a bit. For example, we can probably reuse the analysis from REVM now instead of building our own IC maps.
The speedup is also only really for fuzz tests that deploy their contracts in `setUp` or the constructor - we can potentially improve here as well
Depends on https://github.com/bluealloy/revm/pull/156
=> build: use new revm with analysis cache

evm/src/executor/inspector/cheatcodes/expect.rs, testdata/cheats/ExpectRevert.t.sol
`vm.expectRevert` returns some dummy return data that Solidity can decode. This is needed since if the call does not revert, and the function returns some data, Solidity **will** try to decode the return data.
The previous 320 bytes was not big enough in some cases, so we just increase to 512 bytes.
Increase dummy return data to 512 bytes (16 words of 256 bits).
Closes #2454
=> fix: increase dummy return data to 512 bytes

common/src/evm.rs, config/src/lib.rs
allow named chains in place of `--chain-id <name>`
replace `Option<u64>` with `Option<Chain>`
=> feat: support named chains for env args

evm/src/executor/inspector/cheatcodes/ext.rs
* ensure we trim non-0x prefixed output before attempting hex decoding (fix)
* trim string return (convenience)
this should also fix failing windows tests because the `-n` flag is no longer necessary and this apparently doesn't exist on windows
https://github.com/foundry-rs/foundry/runs/7641673465?check_suite_focus=true
=> fix: trim ffi output

evm/src/executor/inspector/cheatcodes/expect.rs, testdata/cheats/MockCall.t.sol
It might be preferred in some situations to mock functions on empty accounts instead of deploying a contract just to overwrite all of the calls. This works fine in a lot of cases, but if you mock a function with no return value, Solidity will insert an `extcodesize` check to make sure the target address has code to run.
Functions with no return values are usually mocked if you are mocking a contract that is acted upon by some other contract.
If the target of `mockCall` has no code we etch a singular 0 byte (`STOP`)
Closes #1987
=> feat: etch some bytes to empty accounts on mock

cli/src/term.rs
Rewrites the Solc reporter using yansi so the indicator respects `NO_COLOR`.
Unfortunately, it does not seem like yansi has the "clear line" etc. escape sequences
=> fix: make solc reporter respect `NO_COLOR`

evm/src/fuzz/strategies/state.rs
Our state fuzzing wasn't deterministic because we used a `HashSet` to store the state, which arbitrarily orders the data. Now we use a `BTreeSet` instead.
Closes #2571
=> fix: make state fuzzing deterministic

anvil/core/src/eth/mod.rs, anvil/src/eth/api.rs, anvil/src/eth/backend/mem/mod.rs, anvil/tests/it/anvil_api.rs
Closes #2341
hardhat uses DATA (H256) for the value field of `setStorageAt`:
https://github.com/NomicFoundation/hardhat/blob/e5d7c0d099780f477c28af23520a2ddf74fb317a/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L305-L311
use H256 instead of U256
=> fix(anvil): use H256 for setStorage value parameter

Cargo.lock, cli/Cargo.toml, cli/src/cast.rs, cli/src/forge.rs, cli/src/utils.rs
People want `.env` support
Loads `.env` before anything else so anything is configurable (`NO_COLOR` etc). Uses the `dotenv` crate which hasn't had an update in a while, but is widely used. Not sure if there are good alternatives.
Closes #840
=> feat: dotenv support

evm/src/fuzz/strategies/int.rs
Fixes #2560 
The problem was that generating random int relied on the overflow behavior for U256. I.e. it assumed that bits for U256 are just the bits of I256. This perfectly generates random I256. However it stops working when we generate I128 and use I256 for that. Because U128 is not overflown in I256.
=> Fixed fuzz int overflow

cli/src/cmd/forge/coverage.rs, cli/src/cmd/forge/snapshot.rs, cli/src/cmd/forge/test/mod.rs, forge/src/multi_runner.rs, forge/src/runner.rs
We introduced `--include-fuzz-tests` to make gas snapshots less prone to change from fuzz RNG because we had no way to make the fuzzer deterministic. Now that the fuzzer is deterministic we can remove the flag and include fuzz tests always
Removes `--include-fuzz-tests` and uses a deterministic seed for `forge snapshot` runs. This also cleans up the code a bit, since we introduced a variable we had to carry into many files to disable fuzz tests.
Closes #2553
=> feat: snapshot fuzz tests using deterministic seed

anvil/src/eth/backend/db.rs, anvil/src/eth/backend/mem/fork_db.rs, anvil/src/eth/backend/mem/in_memory_db.rs, anvil/src/eth/backend/mem/mod.rs, cli/src/cmd/forge/script/broadcast.rs, cli/src/cmd/forge/script/sequence.rs, cli/tests/it/script.rs
the test introduced in #2524 makes use of `roll` cheatcode, first by
`vm.roll(block.number - numUpdates)`;
then simulates mining by 
```
for(uint i = 0; i < numUpdates; i++) {
vm.roll(block.number + 1);
hashChecker.update();
}
```
which does `blockhash(block.number - 1)`
this highlighted a problem with block hashes in anvil that were not updated internally in the `Db`
this meant that if a tx requires a hash for a block that was already mined _by_ anvil but is now missing in the DB's internal storage it will try to query it from the endpoint but if there's no new block it will return the 0 hash `blockhash(block.number - 1)`
manually insert the new blockhash in the db after mining a new block
=> fix(anvil): update blockhash in db 

fmt/src/formatter.rs, fmt/testdata/DocComments/fmt.sol, fmt/testdata/DocComments/original.sol
#2597
trim the end of line when writing doc block comments
=> fix(fmt): doc block trailing whitespace

cli/src/cmd/forge/script/executor.rs
closes #2593
We collect local and external contract names through tracing. However, tracing is only enabled with verbose mode.
Always enable tracing. Since we're only talking about `forge script`, I'd say the performance hit is not significant.
=> fix(forge): always enable tracing to collect contract names without requiring `-vvvv` on `forge script`

cli/src/utils.rs, cli/test-utils/src/lib.rs
`dotenv()`
>  It loads the .env file located in the environment's current directory or its parents in sequence.
I think we should restrict this to cwd + project dir only, so no env vars are read from outside the project
=> fix: only load env vars from cwd and prj root

common/src/calc.rs
The gas report of my test suite is panicking when providing `FOUNDRY_FUZZ_RUNS=0`, because it's computing the mean of an empty array (`&func.calls`)
Check if the array is empty in `calc::mean`
- Closes #2611
=> Fix mean on empty arrays

cli/src/cmd/forge/build/mod.rs, cli/src/cmd/forge/install.rs
It's nice
Use `git submodule status` to check if the project has submodules that have not been pulled. If there is, we pull them by calling `forge install`
Closes #2098 with the note that we should create a new issue for the discussion in there about #2386
=> feat: install missing deps on build

testdata/fuzz/Fuzz.t.sol
Tests are failing
Fix them
1. `testFailFuzz` did not fail as it should in some cases. This is because `proptest` just makes us generate a new tree on every test case, so effectively we're just throwing random numbers at the fuzz test. Since we run 256 times, there is a probability that we don't hit `x = 5` exactly, so I just broadened the chance of failure (`x > 128` fails the test)
Closes #2548
=> test: fix tests

cli/src/cmd/forge/test/mod.rs, forge/src/result.rs
Prints the test suite name in the failure summary in case there are similar test names in the project.
Closes #2581
=> feat: print test suite names in failure summary

evm/src/executor/backend/mod.rs, evm/src/executor/fork/multi.rs, forge/src/multi_runner.rs, testdata/repros/Issue2623.t.sol
Ref #2623
fixes the issue where env.block values like timestamp weren't updated correctly on `rollFork`.
couldn't reproduce the RPC issues mentioned
* update current env.block with fork values on `rollFork`
=> fix(fork): update env correctly on roll fork

evm/src/executor/backend/mod.rs, forge/tests/it/repros.rs, testdata/repros/Issue2629.t.sol
Closes #2629
>juggling different evm states at a time is a bit complex.
>
> The way this works with https://github.com/bluealloy/revm is, that there's a Subroutine that holds the "hot" accounts loaded from the underlying Database that feeds the Account/State data to the subroutine so it can apply changes to the state while the evm executes.
In a way the Subroutine is something like a cache that
> check if account is already loaded (hot)
if not load from the Datbase (this will then retrieve the account via RPC in forking mode)
when we created a fork, we only replaced the Database object, so if the account was loaded (1.) previously, then wouldn't reach 2. and the state is not updated on this new fork.
> the fix is to adjust the SubRoutine when creating a fork.
As explained …
=> fix: use separated SubRoutines for multifork

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/build/mod.rs, cli/src/cmd/forge/install.rs
Ref https://github.com/foundry-rs/foundry/issues/2633
which should run this automatically only if git is installed and only on the install folder, `git submodule status [path]`
=> fix: auto install only lib folder if git exists

Cargo.lock, cli/Cargo.toml, cli/src/cmd/forge/script/cmd.rs, cli/src/cmd/forge/script/mod.rs, common/src/constants.rs
Contracts above 24KB were getting deployed, leading to failed transactions.
closes #2535
Checks for the deployed bytecode size and issues a warning if above it. If `--broadcast` is passed, then it requires the user for manual confirmation to deploy.
=> feat(forge): detect max code size on deployed contracts during `forge script`
