cast/src/lib.rs
cast/src/tx.rs
cli/src/cast.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/mod.rs
cli/src/opts/cast.rs
cli/tests/it/cast.rs

This PR aims to implement https://github.com/foundry-rs/foundry/issues/2253
We add a `--create` flag to `cast estimate` that accepts contract bytecode, constructor, and arguments. 
In order to maintain the existing interface and use `--create` the way `seth` does, I split out the `Estimate` command into default args, and optional subcommands `--create`.
If `--create` is set, we use a different set of arguments. We hash the constructor and argument data, append it to the contract bytecode, and set it to the data field. Setting the `to` value is technically allowed, but drastically changes the gas estimation -- and results in a potentially inaccurate estimate.
Any of the following are valid usages:
`cast estimate --create <CODE> <SIG> [ARGS...]`
`cast estimate --create <CODE> DATA`
`cast …

Add create flag to estimate command

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

I find myself often having to reach to `ethers.js` or `ethers-rs` when interacting with smart contracts that make use of bytes32-encoding of strings, sometimes only to generate an argument for a contract call. Since bytes32 strings have already been supported in `ethers-rs` for a long time (via 2 util functions), it makes sense to expose the functionalities through the `cast` command line tool.
This PR adds two subcommands: `--format-bytes32-string` and `--parse-bytes32-string`. Both accept positional arguments as well as input from stdin.

feat(cast): subcommands for formatting and parsing bytes32 strings

---

cli/src/cmd/forge/build/mod.rs

Ref https://github.com/foundry-rs/foundry/issues/2633
instead of aborting if we fail to auto install missing deps, make this a warning. If the deps are indeed missing it will fail regardless.

chore: make auto install missing dep err a warning

---

cli/tests/it/cast.rs

common args must be set before the `--create` subcommand

test: set estimate params correctly

---

anvil/tests/it/traces.rs
evm/src/executor/inspector/tracer.rs
evm/src/trace/mod.rs

when the first `CallTrace` was pushed, the `CallTrace` of the default `CallTraceNode` at index (depth) 0 was updated with the `new_trace` (`CallTrace::update(CallTrace)`), which didn't update the `caller`, so the caller was always the default address (0x00000...).
deprecate the `update` function and instead replace the `trace` of the `CallTraceNode` if depth == 0
but maybe replacing could have side-effects?

fix(evm): set trace node depth 0 correctly

---

Cargo.lock
anvil/Cargo.toml
anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/validate.rs
anvil/tests/it/fork.rs
anvil/tests/it/proof/mod.rs

#2646 was the final straw for `parking_lot::RwLock<Db>`.
After looking at the logs and wrapping my head around what's locked sync and what's locked async in various contexts, I came to the conclusion the `Db` should be guarded by `tokio::sync::RwLock` instead for several reasons:
the `Db` trait is a sync abstraction over fork+mem db, fork being the critical implementation.
when we execute transactions, we need mutable access due to `revm`'s `Database` abstraction, this means we need to acquire a `WriteGuard` for the duration of the evm execution.
In fork mode, is can take a while because if the evm needs data we don't have yet it will be fetched.
So while the `WriteGuard` is active for mining a block, a call to 
`set_balance(&self) {
self.db.read()....
}`
becomes blocking until mining has …

refactor(anvil): use tokio::sync::RwLock to guard Db

---

cli/src/cmd/forge/fmt.rs
fmt/src/comments.rs
fmt/src/formatter.rs
fmt/src/helpers.rs
fmt/src/inline_config.rs
fmt/src/lib.rs
fmt/src/macros.rs
fmt/src/solang_ext/loc.rs
fmt/src/visit.rs
fmt/testdata/InlineDisable/fmt.sol
fmt/testdata/InlineDisable/original.sol

Users may want to disable formatting for certain sections of code
Allows for inserting special comments in the source to disable formatting
```solidity
// forgefmt: disable-next-item
// forgefmt: disable-next-line
// forgefmt: disable-start
// forgefmt: disable-end
```

feat(fmt): Disable format ranges

---

evm/src/fuzz/strategies/invariants.rs
forge/src/runner.rs

Closes #2651
this was an invariant bug
where both `targeted_functions` and `possible_funcs` are empty
https://github.com/foundry-rs/foundry/blob/master/evm/src/fuzz/strategies/invariants.rs#L120
so it panics here 
https://github.com/foundry-rs/foundry/blob/e306e24c9bcf223af0de6f54e1774b727c430cfa/evm/src/fuzz/strategies/invariants.rs#L137
only select contracts with at least 1 function

fix(invariant): only considere contracts with at least 1 function

---

Cargo.lock
anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs
common/Cargo.toml
common/src/constants.rs
common/src/lib.rs
common/src/provider.rs

Make creating Retry providers more convenient,
this also includes a new timeout setting to set reqwest request timeouts to 30s, the default is None which can result in hanging requests
* `ProviderBuilder` helper
needs followup to replace all usage in cast

feat: add ProviderBuilder helper

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/tests/it/fork.rs
anvil/tests/it/traces.rs
evm/src/executor/inspector/tracer.rs
evm/src/trace/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/2656
Closes #2663
Fixes `traceAddress` calculation. this will add the index of the call in the parent node instead of the parent's depth
@naddison36 mind giving this another try, the from issue should be fixed as well

fix(anvil): calculate trace address acording to the spec

---

fmt/src/formatter.rs

fix(fmt): eof newline

---

cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/script/mod.rs
evm/src/coverage/anchors.rs
evm/src/coverage/mod.rs
evm/src/debug.rs
evm/src/executor/inspector/coverage.rs
evm/src/executor/inspector/debugger.rs
evm/src/fuzz/mod.rs
evm/src/utils.rs
forge/src/lib.rs
forge/src/runner.rs
ui/src/lib.rs

After enabling fuzz tests in coverage (no data is used yet) coverage went from taking about 2 seconds for solmate to 27 seconds. The hottest piece of code seems to be the coverage collector itself that does some very expensive computations (translating program counters to instruction counters and then recording them) on every call.
Instead of doing the PC -> IC translation in the inspector, we can do it once before or after we collect hit data. The hit data is then just a mapping of PC -> hits. This took the time back down to 2 seconds.
For coverage I opted to just move from using instruction counters in the anchors to program counters, so we use an IC -> PC map (since source maps are based on instruction counters, we need to translate from instruction counters to program counters in some …

perf: improve pc/ic mapping stuff

---

cli/src/cmd/forge/script/broadcast.rs

Closes https://github.com/foundry-rs/foundry/issues/2679
the if branch was not great because we had:
`script_config.evm_opts.fork_url.is_some() {self.evm_opts.fork_url.unwrap()}`
@joshieDo this section is a bit hard to make sense of, but this condition seemed off, is that the correct fix?
uses the fork_url that's initialized in the `ScriptConfig`

fix(script): use correct fork url

---

anvil/src/eth/backend/mem/mod.rs

since https://github.com/foundry-rs/foundry/pull/2369 the `storage` lock is no longer kept during mining so the `block_in_place` wrappers to read data from `storage` is no longer required as all write operations to `storage` are fast enough, only write to memory.
* rm `block_inplace` wrappers

perf(anvil): remove block_in_place task wrappers

---

anvil/src/filter.rs
anvil/src/service.rs

flip logic how filters are evicted, instead of `now` they now store their expiration deadline.
~~this is the only time we use `Instant::now -Duration` but is unlikely the reason for https://github.com/foundry-rs/foundry/issues/2685~~
Ther was an `tokio::time::interval` that internally uses substraction
apparently there can be some inconsitencies with Instant + Systemtimestamp+ system boot: https://github.com/rust-lang/rust/issues/48980
convert `now - dur` to `now + dur`
Closes #2685
* use `interval_a`t instead of `interval`

refactor(anvil): flip filter expiration timestamp

---

anvil/src/eth/backend/cheats.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/anvil_api.rs

Closes #1943
there were some changes in revm re `Bytecode` and how accounts are handled, previously it was sufficient to just set the `code_hash` to KECCAK_EMPTY. 
this is no longer the case, so #1943 resurfaced
* also remove the code temporarily when impersonating an account
* add test for gnosis safe contract

fix(anvil): also remove code when impersonating

---

cli/src/cmd/forge/script/runner.rs
cli/tests/fixtures/can_execute_script_command.stdout
cli/tests/fixtures/can_execute_script_command_fqn.stdout
cli/tests/fixtures/can_execute_script_command_with_args.stdout
cli/tests/fixtures/can_execute_script_command_with_returned.stdout
cli/tests/fixtures/can_execute_script_command_with_sig.stdout
cli/tests/it/script.rs

atm gas limit in script is `gas as returned by the executor` * multiplier (=1.3)
however, the gas returned by the executor is the exact gas value the call consumed, which might not be enough if used as gas_limit
use binary search over `(gas, gas*3)` to find the lowest gas limit with which the call succeeds and use that instead

perf(script): binary search gas estimation

---

anvil/src/eth/backend/mem/fork_db.rs
anvil/tests/it/abi.rs
anvil/tests/it/anvil_api.rs
evm/src/executor/fork/database.rs

Closes https://github.com/foundry-rs/foundry/issues/2341
rust port of python test https://github.com/foundry-rs/foundry/issues/2341#issuecomment-1210388372
~~for some reason the ethcall returns empty bytes, unclear at this point if this is a bsc issue or something else. setting, getting storage seems to work fine~~
turns out there was a caching issue that happened when `setStorage` was called before the account was loaded. because `set_storage` inserts a default account if it's missing, sigh
load the account first before setting storage

fix(anvil): load account first before setting storage

---

Cargo.lock
cli/src/cmd/forge/test/mod.rs
cli/test-utils/src/util.rs
cli/tests/it/cmd.rs
cli/tests/it/config.rs
config/src/lib.rs
forge/Cargo.toml
forge/src/gas_report.rs

See #2464 
Create a new Config field called `gas_reports_ignore` and a new field in `GasReport` called `ignore`. (Default value for `gas_reports_ignore` is an empty Vec&lt;String&gt;.)
Pass `gas_reports_ignore` as an argument to function `GasReport::new` so `GasReport`s are built with an ignore list.
The initialization of the variable `report_contract` decides if the contract has to be reported, using this logic:
Were:
- a: self.report_for.contains(&contract_name)
- b: self.ignore.contains(&contract_name)
- c: self.report_for.is_empty()
- d: self.report_for.contains(&"*".to_string())
In simpler terms: Report the contract every time it's listed on `report_for`. Report all contracts if `report_for` is either empty or contains "*". If you're reporting all contracts but one of them is listed …

feat(forge): add contract ignore list for gas reports

---

cast/src/lib.rs
cast/src/rlp_converter.rs

Closes #2683
handle ',' correctly, instead of comparing if the value is `eq(last)` use peekable

fix: join array items correctly

---

cli/src/cmd/forge/snapshot.rs

If a gas snapshot file has a test using T=200 gas, and the test now runs in S=100 gas, `forge snapshot --diff` will display:
```
testExample() (gas: -100 (-0.500%))
```
(T-S)/T needs to be multiplied by 100 to be a percentage
Closes #2707

Fix percentage change in gas snapshot diffs

---

anvil/core/src/eth/block.rs

I was having issue using Anvil with Go-Ethereum `EthClient`, which computes the block-hash from its header, even when fetched from a remote RPC which includes the block hash.
It seems that the RLP encoding of Anvil for a block-header post 1559 was wrong.
Specify the right list length for the block-header RLP encoding + add tests based on the official `ethereum/tests` repo

anvil: Fix invalid Block Header RLP encoding

---

config/src/fmt.rs
fmt/src/formatter.rs

feat(fmt): default line length 120

---

common/src/constants.rs

As seen here https://github.com/foundry-rs/foundry/issues/2646 the previous 30s timeout may not be enough.
this bumps it to 2minutes, which is high but this is basically only used as a precaution for hanging connections

fix: bump default timeout to 120s

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/api.rs
anvil/tests/it/fork.rs
anvil/tests/it/traces.rs
anvil/tests/it/transaction.rs

This fixes the issue reported in #2599 : the `pending` block wasn't taken into account for any of the state-reading RPC calls: `estimateGas`, `call`, `getCode`, etc.
The solution I'm proposing here is to re-work the `with_database_at` method, so that it can accept a `Pending` block argument, which includes the *required* pending transactions list in order to execute them, and pass the updated (temporary) `state` to anyone who needs it.
With this in place, all the required methods are now using this, which also simplifies some parts of the code (no need to manually count the pending transactions of an account to get the last `nonce`, etc.)
There are a couple of behavior changes though:
1. In the `eth_getCode`, `eth_getBalance`, etc. methods, when requesting on a previous block that is …

anvil: Run RPC calls in `pending` block when requested

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/genesis.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/tests/it/anvil.rs

currently if using anvil, keeping a consistent genesis block hash on new instances is impossible since the genesis timestamp cannot be manually specified. this is particularly important for running with graph-node as it checks the genesis hash on startup.
add a genesis block timestamp parameter, which allows the genesis block to be consistent every time

feat(anvil): add genesis block timestamp parameter

---

rust-toolchain

We added the `rust-toolchain` file because of an issue with a dependency that has since been resolved.
https://github.com/foundry-rs/foundry/issues/2314 suggested setting the `rust-version` field in `Cargo.toml` but as far as I could tell this does not work in a top-level `Cargo.toml` file for workspaces, so I opted to not add it to every single `Cargo.toml` here.
Closes #2314

chore: remove `rust-toolchain`

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/inspector/cheatcodes/fork.rs
forge/tests/it/repros.rs
testdata/repros/Issue2723.t.sol

Closes #2723
when the rolled fork is the active fork, update the active subroutine right away, this will ensure cached state (from previous block) is discarded

fix: update active subroutine if belongs to rolled fork

---

Cargo.lock
Cargo.toml
cli/tests/it/cmd.rs
cli/tests/it/config.rs
config/README.md
config/src/lib.rs

Blocked by https://github.com/gakonst/ethers-rs/pull/1590
Closes #2706
* support --include-path and absolute imports, See https://github.com/gakonst/ethers-rs/pull/1590
* drops custom remappings for `src`, `test`, `script`, is now handled via --include-path
* add `include-paths` config
* add tests

feat(forge): support solc --include-path

---

cli/src/cmd/cast/run.rs

If we run `cast run` on a block with a lot of transactions, there's a lot of waiting time without any kind of feedback.
Add progress bar.

cast: add progress bar to `cast run` 

---

cli/src/cast.rs
cli/src/cmd/forge/mod.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/compile.rs
cli/src/forge.rs
cli/src/lib.rs
cli/src/utils.rs

turn `cli` crate into a real lib crate which `forge` and `cast` then use.
this ensures that we compile cli as lib crate. before that, we basically had two `cli` crates since both bins declared the `mods` separately.
* add `lib.rs` with all mod declarations.

refactor: turn cli crate into lib crate

---

anvil/tests/it/traces.rs
cli/src/cmd/cast/run.rs
cli/tests/it/cast.rs
evm/src/executor/mod.rs
evm/src/executor/opts.rs

Closes #2705
The `env` was not configured properly, and instead used the default testing env of the `Executor`.
Also the executor was configured with cheatcodes which also modifies the env
* add new `Executor` functions to provide the env to execute a tx
* configure the `env` properly for the block of the tx
* disable cheatcodes
```console
cast run -v 0x2d951c5c95d374263ca99ad9c20c9797fc714330a8037429a3aa4c83d456f845
Executing previous transactions from the block.
Traces:
[120091] 0x99999999d116ffa7d76590de2f427d8e15aeb0b8::30000003(000000000000000000000000adda1059a6c6c102b0fa562b9bb2cb9a0de5b1f4000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a300000004fffffffffffffffffffffffffffffffffffffffffffff679dc91ecfe150fb …
```

fix(cast): configure env properly for cast run

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/mod.rs
evm/src/decode.rs

When running an `anvil`, it would be useful to print-out why a transaction reverted, when possible.
With [this bash script](https://gist.github.com/ngotchac/4ce8246a5f4c29fd5416430ab9649e7b), which sends reverting transactions (with and without a reason string, and with a custom error):
<details>
<summary>Hardhat prints the following logs:</summary>
```
eth_sendTransaction
Contract deployment: <UnrecognizedContract>
Transaction:         0xc00de227c941c281c89069a908a23220450ff65a062d6a2bcc5fe5a5610ac2f5
From:                0xb60e8dd61c5d32be8058bb8eb970870f07233155
Value:               0 ETH
Gas used:            53376 of 30000000
Block #1:            0xc6449303b0e267931e7f21767ff4310a4be860dda67044f9ab2d00dac2561dfa
Error: Transaction reverted without a reason string
[...] …
```

feat(anvil): Print the transaction's revert reasons

---

evm/src/trace/identifier/etherscan.rs

* add additional etherscan traces
* Arc client, while `etherscan::Client` is cheap to clone, `Arc<Client>` is more appropriate here

chore: etherscan traces and Arc'ed

---

cli/Cargo.toml

Sourcify support broke the release workflow because it used reqwest w/o `rustls`
Use `rustls`

build: use rustls for reqwest

---

cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/script/runner.rs
cli/src/cmd/utils.rs

Long time coming. By default we call `run()` on `forge script`, and we expect the script contract to have no arguments. However, we were not properly handling when that didn't happen.
closes #2770
ref #2432
Give a proper error when:
* the run signature is not found
* the constructor has arguments
* the constructor fails its execution

fix(forge): properly handle `forge script` initialization errors

---

fmt/README.md

Expand the existing `README.md` covering the `fmt` development process and contribution guidelines

forge(fmt): docs & contribution guide

---

anvil/src/anvil.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs

Help text incorrectly described the autocomplete spec as Figma spec in https://github.com/foundry-rs/foundry/pull/2736, but the terminal is called Fig: https://fig.io/

chore: figma -> fig

---

evm/src/fuzz/invariant/error.rs
evm/src/fuzz/invariant/mod.rs
forge/tests/it/invariant.rs

Traces from invariant failures can really be long. Especially with a high `invariant_depth` value. This aims to reduce the sequence to its minimum representation.
Add some basic shrinking:
```rust
/// Tries to shrink the failure case to its smallest sequence of calls.
///
/// Sets an anchor at the beginning (index=0) and tries to remove all other calls one by one,
/// until it reaches the last one. The elements which were removed and lead to a failure are
/// kept in the removal list. The removed ones that didn't lead to a failure are inserted
/// back into the sequence.
///
/// Once it reaches the end, it increments the anchor, resets the removal list and starts the
/// same process again.
///
/// Returns the smallest sequence found.
```
Is there a need for it to be optional?

feat(evm): add shrinking to invariant testing

---

evm/src/fuzz/invariant/error.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
forge/src/runner.rs

- Needed for coverage so we can identify contracts in fuzz tests for the coverage reports (#1964)
- Needed for gas reports (#1023)
- Separately asked for (#1102)
We were in fact already collecting traces in the EVM itself, we were just not carrying them over with us into other parts of Forge. Each fuzz case can now carry its own separate traces, and each counter example can as well.
In order to not flood the CLI only the last trace is displayed for fuzz tests that pass if the verbosity is high enough
Closes #1102

feat: fuzz test traces

---

cli/src/opts/multi_wallet.rs

closes #2709
When passed `--hd-paths`, `ledger` actually instantiates 2 `Ledger` wallets. The default `LedgerLive(0)` and the one with user provided path `Other(hd_path`. However, `ledger` cannot at the moment support more than two instantiations, since the first locks access to the device.
Even if we didn't instantiate the default path, the same error behavior would happen if used with multiple `--hd-paths`.
Temporarily limit ledger to one instantiation only, while we extend support on `ethers-signers` for more. Otherwise, `--hd-paths` is not usable at all.

fix(forge): temporary fix for `ledger` when using `--hd-paths` on `forge script`

---

anvil/src/eth/miner.rs
anvil/tests/it/transaction.rs

There was an issue when:
1. Switching off `auto-mining` mode
2. Sending a transaction
3. Switching on `auto-mining` mode
The transaction wouldn't be mined after (3). Even if we added a:
4. Send another transaction
The block production wouldn't be waken up.
It seems that the Poll context wasn't properly updated in `MinerInner` for each new poll. So when switching mode, the wake-up would be on an ancient Context.
I also took the liberty to modify the `ReadyTransactionMiner::poll` so that when switching on `auto-mining` it would mine transactions in the mempool that was received previously. Although I can understand if this is not wanted; so I can revert if needed.

fix(anvil): Wake-up tasks when switching mining-mode

---

evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/strategies/param.rs
testdata/fuzz/invariant/targetAbi/ExcludeArtifacts.t.sol

Functions without any mutable functions were not being excluded from potential targets. This would lead `proptest` to try and select from an empty list of random functions.
closes #2804
Exclude contracts without mutable functions at the artifact level.

fix(forge): exclude artifacts without mutable functions on invariant testing

---

cli/src/cmd/forge/script/sequence.rs

When a contract doesn't find a matching bytecode during verification, the user is left with no warning message.
closes #2807
Warn when matching bytecodes are not found, and provide a small hint on what the issue might be.
small fix: ends the loop early when it finds a matching contract, instead of going through the rest.

chore(forge): warn which contracts cant be verified on `forge script`

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/env.rs
forge/README.md
testdata/cheats/Cheats.sol
testdata/cheats/Difficulty.t.sol
testdata/cheats/Setup.t.sol
testdata/cheats/Snapshots.t.sol

Wanting to mock `block.difficulty`.
Adding a new cheatcode `vm.difficulty(uint256 newDifficulty)` to mock `block.difficulty`.

feat(forge): add cheatcode vm.difficulty()

---

cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/mod.rs
cli/test-utils/src/script.rs
cli/tests/it/script.rs

No reason to hide traces if the script has failed. 
closes #2793
Also:
* Hides `== Return ==` if script failed. `returned` has the revert reason, so it never shows anything here anyway.
* Decode revert on failure and add it to the `bail!` msg
* Fix: Even if `setUp()` failed, the script execution was going through. It would ultimately fail, since we do `result & method_result`, but traces would get confusing.

fix(forge): always show traces on script failure & small fixes

---

evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
forge/src/runner.rs

Closes #2796
only keep 1 set of traces per fuzz test, which gets rid of `fuzz_cases - 1` (redundant) traces (255 by default).
this greatly reduces memory consumption in verbose mode `-vvv`
previously running `forge test --no-match-contract 'Element|AceOfZk|StabilityPoolBridge' --no-match-test 'testRedistribution' -vvv` on https://github.com/AztecProtocol/aztec-connect-bridges peaked at ~12GB (due to large number of fuzz cases in combination with heavy test functions)
with this fix it's down to ~220MB peak

perf: don't keep all fuzz case traces

---

forge/src/runner.rs

Invariant testing requires `setUp` to be run with `tracing` enabled, to figure out which addresses are available. However, if there were other fuzz/normal tests in the contract, they too were being run with tracing enabled even without any verbose flag.
Restore original tracing setting.

fix(forge): restore tracing setting when there are invariant tests

---

anvil/src/config.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs

When using `anvil` in fork-mode, the `latest` block context had a timestamp of `1`. This was causing some issues when calling some contracts (cf. the added test, which calls a Yearn token's method, which down the stack depends on the timestamp).
Correctly set the `timestamp` in the block-env when creating the node, as well as when resetting the fork.

fix(anvil): Fix initial block timestamp in fork-mode

---

anvil/src/config.rs
anvil/src/eth/backend/genesis.rs
anvil/src/eth/backend/mem/mod.rs

when resetting fork, all account data including genesis/dev accounts got wiped, which then need to be fetched again via RPC.
Ref #2801
* cache genesis accounts at launch and reuse them after fork reset

perf(anvil): cache genesis accounts

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/cmd/cast/interface.rs
cli/src/cmd/cast/mod.rs
cli/src/opts/cast.rs
testdata/fixtures/SolidityGeneration/WithStructs.json
testdata/fixtures/SolidityGeneration/WithStructs.sol
utils/src/lib.rs

Closes #2722
* turn `Interface` variant into a standalone command
* fix duplicate `struct ` prefix

fix/refactor(cast): strip struct prefix and make interface a cmd

---

anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs

Closes #2744
if in forking mode and no blocks mined yet, delegate the `eth_getProof` call to the provider

feat(anvil): delegate eth_getproof in forking mode

---

cli/src/cmd/forge/verify/sourcify.rs

metadata is outputted by default now #2798

fix(forge): remove metadata requirement for sourcify verifier

---

anvil/src/cmd.rs

the `std::process::exit(0);` installed via the ctrl-c handler only fired in forking mode
always exist

fix(anvil): always exit on ctrl-c

---

anvil/src/filter.rs
anvil/src/pubsub.rs

The `NewBlockNotification` stream is an `UnboundedReceiver` which poll_next fn looks like
```rust
match self.next_message() {
Poll::Ready(msg) => {
if msg.is_none() {
self.inner = None;
}
Poll::Ready(msg)
}
Poll::Pending => {
// There are no messages to read, in this case, park.
self.inner.as_ref().unwrap().recv_task.register(cx.waker());
// Check queue again after parking to prevent race condition:
// a message could be added to the queue after previous `next_message`
// before `register` call.
self.next_message()
}
}
```
this means only if the receiver half of the channel is pending is the new waker registered.
always poll `NewBlockNotification` until it's pending in subscriptions this prevents cases where the `NewBlockNotification` returns `Ready(Some)` but the eth sub stream returns …

fix(anvil): poll receiver until pending

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/error.rs

hardhat will send evm_setNextBlockTimestamp as hex
support any numeric variant for `evm_setNextBlockTimestamp`

fix(anvil): accept hex for evm_setNextBlockTimestamp

---

.github/workflows/live-test.yml
.github/workflows/test.yml
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/sequence.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/sourcify.rs
cli/tests/fixtures/ScriptVerify.sol
cli/tests/it/verify.rs
evm/src/executor/inspector/tracer.rs
evm/src/lib.rs
evm/src/trace/mod.rs
evm/src/trace/node.rs
ui/src/lib.rs

Identifies and verifies contracts created during a `call` or `deploy`.
ref https://github.com/foundry-rs/foundry/issues/2518#issuecomment-1199961233
Since we recently enabled the traces for all scripts, independently of verbosity, we can get all the contracts through `CallKind::Create` and `CallKind::Create2` traces.
Also:
* Fix verification regression where libraries were not being used. And thus, failing any contract verification that required them
* Added a CI job that only happens on push to master since it requires the following repository secrets: `${{ secrets.ETHERSCAN_API_KEY }}` `${{ secrets.TEST_PRIVATE_KEY }}`. It deploys and verifies a script which uses predeployed libraries and contracts create inside contracts.

feat(forge): verify contracts created inside a call

---

Cargo.lock
Cargo.toml

Solc 0.8.16 is not available for Linux aarch64 in svm right now, but it is needed in about 2 hours
Use the patched version of svm-rs until it is merged (https://github.com/roynalnaruto/svm-rs/pull/60)

build: use temporary svm patch for linux aarch64

---

Cargo.lock
Cargo.toml
anvil/Cargo.toml
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/util.rs
anvil/tests/it/transaction.rs
cast/src/lib.rs
cli/src/cmd/forge/script/broadcast.rs
evm/src/executor/inspector/access_list.rs
evm/src/executor/inspector/mod.rs

The generated AccessList via `createAccessList` RPC call wasn't actually correct:
- It included the `coinbase` address (for which info was fetched, and thus added to the state diff)
- It didn't take into account for the `to` address whether storage was read or not
- The precompiles that should be excluded was a fixed list, not dependent on the fork
- Although not necessarily an issue, it kind of depended on `revm` implementation regarding the returned state-diff, which returned read accounts even though they weren't changed
I implemented a custom tracer which checks for some opcodes was address/storage slot will be read/written to.
The trace was implemented based on Geth's one: https://github.com/ethereum/go-ethereum/blob/23ac8df15302bbde098cab6d711abdd24843d66a/eth/tracers/logger/access_l …

fix(anvil): Fix AccessList generation

---

evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/invariant/filters.rs
evm/src/fuzz/invariant/mod.rs
evm/src/fuzz/strategies/invariants.rs
forge/tests/it/invariant.rs
testdata/fuzz/invariant/target/ExcludeSenders.t.sol

It's important to have a way to exclude senders. 
Similar to other filter methods: `excludeSenders()`. Exclusion takes priority on clashing.
`address(0)` is excluded by default (should we add more?)

feat(forge): add `excludeSenders()` on invariant testing

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/runner.rs

closes #2865 
Doesn't panic, and decodes traces when an onchain simulation fails. Also, it fails early instead of going through the rest of transactions.

fix(forge): decode traces when an onchain simulation fails

---

Cargo.lock
Cargo.toml
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/transaction.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/script/runner.rs
evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/backend/snapshot.rs
evm/src/executor/fork/cache.rs
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/fork.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/cheatcodes/snapshot.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/inspector/coverage.rs
evm/src/executor/inspector/debugger.rs
evm/src/executor/inspector/tracer.rs
evm/src/executor/mod.rs
evm/src/fuzz/invariant/error.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
evm/src/fuzz/strategies/state.rs
forge/src/runner.rs

~~Blocked by https://github.com/bluealloy/revm/pull/182~~
this should fix the recent debugger issues 
https://github.com/bluealloy/revm/commit/136555437e1c410508aafdd9948a43477c0d64ee
ref https://github.com/foundry-rs/foundry/issues/2870
patch until new revm released
> The updates are mostly internal. Externally it's mostly about renaming subroutine to journaled_state, replacing the Account::Filth flag with the corresponding boolean getters, and replacing the execution results from a tuple into a struct. ref #2878

fix: use revm patch

---

Cargo.lock
common/src/constants.rs
common/src/provider.rs

Ref https://github.com/foundry-rs/foundry/issues/2755
lowers the default timeout and instead supports multiple retries for request failures related to connection issues, like `reqwest::TimedOut`

feat: configure timeout retries

---

anvil/core/src/eth/mod.rs
anvil/core/src/eth/state.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/state.rs
anvil/src/eth/error.rs
anvil/tests/it/api.rs
anvil/tests/it/fork.rs

In `go-ethereum` (and maybe other clients too?), there is an additional optional parameter to `eth_call` which is called "StateOverride", cf. https://geth.ethereum.org/docs/rpc/ns-eth#3-object---state-override-set
It is useful in some conditions, for setting code/balance/etc. temporarily for a single call.
I implemented this new optional parameter, with added tests for most of the usages

feat(anvil): Add `stateOverride` to `eth_call`

---

cli/src/cmd/forge/test/mod.rs

Adds the `SignaturesIdentifier` (4byte/sig.sam) to `forge test` traces as well, since I've seen more people asking for it lately.

feat(forge): decodes external event/function signatures on `forge test`

---

evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue2898.t.sol

Closes #2898 
this was a regression introduced by the latest revm bump.
when modifying account data directly, we need to ensure the account gets loaded _and_ `touched`.
* add helper function that loads and marks the account as touched

fix(forge): ensure accounts are touched in cheatcodes

---

evm/src/executor/inspector/cheatcodes/ext.rs

When parsing a string, it will try the following in that order:
- It will try to parse as Address
- it will see if it starts with `0x`
- If it doesn't, it will return `string`
- else, it will return a `Bytes32` if `length` == 32 or `bytes` if not (bytes32 is a fairly common bytes type)
We could try to detect for Bytes8, 16, 32 but not sure it adds to the UX.

fix: return bytes or bytes32 if detected

---

Cargo.lock
anvil/Cargo.toml
anvil/src/eth/backend/db.rs
anvil/src/eth/backend/mem/cache.rs
anvil/src/eth/backend/mem/fork_db.rs
anvil/src/eth/backend/mem/in_memory_db.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/tests/it/transaction.rs
cli/test-utils/Cargo.toml
common/src/errors.rs
common/src/fs.rs
evm/src/executor/backend/mod.rs
evm/src/executor/backend/snapshot.rs
evm/src/executor/fork/backend.rs
evm/src/executor/fork/cache.rs
evm/src/executor/fork/database.rs

Closes #2880
previously we had an unbounded mem map that stored _all_ previous states
this will lower the limit to 1_000 blocks, roughly 30mins with 1s interval and extract the state of older blocks and write that in a temp dir until requested again.
This extract and init step is necessary because the state is essentially a `dyn Database` so instead this adds new functions to `clear` and `init` a `StateSnapshot`

fix(anvil): move old state to disk

---

Cargo.lock

Found regression merged yesterday, the newest revm fixes it.
More info in: https://github.com/bluealloy/revm/issues/186

fix: revm regression

---

anvil/src/eth/api.rs
anvil/src/eth/backend/time.rs

Ganache's [`evm_increaseTime`](https://github.com/trufflesuite/ganache/blob/d48d998bd057a82b78c15ce197de06abc3487d2c/src/chains/ethereum/ethereum/RPC-METHODS.md#evm_increasetime) returns the time offset in seconds while Anvil's returns nothing, which leads to unexpected errors. Example: [eth-brownie/brownie](https://github.com/eth-brownie/brownie) uses it to track the time offset of the provider, but it raises an error when trying to parse the call's result since it is not a number:
https://github.com/eth-brownie/brownie/blob/4ae5f527ea86eb95766fe225a0f67620ffd36022/brownie/network/state.py#L375
Return the input seconds in `EthApi::evm_increase_time`.

fix(anvil): return time offset in `evm_increase_time`

---

anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/time.rs
anvil/src/eth/error.rs
anvil/tests/it/fork.rs
anvil/tests/it/transaction.rs

So the initial goal of this PR was to fix an issue when reverting snapshots, that the timestamp wouldn't be reset (even though it could be done with `setNextBlockTimestamp` I guess).
I also found out that the timestamps aren't always increasing, which is kind of not-spec compliant (but this isn't necessarily an issue since setting state/code/etc. isn't), but doesn't follow what Hardhat is doing for example, and thus could break a few things (at least it broke some assumptions on my side).
I mainly reworked a bit the `TimeManager` implementation. First, it should always be able to know what was the last block timestamp: in fork mode it's easy, otherwise the genesis block already have a timestamp. I also factorized the `next_timestamp` and `current_call_timestamp` methods' computation part. …

fix(anvil): Ensure timestamp is always increasing

---

common/src/fs.rs
evm/src/executor/inspector/cheatcodes/config.rs
forge/tests/it/config.rs
testdata/cheats/File.t.sol

Closes #2890
prevent path traversal
* add normalize path function, can't use `std::fs::canonicalize` as this only works for existing files
* normalize path when checking if a path is allowed

fix: normalize paths

---

evm/src/coverage/anchors.rs

Some instructions that were selected to mark coverage items as covered were wayyyy too wide as the source range marked by the source map for those instructions cover almost the entirety of a function or a contract. This lead to #2897 (and maybe #2668?) since one of the branches was some global branch of the contract that was never taken (possibly an error path if the calldata selector does not match a known function?)
Ensure that the selected instructions's source range start *at or after* the source range we're interested in
Closes #2897

fix: ignore anchors that cover the entire contract

---

anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs

This PR fixes several things (split into different commits which should make reviewing easier):
1. The `backend.ensure_block_number` wouldn't return the right block number in fork mode, if called with a block-hash of a block preceding the fork. This would be breaking some RPC calls which accept a block hash as a parameter
2. The `*uncles*` RPC calls are now implemented (by adding an `uncles` cache in `forking`)
3. The `eth_getCode` works on blocks preceding a fork (in fork mode)
4. The ` eth_getBlockTransactionCountBy*` methods are implemented
Note that (2) was needing when fetching a block with uncles with geth's `ethclient`, which would request it if it finds a block header with uncles; and (4) is useful to get the number of pending transactions (which is its own method in geth's …

feat(anvil): Add some missing RPC implementations

---

anvil/src/cmd.rs

use named arguments for --timeout and --retries
cc @sunwrobert saw this on #2931 this was not intended and we should use named arguments here
use long

fix(anvil): use named arguments for timeout and retries

---

evm/src/fuzz/strategies/state.rs

There's an old report that immutables were not collected in the fuzzer. Immutables are sections in the bytecode of contracts that are replaced by constant values, so we *should* be collecting them (since we collect push bytes), but it turns out that we were not collecting push bytes in the initial fuzzer DB (i.e. from the state right after `setUp`).
See https://github.com/foundry-rs/foundry/issues/1168
Also collect push bytes after `setUp`. Closes https://github.com/foundry-rs/foundry/issues/1168
Note: The state dict after `setUp` for the test in #1168 contains about ~120 values. It seems that either one of the tests fail every time (which is what we want), but not super reliably. Increasing the fuzzer runs to 512 makes them both fail reliably, though.

fix: collect push bytes from test setup in fuzzer

---

evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
evm/src/fuzz/strategies/param.rs
evm/src/fuzz/strategies/state.rs

A follow-up PR resolving inconsistencies between #2929 and #2882 
add `include_push_bytes` flag on building initial fuzz state

fix: add `include_push_bytes` flag on initial state

---

evm/src/executor/backend/mod.rs
testdata/cheats/Fork2.t.sol

make caller non persistent by default
needs book update

fix: make caller not persitent by default

---

anvil/src/eth/backend/time.rs
anvil/tests/it/fork.rs

I actually introduced a bug in https://github.com/foundry-rs/foundry/pull/2920 ; sorry :/
So the issue is that after setting the next block timestamp manually, the following block will have a timestamp way in the future.
I had the order wrong in the subtraction between the new block timestamp and the current time...
I also added a test that ensures the issue is fixed.

fix(anvil): Fix wrong timestamp after manually set

---

Cargo.lock
cli/test-utils/Cargo.toml
cli/test-utils/src/script.rs

use `RetryProvider` in script, this prevents any hanging requests in spurious networks

chore: use retry provider

---

cli/tests/it/script.rs
cli/tests/it/test_cmd.rs
testdata/cheats/Broadcast.t.sol

* running `forge test` on `forge-std` takes a lot of resources (fuzzing) so we run them exclusively in serial
* also decreases the 100tx test to more sensible 50tx and run them in serial as well

chore: run resource heavy tests in serial

---

forge/tests/it/cheats.rs

this excludes tests that use `expectRevert` with a specific file pah, which is different on windows
ref https://github.com/foundry-rs/foundry/pull/2867

chore: exclude file related tests

---

evm/src/executor/inspector/cheatcodes/config.rs
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/File.t.sol

harden `writeFile|Line` cheatcodes and prevent write access to foundry.toml, otherwise it would be possible to modify the config (like `ffi`) via malicious cheatcodes.
* prevents write access to `foundry.toml` via cheatcodes.
* add additional check for `foundry.toml` in cheatcodes that write

fix: prevent write access to foundry.toml

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/forge/verify/sourcify.rs
cli/tests/it/verify.rs
config/src/lib.rs

Closes #2969
@rkrasiuk do we have a sourcify test?
instead of emitting the metadata as separate file, we put it in the artifact itself
sourcify verification is then still possible by extracting the metadata from the artifact

fix: put metadata in artifact instead separate file

---

cli/assets/.gitignoreTemplate

Follow up on https://github.com/foundry-rs/foundry/pull/2587 by adding `.env` in `.gitignore` when generated by Forge.

chore: add .env in gitignore template

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue2984.t.sol

Closes #2984
ensure the caller account is always set to prevent panic in revm finalize

fix: ensure caller is always set

---

cli/src/opts/multi_wallet.rs

Same as https://github.com/foundry-rs/foundry/pull/2099 but for `forge script`
Closes #2976 and closes #2978

fix: trim private keys

---

config/src/lib.rs

Currently, the env setting for standalone sections doesn't work as specified [in the book](https://book.getfoundry.sh/reference/config#formatter)
Map the env vars prefixed with standalone sections to respective key paths

fix(config): env for standalone sections

---

config/src/lib.rs

added more tests to cover current fallback behavior with profiles. the logic is the following
1. if the selected profile is `default` and no `invariant` config values were set, then common values (`runs`, `dictionary_weight` etc) will be taken from `fuzz` section if present or `InvariantConfig::default`
2. if the selected profile is other than `default` and no `invariant` section present, the common values will be taken from `[profile.default.invariant]` (which in turn falls back to `[profile.default.fuzz]`)
open for comments. happy to change/revert the fallback if it's too confusing 
cc @mds1 @devtooligan @transmissions11 @gakonst

test(config): fuzz profile sections

---

anvil/src/eth/api.rs
anvil/tests/it/transaction.rs

Should fix https://github.com/foundry-rs/foundry/issues/3017
The `latest` block was the default block when None is passed for gas estimation; however it might make more sense to take into account pending txs.
Set the block to Pending if None is given for gas estimation.
Note that this doesn't work when using `ethers-rs` since it overrides the None block parameter to `Latest`: cf. https://github.com/gakonst/ethers-rs/blob/13a0144abae32c45c01b1639929f612527994dd1/ethers-providers/src/provider.rs#L577
I think we might want to just not pass the block parameter if it's `None`

feat(anvil): Use `pending` as default block for estimateGas

---

Cargo.lock
anvil/Cargo.toml
anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/hardfork.rs
anvil/src/lib.rs

[Fork IDs](https://eips.ethereum.org/EIPS/eip-2124) are used in the p2p network to detect nodes that are not up to date, or on separate forks.
The `anvil::Hardfork` enum is a useful abstraction for working with hardforks. Adding a `fork_id` method allows for a status message to be constructed like this:
```rust
let status = Status {
version: EthVersion::Eth67 as u8,
chain: Chain::Id(1),
total_difficulty: uint!(36206751599115524359527_U256), 
blockhash: hex!("feb27336ca7923f8fab3bd617fcb6e75841538f71c1bcfc267d7838489d9e13d"),
genesis: hex!("d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"),
forkid: Hardfork::Latest.fork_id(), // or Hardfork::Frontier.fork_id(), etc.
};
```
* Add missing hardforks `Dao` and `GrayGlacier`.
* Add a `fork_block` method that returns a …

feat(anvil): add fork IDs and blocks to Hardfork

---

cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs

Currently `--hd-path` argument works only for hardware wallets. But it makes sense to apply it to mnemonic based wallets too. This PR does exactly that.
I moved this argument from `WALLET OPTIONS - HARDWARE WALLET` to `WALLET OPTIONS - RAW` and renamed to `mnemonic-derivation-path` for consistency, older `hd-path` alias is still available for backwards compatibility. The motivation for the rename is that there is already `mnemonic-index` option that applies to hardware wallet address derivation, so now the options are more consistent.
Just like with hardware wallets, if `mnemonic-derivation-path` argument is specified it will override `mnemonic-index` arguments.
Please check the implementation and provide any comments. Also my implementation of `mnemonics()` in `multi_wallet.rs` looks …

Respect derivation path argument for mnemonic wallets in `cast`

---

anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/inspector.rs
cli/src/cmd/forge/coverage.rs
cli/src/opts/multi_wallet.rs
evm/src/executor/inspector/tracer.rs

https://github.com/foundry-rs/foundry/issues/3067
Steps tracing in coverage with `-vvv` resulted in enormous memory growth but we don't really need such granular tracing in there. So now we only enable steps tracing in Anvil, when we're executing only a bunch of transactions (instead of lots of tests in parallel) and really care about using these traces later.
Memory usage before/after changes during running `forge coverage -vvv` in Solmate:
---
If, for some reason, we may want to have steps tracing in any of the `forge` commands, we can make it configurable here: https://github.com/foundry-rs/foundry/blob/4b9cca1790096c8bfdd50922bf22244983ad6e4f/evm/src/executor/builder.rs#L36-L41
and maybe enable with even higher verbosity.

feat(anvil, evm): make steps tracing configurable

---

cli/src/cmd/forge/coverage.rs

https://github.com/foundry-rs/foundry/issues/3072
```console
/Users/shekhirin/.cargo/bin/cargo run --color=always --bin forge -- coverage --root /Users/shekhirin/Projects/solmate
Finished dev [unoptimized] target(s) in 0.26s
Running `target/debug/forge coverage --root /Users/shekhirin/Projects/solmate`
Compiling 51 files with 0.8.15
Solc 0.8.15 finished in 2.39s
Analysing contracts...
Running tests...
+-------------------------------------------------------+------------------+------------------+-----------------+------------------+
| File                                                  | % Lines          | % Statements     | % Branches      | % Funcs          |
+======================================================================================================== …
```

fix(forge, coverage): versioned path source

---

cli/src/opts/multi_wallet.rs
cli/src/opts/wallet.rs

This PR adds support for raw mnemonics and renames `--mnemonic-path` to `--mnemonic`. `--mnemonic-path` is kept as an alias for backwards compatibility.
The value of `mnemonic` argument is tested for being an existing file, and if so it reads its contents as mnemonic, otherwise it's treated as a raw mnemonic. Valid usages are:
```bash
cast wallet address --mnemonic "test test test test test test test test test test test junk"
cast wallet address --mnemonic seed.txt
```

feat(cast): support raw mnemonics

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/verify.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/utils.rs

Closes https://github.com/foundry-rs/foundry/issues/3065.
Extract `read_constructor_args_file` from `create` as a util function and reuse it in `verify-contract`.

feat(forge): constructor-args-path option for verify-contract

---

cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs

Fixes the implementation in https://github.com/foundry-rs/foundry/pull/3078. Apologies for the oversight in the previous PR.
To provide ABI-encoded arguments for verification, we'll need the constructor signature in order to encode the arguments in the file.  Currently I'm using ABI info from the cached artifact to do this. But if there's more elegant way, please let me know.

fix(forge): verify-contract encode args from constructor-args-path

---

Cargo.lock
cli/src/cmd/forge/script/mod.rs
config/src/lib.rs

~~Blocked by https://github.com/gakonst/ethers-rs/pull/1656~~
it was reported `--etherscan-api-key mumbai` results in invalid API key even if specified in table.
This was an issue because `Chain` only matched: `polygon-mumbai`:
https://github.com/gakonst/ethers-rs/pull/1656
* Add additional etherscan-api-key tests
* bump ethers

test: add more etherscan api key tests

---

Cargo.toml
cli/src/cmd/forge/script/runner.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/mod.rs

https://github.com/foundry-rs/foundry/issues/3069

fix(evm, cheatcodes): prevent early filesystem commits

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3077.t.sol

Closes #3077
use the current depth when `rollFork` is called

fix(forge): set depth on roll fork correctly

---

evm/src/executor/backend/diagnostic.rs
evm/src/executor/backend/mod.rs

Ref https://github.com/foundry-rs/foundry/issues/3077
improve error message if contract was not found
* make note of `vm.makePersistent` if contract is not marked as such

chore: improve contract does not exists error message

---

cli/tests/it/script.rs

script test can be a bit flaky expensive on smol runners: https://github.com/foundry-rs/foundry/runs/8196349472?check_suite_focus=true
better to run them in serial

chore: run script remember key test in serial

---

evm/src/executor/backend/mod.rs
evm/src/executor/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3055.t.sol

Closes #3055
there were some changes in revm state recording, so we need to check the `JournaledState`'s present value of the slot that contains the `failed` variable when we revert a snapshot to record if there was a failure in a reverted snapshot

fix(forge): record snapshot failures correctly

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/fork.rs
common/src/constants.rs
common/src/provider.rs

Allow to configure a custom compute unit per second budget.
The alchemy free tier allows 330 CUPS which is used by the provider to anticipate retries
Ref https://github.com/alchemyplatform/alchemy-docs/blob/master/documentation/compute-units.md#rate-limits-cups
allows setting a custom CUPS value, for example Growth/Enterprise 
cc @sunwrobert

feat(anvil): allow setting custom compute units per second

---

cli/src/cmd/cast/wallet.rs
cli/src/opts/wallet.rs

Ref #3046
use password prompt_password to show prompt directly
rpassword only uses hiddeninput

chore: prompt password

---

evm/src/executor/inspector/cheatcodes/env.rs
testdata/cheats/Travel.t.sol

Resolves #3098 
Since chain ID is handled as `u64` internally, setting a value greater or equal to 2^64 by `cheats.chainId` cause the error because `cheats.sign`, etc. casting from `U256` to `u64`.
Unlike `cheats.chainId`, it is not allowed to set chain ID to a value greater or equal to 2^64 in config files and the `--chain-id` option. (Strictly speaking, in config files, setting a value greater or equal to 2^63 throws the error due to [this bug in toml-rs](https://github.com/alexcrichton/toml-rs/issues/256). )
This PR also disallows setting chain ID to a value greater or equal to 2^64 using `cheats.chainId`.

Fix chain ID overflow

---

cast/src/lib.rs
common/src/fmt/mod.rs
common/src/fmt/token.rs
common/src/fmt/ui.rs

add missing tuple + array return type formatting for `cast call`
* add `TokenDisplay` helper type that formats
* tuples: `(,,,)`
* arrays `[,,,,,]`
turn `common::fmt` into a standalone module

fix: format tuples and arrays

---

cli/src/cast.rs
cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/send.rs
cli/src/cmd/forge/create.rs
cli/src/utils.rs
common/src/provider.rs
config/src/endpoints.rs
config/src/lib.rs

Closes #3021
this allows aliases in place of `--eth-rpc-url "mainnet"` if `"mainnet"` is an entry in [rpc_endpoints]
* add helper functions `Config::get_rpc_url` that looks up if `eth_rpc_url` is an alias in the [rpc_endpoints] table and returns that instead
* `Config::get_rpc_url_or_localhost_http` will return "http://localhost:8545" if `eth_rpc_url` is None

feat: resolve rpc url aliases

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3110.t.sol

Closes #3110
when rolling the active fork, we also need to ensure the caller exists in the rolled journaledState
copy caller state

fix: copy caller state when rolling active fork

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3119.t.sol

likely fixes #3119
wasn't able to reproduce this but, I think what happened was that a call reverted and we wrongly diagnosed this related to missing account
also check the current state if the address is a contract

fix: check current state for calle on revert diagnose

---

evm/src/executor/inspector/cheatcodes/env.rs

Identical to https://github.com/foundry-rs/foundry/pull/3041, but to fix https://github.com/foundry-rs/foundry/pull/3111 
Wondering at what point we should abstract these checks into a helper method?
cc @devanonon

fix: use >= instead of > for private key check

---

evm/src/executor/inspector/cheatcodes/util.rs
testdata/cheats/Env.t.sol

This bug was found in the Telegram group: https://t.me/foundry_support/23118
uints should be read as big-endian from environment or strings.
Added more tests. I think these tests were only passing before because the hex strings were symmetrical! 😄

fix(forge): incorrect endianness used parsing uints

---

cli/src/compile.rs

The EVM contract size limit applies to runtime bytecode, NOT constructor code.
Source:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md
https://github.com/ethereum/go-ethereum/blob/d30e39b2f833fb75f1e529cd405061fb6b548b8d/core/vm/evm.go#L453-L458 (shoutout @mds1 for this link)
Using `get_deployed_bytecode_bytes` should measure runtime bytecode instead.

fix: use `get_deployed_bytecode_bytes` for codesize

---

cli/src/cmd/forge/snapshot.rs
forge/src/runner.rs
forge/tests/it/config.rs
forge/tests/it/invariant.rs

use function signatures as identifiers for invariant tests
fixes a snapshot bug where entries are formatted as `WETHInvariants:invariantTotalSupplyEqualsBalance (runs: 256, calls: 3840, reverts: 1860)`

fix: use invariant signatures instead of names in resuts

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/mod.rs

https://github.com/foundry-rs/foundry/issues/3133
Hotfix introducing the cmd option to enable steps tracing (disabled by default). Afterwards, we can implement lazy geth-style traces calculation on `debug_traceTransaction` and `debug_traceCall` requests.

feat(anvil): make steps tracing optional in cmd

---

cli/tests/it/config.rs
config/README.md
config/src/fuzz.rs
config/src/lib.rs
config/src/providers/mod.rs
config/src/warning.rs
evm/src/executor/inspector/cheatcodes/fuzz.rs
evm/src/fuzz/error.rs
evm/src/fuzz/invariant/error.rs
evm/src/fuzz/mod.rs
forge/src/lib.rs
forge/src/runner.rs
forge/tests/it/config.rs
testdata/foundry.toml

Closes https://github.com/foundry-rs/foundry/issues/1202.
Related discussion about the `vm.assume` error message formatting: https://github.com/foundry-rs/foundry/pull/3123.
1. Display clearer error message when fuzzing aborts due to too many rejects caused by `vm.assume`.
2. Remove `fuzz.max_local_rejects` in config.
3. Deprecate and replace `fuzz.max_global_rejects` with `fuzz.max_test_rejects` in config.
4. Also took this chance to revamp error handling in fuzz test module.
`foundry.toml`:
```toml
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
[fuzz]
max_global_rejects = 16
```
`test/Fuzz.t.sol`:
```solidity
pragma solidity 0.8.10;
import "forge-std/Test.sol";
contract ContractTest is Test {
}
function testFuzzAssume(uint256 a) external {
vm.assume(a …
```

fix(config): fuzz rejects

---

cli/src/cmd/cast/run.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/mod.rs

Closes #3143
`env.tx.transact_to` was misconfigured for CREATE transactions
configure correctly
```console
cast run 0xc2d97bb0bf727b63bcfe9b5440f506ea2a49225b2408358a5aeef70883a40cbf -v 
Traces:
[105297] 0x74d95845ba4b44dcb0f399ea55c405d8f94131ed::deploy()
├─ [50786] → new <Unknown>@"0xf3c25b1063a9fbf363c220e4646a4c0334f0b9a1"
│   └─ ← 143 bytes of code
└─ ← ()
Transaction successfully executed.
Gas used: 126361
```

fix(cast): configure env.tx correctly

---

cli/src/cmd/forge/build/mod.rs

BuildArgs is itself a Provider, use the merge macro instead

fix: merge buildargs provider

---

anvil/src/eth/backend/mem/in_memory_db.rs

```
warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
--> anvil/src/eth/backend/mem/in_memory_db.rs:65:13
|
63 |               let old_account = self.inner.accounts.get(&addr);
|                                 ------------------------------ immutable borrow occurs here
64 | 
65 | /             self.insert_account(
66 | |                 addr,
67 | |                 AccountInfo {
68 | |                     balance: account.balance,
...  |
78 | |                         old_account.map(|a| a.info.nonce).unwrap_or_default(),
| |                         ----------- immutable borrow later used here
...  |
81 | |                 },
82 | |             );
| |_____________^ mutable borrow occurs here
|
= note: `#[warn(mutable_borrow_reservation_conflict)]` on by …
```

fix(anvil): avoid mutable/immutable borrow conflict

---

cli/src/cmd/forge/coverage.rs

Sorry I did not intend to spam with tiny PRs, but there's another one of these (and no more warnings after this).
```
warning: cannot borrow `report` as mutable because it is also borrowed as immutable
--> cli/src/cmd/forge/coverage.rs:296:17
|
291 |               if let Some(source_id) = report.get_source_id(
|  ______________________________________-
292 | |                 artifact_id.version.clone(),
293 | |                 artifact_id.source.to_string_lossy().to_string(),
294 | |             ) {
| |_____________- immutable borrow occurs here
295 |                   // TODO: Distinguish between creation/runtime in a smart way
296 | /                 report.add_hit_map(
297 | |                     &ContractId {
298 | |                         version: artifact_id.version.clone(),
299 | …
```

fix(forge): avoid mutable/immutable borrow conflict

---

config/src/lib.rs

make it impossible to set `fs_permissions` via env var

fix: ignore fs_permissions via env

---

config/README.md
config/src/error.rs
config/src/lib.rs

Closes #3159
supports error code string identifiers and numbers for error codes, uses string identifiers in serialize

feat: support string aliases for error codes

---

cli/src/opts/cast.rs

Small oversight, negative numbers are already supported but clap was not allowing them
Add `allow_hyphen_values = true`

fix(cast): allow hyphens for negative numbers in --to-base

---

cli/src/cmd/forge/script/sequence.rs
evm/src/trace/mod.rs
evm/src/trace/utils.rs
utils/src/lib.rs

https://github.com/foundry-rs/foundry/issues/2975
Change logged address (input, output, ...) to checksummed with `ethers::core::utils::to_checksum`.
It converts `Address` to `String`, so including fix for some formatting.
still not fixing `broadcast` json file, WIP
This is my first PR, so I'm sorry if it's in a wrong manner.

Checksum address output in log_address event and broadcast files

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
cli/tests/it/svm.rs

Closes #3141
contains svm-rs patch with 0.8.17 support
patch can be phased out after published and upstreamed in ethers-rs
* added new test to ensure `forge test` works with latest version

feat: patch svm-rs with 0.8.17

---

Cargo.lock
evm/src/trace/mod.rs

~~Blocked by https://github.com/gakonst/ethers-rs/pull/1690~~
Closes https://github.com/foundry-rs/foundry/issues/3179
fix geth types breaking changes
encode memory like geth does https://github.com/ethereum/go-ethereum/blob/366d2169fbc0e0f803b68c042b77b6b480836dbc/eth/tracers/logger/logger.go#L450-L452

fix: breaking changes geth trace data

---

cli/src/handler.rs

Closes #3050
this could be related to this windows+lto issue https://github.com/rust-lang/rust/issues/81408 with once_cell (the eyre HOOK is a once_cell)
because there's nothing else that sets the hook, so it would only fail if once_cell itself fails to set it...
* makes installing the panic hook a noop on windows

fix: panic hook panic

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/mod.rs
forge/tests/it/repros.rs
testdata/cheats/ChainId.t.sol
testdata/cheats/Fork.t.sol
testdata/cheats/Setup.t.sol
testdata/repros/Issue3190.t.sol

Closes #3190
changes to env during setup, (`vm.chainId`) weren't tracked properly so subsequent tests started with the default value again.
update `env` after the `setup` call so any changes made during setup are recorded

fix: make env cheatcodes during setup persistent

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3192.t.sol

Closes #3192
revm will panic if the `caller` account does not exist in the final journaled state.
There was another edge case where this could have happened.
Ensure that the caller account always exists in the fork's journaled state when selecting another fork.

fix: ensure caller exists

---

cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/mod.rs
forge/tests/it/repros.rs
testdata/lib/ds-test/src/test.sol
testdata/repros/Issue3189.t.sol

Closes #3189
previously we effectively only checked the contract's own `failed` variable when evaluating success. This wouldn't detect failures like #3189.
DSTest also records failures by storing true inside the cheatcode's state. this way failing asserts from any contract are recorded
This contains two fixes:
* touch the account in `store` cheatcode, this ensures the change (`globalFailure`) shows up in the final changeset
* also clone the CHEATCODE_ADDRESS' state when evaluating success, so the `failed` function can lookup the `globalFailure` flag inside the cheatcode_address' state.
* update DSTest calls

fix: detect global failures

---

cli/src/cmd/utils.rs

Ref #3195
when extracting the `EmvOpts` from the config we should also set the actual URL if it was an alias.
@devanonon you wanna try this? this should cover at least all of `script`

fix: update fork url when extracting evm opts

---

cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/mod.rs
cli/tests/it/create.rs
cli/tests/it/script.rs
cli/tests/it/verify.rs

Deployment sizes check introduced in #2619 would not work for arbitrary bytecode deployed without an artifact and thus pass without errors.
Check against bytecodes from both artifacts and traces
Tested with, closes #2923:
Before: https://mumbai.polygonscan.com/tx/0xcf74fcecf15120bcf703598b4f47411f46210a5b6ffcef46a3e3919fd04f629b
(max codesize exceeded revert)
After:

fix(forge/script): deployment size check

---

cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/cast/wallet/vanity.rs

the previous impl was a regex match on the address in hex format, which required additional allocs
this will try to match against the address bytes directly if the (start, end) are valid hex,
this means however, that odd patterns are still parsed via regex. this is probably faster for longer patterns than left|right padding
it accepts all combinations of `--starts-with (hex|regex) --ends-with (hex|regex)`
```console 
cast wallet vanity --starts-with "0000"                                                                                                                                                         
Starting to generate vanity address...
Successfully found vanity address in 10 seconds.
Address: 0x00009AaB527c82E0ac9B53EB83DbBdd87aDeff14
Private Key: …
```

perf: improve vanity address matching

---

cli/src/cmd/forge/script/transaction.rs

the argument parsing appears to be a bit buggy atm.
until fixed, just log the error

fix: no hard error on failed CREATE argument deserialization

---

Cargo.lock
Cargo.toml
anvil/src/eth/backend/mem/inspector.rs
evm/src/executor/inspector/tracer.rs
evm/src/trace/mod.rs

continued work on top of https://github.com/foundry-rs/foundry/pull/3187
relevant piece of geth code: https://github.com/ethereum/go-ethereum/blob/366d2169fbc0e0f803b68c042b77b6b480836dbc/eth/tracers/logger/logger.go#L181-L206
Deposit WETH and debug this transaction
```bash
➜  ~ cast send --rpc-url http://localhost:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 deposit --value 1 --json |
jq -r .transactionHash |
xargs -I{} cast rpc --rpc-url http://localhost:8545 --raw debug_traceTransaction '["{}", {"enableMemory": true, "enableReturnData": true}]'
```
Check `SLOAD` instruction and storage slots associated with it (before, during, after)
Check `SSTORE` instruction and storage slots associated with it …

perf(evm): only store storage slot diffs and reconstruct full storage on request

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3220.t.sol

Closes #3220
There where a couple of issues with how multiple journaledstates would behave on reverts.
Revm uses checkpoints to track what to revert in case of a revert, these are tracked in the evm impl. But since we're replacing them on `selectFork` those checkpoints don't necessarily match if there's a revert after selecting another fork. which would lead to an underflow here https://github.com/bluealloy/revm/blob/1e25c99b544863d15610e9af8e623dd173397b48/crates/revm/src/journaled_state.rs#L430
This is fixed by simply adding empty JournalEntries when another fork is selected.
The other issue was with how the init `JournaledState` was determined:
https://github.com/foundry-rs/foundry/blob/233ba5c4da31c353cad44fbc067b8bb7028689c0/evm/src/executor/backend/mod.rs#L819-L825
however this not …

fix(evm): improve journaledstate handling on reverts

---

Cargo.lock
evm/src/trace/identifier/etherscan.rs

treat `BlockedByCloudflare` same as `InvalidApiKey` -> no more requests.
also fixes that we store the correct value `true`

chore: handle etherscan blocked by cloudflare

---

Cargo.lock
cli/src/cmd/cast/wallet/vanity.rs
cli/src/cmd/forge/bind.rs
cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/config.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/fmt.rs
cli/src/cmd/forge/fourbyte.rs
cli/src/cmd/forge/inspect.rs
cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/utils.rs
cli/src/lib.rs
common/Cargo.toml
common/src/compile.rs
common/src/lib.rs
common/src/term.rs

extracts `cli::compile --> foundry_common::compile` from #3006

refactor: move compile mod to common

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/ext.rs

I started this while investigating why patching code for a precompile via
```solidity
vm.etch(arbSys, vm.getCode("ArbitrumDomain.sol:ArbSysOverride"));
```
didn't work.
This doesn't work, simply because `getCode` returns the _deployment_ code
the books's example is:
```solidity
bytes memory args = abi.encode(arg1, arg2);
bytes memory bytecode = abi.encodePacked(vm.getCode("ArbitrumDomain.sol:ArbSysOverride"), args);
address deployedAddress;
assembly {
deployedAddress := create(0, add(bytecode, 0x20), mload(bytecode))
}
```
The same result could then be achieved by adding:
```solidity
bytes memory code = address(deployedAddress).code;
vm.etch(arbSys, code);
```
for stateless contracts this would be equal to
```solidity
vm.etch(arbSys, …
```

feat: add deployedCode cheatcode

---

evm/src/executor/backend/mod.rs
evm/src/executor/inspector/tracer.rs

Closes https://github.com/foundry-rs/foundry/issues/3237
In multifork, each fork has its own `State` that tracks the current depth separately.
which could result in out of bounds errors in the tracer that uses the depth to populate the tree. 
Under normal circumstances there are no gaps in depth, however, in multifork that could end up happening.
When selecting a different fork, handover the current depth, this ensures there are no gaps and the selected fork starts at the same depth

fix(evm): handover depth in multifork

---

cli/src/cmd/cast/run.rs
cli/src/cmd/forge/inspect.rs
cli/src/cmd/forge/script/mod.rs
cli/src/cmd/forge/test/mod.rs
evm/src/trace/decoder.rs
evm/src/trace/identifier/etherscan.rs
evm/src/trace/identifier/local.rs
evm/src/trace/identifier/mod.rs
evm/src/trace/mod.rs
ui/src/lib.rs

Debugging with sources is helpful, pulling sources from etherscan expands amount of source code available. Built off of [this PR](https://github.com/foundry-rs/foundry/pull/1413). 
1 . When identifying addresses for traces, collect addresses & sources.
2. Compile each contract address [and downloads the solc version required)
3. Provide them to the TUI debugger. 
Still can't handle vyper, `--via-ir`, or multifile sources.
In order to make these changes, we migrate the `compile` module to the common module. This makes the dependecy pattern more obvious and removes cyclical imports. The compile from etherscan function is now in this module and can be imported into other crates.
Example from ethereum mainnet: 
`cargo run --bin cast -- run …

feat(evm): Compile Etherscan Sources for use in Debugger

---

fmt/src/formatter.rs
fmt/testdata/DocComments/fmt.sol
fmt/testdata/DocComments/original.sol
fmt/testdata/SimpleComments/fmt.sol
fmt/testdata/SimpleComments/original.sol

ref #3184
don't trim doc comment line whitespaces

fix(forge): fmt doc comment spacing

---

cast/src/lib.rs

add additional check after failed `cast call` decoding that `to` is indeed a contract

chore(cast): improve cast call error

---

anvil/src/config.rs

Closes #3247
use default `gasLimit` if block's gaslimit is `0`

fix(anvil): use default gas limit if zero

---

anvil/src/config.rs

previously we determined the hardfork, if not provided as arg, by checking the block number in forking mode.
this should only be done if we're forking mainnet

fix(only): only derive hardfork spec on mainnet

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/mod.rs
forge/tests/it/core.rs
testdata/core/FailingTestAfterFailedSetup.t.sol

close #1291
Refactoring according to @onbjerg's comment
> We can refactor Executor such that we only really have the call_raw/call variants that return state changesets - call_committing/call_raw_committing would then just be very thin wrappers around these that also call db.commit(changeset). This cleans up the executor code a bit, and seems like the right path forward. I think I did attempt this at some point, but there was some annoyances in some other parts of the code so I shelved it to get REVM over the line.

fix(evm): refactor executor & detect `setUp` assertion failures

---

utils/src/abi.rs

close #3260. `cast interface` breaks if it encounters member accessed struct internal type like `struct Lib.StructType`
strip top-level identifiers in struct name

fix(cast): interface struct member access

---

cli/src/opts/mod.rs
cli/src/opts/wallet/error.rs
cli/src/opts/wallet/mod.rs
cli/src/opts/wallet/multi_wallet.rs

Ref https://github.com/foundry-rs/foundry/issues/2978
better error when parsing private key failed.
it can fail if:
* pk is invalid hex
* invalid signature, in which case we check if it's actually an env var (pk env var names can be valid hex)

chore: better private key error diagnostic

---

Cargo.lock
fmt/Cargo.toml
fmt/src/formatter.rs
fmt/src/solang_ext/ast_eq.rs
fmt/src/solang_ext/attr_sort_key.rs
fmt/src/solang_ext/loc.rs
fmt/testdata/SelectorOverride/fmt.sol
fmt/testdata/SelectorOverride/original.sol

close #3276
tangent: [tracking issue](https://github.com/ethereum/solidity/issues/11819) for overriding function selector in solidity

deps(fmt): bump ethers, solang-parser 0.1.18 & support for overriding function selector

---

Cargo.lock
cli/Cargo.toml
cli/benches/cast.rs
cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/cast/wallet/vanity.rs

`iter::repeat_with`'s function is not executed in parallel and is 20x slower than when called with any other constant time iterator (ranges etc) paired with a parallel map
- fix: hex_address_validator in the wrong spot
- perf: use `iter::repeat` (interchangeable with `(0..)`) with a parallel map instead of `iter::repeat_with`
- Using CPU
- OS: Ubuntu 22.04.1 LTS x86_64
- Kernel: 5.15.0-47-generic
- CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
- Using GPU
- OS: Windows 10 Pro
- Build: 19041.1.amd64fre.vb_release.191206-1406
- GPU: NVIDIA GeForce RTX 3060
- Rust: latest nightly
- Browser: Brave
---
- GTX 1070 OC: 179M/s
- GTX 1070: 163M/s
- RX 480: 120M/s
~2K/s per thread, with diminishing returns
- Local benches:
- (master) iter::repeat_with, 10K
- local: in ~1310ms ~= 7.7K/s
- range iter / …

perf(cast): improve vanity wallet generation

---

fmt/src/formatter.rs
fmt/testdata/TernaryExpression/fmt.sol
fmt/testdata/TernaryExpression/original.sol

fix(fmt): multiline ternary expression in assignment

---

cli/src/cmd/forge/bind.rs
cli/src/cmd/forge/build/core.rs
cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/config.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/flatten.rs
cli/src/cmd/forge/fmt.rs
cli/src/cmd/forge/geiger/mod.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/remappings.rs
cli/src/cmd/forge/remove.rs
cli/src/cmd/forge/tree.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/sourcify.rs
cli/src/cmd/utils.rs
config/src/error.rs
config/src/lib.rs

Ref https://github.com/foundry-rs/foundry/issues/3259
this adds additional `try_from_*` `ConfigLoader` functions that don't panic
this also improves the config error message:
```toml
[profile.default]
etherscan_api_key = 5
```
```console
forge config                                                                                                            
Error: 
failed to extract foundry config:
foundry config error: invalid type: found signed int `5`, expected a string for setting `etherscan_api_key`
```

refactor: use Config::try_from where possible

---

config/src/etherscan.rs
config/src/lib.rs

previously we required exact matching entries in the table: `Chain::to_string`
this also compares chain id, if set and returns the first matching entry with matching chain id

chore: try to find by chain

---

cli/src/cmd/utils.rs

Just tried deploying to optimism goerli and got a nonce too low error since it did not default to `--slow` like the other optimism chains.

fix: optimism goerli scripts default to --slow

---

cli/tests/it/config.rs
config/README.md
config/src/fs_permissions.rs
config/src/lib.rs
forge/tests/it/fs.rs
testdata/fs/Default.t.sol

change `fs_permission` default from `None` to `read` from project's output dir.
This will unblock `getCode` cheatcodes restrictions and is a reasonable default now that cheatcode access is closed off.
~~alternatively, we could change it from root to `out` dir instead?~~

refactor: allow project output dir read access

---

cli/src/cast.rs
cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/find_block.rs
cli/src/cmd/cast/rpc.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/cast/send.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs

replace `get_http_provider` usage with `try_get_http_provider` preventing an unwrap/panic

chore: use try_get_http_provider and prevent unwrap

---

config/src/resolve.rs
testdata/cheats/RpcUrls.t.sol

Flip env name and unresolved value in error message so we print
```
Failed to resolve env var `ABC` in `https://polygon-mumbai.g.alchemy.com/v2/${ABC}`: environment variable not found
```
instead of
```
Failed to resolve env var `https://polygon-mumbai.g.alchemy.com/v2/${ABC}` in `ABC`: environment variable not found
```

chore: flip unresolved interpolated and env var in err message

---

cli/src/cmd/forge/script/mod.rs
cli/src/cmd/utils.rs
common/src/provider.rs
config/src/lib.rs
utils/src/lib.rs

Closes #3195
don't use forced snake case case for entries in standalone sections like `rpc_endpoints`
also improves error message for invalid URLs, ref https://github.com/foundry-rs/foundry/issues/3178

fix: don't force snake case standalone sections

---

Cargo.lock
anvil/core/Cargo.toml
anvil/core/src/eth/proof.rs
anvil/core/src/eth/receipt.rs
anvil/core/src/eth/transaction/mod.rs

first step towards isolating `anvil-core`.
still depends on tracing support provided by `foundry-evm`.
~~Suggesting we extract some core types/features from `foundry-evm` and move it to a new crate (foundry-evm-core) perhaps.~~
Or better we flip it and extract all things ethereum only from anvil-core to a generic ethereum crate.

refactor(anvil): depend on revm directly

---

cli/src/cmd/forge/geiger/find.rs
fmt/src/helpers.rs

Closes #3180
Calculate line and column correctly.
Only `start` offset is required:
count all line breaks until `offset > start`

fix: correct line col calc

---

anvil/src/eth/backend/mem/storage.rs

To prevent unreasonable large number of historic states in memory this
* decreases the number of cached states from 1_000 to 250, meaning
* once we Hit 250 states, this will gradually decrease the limit one-by-one until we Hit the minimum of 10 history states. This prevents the memory from increasing uncontrollably over time. This guarantees, that the last 10 states are always in memory, older states are written to disk until requested.

fix(anvil): gradually decrease state cache limit

---

evm/src/trace/decoder.rs
evm/src/trace/node.rs
evm/src/trace/utils.rs

Closes #3333
Redact input for cheatcodes that accept a private key:
```console
Traces:
[27091] CounterScript::run() 
├─ [0] VM::startBroadcast(<pk>) 
│   └─ ← ()
└─ ← ()
```

fix: redact private key in broadcast functions and env values

---

evm/src/trace/decoder.rs
forge/tests/it/config.rs
forge/tests/it/repros.rs
testdata/repros/Issue3347.sol

Closes #3347
This is a known bug in ethabi, https://github.com/rust-ethereum/ethabi/issues/206. the decoding impl is a bit cryptic...
Instead, this is fixed by temporarily patching empty event args:
```
forge test -vvvvv                                                                                                        
[⠆] Compiling...
Running 1 test for test/Counter.t.sol:LogTest
[PASS] test() (gas: 1497)
Traces:
[1497] LogTest::test() 
├─ emit log2(: 1, : 2)
└─ ← ()
```

fix: patch empty event args

---

cli/src/cmd/forge/coverage.rs

When compiling contracts for coverage reporting, the optimizer is set to disabled. However, the yul IR pipeline is not. It isn't intended to be run without the optimizer, and doing so can frequently cause stack too deep errors in many codebases.
Set via_ir in the solc config settings to false before the project is built

Disable Yul compilation pipeline along with optimizer in coverage command

---

cli/src/cmd/forge/script/mod.rs
config/src/lib.rs

Closes #3224
consider
```toml
[rpc_endpoints]
mumbai="${MUMBAI_NODE_URL}"
[etherscan]
mumbai={key="${POLYGON_API_KEY}"}
```
so the alias should be an OR: `alias = config.etherscan || config.eth_rpc_url` and only 1 is required
Resolve correctly when either config.etherscan || config.eth_rpc_url is set

fix: use rpc url as alias when resolving etherscan

---

common/src/compile.rs

Closes #3375
previously, unlinked contracts returned size of `0` and were hidden in the output.
also determine size of unlinked contracts

fix: determine size of unlinked contracts

---

anvil/src/eth/backend/mem/cache.rs
anvil/src/eth/backend/mem/storage.rs

flushing historic cached state to file in sync could be a performance bottleneck once the state reached a certain size.
flush historic state to file in separate task.
there's the possibility that a request for historic data that is currently in the process of being flushed returns nothing. But since only old state is flushed to disk, I think we can neglect that here and rather focus on block mining perf.

perf(anvil): flush historic state in new task

---

cli/test-utils/src/util.rs
common/src/term.rs

Terminal output uses title case almost everywhere, except when installing solc:
```logs
[⠆] installing solc version "0.8.17"
[⠒] Successfully installed solc 0.8.17
[⠑] Compiling 10 files with 0.8.17
[⠃] Solc 0.8.17 finished in 1.05s
```
Adjust case for `installing solc version` message.

Use consistent casing

---

Cargo.lock
anvil/tests/it/revert.rs
evm/Cargo.toml
evm/src/decode.rs

Closes https://github.com/foundry-rs/foundry/issues/3399
Brute forces custom error decoding.
```solidity
error MyError(address);
```
will be decoded and printed to console as:
` Error: reverted with 'Custom Error 73ea2a7f:(0x0000000000000000000000000000000000000001)'`
Note: the decoding impl could be further optimized by manually counting words but this should be sufficient

feat: decode custom errors

---

foundryup/install

This adds support for ash (the Almquist shell, as in, on Alpine linux/busybox) in the installer. This allows you to use foundry in a busybox without installing another shell.
I add it as a shell option in the installer.
I tested this with this Dockerfile, and everything went fine :) have to do some futzing later on with paths for the forge binary, but it installs and runs.
```
FROM alpine
RUN apk add --no-cache bash curl jq git
COPY ./integration-test/install.sh /install.sh
RUN chmod +x /install.sh
RUN /install.sh
ENV PATH="/root/.foundry/bin:${PATH}"
RUN foundryup
```

adding ash support to foundryup install.sh for easier install/use on busybox/alpine

---

cli/src/cmd/forge/install.rs
cli/tests/it/cmd.rs

handles repeated forge install calls for the same dependency gracefully.
repeatedly installing the same repo doesn't have any side-effects but git returns an error if nothing has changed on git commit.
ref https://github.com/foundry-rs/foundry/issues/3321

fix: don't fail on repeated installs

---

cli/tests/it/config.rs
common/src/evm.rs
config/src/lib.rs
evm/src/executor/opts.rs

closes #3423
support --code-size-limit to configure max codesize in the env

feat: add --code-size-limit argument and setting

---

evm/src/executor/backend/mod.rs

Ref #3424
when we encounter a revert in forking mode we check if the account of the call recipient actually exists. this is useful in multi forking mode, but only really in multiforking mode.
This will only try to diagnose a revert if there are more than 1 forks created.

fix: diagnose forking reverts only in multifork mode

---

evm/src/fuzz/strategies/invariants.rs

Closes https://github.com/foundry-rs/foundry/issues/3400
I'm unsure why we originally decided to choose random addresses 20% of the time even when `targetSenders()` is used. I agree with @lucas-manuel that isn't ideal. Curious to hear from @joshieDo why we currently do this, but if there's value in it we can always add this back with a new config flag to determine how `targetSenders()` behaves

feat: no random target senders if `targetSenders()` is used

---

cli/src/cast.rs
cli/src/utils.rs

Closes #3433
use new alias helpers when resolving rpc URL in cast

feat(cast): resolve rpc aliases if foundry.toml is present

---

cli/src/cmd/forge/inspect.rs

somewhat related to #3142
print event signatures and corresponding hashes
usage:
`forge inspect <contract name> ev`

feat(forge): inspect event signatures

---

cli/tests/it/cmd.rs

Ref https://github.com/foundry-rs/foundry/issues/3440
@mds1 do you have an example where this currently fails? Because this test passes

test: add test for absolute imports from test and script

---

anvil/src/anvil.rs
cli/src/opts/cast.rs
cli/src/opts/forge.rs

https://github.com/clap-rs/clap/issues/2808
Since clap 4.0 `DeriveDisplayOrder` became the default, so our subcommands ordering for `cast`, `forge` and `anvil` switched from lexicographic to WYSIWYG.
Return lexicographic ordering back.
---
Before:
```console
➜  ~ forge --help
Build, test, fuzz, debug and deploy Solidity contracts.
Usage: forge <COMMAND>
Commands:
test               Run the project's tests. [aliases: t]
script             Run a smart contract as a script, building transactions that can be sent onchain.
coverage           Generate coverage reports.
bind               Generate Rust bindings for smart contracts.
build              Build the project's smart contracts. [aliases: b]
debug              Debugs a single smart contract as a script. [aliases: d]
update …
```

fix(cli): --help subcommands display order

---

Cargo.toml
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/invariant/mod.rs
forge/src/runner.rs

https://github.com/foundry-rs/foundry/issues/2962
1. When invariant succeeds, we collect logs and traces from the last successful run
2. When invariant breaks, we replay the call to collect logs and traces from the last run that broke the invariant
<details>
<summary>Code</summary>
```solidity
// SPDX-License-Identifier: UNLICENSED
import "forge-std/Test.sol";
contract NonceCounter {
int256 public nonce = 1;
function increment() public {
nonce++;
}
}
contract NonceCounterTest is Test {
NonceCounter nonceCounter;
int256 lastNonce;
nonceCounter = new NonceCounter();
}
function invariant_NonceGoUp() external {
console2.log('lastNonce: ', vm.toString(lastNonce));
int256 currentNonce = nonceCounter.nonce();
console2.log('currentNonce: ', …
```

feat(invariant): collect logs & traces for last successful runs

---

fmt/src/formatter.rs
fmt/testdata/PragmaDirective/fmt.sol
fmt/testdata/PragmaDirective/original.sol

close #3472
Currently, the formatter forces a newline between two pragma directives. The expected behavior is that the newlines would be preserved (2 at most) between multiple consecutive pragma directives

fix(forge): fmt pragma directive newlines

---

cli/src/cmd/forge/script/build.rs

close #3454 
Currently, on no input files provided forge script exits with code `0` upon calling `compile::compile_target`. Exit with non-zero code and an error message

fix(forge): script non-zero exit code on no inputs

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/mem/mod.rs

ref https://github.com/foundry-rs/foundry/issues/3478
add `--prune-history` to opt-out of full state history and only keep the current state

feat(anvil): add --prune-history flag

---

cli/tests/it/config.rs
config/src/lib.rs

Solidity 0.8.18 (unreleased) will introduce an option to completely remove the CBOR metadata from the bytecode. This PR adds that option here.
See `appendCBOR` in https://docs.soliditylang.org/en/develop/using-the-compiler.html#input-description
Depends on https://github.com/gakonst/ethers-rs/pull/1782

Add solc option to remove metadata hash from the bytecode.

---

cli/src/cmd/forge/verify/etherscan.rs

Currently, the verification is broken on master, because JSON standard input is not sanitized during construction
Temp fix: convert to compiler input, sanitize & convert back to JSON standard input

fix(verify): json input sanitization 

---

cast/src/base.rs
cli/src/cast.rs
cli/src/opts/cast.rs
cli/tests/it/cast.rs

closes: #3506
re-add `ToHex`, `ToDec` commands which just use `ToBase` with always the same `base_out`
maybe there's a better way to do this by using using clap, without creating new commands?

fix(cast): --to-base aliases

---

Cargo.lock
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/src/hardfork.rs

Folks trying to upgrade anvil and ethers are running into a problem with the BlockNumber enum (in the latest version of ethers).
This PR fixes that problem at brings anvil up to parity with the latest version of ethers-rs.
After the merge, there is a notion of "safe" and "finalized" blocks (in addition to "latest", "pending", etc). We need to support all of the block number functionality for these new tags, which are described in more detail here: 
**https://www.alchemy.com/overviews/ethereum-commitment-levels**

bump ethers and fix BlockNumber issue

---

evm/src/fuzz/mod.rs
forge/src/result.rs
forge/src/runner.rs
forge/tests/it/config.rs
forge/tests/it/fuzz.rs

> It would be nice if it could also include the decoded/interpreted logs, as commands consuming this json are not likely to have the ability to decode these logs - Willyham
Closes #3002 
I added a simple `decoded_logs` field on the `TestResult` and `FuzzTestResult` structs.

✨ Add a decoded_logs field to TestResult structs

---

foundryup/foundryup

In `foundryup` we're not properly checking for whether the user has specified a branch or version when using a local repo. Instead of reading `FOUNDRYUP_BRANCH` and `FOUNDRYUP_VERSION` which is where we store the passed arguments, we instead read `FOUNDRY_BRANCH` and `FOUNDRY_VERSION`.
Instead of flagging up this error we instead silently install foundry using the current state of the local repo.
I've replaced the faulty `FOUNDRY` prefix with `FOUNDRYUP`

fix: correct variable names in branch/version check

---

Dockerfile

Resolves docker build for multiarch `arm64` and `amd64` 
Related to https://github.com/foundry-rs/foundry/issues/3545 and https://github.com/foundry-rs/foundry/issues/3513
Configure `CFLAGS`  dependent on image arch.
Note:
`ARG TARGETARCH` is provided by docker itself on build stage.

Fixes multiarch docker build

---

cli/src/cast.rs

Related to https://github.com/foundry-rs/foundry/issues/3544
Outputs `tx_hash` rather than unstructured debug info from `PendingTransaction` on `cast publish --async`
`cast send --async` output is raw `tx_hash` but for `cast publish --async` output is raw Debug `PendingTransaction`.
Return `tx_hash` only.
Output example:
```
cast publish --async --rpc-url http://geth.local:8545  $TX
0xa29a3a8527e2da1a9eb5241fbbae245c0b069291f15d7f59e7d4af3267c4a098
```

Updated output for cast publish --async from debug data to tx_hash

---

cli/src/cmd/forge/verify/etherscan.rs

When running `check-verify` I kept getting `Contract successfully verified`, but the contract did not show up as verified on the block explorer. We dug into this deeper and when using a curl command to get more info, it turns out the response was `{"message":"OK","result":"Fail - Unable to verify","status":"1"}` . At the moment, if the status is 1 it says that the contract is successfully verified when it is not. Blockscout seems to always return 1 as the status, so we shouldn't rely on this.
Given that other errors like this could come up in the future, it seems best to display the whole message  / result that is returned, in order to give developers as much information as possible. I added a line to print this out. In addition, it now returns an error for this specific error I ran into.

More accurate error message in check-verify

---

cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs

If the chain argument is committed, then mainnet is the default, which may not be the actual network the contract is deployed on.
Add chain info to output so user can see what chain is targeted.

chore: improve verify output with chain info

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/verify.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs

Add new `--show-standard-json-input` to print the standard-json forge would send to etherscan verifyContract endpoint.
This can be useful when changes have to applied manually to the input and verify via browser.

feat(verify): add --show-standard-json-input

---

config/src/lib.rs

fixes an issue where the default read permission would be set to an absolute path
```
[[profile.default.fs_permissions]]
access = 'read'
path = '/Users/Matthias/git/rust/foundry-integration-tests/testdata/foundry-playground/out'
```

fix: use relative path for fs permissions

---

anvil/src/config.rs
anvil/src/eth/backend/mem/cache.rs

Ref #3623
Add dedicated anvil folder in `~/.foundry/anvil` and store state cache in `~/.foundry/anvil/tmp`, also prefix the tmp dir with current timestamp.

fix(anvil): store state cache in anvil specific location

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/verify.rs
cli/src/cmd/retry.rs

add support for retry args (--retries, --delay) used by `forge verify-contract` to `forge create` as well

feat(create): add retry args to create

---

evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/Cheats.sol
testdata/cheats/RecordLogs.t.sol

This change aims to fulfill [#2921](https://github.com/foundry-rs/foundry/issues/2921) in support of the ```getRecordedLogs``` cheatcode.  I'm new to the foundry codebase (& rust 🥂) so felt like this was a fitting task to get my feet wet in the dev environment
Add additional ```Log``` struct which contains ```emitter``` field as outlined by @onbjerg.  Update unit tests to assert against proper emitter.
```cargo build --bin forge``` to rebuild forge executable
modify ```./testdata/foundry.toml```: ```test = 'cheats/'```
```./target/debug/forge test -c ./testdata/cheats --config-path ./testdata/foundry.toml --match-contract RecordLogsTest```
```
Running 7 tests for cheats/RecordLogs.t.sol:RecordLogsTest
[PASS] testEmitRecordEmit() (gas: 53465)
[PASS] testRecordOffGetsNothing() (gas: 46202) …
```

feat(forge): add emitter addr to log (#2921)

---

evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Json.t.sol

When I changed the JSON path library to one that supports "replace", I inadvertently broke existing functionality for parseJson, as the new library would not order the values of the objects by alphabetical order of the keys. 
Added a small intermediary step to force the order and forge-std tests again pass. 
**EDIT:** 
I also changed how `writeJson` works to support writing either a full Json or a single value. Now writeJson will get as input the stringified JSON (that we got from `serialize()`) instead of the key. From a UX perspective is also better cause it mimics how writeFile works.

Chore: Quality of Life improvements for writeJson

---

cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/cast/wallet/vanity.rs

close #3635
add `0x` prefix to make `cast wallet new` output consistent with `cast wallet vanity`

chore(cast): add 0x prefix to `cast wallet new` output

---

cli/src/cmd/forge/doc.rs
doc/src/builder.rs

A config option for `forge doc` that let's you specify an output path for the doc generation. Continuation work for #2701

feat(doc): add out path option in config

---

cli/src/cmd/forge/coverage.rs
forge/src/coverage.rs

Closes https://github.com/foundry-rs/foundry/issues/3644
Now you can do get multiple output formats with a single `forge coverage` run, such as:
```
$ forge coverage --report summary --report lcov
[⠒] Compiling...
[⠆] Compiling 18 files with 0.8.16
[⠔] Solc 0.8.16 finished in 2.17s
Analysing contracts...
Running tests...
+---------------------+---------------+---------------+---------------+---------------+
| File                | % Lines       | % Statements  | % Branches    | % Funcs       |
+=====================================================================================+
| script/Deploy.s.sol | 0.00% (0/2)   | 0.00% (0/2)   | 100.00% (0/0) | 0.00% (0/1)   |
|---------------------+---------------+---------------+---------------+---------------|
| …
```

feat: allow multiple coverage output formats

---

cli/src/opts/wallet/mod.rs
cli/src/opts/wallet/multi_wallet.rs
cli/tests/fixtures/keystore/password

Covers requests from
https://github.com/foundry-rs/foundry/issues/3555
https://github.com/foundry-rs/foundry/issues/2794
Leaves `--password` option as is, without modifications.
Adds new `--password-file` option to cast wallet with alias to `ETH_PASSWORD` env variable.
If no `--password` is set, tries to load keystore password from `--password-file` or `ETH_PASSWORD`
**NOTE** `--password-file` option is ignored for [multi wallet](https://github.com/foundry-rs/foundry/blob/70f4fb55fa87e0e980f7f9fcccc5429bb1a48dbe/cli/src/opts/wallet/multi_wallet.rs)

Added --password-file option to cast wallet + ETH_PASSWORD env var support

---

Cargo.lock
anvil/src/eth/api.rs

ethers-rs had the [issue](https://github.com/gakonst/ethers-rs/issues/1843) that it expected the wrong transaction format in the JSON RPC method `txpool_content`. This was fixed in https://github.com/gakonst/ethers-rs/pull/1844. Anvil has the same issue from the other side: Its response to `txpool_content` uses the wrong format (or at least a format different from geth).
Update to the latest version of ethers and use the new transaction format.
There's still some tests that are failing, but I'm unsure if it's because of this PR or a preexisting issue.

Update ethers and use new transaction format in txpool_content

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3653.t.sol

Closes #3653
previously we only set the test contract address when the `setUp` function was called, via the `to` field of the tx.
With this fork inits inside the constructor are also supported, by deriving the address of the test contract from the CREATE transaction.

fix(forge): set test contract address during constructor call

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/fork.rs
testdata/cheats/Cheats.sol

This helps avoid stack to deep errors in older solidity versions when returning a nested array of strings with `vm.rpcUrl`
Ref https://github.com/foundry-rs/forge-std/pull/217, https://github.com/foundry-rs/forge-std/issues/215
Open to alternative function names

feat: add rpcUrlStructs cheat

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3674.t.sol

closes #3674 
Forks that were created after the first one was selected (on a `!launched_with_fork` scenario), were not  properly handling `msg.sender` account info. Reason being that `fork_init_state` was ending up with `state.depth = 1` .
Make sure that that all created forks have a `state.depth = 0` before they're first selected.

fix(evm): Make sure new forks have  `state.depth = 0` before they're first selected

---

evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/stack.rs
forge/tests/it/repros.rs
testdata/repros/Issue3596.t.sol

Closes #3596
This fixes an issue with `deal` cheat code on revert.
`Deal` sets the balance of an address. revm records balance transfers which are then rolled back on revert via unchecked math (reverse transfer).
If, after a transfer, a transaction occurs that sets the recipient's balance to a value lower than that previously transferred, this will result in an underflow when the transfer is reversed during revm's cleanup.
record all `deal`s and roll them back manually on revert before revm applies the actual revert

fix: roll back deals on revert

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3685.t.sol

Closes #3685
This delays the on_revert cleanup until a potential expectRevert was handled.

fix(cheats): delay on revert cleanup until expected revert handled

---

Cargo.lock
anvil/core/Cargo.toml
evm/Cargo.toml
ui/Cargo.toml

bump revm to v2.2.0.
changelog: https://github.com/bluealloy/revm/blob/main/crates/revm/CHANGELOG.md

chore: Bump revm to v2.2.0

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/verify/etherscan.rs
cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/forge/verify/provider.rs
cli/src/cmd/forge/verify/sourcify.rs

Ref #3691
Adds a `preflight_check` routine for `create + verify` combo.
This should prevent contract deployments when the subsequent verify will fail due to config issues.
This adds a new `VerificationProvider::preflight_check` function that prepares the verify request but does not send it, the same way the actual `VerificationProvider::verify` would do.
@rkrasiuk mind giving this a spin?

feat(verify): add preflight check

---

cli/src/cmd/forge/inspect.rs
common/src/compile.rs
forge/src/coverage.rs
forge/src/gas_report.rs

When using foundry features(inspect for storage layout, but potentially gas report etc), it often happens that in the end i want to put these results into a document. What i noticed ppl tend to do is: making screenshots of the terminal and embedding it into markdown. This imo is not so good as it makes this stuff hard to maintain and a bit cumbersome. Therefore i'd suggest to allow generating markdown compatible tables.
The `comfy_table` crate used inside foundry provides a markdown preset that can be used.
I think is worth discussing:
Does this need a flag or should it just be the default?
I don't really see the value in "non markdown" tables (as markdown is perfectly readable in console as well).
If there's no opposition, would delete the flag and just use this preset in `all` tables. …

[RFC] feat: markdown compatible tables

---

cli/src/cmd/forge/install.rs
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/executor.rs
cli/test-utils/src/util.rs
cli/tests/it/cmd.rs

Closes #401
cc @mds1 
after submodule clone, scans all semver tags and install latest, if not tag was provided as argument.
eg:
```
forge install "openzeppelin/openzeppelin-contracts"
cat .gitmodules
```
```
[submodule "lib/forge-std"]
path = lib/forge-std
url = https://github.com/foundry-rs/forge-std
[submodule "lib/openzeppelin-contracts"]
path = lib/openzeppelin-contracts
url = https://github.com/openzeppelin/openzeppelin-contracts
branch = v4.8.0
```

feat(forge): install latest semver tag if it exists

---

evm/src/executor/fork/multi.rs
forge/tests/it/fork.rs
testdata/fork/ForkSame_1.t.sol
testdata/fork/ForkSame_2.t.sol

Forks are identified via `provider+block`. 
This fixes a logic error where an additional task to create a fork while another task was active would overwrite the matching forkid's backend on completion.
Before starting a new task to create a fork, check if there's already an active for the same forkId, if so, simply push the `Sender` and don't start a new task.

fix: reuse in progress fork task

---

common/src/evm.rs

Now that we can fork via cheatcodes, --no-storage-caching can be valid even without --forkurl.

fix: rm --fork-url requirement for --no-storage-caching

---

.gitmodules
testdata/foundry.toml

forge-std submodule was accidentally merged here https://github.com/foundry-rs/foundry/pull/2854
The reason why we don't use forge-std as test standard is, because we'd otherwise have a circular dependency `forge <-> forge-std`

chore: rm forge-std submodule

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Cheats.sol
testdata/cheats/File.t.sol
testdata/fixtures/File/symlink

Resolves half of #3695 - Per @mattsse request, let's get some file/dir metadata going.
Created `cheats.fsMetadata` which returns a struct roughly mirroring `std::fs::Metadata`.
A couple areas that may deserve review attention:
- is it appropriate to have the test in File.t.sol?
- is it appropriate to use dir+file from the File fixture in the test?
- for modified, created, accessed timestamps, is it appropriate to return 0 when not supported by platform?
- currently i called filesize `len` like std::fs::Metadata does, but I'm wondering if `size` is better!
- And probably tons of other stuff I'm unaware of...
I'll be really happy for your feedback, this is my first foundry PR!

feat(forge): add fsMetadata cheat

---

evm/src/executor/inspector/cheatcodes/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3753.t.sol

Closes #3753
expectRevert only checks the next call:
> If the next call does not revert with the expected message msg, then expectRevert will.
The exit condition looks like 
```
if evm.depth() <= expected_revert.depth {
// check if reverted
}
```
The next call would be `expected_revert.depth + 1`, so after the call returns we check if it reverted. This is not the case in #3753
so in this case the expectRevert should be set directly before the require
@prestwich 
will add this example to the book.

test: add expectRevert test

---

evm/src/executor/backend/mod.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue3708.sol

Closes #3708
CREATE2 deployer address is persistent by default, however when merging the underlying dbs on select, we did `unwrap_or_default` so if the CREATE2 deployer hasn't been loaded yet an empty account was created.
Skip non-existing, persistent accounts

fix: only merge account if it was loaded

---

cli/src/cmd/forge/script/receipts.rs

Error message is incorrect and not helpful.
Made it correct and helpful

fix: correct error message in script receipt tracking

---

anvil/core/src/eth/mod.rs
anvil/core/src/types.rs
anvil/src/eth/api.rs
anvil/src/eth/pool/transactions.rs
anvil/tests/it/anvil_api.rs

Feature inspired in #2424, which asks for an `anvil_nodeInfo` rpc method with helpful info about the current anvil node.
adds an `anvil_nodeInfo` RPC method to fetch info about the queried anvil node. Opening a draft to see what's the best way to proceed and finish shaping the PR as it's my first non-docs contrib :).
A few doubts/qs:
- What other info should we include?
- How should we order the fields? I went with somewhat mimicking the configuration params, but happy to change.
- Happy to discuss how the `json` is being constructed/return type. Right now i'm just building the json through the `json!` macro as I didn't wanna introduce an intermediate struct for this, but also happy to change it.
Sample response with current draft:
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": { …
```

feat(anvil): `anvil_nodeInfo` RPC call

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/api.rs
anvil/tests/it/anvil_api.rs

Closes #3759
prevent collision by appending the impersonated sender to the transaction so impersonated tx hashes are unique.

fix(anvil): make impersonated tx hashes sender unique

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/receipts.rs

#3780 
Modify the logic that handles pending txns on resume to correctly remove dropped transactions so that they can be rebroadcast

refactor: improve behavior of script receipt checking

---

docs/dev/scripting.md

Adds some diagrams on the highlevel flow of `forge script`
Interesting that the PR doesn't actually render the diagram, so you have to go ahead and click on `View File`.

docs: add flow diagrams about `forge script`

---

cli/src/cmd/forge/bind.rs

exclude `forge-std` contracts by default in `forge bind`

fix(bind): exclude forge-std contracts by default

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/api.rs
anvil/tests/it/anvil_api.rs

Reverts #3775
Closes #3803
This change was bad since this causes a lot of friction:
* with this phase `keccak(tx)` != tx.hash the we use to identify the tx
Instead https://github.com/foundry-rs/foundry/issues/3759 should be fixed via https://github.com/foundry-rs/foundry/issues/3808 by setting the from field
revert the previous change until we found a better way, since this change did more harm than good apparently.

Revert "fix(anvil): make impersonated tx hashes sender unique (#3775)"

---

config/README.md
config/src/lib.rs

Add a "max" alias for `gas_limit`

feat(config): allow gas_limit = \"max\"

---

.github/workflows/release.yml

github is _gradually_ migrating `ubuntu-latest` to `ubuntu-22.04`: https://github.com/actions/runner-images/issues/6399
which caused some issues if the forge release CI is run on 22.04. which breaks on 20.04 https://github.com/foundry-rs/foundry/issues/3827
pin release runner 20.04 until stabilized.

ci: pin ubunut-20.04

---

cli/src/cmd/forge/script/runner.rs
cli/test-utils/src/script.rs
cli/tests/it/script.rs
docs/dev/scripting.md
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/mod.rs
testdata/cheats/Broadcast.t.sol

* closes #3799 - correcting the nonce of the `Config::DEFAULT_SENDER` after `setUp`, was causing a conflict later on,
when creating a contract with the same nonce as the script contract.
* clean up nonce correction + docs (loving mermaid+github integration tbh)
Missing:
* test

fix: empty `setUp` with default sender on `forge script`

---

cli/src/cmd/forge/create.rs
cli/src/cmd/forge/script/broadcast.rs

For future cases.
ref [#3846](https://github.com/foundry-rs/foundry/issues/3846)

chore(forge): add hint to error message if chain does not support EIP1559

---

evm/src/executor/mod.rs

getting an immutable reference to env should not require a mutable reference to self.
change mutability requirement on self.

Fix: env() need not require mutable reference to self.

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/providers.rs

Ref https://github.com/foundry-rs/foundry/issues/3838
Replace bad panic with proper error.
The panic likely happened due to an erroneous `estimate_eip1559_fees` call which was converted to an `Option`
This keeps the `Result`s of the gas price requests so we can properly report failed rpc calls.

chore: replace bad panic with error

---

Cargo.lock
anvil/Cargo.toml

Anvil and ethers-rs 1.0.2 use two different versions of `primitive-types` crate. This fixes it.
We should also remove all of the git dependencies on the ethers-rs repo and just shift to the crates.io version. This will break anyone still pointing to the repo so maybe we want to schedule that or something. It's not in this PR.

bump ethereum-forkid to be compatible with ethers 1.0.2

---

evm/src/executor/backend/mod.rs

closes #3874 
Adds the default sender to the persistent accounts.
But, to be honest, I'm not sure if this is the right approach. If there are tests that assume that the default sender is reset after changing forks, this would break it. But I'm not sure why would they use forks + default sender anyway.

fix(forge): add default caller to persistent accounts

---

anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/transaction.rs

During eth_sendTransaction anvil is doing evm_mine operation with out writing it to storage in order to calculate nonce
This is look likes very expensive (also see this during profiling), especially when sending many transactions
Simplify nonce calculation, but looking for max nonce value

Optimize nonce calculations

---

anvil/src/cmd.rs
anvil/src/config.rs
evm/src/executor/fork/cache.rs

Signed-off-by: xphoniex <xphoniex@users.noreply.github.com>
https://github.com/foundry-rs/foundry/issues/3837:  idea is being able to run `anvil` using a local cache file, without having to contact remote endpoint as long as the required state is in the local cache.
When starting `anvil` from a fork, it first retrieves over rpc the `chain_id` of remote, and then creates the `block` and compares that with the one from local cache file, if they are the same, it'll populate in-memory db with local cache. 
Since we want to avoid unnecessary contact with remote, we'll have to pass `--fork-chain-id` so that we can know which local cache file to read, and since we don't know the state of `block`, we can either skip the check (as we're comparing `default` block vs. the one in the cache file) or …

feat(anvil): Add `--fork-chain-id` to enable offline-start mode

---

cli/src/cmd/forge/build/mod.rs

Running `forge build --help` outputs this:
```text
--skip <SKIP>...
Skip building whose names contain FILTER. `test` and `script` are aliases for `.t.sol` and `.s.sol`. (this flag can be used multiple
times)
```
I changed the help for the `skip` build argument to say "SKIP" instead of "FILTER".

chore: fix keyword used in --skip help

---

chisel/src/cmd.rs
chisel/src/dispatcher.rs

Adds a `quit` command to `chisel`
Have received a few messages asking how to quit chisel- adds a simple `quit` command for those that are unfamiliar with `ctrl+c` x2 or `ctrl+a+d`.

feat(chisel): `quit` command

---

cli/src/cmd/forge/coverage.rs

I was struggling to stabilize the codehash of one of my contracts between unit tests & coverage. I was aware that `forge coverage` would disable the optimizer but found it tricky to determine the exact settings. It appeared that  the `optimizer_runs` parameter affected the codehash (despite the optimizer being disabled, which was bizarre).
In the end, I thought it best to be more explicit about disabling all optimizer related fields.
This is a pretty simple change and may not be appropriate for merging. That said, my CI currently builds forge in 28 minutes which is making my eyes water, so keen to have this problem resolved in `master` one way or another.

fix: make coverage optimizer settings more consistent

---

anvil/src/eth/api.rs
anvil/tests/it/anvil.rs

See #3913 + reaches [parity](https://github.com/NomicFoundation/hardhat/blob/f081b1cc5fd7bfe2bd20abfa18a5e1d6838067ad/packages/hardhat-core/src/internal/hardhat-network/provider/MiningTimer.ts#L43-L46) with Hardhat.
Set the mining mode to `MiningMode::None` when the interval is zero.

fix(anvil): disable interval mining when set to zero

---

cli/src/cmd/forge/script/broadcast.rs

closes [#3897](https://github.com/foundry-rs/foundry/issues/3897)
>There's a stage where we estimate the gas usage to show the user (even without the --broadcast). For arbitrum and other similar chains, we rely on the external RPC to give us the gas usage estimation (and disregard the locally calculated one). However, in situations like this (tx2 depends on tx1), we obviously hit these kind of errors.
>It doesn't happen on eth_mainnet and eth_goerli, because we don't disregard the locally calculated one.
Just ignore the error. (reminder that this is only an issue for chains which rely on external RPC gas estimation).
```Rust
// We are trying to show the user an estimation of the total gas usage.
//
// However, some transactions might depend on previous ones. For
// example, tx1 might …
```

fix(forge): ignore external gas estimation error when estimating total gas

---

evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/GasMetering.t.sol

fix #3858
fix https://github.com/foundry-rs/forge-std/issues/257
Due to this: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm/src/evm_impl.rs#L190
when making external calls, there is a returned amount of gas that would cause an underflow when trying to return. This actually popped its head up as a `OutOfGas` overhead in some situations. So in the case that gas metering is off, and we are returning from an execution frame, we just set the gas to a `new` with 0 values for everything. This makes the above make no adjustments

fix(forge): fix external call gas metering cheats

---

cli/src/cmd/forge/script/runner.rs
cli/tests/fixtures/can_execute_script_and_skip_contracts.stdout
cli/tests/fixtures/can_execute_script_command.stdout
cli/tests/fixtures/can_execute_script_command_fqn.stdout
cli/tests/fixtures/can_execute_script_command_with_args.stdout
cli/tests/fixtures/can_execute_script_command_with_returned.stdout
cli/tests/fixtures/can_execute_script_command_with_sig.stdout

closes #3921 
To search for optimal gas usage, we do need to re-execute certain calls. But as far as I can see, these should only be the ones which we intend to broadcast. No need the re-execute the `Script::run()`.

fix(forge): do not search for optimal gas usage of `run()`

---

cli/tests/it/cast.rs
cli/tests/it/verify.rs

etherscan vars are set as secrets in CI
this skips the test that would otherwise fail, so testing locally, without the env vars is more convenient.

test: skip test if etherscan vars not set

---

evm/src/executor/abi/fmt.rs

Lots of byte indexing with UTF-8 strings which may break the formatted output
Use char_indices and clean up reverse logic

fix(evm): console_log_format

---

cli/tests/it/verify.rs

CI has been broken for a while since the goerli live test keeps failing with `Transaction dropped...`. However, I haven't been able to reproduce it locally even once. 
I feel like adding `--slow` might help out with the CI passing (adding around 5 block-time seconds to the job), while this is further investigated (#3969).

fix(ci): add `--slow` to goerli live test

---

Cargo.lock
evm/src/trace/mod.rs

Breaking change in ethers, GethTrace is using U256 instead of u64 as gas type.
https://github.com/gakonst/ethers-rs/commit/b27c7b0773d7ba329e0e1eebb37db652ac8fa601

[fix] GethTrace in ethers is using U256

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/fork.rs
testdata/cheats/Fork2.t.sol
testdata/fork/Transact.t.sol

Closes #3797 
- Add optional inspector to `commit_transaction`
- Add implementation for `RollFork3`/`vm.rollFork(uint256 forkId, bytes32 transaction)` (which was not implemented until now for some particular reason?)
- Add tests for `transact` and `rollFork` cooperating with cheatcodes
It is evident that the `Cheatcodes` inspector doesn't inspect the transaction that is executed in `transact` since not only does `vm.recordLogs` not work as expected but even other cheatcodes like `vm.expectCall` doesn't work as expected.
I added an optional inspector to inspect the new `EVM` instance that the `transact` is run on. However, since the `Cheatcodes` inspector needs the `Database` to also implement the `DatabaseExt` trait, I create a new `Backend` database with the fork's database and pass it …

fix(forge): Fix cheatcodes not cooperating with `vm.transact`

---

chisel/src/bin/chisel.rs
chisel/src/cmd.rs
chisel/src/dispatcher.rs
chisel/src/executor.rs
chisel/src/lib.rs

Improves error verbosity by showing traces when an expression inspection reverts.
(Also fixes a typo: `ChiselDisptacher` -> `ChiselDispatcher`)
@devtooligan pointed out that if an expression inspection reverts, chisel only showed a `No state present` error message, which didn't help explain why the inspection failed.
Always show traces when an expression inspection fails.

fix(chisel): Improve error verbosity when an expression inspection reverts

---

chisel/src/cmd.rs
chisel/src/dispatcher.rs

Adds a new `!rawstack` / `!rs` command to chisel that displays the raw value of a variable's stack allocation.
Feature requested by @transmissions11 
1. Clone the current session source.
2. Append the following code to the cloned source's `run()` function, where `to_inspect` is the argument supplied to `!rawstack`
```solidity
bytes32 __raw__;
assembly {
__raw__ := to_inspect
}
```
3. Inspect the `__raw__` variable.

feat(chisel): `rawstack` / `rs` command

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/traces.rs

trying to address this https://github.com/foundry-rs/foundry/issues/2782 issue. Related https://github.com/foundry-rs/foundry/issues/1737
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debug_tracecall geth like api. Return same data like debug_traceTransaction

(Feat Anvil): add geth like debug_traceCall api

---

cli/src/cmd/forge/init.rs

Currently, if you `forge init --template <TEMPLATE>` it's just an alias to `git clone` the template. This means your new forge project is initialized with the template's commit history and the template repo set as the remote.
OTOH, when you click the "Use this template" button in the github UI it creates a repo with a single commit from the person who forked it with the message "Initial commit". This behavior is preferable as you don't want the template's commits and authors in your repo history, nor do you want it a a remote.
This PR updates `forge init --template <TEMPLATE>` to behave similarly by deleting the git folder and initializing a new repo

fix: remove forge init template history

---

cli/src/cmd/forge/script/receipts.rs

We are getting a lot of reports with errors such `Transaction dropped...` , while the transaction has actually been confirmed.
Was able to reproduce it consistently with fuji (#3880). Also saw reports that it happens fairly frequently on avalanche mainnet.
Remove an early mempool check. That might be checking it too fast? I'm assuming that a similar thing happens on `goerli` #3969 (can't confirm, since I cannot reproduce it locally for `goerli`).
If it's really dropped, we should know on the return of the following `PendingTransaction.await` anyway. I'd rather wait more on a transaction dropped event, than the current state.
wdyt @prestwich 
Also, leaning towards adding a second `PendingTransaction` attempt, but I want to see if the `CI` performs better with just this fix.

fix(forge): remove early mempool check when broadcasting

---

macros/impl/src/utils.rs
macros/src/console_fmt.rs
macros/src/lib.rs

Derive macro was using `crate::` for when manifest dir ended with /macros so windows would not use this
```diff
- .ends_with("/macros")
+ .ends_with("macros")
```

fix(macros): windows tests

---

cast/src/errors.rs
cast/src/lib.rs
cast/src/tx.rs
cli/src/cmd/cast/call.rs

Closes #4016
only set args if `sig` argument provided.
```
cast call
0x
```
```
cast call 0x<address>
0x
```
should cast call without an address arg fail @prestwich ?

fix(cast): only set function args if signature provided

---

common/src/compile.rs

When running `forge build --sizes` in a project with contracts without ABI, it fails with:
```
Message:  called `Option::unwrap()` on a `None` value
Location: common/src/compile.rs:151
```
This PR fixes this

Fix `--sizes` for contracts without ABI

---

config/src/fmt.rs
fmt/src/formatter.rs
fmt/testdata/FunctionDefinition/override-spacing.fmt.sol
fmt/testdata/ModifierDefinition/override-spacing.fmt.sol
fmt/testdata/VariableDefinition/override-spacing.fmt.sol

closes #4025 
replace `variable_override_spacing` option with `override_spacing` that sets the spacing on `override` attributes for contract state variables, functions, and modifiers
cc @paulrberg

feat(fmt): override spacing

---

anvil/src/eth/backend/mem/fork_db.rs

Addresses: https://github.com/foundry-rs/foundry/issues/4026
Anvil currently does not have state dump / loading enabled when using a fork. 
Implement, code is modified from non fork methods.

feat(anvil): enable dumping state while forked

---

cli/src/cmd/cast/call.rs

Adds `cast call --data <hex>` that allows setting the `data` field directly without providing a sig or args.
cc @prestwich

feat(cast): add cast call --data argument

---

Cargo.lock
cast/Cargo.toml

The releases are currently [failing](https://github.com/foundry-rs/foundry/actions/runs/3851356109) due to default native tls usage in rusoto
Blocked by https://github.com/gakonst/ethers-rs/pull/2021

fix: disable native tls on rusoto

---

Cargo.lock
config/Cargo.toml
config/src/etherscan.rs

there are reports that etherscan responds with 403 if no user-agent is provided https://stackoverflow.com/questions/69312369/etherscan-api-request-403-forbidden-in-ropsten-network
This sets `foundry/<version>` as user-agent
cc @hexonaut

feat: add user agent to etherscan API client

---

cli/src/cmd/cast/call.rs
config/src/fmt.rs
fmt/testdata/FunctionDefinition/all.fmt.sol
fmt/testdata/FunctionDefinition/fmt.sol
fmt/testdata/FunctionDefinition/override-spacing.fmt.sol
fmt/testdata/FunctionDefinition/params-first.fmt.sol
fmt/testdata/ModifierDefinition/fmt.sol
fmt/testdata/ModifierDefinition/override-spacing.fmt.sol
fmt/testdata/VariableDefinition/fmt.sol
fmt/testdata/VariableDefinition/override-spacing.fmt.sol

[The Solidity documentation](https://docs.soliditylang.org/en/v0.8.17/contracts.html#function-overriding) uses no spacing between the `override` keyword and the overridden contract names:
```solidity
contract Inherited is Base1, Base2
{
// Derives from multiple bases defining foo(), so we must explicitly
// override it
function foo() public override(Base1, Base2) {}
}
```
Anecdotally, most Solidity code bases I've seen adhere to the same pattern where there is no spacing. This is perhaps the same reason why @benesjan opened issue #3522 in the first place.
Set the default value of `variable_override_spacing` to `false`.
Though, before this is merged in, we should fix #4025 first.

refactor(fmt): change default for `override_spacing` to `false`

---

chisel/README.md

Fixes a typo in the fork url example in Chisel's readme.

 docs: fix fork url example in Chisel

---

forge/src/multi_runner.rs

In order to use forge as a library, it's neccessary to expose the `sender` field in `MultiContractRunner`.
This pr simply makes the `sender` field public.
closes #4087

Support running forge as a rust lib

---

evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/GetCode.t.sol
testdata/fixtures/GetCode/HuffWorkingContract.json

While not directly supported by Foundry, a good deal of [Huff EVM smart contract language](https://github.com/huff-language/huff-rs) tooling is based on Foundry, such as the [`foundry-huff` repo](https://github.com/huff-language/foundry-huff).
Since Foundry cannot load Huff artifacts, [standard procedure is to run tests and scripts using the potentially-unsafe `ffi` cheatcode](https://github.com/huff-language/foundry-huff/blob/main/src/HuffConfig.sol#L10) to compile and then load smart contract bytecode.
Adding support for Huff artifacts to the `getCode` and `getDeployedCode` cheatcodes will make interacting with pre-compiled Huff smart contracts much easier and safer, as devs can compile Huff artifacts as part of a separate build step, and then use the `getCode` and `getDeployedCode` …

feat(forge): add support for getting bytecode from Huff artifacts

---

evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Json.t.sol

Serializing an empty array resulted in an incomplete JSON `"["`. e.g.
```solidity
address[] memory arr = new address[](0);
console.log(stdJson.serialize("", "qwer", arr));
// Logs {"qwer":"["}
```
Experienced the bug in:
- MacOS 12.6, Apple M1 chip
- forge 0.2.0 (e1eb912 2023-01-17T00:11:52.918569Z)
- Fix the array serializer functions `array_eval_to_str` and `array_str_to_str` to work when `array.len() == 0`
- Add a test in `testdata/cheats`

fix: serialize empty array to JSON

---

doc/src/parser/comment.rs

We encountered an error on invalid natspec tags when using `forge doc`, we didn't know custom natspec tags had to be preceded by the string `"custom:"` and it appears this is a recent addition to natspec, much to our confusion. Another user encountered the same problem
Add some extra context on the "unknown comment tag" error, guiding the user towards learning about `"custom:"`
Otherwise, if this PR is not merged, they might then stumble upon the issue below when they encounter the error. I'm not sure it is appropriate to provide context on error messages.
related to #4118

chore(forge): doc, context on custom tags

---

chisel/src/dispatcher.rs

Chisel currently returns an error when the input is completely empty, or panics with the following message when it is only whitespaces:
```text
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', chisel/src/executor.rs:215:55
```
Return `CommandSuccess(None)` when the input is only whitespace or empty, as it shouldn't error

fix(chisel): panic on empty input

---

cli/src/cmd/forge/verify/mod.rs
cli/src/cmd/forge/verify/provider.rs

Closes #4056
Adds a check on error if the provided verifier URL is either invalid or host only, indicating missing /api

chore: improve error message if given verifier url is host only

---

Cargo.lock
chisel/Cargo.toml
chisel/src/dispatcher.rs
chisel/src/executor.rs

Various errors or panics when using comments with or without traces:
- panic on inspect with a block comment, same as #4131
- "no traces" error when the first input is a line comment
If the input is a comment, add it to the run code so we avoid running with empty input

fix(chisel): comment errors

---

chisel/src/dispatcher.rs
chisel/src/solidity_helper.rs

highlighting is done on every input change so it's pretty important that they run fast
- instatiate vecs with capacity
- run Paint::is_enabled (atomic load) only once per highlight call (at the start) instead of twice per token (in fmt::Display of Paint), which also allows to early return with no changes to input
- saturating add on usize counters to normal addassign since your computer's memory will overflow before those will
- more efficient command comparisons
- use COMMAND_LEADER constant instead of hardcoding the same character many times

perf(chisel): solidity_helper

---

chisel/src/dispatcher.rs
chisel/src/solidity_helper.rs

any input that starts with a dot `.` followed by a number will make the solang Lexer panic:
```log
Welcome to Chisel! Type `!help` to show available commands.
➜ .thread 'main' panicked at 'attempted to index str up to maximum usize', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/solang-parser-0.2.1/src/lexer.rs:699:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
add a skip input method that will check for the panic condition

fix(chisel): invalid input panic

---

Cargo.lock
binder/Cargo.toml
binder/README.md

Upgrade git2 dep. Ref https://github.com/libgit2/libgit2/security/advisories/GHSA-8643-3wh5-rmjq

dep: upgrade git2

---

anvil/src/eth/backend/genesis.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs

Closes #4082
This fixes an edge case where data from the forked block was requests (eth_getBalance) after the first block was mined.
Since we don't have a historic state for the forked block there was essentially an off-by-one error.
There's another edge case that prevents us from just requesting everything from remote under these circumstances, because relevant account could be provided via genesis which overrides remote accounts.
This introduces a new Database type that checks all genesis account infos first and fetch from remote otherwise.

fix(anvil): fix forked block edge case

---

cli/src/opts/forge.rs

Adds the alias compile to forge build. Closes #3987 
I've done the initial work, but the issue never received "approval" from the maintainers so will close this PR or try to implement any further logic we want pending.

feat(forge): Add `compile` alias to `forge build`

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/tests/it/anvil_api.rs

Closes #4144
adds `evm_setTime` which allows setting the timestamp directly

feat(anvil): add evm_setTime

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs

Ref https://github.com/foundry-rs/foundry/issues/3759
This prepares a pending fix for #3759 by re-enabling this https://github.com/foundry-rs/foundry/pull/3809/files
This will always use the hash we already store for the transaction, this allows us to override modified hashes, for example for impersonated transactions

refactor: always use hash of MinedTransaction when building tx

---

evm/src/trace/mod.rs

Hopefully fixes https://github.com/foundry-rs/foundry/issues/3819 - `CREATE` and `CREATE2` traces are missing in `debug_traceTransaction` output.

fix(evm): include missing CREATE and CREATE2 geth traces

---

anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs

The previous max memory setting was pretty high resulting in bloated memory.
This decreases the max in memory limit and also adapts it if in interval mining, in which case it should be drastically decreased. so that only a couple blocks should be stored in mem, since unlikely older state will be requested at all.
this needs a followup to fix https://github.com/foundry-rs/foundry/issues/3623 which concerns disk space.

fix(anvil): stricter memory limits in interval mining mode

---

cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/test/filter.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/forge/watch.rs

Closes https://github.com/foundry-rs/foundry/issues/4008
adds a check in the `matches_path` that ensures that the path of the contract is not a child of a lib folder.
In other words: ignore all tests defined in lib folders.
Add a new filter type that wraps the existing filter but also has access to the project's paths.

fix(forge): ignore contracts defined in lib paths

---

anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/anvil_api.rs

There's a small bug in Anvil where it uses the latest block's base fee to calculate the effective gas price of a transaction when constructing a transaction receipt. 
This becomes an issue for EIP-1559 transactions, if the original block's base fee was different than the current block's base fee (e.g. due to an `anvil_setNextBlockBaseFeePerGas` call).  
Steps to reproduce:
1. Set the block base fee using `anvil_setNextBlockBaseFeePerGas`
2. Send an EIP-1559 transaction
3. Mine blocks
4. Fetch the transaction receipt of the EIP-1559 transaction, and notice that the effective gas price is miscalculated
We should use the original block's base fee when calculating the effective gas price for a transaction receipt
Added a test that uses the "Steps to reproduce" steps to verify that it's fixed. …

fix(anvil): Use the block's base fee when calculating effective gas price for a tx receipt

---

evm/Cargo.toml
evm/src/executor/fork/cache.rs
evm/src/executor/fork/init.rs
evm/src/executor/opts.rs

Ref https://github.com/foundry-rs/foundry/issues/2963
This disables the EIP3607 check by default.
This will allow senders with code, which has been an issue during fuzzing etc...

feat: disable eip3607 by default in forge test

---

anvil/src/config.rs
anvil/src/eth/backend/cheats.rs
anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/anvil_api.rs
evm/Cargo.toml
evm/src/executor/fork/cache.rs
evm/src/executor/fork/init.rs
evm/src/executor/opts.rs

Closes #3886
Blocked by https://github.com/foundry-rs/foundry/pull/4181
This disables the eip3607 check by default for anvil, allowing impersonation without manually removing the code

feat(anvil): disable eip3607 by default

---

anvil/src/eth/backend/mem/storage.rs

the previous PRs were too strict, and did ignore that we already gradually decrease the limit once we hit it.
this rolls back the defaults and is even less strict for interval mode because in interval mode we'll have a lot small blocks so the default limit should be increased
Closes https://github.com/foundry-rs/foundry/issues/4201

perf: tune storage limit defaults

---

anvil/Cargo.toml
anvil/core/Cargo.toml
anvil/core/src/eth/block.rs
anvil/core/src/eth/transaction/ethers_compat.rs
anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/cheats.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/src/eth/fees.rs
anvil/tests/it/pubsub.rs

Closes #4205
after #4185 we're making impersonated transactions unique by appending the sender to the preimage. however we didn't use that everywhere, for example when retrieving the `TypedTransaction` of a block we'd still use the regular hash using the impersonated signature.
This PR includes following changes
* add wrapper type `MaybeImpersonatedTransaction(TypedTransaction,Option<Address>)` which keeps track of the sender so we can use in when computing the hash if the transaction is impersonated
* change `block.transactions` to `Vec<MaybeImpersonatedTransaction>`
* feature gate impersonated-tx in `anvil-core`
@jxom could you please give this a try?

fix(anvil): track impersonated sender for transaction

---

cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr
cli/tests/it/cmd.rs

Fixes #4214
If the folder is already initialized to a git repo (and using `--force`), we're creating all the necessary files, except for workflow, .gitignore and the initial commit (`init_git_repo` doesn't run), so when git status is checked later during forge-std installation, it fails with that message because the initialized files didnt get committed
make `if !is_git` block only apply to `git init` itself
do not overwrite `.gitignore` and `.github/workflows`

fix(forge): init errors

---

anvil/src/config.rs
evm/src/executor/fork/init.rs
evm/src/utils.rs

Closes https://github.com/foundry-rs/foundry/issues/4086
adds check to enabled  EIP-4399 and replace difficulty with prevrandao after merge
configure difficulty with prevrandao if block difficulty is 0 or specific for mainnent

fix: replace difficulty with prevrandao after merge

---

cli/src/cmd/forge/script/verify.rs

fix #3872 
https://github.com/foundry-rs/foundry/pull/4220#issuecomment-1408133145

fix(forge): get etherscan api key from config when using anvil chain

---

Cargo.lock
testdata/fixtures/SolidityGeneration/WithStructs.json
testdata/fixtures/SolidityGeneration/WithStructs.sol
utils/Cargo.toml
utils/src/abi.rs

Closes #3957 
`cast interface` incorrectly looked up the name of rust types for code generation instead of solidity type identifier

fix(cast): interface arg name lookup

---

cli/src/cmd/forge/geiger/mod.rs

closes #3952 
Add `--ignore` option to `forge geiger`

feat(geiger): paths ignore option

---

cli/src/cmd/forge/script/sequence.rs

Fix for a typo introduced in yesterday's commit: https://github.com/foundry-rs/foundry/commit/5c2db0babf02e1f1016b1471de3b21593cb06b56#r98769848
We relied on the logging output format to grab the path of the transaction log.

fix(forge) fix a typo in logging output

---

anvil/src/config.rs

ref https://github.com/foundry-rs/foundry/issues/4232
ensure prevrandao is set, even if no mixHash in response

fix(anvil): ensure prevrandao is set in forking mode

---

cli/src/cast.rs
cli/src/cmd/forge/install.rs
cli/src/stdin.rs
cli/src/utils.rs
cli/tests/it/cmd.rs

Remove boilerplate to prompt, wait stdin answer and parse:
```rust
print!("<prompt>");
io::stdout().flush()?;
let mut s = String::new();
io::stdin().read_line(&mut s)?;
let n: usize = s.parse()?;
```
add `prompt!` macro to `stdin` module
refactor where necessary to use `prompt!` instead of above

refactor(cli): add cli prompts

---

chisel/src/dispatcher.rs

Small change to automatically encode addresses within the REPL input to their valid checksums.
@maurelian pointed this out to me the other day- when inputting an address that has an invalid checksum, chisel will not correct it and present the following solc error:
This can cause some friction, and doing this for the user automatically can be done easily.
Before processing the input, check for matches against the `0x[a-fA-F0-9]{40}` address regex. If any addresses are found, encode them to their EIP-55 checksum using `ethers::utils::to_checksum` and update the input.

feat(chisel): Automatically encode `address`es to their valid EIP-55 checksum.

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

I want an easy to to tell if a contract is a proxy and to be able to know the proxy admin and proxy impl using `cast`.
Implements two new commands for `cast` that fetch common EIP-1967 storage slots and print the values as address strings.
```
$ cast admin
$ cast implementation
```
This makes it very easy to determine if a contract is proxied.
Closes https://github.com/foundry-rs/foundry/issues/4168

cast: eip1967 commands

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs

Closes https://github.com/foundry-rs/foundry/issues/4252
add --prune-history <max-memory> argument
only keep the latest `max-memory` states in memory, no disk caching.

feat(anvil): support max mem history value for --prune-history

---

cli/src/cmd/forge/snapshot.rs

Closes https://github.com/foundry-rs/foundry/issues/4273
instead of summarizing gas diff, calculate overall gas change from the total gas change and total used.

fix: calculate overall gas diff correctly

---

anvil/src/eth/backend/mem/mod.rs
anvil/tests/it/fork.rs

There's a bug in Anvil where it returns a transaction receipt for transactions that occur after the forked block. 
Steps to reproduce:
1. Start a fork at a block number n in the past
2. Send an `eth_getTransactionReceipt` request for a mainnet transaction that occurred at n+1
3. Notice that the fork returns the transaction receipt for the mainnet transaction
We should check that the transaction's block number predates the fork before returning it
Added a test that uses the "Steps to reproduce" steps to verify that it's fixed. I also ran that test against the current master branch (without the fix), and verified that the test was failing

fix(anvil): Ensure the transaction's block number predates the fork before returning a receipt

---

evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Json.t.sol
testdata/fixtures/Json/test.json

fixes #4244 
The cheatcode incorrectly always assumed that the jsonPath would return a single value (an object, an array, etc.), but a jsonPath can return multiple values (as in the issue that this PR fixes). Now it will correctly encode the values as an Array if they are numerous.
Before, both notations ".key" and "key" would work because of the bug. The cheatcode adds internally `$.` in front of the passed key, so it's easier for users. That meant that `.key` would be translated to `$..key`, which returned **all values** in the JSON path, no matter their nested position. Due to the bug, it would take the first value of the array, so it worked virtually thew same.
Now that this is fixed, `.key` will not longer work properly, as it will be translated to `$..key` and `key` to `$.key`. …

Fix: Properly encode json path that returns array 

---

cli/src/cmd/forge/install.rs

Closes https://github.com/foundry-rs/foundry/issues/4261
Add a message to `forge install` command if no dependency was provided, in which case all deps are updated.

chore: add update deps message in install command

---

cli/src/opts/cast.rs

Running `cast etherscan-source ADDRESS` without setting Etherscan API key will show the following error message, telling user to specify it with `-e` option.
```
No Etherscan API Key is set. Consider using the ETHERSCAN_API_KEY env var, or **setting the -e CLI argument** or etherscan-api-key in foundry.toml
```
But `-e` option is not available,
```
❯ cast src --help
Get the source code of a contract from Etherscan.
Usage: cast etherscan-source [OPTIONS] <ADDRESS>
Arguments:
<ADDRESS>  The contract's address.
Options:
-c, --chain <CHAIN>            [env: CHAIN=] [default: mainnet]
-d <DIRECTORY>                 The output directory to expand source tree into.
--etherscan-api-key <KEY>  [env: ETHERSCAN_API_KEY=]
-h, --help                     Print help
```
Add missing short arg of …

fix(cast): `etherscan-source` api key short arg

---

config/README.md

#3481 added support for `cbor_metadata` internally, but it did not document it in the README. Users currently have to look up Foundry's source code to find the name of this new compiler setting.
Mention the newly introduced `cbor_metadata` setting in the config README.

docs: document "cbor_metadata" in README

---

anvil/src/eth/backend/mem/storage.rs

Follow-up of https://github.com/foundry-rs/foundry/pull/4263 which introduced a user-configurable maximum number of states to keep only in memory.
The issue is that with a non-zero limit (e.g. `--prune-history 50`) this causes an infinite loop in the following lines of code:
https://github.com/foundry-rs/foundry/blob/b45456717ffae1af65acdc71099f8cb95e6683a0/anvil/src/eth/backend/mem/storage.rs#L144-L151
`self.max_on_disk_limit` is zero in this case.
Added an extra check `!self.is_memory_only()` that actually checks that `self.max_on_disk_limit != 0`.

fix(anvil): memory only state non-zero limit infinite loop

---

evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Json.t.sol

Address comments raised by @mds1 on #4105 
- jsonPath supports both ".key" and "$.key"
- remove dbg! statement

fix: Canonicalize jsonPath to avoid breaking change

---

evm/src/error.rs
evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/ExpectRevert.t.sol
testdata/cheats/Json.t.sol

Unblocks https://github.com/foundry-rs/forge-std/pull/291
some cheatcode errors were not returned as errors but as abi strings, conflicting with the expect revert logic.
return actual errors in env cheatcodes

fix: encode env errors as errors

---

foundryup/foundryup

banner prints before any arg parsing or missing command error which may be confusing
also fix invalid arg message and print usage:
from: `foundryup: internal error: unknown option "-a"\n`
to: `foundryup: unknown option: -a`

chore(foundryup): print banner after parsing args

---

anvil/src/cmd.rs
anvil/src/config.rs
anvil/tests/it/transaction.rs
evm/Cargo.toml
evm/src/executor/fork/cache.rs

Ref https://github.com/foundry-rs/foundry/issues/3783
Ref https://github.com/foundry-rs/foundry/issues/3573
enables the `optional_block_gas_limit` and add cli arg to opt-in.

feat(anvil): add --disable-block-gas-limit

---

cli/src/cmd/forge/script/multi.rs

ref https://github.com/foundry-rs/foundry/issues/4325
previous errors were unhelpful.
@joshieDo the `split_once('(')` or error seems weird tbh, but unclear what the assumptions regarding `sig` are here. seems weird that this is an error at all.

chore(script): improve path file name errors

---

Cargo.toml

This simply sorts the workspace in foundry.toml
Simple change to make foundry code base a little bit better and make my first commit while learning the code base.

chore: Sort foundry workspace members alphabetically

---

Cargo.lock
Cargo.toml
anvil/tests/it/ganache.rs
anvil/tests/it/revert.rs
anvil/tests/it/traces.rs
chisel/Cargo.toml
chisel/src/executor.rs
chisel/src/session_source.rs
cli/Cargo.toml
cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/verify/etherscan/flatten.rs
config/src/lib.rs
doc/Cargo.toml
doc/src/writer/as_string.rs
fmt/Cargo.toml
fmt/src/chunk.rs
fmt/src/formatter.rs
fmt/src/solang_ext/ast_eq.rs
fmt/testdata/MappingType/fmt.sol
fmt/testdata/MappingType/original.sol

Closes #4319
Upgrade `solang-parser` to `0.2.2`
Add support for named mapping in forge formatter
Blocked by https://github.com/gakonst/ethers-rs/pull/2135

dep: solang parser 0.2.2

---

chisel/src/dispatcher.rs

I was trying out chisel and failed on
```
❯ chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ !fetch 0x142FD5b9d67721EfDA3A5E2E9be47A96c9B724A4 IERC1155CreatorImplementation
Added 0x142FD5b9d67721EfDA3A5E2E9be47A96c9B724A4's interface to source as `IERC1155CreatorImplementation`
➜ !source
Failed to format session source
```
The cause seems to be that in dispatcher.rs::527 the event parameters are formatted and the keyword ` memory` is appended to dynamic parameters of FixedArrays or Tuples. However this should happen only for function parameters, not event parameters. Appending it causes the compiler/formatter to fail.
Removing the macro `format_param` for event parameters does the trick.

fix(chisel): stop appending memory to event params

---

evm/src/executor/inspector/cheatcodes/env.rs
testdata/cheats/Broadcast.t.sol

The original motivation was stated in: https://github.com/foundry-rs/foundry/issues/2453. 
Running `vm.stopBroadcast();` without starting the broadcast first should result in error as it doesn't make sense. @onbjerg agreed that this could be improved.
I tweaked implementation of `vm.stopBroadcast()` cheatcode.

Prevent stopping not existing broadcasts

---

anvil/src/eth/api.rs

It only makes sense to the next block base fee per gas when EIP-1559 (hardfork `london` or newer) is enabled. Hardhat returns an error in this case with a slightly different error message (`hardhat_setNextBlockBaseFeePerGas is disabled because EIP-1559 is not active`).

fix(anvil): `anvil_setNextBlockBaseFeePerGas` return error old hardfork

---

cli/src/opts/cast.rs

I'd like to use the `finalized` and `safe` blocktags with `cast`
The `parse_block_id` function is used to parse `cast` cli commands.
Adds support for the following blocktags:
- `safe`
- `finalized`
These changes will apply to all commands that accept a blocktag.
Also includes unit tests for the different cases.

cast: parse additional blocktags

---

cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/send.rs
cli/src/cmd/cast/storage.rs
cli/src/opts/cast.rs

tg discussions, ref gakonst/ethers-rs#2095
current implementation contains a bug, fixed by: gakonst/ethers-rs#2155
remove `parse_name_or_address` and `parse_block_id`, which Clap defaults the parsing to use `FromStr::from_str`

chore: replace custom CLI parsers with ethers FromStr implementations

---

fmt/README.md

Document the `// forgefmt: disable-line` functionality.

docs: document fmt disable-line

---

fmt/src/formatter.rs
fmt/testdata/FunctionCallArgsStatement/bracket-spacing.fmt.sol
fmt/testdata/FunctionCallArgsStatement/original.sol

Follow up to #4363. Extra line was added to multiline call args

fix(fmt): extra line on multiline call args

---

cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs
cli/src/cmd/cast/send.rs
cli/src/cmd/cast/storage.rs
cli/src/opts/cast.rs

Fixes #4378
Clap prioritizes `From<&str>` over `FromStr` (with [`value_parser`](https://docs.rs/clap/latest/clap/macro.value_parser.html)'s automatic detection), thus we have to explicitly declare `value_parser` to use the `FromStr` implementation.

fix: use FromStr for NameOrAddress parsing

---

evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/GasMetering.t.sol

Pausing gas metering before creating a new contract causes the test to revert. This PR builds on #3906 to correctly handle `CREATE`/`CREATE2` call frames.
`CREATE`/`CREATE2` opcodes deduct additional gas for code storage, and deducted amount is compared to gas limit. If we set this to 0, create opcodes would fail with out of gas.
If we however set gas limit to the limit of outer frame, it would cause a panic after erasing gas cost post-create. Reason for this is, pre-create REVM records `gas_limit - (gas_limit / 64)` as gas used, and erases costs by `remaining` gas post-create. 
`gas used ref`: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm/src/instructions/host.rs#L254-L258
`post-create erase ref`: …

fix(forge): set correct gas limit when exiting `CREATE` frames when gas metering is paused

---

anvil/src/eth/error.rs

ref https://github.com/foundry-rs/foundry/issues/4388
cc @PhilippLgh
use same wording as hardhat.

chore: use compat wording in out of gas error

---

anvil/src/eth/backend/mem/mod.rs

ref https://github.com/foundry-rs/foundry/issues/4388
> sending gasLimit on a read (especially larger than block limit) is ignored by hardhat but failing in anvil:
> error: { code: -32603, message: 'EVM error CallerGasLimitMoreThenBlock' }
(Just noticed it seems there is also a typo: "CallerGasLimitMoreThanBlock")
> I know that Infura supports up to 10x block gas on reads so maybe the default setting should not be capped like this?
disable block gas limit setting for eth_call

fix(anvil): disable block gas limit in eth_call

---

anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
anvil/tests/it/gas.rs

At the moment, we allow transactions to execute if the tip is higher than the fee cap. Would be nice to reach parity with nodes such as [geth](https://github.com/ethereum/go-ethereum/blob/1db978ca6b28b28d5eda9cf04b519ee301b05345/core/error.go#L87) & [erigon](https://github.com/ledgerwatch/erigon/blob/devel/core/error.go#L37) who throw this error.
Add a check to see if the tip is higher than the fee cap.

feat(anvil): assert that fee cap is higher than tip

---

anvil/src/anvil.rs
anvil/src/cmd.rs
config/src/lib.rs

Currently it is not possible to use the alias defined in foundry.toml when passing the `--fork-url` parameter to anvil.
closes: https://github.com/foundry-rs/foundry/issues/3379
Add logic that loads the config file and attempts to resolve the alias using the `rpc_endpoints` field.

feat(anvil): resolve rpc aliases if foundry.toml is present

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
forge/README.md
testdata/cache/solidity-files-cache.json
testdata/cheats/Cheats.sol
testdata/cheats/ExpectCall.t.sol

Adds two new variants of the `expectCall` cheatcode that allows for asserting the amount of gas passed to a call.
```solidity
// Expect a call to an address with the specified msg.value, gas, and calldata.
function expectCall(address, uint256, uint64, bytes calldata) external;
// Expect a call to an address with the specified msg.value and calldata, and a *minimum* amount of gas.
function expectCallMinGas(address, uint256, uint64, bytes calldata) external;
```
Ran into a situation where I need to assert that the amount of gas passed to a nested call is correct in a test.

feat: Add new `expectCall` cheatcode variants

---

cli/src/cmd/forge/bind.rs

fix: exclude additional forge-std contracts in forge bind

---

anvil/src/lib.rs

If you are calling into `anvil::spawn` from rust code, you have no method currently to shut down the service (aside of killing the entire tokio runtime). This patch is to expose the `JoinHandle`s which can be aborted by the caller, if desired.
This patch exposes the `JoinHandle`s for the node service and server in the `NodeHandle` object. We switch from using a `select!()` to simply checking the state of each of those handles in the `poll` function, similar to what we're already doing with the `IpcTask` handle. This means that we'll have the same behavior that if either the node service or server completes, than this future will complete (`Poll::Ready(())`). This should not exhibit any changes in behavior from today, but does allow greater flexibility in the future.

Surface node_service and server join handles and handle select in poll function

---

fmt/README.md

In #4372, I introduced an error when documenting the behavior of the comments that can disable `forge fmt`.
I should have referred to `disable-next-line` instead of `disable-line` in the first example I gave.
This PR fixes that.

docs: correct example for disable-next-line

---

config/src/fuzz.rs
config/src/lib.rs
forge/src/lib.rs
forge/tests/it/config.rs

fix(config): remove fuzz.max_global_rejects

---

cli/tests/it/script.rs
evm/src/executor/inspector/cheatcodes/mod.rs

This PR fixes #4434 
In `forge script` during a broadcast, from within a call, if a call is made to another contract, or if a contract is created, the `new_origin` is reset to the original `original_origin` which basically means that the `tx.origin` is not the "broadcaster" anymore.
This is because before resetting, the depth of the call was not checked.
This should fix it.
I wrote a test to go with it. It's pretty simple. Let me know if I should write more tests.  
The test is entirely written in the test file `script.rs`. I saw that there is a `Broadcast.t.sol` which seems to be used for test. I can also move it there if it's better.

fix(forge): do not reset tx.origin during broadcast in forge script

---

evm/src/fuzz/strategies/int.rs

Per issue #4462, when using `foundry-evm` as a cargo dependency, we receive compilation errors that do not occur when building the project standalone. This error is not entirely obvious as to why it occurs only when used as a dependency, but the error itself simply asks for more type annotations to be available for the compiler, which are easily enough added here (since we know we want every conversation to be a u32 to I256). As such, adding these annotations fixes that error and makes the code slightly more explicit, which seems on the whole, a positive change.
Adds type annotations to `evm/src/fuzz/strategies/int.rs` to assist compiler, esp. when used as a dependency. There should be zero net effect on the code aside of (possibly) marginally faster build times (as more type information …

Add complete type annotations for into I256

---

macros/src/console_fmt.rs

New Feature:
Add %e and %x support for format string, resolving https://github.com/foundry-rs/foundry/issues/4464
When testing DeFi protocols, it's common to print the number of tokens for debugging, which always has big `decimals` and can be hard to read when console.log with `"%d"`
Add %e and %x support for format string
~~I found it a little difficult(for me) to support %e simply as %x; The `U256` format cannot be easily casted into `format!{[:e]}` supported types without precision loss. Either importing a new `BigInt` crate(just for this) or explicitly cast down to supported types seems not a good solution....I'm wondering some suggestions about this.~~
Solved

Add "%e/%x" format support for forge console log

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/expect.rs
testdata/cheats/Cheats.sol
testdata/cheats/ExpectEmit.t.sol

From the Foundry Book on [best practices](https://book.getfoundry.sh/tutorials/best-practices):
> When testing events, prefer setting all `expectEmit` arguments to `true`, i.e. `vm.expectEmit(true, true, true, true)`.
This PR introduces two `expectEmit` cheatcode variants that have no boolean arguments. All of the topics (`checkTopic1`, `checkTopic2`, `checkTopic3`, and `checkData`) are set to `true` by default.
I added the variants in the ABIGEN defined in `evm/src/executor/abi/mod.rs`, and then I implemented them in Rust in `evm/src/executor/inspector/cheatcodes/expect.rs`.
I'm not sure if any tests need to be written for this?

feat(evm): add "expectEmit" variants

---

common/src/selectors.rs

This PR changes the labels on pretty-calldata from decimal integers to hex labels, like one finds in the debugger.
For example, 
```
[0]:  0000000000000000000000000000000000000000000000000000000000000020
[1]:  0000000000000000000000000000000000000000000000000000000000000002
[2]:  0000000000000000000000000000000000000000000000000000000000000040
[3]:  0000000000000000000000000000000000000000000000000000000000000140
[4]:  000000000000000000000000da5a5adc64c8013d334a0da9e711b364af7a4c2d
[5]:  0000000000000000000000000000000000000000000000000000000000000000
[6]:  0000000000000000000000000000000000000000000000000000000000000000
[7]:  0000000000000000000000000000000000000000000000000000000000000080
[8]:  0000000000000000000000000000000000000000000000000000000000000044
[9]: …
```

change pretty-calldata labels from decimal ints to hex values

---

foundryup/foundryup

Grep's `-n` option does not allow `foundryup` to download the correct archive.
Strip the relative line number (if it exists) from grep's output, so the output is a valid SHA.
Fixes #4510

fix(foundryup): strip grep line number

---

anvil/src/config.rs

connect adjusts the provider interval based on the chain's avg blocktime, this is not used in forking mode, so can skip that.

perf(anvil): get rid of redundant chain id call

---

anvil/src/eth/backend/mem/mod.rs
evm/src/executor/backend/error.rs

previously all dev accounts were fetched sequentially, however since the forked backend can handle multiple requests, we can fetch all of them concurrently.

perf(anvil): fetch all dev accounts concurrently in forking mode

---

cast/src/lib.rs

Currently `cast chain` doesn't recognize optimism-goerli, it returns `unknown`.
Add optimism-goerli genesis hash recognition. The hash is taken from https://goerli-optimism.etherscan.io/block/0 and the name from the output of `forge verify-contract` when it gets passed `--chain unknown`.

chore(cast): add optimism-goerli chain detection

---

anvil/src/cmd.rs
anvil/src/lib.rs

Closes https://github.com/foundry-rs/foundry/issues/4561
--silent should not only silence startup log but all logs

fix(anvil): silence all logs if --silent

---

cli/src/cmd/forge/bind.rs

If you run `forge bind --overwrite` without first running `forge bind`, the `--overwrite` tries to delete a nonexisting directory. This results in:
```
Error:
No such file or directory (os error 2)
```
Want to avoid this error.
Just a very quick and obvious fix.

Fix bind --overwrite failing on first run

---

evm/src/executor/backend/mod.rs

when we fork to tx we need to fork the state at (tx.block - 1) but use the `tx.block` env (block number, timestamp etc.)
ref https://t.me/foundry_rs/27136

fix(evm): update env properly when fork to tx

---

Cargo.lock
cast/Cargo.toml
cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Output of `cast code` is currently raw hex encoded bytes, which is hard to read and reason about.
Add a flag `--disassemble` that disassembles the bytecode into individual opcodes.
The format of the output is based on [pyevmasm](https://github.com/crytic/pyevmasm). (see screenshot).
The implementation of the disassembly is factored out into its own [little crate](https://crates.io/crates/evm-disassembler). Lmk if you'd like me to avoid that extra dependency and instead copy paste the implementation into a module here. 
EDIT: Additionally added a separate `disassemble` cast command

feat(cast): Option to disassemble bytecode returned by cast code

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/fork.rs
anvil/tests/it/transaction.rs

Closes https://github.com/foundry-rs/foundry/issues/4564
cache responses when `eth_call`, `eth_estimate`, `logs` is delegated to the fork (if block number < forked block)

feat(anvil): cache more fork responses

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs

should close https://github.com/foundry-rs/foundry/issues/4572
when we're fuzzing we only take reference of the backend until we need to modify it (cheatcodes). however then the backend wasn't initialized properly and resulted in panics in the evm.
initialize fuzzed backend when cloned.

fix(evm): initialize fuzzed backend

---

macros/src/console_fmt.rs

We already have hexadecimal formatting for `address` and `unit256` thanks to #4482. It seems only logical to have a formatting option for the last most-used solidity type `bytes32`. Solves #4579 
I implemented '%s' '%x' and '%o'.

implement ConsoleFmt for H256

---

.github/workflows/release.yml
anvil/src/genesis.rs
cast/src/rlp_converter.rs
chisel/src/dispatcher.rs
cli/src/cmd/cast/bind.rs
cli/src/cmd/utils.rs
config/src/fix.rs
config/src/warning.rs
deny.toml
evm/src/decode.rs
evm/src/executor/backend/mod.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/fuzz/invariant/call_override.rs
evm/src/fuzz/invariant/error.rs
fmt/src/buffer.rs
fmt/testdata/Yul/fmt.sol
fmt/testdata/Yul/original.sol
testdata/fuzz/invariant/common/InvariantReentrancy.t.sol

This PR fixes misspellings in the codes.
For maintenance and clarity.
I found some misspellings when I was reading the codes.
Ran the following command using https://github.com/client9/misspell
(Ignored some words that might be false-positive)
```shell
misspell -i inbetween,strat -w .
```

Fix misspellings

---

cli/src/cmd/forge/verify/mod.rs
config/src/lib.rs

closes https://github.com/foundry-rs/foundry/issues/3861
Closes https://github.com/foundry-rs/foundry/issues/4571
closes #4563
This includes a fix that gives the `etherscan_api_key` of the config precedence over the chain. This is sound because, if --etherscan-api-key is provided via CLI it should be prefered over the etherscan table.
This also improves the error message instead of `ETHERSCAN_API_KEY` not found.
```
Failed to resolve env var `BSC_ETHERSCAN_API_KEY` in `${BSC_ETHERSCAN_API_KEY}`: environment variable not found
Context:
- environment variable not found
```
ptal @DaniPopes

fix(verify): improve etherscan section parsing

---

evm/src/executor/backend/fuzz.rs

Attempts to fix https://github.com/foundry-rs/foundry/issues/4586
the fuzzed backed is cloned across multiple fuzz runs, but each fuzz run can have different env settings (sender for example).
when we call inspect, we unset the initialized state so if it is initialized again, this now behaves just as the regular backend.

fix(evm): uninitialize fuzz backend on inspect

---

evm/src/executor/inspector/debugger.rs
evm/src/fuzz/mod.rs

This just uses `saturating_sub` on some gas subtractions to ensure no underflows.
I'm doing some funky stuff with forge and currently disabling gas costs, which caused me to notice these bugs. While they are unlikely to occur for others, might as well fix them.
This just changes two subtractions to use `saturating_sub`. So instead of underflowing an unsigned integer, the remaining gas will be left at zero.

Fix bugs when gas is disabled

---

evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/4592
serialize into BTreeMap instead of HashMap

fix: serialize into BtreeMap

---

cli/src/cast.rs
cli/src/cmd/cast/call.rs
cli/src/cmd/cast/storage.rs
cli/src/opts/cast.rs
cli/tests/it/cast.rs
common/src/selectors.rs

1. Remove the requirement to specify `--block` for `cast basefee` and `case age`. (Both only depend on the block argument besides rpc opts). Closes #4584.
2. Unify and improve help text for the `block` argument. Add `finalized` and `safe` tag in help text.
3. Make `block` argument optional for `cast block` and default to `latest` following other commands.

fix(cast): block opt

---

.github/workflows/test.yml

> warning: filter expressions are no longer experimental: NEXTEST_EXPERIMENTAL_FILTER_EXPR does not need to be set

ci: rm redundant env setting

---

Cargo.lock
Cargo.toml
anvil/Cargo.toml
anvil/core/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
chisel/Cargo.toml
cli/Cargo.toml
cli/test-utils/Cargo.toml
common/Cargo.toml
config/Cargo.toml
doc/Cargo.toml
evm/Cargo.toml
fmt/Cargo.toml
forge/Cargo.toml
macros/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml

Not pinning the ethers-rs dependency to a specific `rev` causes cargo to fetch literally any commit when forge is used as a library
Pin the etherers-rs to a specific `rev` using workspace dependencies, also makes it easier to update

use workspace dependency for ethers-rs

---

cli/src/cmd/forge/test/mod.rs
evm/src/fuzz/mod.rs
forge/src/result.rs
forge/src/runner.rs

Ref https://github.com/foundry-rs/foundry/issues/4618
this reduces fuzz mem footprint drastically, for some reason we kept all cases in memory but we don't need them
calculate report info (gas usage) ad-hoc so cases are longer required to be in memory.

perf: dont keep all fuzzed cases around

---

config/src/fuzz.rs
evm/src/fuzz/mod.rs
evm/src/fuzz/strategies/state.rs
forge/tests/it/config.rs

ref https://github.com/foundry-rs/foundry/issues/4618
Identified the root cause for unbounded mem growth and it was the state dictionary which records all state changes over all fuzz runs.
This adds size restrictions to the state dictionary. if it exceeds the limit random entries are removed.
perhaps the current limits (200MB addresses, 200MB values) are still a bit excessive but with some napkin math this should now be limited by the number of parallel fuzz tests.
for example on a machine with 16 cores (max 16 parallel tests)
16 * (200MB+200MB) so around 6.4 GB for the fuzz state alone at most
I ran seaport and stayed under 4GB, but now we can easily tune this
cc @sambarnes
these settings are now configurable via 
`max_fuzz_dictionary_addresses` and `max_fuzz_dictionary_values` config …

perf: restrict state dictionary size

---

foundryup/install

on apple silicon homebrew might be installed under /opt/homebrew

chore: check for libusb in alternative homebrew location

---

foundryup/install

Running the install script as shown in the readme doesn't work at the moment due to a syntax error introduced in https://github.com/foundry-rs/foundry/pull/4642. 
fix syntax error.

fix install script

---

utils/src/abi.rs

Fixes #4624 
I'm not sure if this is the right approach but it *should* be sufficient to just output the struct name without the parent scope as we are generated single, flat interfaces here. Or am I missing sth.?

fix struct name output by only returning last name segment

---

chisel/src/session.rs
chisel/src/session_source.rs

closes https://github.com/foundry-rs/foundry/issues/4652
respect the `--use` and `--offline` flags
```
chisel --use "/Users/Matthias/.svm/0.8.19/solc-0.8.19"                                                                                                                                                          
Welcome to Chisel! Type `!help` to show available commands.
```
```
chisel --use "0.8.8" --offline                                                                                                                                                                                  
Error: can't install missing solc 0.8.8 in offline mode
```
cc @clabby

fix(chisel): respect --use and --offline

---

evm/src/utils.rs
forge/tests/it/repros.rs
forge/tests/it/test_helpers.rs
testdata/repros/Issue4640.t.sol

Closes https://github.com/foundry-rs/foundry/issues/4640
arbitrum `block.number` is l1BlockNumber
use the l1BlockNumber field to set env.blocknumber

fix: set block.number to l1BlockNumber on arbitrum

---

anvil/src/cmd.rs

Supports SIGTERM, allowing docker setups to do a graceful shutdown by default.

feat(anvil): shutdown on sigterm

---

anvil/src/config.rs
evm/src/executor/fork/backend.rs
evm/src/executor/fork/init.rs
evm/src/executor/fork/multi.rs
evm/src/executor/opts.rs

Closes https://github.com/foundry-rs/foundry/issues/4683
In #4669 we're using the l1BlockNumber for `env.blockNumber` on arbitrum, but we still used `env.blocknumber` when configuring the fork and caching. Instead we need to use the number from the block `block.number`
cc @0xdapper

fix: use block.number when creating fork

---

config/src/fuzz.rs
config/src/invariant.rs
config/src/lib.rs
evm/src/executor/inspector/fuzzer.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
evm/src/fuzz/strategies/param.rs
evm/src/fuzz/strategies/state.rs
forge/tests/it/config.rs
forge/tests/it/invariant.rs

refactors how the size of the dictionary was enforced: https://github.com/foundry-rs/foundry/pull/4627
instead of randomly evicting entries (very expensive), check max capacity before inserting.
cc @PaulRBerg

perf(fuzz): improve Fuzz Dictionary size enforcement

---

ui/src/lib.rs

hotfix for https://github.com/foundry-rs/foundry/issues/4608
now everytime the memory is accessed in the debugger, words are not necessarly aligned anymore. e.g if I write `<value> 0x04 mstore`:

feat(forge) add non-aligned memory words in debugger

---

cli/src/cmd/forge/fmt.rs

This closes #4478 (cc @h0tw4t3r)
In `forge fmt` I think `--root` should work correctly with PATH(S).
The `conflicts_with = "root"` option was added by @mattsse in PR #2180 but after looking at the code and running some tests, I think both options can work together.

fix(fmt): --root shouldn't conflict with [PATH]

---

Cargo.toml
anvil/core/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
cli/Cargo.toml
cli/test-utils/Cargo.toml
common/Cargo.toml
config/Cargo.toml
doc/Cargo.toml
evm/Cargo.toml
fmt/Cargo.toml
forge/Cargo.toml
macros/Cargo.toml
utils/Cargo.toml

```log
warning: /path/to/Cargo.toml: `default-features` is ignored for ethers, since `default-features` was not specified for `workspace.dependencies.ethers`, this could become a hard error in the future
```
Add `default-features = false` for `workspace.dependencies.ethers[-*]`, and remove it from all the workspace crates

chore: fix cargo default-features warning

---

chisel/src/bin/chisel.rs
chisel/src/history.rs
chisel/src/lib.rs

load and save chisel history
default location is `~/.foundry/.chisel_history`

fix(chisel): properly load and save history

---

chisel/src/dispatcher.rs
chisel/src/executor.rs
chisel/src/session_source.rs

Closes https://github.com/foundry-rs/foundry/issues/4467
chisel uses solc directly and remappings were not configured in the compiler input.
This sets the remappings retrieved from the config, so if invoked in a project this will also set all remappings but not forge-std because we set the VM directly (we can not rely on forge-std being present).
cc @mlgarchery @exp-table @clabby

fix(chisel): support library imports

---

Cargo.lock
cast/Cargo.toml
cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Adds `--optimize` option to cast sig to optimize the signature to have a defined number of leading zeroes, similar to description in: https://github.com/foundry-rs/foundry/issues/2175.
As described in: https://github.com/foundry-rs/foundry/issues/2175, this feature provides users the ability to easily optimize function signatures.
Allows user to provide `--optimize` option along with `cast sig`, defining a number of leading zeroes to mine by adding a nonce to the function signature.

feat(cast): add optimize selector command

---

cast/src/lib.rs

I added this in https://github.com/foundry-rs/foundry/pull/4705
as @DaniPopes correctly pointed out, this is not needed because rayon's closures don't require 'static and AtomicBool isn't even Copy

chore: rm redundant Arc

---

anvil/src/eth/backend/mem/mod.rs

ref https://github.com/foundry-rs/foundry/issues/4729
removes a check that could lead to unrequested logs because we forcefully set the lower bound to the best block
eg:
`from_block: 5`
`best: 4`
would include logs of block 4

fix(anvil): dont adjust from block

---

foundryup/install

So far, the `foundryup` installation script assumes that if the preferred shell is zsh, then the path to the foundry binary will be stored in the `$HOME/.zshrc`.
This could trap zsh users because they could have their zsh configuration elsewhere. This script will create a file on the $HOME directory, forcing zsh users to copy that line to the correct file and then remove the newly created file. 
We should use the `$ZDOTDIR` value instead; if this value is unset, it will default to `$HOME`.
Another thing is that following [zsh documentation](https://zsh.sourceforge.io/Intro/intro_3.html), `.zshrc` is not the correct file to store paths. Instead, we should use `.zshenv` because this file is executed for all zsh shells, whether they are interactive or not. 
The `.zshrc` file configures the …

Make foundryup installation script more flexible for ZSH users

---

utils/src/rpc.rs

remove infura keys because very long, the auto backoff of 30s is likely the root cause for slow CI

chore: remove infura test keys

---

chisel/src/bin/chisel.rs
chisel/src/cmd.rs
chisel/src/dispatcher.rs
chisel/src/executor.rs
chisel/src/runner.rs
chisel/src/session_source.rs
chisel/tests/cache.rs

Needed when working with functions that take `bytes calldata` as argument and when messing with the calldata layout in assembly.
New `chisel` command `!calldata / !cd` which appends the provided hex data after `run()` function selector. In solidity it can then be accessed via `msg.data` (need to skip the 4-byte selector though).

feat(chisel): add support for setting `msg.data`

---

cli/src/cmd/forge/fmt.rs
cli/src/cmd/forge/geiger/visitor.rs
fmt/src/formatter.rs
fmt/src/macros.rs
fmt/src/visit.rs
fmt/testdata/InlineDisable/fmt.sol
fmt/testdata/InlineDisable/original.sol

Fixes (the comment) https://github.com/foundry-rs/foundry/issues/3830#issuecomment-1516391215
This happens because `visit_var_declaration` doesn't write the ' =' if it gets skipped in inline config
`VariableDeclaration` should not write the eq, and `Statement::VariableDefinition` should always write a semicolon since it's a statement, instead of having perma false/true arguments

fix(fmt): `Variable{Declaration,Definition}` visit and fmt implementations

---

cli/Cargo.toml

This change fixes the bug reported in https://github.com/foundry-rs/foundry/issues/4446 by using the feature specified in Reqwest's documentation specified here https://docs.rs/reqwest/latest/reqwest/#optional-features
Motivation
This fixes the original fix from this issue https://github.com/foundry-rs/foundry/issues/2873 in this PR https://github.com/foundry-rs/foundry/pull/2939
Using the functionality of rustls-native-certs such as using the environment variable to include your certificate had no effect and caused requests to still fail.
Solution
Reqwest's documentation providers a different string for the feature than what was originally added. Built and tested locally with the SSL_CERT_FILE environment variable and it now picks it up and works.

fix: Fix self signed certificates in chain by using correct Reqwest feature

---

evm/src/executor/inspector/cheatcodes/env.rs

Match logic of `StopBroadcast` (which fails if a broadcast is not in progress)
Fail to `StopPrank` if there is no prank in progress to stop.

StopPrank iff there is a prank started

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/logs.rs
ui/src/lib.rs

Implementing @mds1 's ideas about extending breakpoints, ref: https://github.com/foundry-rs/foundry/pull/4679#issuecomment-1503455791
1. Add conditional breakpoints (`vm.breakpoint("a", true)` to switch on and `vm.breakpoint("a", false)` to switch off)
2. Write the `['<char>]: goto breakpoint` notice on debugger footer
It's getting somewhat big and I cannot see the whole footer (about 2/3 currently) at once. Why not adding a `h` to toggle help that would take more space, but could be collapsable ?

(feat) add conditional breakpoints

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
forge/README.md
testdata/cheats/Cheats.sol
testdata/cheats/ExpectCall.t.sol

Closes #4513 
Currently we can only assert that a call is made to a function using expectCall(), it would be nice to have another cheatcode to check the number of time a call was made, which can also be useful to assert if a call is not made.
Overriding the `expectCall` cheatcodes to also accept the number of times it is expected to be called and enforce the same.

feat: add count to `expectCall` cheatcodes

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectCall.t.sol

#4833 introduced a breaking change to `expectCall` whereby if no `count` was specified it would default to 1. This PR preserves the older behaviour of checking that a call is made at least once if `count` is not specified.
Change `count` type to `Option<u64>` and revert to older behaviour if `is_none()`

fix(forge): `expectCall` with no count

---

.github/workflows/test.yml

Issue reproduction & forge-std tests can take quite a long time to finish & stall CI. Ideally we should be able to make sure that only these tests are the ones clogging the CI other than looking at the `SLOW` output on logs.
Creates new jobs for forge-std and issue reproduction tests.
Closes #4782.

CI: Separate issue reproduction & forge-std tests into their own jobs

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
forge/src/gas_report.rs

Anvil is improperly bailing out of estimating gas if we run into a `GasTooHigh` error—we should treat it like other `revert/OOG/OOF` errors and just adjust the gas price accordingly. This was due to an improperly mapped error type when performing a call with state.
Properly maps the error to `InvalidTransactionError::GasTooHigh` and refactors the binary search to also include the case when this happens.

fix(anvil): properly estimate gas instead of bailing on `GasTooHigh`

---

cli/src/cmd/cast/run.rs

Currently cast run panicks when trying to simulate a failed contract deployment, due to a misplaced "unwrap" call.
This fixes that.
Remove the offending `unwrap` and replace with a pattern match.
closes https://github.com/foundry-rs/foundry/issues/4870

fix(cast) `cast run` panicks when encountering failed contract deployment

---

foundryup/foundryup
foundryup/install

The installation scripts assume `$HOME` as the default directory to store foundry files. This is not wrong, but we are defiling the `$HOME` directory. 
Some users might have proper configurations so that application-specific data is stored somewhere else logically.
We should follow [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) specification.
Following XDG Base Directory specification, this kind of data should be in `$XDG_DATA_HOME`.
This PR updates the installation scripts to use this variable instead of `$HOME`,

Use XDG Base Directory specification in installation files

---

anvil/src/eth/api.rs
anvil/src/eth/backend/executor.rs
anvil/src/eth/backend/mem/mod.rs
cli/tests/fixtures/can_create_template_contract-2nd.stdout
cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked-2nd.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout

We missed a few cases with #4861. To avoid so, we're just porting what was left of Reth's gas estimation method, which handles a few more special cases. As we're using revm 3 things are not exactly 1:1, but they are pretty close.
We also fix a somewhat unrelated executor bug that would throw an incorrect error.
Closes #4877 and #4882.

fix(anvil): Port Reth's gas estimation and fix wrong executor error

---

anvil/src/cmd.rs

There is a typo in `--state` argument description. This small PR fixes it 😁
The `bot` word in `This is an alias for bot --load-state and --dump-state.` was changed to `both`.
I'm not sure if changing comment in this place fixes output of `anvil --help`. If there are any other places to fix, please let me know 🦉 .

fix(anvil): typo in `--state` argument description

---

anvil/server/src/ipc.rs
chisel/src/session_source.rs
cli/src/cmd/forge/coverage.rs
common/src/provider.rs

Seems to be the last thing that slipped through—chisel is installing 0.8.17 by default and should install at least 0.8.19
Closes #4888 
Makes chisel install 0.8.19 by default for paris support, which is our default EVM version now. Users might still see errors if they have an older compiler version installed by default—wondering if we should give out a warning message in chisel too.

fix(chisel): upgrade default solc version to 0.8.19

---

Cargo.toml

We bumped the main ethers package, but did not bump the other subpackages. This bumps them.

chore(deps): bump all individual ethers packages

---

cli/src/cmd/cast/send.rs
cli/src/opts/wallet/mod.rs

Closes #4831.
`cast send` right now assumes that if a signer can't be constructed, it must fall back to `eth_sendTransaction` in all cases. This is not exactly true, and will result in misleading error messages depending on the combination of flags passed in for the wanted signing method. Particular highlights were:
- If a path to a folder that contains a keystore was passed in, it would try and walk the directory to try and find it. However, keystores no longer contain the `address` field that was being used to identify the correct keystore, so they were never found. This caused `cast send` to fall back to `eth_sendTransaction` hoping the remote RPC had the unlocked account to sign the tx.
- If the ledger option was passed in but the ledger was not available or connected, `cast send` …

fix(cast): Harden `cast send` and provide more accurate error messages

---

evm/src/executor/inspector/cheatcodes/env.rs

Right now,  the `vm.difficulty`/`vm.prevrandao` just do not work if the correct EVM version is not being used and give no warnings. See https://github.com/foundry-rs/forge-std/pull/373
Make them completely fail if not using the correct EVM version, to avoid unexpected behavior during tests.
Feel free to nit over the fail message!

feat(cheatcodes): ensure `vm.difficulty` and `vm.prevrandao` fail if not using the correct EVM Version

---

common/src/traits.rs
forge/tests/it/invariant.rs
testdata/fuzz/invariant/common/InvariantTest1.t.sol

Closes #4650
There's been repeated discussion about how to call fuzz/invariant tests. One of the things proposed for invariants is to add some alias that could be used instead of invariant to more properly narrow down its meaning, without necessarily removing the usage of `invariant` yet.
Adds `statefulFuzz` as an alias to `invariant`, as suggested in the linked issue.
I personally do not have strong opinions on what alias we should use, and `statefulFuzz` feels a tad long—feel free to nitpick!
Proposed plan is:
- Foundry 1.0 will support both.
- Foundry 1.1+ will support both, but will warn users that `invariant` might not be supported in a future 2.0 release.
- Foundry 2.0 and beyond: remove the `invariant` keyword.

feat(invariant): add `statefulFuzz` as an alias to `invariant`

---

config/src/doc.rs
doc/src/builder.rs

When using the docs command, I wanted to be able to use a different README file for the 'home page' of the docs other than README.md.    I want my README file to be used for developers to be able to boot up my smart contracts but i want the welcome page of our docs (teller finance) to be better for users.  However, there was no way to do this with 'forge doc' as it was hard coded to use README.md . It was also impossible to command 'forge doc' to copy files over and then separately build the book folder with a separate command  (that would be nice too but that would have to be a different PR).  
Therefore, I added a config to my foundry.toml file llke so:
[doc]
homepage= "HOME.md"
and I created this PR which changes the builder so that it attempts to read that config value.  If it is …

improving docs generation by adding homepage to config

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectCall.t.sol

**This is a breaking change.**
Closes #4879.
Implements the intended behavior for the `expectCall` cheatcode, with and without count.
`expectCall` will be invoked in two different modes depending on how the cheatcode was used:
- If no count was provided, the mode will be `NonCount`. The behavior of this mode is:
- It is **additive**. Calling `expectCall(...)` `N` times, will set a lower bound of expected calls of `N`, but will _not_ revert if more than `N` calls are matched. This is the legacy `expectCall` behavior.
- For the same calldata, **cannot** be overwritten with a `Count` `expectCall` cheatcode call.
Example of `NonCount` additive behavior:
```
// this will PASS
cheats.expectCall(address(target), abi.encodeWithSelector(target.add.selector, 1, 2)); …
```

fix(cheatcodes): Fix `expectCall` behavior

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectEmit.t.sol
testdata/cheats/GetDeployedCode.t.sol
testdata/fork/Transact.t.sol

*This is a big breaking change.*
Partially closes #1745. `expectCall` is left and needs #4912 to be merged before it can be reworked to support this. 
Makes `expectEmit` only work for the _immediate_ next call after the cheatcode has been called.
`expectEmit` remains _additive_. Calling `expectEmit` `N` times will set a lower bound of `N` events that must be seen for the cheatcode to pass successfully.
The current behavior of `expectEmit` allows to:
- declare the cheatcode before all events are emitted.
- "fill" the expected emits _before_ the test ends.
- match events after the tests ends.
The intended behavior is that it only works for the *next immediate call*. This new behavior only allows to:
- Call the cheatcode AND fill the expected emit right after calling the cheatcode. Declaring …

feat(cheatcodes): Make `expectEmit` only work for the next call

---

evm/Cargo.toml

evm crate lacks new ethers-solc feature, now that it is optional in ethers

fix: add missing ethers-solc feature

---

CHANGELOG.md

As we've been introducing a few breaking changes this week and will introduce bigger ones, we need a way to keep track of them, as well as a way to highlight all the changes post 1.0 that can be kept for posteriority.
Adds a `CHANGELOG.md` file with information about pre 1.0 breaking changes. This later on will contain the changes made on each semver release.

feat(repo): add `CHANGELOG.md`

---

Cargo.lock
common/Cargo.toml
common/src/fmt.rs
common/src/lib.rs
macros/Cargo.toml
macros/src/fmt/console_fmt.rs
macros/src/fmt/mod.rs
macros/src/fmt/token.rs
macros/src/fmt/ui.rs
macros/src/lib.rs

`foundry-macros` depends on `foundry-config` for just the UIFmt trait, thus any user of the simple macro crate would have hundreds of other unrelated dependencies.
Part of #4928, helps with #4935

chore: move formatting logic to foundry-macros

---

chisel/src/executor.rs
chisel/src/session_source.rs
chisel/tests/cache.rs
cli/test-utils/src/util.rs

Closes #4888 .
Seems people still are having issues with the issue linked above. It's caused by a mismatch between the used solc and evm version required.
Introduces a check to ensure that the user is using/installing an solc version that is compatible the merge onwards if the evm version is higher or equal to Paris. This overrides the solc option set by the user if it's not recent enough, but it will *not* override a local solc path.
cc @clabby looping you in! this should hopefully fix this—lmk if i missed any other solc checks elsewhere

fix(`chisel`): Override set solc and Install post-merge solc version if needed

---

chisel/tests/cache.rs

Seems #4949 introduced some regressions in the integration tests, probably due to async usage with tokio on tests.
Revert to original serial behavior on tests and use `blocking_install` to not need to run tests asynchronously.

fix(chisel/ci): un-async chisel tests for filesystem consistency

---

Cargo.lock
cli/tests/it/svm.rs

svm-rs has been bumped, so we should update things accordingly.
bump related packages & latest solc

chore(deps): bump `svm-rs`, `svm-rs-builds` and update `LATEST_SOLC`

---

evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/mod.rs
testdata/repros/Issue3055.t.sol

Closes #3055.
Fuzzing was having soundness issues with snapshot failures. This is because snapshot failures were not being persisted throughout fuzz runs, and when the Fuzz Backend Wrapper we use was dropped, this information was lost, leading to inconsistent test PASS states.
Persist snapshot failures when fuzzing.

fix(fuzzing): persist snapshot failures when fuzzing

---

evm/src/trace/decoder.rs

Closes #916.
Adds a few more built in labels as requested in the issue. Keeping it simple and not adding #640 to this as we might wanna do that in a separate PR

feat(`evm`): more built-in labels

---

anvil/src/hardfork.rs
anvil/tests/it/anvil_api.rs

Anvil wasn't updated to support newer hard forks from the merge onwards—with the shanghai upgrade this has caused some bug reports when forking. This updates it.

feat(`anvil`): Support newer (Paris, Shanghai) hard forks

---

config/src/lib.rs

Closes #4954. Note that this does not handle the case when the solc version is autodetected—I think this might need a change in ethers-solc?
If both solc and evm version are set in the foundry config, we should ensure both are compatible. A solc/evm version combo is compatible when using an specific solc version won't introduce invalid opcodes that the EVM version can't handle. In the solc versions currently supported by forge, this only really happens with using `>=0.8.20` on evm versions less than Shanghai.*
* Technically, different evm chains also could have problems with newer specs, but handling this at a multi-chain level is another conversation in itself.
Sanitize the EVM version / solc combo if both are set.

fix(`config`): properly sanitize evm and solc version if both are set

---

.github/workflows/cross-platform.yml
.github/workflows/docker-publish.yml
.github/workflows/release.yml

This reverts commit 557f5d57695dcda123218192e82f478e44387443.
@tolbrino I'm reverting this because this broke releases. 
the file names include the full sha tag when they should only be nightly
see https://github.com/foundry-rs/foundry/releases/tag/nightly-4f9369f876c70cefe53c9fea5919e078b50e29ae
vs https://github.com/foundry-rs/foundry/releases/tag/nightly-e15e33a07c0920189fc336391f538c3dad53da73 
also one of these is wrong
```
IS_NIGHTLY: ${{ github.event_name == 'schedule' || ( github.event_name == 'workflow_dispatch' && github.ref_type != 'tag' ) }}
if: env.IS_NIGHTLY == true
```
as mentioned my bash skills are kinda limited, hence the revert.
feel free to reopen and we'll test this before merging again.

Revert "ci: Fix use of parameter in conditionals (#4984)"

---

evm/src/fuzz/invariant/executor.rs

Reverts #4980 — this new check is flawed and breaks invariant tests.

Revert fix(invariant): revert check for assert failures on handlers #4980

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectCall.t.sol
testdata/fork/Transact.t.sol

Reverts foundry-rs/foundry#4986
this was blocked for 1.0 and should not have been merged yet.

Revert "feat(cheatcodes): Make `expectCall` only work for the next call's subcalls"

---

cli/test-utils/src/util.rs

we're definitely running 0.8.20, svm file lock does not prevent all edge cases which could be the reason for the uptick of failing cross tests

chore: preinstall 0.8.20

---

cli/tests/it/script.rs

this test is flaky on windows:
--- TRY 4 STDERR:        foundry-cli::it script::check_broadcast_log ---
thread 'script::check_broadcast_log' panicked at 'assertion failed: fixtures_log == run_log', 
using assert_eq should provide more context

test: use assert_eq for flaky test

---

chisel/tests/cache.rs

The last flaky parts of the CI have been these chisel CI tests—we were forcing a 0.8.19 install so they don't complain about the EVM version being too new (Paris). This seemed to cause a wreck on the CI fs and gave weird errors. So this tries the other way around—sets up foundry to use an older evm version (London) to let these tests use 0.8.13, which is what they default to.
Removes the forced installation of 0.8.19 from the chisel tests and forces the chisel session to use London.

fix(ci): remove ensure solc from chisel tests

---

config/README.md

As shown by https://github.com/foundry-rs/foundry/issues/3661 and [this StackExchange Q&A](https://ethereum.stackexchange.com/q/147319/24693), Foundry users are confused about the default value that `msg.sender` has in the testing call contexts.
This PR aims to bring a little clarity to the README by:
- Displaying the actual default value that `sender` and `tx_origin` have now (the address removed by this PR is the historical sender used by DappTools, which is no longer used by Foundry)
- Explaining how the default value was chosen
I will confess that I was personally confused by this, too, although I have been using Foundry for >1 year now.

docs: update default "sender" and "tx_origin"

---

chisel/src/session_source.rs
testdata/cheats/Cheats.sol

Closes #5051. Chisel was not respecting the EVM version configured when compiling, as it was not included in the compiler input. 
include the EVM version in the compiler input.
**A caveat:** I see some people wanting to use chisel with versions < 0.8, but this is not possible because we're using the `testdata` `Cheats.sol` for the cheatcodes, which is set to `>=0.8`. Maybe this is what we want and we should let people know that solidity versions lower than 0.8 are not accepted, or should we just use the same pragma that is on forge std (`>=0.6.2 <0.9.0`)?

fix(chisel): include evm version on solc compiler input

---

testdata/cheats/ExpectEmit.t.sol

While doing QA I saw the `expectEmit` tests could be strengthened a bit to test events can be matched in a window on the next call as intended.
Add a few more tests which won't hurt to verify we have correct behavior. Note that this will be merged into the feature branch.
Btw, CI is expected to fail as external integration tests will complain due to the new behavior.

chore(tests): add more cases for `expectEmit`

---

cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/script/runner.rs
cli/src/cmd/forge/test/mod.rs
common/src/traits.rs
evm/src/executor/mod.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
forge/src/lib.rs
forge/src/multi_runner.rs
forge/src/result.rs
forge/src/runner.rs
forge/tests/it/config.rs
forge/tests/it/core.rs
forge/tests/it/fork.rs
forge/tests/it/fuzz.rs
forge/tests/it/inline.rs
forge/tests/it/invariant.rs

All `Result::Err` variants are currently ignored (other than an error log) when running any test: https://github.com/foundry-rs/foundry/blob/a5c27411c7e5d1dd574df758060da8ad501ecbde/forge/src/multi_runner.rs#L161
This PR makes methods that execute tests return only the `Ok` type, which includes a `success` or similar field. This heavily simplifies logic around these methods and avoids `unwrap` calls in callers or silent failures in CLI.

fix(forge): `test` result/error handling

---

config/src/error.rs
config/src/lib.rs

ref https://github.com/foundry-rs/foundry/issues/5088 silence contract init code size error by default

chore: silence contract init code size error by default

---

evm/src/trace/identifier/etherscan.rs

ref https://github.com/foundry-rs/foundry/issues/5082
for some reason we were using default etherscan client if none was configured...
not sure if this is the root cause of the issue but this is definitely a bug.

fix: dont use default etherscan identifier

---

cli/src/cmd/cast/send.rs

If user specifies a chain ID, with this change it will check if the current chain id returned by the RPC is the same as user provided chain id. If not will attempt to switch it with `wallet_switchEthereumChain`.
This change particularly allows me to use https://frame.sh/ to sign transactions using the unlocked signers on local node method. Ex: https://gist.github.com/0xdapper/7461f2b0f0100b6508938cfff4db2dad
Switch the chain if necessary.

feat(cast): switch chain before sending tx if current chain is different

---

cli/tests/it/script.rs
evm/src/executor/inspector/cheatcodes/mod.rs

This bug was cursed.
So, in #5062 it was described that nested CREATES cause the nonce to not increase and the `tx.origin` to become wrong. This fixes the first part—as I believe we might need a revm change for solving the latter part.
What's happening here is that the nonce was not being incremented because even though we're only cleaning up broadcasts at the depth they were created, we still need to reapply them at increased depths even if we're not using them for txs (as we only need the tx of the broadcast level). This PR therefore makes the `create` hook reapply broadcasts at increased depths, but only create the first tx.

fix(`cheatcodes`): keep applying broadcast sender replacement at increased depths

---

Cargo.toml

See rust-lang/cargo#10910, released with Rust 1.70
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
```

fix: cargo warning

---

Cargo.lock
anvil/Cargo.toml
anvil/src/eth/backend/mem/mod.rs

9 months ago I wrote the code for `anvil_dumpState` and `anvil_loadState`. During the time, I mentioned the possible benefits of compressing the state dumps.
Recently, my state dumps have been getting so big that they no longre seem to work with the JSON RPC API (getting errors like "Invalid request" even though there should be no limit on the size of requests).
Whatever the reason, much larger state dumps could be much, much smaller by compressing the blob returned by `dumpState` and loaded by `loadState`. This improves the efficiency of data handling for tools outside of anvil, as well as eliminating the above described request issue due to request size.
Using the `flate2` cargo package, compress the state dump returned by anvil on `anvil_dumpState` with `GzEncoder`. Use default …

Compressed state dumps

---

cli/src/cmd/forge/script/mod.rs

Closes #5119.
Decoding traces using etherscan is slow, as we run into rate limits. We should make this opt in by only using them an etherscan API key is provided.
Detect if an api key is provided, and warn/use etherscan appropiately.

chore(`script`): disable etherscan tracing if no API key is provided, provide warning

---

cli/tests/it/script.rs

this fails regularly if there are ABI changes
can ignore it at this point

test: ignore flaky check

---

anvil/src/eth/backend/mem/mod.rs
evm/Cargo.toml
evm/src/executor/fork/cache.rs

should close https://github.com/foundry-rs/foundry/issues/5125
we disable basefee check if basefee is 0
https://github.com/bluealloy/revm/blob/69f417f15755d7fcf9fac8dd2df3dc4cb2cd6bad/crates/primitives/src/env.rs#L282
this can never happen naturally because the lower limit technically possible is `7`

fix(anvil): disable basefee if manually set to 0

---

evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/mod.rs
testdata/cheats/ExpectCall.t.sol
testdata/cheats/ExpectEmit.t.sol

Closes #5138, but will go into the 1.0 branch.
When a function reverts, it's like it never happened as it gets rolled back—but we're still matching calls/events.
This completely disallows matching calls or events if the user has previously used `expectRevert`. This restriction will be in place until the `expectRevert` is "filled", meaning until after the next call, by which either the test will fail due to a non-reverting call, or end execution as it effectively reverted.

feat(`cheatcodes`): disallow usage of `expectRevert` with `expectCall` and `expectEmit` 

---

cli/src/cmd/forge/test/mod.rs
cli/tests/it/test_cmd.rs

Fix wrong exit code when `forge test` is ran with `--fail-test` flag and `forge` exits early. Reported in #4883.
The solution is to exit with an error code if a test fails and the `--fail-test` flag is specified.
The cause of the bug was that the failing test suite wasn't added in the loop that aggregates test results due to breaking early when the `--fail-test` flag is specified. I moved inserting the test suite to the results to the top of the loop to fix it.
Also added CLI tests to check if `forge test` exits with an error on `--fail-fast`. 
Note that the `--json` option invokes a different code path for aggregating results, but failing fast is not supported currently in json mode. I added the test with the `"--fail-fast --json"` flags  for future proofing in case support is added …

fix(forge): exit with error code on fail fast (#4883)

---

cast/src/lib.rs

Closes #5143.
Improves the `abi-encode` error messages, like so:

chore(`cast`): improve `abi-encode` error messages

---

cli/src/cmd/utils.rs

Optimism after upgraded to bedrock has much better devex
After bedrock, transactions are held in a mempool meaning that it is possible to send batches of transactions. There is no need to wait for each transaction to be confirmed before sending the next like in the legacy system. This commit removes the need to send transactions sequentially when using optimism with `forge script`
Remove the force sending of txs sequentially when using optimism

script: support sending batches to optimism

---

Cargo.lock
Cargo.toml

We need to upstream some verification fixes from ethers—so we're repinning ethers to a specific commit until further notice.

chore(deps): pin ethers to branch & commit

---

.github/RELEASE_FAILURE_ISSUE_TEMPLATE.md
.github/workflows/release.yml

Closes #5154 
Motivated by the recent release failure we had—we should be notified automatically if this happens

feat(`ci`): add auto issue on release failure

---

evm/src/coverage/analysis.rs

Fix for https://github.com/foundry-rs/foundry/issues/4305
We need this fix to properly track our coverage.
Coverage analysis doesn't travel through the library when the path in the AST is Return -> FunctionCall -> MemberAccess -> Library Call

fix(coverage): return values assigned to library calls

---

abi/Cargo.toml
cli/tests/it/script.rs
utils/Cargo.toml

some crates don't build individually (`cargo c -p crate`) because of certain features that are unified in the workspace
```sh
#!/usr/bin/env bash
crates=(
anvil
anvil/core
anvil/rpc
anvil/server
abi
binder
cast
chisel
cli
cli/test-utils
common
config
doc
evm
fmt
forge
macros
macros/impl
ui
utils
)
for crate in "${crates[@]}"; do
echo "--- $crate ---"
cargo c --manifest-path $crate/Cargo.toml
done
```

fix: individual crate compilation

---

evm/src/executor/inspector/cheatcodes/ext.rs
forge/tests/it/repros.rs
testdata/repros/Issue5038.t.sol

Fixes #5038
Parsing powers of ten failed even if the number was a correct json value
It seems that `Number::to_string` from `serde_json` formats big numbers powers of 10 to use the scientific notation. After parsing the number to a string and giving it to `U256::from_dec_str` or `U256::from_dec_str`, the conversion failed because the expected string should be in decimal format. 
In any other case, the conversion worked perfectly because `Number::to_string` is not trying to use scientific notation. In order to avoid a wrong string formatting I'm using the floating point representation of the number and then parsing it into string using the `format!` macro. Although this does work for powers of ten, it fails in other scenarios. Common shenanigans found while debugging were the following …

fix(forge): `vm.parseJson` and error while parsing powers of ten

---

anvil/src/eth/fees.rs

Closes #5161 
Treats base fee set at 0 as a constant and skips calculating a new basefee altogether if so.

fix(`anvil`): treat 0 `basefee` as constant

---

cli/src/opts/cast.rs

- Added alias `cast base-fee` to `cast basefee`.
- Suggestion for this change by @mattsse in https://github.com/foundry-rs/book/pull/925

chore(cast): added cast base-fee alias for basefee

---

anvil/src/eth/backend/mem/mod.rs

the env's difficulty is pinned to the forked blocks difficulty during startup.
this removes in incorrect update where we set the blocked envs difficulty to the total difficulty at the forked block which lead to saturated total difficulty over time:
https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/backend/mem/mod.rs#L845-L845
remove incorrect value write for block difficulty

fix: don't set block env's difficulty with fork's total difficulty

---

cli/src/cmd/forge/script/build.rs
utils/src/lib.rs

Sometimes the linking process would result in libraries being deployed more than once, which could also lead to verification issues on block explorers.
Ref https://github.com/foundry-rs/foundry/issues/4443
~A really quick hack to deduplicate deployed contracts is in this PR. Essentially we hijack the "dynamic linking" part of the linker, where the user can supply pre-determined library addresses, since we already check this structure to see if the library has been deployed before. When we finish linking a new object, we add it to the list.~
☝🏻  Unfortunately this did not work, since we just collect the addresses and slugs of deployed libraries from the linker for all contracts we want to deploy. Since some contracts may deploy on the same library, the library would show up twice in the …

fix: dedupe linker outputs

---

cast/README.md
cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

To my knowledge, there's not an easy way to get the codesize of a contract outside of Solidity's `extcodesize()` assembly function. As of right now, you need a build artifact and then need to take the size of it by trimming it by 2 to remove the '0x' and then dividing by 2 to get the value in bytes. This is far more clumsy than it should be.
This `cast codesize` command makes it easy to immediately query the runtime codesize in bytes for a contract while only providing the address.
I elected to only return the number of bytes as a string for maximum flexibility. 
Earlier I had a more advanced implementation: 
```rust
pub async fn codesize<T: Into<NameOrAddress> + Send + Sync>(
&self,
who: T,
block: Option<BlockId>
) -> Result<String> {
let who = who.into();
let who_str = match &who { …
```

feat(cast): cast `codesize`

---

cli/src/cmd/forge/script/build.rs
utils/src/lib.rs

This reverts commit 12ea9f61a344087989f884d2ab735893c77ea576.
Sadly it seems this bricked a few tests on some places—there seems to be problems when retrieving the code of the library.

Revert "fix: dedupe linker outputs (#5164)"

---

cli/src/opts/cast.rs

This standardizes cast commands to not use `--`, but rather their name, and adds the dash version as an alias instead.
The motivation for this is that some commands had this, and some didn't. As we're gonna do V1 soon it's a good time to standardize it.
Remove `--` from cast commands and set the dashed version as an alias.

refactor(`cast`): remove double dashes from cast commands

---

Cargo.lock
chisel/Cargo.toml
cli/Cargo.toml

- bump strum
- rust-analyzer style, lmk if we like them or we want to revert to original

chore: bump strum

---

anvil/src/config.rs

Logs the anvil default chain ID if not in fork mode. The output now looks as follows:

feat(`anvil`): log chain ID if not in fork mode

---

cli/src/cmd/forge/install.rs

Fix for #4552. Now `init`/`install` will add the proper `.gitmodules` when in an existing git repo ex. a monorepo.
Support using `forge` in monorepos.
When adding the `.gitmodules` file, use the path of the top-level directory of the working tree [0] as the `current_dir`.
[0] https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-toplevel

fix(forge): use proper path for .gitmodules

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/doc.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/remove.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/forge/update.rs
cli/src/opts/dependency.rs
cli/src/utils.rs
cli/tests/it/cmd.rs
config/src/lib.rs

Closes #5095
Best reviewed with whitespace disabled in github viewer
- Refactor git commands in foundry-cli (see `Git` struct)
- Add `--depth=1` to clone and submodule commands
- note that this is technically breaking, since tags are fetched at the given depth, so now the default behaviour won't automatically switch to the latest tagged version branch unless `--deep` is specified
- clone commands (which are likely to "hang") now print git progress by default, silenced by `--quiet`
TODO: `--deep` with shallow by default, or viceversa? cc @mattsse @Evalir

feat(forge): shallow clones

---

cast/src/lib.rs
cli/src/opts/cast.rs

Follows up on PR https://github.com/foundry-rs/foundry/pull/5178 to clean up the docs to explain the `cast` methods 
@Evalir as requested https://github.com/foundry-rs/foundry/pull/5178#pullrequestreview-1493319690

chore: Clean up docs for `abi-decode` & `calldata-decode` 

---

cli/tests/it/script.rs

CI seems to be flaky right now due the broadcast log test.
Just escape the `\r` carriage returns to not have this difference across OSs on this test.

fix(`ci`): escape carriage returns when checking log

---

.github/workflows/test.yml

Part of the issue regarding consistency and flakyness in the CI is due to using random solidity versions. This forces a solidity 0.8.19 install through the CI to default to this version.
Install SVM and use 0.8.19

fix(`tests`): force install solidity 0.8.19 through svm

---

foundryup/foundryup

For v1, foundryup needs a few changes:
- The default `foundryup` command needs to download the latest v1 binary instead of nightlies.
- Doing `foundryup legacy` command should download the last v0 binary we publish before v1.
_this is still being tested_

`foundryup`: v1 changes

---

cli/src/cmd/forge/inspect.rs

Currently it is possible to get the selectors for functions (`methodIdentifiers`) and events (`events`) but not errors.
This PR adds a `errors`field to the `forge inspect`command.

feat(forge): Add `errors` field to `forge inspect`

---

cli/src/cmd/cast/run.rs

Fixes https://github.com/foundry-rs/foundry/issues/5122
Optimism and arbitrum both have a fixed first transaction that is made from/to specific special addresses. Optimism tx has gas price 0, arbitrum tx has gas price and gas limit both 0 which violates the basefee and gas used checks in revm. 
Specifically for `cast run` we can skip the base fee checks and assume they always pass because those transactions are already confirmed by the network and hence _valid_. Hardcoded a tx skip from `a4b05` address but there's probably a better and cleaner way to do this.

fix(cast): disable base fee checks and skip 0xa4b05 address txs

---

evm/src/executor/inspector/cheatcodes/expect.rs

fix(`mockCall`): add missing check on alternative mockCall signature

---

abi/abi/HEVM.sol
abi/src/bindings/console.rs
abi/src/bindings/hardhat_console.rs
abi/src/bindings/hevm.rs
cli/src/cmd/forge/test/mod.rs
cli/tests/fixtures/can_check_snapshot.stdout
cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
cli/tests/fixtures/can_test_repeatedly.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
evm/src/decode.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/mod.rs
forge/src/result.rs
forge/src/runner.rs
forge/tests/it/cheats.rs
forge/tests/it/config.rs
forge/tests/it/fuzz.rs
testdata/cheats/Cheats.sol
testdata/cheats/Skip.t.sol

Closes https://github.com/foundry-rs/foundry/issues/1123
Adds a `vm.skip(bool)` cheatcode that marks tests as skipped. It also moves the test runner to use a `TestStatus` enum to mark success, failure, or a skipped test, which is the bulk of the work here really.
- On normal tests, this will just check if it failed due to a skip.
- On fuzz tests, it will fuzz with only one run and check the revert reason.
- On invariant tests, it will run once and check if it failed due to a skip, like a normal test.
One thing I noticed is that the handling and return types between normal/invariant/fuzz tests are pretty different. When we revisit the test runner we should try and streamline the handling of all of these so we can properly detect EVM errors in an easier way.
TODO:
Sample output:

feat(cheatcodes): `vm.skip(bool)` for skipping tests

---

anvil/src/eth/backend/mem/mod.rs

Post merge TD is set to prevrandao. Anvil was adding prevrandao to fork difficulty causing overflows
Relevant dependency in REVM https://github.com/bluealloy/revm/blob/1839b3fce8eaeebb85025576f2519b80615aca1e/crates/interpreter/src/instructions/host_env.rs#L27
Check for post merge and don't add difficulty

Add check for post merge and don't add difficulty

---

cli/src/opts/cast.rs

Currently, the `cast logs` command erroneously uses the same description as `cast access-list` and lacks a short-hand alias.
This PR corrects the `cast logs` description and adds the short-hand alias `l`. Since this alias was already occupied by `cast lookup-address`, I opted to give it the replacement `la` which I believe is incidentally more appropriate.

docs: fix docs for `cast logs`

---

evm/src/fuzz/strategies/state.rs

This pr provides a small update to the fuzz corpus that should allow higher effectiveness in fuzzing to find bugs, hit assertions, cause failures, etc.
The fuzz corpus uses the values for the `push`, `slot`, `slot_value`, and log `topics` for relevant `accounts` in the state db.
The fuzz corpus can be minorly improved by also inserting values that are +/- 1 of the value, in order to pass through conditional statements that use `<` or `>`.
For example:
Challenge:
```solidity
contract MagicNumber {
uint256 public target = 0;
function check_against_magic(uint256 number) public {
if (number > 100_098) { 
if (number < 100_100) {
target = 1;
}
}
}
function is_solved() public view returns (bool){
return target == 1;
}
}
```
Test:
```solidity …
```

feat(forge): improve fuzz corpus

---

chisel/src/bin/chisel.rs

RIght now, chisel ignores dotenv files (at least on startup), and this leads to it being unable to fork chain which RPC_URL is set in config via .env variable.
For example:
```
foundry.toml:
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
goerli = "${GOERLI_RPC}"
```
```
.env:
GOERLI_RPC=some_rpc
```
In such context `chisel --fork-url goerli` will fail with following error `Failed to resolve env var GOERLI_RPC in ${GOERLI_RPC}: environment variable not found` until the GOERLI_URL will not be explicitely set to environment via `export GOERLI_RPC=some_rpc`
Add `utils::load_dotenv` to startup of chisel

Read dotenv when running chisel

---

forge/src/runner.rs

Closes #5262 — removes the additional run added for checking if the test was skipped, and checks the last fuzz run instead. cc @DaniPopes

perf(`runner`): check last fuzz result instead of adding aditional run

---

cli/src/cmd/forge/test/mod.rs

Closes #5271
test is now async, this removes leftover block_on
ref https://github.com/foundry-rs/foundry/pull/5263

fix: rm leftover block_on

---

cli/src/cmd/forge/test/mod.rs
cli/tests/fixtures/can_check_snapshot.stdout
cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
cli/tests/fixtures/can_test_repeatedly.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout

Add aggregated summary to the test results for all test suites in the format:
`Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)` 
https://github.com/foundry-rs/foundry/issues/5195
- ~How should we write tests for this? Is there a place to write tests for `test` command (no pun intended 😄)~

feat(forge): add aggregate summary to test result

---

cli/src/opts/wallet/multi_wallet.rs

As explained in #5179 when using the `--mnemonic-indexes` flag if not providing the `mnemonics` flags foundry complains that the arg is required even if another wallet option like `ledger` or `trezor` is used which also can use the  `--mnemonic-indexes` flag.
It seems that in [4768](https://github.com/foundry-rs/foundry/pull/4768/files#diff-da1bbdee19948a843fedbd01d62893be3b2557c23d07333649a1c60816d9a9aaR140) the `requires = "mnemonics"` constraint was added to the  `--mnemonic-indexes` args which seems to be the cause of  #5179 because the constraint wasn't there before so I simply removed it.

fix(forge): remove required `mnemonics` flag when using `--mnemonic-indexes`

---

cli/src/opts/cast.rs

Closes #5275 — adds `--abi-decode` as a visible alias just to have parity with the book. The command is new and never had the dashes, but it doesn't hurt to have them.

chore(cast): add --abi-decode as visible alias

---

Cargo.lock
anvil/src/config.rs
anvil/src/eth/sign.rs
cast/src/tx.rs
cli/src/cmd/forge/script/build.rs
cli/src/cmd/forge/script/runner.rs
cli/src/cmd/forge/verify/etherscan/mod.rs
cli/src/suggestions.rs
common/src/shell.rs
config/src/lib.rs
doc/src/parser/mod.rs
evm/src/executor/inspector/access_list.rs
evm/src/executor/inspector/cheatcodes/expect.rs
fmt/src/buffer.rs
fmt/src/comments.rs
forge/tests/it/fuzz.rs

Some new clippy lints were affecting CI.
This also bumps ethers to latest that also has clippy fixes.

chore: fix clippy warnings + bump ethers

---

cli/tests/it/config.rs
config/README.md
config/src/lib.rs

Users may prefer that the contract metadata contains the literal source of compiled contracts (instead of Swarm and IPFS URIs) when compiling contracts with Forge.
This makes it easier to, for instance, verify contracts on Tenderly with the contract metadata, since Tenderly doesn't appear to have native support for verifying contracts belonging to Foundry projects.
Resolves #4805.
This change exposes the `use_literal_content` ethers-solc setting (equivalent to `--metadata-literal` on solc) in the Foundry config as `use_literal_content`.

feat(config): expose use_literal_content solc setting in config

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/forge/test/filter.rs
cli/tests/fixtures/can_build_skip_glob.stdout
cli/tests/it/cmd.rs
common/Cargo.toml
common/src/compile.rs
common/src/glob.rs
common/src/lib.rs

Currently, `forge build --skip test --skip script` is unreliable as some projects do not consistently use `.t.sol` or `.s.sol`. This PR enables glob patterns like `--skip */test/** --skip */script/**` to enable only building `src`.
Closes https://github.com/foundry-rs/foundry/issues/4628
I moved an existing glob matcher util to `common` and used it in the the `FileFilter` impl

feat(forge): implement glob pattern for forge build --skip

---

common/src/selectors.rs

This error message is somewhat counterintuitive:
```
❯ cast 4byte 0x098866
Error:
Invalid selector: expected 8 characters (excluding 0x prefix), got 8 characters (including 0x prefix).
```
It is also inconsistent with similar behaviour in the `decode_calldata`, which always considers length excluding the prefix

More intuitive cast 4byte error message when selector is too short

---

evm/src/executor/inspector/cheatcodes/mod.rs

Fixes #5308.
Improves the error message on the `expectEmit`/`expectCall` cheatcodes to point out the call where the cheatcodes where expected to happen reverted.
Example for `expectCall`:
Example for `expectEmit`:

feat(`cheatcodes`): modify emit/call failure message depending on status

---

ui/src/lib.rs

#5310 
It seems that in a previous PR,  a new keystroke was added to hide the footer with the shortcuts in the debug mode. The variable responsible for this functionality was set to `false` by default, to fix the bug I changed it to true so that once someone opens the debug window can optionally hide it by typing `h`.
I also renamed the variable in order to make it clearer what aspect of the UI it manages.
When opening the debug window the first time:
After typing `h`:

fix(forge): shortcuts footer not showing in debug mode

---

cli/src/opts/cast.rs
cli/src/opts/forge.rs
cli/tests/it/script.rs
common/src/selectors.rs
evm/src/trace/identifier/signatures.rs

Closes #4177.
The new API URL moved—this switches to using the new db.

fix(`4byte`): use new db url

---

cli/src/cmd/forge/script/mod.rs

While running deployment scripts in CI, I had no way to bypass code size limits - without the use of some terminal keystroke logger, like `expect`.
A user should be able to bypass `forge script`'s contract size check via an inline argument.
Use `code_size_limit` on the `evm_opts.env` object for the contract size check, and the hardcoded EIP-170 size as a fallback value.

feat(script): Use code_size_limit for in deployment scripts

---

cli/src/cmd/forge/inspect.rs

Issue: https://github.com/foundry-rs/foundry/issues/2433
Allow `--pretty` flag to print a specified contract's abi which is formatted using `foundry_utils::abi::abi_to_solidity` _(same way as `cast interface`)_
_example_
```bash
$ cat src/Counter.sol
// SPDX-License-Identifier: UNLICENSED
contract Counter {
uint256 public number;
function setNumber(uint256 newNumber) public {
number = newNumber;
}
function increment() public {
number++;
}
}
$ ~/Documents/GitHub/foundry/target/debug/forge inspect Counter abi --pretty
interface Interface {
function increment() external;
function number() external view returns (uint256);
function setNumber(uint256 newNumber) external;
}
```

feat(forge): print formatted interface when using `forge inspect <contract> abi --pretty`

---

ui/src/lib.rs

This is a follow up PR to foundry-rs/foundry#5313 based on a suggestion by @pcaversaccio to add a hint in the debug window to inform the users that the footer can be hidden by typing `h`.
Add the hint to the correct footer text and removed unused variables.
Final result:

refactor(forge): add hint to toggle footer in debug window

---

anvil/core/src/eth/mod.rs
anvil/src/cmd.rs
anvil/src/config.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/lib.rs

It should be possible to auto-impersonate accounts upon the initial spawning of Anvil instances.
This PR introduces an `--auto-impersonate` flag which enables auto impersonation of accounts when the anvil instance is created. This helps avoid the need to use `curl` or `cast rpc` to set `anvil_autoImpersonateAccount` to true when the Anvil instance is spawned. Resolves #5334

feat(anvil): Anvil `--unlocked` for auto-impersonation on instance creation

---

chisel/src/session_source.rs

Closes #5326 
Explicitly includes `forge-std/Vm.sol` into sources list only in case when `forge-std` is not available in remappings

Add support for forge-std imports in chisel

---

config/README.md

Adds missing docs for `auto_detect_remappings`.
Ref https://github.com/foundry-rs/foundry/pull/3036.

docs: document auto_detect_remappings

---

evm/src/trace/decoder.rs

We were using an incorrect definition coming from evm.codes, [which has now been fixed there](https://github.com/smlxl/evm.codes/pull/236/files). This fixes it here too.
Note that this doesn't really solve #5337 completely—we require parsing this precompile in a custom manner as it doesn't conform to an ABI spec.

fix(calltracer): name ecpairing precompile correctly

---

RELEASE_PROCESS.md

Adds a `RELEASE_PROCESS.md` file that describes how the new release process is intended to look.

feat(docs): add `RELEASE_PROCESS.md`

---

Cargo.lock
abi/Cargo.toml
anvil/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
chisel/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
config/Cargo.toml
evm/Cargo.toml
fmt/Cargo.toml
forge/Cargo.toml
macros/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml

chore(`crates`): bump crates to 1.0.0

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

This PR applies the changes needed to properly release stable foundry versions. Changes are:
- Fix several nightly or stable detection changes in the main release workflow, as this was broken.
- Stop pruning nightlies.
- Remove any cronjobs for scheduled nightlies, and only create new releases on `vx.x.x` tag pushes.

feat(`ci`): v1 release workflow changes

---

Cargo.lock
Cargo.toml
chisel/src/solidity_helper.rs
fmt/src/solang_ext/ast_eq.rs

@mattsse please check this with a grain of salt. I'm not sure what the problems were, but it compiles and all tests passed except for the following:
```
cmd::can_check_snapshot
create::can_create_template_contract
create::can_create_using_unlocked
test_cmd::can_use_libs_in_multi_fork
```
But failure seems unrelated (number of contracts compiled)
(Hopefully) Closes https://github.com/foundry-rs/foundry/issues/5358
Upgrade

bump solang-parser to 0.3.1

---

evm/src/coverage/analysis.rs

I found the following bugs in `forge test coverage` :  
1.  The hits of a library used in a base contract is missing in the coverage report 
2.  The hits of a library used in a library is missing in the coverage report  
3.  The hits of a function call in a binary operation is missing in the coverage report 
The fix for 2 also works for 1.  
Here is a simple project to replicate 2 & 3: 
`LibA` is the base contract of `LibB`, and `LibB` is the base contract of `LibC`.  
Only `LibC` is directly used in the contract `useLib`:  
```solidity
// SPDX-License-Identifier: UNLICENSED
library LibA {
function get() internal view returns (uint256 result) {
assembly {
result := sload(0xa)
}
}
}
```
```solidity
// SPDX-License-Identifier: UNLICENSED …
```

fix(coverage): fix missing items in indirectly used libraries

---

evm/src/executor/backend/mod.rs

Working with Foundry EVM Executor, one can alter balance, nonce and code of an account, but not the storage.
This PR exposes two functions
1. `active_fork_db_mut` will be `pub` (same as `active_fork_mut`)
2. Added the function `insert_account_storage` to the Backend

Expose storage altering functions in EVM Executor Backend

---

common/src/compile.rs

When compiling an etherscan project, we want solc version to be taken from etherscan, and not be automatically chosen.
disable automatic detection

Disable solc version auto detection in etherscan project

---

anvil/src/config.rs
anvil/src/eth/backend/mem/mod.rs

Closes #5341 
Right now, anvil does not properly set everything to handle unlimited block gas limit, if the `disable_block_gas_limit` flag is passed in.
properly set all the require configs

fix(`anvil`): properly make block gas limit unlimited if disabled

---

cli/tests/it/integration.rs

Sparklend is a pretty complex repo that is still straightforward to run tests on—and has managed to uncover several edge cases in our linking code. We should include it from now on to ensure new changes are good
Include `sparklend` as a forking integration test (as it needs an external rpc url to run some of the tests)

chore(`tests`): add `sparklend` as external forking integration test

---

.github/workflows/cross-platform.yml

Windows cross plat builds are failing due to using a multi line command—let's just put everything in a single line, doesn't hurt
Should start to alleviate CI and let these tests build

fix(`ci`): use single line command for windows test

---

cli/README.md

After https://github.com/clap-rs/clap/commit/d43f1dbf6f1f7865dccfece0e1605a12efb76670#diff-941dad1b645f696e69334cbff5b923dd8905d3981d6d23872d56da67f9110c50, all doc files were moved to `docs.rs`, removing the referenced README
Just changing the reference to point to docs.rs

chore: change outdated clap::_derive reference

---

evm/src/utils.rs

We were missing some hard forks for selection as evm version, mainly the really old ones.
Add them

fix(`evm`): add missing hardforks

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs
cli/tests/it/cast.rs

Often it is useful to get the raw encoded transaction from an RPC provider. 
Implement the "raw" field for `cast tx` which if specified returns the RLP transaction instead of the transaction fields. 
```
cast tx 0x44f2aaa351460c074f2cb1e5a9e28cbc7d83f33e425101d2de14331c7b7ec31e raw
0xf86d824c548502743b65088275309491da5bf3f8eb72724e6f50ec6c3d199c6355c59c87a0a73f33e9e4cc8025a0428518b1748a08bbeb2392ea055b418538944d30adfc2accbbfa8362a401d3a4a07d6093ab2580efd17c11b277de7664fce56e6953cae8e925bec3313399860470
```
This is the same output as:
https://etherscan.io/getRawTx?tx=0x44f2aaa351460c074f2cb1e5a9e28cbc7d83f33e425101d2de14331c7b7ec31e
Some RPC (`geth`) endpoints support `eth_GetRawTransactionByHash` but this is not always available, as is the case with Alchemy.

feat(cast): output raw tx

---

Cargo.lock
cli/src/cmd/forge/script/build.rs
forge/src/multi_runner.rs
utils/Cargo.toml
utils/src/lib.rs

Closes #5396.
The new linking fixes broke workspace setups that have files imported from outside the project root.
Add a fallback that is composed of the project root + the relative path obtained.

fix(`linking`): handle workspace setups by adding a fallback for artifacts

---

Cargo.lock
Cargo.toml
cli/src/cmd/forge/remappings.rs
cli/src/cmd/forge/script/build.rs
cli/tests/it/config.rs
common/src/compile.rs
config/src/providers/remappings.rs
config/src/utils.rs

Dependencies in projects using Foundry can mess with how imports are resolved through the project because remappings from dependencies are just merged with remappings defined in the root folder.
To solve this, we make use of solc's remapping contexts.
This PR adds support for specifying remapping contexts if necessary, but ideally it should never be. Instead, this PR also automatically scopes each remapping defined in dependencies to files in the dependency itself.
Global remappings (`context: None`) are still automatically generated for each installed dependency, making it possible to import them as usual.
This PR in other words just makes the following user-facing change: remappings defined in dependencies/libraries can no longer override remappings defined in …

feat: remapping contexts

---

anvil/src/eth/miner.rs
binder/src/utils.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/fork.rs
evm/src/executor/inspector/fuzzer.rs
evm/src/executor/inspector/tracer.rs
fmt/src/comments.rs
testdata/cheats/Json.t.sol
ui/src/lib.rs

Closes #5422.
Support `.` as identity key to retrieve the whole JSON object. It's also possible to use `$` but ppl are familiar with jq as well. cc @mds1 
Also took a lil opportunity to slightly refactor some of the json parsing function—I think we can improve the json parsing code as a whole (by making it some sort of struct that works as a parser)

feat(cheatcodes): allow dot identity key for json

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/forge/fmt.rs
cli/src/utils.rs
fmt/src/comments.rs
fmt/src/helpers.rs

Really weird code in CLI -> forge fmt
Something to note: a loop in `from_comment_and_src` takes up to 80% of the entire time spent formatting a source because it loops over every character before a comment, for every comment.
Normally this is not that noticeable since formatting is parallelized over a lot of small files, but it is when there are very big files with a lot of block comments
Best reviewed with "Hide whitespace"
- Make it less bad
- Replace `console` with `yansi` in cli since it's used only for ANSI formatting

refactor(forge): refactor fmt command and parsing

---

abi/abi/HEVM.sol
abi/src/bindings/hevm.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/trace/utils.rs
testdata/cheats/Json.t.sol
testdata/cheats/Vm.sol

Closes #5369 , supersedes https://github.com/foundry-rs/forge-std/pull/226 as a native impl of the cheatcode.
Instead of reverting if a key does not exist, a more correct behavior should be exposing a helper to validate if a key exists or not.
Implements a `keyExists(string calldata json, string calldata key) external view returns (bool)` cheatcode, which can validate if a certain key exists or not.
cc @mds1

feat(`cheatcodes`): add `keyExists` cheatcode

---

common/src/compile.rs

Currently, etherscan verified contract with with [Direct Imports](https://docs.soliditylang.org/en/v0.8.20/path-resolution.html#direct-imports) fails to compile
https://etherscan.io/address/0x15afc6fb4b76727a725709d7cd61742e4c3d2897#code as an example
Set the root path of the project to be the source path (haven't found any better way)

change etherscan root folder

---

cli/src/cmd/forge/fmt.rs
utils/src/lib.rs
utils/src/path.rs

We weren't filtering out the ignored paths correctly in the case we ran `forge fmt --check` on a project root without any more input on the contract locations.
canonicalize the ignored paths, and filter them out

fix(`fmt`): properly ignore paths when `forge fmt` is called without any paths

---

evm/src/executor/inspector/cheatcodes/ext.rs

Closes #5423.
This is really a semantics issue—the code is fine. This just makes it clear that it's an error the parsing library throws.
Also removes some unneeded formatting.

chore(`cheatcodes`): extend `JSON` error messages

---

anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs

There is an observed deadlock scenario in the anvil backend code. 
In short, this is caused by incorrectly trying to take 2 read locks on the same thread with the potential of a waiting write lock on a different thread.
On line 1190 of `anvil/src/eth/backend/mem/mod.rs`:
- The read lock taken by the `if let...` is still in scope when it calls into `mined_logs_for_block` on the next line. See https://doc.rust-lang.org/stable/reference/destructors.html#temporary-scopes.
- Then on line 1355, another read lock is attempted.
- If a write lock has been attempted on another thread, you will have a deadlock. Write Lock A will be waiting for Read Lock A to release, but Read Lock A can't release until Read Lock B is taken, which can't happen with the pending Write Lock A.
This was confirmed by:
1. …

Fix deadlock scenario in Anvil's backend/mem

---

cli/src/cmd/cast/run.rs
cli/src/cmd/forge/build/paths.rs
cli/src/cmd/forge/doc.rs
cli/src/utils.rs
cli/tests/it/create.rs
config/src/macros.rs
config/src/utils.rs

I want to use this utility in an external project

refactor(find_project_root_path): optional arg to provide path instead of cwd default

---

evm/src/fuzz/invariant/executor.rs

Closes #4718.
The targeted contracts were not being checked for `DSTest` assertions—which means assertions were never going to work. We now check for these when checking if the depth runs can continue. This should not be an issue if the targeted contracts do not inherit `DSTest`.

fix(`invariant`): support assertions on handlers

---

cli/src/cmd/cast/run.rs

Closes #5453 and all recent duplicates.
Make `--evm-version` available on `cast run` so ppl can specify the correct evm version for the transaction they'd like to run.

feat: make evm version configurable on cast run

---

cli/assets/README.md
cli/src/cmd/forge/init.rs

Adding README.md in the default template to give more info on how to work with the provided template.
fixes #5456

Create README.md in default template

---

cli/assets/CounterTemplate.s.sol
cli/assets/CounterTemplate.t.sol

To Add named imports which can increase readability.
In `CounterTemplate.t.sol` and `CounterTemplate.s.sol` 
`named` imports have been added.
fixes #5455

Add named imports in default solidity templates

---

evm/src/executor/backend/mod.rs
evm/src/executor/backend/snapshot.rs
evm/src/executor/fork/database.rs
evm/src/executor/snapshot.rs

Closes #5118 
Right now snapshots are not persisted, and snapshots created after the snapshot to be deleted are also deleted.
Remove this legacy behavior by just persisting snapshots.
We now have a few more clones as a result of this, but it should be OK—this is an infrequent operation.

feat(`evm`): make `vm.snapshot`s persistent

---

chisel/src/executor.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/script/executor.rs
cli/src/cmd/forge/test/mod.rs
evm/src/executor/opts.rs
forge/tests/it/config.rs

A smol leftover from #5503, we could handle these failures more gracefully depending on where they happened.
Deal with a `Result` instead of outright panicking

chore(`forge`): handle fork instantiating failures more gracefully

---

.github/workflows/dependencies.yml

Runs `cargo update` and submits a PR for just `Cargo.lock`.
Example:
- danipopes/test-update#1

ci: add weekly cargo update workflow

---

CHANGELOG.md
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Json.t.sol

Right now following code will return `uint256(32)`: `abi.decode(vm.parseJson('{"a": 1}', '.b'), (uint256))` while expected behavior would be for it to revert because `vm.parseJson('{"a": 1}', '.b')` should result in `bytes("")`
But, in fact, it results in `0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000 == abi.encode(bytes(""))`
Add processing of edge case when there are no json tokens corresponding to given path

Add correct processing for non-existent json-keys

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs

GasTooHigh errors were too opaque and I could not tell what was generating the GasTooHigh error.
Made the GasTooHigh variant a struct with a string that could carry details.

Pass details on GasTooHigh

---

cli/assets/generated/TestTemplate.t.sol
cli/src/cmd/forge/generate/mod.rs
cli/src/cmd/forge/mod.rs
cli/src/forge.rs
cli/src/opts/forge.rs

> [!NOTE]  
> I have exactly 3 days of Rust experience. So I had to wing this PR. Please excuse if I have missed any obvious expectations. BTW rust blown away by the rust compiler :exploding_head: 
Creating test file typically involves repeated, verbose steps. This PR introduces a new forge sub command to help scaffold generation of test file - one of many features discussed in detail in this issue: #5466 
A new forge sub command has been introduced `forge generate test --contract-name <CONTRACT_NAME>`. For a given contract it does the following:
- Creates the test file in `tests` directory.
- Adds the necessary imports.
- Adds setup code for the test contract.
A sub command called generate has intentionally been added to accommodate  more potential scaffolds in the future - like …

feat(`forge`) - Test scaffolding

---

evm/src/executor/inspector/cheatcodes/env.rs

Closes #5515 . This problem (`tx.origin` not being updated correctly after doing `vm.prank` after a `vm.startPrank`) is introduced in part due to https://github.com/foundry-rs/foundry/pull/4884 — we now have certain rules to override pranks that weren't explicit enough in the code. You should probably not be able to call `vm.prank` after a `vm.startPrank`, as `vm.startPrank` is "multi-use" and must be stopped, while `vm.prank` is "single use", and one should not overlap the other, as you can use `vm.startPrank` again after having used the first startPrank. This is made a little confusing as we don't have a `changePrank` cheatcode, but rather re-use `vm.startPrank` for this.
We could probably make a case for allowing this, but this feels like a hard-to-explain possible footgun and I'd …

fix(`cheatcodes`): disallow using `vm.prank` after `vm.startPrank`

---

anvil/src/eth/backend/mem/mod.rs
cli/src/cmd/cast/run.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/cmd.rs
cli/src/cmd/forge/script/executor.rs
evm/src/trace/decoder.rs
forge/src/gas_report.rs

When `cast run` targets the transaction that has a preceding reverted transaction within the same block, execution fails.  
The behavior can be reproduced by running:
```
cast run 0x2c00ce3c21741b75477258190a822d8c358c8584e3eef42426bf06f26e5840de --rpc-url $SEPOLIA_URL
```
Skip the reverted transactions without propagating the error.

fix(cast): continue execution after preceding reverted transaction

---

anvil/src/eth/backend/mem/inspector.rs
evm/src/executor/inspector/mod.rs
evm/src/executor/inspector/stack.rs

To make the source code clearer, and searching for places where the code is touching the log inspector vs the collected logs, and to make the naming more consistent with its brethren (like "tracer"), I've renamed the struct members in InspectorStack and Inspector from logs to logger.
Symbol name change.

logs member name changed to logger when referring to LogCollector inspector

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs

Fixes https://github.com/foundry-rs/foundry/issues/5485
Removed `is_eip1559` flag from `transaction_build` fn

chore: removed `is_eip1559` boolean flag

---

cli/src/cmd/forge/build/core.rs
cli/src/cmd/forge/script/build.rs
cli/tests/it/config.rs
config/src/providers/remappings.rs

Right now we have an issue where remappings are being set even if they're optional—which blows up the whole input, and creates problems for _nested_ contexts, which we yet can't really handle. There's also bad deduping happening as we're not taking contexts into account.
Do not set contexts by default which resolves #5475.
Also dedupe and sort remappings correctly, which resolves #5447.

fix(`forge`): Dedup remappings on build correctly & do not set context by default

---

abi/abi/HEVM.sol
abi/src/bindings/hevm.rs
evm/src/executor/inspector/cheatcodes/ext.rs
testdata/cheats/Sleep.t.sol
testdata/cheats/Vm.sol

Closes #4848
Uses `std::thread::sleep(sleep_duration);` to suspend execution of the thread for the specified duration.
It was not straightforward to test this feature. I used vm.ffi() to get time before and after to calculate duration, but OS X `date` command does not support nanosecond precision, so the testing is somehow limited. Not sure at all about behaviour on windows. However this only affects the tests and the implementation should be sound across platforms.

feat(forge): Implement vm.Sleep

---

utils/src/lib.rs

Closes #5396 
The problem here is that versioned linking introduces a problem when the same artifact is compiled with several compiler. versions: Its identifier will have the compiler version appended, e.g `contracts/libraries/SafeDecimalMath.sol:SafeDecimalMath.0.8.21` . In this case, the identifier we were using won't match, as we're not appending the version used.
We need to make sure to use the _requested_ compiler version instead of using the incorrect one when linking. Therefore, we'll track the version used to compile the dep in the `ArtifactDependency` struct, to later append it and use it if the naked identifier can't be found

fix(`linker`): Use correct compiler version appended when there are multiple

---

cli/src/cmd/forge/build/core.rs
cli/tests/it/config.rs
config/src/lib.rs
config/src/providers/mod.rs
config/src/providers/remappings.rs

Closes #5540 
As discussed in the issue, we were doing two things wrong:
- Sorting (therefore losing all priority)
- Inserting remappings that might conflict with other remappings that might not be "closer" but are higher priority.
We now do not sort, and only insert if the remapping name has not been seen before.

fix(`remappings`): Only append new lower-priority remappings if they do not exist

---

anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/mem/mod.rs

regression in #5534 where type was removed
this changes the if condition by add a is_dynamic_fee and not resetting the tx type in the else branch
cc @DaniPopes

fix: add is dynamic fee fn

---

config/src/lib.rs

Want to reuse config helper methods that return ethers_solc objects in https://github.com/parmanuxyz/solidity-analyzer/issues/12. Re-exporting will allow me to use it without having different crate version error.
I don't think this should be a problem to re-export? If it is let me know.

chore: re-export ethers-solc from foundry-config

---

Cargo.lock
cast/Cargo.toml
cast/src/lib.rs

Stabilized in 1.59.
Replace `num_cpus` with [`std::thread::available_parallelism`](https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html)

chore: use standard `available_parallelism`

---

Cargo.lock
Cargo.toml
anvil/src/eth/backend/mem/inspector.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
evm/src/executor/backend/in_memory_db.rs
evm/src/executor/backend/mod.rs
evm/src/executor/backend/snapshot.rs
evm/src/executor/fork/cache.rs
evm/src/executor/fork/database.rs
evm/src/executor/inspector/access_list.rs
evm/src/executor/inspector/cheatcodes/mapping.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/chisel_state.rs
evm/src/executor/inspector/coverage.rs
evm/src/executor/inspector/debugger.rs
evm/src/executor/inspector/fuzzer.rs
evm/src/executor/inspector/logs.rs
evm/src/executor/inspector/printer.rs
evm/src/executor/inspector/stack.rs
evm/src/executor/inspector/tracer.rs
evm/src/executor/mod.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/strategies/state.rs
evm/src/lib.rs

feat(`deps`): upgrade to use latest `revm`

---

evm/src/fuzz/invariant/error.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/invariant/mod.rs
forge/src/runner.rs

Closes #4951 
Adds support for console logs on invariant handlers, by persisting the logs and traces for the last call.
To avoid any performance regressions we only move values and only copy where absolutely necessary (filling each invariant with the corresponding logs at the end), and only persist the call values at the end of each run campaign, as they would just be overwriting values persisted at the stack otherwise.

feat(`forge`): support for `console.log` on Invariant handlers

---

cli/src/cmd/forge/script/broadcast.rs
cli/src/cmd/forge/script/mod.rs

Currently, the estimated `ETH_PRIORITY_GAS_PRICE` used by `forge script` is unnecessarily large on L2's such as Optimism and Arbitrum. Resolves #5281
This PR adds an argument to manually set the priority gas price for forge script and uses that price if it is provided. 
[Additional context](https://github.com/foundry-rs/foundry/issues/5281#issuecomment-1673019379)

feat(forge): Add `--priority-gas-price` argument for `forge script`

---

cli/src/cmd/forge/script/mod.rs

feat(`scripts`): add flag to skip interactivity

---

Cargo.lock
Cargo.toml
anvil/src/genesis.rs
evm/src/executor/fork/cache.rs
evm/src/executor/inspector/coverage.rs
evm/src/fuzz/strategies/param.rs

chore(deps): bump revm

---

config/README.md

Some env variables are explicitly ignored, but the README suggests they all should work

Clarifies readme regarding ignored env variables

---

Cargo.lock
Cargo.toml
cast/Cargo.toml
cast/src/lib.rs
cli/Cargo.toml
cli/src/cast.rs
cli/src/cmd/forge/create.rs
cli/src/cmd/forge/verify/etherscan/mod.rs
evm/Cargo.toml
evm/src/executor/inspector/cheatcodes/ext.rs
forge/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml

[`const-hex`](https://github.com/DaniPopes/const-hex)

perf: replace `rustc-hex` and `hex` with `const-hex`

---

cli/src/cmd/cast/wallet/mod.rs
cli/src/opts/wallet/mod.rs
cli/src/opts/wallet/multi_wallet.rs

missing docs for #5551 
Improved and added missing docs

docs: cast wallet import

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/error.rs
crates/anvil/src/genesis.rs
crates/evm/src/executor/backend/mod.rs
crates/evm/src/executor/fork/cache.rs
crates/evm/src/executor/inspector/access_list.rs
crates/evm/src/executor/inspector/cheatcodes/mapping.rs
crates/evm/src/executor/inspector/cheatcodes/mod.rs
crates/evm/src/executor/inspector/chisel_state.rs
crates/evm/src/executor/inspector/coverage.rs
crates/evm/src/executor/inspector/debugger.rs
crates/evm/src/executor/inspector/fuzzer.rs
crates/evm/src/executor/inspector/logs.rs
crates/evm/src/executor/inspector/printer.rs
crates/evm/src/executor/inspector/stack.rs
crates/evm/src/executor/inspector/tracer.rs
crates/evm/src/fuzz/strategies/state.rs

For some reason the revm upgrade broke a lot of stuff that shouldn't have been broken considering the migration was mostly transparent, and we've yet to triage the entirety of the issue.
Revert back to `release/25` as a stable revm version. The current branch with latest revm changes is now `latest-revm`.

fix(`evm`): revert all revm changes

---

README.md

After https://github.com/foundry-rs/foundry/pull/5597 was merged, there are certain links in the readme which point to the wrong location. Just looking to leave things cleaner than how I found them :)
Fixed links

fix: readme fix after crates move

---

crates/cli/assets/CounterTemplate.t.sol
crates/cli/tests/fixtures/can_test_repeatedly.stdout
crates/config/src/inline/natspec.rs

Currently, the test names in `Counter.t.sol` do not adhere to the style guide in [Best Practices](https://book.getfoundry.sh/tutorials/best-practices#tests).
These have been updated to conform to the style guide accordingly. Resolves #5618

chore: update `CounterTemplate.t.sol` to adhere to best practices

---

crates/config/src/lib.rs

Apparently the structure of the repo changed a bit but this link hasn't been updated.
Update the link :-)

fix(`config`): init foundry.toml url

---

crates/config/src/lib.rs

Updated the link displayed in the default `foundry.toml` file, as the existing one seems to be outdated (`https://github.com/foundry-rs/foundry/tree/master/config`)

Updated link to all config options example file

---

crates/anvil/README.md
crates/chisel/README.md
crates/cli/README.md

When looking https://github.com/foundry-rs/foundry/blob/5f2262736feaeabadeef2ae989a78e9b43da8eee/crates/anvil/README.md#installation, the `foundryup` link didn't work. Because the link was broken since https://github.com/foundry-rs/foundry/pull/5597.
I just fixed those links 🔨

docs: correct `README.md` link path

---

foundryup/foundryup

Local paths are broken, should not use them

chore: update foundryup

---

Cargo.toml
crates/cast/bin/cmd/create2.rs
crates/forge/tests/cli/test_cmd.rs

Unit tests are held hostage for 30s+ by a single keystore test because the key derivation crate is not optimized, and some create2 tests
Forge tests spend a lot of time cloning the compiler output, something to take note of (`(*COMPILED).clone()`) cc @Evalir

test: speed up some tests

---

.github/workflows/heavy-integration.yml
crates/forge/tests/cli/heavy_integration.rs

The current heavy integration tests workflow fails because the maple repo is just damn huge, and takes almost an hour to run. Combined with other tests that are matching the current filter that also clog the CI, it makes the whole job fail because it takes longer than an hour and github automatically disconnects it, not even allowing an issue to be created.
prefix all heavy integration tests (only maple atm) with `heavy`, and filter this with nextest.

fix(`tests`): only run heavy integration tests on workflow by tightening filters

---

crates/abi/abi/HEVM.sol
crates/abi/src/bindings/hevm.rs
crates/evm/src/executor/inspector/cheatcodes/ext.rs
crates/forge/tests/it/cheats.rs
testdata/cheats/TryFfi.sol
testdata/cheats/Vm.sol

Closes https://github.com/foundry-rs/foundry/issues/2932 .
Rebase & reimpl of #4908, as the rebase was a bit cumbersome.

feat(`cheatcodes`): tryFfi (rebased)

---

foundryup/foundryup

Fixes #5658
Actually tested now

fix(foundryup): check if file exists before moving

---

crates/abi/abi/HEVM.sol

Doing this to conform to solidity standards.

chore(`cheatcodes`): fix `FfiResult` field name with correct casing

---

.github/workflows/test.yml

Windows moment: <https://github.com/foundry-rs/foundry/actions/runs/5907015101/job/16024199431>

ci: explicitly set bash as shell

---

.github/workflows/heavy-integration.yml
.github/workflows/test.yml

Missing from recent CI changes
Add them

fix(`ci`): force using http for submodules & setup git config on heavy integration tests

---

.github/workflows/heavy-integration.yml
.github/workflows/release.yml

<https://github.com/foundry-rs/foundry/actions/runs/5908203456>
This workflow failed but didn't open any issues because it's only a step in the `release` job. The same would happen if the `release` job timed out which makes it not reach the final steps.
Make them separate jobs.

ci: open an issue if any release job fails

---

crates/forge/tests/cli/config.rs
crates/forge/tests/it/invariant.rs

- <https://github.com/foundry-rs/foundry/actions/runs/5907890144/job/16026701137>
- <https://github.com/foundry-rs/foundry/actions/runs/5907890144/job/16026701222>

test: fix some windows tests

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

`echo "::set-output name=(\w+)::(.*)"` -> `echo "$1=$2" >> "$GITHUB_OUTPUT"`

ci: fix deprecation warnings

---

Cargo.toml
crates/cli/src/utils/cmd.rs
crates/evm/src/fuzz/invariant/error.rs
crates/evm/src/fuzz/invariant/executor.rs
crates/evm/src/trace/decoder.rs
crates/forge/src/runner.rs

Also cache `CallTraceDecoder` initializer since it's pretty expensive

perf: tweak optimizations again

---

crates/evm/src/executor/inspector/cheatcodes/mod.rs
crates/evm/src/fuzz/invariant/error.rs
crates/evm/src/fuzz/invariant/executor.rs
crates/evm/src/fuzz/invariant/mod.rs
crates/evm/src/fuzz/mod.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs

Most of the invariant code is written as if it handles multiple functions per call (e.g. argument is `&[Function]` instead of `&Function` etc.).
This is fine, except we call these functions with `vec![function]` in a loop over the functions...
Recommended to review with "Hide whitespace" since this gets rid of a lot of indentation
Rewrite invariants to run one function at a time, and parallelize the top level loop

refactor: parallelize invariants

---

.github/workflows/heavy-integration.yml
.github/workflows/release.yml

They obviously need the `needs` to run after

ci: fix issue jobs (again)

---

crates/chisel/src/dispatcher.rs
crates/cli/src/utils/cmd.rs
crates/evm/src/trace/decoder.rs
crates/evm/src/trace/identifier/etherscan.rs
crates/evm/src/trace/identifier/local.rs
crates/evm/src/trace/identifier/mod.rs
crates/evm/src/trace/mod.rs
crates/evm/src/trace/utils.rs
crates/forge/bin/cmd/script/mod.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/src/result.rs

~~Identifying and decoding traces contributes the majority (usually >40%) of the time spent in running tests. We can avoid most of this by just using the existing check flags to skip identifying only when needed.~~
My assumptions were wrong. Generally, we decode traces on the main thread in parallel to the threads executing tests. This is a problem when there are a lot of them, and are sent batched (like for invariants). This causes the main thread to block for a while just decoding traces, which may also block after all tests are done.
This PR cleans up some tracing code, but the issue mentioned above will have to be fixed in another PR.

perf: optimize trace identifiers

---

Cargo.lock
crates/config/src/inline/conf_parser.rs
crates/config/src/inline/natspec.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/src/lib.rs
crates/forge/tests/it/inline.rs

Cloning = slow
Cloning compiler output (TWICE) = incredibly slow
Please do not do this :)
We're talking 150ms for a `forge init` project, going into the seconds PER CLONE for big projects.
Benchmarked with `AMD Ryzen 9 5900X (24) @ 3.700GHz`
Don't clone

chore: avoid cloning `CompileOutput` to parse inline config

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/error.rs
crates/anvil/src/genesis.rs
crates/evm/src/executor/backend/mod.rs
crates/evm/src/executor/fork/cache.rs
crates/evm/src/executor/inspector/access_list.rs
crates/evm/src/executor/inspector/cheatcodes/mapping.rs
crates/evm/src/executor/inspector/cheatcodes/mod.rs
crates/evm/src/executor/inspector/chisel_state.rs
crates/evm/src/executor/inspector/coverage.rs
crates/evm/src/executor/inspector/debugger.rs
crates/evm/src/executor/inspector/fuzzer.rs
crates/evm/src/executor/inspector/logs.rs
crates/evm/src/executor/inspector/printer.rs
crates/evm/src/executor/inspector/stack.rs
crates/evm/src/executor/inspector/tracer.rs
crates/evm/src/fuzz/strategies/state.rs
crates/forge/tests/cli/coverage.rs
crates/forge/tests/cli/main.rs

- revert efedf1f9e8323bdb1c0fcf0ce728115d0a4a92f4 (#5669)
- add a basic `forge coverage` test

Revert "feat(evm): Use latest revm main commit (#5669)"

---

crates/cast/bin/opts.rs

Quite a few commits ago it seems we removed support from `--from-utf8` as alias, and this was in the book. While the book has been updated, don't see why this shouldn't be supported
add back

chore(`cast`): re-add --from-utf8 as alias from book

---

.github/workflows/deny.yml
deny.toml

Should stop CI erroring for now—we've yet to transition to using the maintained rust AWS SDK which would allow us to remove these denys.

fix(`ci`): exclude `rusoto` & `ethers-providers` from `cargo-deny`

---

crates/cast/bin/cmd/create2.rs

Follow up to my previous PR https://github.com/foundry-rs/foundry/pull/5713. While testing I also got another error case with `cast create2 -s x00` which would hangs infinitely as well.
We pass `hex::decode` check because extra 0 is prepended and hex string becomes valid (`0x00`) though it would never be possible to find address starting with `x00`
Instead of prepending extra `0` to the searchable string to check with `hex::decode`, append `0` to the end of the searchable string
```diff
-hex::decode(format!("{s:0>pad_width$}"))?;
+hex::decode(format!("{s:0<pad_width$}"))?;
```
Added relevant tests

Append extra 0 to prefix/suffix in cast create2 to avoid getting wrong hex strings

---

crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/cheats.rs
crates/anvil/tests/it/anvil_api.rs

Fix for https://github.com/foundry-rs/foundry/issues/5732 (see that issue for detailed context).
Added `CheatsManager::impersonated_accounts()` to allow fetching impersonated accounts from `EthApi`.
Collected relevant addresses in `EthApi::accounts()` into a `HashSet` to avoid returning duplicate accounts when a user tries to impersonate an account that is already owned by the node.
Extended the `can_impersonate_account` unit test to assert that the impersonated account gets returned by the `eth_accounts` handler.

Make eth_accounts return impersonated accounts

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/fixtures/can_check_snapshot.stdout
crates/forge/tests/fixtures/can_run_test_in_custom_test_folder.stdout
crates/forge/tests/fixtures/can_test_repeatedly.stdout
crates/forge/tests/fixtures/can_use_libs_in_multi_fork.stdout
crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout

Currently, the test result summary doesn't differentiate between the failed, passed and skipped tests visually. So it would be nice to have colored test summary similar to Hardhat. 
Also redundant summary is printed if any of the tests fail. It is no longer required as we already print aggregated test summary by default (Issue #5195).
Used red, green and blue colors in test summary for the no.of failed, passed and skipped tests respectively. 
Also removed the redundant test summary output.

⚡ Improve test summary formatting
