anvil/core/src/eth/mod.rs

Ref #4144 add alias for existing `anvil_setNonce`

feat(anvil): add evm_setAccountNonce alias

---

anvil/src/config.rs

#4157 
- Changed account addresses in start up log to checksummed with ethers::core::utils::to_checksum.

Anvil: Checksum address output in start-up log

---

utils/src/rpc.rs

rm key that's no longer working

chore: rm broken infura key

---

cli/src/cmd/forge/snapshot.rs

Closes #4127
sort snapshot reports by default

chore(forge): sort snapshot report

---

chisel/src/session_source.rs

seems to be failing on aarch64
show result in fail message.

chore(chisel): show version result on error

---

anvil/src/eth/backend/mem/storage.rs

the previous limits were too strict for low intervals

chore: more sensible default limits

---

anvil/src/eth/backend/mem/storage.rs

on clear remove all snapshots that are on disk

fix(anvil): rm disk states on clear

---

Cargo.lock
cli/Cargo.toml

- toml 0.5 -> 0.7.0
- serial_test 0.9.0 -> 1.0.0
Detected by - [Crates VSCode Plugin](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates)
`foundry/cli/Cargo.toml` - Update Crates

Crates Update - Prompted by Crates Vscode Extension

---

cli/src/cmd/cast/call.rs
cli/src/cmd/cast/estimate.rs

close #4227
Retrieve sender from any provided wallet-related cli flag.

fix(cast): estimate and call sender options

---

cli/src/cmd/forge/install.rs
cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr

#4223
> I feel like this is in the top 5 questions asked in the telegram chat, so tried to add even more information to the error message

docs(forge): improve `ensure_git_status_clean` error message

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/lib.rs
cli/src/opts/cast.rs
cli/src/stdin.rs

Some Cast subcommands are missing `stdin` fallback when a value is not provided

feat(cast): extend stdin support

---

foundryup/foundryup

1. Fix [shellcheck](https://www.shellcheck.net/) lints
2. Refactor repetition with binaries
3. Improve "which ~= cargo" to include any other binary with the same name, given that there may be other software with the same name as the foundry binaries (like forge as seen in <https://t.me/foundry_support/31448>)

chore(foundryup): fix shellcheck lints

---

cli/src/cmd/forge/script/cmd.rs
cli/src/forge.rs

Closes #4253
fixes regression after #4253

fix: install shell only once

---

Cargo.lock
anvil/src/eth/api.rs
anvil/src/eth/backend/fork.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/backend/mem/storage.rs
anvil/tests/it/traces.rs
cli/tests/it/svm.rs
evm/src/trace/mod.rs

chore(deps): bump ethers with svm 0.8.18 support

---

Cargo.lock
chisel/Cargo.toml
chisel/src/executor.rs

synchronize when solc is installed.

test: synchronize solc installation in test

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/opts/cast.rs

Closes #4123
Add "type" positional arg to `cast {--max-int,min-int,--max-uint}`
Calculate min and max values using the given type and bit size

feat(cast): arbitrary min/max int/uint

---

utils/src/rpc.rs

chore: key maintenance

---

README.md

Readme missing brief description of Chisel Tool
Edit README.MD

fix(readme): add chisel

---

cast/src/lib.rs
cli/src/cast.rs
cli/src/cmd/cast/bind.rs
cli/src/cmd/cast/interface.rs
cli/src/cmd/cast/mod.rs
cli/src/opts/cast.rs
cli/src/opts/chain.rs

Cast Command to generate ethers-rs binding
Fixes #4132

Cast Command to generate ethersrs binding

---

utils/src/lib.rs

this fixes the linking limitation that prevented multi version builds from working.
With this change we also consider the version when matching artifacts.
Note: this code is a bit horrible but it would require a total rewrite to make it nice, apologies in advance.
it was tested against the referenced issue.
Closes https://github.com/foundry-rs/foundry/issues/4320

fix: support versioned linking

---

cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout
cli/tests/fixtures/can_test_repeatedly.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout

discovered here https://github.com/foundry-rs/foundry/pull/4354

chore: update fixtures for forge-std 1.4

---

anvil/core/src/eth/transaction/ethers_compat.rs
anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/api.rs

Closes #4365 
adds missing `chain_id` field to request type, ref https://ethereum.github.io/execution-apis/api-documentation/
cc @michprev

fix(anvil): add chain id field

---

fmt/src/formatter.rs
fmt/testdata/FunctionCall/bracket-spacing.fmt.sol
fmt/testdata/FunctionCall/original.sol
fmt/testdata/FunctionCallArgsStatement/fmt.sol

Closes #4020 
@PaulRBerg can you confirm this is working as expected?

fix(fmt): respect bracket spacing in named function call

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs
anvil/tests/it/transaction.rs

Closes #4386
ensures current hardfork supports typed transactions.
add check to eth_sendRawTransaction.
wdyt @michprev

fix(anvil): ensure typed tx supported based on hardfork

---

anvil/src/eth/backend/mem/mod.rs

improve error messages ref https://github.com/foundry-rs/foundry/issues/4388
wdyt @PhilippLgh

chore(anvil): improve error logs

---

Cargo.lock
cli/src/cmd/forge/fmt.rs
fmt/Cargo.toml
fmt/src/helpers.rs
fmt/src/lib.rs

Ref #4403 
Print parser diagnostics report.
Before:
After:

feat(fmt): diagnostics report

---

common/src/evm.rs

ref https://github.com/foundry-rs/foundry/issues/4409
add --memory-limit to cli args

feat: add --memory-limit to env args

---

README.md

Feature added  : recommended to install WSL for Windows users
Fixes #4262

 recommended to install WSL 2

---

cli/src/opts/wallet/multi_wallet.rs

Add trace for debugging
ref https://github.com/foundry-rs/foundry/issues/4362

chor: add ledger trace

---

Cargo.lock
anvil/tests/it/abi.rs
anvil/tests/it/geth.rs
anvil/tests/it/main.rs
anvil/tests/it/revert.rs
cli/Cargo.toml
cli/tests/it/svm.rs

Closes #4412
add 0.8.19 support
~~blocked by https://github.com/gakonst/ethers-rs/pull/2179~~
blocked by https://github.com/roynalnaruto/svm-rs/pull/76

chore: bump svm-rs with 0.8.19

---

README.md

PR adding to the README the instructions to install chisel via cargo.

chore(README): add chisel install instructions

---

config/src/lib.rs

add test with empty optimizerdetails

test: add optimizer details test

---

config/src/lib.rs

only configure optimizer details if optimizer is enabled.

fix: disable optimizer details if optimizer is disabled

---

fmt/src/formatter.rs
fmt/testdata/EmitStatement/fmt.sol
fmt/testdata/EmitStatement/original.sol

fix(fmt): emit stmt grouping

---

anvil/src/eth/backend/db.rs
anvil/src/eth/backend/mem/fork_db.rs
anvil/src/eth/backend/mem/in_memory_db.rs

actually impl `loadState` for memdb
likely related to https://github.com/foundry-rs/foundry/issues/4173

fix(anvil): apply load state in memdb

---

anvil/core/src/eth/transaction/ethers_compat.rs
anvil/core/src/eth/transaction/mod.rs
anvil/src/eth/backend/mem/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/4428
set transaction_type in receipt
@DaniPopes

fix(anvil): set transaction type in receipt

---

Cargo.lock

chore: bump clap

---

cli/tests/fixtures/can_create_template_contract.stdout
cli/tests/fixtures/can_create_using_unlocked.stdout
cli/tests/fixtures/can_use_libs_in_multi_fork.stdout

test: update test fixture

---

anvil/src/eth/api.rs

return correct gas, discovered while porting to reth

fix(anvil): return correct gas

---

chisel/src/executor.rs

ref https://github.com/foundry-rs/foundry/issues/4481
convert panics into errors

chore(chisel): turn panics into errors

---

Cargo.lock
chisel/Cargo.toml
chisel/benches/session_source.rs
cli/benches/cast.rs
cli/src/cmd/cast/wallet/vanity.rs
cli/src/cmd/forge/build/mod.rs

- minor updates to cast benches
- add Forge build standalone bench, update to use Args instead of external binary
- Chisel benches were simply not running because the actual code was wrapped in functions or futures and not executed. CC @clabby:

chore: update benches

---

cli/src/cmd/forge/verify/mod.rs
config/src/chain.rs
config/src/etherscan.rs
config/src/lib.rs

Fixes #4484
Etherscan config was not being resolved in `get_etherscan_config_with_chain`

fix(config): Etherscan config resolution

---

cli/src/cmd/utils.rs
config/src/error.rs
config/src/lib.rs

Closes https://github.com/foundry-rs/foundry/issues/4520#issuecomment-1464360492
the figment error was not mapped correctly.
improved error:
> failed to extract foundry config:
foundry.toml error: unexpected character found: `;` at line 5 column 16 in foundry.toml TOML file

fix(config): use ExtractConfig Error

---

chisel/src/executor.rs
chisel/src/session_source.rs

on some CI targets install is a bit flaky.
retry 3 times until succeeds

test(chisel): retry install attempts

---

cli/tests/it/utils.rs

add sepolia env settings to kick off transition to sepolia

chore: add sepolia env settings

---

cli/tests/it/utils.rs
cli/tests/it/verify.rs

print address we're verifying from in CI so we know immediately what to fund when out of funds

test: print verify source address

---

anvil/src/eth/api.rs

Closes https://github.com/foundry-rs/foundry/issues/4436
we already had this but didn't enable it.

feat(anvil): enable max priority fee per gas

---

forge/tests/it/invariant.rs

test: ignore flaky test on windows

---

doc/src/parser/item.rs

Closes https://github.com/foundry-rs/foundry/issues/4536
check what kind of contract def it is

fix(doc): distinguish contract interface library

---

chisel/src/bin/chisel.rs
chisel/src/dispatcher.rs
chisel/src/solidity_helper.rs

Closes #4503
Refs https://github.com/kkawakam/rustyline/pull/215
Move syntax highlighting to `SolidityHelper`

fix(chisel): Windows prompt

---

anvil/tests/it/fork.rs

test(anvil): use retryprovider

---

cli/src/cmd/forge/install.rs

Currently adding a submodule with forge install using a tagged release assumes a matching branch exists, which isn't always true.
Only add the branch specifier to .gitmodules if the branch actually exists

When adding submodules, check if the branch exists before setting on the submodule

---

cli/src/opts/wallet/mod.rs
cli/tests/it/cast.rs

Closes #4629
fixes a regression introduced in f5e5eb52f62928c5b4daeec0fe963ad7f88cb464

fix(cast): cast wallet keystore regression

---

evm/src/executor/abi/mod.rs
evm/src/executor/inspector/cheatcodes/env.rs

Closes #4581
@luketchang should we name this `txGasPrice`?
do you want to add this to forge-std once merged?

feat: add gasprice cheatcode

---

cast/src/lib.rs

chore: remove unwrap

---

evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/util.rs
forge/src/multi_runner.rs

vecs of length 1 with `is_array` false to something that is more idiomatic

refactor(evm): parse cheatcodes

---

evm/src/executor/backend/mod.rs
forge/tests/it/repros.rs
testdata/repros/Issue4586.t.sol

Closes #4586
Ensure the new journalstate includes all accounts.

fix(evm): clone current journaled state if active

---

forge/src/lib.rs
forge/src/runner.rs

make sure the correct fuzz config is used, and not default
ref https://github.com/foundry-rs/foundry/pull/4627

fix: use fuzz config as configured

---

config/src/fuzz.rs
config/src/utils.rs
forge/src/runner.rs

support using:
```
[profile.test-optimized.fuzz]
max_fuzz_dictionary_addresses = "max"
max_fuzz_dictionary_values = "max"
```

feat: support max literal

---

.github/workflows/docker-publish.yml

Closes https://github.com/foundry-rs/foundry/issues/4685
add cron job for `docker-publish`

feat: cron docker-publish

---

Cargo.lock
Cargo.toml

As discussed on Discord with @gakonst @mattsse

Pin ethers-rs version to 2

---

anvil/src/cmd.rs

chore: add anvil --block-gas-limit alias

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/backend/cheats.rs
anvil/src/eth/backend/mem/mod.rs

See issue #4609 
Implement a function to automatically impersonate every account, basically just returning true when the cheat class is asked if an account is impersonated when this feature flag is set to true.

feat: Auto Impersonation

---

anvil/src/eth/api.rs
anvil/src/eth/backend/cheats.rs
anvil/tests/it/anvil_api.rs

test(anvil): add auto impersonate test

---

anvil/core/src/eth/mod.rs

went unnoticed because tests require serde feature...

test: fix failing anvil test

---

cli/src/cmd/forge/geiger/find.rs
cli/src/cmd/forge/geiger/mod.rs
cli/src/cmd/forge/geiger/visitor.rs
cli/src/forge.rs

The `--check` didn't actually do anything for what I could see.
Exit with the error code set to the number of unsafe cheatcodes found if `--check` is set.
Refactor a bit

fix(forge): update forge geiger

---

cli/src/cmd/forge/remove.rs
cli/src/opts/dependency.rs

- Calling `rm` command...
- Use `git rm path/to/submodule`. See: <https://stackoverflow.com/a/1260982>

fix(forge): update forge remove

---

cli/src/opts/wallet/mod.rs

style: replace macro with closure

---

.github/workflows/live-test.yml
evm/src/executor/fork/backend.rs
testdata/repros/Issue2956.t.sol
testdata/repros/Issue3221.sol
testdata/repros/Issue3223.sol
testdata/repros/Issue3674.t.sol

new infura keys, infura also has outages currently.

chore: replace infura keys

---

README.md
foundryup/foundryup

We are already providing pre-compiled binaries for Windows, and foundryup supports Windows for local and git installs.
I've seen this asked a bit on telegram and looking into it there seems to be nothing stopping adding support for it.

feat(foundryup): add support for MINGW

---

README.md

Move installation guide to the book. Less docs to maintain in sync here. 
Refs: #4847, foundry-rs/book#882

docs: move README's installation and troubleshooting sections to the book

---

cli/src/cmd/cast/access_list.rs

the code is duplicate.
remove the duplicate code.

chore(cast): cleanup code in access-list

---

cli/src/cmd/forge/test/mod.rs
forge/src/multi_runner.rs

- fixes: https://github.com/foundry-rs/foundry/issues/4304
- flag added under ```Test filtering:```
```bash
--allow-failure
Exit with code 0 even if a test fails
[env: FORGE_ALLOW_FAILURE=]
--fail-fast
Stops running tests after the first failure
```
- tested with solmate 
```bash
[⠆] Compiling...
Running 4 tests for src/test/MerkleProofLib.t.sol:MerkleProofLibTest
[PASS] testValidProofSupplied() (gas: 2153)
[PASS] testVerifyEmptyMerkleProofSuppliedLeafAndRootDifferent() (gas: 1458)
[PASS] testVerifyEmptyMerkleProofSuppliedLeafAndRootSame() (gas: 1452)
[PASS] testVerifyInvalidProofSupplied() (gas: 2172)
Test result: ok. 4 passed; 0 failed; finished in 223.96µs
Running 2 tests for src/test/Bytes32AddressLib.t.sol:Bytes32AddressLibTest
[PASS] …
```

Bail after test fail

---

anvil/src/eth/api.rs
anvil/src/eth/backend/mem/mod.rs
anvil/src/eth/error.rs

Reth has some nice conversions implemented for REVM that we can leverage, mainly to remove the `FatalExternalError`s introduced due to the revm 3.0 migration. We also should, over time, try to port as much from reth as we can, and this brings the relevant error nomenclature over.
[Ports `InvalidTransactionError` from Reth](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/error.rs#L16), along with the [`EVMError`](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/error.rs#L94-L105) & revm's [`InvalidTransaction`](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/error.rs#L246-L274) conversions.
@0xmelkor as always, feel free to review!

chore(evm): Bring over Reth's `InvalidTransaction`-related conversions

---

cli/src/cmd/cast/wallet/mod.rs

fix(cast): cast wallet verify can be made to parse hex string

fix(cast): cast wallet verify can be made to parse hex string

---

evm/src/executor/fork/init.rs

fix: ensure prevrandao is set

---

docs/dev/cheatcodes.md

There are few typos in doc. And the function signature of `Inspector::call` is not matching with upstream signature.
fix it :)

fix(docs): minor typos and updates

---

evm/src/coverage/analysis.rs
evm/src/coverage/anchors.rs
evm/src/executor/backend/fuzz.rs
evm/src/executor/backend/mod.rs
evm/src/executor/fork/backend.rs
evm/src/executor/fork/cache.rs
evm/src/executor/fork/database.rs
evm/src/executor/fork/multi.rs
evm/src/executor/inspector/cheatcodes/config.rs
evm/src/executor/inspector/cheatcodes/env.rs
evm/src/executor/inspector/cheatcodes/error.rs
evm/src/executor/inspector/cheatcodes/expect.rs
evm/src/executor/inspector/cheatcodes/ext.rs
evm/src/executor/inspector/cheatcodes/fork.rs
evm/src/executor/inspector/cheatcodes/fs.rs
evm/src/executor/inspector/cheatcodes/fuzz.rs
evm/src/executor/inspector/cheatcodes/mod.rs
evm/src/executor/inspector/cheatcodes/snapshot.rs
evm/src/executor/inspector/cheatcodes/util.rs
evm/src/executor/mod.rs
evm/src/executor/opts.rs
evm/src/fuzz/invariant/error.rs
evm/src/fuzz/invariant/executor.rs
evm/src/fuzz/mod.rs
evm/src/fuzz/strategies/calldata.rs
evm/src/fuzz/strategies/invariants.rs
evm/src/lib.rs
evm/src/trace/identifier/etherscan.rs
evm/src/trace/identifier/signatures.rs

Not enough debug info.
Refs #4940 
- `#[macro_use] extern crate tracing`
- `err!` -> `fmt_err!` due to similar names with tracing's `error!`
- `#[instrument]` all `apply` fns

feat: better cheatcodes tracing

---

CHANGELOG.md

Missing addition to changelog from #4826

chore(`CHANGELOG.md`): add startPrank changes

---

Cargo.lock
anvil/Cargo.toml
anvil/core/Cargo.toml
anvil/server/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
chisel/Cargo.toml
cli/Cargo.toml
cli/test-utils/Cargo.toml
common/Cargo.toml
config/Cargo.toml
doc/Cargo.toml
doc/src/parser/mod.rs
evm/Cargo.toml
fmt/Cargo.toml
forge/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml
utils/src/lib.rs

anvil:
- trie-db
- hash-db
- memory-db
- axum

chore: bump all dependencies

---

cli/src/opts/cast.rs

docs(cast): clarify type of bytecode

---

evm/src/fuzz/mod.rs

Closes #4778
weight function
> Panics if options is empty or any element has a weight of 0.

fix: prevent dictionary weight panic

---

config/src/fuzz.rs

Closes #4967.
Open question: should we restrict the possible input range? cc @mds1

feat(forge): add support for fuzz dictionary weight config

---

.github/workflows/cross-platform.yml
.github/workflows/docker-publish.yml
.github/workflows/release.yml

The boolean parameters were not used correctly leading to all builds ending up being nightlies, even though they might have been tagged releases.
Also all conditionals were normalized not to use explicit expression syntax since that is not needed.

ci: Fix use of parameter in conditionals

---

Dockerfile

https://t.me/foundry_support/37865

chore: update dockerfile to add chisel and ui binaries

---

cli/tests/it/integration.rs

Adds a few more critical mission repos for external integration tests.

feat(ci): add new repos for integration

---

anvil/src/eth/backend/mem/mod.rs

Fixes: https://github.com/foundry-rs/foundry/issues/3985
- still figuring out how to reproduce the error and test out different errors

fix(anvil): Anvil no reason revert string

---

anvil/src/hardfork.rs

Closes #5058
missing from_str case

fix(anvil): add missing hardfork variants

---

anvil/src/cmd.rs

docs: better hardfork args docs

---

anvil/src/eth/fees.rs

ref #5065
the previous impl used the wrong elasticity value.
this replaces it with reth's base fee calc function

fix: correct base fee calc

---

Cargo.lock
Cargo.toml

patch revm until new release to prevent shanghai maxinit code error.

patch revm release v25

---

Cargo.lock
Cargo.toml

this will finally solve the blockscout verification issues posted so far!

chore(packages): bump ethers

---

foundryup/foundryup

Fixes #5141
> if the colon is included, the operator tests for both parameter’s existence and that its value is not null; if the colon is omitted, the operator tests only for existence.
<https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html>

fix(foundryup): default variable values

---

anvil/Cargo.toml

should close #5115
ipc is supported on windows but we didn't enable it

chore: enable ipc on windows

---

cli/src/cmd/forge/test/mod.rs

Closes #4156.
Adds a `--fuzz-runs` flag to `forge test`.

feat(`forge`): add `--fuzz-runs` flag

---

binder/src/utils.rs

chore(general): fmt

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/doc.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/remove.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/forge/update.rs
cli/src/opts/dependency.rs
cli/src/utils.rs
cli/tests/it/cmd.rs
config/src/lib.rs

This reverts commit 36c76adefb0155ad9b209bb80f21271fdae7404f.
this changed the default install no longer use tags, which is breaking and will cause issues
cc @DaniPopes

Revert "feat(forge): shallow clones (#5204)"

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/cast/wallet/mod.rs
cli/src/cmd/forge/build/mod.rs
cli/src/cmd/forge/coverage.rs
cli/src/cmd/forge/doc.rs
cli/src/cmd/forge/init.rs
cli/src/cmd/forge/install.rs
cli/src/cmd/forge/remove.rs
cli/src/cmd/forge/test/mod.rs
cli/src/cmd/forge/update.rs
cli/src/opts/dependency.rs
cli/src/utils.rs
cli/tests/it/cmd.rs
config/src/lib.rs

See #5204 + d9504882
Restore default behaviour (normal by default + shallow opt-in)

feat(forge): shallow clones (again)

---

cli/src/cmd/forge/install.rs
cli/src/cmd/forge/update.rs
cli/src/utils.rs

fix(forge): update, install fixes

---

config/src/etherscan.rs
config/src/lib.rs

fix: resolve etherscan api url string

---

binder/src/utils.rs
cli/src/cmd/forge/script/build.rs
utils/src/lib.rs

Reopening #5164 for figuring out what's wrong here.

feat: dedupe linker outputs

---

.gitattributes
abi/src/bindings/console.rs
abi/src/bindings/hardhat_console.rs
abi/src/bindings/hevm.rs

chore: update abi bindings and mark them as generated

---

.github/workflows/cross-platform.yml
.github/workflows/deny.yml
.github/workflows/release.yml
.github/workflows/test.yml

ci: update all jobs, split lint jobs

---

anvil/core/src/eth/mod.rs
anvil/src/eth/api.rs
anvil/src/eth/sign.rs

I need `eth_signTransaction` to test txn signing over JSON-RPC. 
Implement `eth_signTransaction`.

feat: `eth_signTransaction`

---

anvil/src/eth/backend/mem/mod.rs

Closes #5336 
this will now handle evm errors and bubble up accordingly

fix(`anvil`): properly handle `EVMError`s on call_with_state

---

evm/src/fuzz/strategies/invariants.rs
evm/src/fuzz/strategies/param.rs

perf: improve some proptest strategies

---

.github/workflows/release.yml

fix(`ci`): properly revert nightly detection

---

Cargo.toml

now that we're back on ethers git the patch section should be changed.
this took me a minute to realize I had to put this under patch.http
updating this for future use

chore: update patch section

---

Cargo.lock
cli/tests/it/svm.rs

feat: `0.8.21` solidity support

---

anvil/src/eth/api.rs

fix(`anvil`): increase timestamp instead of sleeping on `anvil_mine`

---

Cargo.lock
cli/Cargo.toml

new svm release, last one yanked

chore(deps): bump svm-rs

---

evm/src/executor/inspector/cheatcodes/expect.rs

chore: double dummy call output

---

cli/src/cmd/cast/run.rs

chore: dont unwrap

---

cli/src/cmd/cast/run.rs
cli/src/utils.rs
common/src/provider.rs

adds missing flags to control ratelimiting

feat: support ratelimit flags on cast run

---

Cargo.lock

Adds a few useful PRs that were merged:
- Add linea chain, requested on support chat
- Unblocks https://github.com/foundry-rs/foundry/pull/5501
bump ethers

chore: bump `ethers`

---

Cargo.toml

Tweak optimizations in profiles to improve compile times and run time performance.
Binary size should not be impacted much.
- Remove `test` profile modifications, since it will inherit from dev
- Make `local` optimize less to actually be faster than `release` (currently it is not)
- Build dependencies with -O3 on `release` + manually set some non perf-sensitive deps opt levels to offset the compile time increase

chore: tweak optimizations in profiles

---

Cargo.lock
Cargo.toml
anvil/Cargo.toml
cast/Cargo.toml

Subbing in for GHA bot, he's sick this week

chore(deps): weekly `cargo update`

---

evm/src/executor/inspector/cheatcodes/expect.rs

chore(`evm`): make `DUMMY_CALL_OUTPUT` lazy, bump to 8k

---

cli/src/utils.rs

fix: use shell::println

---

evm/src/executor/fork/cache.rs

See `https://github.com/serde-rs/json/issues/160`

perf: avoid `serde_json::from_reader`

---

.github/workflows/docker-publish.yml
.github/workflows/heavy-integration.yml
.github/workflows/release.yml

<https://github.com/foundry-rs/foundry/actions/runs/5908203456>

ci: relax timeout-minutes for release jobs

---

crates/chisel/src/executor.rs
crates/forge/tests/cli/script.rs

From CI <https://github.com/foundry-rs/foundry/actions/runs/5929442004/job/16077818134>

test: fix some tests

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/lib.rs

tui is unmaintained
Replace for ratatui, closes #5696 
cc @iFrostizz might give conflicts with the fuzzer PR—sorry, it's just that CI is broken right now due to this

chore(`deps`): remove `tui` for `ratatui`

---

crates/macros/impl/Cargo.toml

Might fix https://github.com/foundry-rs/foundry/actions/runs/5964270019/job/16179575100
There are no tests to run anyway

fix: do not run proc-macro tests

---

crates/cast/bin/cmd/interface.rs
crates/cast/src/lib.rs
crates/common/src/selectors.rs
crates/fmt/src/solang_ext/ast_eq.rs

Adds a `--json` flag to `cast interface` that prints the JSON ABI of the contract.

feat: `cast interface` JSON ABI option

---

Cargo.lock
crates/anvil/Cargo.toml
crates/anvil/src/anvil.rs

Closes #5754, Closes #5756, and might resolve #5749. Seems parity stuff has their own allocators and it's messing with anvil. 
remove jemalloc from anvil for now. hopefully it doesn't mess with forge and other bins

fix(`anvil`): remove jemalloc

---

crates/abi/Cargo.toml

See https://github.com/foundry-rs/foundry/pull/5789#issuecomment-1710913424

chore: add providers feature to foundry-abi

---

crates/evm/src/executor/inspector/cheatcodes/ext.rs
crates/forge/tests/it/repros.rs
testdata/repros/Issue5808.t.sol

add test for #5808
we can use this as a basis to decide what to do with #5808

test: add test for #5808

---

crates/cast/bin/cmd/wallet/mod.rs

chore: log full address

---

Cargo.toml

prep for https://github.com/hyperledger/solang/pull/1541
use ethers from crates and patch for ws instead

chore: use crates ethers and patch

---

.github/workflows/heavy-integration.yml
.github/workflows/release.yml

https://github.com/foundry-rs/foundry/actions/runs/6293244189/job/17083858483

ci: fix issue jobs (again) (for real this time)

---

.github/workflows/release.yml

ci: update some actions

---

.github/workflows/heavy-integration.yml
.github/workflows/release.yml
.github/workflows/test.yml

Idk why this is not on by default

ci: cache on failure

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

Reverts foundry-rs/foundry#5895
Closes #5903
@DaniPopes reverting this because this still causes issues on ubuntu

Revert "ci: use latest ubuntu runners"

---

.github/workflows/release.yml

ci: add multilib deps

---

Cargo.lock
crates/chisel/Cargo.toml
crates/config/Cargo.toml
crates/debugger/Cargo.toml
crates/evm/Cargo.toml

Should fix our failing action CI.

feat(`deps`): bump revm and disable kzg

---

crates/anvil/src/eth/api.rs

add missing gasPrice log statement

fix(anvil): log gas price request

---

crates/cli/src/opts/dependency.rs

add "@aave" as commonly known alias

chore: add aave alias

---

Cargo.lock

Reverts foundry-rs/foundry#5964

Revert "chore(deps): weekly `cargo update`"

---

Cargo.lock
Cargo.toml
crates/binder/Cargo.toml
crates/binder/src/lib.rs
crates/binder/src/utils.rs
crates/cast/Cargo.toml
crates/chisel/Cargo.toml
crates/common/Cargo.toml
crates/config/Cargo.toml
crates/debugger/Cargo.toml
crates/evm/Cargo.toml
crates/fmt/Cargo.toml
crates/forge/Cargo.toml

chore: bump deps

---

Cargo.toml
crates/anvil/core/Cargo.toml
crates/debugger/Cargo.toml
crates/evm/Cargo.toml

we still have cross platform issues with c.kzg build
disable default feature

chore(deps): no c-kzg default feature

---

crates/forge/bin/cmd/create.rs

Resolves #5993 
Respect chain id, if set explicitly via command line args

fix: forge create respects chain id cmd args

---

crates/common/src/contracts.rs
crates/macros/Cargo.toml
crates/macros/impl/src/console_fmt.rs
crates/macros/impl/src/lib.rs
crates/macros/src/lib.rs

chore: simplify foundry-macros

---

.github/workflows/project.yml
.github/workflows/test.yml

ci: add concurrency

---

crates/forge/bin/cmd/script/executor.rs

chore: convert panics into errors

---

crates/config/src/lib.rs

closes #6053
backwardscompat provider should not replace solc with solc_version if solc was provided
cc @0xalpharush

fix: dont replace solc with solc_version

---

crates/forge/bin/cmd/create.rs
crates/forge/tests/cli/create.rs
crates/forge/tests/fixtures/can_create_with_tuple_constructor_args.stdout

fix: resolve constructor args

---

Cargo.lock
crates/forge/tests/cli/svm.rs

feat: `v0.8.22` support

---

crates/cheatcodes/src/impls/evm.rs

fix(cheatcodes): allow `deal` on precompiles

---

Cargo.lock
Cargo.toml

chore(deps): bumps

---

Cargo.lock

Fixes #6190
https://github.com/alloy-rs/core/pull/396/

chore(deps): bumps 2

---

Cargo.lock
crates/cast/src/lib.rs

chore: bump alloy

---

.github/workflows/release.yml

Closes https://github.com/foundry-rs/foundry/issues/6234

ci: fix windows release

---

Cargo.lock
Cargo.toml

chore(deps): switch to using foundry compilers from crates.io

---

.config/nextest.toml

fix: increase timeout for heavy integration test

---

.github/workflows/release.yml

ci: fix release workflow (again)

---

crates/doc/src/writer/as_doc.rs
crates/doc/src/writer/buf_writer.rs
crates/doc/src/writer/mod.rs
crates/doc/src/writer/traits.rs

Closes #6282
@webthethird
ref https://github.com/foundry-rs/foundry/issues/6282#issuecomment-1806854682

feat(doc): add struct events error table

---

crates/cast/bin/opts.rs

feat: add alias for topic0-event

---

.github/CODEOWNERS

cc @mattsse @Evalir @rkrasiuk @onbjerg

chore(meta): add CODEOWNERS

---

Cargo.lock
Cargo.toml
testdata/repros/Issue4640.t.sol

Missed in #6318
Also change flaky ankr RPC

fix: unpatch chains

---

crates/anvil/src/eth/api.rs

i didn't test it already since anvil can't compile in my actual computer but this should fix https://github.com/foundry-rs/foundry/issues/6335

fix(anvil) : fix returning type

---

crates/anvil/core/src/types.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil_api.rs

Fixes #6335
Also made `chain_id` a `u64` as it should be

fix(anvil): anvil_metadata return types

---

crates/evm/evm/src/executors/fuzz/mod.rs

Encountered in CI: <https://github.com/foundry-rs/foundry/actions/runs/6936640187/job/18869162678#step:12:925>

fix(evm): don't panic on short calldata

---

crates/evm/core/src/fork/init.rs

fix: block numbers are u64

---

Cargo.lock
Cargo.toml
crates/forge/bin/cmd/script/mod.rs

chore: rewrite shanghai support check

---

crates/evm/core/src/fork/cache.rs

style: ugly serialize impl

---

Cargo.lock
crates/forge/Cargo.toml

2.3.2 was released https://github.com/watchexec/watchexec/issues/703

chore(deps): unpin watchexec

---

crates/config/src/inline/natspec.rs
crates/doc/src/parser/mod.rs
crates/fmt/src/formatter.rs

chore: misc fmt

---

crates/debugger/src/tui/draw.rs
crates/fmt/src/formatter.rs

chore: make clippy happy

---

crates/forge/bin/cmd/script/executor.rs

chore: replace expect with wrap_err

---

Cargo.lock
Cargo.toml

chore: bump foundry-block-explorers

---

crates/anvil/tests/it/fork.rs

ref #6463
add snapshot test for scenario described in https://github.com/foundry-rs/foundry/issues/6463#issuecomment-1836739910

test: add snapshot revert test

---

Cargo.lock
crates/anvil/core/src/eth/transaction/ethers_compat.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/common/src/types.rs
crates/evm/core/src/utils.rs

We had commented this out due to lack of support in alloy.
Alloy now supports this, so add it back.

feat(`anvil`/`evm`): re-add support for additional fields

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/fork/init.rs

ref https://github.com/alloy-rs/alloy/pull/70

fix: handle mix hash being optional

---

Cargo.lock
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/common/Cargo.toml
crates/common/src/types.rs

Reintroduces the tracing endpoints, cleans up some stuff. Almost ready.

chore: providers migration cleanup

---

Cargo.lock
Cargo.toml
crates/config/src/etherscan.rs
crates/config/src/lib.rs

Improves error message and adds a test
ref https://github.com/foundry-rs/foundry/issues/6580

test: add alias test

---

crates/anvil/tests/it/main.rs
crates/anvil/tests/it/traces.rs

chore: re-enable tracing tests

---

Cargo.lock
crates/cast/bin/cmd/run.rs

chore: fix ci failures

---

docs/dev/cheatcodes.md

chore: fix typos

---

crates/common/src/runtime_client.rs
crates/evm/core/src/fork/backend.rs

chore: remove outdated clippy

---

crates/forge/tests/cli/ext_integration.rs

<https://github.com/foundry-rs/foundry/actions/runs/7281320957/job/19841607463>

test: disable PRB ext tests on Windows

---

crates/doc/src/preprocessor/infer_hyperlinks.rs

Closes #6642
constructors dont have a name

fix(doc): handle constructor edge case

---

docs/dev/cheatcodes.md

See https://github.com/foundry-rs/forge-std/pull/487

docs: remove forge-std PR requirement for new cheatcodes

---

Cargo.lock
Cargo.toml

includes several fixes for symlinks 
https://github.com/foundry-rs/compilers/blob/main/CHANGELOG.md#bug-fixes

chore: bump foundry-compilers

---

crates/evm/core/src/backend/in_memory_db.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/mod.rs

chore: fix some docs

---

Cargo.lock
crates/forge/bin/cmd/verify/etherscan/mod.rs

bump block-explorers and ensure no trailing slashes

chore: bump block explorers

---

Cargo.lock
Cargo.toml
crates/common/src/compile.rs

chore(deps): bump foundry-compilers

---

crates/evm/core/src/decode.rs

chore: update decode_revert message for empty data

---

crates/forge/tests/fixtures/repro_6531.stdout

chore: update usdc addr

---

Cargo.lock
Cargo.toml
crates/evm/traces/Cargo.toml
crates/evm/traces/src/lib.rs

https://github.com/paradigmxyz/evm-inspectors
Removes dependency on Reth. Most of the patches will be gone once the transition is done.

chore(deps): add revm-inspectors

---

Cargo.lock
Cargo.toml
crates/cheatcodes/src/test/expect.rs
crates/common/src/abi.rs
crates/evm/core/src/decode.rs
crates/evm/traces/src/decoder/mod.rs
crates/evm/traces/src/lib.rs

chore(deps): bump alloys

---

Cargo.lock
Cargo.toml
crates/evm/evm/src/inspectors/access_list.rs
crates/evm/evm/src/inspectors/stack.rs

chore: bring back the clippy

---

crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/fees.rs
crates/evm/core/src/fork/cache.rs
crates/evm/traces/src/lib.rs

replace == U256::ZERO with native fn

chore: use is_zero fn

---

crates/evm/traces/src/identifier/etherscan.rs

fix: respect --offline in etherscan identifier

---

Cargo.lock
Cargo.toml

Closes https://github.com/foundry-rs/foundry/issues/6772

chore(deps): remove patch in favor of git deps

---

Cargo.lock
crates/chisel/Cargo.toml

No impact since it's still in foundry-common and evm

chore(chisel): remove ethers

---

crates/common/src/fmt/ui.rs

fix: add missing receipt fields to pretty fmt

---

crates/anvil/src/eth/api.rs

https://github.com/foundry-rs/foundry/pull/6843

fix: make anvil compile

---

Cargo.lock
deny.toml

chore: fix deny checks

---

Cargo.lock
crates/forge/bin/cmd/verify/etherscan/mod.rs

Follow-up to https://github.com/foundry-rs/foundry/pull/6781, see that PR for more details.

feat: add viaIR to etherscan verification input

---

Cargo.lock
Cargo.toml

Bump foundry-compilers

---

Cargo.lock
Cargo.toml

https://github.com/alloy-rs/chains/pull/31

Chore: Update `alloy-chains`

---

config

Revert "chore: symlink config to crates/config for visibility"

---

crates/config/src/etherscan.rs

ref https://github.com/alloy-rs/chains/pull/32
this improves chain alias parsing 
fyi @gabrielstoica

fix: resolve more chain alias variants

---

crates/anvil/Cargo.toml

chore(deps): unpin k256

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/svm.rs

chore: solc 0.8.24

---

crates/config/src/etherscan.rs

unused type committed by accident in #6918

chore: rm unused type

---

crates/forge/bin/cmd/retry.rs

closes #6953
allow any value > 1

chore: uncap verification retries

---

.github/workflows/release.yml

ci: update actions/github-script

---

crates/anvil/src/eth/backend/genesis.rs

chore(`perf`): remove unneeded to_vec conversion

---

.github/workflows/test.yml

Same as https://github.com/paradigmxyz/reth/pull/6435

chore: pin nightly

---

Cargo.lock
Cargo.toml

chore(deps): bump compilers 0.3.2

---

.github/scripts/matrices.py

Bottle-necked by slow / forking / RPC tests, they have less availability, and they expose more flakiness due to more parallelism -> race conditions.

ci: revert to free GHA runners for tests

---

crates/evm/fuzz/src/strategies/state.rs

This should fix CI broken by #7057

fix(`forge`): small invariant fix

---

crates/anvil/src/eth/backend/mem/mod.rs

chore: add warn logs for fork delegations

---

Cargo.lock
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs

chore: bump alloy rpc

---

crates/cheatcodes/src/test/assert.rs
testdata/cheats/Assert.t.sol

fix(cheatcodes): fix assertApproxEqRel

---

crates/common/src/provider/retry.rs

new quicknode error unlocked: https://github.com/foundry-rs/foundry/pull/6712#issuecomment-1951441240
cc @sakulstra

chore: retry quicknode error

---

Cargo.lock
crates/chisel/Cargo.toml
crates/forge/Cargo.toml
crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/create.rs
crates/forge/tests/cli/script.rs

test: remove serial_test from forge tests

---

crates/cast/src/lib.rs
crates/config/README.md

Adding fraxtal genesis blocks to cast.  I will be following up with a related PR to https://github.com/alloy-rs/chains of the chain aliases.
I also improved documentation on etherscan.

build(cast): fraxtal genesis blocks

---

crates/cast/src/lib.rs

Fixes https://github.com/foundry-rs/foundry/issues/6692

fix(cast): correctly compute mapping indexes

---

CONTRIBUTING.md

lint in contrib docs is different than CI
update contrib doc, add `--all-targets`

Contrib docs: clippy all-targets

---

crates/evm/fuzz/src/strategies/state.rs

chore: reduce unnecessary collected fuzz state

---

crates/evm/fuzz/src/strategies/state.rs

bad order https://github.com/foundry-rs/foundry/pull/7305
I think return is bad there

chore: reduce unnecessary collected fuzz state 2

---

Cargo.lock

fixed blast mainnet blastscan url

chore: bump alloy-chains

---

crates/cli/src/opts/build/paths.rs

chore: add panic message

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/backend/mem/storage.rs
crates/config/src/lib.rs
crates/evm/coverage/src/analysis.rs
crates/forge/tests/it/core.rs

chore(deps): unpin and bump ethers

---

crates/anvil/src/service.rs

perf: mine new blocks on blocking task

---

crates/anvil/src/eth/backend/fork.rs

chore: remove fork caches for eth call and call estimate

---

.github/workflows/test.yml
crates/config/src/lib.rs
crates/evm/core/src/backend/snapshot.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/traces/src/decoder/mod.rs
crates/script/src/lib.rs
crates/script/src/sequence.rs

Keeping fmt pinned due to panics still being a thing

chore: unpin nightly in ci, clippy

---

.gitignore
Cargo.lock
Cargo.toml
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/time.rs
crates/anvil/src/pubsub.rs
crates/anvil/tests/it/api.rs
crates/anvil/tests/it/fork.rs
crates/anvil/tests/it/genesis.rs
crates/anvil/tests/it/wsapi.rs
crates/cast/bin/cmd/run.rs
crates/cast/src/lib.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/evm/fork.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/lib.rs
crates/common/src/provider/alloy.rs
crates/evm/core/Cargo.toml
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/fork/backend.rs
crates/evm/core/src/fork/init.rs
crates/evm/core/src/fork/multi.rs
crates/evm/core/src/opts.rs
crates/evm/evm/src/inspectors/stack.rs

Supersedes https://github.com/foundry-rs/foundry/pull/7356

chore(deps): bump all dependencies, revm 7

---

crates/fmt/src/formatter.rs
crates/forge/tests/it/fuzz.rs

chore: typos

---

crates/anvil/src/hardfork.rs
crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/traces.rs

chore: set cancun block

---

crates/cast/bin/cmd/create2.rs

Ref https://github.com/foundry-rs/foundry/issues/7423

feat(cast): print config in create2

---

crates/evm/fuzz/src/strategies/invariants.rs

chore(fuzz): improve `override_call_strat`

---

Cargo.lock
Cargo.toml
crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/common/Cargo.toml
crates/common/src/compile.rs

Missed in https://github.com/foundry-rs/foundry/issues/7567
cc @radeksvarz

feat: right-align and prettify --sizes output

---

crates/cheatcodes/src/test/assert.rs
testdata/default/cheats/Assert.t.sol

fix: `assertApproxEqRel` edge case

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/script.rs

fix: use correct estimator

---

crates/forge/src/runner.rs

Closes #4259
We had two duplicated branches and one of them missed coverage update.

fix: simplify `run_test`

---

Cargo.lock
Cargo.toml

Closes https://github.com/foundry-rs/foundry/issues/6792
Pulls in the Foundry `block-explorers` release `0.2.6` which includes https://github.com/foundry-rs/block-explorers/pull/40 to resolve #6792

Upgrade `foundry-block-explorers` to `0.2.6`

---

crates/anvil/core/src/eth/mod.rs

feat: add alias for personal_sign

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
testdata/cheats/Vm.sol

accommodate new cheatcodes in forge-std, solc 0.6.2 compatibility
https://github.com/foundry-rs/forge-std/pull/539#issuecomment-2060108249
- fix `isContext` shadowing in `isContext` cheatcode
- use calldata location for `input` in `indexOf` cheatcode

chore(cheatcodes): solc 0.6.2 compatibility

---

crates/cheatcodes/src/fs.rs

fix `cargo +nightly clippy --all --all-targets --all-features -- -D warnings`

chore: fix test clippy

---

Cargo.lock
Cargo.toml
crates/anvil/server/Cargo.toml
crates/anvil/server/src/ipc.rs
crates/anvil/server/src/lib.rs
crates/anvil/src/cmd.rs
crates/anvil/src/lib.rs
crates/anvil/src/server/mod.rs
crates/chisel/Cargo.toml
crates/common/Cargo.toml
crates/config/Cargo.toml
crates/forge/Cargo.toml
crates/forge/bin/cmd/doc/server.rs
crates/verify/Cargo.toml

Axum breaking changes: <https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#070-27-november-2023>
To avoid having a lot of duplicate dependencies, this will require:
- reqwest https://github.com/seanmonstar/reqwest/issues/2039
- Rusoto removal https://github.com/alloy-rs/alloy/pull/44
- Remaining Alloy migration & Ethers removal: https://github.com/foundry-rs/foundry/pull/7106
`Server` is not a thing anymore, so use `Router`s instead

chore(deps): update to hyper 1.0

---

Cargo.lock
crates/forge/Cargo.toml
crates/forge/src/result.rs

closes https://github.com/foundry-rs/foundry/issues/7704

feat: use humatime serde for SuiteResult duration

---

crates/cast/bin/cmd/logs.rs

fix(cast): return logs in all cases

---

Cargo.lock

chore: bump alloy chains

---

crates/cast/src/lib.rs

Remove `ethers` from codebase
Migrate to `alloy`

migrate: cast doctests to alloy

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
testdata/cheats/Vm.sol

Addresses shadowing issues in https://github.com/foundry-rs/forge-std/pull/549
Change return value name

fix: change envExists return sig

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
testdata/cheats/Vm.sol

Ref https://github.com/foundry-rs/forge-std/pull/553#issuecomment-2078338495
Change arg and return value

fix: blob cheats shadowing

---

crates/anvil/src/eth/api.rs

closes #7771
fixes panic on downcast

fix: unsafe balance conversion

---

crates/forge/bin/main.rs
crates/forge/tests/cli/cmd.rs

Closes https://github.com/foundry-rs/foundry/issues/7497 
- remove fuzz cache dir on `forge clean`

fix(fuzz): remove fuzz dir on forge clean

---

crates/config/src/lib.rs
crates/forge/bin/main.rs

https://github.com/foundry-rs/foundry/pull/7809#issuecomment-2083506358

chore: sync `forge clean` and `--force` implementations

---

crates/anvil/src/cmd.rs
crates/config/src/lib.rs

closes #7820
#7812 followup, also skip remappings when loading config for anvil

perf: skip remappings when loading anvil config

---

crates/evm/evm/src/inspectors/stack.rs

Follow up https://github.com/foundry-rs/foundry/pull/7716

fix: make trace printer work

---

crates/forge/bin/cmd/create.rs

closes #7828
must be included before estimating gas

fix: set value before estimating gas

---

crates/forge/bin/cmd/remove.rs
crates/forge/bin/cmd/update.rs

Otherwise it fails inside of git

fix(forge): require at least one dependency in `remove`

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs

Anvil doesn't have cancun specific RPC method `eth_blobBaseFee`
Add `eth_blobBaseFee`

feat(anvil): eth_blobBaseFee

---

crates/anvil/src/eth/api.rs

only checking input is not sufficient and we need to check more fields that have an effect on gas

fix: more gas estimation checks for transfer

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/tests/it/eip4844.rs

Fixes #7841
Set blob fields in `BlockchainStorage::new()` and `ClientForkConfig`

fix(anvil): set blob fields in genesis

---

Cargo.lock
crates/cast/Cargo.toml
crates/wallets/Cargo.toml

Probably fixes https://github.com/foundry-rs/foundry/issues/7852

fix: enable eip712 for all signers

---

Cargo.lock
crates/anvil/Cargo.toml
crates/anvil/src/hardfork.rs

chore: remove unused fork ID support

---

Cargo.lock
crates/anvil/core/src/eth/trie.rs
crates/anvil/server/Cargo.toml
crates/anvil/server/src/ipc.rs
crates/anvil/src/config.rs
crates/anvil/src/lib.rs
crates/anvil/tests/it/ipc.rs
crates/common/src/provider/runtime_transport.rs

-1 parity dep
`interprocess` will be deduped with https://github.com/alloy-rs/alloy/pull/687

chore(deps): replace `parity-ipc-server` with `interprocess`

---

crates/wallets/src/utils.rs

closes https://github.com/foundry-rs/foundry/issues/7870

fix: use B256::try_from for pk

---

Cargo.lock
Cargo.toml
crates/anvil/core/src/eth/block.rs
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/fork.rs
crates/anvil/tests/it/traces.rs
crates/anvil/tests/it/txpool.rs
crates/cast/src/lib.rs
crates/common/src/transactions.rs
crates/debugger/src/tui/draw.rs
crates/evm/traces/src/lib.rs

ref https://github.com/foundry-rs/foundry/issues/7867

chore: bump alloy 17c5650

---

crates/anvil/tests/it/api.rs
crates/anvil/tests/it/ganache.rs
crates/anvil/tests/it/transaction.rs

test: fix some flaky tests

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/otterscan/types.rs
crates/anvil/src/hardfork.rs
crates/anvil/tests/it/otterscan.rs

Ref https://github.com/foundry-rs/foundry/pull/7877#discussion_r1591471989
cc @sealer3
bumps alloy and evm-inspectors for https://github.com/paradigmxyz/evm-inspectors/pull/111
including:
- fixes https://github.com/foundry-rs/foundry/issues/7852

fix(anvil/ots): include selfdestruct target address

---

crates/cast/bin/cmd/access_list.rs
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/estimate.rs
crates/cast/bin/tx.rs

Fixes https://github.com/foundry-rs/foundry/issues/7903

fix(cast): create transactions

---

Cargo.lock

chore(deps): bump chains

---

crates/anvil/server/src/ipc.rs

chore: update interprocess to fix a todo

---

Cargo.lock
crates/forge/tests/cli/svm.rs

feat: support solc 0.8.26

---

crates/anvil/src/eth/api.rs

EIP-1159 doesn't exists, eth_feeHistory is introduced in EIP-1559
Adjusts comment.

Nit: Fix EIP 1159 typo in comment

---

crates/anvil/src/eth/otterscan/types.rs
crates/cheatcodes/src/test/expect.rs
crates/config/src/providers/remappings.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/fork/backend.rs
crates/evm/core/src/utils.rs
crates/evm/fuzz/src/strategies/int.rs
crates/evm/fuzz/src/strategies/mod.rs
crates/evm/fuzz/src/strategies/uint.rs
crates/forge/bin/cmd/clone.rs
crates/forge/src/coverage.rs
crates/forge/src/runner.rs

Addresses some new clippy lints (mostly related to docs)

fix: make clippy happy

---

crates/forge/tests/it/fuzz.rs
testdata/default/fuzz/FuzzScrapeBytecode.t.sol

Add unit test from https://github.com/foundry-rs/foundry/issues/1168

chore(fuzz): add unit test for #1168

---

Cargo.lock
crates/cast/Cargo.toml
crates/wallets/Cargo.toml
crates/wallets/src/error.rs
crates/wallets/src/multi_wallet.rs
crates/wallets/src/wallet.rs
crates/wallets/src/wallet_signer.rs

number in progress bar:
- `cargo check`: 924 to 889
- `cargo build`: 852 to 817

chore: make aws-kms signer support optional

---

crates/cast/bin/cmd/wallet/list.rs
crates/wallets/src/multi_wallet.rs
crates/wallets/src/wallet.rs

Follow-up https://github.com/foundry-rs/foundry/pull/7976

chore: hide aws flags when not enabled

---

crates/cheatcodes/src/config.rs
crates/cheatcodes/src/evm/fork.rs
crates/config/src/cache.rs
crates/config/src/lib.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/it/fork.rs
testdata/default/cheats/Fork.t.sol

Closes #7866 
- propagate and check `no_storage_caching` config to cheatcodes config

fix(forge): consistently apply `no_storage_caching` config

---

crates/config/src/error.rs

Fixes #7998 
- Fix string identifier of `UnnamedReturnVariable`
- Add missing error code in `SolidityErrorCode.from_str`
- Update the order of error codes (according to the order they are declared in `SolidityErrorCode`)

Fix missing error code

---

Cargo.lock
Cargo.toml
crates/cheatcodes/Cargo.toml
crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/utils.rs
testdata/cheats/Vm.sol
testdata/default/cheats/RandomUint.t.sol

Closes #7958 
Closes https://github.com/foundry-rs/foundry/issues/5407
Use `rand::thread_rng`

feat(cheatcodes): randomUint

---

crates/cast/bin/cmd/call.rs

Fixes #8008 
Set `config.fork_block_number`

fix(cast): set --block value as fork_block_number while tracing

---

foundryup/foundryup

Follow-up fix https://github.com/foundry-rs/foundry/pull/8021

fix(foundryup): nproc does not exist on macos

---

Cargo.lock
crates/evm/evm/Cargo.toml
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/fuzz/src/invariant/mod.rs
crates/evm/fuzz/src/strategies/state.rs

and some other minor improvements
cc @grandizzy

perf: prefill fuzz dictionary with 0

---

crates/anvil/src/cmd.rs

Follow up fixes from https://github.com/foundry-rs/book/pull/1210

nit: Minor help style consistency

---

Cargo.lock
Cargo.toml
crates/chisel/src/executor.rs
crates/config/src/lib.rs
crates/debugger/src/tui/draw.rs
crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/anchors.rs
crates/evm/coverage/src/lib.rs
crates/forge/src/coverage.rs

chore(deps): bump foundry-compilers to 0.5.1

---

crates/forge/Cargo.toml

Fixes https://github.com/foundry-rs/foundry/issues/8031

fix: enable providers in ethers-contract-abigen

---

Cargo.lock
crates/wallets/Cargo.toml

Fixes https://github.com/foundry-rs/foundry/issues/8042

fix: re-enable aws-config default-features

---

crates/cheatcodes/src/fs.rs
crates/cheatcodes/src/script.rs
crates/cheatcodes/src/utils.rs
crates/wallets/src/wallet_signer.rs

`WalletSigner::from_private_key` panics if the slice is not 32 bytes

fix: panic in WalletSigner::from_private_key

---

crates/evm/evm/src/executors/fuzz/mod.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/fuzz/src/strategies/state.rs
crates/forge/src/multi_runner.rs
crates/forge/src/runner.rs

As well as improve testing spans

chore: add fuzz dictionary stats

---

crates/cast/bin/cmd/wallet/mod.rs
crates/cast/tests/cli/main.rs
crates/test-utils/src/util.rs

Fixes https://github.com/foundry-rs/foundry/issues/8075

fix(cast): return an error if wallet validation failed

---

crates/cast/bin/main.rs
crates/cast/bin/opts.rs
crates/cast/tests/cli/main.rs
crates/common/src/lib.rs
crates/common/src/utils.rs

Closes https://github.com/foundry-rs/foundry/issues/8078

feat(cast): implement ERC-7201 as `cast index-erc7201`

---

crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/fuzz/src/invariant/call_override.rs
crates/evm/fuzz/src/lib.rs
crates/evm/fuzz/src/strategies/calldata.rs
crates/evm/fuzz/src/strategies/invariants.rs
crates/evm/fuzz/src/strategies/mod.rs
crates/evm/fuzz/src/strategies/param.rs

remove calls to boxed, simplify fixtures

chore: simplify proptest strategies

---

crates/forge/tests/it/repros.rs
testdata/default/repros/Issue2851.t.sol

chore: add test for #2851

---

crates/anvil/src/eth/backend/executor.rs
crates/anvil/tests/it/transaction.rs

closes #8094
we didn't check if block gas limit should be disabled (via cli arg)

fix: bypass block gas limit if disabled

---

crates/anvil/README.md

closes https://github.com/foundry-rs/foundry/issues/7921

Feat: add solc & evm version to anvil readme

---

crates/config/README.md
crates/config/src/error.rs

new error code discovered
https://t.me/foundry_support/54341

feat: add too many warnings error variant

---

crates/forge/tests/it/invariant.rs
testdata/default/fuzz/invariant/common/InvariantRollFork.t.sol
testdata/default/repros/Issue8006.t.sol

- add test to show handler state can be asserted from invariant function in a roll fork scenario
- Issue8006Test name fix

chore: add roll fork invariant test with handler state

---

.github/workflows/release.yml
Dockerfile

- fixes #8072 
Build `forge` and `cast` with the `aws-kms` feature enabled for releases so the `--aws` flag is supported

fix(release): build forge and cast with aws support on release

---

crates/common/src/provider/tower.rs

closes #8140
unclear why this was added, but this always retries error requests which is bad behaviour because error responses are valid responses, for example a revert error.
this also did not do any timeout checks, so unclear what this really did...
ignoring this for now because this feature is being implemented natively in alloy atm

fix: remove hardcoded retries

---

crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/script.rs
crates/cheatcodes/src/utils.rs

perf: don't unnecessarily create CheatsConfig

---

crates/config/README.md

added more known error codes to config README
errors fetched from [here](https://github.com/foundry-rs/foundry/blob/master/crates/config/src/error.rs#L151-L168)

chore: add known error codes

---

Cargo.lock
Cargo.toml
crates/cheatcodes/src/lib.rs

Alloy has been released https://crates.io/crates/alloy 
Discard git versioning and use released version.
Includes a `revm-inspectors` bump to avoid version conflicts.

chore(deps): pin alloy 0.1.1

---

crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/src/eth/otterscan/types.rs
crates/cast/bin/cmd/logs.rs

chore: remove rU256 alias

---

crates/anvil/src/eth/backend/mem/mod.rs

This PR closes https://github.com/foundry-rs/foundry/issues/5056.

pick a random value for prevrandao for each block

---

crates/anvil/tests/it/anvil_api.rs

https://github.com/foundry-rs/foundry/actions/runs/9583404078/job/26424640416

test: unflake an anvil test

---

crates/forge/src/result.rs

chore: remove TestResult.to_owned

---

crates/anvil/README.md
crates/anvil/tests/it/transaction.rs

sorry for the bothering, but I mistakenly used the default language of my local browser in the path of[ #8215](https://github.com/foundry-rs/foundry/pull/8215). I deleted it to adapt to readers in all countries.

fix: Re-edited to delete the language choose

---

crates/anvil/src/eth/miner.rs

the default missed tick behaviour is burst 
> Ticks as fast as possible until caught up.
which can lead to drifting timestamps because we enforce monotonically increasing timestamps

fix: use delay tick behaviour

---

crates/config/src/providers/remappings.rs
crates/evm/core/src/fork/init.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/logs.rs

If the log collector isn't set, collect logs from execution result instead

feat(evm): collect logs from execution result

---

crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/evm/src/executors/invariant/result.rs

Cleanup invariant code by introducing  `InvariantTestData`, `InvariantTest` and `InvariantTestRun` structs

chore: cleanup invariant test code

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/utils/mod.rs

https://github.com/wolfpld/tracy

feat: add feature to enable tracy

---

crates/config/src/lib.rs
crates/forge/bin/cmd/inspect.rs

Closes https://github.com/foundry-rs/foundry/issues/3174

feat(forge): prettify `ir` and `irOptimized` inspect outputs

---

crates/cheatcodes/src/json.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue8277.t.sol

Fixes https://github.com/foundry-rs/foundry/issues/8277

fix(cheatcodes): fallback to string if invalid 0x hex

---

crates/cast/bin/cmd/wallet/vanity.rs

Ref https://github.com/foundry-rs/foundry/issues/8285

chore(cast): improve vanity help

---

crates/anvil/src/cmd.rs

fixes bad unwrap introduced in #8228

fix: forkchoice match checks

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/otterscan/types.rs
crates/debugger/src/tui/context.rs
crates/debugger/src/tui/draw.rs
crates/evm/evm/src/inspectors/stack.rs
crates/evm/traces/src/decoder/mod.rs
crates/evm/traces/src/lib.rs
crates/forge/src/runner.rs

Fixes https://github.com/foundry-rs/foundry/issues/8283

chore(deps): bump revm-inspectors

---

crates/cast/bin/cmd/wallet/vanity.rs

Followup https://github.com/foundry-rs/foundry/pull/8296
Help values still mentioned "HEX"

docs(cast): improve vanity help naming

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm/fork.rs
testdata/cheats/Vm.sol
testdata/default/cheats/Fork2.t.sol

Closes https://github.com/foundry-rs/foundry/issues/8310

feat(cheatcodes): add rpc with url overload

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/soldeer.rs

Soldeer update to v0.2.16
Soldeer release notes:
https://github.com/mario-eth/soldeer/releases/tag/v0.2.16
Mostly solving some bugs and adding small improvements:
- dry-run on push to let the users see what it will be pushed without actually pushing
- warning to not push .dot files
- improved the soldeerignore to work exactly as gitignore. Furthermore we now support both gitignore/soldeerignore files, you don't need to have them both but if there are both of them then we just merge them.

Updating soldeer to version 0.2.16

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/fork.rs

Include txhash in fork cli section on startup

chore: include tx in setup output

---

crates/forge/assets/CounterTemplate.s.sol

Current `Counter.s.sol` template does not deploy the example `Counter` contract requiring the user to make modifications before running `forge script script/Counter.s.sol` before it does anything.
I also run into this often when setting up a quick reproduction w/ `forge init` of a script bug, requiring me to add this exact snippet every time
Import `Counter` and deploy upon running `forge script script/Counter.s.sol`

chore(template): update script template to deploy `Counter` contract

---

crates/evm/core/src/constants.rs
crates/evm/evm/src/executors/mod.rs

chore(evm): extract create2 deployer deployer constant

---

crates/script/src/receipts.rs

feat: better dropped tx check

---

crates/forge/tests/it/config.rs

https://github.com/foundry-rs/foundry/pull/8224/files/0c6607336ecd161ddd49dfc53f612e42184cd817#r1662891341

test: use known contracts when decoding traces

---

testdata/default/cheats/Assert.t.sol

Simplified _formatWithDecimals impl

fix: flaky assertion test

---

crates/wallets/src/utils.rs

test: add test for pk parsing

---

crates/forge/bin/cmd/clone.rs

some additional docs for #8356

docs: add note about evm_version

---

crates/anvil/src/config.rs

chore: fix clippy

---

README.md

Closes https://github.com/foundry-rs/foundry/issues/6925
Adds more detailed instructions to the FAQ section in the Foundry book here: https://github.com/foundry-rs/book/pull/1239
Avoiding the details in the main `README` as it is largely irrelevant

docs: remove mention of install location of `solc` in favor of detailed explanation in Foundry Book

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Closes #8423 
- treat require as branch coverage
- test

fix(coverage): require should be branch

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Add coverage report for try/catch. Each clause and their bodies are reported, including clauses without body.
For example, happy path tested only (one call) will be reported as
Full coverage for all clauses, including clause without body (one call for each)

feat(coverage): report try-catch coverage

---

crates/cast/bin/opts.rs
crates/cast/src/lib.rs
crates/cast/src/rlp_converter.rs

Fixes https://github.com/foundry-rs/foundry/issues/8453

feat(cast): improve to/from rlp

---

Cargo.lock
Cargo.toml
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/state.rs
crates/anvil/tests/it/optimism.rs
crates/anvil/tests/it/otterscan.rs
crates/cheatcodes/Cargo.toml
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test/assert.rs
crates/common/fmt/src/ui.rs
crates/evm/core/src/lib.rs
crates/evm/evm/src/inspectors/logs.rs
crates/evm/evm/src/inspectors/stack.rs

Builds on top of https://github.com/foundry-rs/foundry/pull/8305
Added `console_log` hook to `InspectorExt` because we can't just call `Inspector::log` anymore as it requires interpreter

bump alloy and revm

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Closes #1968 
Should give good support for Yul coverage, tested on more complex code (than the unit tests) from Solady and yul_by_example project, showing good results
- added support for remaining Yul types
- tested support for the other types listed + tests

feat(coverage): Add support for remaining Yul types

---

Cargo.lock

fix: cargo deny

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs

Closes: https://github.com/foundry-rs/foundry/issues/8468
Add eth_getAccount in anvil.

feat: ethGetAccount

---

crates/anvil/src/eth/backend/mem/mod.rs

Just realized this while going through https://github.com/foundry-rs/foundry/pull/8476 (sorry, nits!

chore: 7702 error type correction

---

crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/can_test_repeatedly.stdout
crates/forge/tests/fixtures/suggest_when_no_tests_match.stdout
crates/forge/tests/fixtures/warn_no_tests.stdout
crates/forge/tests/fixtures/warn_no_tests_match.stdout
crates/test-utils/src/util.rs

can_test_repeatedly flaky test
https://github.com/foundry-rs/foundry/actions/runs/10090483737/job/27900022942#step:12:201
use snapbox, port couple of more tests

chore: fix flaky can_test_repeatedly test

---

.github/workflows/release.yml

`--no-default-features` should be passed to actually enable jemalloc conditionally
Closes https://github.com/foundry-rs/foundry/issues/8526

ci: fix conditional release features

---

.github/workflows/release.yml

followup for https://github.com/foundry-rs/foundry/pull/8529
https://github.com/foundry-rs/foundry/blob/master/crates/anvil/Cargo.toml#L127-L127

ci: enable anvil default feature for release

---

crates/cheatcodes/src/fs.rs

https://t.me/foundry_support/55487
```
Message:  index out of bounds: the len is 0 but the index is 0
Location: crates/cheatcodes/src/fs.rs:405
```

fix(cheatcodes): get artifact code panic

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs

fix #8399
Closes #3699 
Closes #4251 
Closes #8392

add `--max-persisted-states` to configure `max_on_disk_limit` 

---

crates/forge/tests/it/invariant.rs

potential fix flakiness of `test_invariant_assert_shrink`: split the two tests performed in individual tests (so they're individually run and cleaner which one fails), assert predictable shrink sequence to 2

chore: potential fix flaky test_invariant_assert_shrink

---

Cargo.lock
Cargo.toml

chore: bump compilers 0.10.2

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/Repros/fmt.sol
crates/fmt/testdata/Repros/original.sol

Closes #3979 
- write condition prefix comments before visiting identifiers

fix(fmt): write prefix comments in if block

---

crates/evm/coverage/src/analysis.rs

simplify code as suggested in https://github.com/foundry-rs/foundry/pull/8615#discussion_r1705467479

chore(coverage): cleanup creation / push item

---

crates/script/src/execute.rs
crates/script/src/lib.rs

Fixes #7817 
Extendend `JsonResult` struct

extended JsonResult structure

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/Repros/fmt.sol
crates/fmt/testdata/Repros/original.sol

Closes #5825 
- if item format disabled, create chunk with raw src

fix(fmt): preserve format of disabled item

---

Cargo.lock
Cargo.toml
crates/common/fmt/src/dynamic.rs

ref https://github.com/foundry-rs/foundry/issues/8682#issuecomment-2294890970
Updates formatting for fixed bytes to remove padding with zero bytes

fix: update formatting for fixed bytes

---

crates/script/src/execute.rs
crates/script/src/runner.rs

Closes https://github.com/foundry-rs/foundry/issues/8304
https://github.com/foundry-rs/foundry/pull/8532 only addressed this partially as it only touched library deployment transactions.

fix(script): correctly populate both fields for `TransactionRequest`s

---

crates/cast/tests/cli/main.rs

https://github.com/foundry-rs/foundry/actions/runs/10458376982/job/28960059810

test: unflake cast storage layout test

---

SECURITY.md

Resolves https://github.com/foundry-rs/foundry/issues/8734
Adds security policy as implemented in https://github.com/alloy-rs/alloy/blob/main/SECURITY.md

chore: add security policy document

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/repros.rs

should address issue in #4370 : reconcile gas when exiting frame

fix(cheatcodes): reconcile gas when exiting frame

---

crates/common/src/ens.rs
crates/config/src/lib.rs
crates/doc/src/preprocessor/infer_hyperlinks.rs
crates/forge/src/multi_runner.rs

Fix clippy - allow elided_named_lifetimes

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/soldeer.rs

Bugfix on integrity check, previously the integrity check was regenerating the hash every run due to a misconfigured absolute path. That has been solved in soldeer 0.3.4
Also fixing a WalkDir issue on windows
Using relative path not absolute

feat: update soldeer 0 3 4

---

Cargo.lock
crates/forge/tests/cli/svm.rs

feat: solc 0.8.27 support

---

Dockerfile

renamed crate, also need to update build command
closes #8827

ci: update docker build

---

crates/anvil/tests/it/traces.rs

wait until tx is mined before tracing

test: fix flaky test

---

Cargo.lock
Cargo.toml
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/tests/it/eip7702.rs

Fixes #8830 
Bumps alloy to include https://github.com/alloy-rs/alloy/pull/1261
Consequently bump `op-alloy-rpc-types`

chore: bump alloy to fix #8830

---

.gitignore
Cargo.toml
crates/evm/traces/src/debug/sources.rs
crates/fmt/src/buffer.rs
crates/fmt/src/formatter.rs
crates/forge/bin/cmd/test/mod.rs

Should be a few MiBs
Ref https://github.com/foundry-rs/foundry/issues/8671

chore: add more size optimizations

---

crates/evm/evm/src/inspectors/stack.rs
testdata/default/cheats/Nonce.t.sol

closes #8811 
- do not reset account nonce when running with isolate

fix(test): increment nonce for calls too when isolate

---

crates/anvil/tests/it/fork.rs
crates/cast/src/lib.rs

test: use alchemy for arbitrum URLs

---

crates/forge/tests/cli/config.rs
crates/forge/tests/cli/ext_integration.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs

- solve test-isolate CI failure and local `cargo test --all --all-features`
- prereq of #8811 fix
- config tests:
- `can_detect_lib_foundry_toml` randomly added `ds-test` remapping
- `can_parse_default_fs_permissions` randomly failing due to prj root
- external integration: no failure, vyper should be at latest version locally, bumped `snekmate` commit to latest master
- couple script and cmd tests failing due to different gas when running isolate, redacted

chore(tests): fix isolate CI + all targets / features tests

---

crates/cli/src/opts/build/mod.rs
crates/config/src/lib.rs

Related issue: https://github.com/foundry-rs/book/issues/789
Updates documentation, here and in https://github.com/foundry-rs/book/pull/1299

docs: improve `optimizer_runs` documentation to be more accurate

---

.github/workflows/release.yml

ci: build release artifacts with maxperf

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/tests/it/eip4844.rs
crates/anvil/tests/it/otterscan.rs
crates/anvil/tests/it/utils.rs
crates/cast/bin/tx.rs
crates/common/src/compile.rs
crates/common/src/provider/mod.rs
crates/forge/tests/it/test_helpers.rs

Bump alloy to latest
Closes #8895 
- Bump alloy, revm, revm-inspectors
- Fix breaking changes
- Add block-explorers patch that includes https://github.com/foundry-rs/block-explorers/pull/63

chore: bump alloy 0.3.6

---

crates/cheatcodes/README.md

readme: fix cheatcode path

---

crates/anvil/src/eth/backend/mem/mod.rs

Partially addresses https://github.com/foundry-rs/foundry/issues/8715,
but most of the magic happens here https://github.com/alloy-rs/core/pull/742 
Print address in checksum format

Log address in checksum format

---

crates/forge/bin/cmd/test/mod.rs

improve description of `--flamechart` and `--flamegraph`

---

crates/forge/bin/cmd/test/mod.rs

fix(forge): improve `test --debug` doc

---

Cargo.lock
crates/anvil/Cargo.toml
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/db.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/fork_db.rs
crates/anvil/src/eth/backend/mem/in_memory_db.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/validate.rs

Trait aliases and upcasting make this way nicer, it is what it is

chore(anvil): use dyn DatabaseRef instead of generics

---

testdata/README.md

https://github.com/foundry-rs/foundry/commit/319398fe6e61f1a9e8f88356944dbb1f6179726c#diff-8b8d38f8a7f4438e514329784e9e25f123f165ad74bde921c711038e03e39f5f 
Hi there the test moved to `default` path in above PR

chore(docs): Update testcode path

---

.github/CODEOWNERS

Should make it easier to have us perform reviews as well by default
Discussed in call w/ @jenpaff

chore: add @grandizzy @yash-atreya @zerosnacks as codeowners

---

Cargo.lock
Cargo.toml

Follow-up to https://github.com/foundry-rs/foundry/pull/8941 + `cargo update`

chore(deps): update revm-inspector version in manifest

---

crates/cli/src/opts/build/core.rs
crates/cli/src/opts/build/mod.rs
crates/forge/bin/cmd/create.rs
crates/forge/bin/cmd/inspect.rs

There's no way to disable optimizer through CLI
Allows passing value to `--optimize` flag, e.g `--optimize=false`

feat(forge): allow passing value to `--optimize`

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/src/result.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/SimpleContractTestNonVerbose.json
crates/forge/tests/fixtures/SimpleContractTestVerbose.json

Closes #9064 
- add logs/decoded logs in json response (verbosity based)

fix(forge): add logs/decoded logs in json test results

---

crates/chisel/bin/main.rs

feat(chisel): add eval command

---

Cargo.lock
Cargo.toml

Hotfix of https://github.com/mario-eth/soldeer/issues/212

feat: update to Soldeer v0.4.1

---

crates/cheatcodes/src/crypto.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/script.rs

Addresses suggestion https://github.com/foundry-rs/foundry/pull/9106#discussion_r1799337831 as a followup
- Use `get_or_insert` 
- Renames `fn script_wallets` to `fn wallets`
- Add `len()` and `is_empty()` fns to `Wallets`

chore(`cheatcodes`): wallet nits

---

crates/anvil/src/eth/backend/mem/mod.rs

we're not pre eip98
noone's using this really
ref https://github.com/alloy-rs/alloy/pull/1506

fix: dont set state root

---

crates/forge/src/runner.rs

re tg discussion https://t.me/foundry_support/57334 : warn if invariant fails on rerunning persisted scenario

chore: add warning on persisted invariant scenario failure

---

Cargo.lock
Cargo.toml
crates/anvil/src/eth/error.rs

chore(deps): bump alloy + revm + fork-db

---

crates/cast/src/rlp_converter.rs

test case for bytes input https://github.com/foundry-rs/foundry/issues/9197

test: add test for rlp data

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil.rs

fix: include withdrawals root in response

---

crates/forge/bin/cmd/create.rs

clap doesn't accep `-<int>` and requires escaped `'-<int>'` so we have to manually unescape here

fix: allow_hyphen_values for constructor args

---

crates/cast/bin/args.rs

ref #9210, the flag is new so shouldn't break anything

fix: rename flag as_int -> as-int

---

crates/forge/tests/cli/script.rs

Fix CI, ignore flaky test due to rostock testnet

chore: ignore flaky rostock chain test

---

Cargo.lock
Cargo.toml

Update to Soldeer 0.5.0.
We don't have breaking changes for the users, mostly on how we manage some extra arguments on the cli. 
We added a way for users to skip interactive prompts.
https://github.com/mario-eth/soldeer/releases/tag/v0.5.0

feat: update to Soldeer v0.5.0

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/tests/it/anvil.rs

Ref https://github.com/foundry-rs/foundry/pull/9290#discussion_r1835445805

chore: typo anvil_getIntervalMing -> anvil_getIntervalMining

---

deny.toml

Related failure: https://github.com/foundry-rs/foundry/actions/runs/11819785986/job/32930522331
- Adds `unicode-3.0` as it was required, this is greenlit in Reth's `deny.toml` so should be OK
- Removes unused

fix(`ci`): update cargo deny

---

Cargo.lock
Cargo.toml

Hotfix https://github.com/mario-eth/soldeer/issues/225

feat: Update to soldeer 0.5.1

---

testdata/default/cheats/GetArtifactPath.t.sol

fix flaky test https://github.com/foundry-rs/foundry/actions/runs/11834078970/job/32974056466#step:12:1762 which would rerun all cheat codes tests

chore: fix getArtifactPath flaky test

---

crates/cli/src/handler.rs

chore: don't color error message in red

---

Cargo.lock
Cargo.toml

Fixes https://github.com/foundry-rs/foundry/issues/9349

chore(deps): bump foundry-compilers 0.12.2

---

Cargo.lock
Cargo.toml

chore(deps): bump foundry-compilers 0.12.3

---

Cargo.lock
Cargo.toml
crates/anvil/Cargo.toml
crates/anvil/tests/it/anvil.rs

Remove flaky anvil cache path test

chore: rm flaky cache-path test

---

Cargo.lock
Cargo.toml

Fixes https://github.com/mario-eth/soldeer/issues/232

feat: Update to soldeer 0.5.2

---

crates/forge/tests/cli/script.rs

Flaky test
Ref: https://github.com/foundry-rs/foundry/actions/runs/11971338274/job/33375962110
Add `--slow`

fix: flaky test_broadcast_raw_create2_deployer

---

Cargo.lock
crates/evm/traces/Cargo.toml
crates/evm/traces/src/debug/sources.rs

Ref https://github.com/foundry-rs/foundry/issues/9317

chore(evm/traces): replace solang with Solar

---

crates/forge/bin/cmd/create.rs

Closes #4361 
- install missing deps when `forge create`, if any

fix(forge create): install missing deps if any

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
testdata/cheats/Vm.sol

- fix `forge-std` 0.6.2 compat fail https://github.com/foundry-rs/forge-std/actions/runs/12012482898/job/33483798391?pr=633#step:10:12
-

fix(cheatcodes): use calldata in attachDelegation

---

Cargo.lock
Cargo.toml
README.md
crates/forge/Cargo.toml
crates/forge/bin/cmd/bind.rs

Reverts foundry-rs/foundry#8826
holding off until foundryup support for opt out breaking changes

Revert "feat: remove ethers"

---

crates/anvil/src/eth/otterscan/api.rs

The previous link has expired and has been replaced with the latest address.
Use the correct url.

chore: fix 404 status URL

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/tests/cli/main.rs

- re https://github.com/foundry-rs/foundry/pull/9428#discussion_r1862641086
- make event sig optional, if not provided decode events with local sigs and Openchain API
- add tests

feat(`cast`): `decode-event` with local and openchain API

---

.github/workflows/release.yml

chore: Add GH attestation for foundry binaries

---

Cargo.lock
Cargo.toml
crates/config/src/lib.rs

Includes changes from https://github.com/foundry-rs/compilers/pull/234

chore: bump compilers

---

.github/workflows/release.yml

fix(release): check `env.IS_NIGHTLY` as string

---

.github/workflows/release.yml

Run release workflow on stable tag push

---

.github/changelog.json

- added breaking changes category
- added feat / fixes category per binaries
- added perf category
- restrict summary to max 60 days / max 100 PRs, add full diff and contributors

chore: update release notes template

---

.github/changelog.json

chore: add contributors in release changelog

---

Cargo.lock
Cargo.toml

chore: bump workspace version to `0.3.0`

---

crates/forge/tests/cli/inline_config.rs

- order of test contracts within same file could differ, see from https://github.com/foundry-rs/foundry/actions/runs/12453169770/job/34762982884#step:12:625
- split inline config test

chore: fix flaky inline config test

---

Cargo.lock
Cargo.toml
crates/anvil/core/src/eth/block.rs
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/src/eth/error.rs
crates/anvil/src/eth/fees.rs
crates/anvil/src/eth/otterscan/api.rs
crates/anvil/tests/it/eip4844.rs
crates/anvil/tests/it/eip7702.rs
crates/anvil/tests/it/fork.rs
crates/cast/bin/cmd/wallet/mod.rs
crates/cast/bin/tx.rs
crates/cast/tests/cli/main.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/script.rs
crates/common/fmt/src/ui.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/script/src/broadcast.rs
crates/script/src/receipts.rs

update revm+alloy
this includes blob changes for prague, for now everything still uses the cancun params for blob gas price

feat: update revm 19 alloy 09

---

crates/cli/src/utils/abi.rs

We have `Etherscan` and `EtherScan` in different files, let's use `Etherscan` instead

typo: EtherScan -> Etherscan

---

.gitattributes

This has to be explicitly enabled for git to utilize its enhanced rust diffing, evidently. 
ref: https://github.com/rust-lang/rust/pull/78882

chore(git): enhance rust diffing

---

crates/cast/src/lib.rs

- feat: add `cast chain` support for `ink` & `ink-sepolia`

Feat: Add `cast chain` support for `ink` & `ink-sepolia`

---

Cargo.lock

- chore(deps): bump `alloy-chains`

chore(deps): bump `alloy-chains`

---

README.md

fix: incorrect repo link in readme for foundry-compilers

---

.github/workflows/docker-publish.yml
Dockerfile.cross
Makefile

implement and close https://github.com/foundry-rs/foundry/issues/8039
use `cross` instead of qemu to build the arm64 image

feat: add arm64 docker image

---

.gitignore
Cargo.toml

Same thing but more descriptive

chore: use "full" for debug

---

crates/common/src/retry.rs

chore: don't warn in RetryError::Continue

---

crates/forge/bin/cmd/coverage.rs
crates/forge/bin/cmd/watch.rs
crates/forge/bin/main.rs

Closes #4303 
Add `--watch` support for coverage by exposing `WatchArgs` via coverage.

feat(`forge`): `--watch` coverage

---

crates/cheatcodes/src/config.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/fs.rs
crates/chisel/src/executor.rs
crates/forge/src/multi_runner.rs
crates/script/src/lib.rs

Closes https://github.com/foundry-rs/foundry/issues/9708
If we have multiple matched artifacts, prefer choosing one which matches the profile of currently running test/script.

feat: filter by profile in `vm.getCode`

---

crates/anvil/core/src/eth/mod.rs

this should be a sequence
ref https://github.com/alloy-rs/alloy/pull/1971

fix: use sequence for rollback

---

crates/forge/tests/cli/ext_integration.rs

- prev pointing to commit from PR which was merged

chore: point forge-std ext test to latest main

---

Cargo.lock
Cargo.toml
foundryup/foundryup

Previous version incorrectly displayed: `0.3.1-v1.0.0-rc`
Updates version numbers for release candidate to be released with `rc` tag
Also updates `foundryup` with no further changes, to be incremented with patch versions.

chore: update version numbers for `v1.0.0-rc`

---

.github/workflows/release.yml

chore: ci release on rc tag

---

crates/anvil/tests/it/fork.rs

- base gas limit lowered to 96,000,000

chore: fix base gas limit test

---

Cargo.lock
Cargo.toml

chore: bump compilers, fix #9788

---

crates/forge/bin/cmd/fmt.rs
crates/forge/bin/cmd/watch.rs
crates/forge/bin/main.rs

Closes https://github.com/foundry-rs/foundry/issues/9831
Watch args and watch mode has been added to `forge fmt command`.

feat(`forge fmt`): add watch mode

---

Cargo.lock
Cargo.toml

chore(deps): bump alloy to `0.11.1`

---

crates/forge/tests/cli/test_cmd.rs

chore: fix isolate tests

---

Makefile
crates/anvil/tests/it/fork.rs

Pin tonistiigi/binfmt iamge
- port docker release fix in v1.0.0 release branch
- port failing base test in v1.0.0 release branch

fix release: Pin tonistiigi/binfmt iamge (#9872)

---

Cargo.lock
Cargo.toml

- bump compilers
- closes #9876

fix(forge): flatten fails on top-level event declarations

---

crates/test-utils/src/rpc.rs

chore: update rpc keys

---

crates/evm/evm/src/executors/mod.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/cli/test_cmd.rs

Closes #9903 
- Catch contract deployment errors in setUp
- Display test suite failure accordingly
- Test

fix(`forge`): catch faulty test constructors

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/version.rs

Follow-up https://github.com/foundry-rs/foundry/pull/9845.

chore: version cmp cheatcodes clean up

---

crates/anvil/src/hardfork.rs

Allow specifying optimism hardforks and Holocene and Isthmus in anvil.

feat(anvil): add holocene and isthmus optimism hardforks

---

crates/cast/bin/main.rs
crates/cast/tests/cli/selectors.rs

fix 4-bytecalldata

---

crates/forge/bin/cmd/eip712.rs

use HashMap::keys avoid unnecessary tuple unpacking

---

crates/forge/bin/cmd/inspect.rs
crates/verify/src/provider.rs
crates/verify/src/verify.rs

change &Option<String> to Option<&str>. it can remove clone

change &Option<String> to Option<&str>

---

crates/doc/src/parser/mod.rs

I found this TODO comment to add a test case, so I wanted to address it.
```
// TODO: test regular doc comments & natspec
```
Added a test case.

test(doc): added test case for doc comments & natspec

---

crates/cheatcodes/src/inspector.rs
crates/forge/tests/cli/test_cmd.rs

fix(forge): do not panic if revert at same depth as start state recording

---

crates/forge/tests/cli/test_cmd.rs
deny.toml

- ignore RUSTSEC-2024-0436 and RUSTSEC-2024-0437
- fix prank stack test in isolation mode

chore: cargo deny and isolate tests

---

deny.toml

humantime is unmaintained, ignore RUSTSEC-2025-0014

fix deny.toml, ignore RUSTSEC-2025-0014

---

Cargo.lock
crates/forge/Cargo.toml

update watchexec to 6.0, watchexec-events to 5.0

---

crates/cast/tests/cli/main.rs

chore: reenable impersonate test

---

Cargo.lock
Cargo.toml
crates/config/src/utils.rs
crates/forge/tests/cli/odyssey.rs
crates/forge/tests/cli/svm.rs
crates/test-utils/src/util.rs

feat: solc 0.8.29

---

crates/test-utils/src/rpc.rs

chore: fix ci

---

.github/workflows/release.yml

- follow up from https://github.com/foundry-rs/foundry/pull/10086

chore: fix target check for musl

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

- closes #10095 
- bump runners to use newer gcc version. regular release pass https://github.com/foundry-rs/foundry/actions/runs/13896654791
- install cross 0.2.5, unclear why fails with cross main. docker release pass https://github.com/foundry-rs/foundry/actions/runs/13904739409/job/38904930753

chore: fix release

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml
Cargo.lock
crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/geiger.rs

- closes #10106 
- closes #10102 
- reverts cargo updates that pulls in incompatible aws-lc-sys
- should be followed up by proper fix / move runners to ubuntu-22.04 and deprecate 20.04 support

chore: fix release - revert updates

---

Cargo.lock

Fixes https://github.com/foundry-rs/foundry/security/dependabot/48
Bumps `svm-rs` containing bump for `zip`.
`zip` crate will be updated as part of https://github.com/foundry-rs/foundry/pull/10110
Together this resolves it

chore: bump svm-rs

---

Cargo.lock
Cargo.toml
crates/forge/Cargo.toml
crates/forge/bin/cmd/soldeer.rs
crates/forge/tests/cli/soldeer.rs

Release of soldeer 0.5.3
https://github.com/mario-eth/soldeer/releases/tag/v0.5.3 with small changes that can be seen in the release page. 
A breaking change is when we try to install via git, `--git` must be specified 
https://github.com/mario-eth/soldeer/blob/main/USAGE.md#git-repository
The reason for this was to differentiate when we want to use git or url for custom dependencies that are not hosted on soldeer repo.

Update to soldeer 0.5.3

---

crates/test-utils/src/rpc.rs

chore: rotate

---

crates/forge/bin/cmd/clone.rs
crates/forge/tests/cli/cmd.rs

- closes #10115 
- raw src dir cloned could contain `node_modules` - if so then reorg and move it outside src dir

fix(forge): clone src with node_modules

---

.github/workflows/test.yml

- run tests only if basic checks pass

chore: run ci tests only if clippy/fmt/deny success

---

crates/anvil/src/eth/miner.rs
crates/anvil/src/service.rs

some misc comments while reviewing the poll logic #10122
couldn't find anything obvious, @zerosnacks maybe we can reproduce this in a test, which should just be, send 30 txs with correct nonces concurrently.

docs: misc miner comments

---

crates/anvil/Cargo.toml
crates/anvil/bin/main.rs
crates/anvil/src/args.rs
crates/anvil/src/lib.rs
crates/anvil/src/opts.rs
crates/cast/bin/main.rs
crates/forge/bin/main.rs

Ref: https://github.com/foundry-rs/foundry/issues/9807
Ref: https://github.com/foundry-rs/foundry/pull/10117
Ref: https://github.com/foundry-rs/foundry/pull/10123
Make `bin` as thin as possible, move `cmd`, rename `args` to `opts` and move into the crate, move `run` into `args` as part of the crate

chore: refactor `anvil` for library use

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
testdata/cheats/Vm.sol

- fix forge-std compatibility with solc <= 0.8.0 failing in https://github.com/foundry-rs/forge-std/pull/670

chore: accessList sig compatible with solc <= 0.8.0

---

.github/workflows/test.yml
crates/anvil/tests/it/state.rs
crates/cast/tests/cli/main.rs
crates/forge/tests/cli/failure_assertions.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/it/test_helpers.rs
crates/test-utils/src/rpc.rs
testdata/default/cheats/RpcUrls.t.sol

- use reth archive node for mainnet tests that require history access (cheatcodes and repros too)
- use reth archive and full nodes for all other mainnet tests
- use DRPC for all other networks in tests: Arbitrum, Optimism, Sepolia, Polygon
- remove test job dependencies

chore: improve ci

---

crates/forge/src/cmd/init.rs

Closes https://github.com/foundry-rs/foundry/issues/9839

fix(forge init): handle github.com/ prefixed templates

---

crates/forge/src/cmd/create.rs
crates/forge/tests/cli/create.rs

- closes #10156 
- use Bytes.is_empty to check object bytecode

fix(forge): bail if forge create contract with empty bytecode

---

crates/cast/src/tx.rs

fix(cast): send should not panic on revert decoding

---

.github/workflows/nextest.yml

chore: update `ETH_RPC_URL` in CI

---

Cargo.lock

closes #10194
we just released hoodi links

chore: bump chains

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/cheats.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/eip4844.rs

Closes #9924 
- Adds a method `skip_blob_validation`
- Returns true if impersonation is enabled
- Bypass blob validation checks accordingly 
- test

feat(`anvil`): bypass sidecar requirement when impersonating

---

crates/cast/src/cmd/call.rs
crates/cast/src/cmd/run.rs
crates/chisel/src/executor.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/trace.rs
crates/forge/src/cmd/test/mod.rs
crates/forge/src/multi_runner.rs
crates/forge/tests/it/config.rs
crates/forge/tests/it/core.rs
crates/forge/tests/it/fork.rs
crates/forge/tests/it/fuzz.rs
crates/forge/tests/it/inline.rs
crates/forge/tests/it/invariant.rs
crates/forge/tests/it/repros.rs
crates/script/src/lib.rs
crates/verify/src/utils.rs

fix(forge): do not panic if create fork err

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/utils.rs
crates/forge/tests/cli/test_cmd.rs
testdata/cheats/Vm.sol

This pull request fixes #10176 
https://github.com/foundry-rs/foundry/issues/10176

add interceptInitcode cheatcode

---

crates/evm/evm/src/executors/invariant/mod.rs
crates/forge/tests/it/invariant.rs

feat(forge): allow invariant contract address as targetContract

---

crates/evm/core/src/decode.rs

Ref https://github.com/foundry-rs/foundry/issues/10162

test: add a test case for RevertDecoder

---

.github/workflows/release.yml

- update last stable version for generating 1.1.0 release notes

chore: release 1.1.0 - update last stable version

---

crates/script-sequence/src/reader.rs

chore: rm redundant clone

---

.github/workflows/release.yml

chore: trigger releases on rc-* tags too

---

Cargo.lock
crates/config/Cargo.toml
crates/config/src/etherscan.rs
crates/config/src/providers/ext.rs

chore(deps): replace inflector with heck

---

Cargo.lock
Cargo.toml
crates/config/Cargo.toml
crates/config/src/lib.rs
crates/config/src/soldeer.rs
crates/forge/src/cmd/soldeer.rs

This is an update to https://github.com/mario-eth/soldeer/releases/tag/v0.5.4 which includes a hotfix 
https://github.com/mario-eth/soldeer/pull/271
TL;DR if a dependency would have versions that were not SemVer compliant we would default to latest

Update to soldeer 0.5.4

---

crates/anvil/tests/it/fork.rs

chore: fix anvil immutable fork test

---

crates/anvil/tests/it/fork.rs

- update immutable forked test to use a newer block

chore: update flaky immutable forked test

---

Cargo.lock
crates/forge/tests/cli/svm.rs

feat: solc 0.8.30

---

FUNDING.json

Adds "opRetro" project id to funding.json

chore: add OpRetro to funding.json

---

crates/anvil/src/eth/api.rs
crates/anvil/src/pubsub.rs
crates/anvil/src/server/handler.rs
crates/anvil/tests/it/transaction.rs

fixes [#2324](https://github.com/alloy-rs/alloy/issues/2324)
and hopefully will also close #9757

feat: added TransactionStream to subscribe to pending transactions

---

crates/anvil/src/eth/backend/mem/mod.rs

fix(anvil): use saturating_to when check for req funds

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml

chore: prepare v1.2 release

---

crates/cheatcodes/src/inspector.rs
testdata/default/cheats/Prank.t.sol

fix(forge): mark prank applied on contract creation too

---

crates/cheatcodes/src/inspector.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue10527.t.sol

fix(forge): do not revert if event with count 0 not emitted

---

crates/forge/tests/cli/test_cmd.rs

Was causing issues on this repro: https://github.com/foundry-rs/foundry/actions/runs/15111542394/job/42473841799 but confirmed this is not a PR related issue 
Temporarily added an override of `mainnet` with an RPC known to work well whilst retaining test setup itself

ci: fix flaky fork test using `StdChains`, add temporary workaround for `eth.llamarpc.com` being down

---

Cargo.lock
Cargo.toml
crates/fmt/src/formatter.rs
crates/fmt/src/solang_ext/ast_eq.rs
crates/fmt/src/solang_ext/loc.rs
crates/fmt/src/solang_ext/mod.rs
crates/fmt/src/visit.rs
crates/fmt/testdata/NonKeywords/fmt.sol
crates/fmt/testdata/NonKeywords/original.sol
crates/fmt/testdata/VariableDefinition/fmt.sol
crates/fmt/testdata/VariableDefinition/original.sol
crates/fmt/testdata/VariableDefinition/override-spacing.fmt.sol
crates/fmt/tests/formatter.rs
crates/forge/src/cmd/fmt.rs

- backport https://github.com/foundry-rs/foundry/pull/10509 and https://github.com/foundry-rs/foundry/pull/10556 in v1.2.0

Backport fmt fixes to 1.2.0

---

.config/nextest.toml

Hopefully reduces CI flakiness

test: increase retry delay from 3s to 5s

---

crates/anvil/src/eth/backend/mem/mod.rs

chore: Simplifing mined_logs_for_block filter

---

Cargo.lock
Cargo.toml

chore: bump version to 1.2.1

---

crates/evm/core/src/backend/mod.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue10552.t.sol

* forge(fix): update persistent storage from active db
* Clippy
- backport fix for #10552 to v1.2.1
- backport fix for flaky test https://github.com/foundry-rs/foundry/pull/10549

bug(forge test): panic crash on foundry v1.1+ (backport to v1.2.1)

---

Cargo.lock
Cargo.toml
crates/cheatcodes/src/evm.rs
crates/forge/tests/cli/test_cmd.rs

- backport fix for https://github.com/foundry-rs/foundry/issues/10544 to v1.2.1
- bump version 1.2.1

fix(forge): vm.cool mark cold instead storage cleaning (backport to v1.2.1)

---

crates/test-utils/src/rpc.rs

Continue running into limits here with DRPC
https://github.com/foundry-rs/foundry/actions/runs/15185825715/job/42710438452
Let's see if this helps

ci: use Optimism mainnet instead of DRPC due to limits

---

crates/test-utils/Cargo.toml

- doesn't seem like this is needed anymore and should fix the cargo warning

chore: remove ui_test patch

---

crates/forge/tests/cli/lint.rs
crates/lint/src/sol/gas/keccak.rs
crates/lint/src/sol/gas/mod.rs
crates/lint/src/sol/high/incorrect_shift.rs
crates/lint/src/sol/high/mod.rs
crates/lint/src/sol/info/mixed_case.rs
crates/lint/src/sol/info/mod.rs
crates/lint/src/sol/info/pascal_case.rs
crates/lint/src/sol/info/screaming_snake_case.rs
crates/lint/src/sol/med/div_mul.rs
crates/lint/src/sol/med/mod.rs
crates/lint/src/sol/mod.rs
crates/lint/testdata/MixedCase.stderr
docs/dev/lintrules.md

chore(lint): correct some spans

---

CONTRIBUTING.md
Makefile

Found the naming to be a bit confusing and `make help` didn't display all relevant commands
Clean up `Makefile`  and mention `make` commands in contribution guide
The `codespell` check was broken before

chore: clean up Makefile and update contribution guide

---

crates/anvil/src/eth/api.rs

this is now unlocked after we bumped alloy

chore: use dedicated accountinfo type

---

crates/cast/src/lib.rs

just replace .on_builtin with connect

docs: update deprecated .on_builtin with connect

---

Cargo.lock
Cargo.toml

chore: bump version to 1.2.2

---

crates/cast/src/args.rs

- backport https://github.com/foundry-rs/foundry/pull/10671 to 1.2.2

fix(cast): read all lines for message to hash (#10671) (backport to 1.2.2)

---

crates/test-utils/src/ui_runner.rs

Hi! I found broken link and fixed this.

chore: fixed dead link in `ui_runner.rs`

---

Makefile

Noticed `.PHONY`'s were missed in https://github.com/foundry-rs/foundry/pull/10602
Fixes `Makefile` by adding correct `.PHONY` tags and fix indentation when running `make help`

chore(`Makefile`): add .PHONY, fix help formatting

---

crates/common/src/constants.rs

some chains have only the r value

chore: add additional check for is_impersonanted

---

Cargo.lock
Cargo.toml

- bump version for next bugfix release

chore: bump version 1.2.3

---

Cargo.lock
Cargo.toml
crates/anvil/tests/it/anvil_api.rs
crates/cast/src/cmd/call.rs
crates/cast/src/lib.rs
crates/cast/tests/cli/main.rs
crates/evm/core/src/opts.rs
crates/forge/src/cmd/eip712.rs
crates/forge/tests/it/fuzz.rs

- backport https://github.com/foundry-rs/foundry/pull/10710 fix for https://github.com/foundry-rs/foundry/issues/10705
Chores
- backport clippy fix: https://github.com/foundry-rs/foundry/pull/10687
- backport flaky test fix: https://github.com/foundry-rs/foundry/pull/10691
- bump version to 1.2.3: https://github.com/foundry-rs/foundry/pull/10712

fix(cast): do not use default overrides if no override arg (v1.2.3 backport)

---

crates/script-sequence/src/sequence.rs
crates/script/src/multi_sequence.rs
crates/script/src/simulate.rs

feat(script): keep script / tx timestamp as milis instead seconds

---

.gitignore

chore: gitignore CLAUDE instructions and settings

---

.github/workflows/release.yml

- fixes #10743
- new gh action release v2.3.0 breaking https://github.com/softprops/action-gh-release/releases/tag/v2.3.0
- pin to v2.2.2

fix: pin action gh release to v2.2.2

---

crates/anvil/src/eth/api.rs
crates/anvil/tests/it/gas.rs

bug(anvil): incorrectly adds +1 gas when estimating transactions with explicit empty data field

---

crates/forge/src/cmd/bind_json.rs
crates/forge/src/cmd/eip712.rs

Fixes https://github.com/foundry-rs/foundry/issues/10788

fix: eip712, bind-json solar cleanups

---

.github/workflows/test.yml

ci: don't check all features

---

.github/workflows/nextest.yml

- ref https://github.com/taiki-e/install-action/issues/1005

chore: pin nextest version in ci

---

crates/cheatcodes/src/test.rs
testdata/default/cheats/GetChain.t.sol

fix(forge): vm.getChain use config for rpc and alias

---

crates/cast/tests/cli/main.rs

- ref test added in https://github.com/foundry-rs/foundry/pull/10710 check for success and redact returned tuples should suffice

chore: fix failing test

---

crates/anvil/core/src/eth/transaction/mod.rs

missing 7702 handling
closes https://github.com/foundry-rs/foundry/issues/10852

fix: receipt conversion

---

crates/cast/src/cmd/call.rs

This PR adds more unit tests to the `cast call` command.

Add more unit tests to `cast call`

---

crates/verify/src/etherscan/mod.rs

chore: add trace for contract_abi error

---

crates/anvil/src/eth/backend/mem/cache.rs

this should be spawned on blocking task

fix: spawn state writer blocking

---

crates/config/src/lib.rs

closes #10926
~~but havent tested this @nikitastupin-matterlabs~~

feat: add mesc chainid lookup

---

crates/forge/assets/CounterTemplate.s.sol
crates/forge/assets/CounterTemplate.t.sol

- fix lint - Counter template unused imports

chore: remove unused import in Counter template

---

crates/forge/tests/cli/test_cmd.rs

- https://scroll-mainnet.chainstacklabs.com/ is unavailable

fix(ci): ignore scroll test

---

crates/anvil/src/eth/backend/mem/mod.rs

chore: clippy fix

---

crates/cast/src/cmd/call.rs
crates/cast/tests/cli/main.rs

- fixes #10930 
- account override state diffs

fix(cast): account state diffs overrides

---

crates/lint/src/sol/info/imports.rs
crates/lint/testdata/Imports.sol
crates/lint/testdata/Imports.stderr

ref:
- https://github.com/foundry-rs/foundry/issues/10984

fix(forge-lint): [unused imports] check path slice 

---

crates/anvil/src/eth/backend/mem/storage.rs

chore: return reorged blocks

---

Cargo.lock
crates/anvil/src/args.rs
crates/cast/src/args.rs
crates/chisel/Cargo.toml
crates/chisel/src/args.rs
crates/cli/src/opts/global.rs
crates/cli/src/utils/mod.rs
crates/evm/core/src/fork/multi.rs
crates/evm/traces/src/identifier/signatures.rs
crates/forge/src/args.rs

Try reducing the number of tokio runtimes we spawn

chore: centralize and reduce number of spawned tokio runtimes

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/api.rs

Adding support for reth `debug_codeByHash` method.
See: https://github.com/paradigmxyz/reth/issues/14479

feat: add support for passthrough of `debug_codeByHash`

---

crates/forge/tests/cli/test_cmd.rs

- re https://github.com/foundry-rs/foundry/actions/runs/16405630004/job/46351112980#step:12:318
- redact gas for newly introduced `revm_27_prank_bug_fix` test

chore: fix isolate test workflow

---

crates/anvil/src/eth/backend/mem/mod.rs

we can lookup the local db first here

chore: lookup codehash locally

---

crates/anvil/Cargo.toml
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/state.rs

we've moved this feature to alloy-evm entirely and can now reuse this
we can do the same for state overrides next

feat: use alloy-evm apply overrides

---

crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/state.rs
crates/anvil/src/eth/error.rs

chore: use alloy-evm::apply_state_overrides

---

crates/cast/src/cmd/call.rs
crates/cast/src/cmd/run.rs
crates/cli/src/opts/rpc.rs

- closes #11084 
- use all providers (to include remappings) if `cast call` / `cast run` with `--with-local-artifacts` arg
- manually tested ticket, test is quite heavy to add (install project with deps, run anvil, deploy, run cast)

fix(cast): use all providers if local artifacts used

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/utils.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/evm.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/stack.rs

chore: more StackInspector cleanups

---

crates/forge/src/opts.rs

feat(forge): "add" alias for install subcommand

---

crates/anvil/src/eth/api.rs

fix: use existing functions for accountinfo

---

crates/common/src/compile.rs
crates/common/src/preprocessor/mod.rs
crates/evm/evm/src/executors/fuzz/mod.rs
crates/evm/fuzz/src/lib.rs
crates/evm/traces/src/decoder/mod.rs
crates/evm/traces/src/identifier/signatures.rs
crates/forge/src/cmd/coverage.rs
crates/forge/src/cmd/test/mod.rs
crates/forge/src/coverage.rs
crates/forge/src/result.rs

`#[instrument]` and clean up. No functional changes intended.

chore: add some more instrumentation

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/assets/cheatcodes.schema.json
crates/cheatcodes/spec/src/vm.rs
testdata/cheats/Vm.sol

Closes https://github.com/foundry-rs/foundry/issues/11165.

chore: make all random cheatcodes view

---

crates/evm/evm/src/inspectors/stack.rs

`with_stack` just needs an inspector with the current state and clearing `self`, so pass by reference instead of creating a new inspectorstack which boxes the cheatcodes
cc @klkvr i think this is right

chore: don't build an inspector stack

---

Cargo.lock
Cargo.toml

Bump version 1.3.1

---

crates/forge/tests/cli/test_cmd.rs

- ref https://github.com/foundry-rs/foundry/actions/runs/16736994558/job/47377744410#step:12:543

chore: fix isolate workflow

---

crates/lint/src/sol/codesize/unwrapped_modifier_logic.rs
crates/lint/testdata/UnwrappedModifierLogic.sol
crates/lint/testdata/UnwrappedModifierLogic.stderr

ref: https://github.com/foundry-rs/foundry/issues/11202

fix(lint): disable unwrap-modifier-logic for assembly

---

crates/forge/src/cmd/build.rs

- closes #11219 explicit lint errors

fix(lint): explicit message when lint on build failures

---

crates/forge/tests/cli/config.rs
crates/lint/src/sol/mod.rs

- closes #11227 by accounting registered codesize lints

fix(lint): account codesize registered lints

---

crates/cast/src/cmd/call.rs

fix: small cast call fixes

---

crates/wallets/src/wallet.rs

closes #11245 
error includes name of the expected var

feat(cast) more descriptive errors for `gcp` & `aws` signers

---

.github/workflows/benchmarks.yml
.github/workflows/bump-forge-std.yml
.github/workflows/docker-publish.yml
.github/workflows/nextest.yml
.github/workflows/nix.yml
.github/workflows/release.yml
.github/workflows/test.yml
Makefile
crates/config/src/soldeer.rs

This PR aggregates changes from the following PRs:
- #10038: Make Soldeer Dependency field public by @TilakMaddy
- #11139: upgrade to Node.js 24 by @Daulox92
- #11274: CI: migrate workflows to checkout v5 by @rejected-l
- #11246: fix: add missing semicolon in typos error message in Makefile by @dizer-ti

chore: aggregate PRs: #10038, #11139, #11274, #11246

---

crates/anvil/core/src/eth/wallet.rs
crates/anvil/src/eth/error.rs

This PR aggregates changes from the following PRs:
- Closes #11283 by @\oooLowNeoNooo
- Closes #11285 by @\Sharilleed223

chore: aggregate PRs

---

crates/evm/fuzz/src/strategies/mutators.rs

- ref https://github.com/foundry-rs/foundry/actions/runs/16984534390/job/48150813892?pr=11303#step:12:2241
- the interesting* could be a noop change, especially the 1 byte value, could be changing 0 to 0 for example
- validate mutations

chore: validate address and word mutations

---

crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil.rs

feat: added fake sig in executor

---

Cargo.lock
benches/Cargo.toml
benches/src/results.rs

chore(benches): use std instead num_cpu

---

crates/evm/coverage/src/inspector.rs

Don't need helper function anymore

chore: use get_or_calculate_hash better

---

crates/lint/src/sol/codesize/unwrapped_modifier_logic.rs

closes: #11357
Replaced `Severity::Gas` with `Severity::CodeSize`

fix(lint): 'unwrapped-modifier-logic' incorrectly marked with `Severity::Gas`

---

crates/evm/traces/src/identifier/etherscan.rs

- regression introduced with https://github.com/foundry-rs/foundry/pull/11194
- closes #11351

fix(forge): handle error if etherscan identifier cannot resolve config

---

crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/lib.rs

Upcasting was stabilized since then, so we can just add it as a super trait.

chore(cheatocodes): remove as_debug

---

Cargo.lock
Cargo.toml
crates/evm/core/src/backend/mod.rs

- ref #11378 
- reverts change done in https://github.com/foundry-rs/foundry/pull/11196 (keeps unit tests)
- updates revm to rev that skips the drain if checkpoint is greater than expected
- should be accommodated in master / new revm release, related Git commit: https://github.com/bluealloy/revm/commit/d9cda3ad8ce75ed772072bc3b55cdf3e959e18cf

fix(forge): do not panic on checkpoint revert

---

crates/anvil/src/eth/backend/mem/inspector.rs
crates/cheatcodes/spec/src/cheatcode.rs
crates/cheatcodes/spec/src/function.rs
crates/cheatcodes/src/error.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/lib.rs
crates/cli/src/utils/mod.rs
crates/common/fmt/src/dynamic.rs
crates/common/fmt/src/exp.rs
crates/common/src/calc.rs
crates/common/src/constants.rs
crates/common/src/io/shell.rs
crates/common/src/io/stdin.rs
crates/common/src/traits.rs
crates/config/src/lib.rs
crates/config/src/utils.rs
crates/debugger/src/tui/draw.rs
crates/doc/src/parser/mod.rs
crates/evm/core/src/backend/mod.rs
crates/evm/fuzz/src/lib.rs
crates/evm/traces/src/identifier/local.rs
crates/forge/src/cmd/clone.rs
crates/forge/src/cmd/inspect.rs
crates/lint/src/inline_config.rs
crates/verify/src/utils.rs

Remove `#[inline]` where it's not needed for performance.

chore: remove a bunch of unnecessary #[inline]

---

crates/cast/src/cmd/artifact.rs
crates/cast/src/cmd/constructor_args.rs
crates/cast/src/cmd/creation_code.rs
crates/cast/src/cmd/interface.rs
crates/common/src/abi.rs
crates/common/src/contracts.rs

chore: extract fetch_abi_from_etherscan and use &Config

---

README.md

docs: fix merkle rpc url

---

crates/common/fmt/src/ui.rs

this would panic if e.g. a node uses milliseconds as timestamp

chore: check timestamp value before fmt

---

crates/anvil/core/src/eth/transaction/mod.rs

Fix: invalid tx input error in anvil component

---

Cargo.lock
Cargo.toml

- ref https://github.com/foundry-rs/foundry/issues/11512
- will backport to v1.3 and tag

fix: bump version v1.3.4

---

Cargo.lock
Cargo.toml
crates/cast/tests/cli/main.rs
crates/forge/tests/it/repros.rs
deny.toml

fix bump v1.3.4
- closes #11512 backports bump version

fix: bump version v1.3.4 (#11514)

---

crates/cast/src/cmd/storage.rs
crates/chisel/src/source.rs
crates/common/src/compile.rs
crates/common/src/preprocessor/mod.rs
crates/config/src/inline/natspec.rs
crates/evm/traces/src/debug/sources.rs
crates/forge/src/cmd/bind_json.rs

Towards https://github.com/foundry-rs/foundry/issues/11456.

chore(evm): re-use project output in SourceData

---

crates/forge/tests/it/cheats.rs

- passed with https://github.com/foundry-rs/foundry/actions/runs/17486156456/job/49665486325

chore: fix isolate workflow, exclude state diff

---

Cargo.lock
Cargo.toml
crates/cast/src/cmd/call.rs
crates/cast/tests/cli/main.rs

- backports state override fix to v1.3 https://github.com/foundry-rs/foundry/pull/11553 (issue https://github.com/foundry-rs/foundry/issues/11551)
- bump version to v1.3.5

chore: Bump 1.3.5, backport state overrides fix

---

crates/forge/src/cmd/update.rs

- when we update a dep to branch like `forge update foundry-rs/forge-std@master` in a project with multiple deps e.g.
```json
{
"lib/LayerZero-v2": {
"rev": "88428755be6caa71cb1d2926141d73c8989296b5"
},
"lib/devtools": {
"rev": "01c1eaeb123e4364fbe96cdddf875640edf2566c"
},
"lib/forge-std": {
"rev": "a3dca253700f19f15b1837c57c67b9388f5cc3fb"
},
"lib/murky": {
"rev": "5feccd1253d7da820f7cccccdedf64471025455d"
},
"lib/openzeppelin-contracts": {
"rev": "69c8def5f222ff96f2b5beff05dfba996368aa79"
},
"lib/solady": {
"branch": {
"name": "main",
"rev": "acd959aa4bd04720d640bf4e6a5c71037510cc4b"
}
}
}
```
then do not update / ignore other deps pinned on branches (like solady in example above)
- quite complex to add a test, can be checked on https://github.com/ithacaxyz/account/

fix(forge): update only the specific dep

---

crates/anvil/src/lib.rs

In rust projects if you have a `.envrc `or you have exported `RUST_LOG=my_crate=info` it will stop showing the anvil logs silently and unexpectedly. Was very confusing experience.
Only use the env filter when the `RUST_LOG` explicitly mentions `anvil` or `node` or if it is a blanket filter like `RUST_LOG=trace`

fix(anvil): use RUST_LOG only in explicit or blanket filter

---

crates/test-utils/src/rpc.rs

chore: switch node back

---

crates/forge/tests/cli/config.rs

chore: fix ci, remove unwrap on test

---

crates/forge/src/coverage.rs

See https://github.com/rust-lang/rust/issues/146701.

fix: Rust breaking change

---

crates/sol-macro-gen/src/sol_macro_gen.rs

Fixes https://github.com/foundry-rs/foundry/issues/11701.

fix(forge): don't check Cargo.toml on module bindgen

---

Cargo.lock
crates/anvil/src/config.rs
crates/cast/src/cmd/call.rs
crates/cast/src/cmd/run.rs
crates/cast/tests/cli/main.rs
crates/evm/evm/src/executors/trace.rs
crates/evm/networks/Cargo.toml
crates/evm/networks/src/celo/transfer.rs
crates/evm/networks/src/lib.rs
crates/test-utils/src/rpc.rs

- infer network from chain id (passed as arg in anvil, retrieved from fork evm env for cast run and send)
- add precompiles label, add test for cast run to show celo transfer precompile

feat(cast): apply network precompiles for cast run and call

---

Cargo.lock

Follow up of https://github.com/foundry-rs/foundry/pull/11728 to include fix https://github.com/alloy-rs/chains/pull/208

fix: bump alloy-chains 0.2.12

---

crates/cast/tests/cli/main.rs
crates/forge/tests/it/repros.rs

chore: reenable tests

---

crates/linking/src/lib.rs

https://github.com/foundry-rs/foundry/pull/11759#discussion_r2373700571
cc @klkvr

test: improve linker test infra

---

crates/anvil/src/eth/api.rs
crates/anvil/src/eth/fees.rs
crates/anvil/tests/it/eip4844.rs

we need to use the next blob fee here instead
this showed up in https://github.com/alloy-rs/alloy/actions/runs/17972876200/job/51119451501

fix: use next fee blob basefee for missing blob fee

---

crates/cast/src/cmd/call.rs

feat: add trace transaction opts

---

Cargo.lock
Cargo.toml

Reduce # of crates in crate graph
Remove unused features

deps: explicit features for some deps

---

crates/config/src/invariant.rs

chore: simplify InvariantConfig

---

crates/forge/src/cmd/test/mod.rs

Free traces to reduce peak memory usage

chore(test): clear gas report traces

---

Cargo.lock
Cargo.toml

Small bugfix when installing submodules
https://github.com/mario-eth/soldeer/releases/tag/v0.7.1
check https://github.com/mario-eth/soldeer/releases/tag/v0.7.1

Update to soldeer 0.7.1

---

Cargo.lock
Cargo.toml

We are releasing private packages.
Organizations can create private packages that can be pulled only if you are logged in.
Now teams can just use soldeer for their ALPHA projects as well.
https://github.com/mario-eth/soldeer/releases/tag/v0.8.0

Update to soldeer 0.8.0

---

crates/lint/src/sol/info/mod.rs
crates/lint/src/sol/info/named_struct_fields.rs
crates/lint/testdata/NamedStructFields.sol
crates/lint/testdata/NamedStructFields.stderr

Adds the lint in #11760, without a snippet. I'll leave the issue open for the snippet portion.

feat: struct initializer lint

---

crates/forge/src/cmd/coverage.rs

- closes #11898 
- filters out vyper sources from coverage

fix(coverage): filter out vyper sources

---

crates/evm/networks/README.md
crates/evm/networks/src/lib.rs

docs: foundry-evm-fuzz extensions

---

.gitignore

Ref https://github.com/foundry-rs/foundry/pull/11047#discussion_r2400668716.
Remove `build` since we have a few directories named build which conflict with the ignore. Also add some structure to it.

chore(meta): update .gitignore

---

crates/forge/assets/solidity/workflowTemplate.yml
crates/forge/assets/vyper/workflowTemplate.yml

Best practice is top-level `permissions: {}` and then grant on a case by case basis
No functional change

fix(`forge`): apply correct permission scoping in workflow templates

---

crates/cast/src/tx.rs

Found a few problems in tx.rs:
First spotted a redundant !self.legacy check - the code was checking the same condition twice inside nested if blocks. Removed the inner check since it's pointless.
When I ran cargo clippy -p cast --lib, got a warning about "unfulfilled lint expectation" for #[expect(clippy::large_enum_variant)] - clippy said the expectation wasn't being used. So I removed it thinking it was just dead code.
But then when we ran clippy with stricter settings (cargo clippy --workspace --all-targets --all-features -- -D warnings), got an error about huge size difference between enum variants (20 bytes vs 256 bytes).

fix(cast): clean up SenderKind enum and remove redundant checks
