foundry-rs/foundry

Cargo.lock, crates/anvil/src/eth/backend/time.rs, crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/init.rs, crates/forge/tests/cli/cmd.rs
Implements feature #5687 which allows a branch argument to be passed when initializing a forge repository from a template. Adds an additional argument `branch` which requires the `template` argument to exist.
```
forge init --template foundry-rs/forge-template --branch [branch_name]
```
=> Added branch functionality to forge init command

crates/evm/src/fuzz/mod.rs, crates/evm/src/fuzz/types.rs, crates/forge/src/result.rs
First part of https://github.com/foundry-rs/foundry/pull/5547 breaking into smaller chunks.
This PR refactors the `fuzz` function in order to have access to a more granular, single-step, function called `single_fuzz`.
It will let us in the context of the debugger to be able to run again the fuzzer on the last relevant (either a counter-example, or the first case, see the current imeplemtnation of the debugger launching https://github.com/foundry-rs/foundry/blob/master/crates/forge/bin/cmd/test/mod.rs#L209-L213 with this time debug traces (they are expensive, especially when fuzzed).
=> Debugger Refactor #1: fuzz single

crates/config/src/providers/remappings.rs
This is debug info, should be traced.
Trace and not println
Closes #5751
=> fix(`remappings`): do not output debug skip remapping info

crates/evm/src/fuzz/invariant/executor.rs
Resolve #5084 and prevent invariant tests with input args from panicking and crashing the program.
Ensure the invariant function does not have any input args before asserting the invariant. This allows any invalid tests to fail gracefully with a clear error message without affecting any other tests being run.
=> fix: invariant tests with input args don't panic

Cargo.lock, crates/anvil/src/lib.rs, crates/cast/bin/cmd/call.rs, crates/cast/tests/cli/main.rs, crates/common/Cargo.toml, crates/common/src/lib.rs, crates/common/src/provider.rs, crates/common/src/runtime_client.rs, crates/evm/src/executor/fork/multi.rs, crates/forge/bin/cmd/script/providers.rs, crates/forge/tests/it/fork.rs, crates/utils/src/rpc.rs
Super early attempt at supporting websockets and IPC for cast. (See #5022 )
Needs a lot more work and the DynamicProvider logic might be more suited to `ethers-rs`. 
Would appreciate any general approach feedback. Happy to continue the development, but anyone else is welcome to take it further (hopefully this gives a starting point). 
Tested with Alchemy websocket endpoint.
Main hurdles are that the Provider type is not known at compile time and that `build()` is synchronous, so need to connect if no client has been established. Using a `RwLock`, not sure if it absolutely necessary.
=> feat(cast): support websockets

crates/cast/bin/main.rs, crates/cast/bin/opts.rs, crates/cast/src/lib.rs
Resolve #4752 and implement `cast decode` to decode raw EIP2718 transaction payloads
=> feat: cast decode can decode raw eip2718 txns

crates/config/src/lib.rs, crates/forge/tests/cli/config.rs
ref #5782
This adds a `cancun = true` option to foundry.toml which enables Cancun SpecId.
This is a temp measure that will get phased out once solc recognizes the cancun version, until then the solc target and evm can be configured independently 
ref https://github.com/gakonst/ethers-rs/issues/2585
@snreynolds
This can be enabled by adding `cancun = true` to foundry.toml,
=> feat: add tmp cancun config value

crates/common/Cargo.toml
https://github.com/foundry-rs/foundry/issues/5783
https://github.com/foundry-rs/foundry/pull/5571 broke installing binaries using `cargo` due to workspace features being missing.
Ensure the correct features are included in the `cargo.toml`.
```
cargo install --git https://github.com/bernard-wagner/foundry --branch fix-ws-ipc --profile local forge cast chisel anvil
```
=> fix(common): include ws and ipc features

crates/cast/bin/cmd/create2.rs
While fixing previously prefix I broke suffix :man_facepalming: regex matching for create2 and suffered from it today
Adding $ to regex expression and the test
=> Fix create2 suffix regex

.github/workflows/test.yml
See https://github.com/foundry-rs/foundry/issues/5788
Ensure that `cargo install` works for all binaries as some workspace dependencies hide features that need to be explicitly declared by crates.
=> feat(ci): feature checks

Cargo.toml
Mainly an improvement taken from reth which has this profile. Dani and I usually have this locally but I thought I'd make this available here for anyone who wants to use this.
Adds a `debug-fast` profile which retains full debug symbols and does not strip any code info.
=> feat(cargo): add fast debug profile for perf

crates/forge/bin/cmd/init.rs
Closes #5720 
When installing thru templates, we were not using the proper path for cleaning the `.git` directory—we tried to clean the directory of the path we invoked the command from, not the actual project itself. blew my foundry `.git` folder a few times this way while debugging :D
=> fix(`forge`): properly clean git dir on path when installing thru template

Cargo.lock, Cargo.toml, crates/cast/Cargo.toml, crates/cast/bin/main.rs, crates/chisel/Cargo.toml, crates/chisel/bin/main.rs, crates/forge/Cargo.toml, crates/forge/bin/main.rs
Closes #5832 
jemalloc was brought in for performance increases on unix but we haven't had time to properly tune things so the allocator doesn't cause spurious issues on things specific to an OS, so we're removing it
we can totally reconsider having this later once we're done with bigger items
remove jemalloc
=> chore(all): remove jemalloc

crates/abi/abi/HEVM.sol, crates/abi/src/bindings/hevm.rs, crates/evm/src/executor/inspector/cheatcodes/env.rs, testdata/cheats/Cool.t.sol, testdata/cheats/Vm.sol
Closes #1340.
Motivation is wanting to have more accurate and easier gas tests in foundry without needing to do hacks around functions/setUp. Adds a cheatcode to reset a warm account to cold and it's storage to be untouched/cold via `vm.cool(address)`
> not familiar with the language/code so maybe some things are pretty wrong, would love some guidance on what to change or if something is missing!
it untouches the `Account.status` and clears all storage cache in the `Account` via `Account.storage`
also had some code relating to removing the `JournalEntry` for `JournalEntry::StorageChange` but it wasn't necessary for this to work in the tests i wrote - so i don't know if it's supposed to be cleared or not but it's not effecting how the gas is calculated at least in this basic test?
i'm not …
=> feat: `cool` cheatcode

Cargo.lock, crates/anvil/src/eth/backend/db.rs, crates/evm/src/executor/backend/diagnostic.rs, crates/utils/Cargo.toml, crates/utils/src/lib.rs, crates/utils/src/types.rs
It's extremely painful to have to write `u256_to_ru256(stuff)` when we could have a trait for this.
Add conversion traits for:
- Alloy -> Ethers
- Ethers -> Alloy
=> feat(`utils`): Add primitive types conversion traits

Cargo.lock, crates/fmt/Cargo.toml, crates/fmt/src/formatter.rs, crates/fmt/src/solang_ext/ast_eq.rs, crates/fmt/src/string.rs
Migrates the `formatter` crate to alloy
Migrate it
=> feat(`formatter`): migrate formatter crate to Alloy

Cargo.lock, crates/debugger/Cargo.toml, crates/debugger/src/debugger.rs, crates/debugger/src/lib.rs
Removes ethers from the debugger crate and replaces it with alloy.
=> feat(`debugger`): migrate `debugger` crate to alloy

Cargo.lock, Cargo.toml, crates/evm/Cargo.toml, crates/evm/src/executor/inspector/cheatcodes/env.rs, crates/evm/src/executor/inspector/cheatcodes/error.rs, crates/evm/src/executor/inspector/cheatcodes/expect.rs, crates/evm/src/executor/inspector/cheatcodes/ext.rs, crates/evm/src/executor/inspector/cheatcodes/fork.rs, crates/evm/src/executor/inspector/cheatcodes/fs.rs, crates/evm/src/executor/inspector/cheatcodes/fuzz.rs, crates/evm/src/executor/inspector/cheatcodes/mapping.rs, crates/evm/src/executor/inspector/cheatcodes/mod.rs, crates/utils/Cargo.toml, crates/utils/src/error.rs, crates/utils/src/types.rs
Followup to #5768, in which the `SolError` trait extensively used in cheatcodes is migrated.
This is not a comprehensive ABI encoding migration, as we're still missing some types necessary to migrate in full, plus cheatcodes are better migrated all at once instead of having to fix spillover from what is a single change. Still, this starts to introduce `dyn-abi` to the crate.
=> feat(`evm`): Migrate `SolError` trait to use `dyn-abi`, adapt cheatcodes

Cargo.lock, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/error.rs, crates/evm/src/executor/fork/init.rs, crates/evm/src/executor/opts.rs
Right now cargo deny, clippy and other ci tests might fail because https://github.com/bluealloy/revm/pull/724 was squashed and rebased against revm's master, which implements 4844, and the sha used doesn't exist anymore.
- Updates `revm` to use the latest commit on the branch we're using
- Accomodates the new `TxEnv`/`BlockEnv` fields by setting them to default. This should be non-consequential since we're not activating the cancun flag yet.
- Accomodates the new `EVMError`s fields by creating the corresponding tx/blockchain errors on anvil/evm. Should be non-consequential since we're not activating cancun yet.
Albeit both should be fine for current users, it might be the case that things might be misconfigured if ppl e.g solc team / uniswap team wants to test new opcodes @mattsse — so …
=> chore(deps): bump `revm`, accomodate new cancun struct changes

crates/evm/src/executor/backend/mod.rs
This PR is a follow up to https://github.com/foundry-rs/foundry/pull/5351 with a similar motivation. Namely, in the aforementioned PR, additional methods were added to `foundry_evm::Backend` in order to facilitate overriding storage slots in the database. However, a method to replace storage that exists on the `CacheDB` was not exposed, which is also useful (and has different semantics to `insert_account_storage` in that it assumes a `0` value for unset slots instead of trying to fetch it from the inner DB).
Expose the `replace_account_storage` storage on the `foundry_evm::Backend` in the same vain as the aforementioned PR.
For the API, I chose to use `revm::HashMap` instead of the Rust standard library `HashMap`. I'm not 100% sure this is the correct choice here (as I don't really have …
=> Expose `replace_account_storage` Method In Foundry EVM Backend

crates/cast/bin/cmd/storage.rs
Closes #5750 
we're letting etherscan give a bad message to the user if no api key is set. This properly bails out if we can't fetch from etherscan because there's no api key.
=> fix(`cast`): properly bail if no api key is set when fetching storage remotely

Cargo.lock, crates/forge/bin/cmd/test/mod.rs, crates/forge/bin/cmd/watch.rs
closes #5684
clap supports concatenated short flags which can lead to recursive watch spawm via `-vw`
this adds another cleanup check to remove any w from these flags
=> fix: clean watch command from concatenated short flags

CONTRIBUTING.md
Adds a small note to `CONTRIBUTING.md` illustrating that we currently strip debug info on the default debug build, and should be re-enabled if a contributor wanted to use a debugger.
=> docs(`contributing`): add note about using a debugger with foundry

Cargo.lock, crates/forge/tests/cli/multi_script.rs, crates/forge/tests/cli/script.rs, crates/test-utils/Cargo.toml, crates/test-utils/src/script.rs
Migrates the test-utils crate. As with most crates, there are a few `ethers_solc`/`rpc` types left.
=> feat(`test-utils`: partially migrate test-utils crate

crates/evm/src/coverage/anchors.rs, crates/evm/src/coverage/mod.rs, crates/evm/src/executor/inspector/coverage.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/script/broadcast.rs, crates/forge/bin/cmd/script/build.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/script/providers.rs, crates/forge/bin/cmd/script/receipts.rs, crates/forge/bin/cmd/script/runner.rs, crates/forge/bin/cmd/script/sequence.rs, crates/forge/bin/cmd/script/transaction.rs, crates/forge/bin/cmd/script/verify.rs, crates/forge/bin/cmd/snapshot.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/bin/cmd/verify/etherscan/mod.rs, crates/forge/bin/cmd/verify/mod.rs, crates/forge/bin/cmd/verify/sourcify.rs, crates/forge/src/multi_runner.rs, crates/forge/tests/it/config.rs, crates/utils/src/lib.rs
Migrates forge's primitive types to alloy. Types remaining from `ethers` are `solc`, `etherscan` and `rpc` related unless highlighted for discussion.
=> feat(`forge`): partial forge migration

crates/forge/bin/cmd/test/mod.rs
Closes #5845
After running `forge test`, the command would "halt" after printing "Ran X test suites: X tests passed, X failed, X skipped (X total tests)". This is because of the `test of tests` loop running immediately after which was introduced in #5753. This loop is only responsible for building and pushing decoders for every test which is only used if the `--debug` flag is present. Moving this `if should_debug` to only push those decoders removes that halting after the tests are finished running
=> chore(`test`): ensure decoder building occurs only when `--debug` is present

crates/forge/bin/cmd/test/mod.rs
Smol followup for #5879. There was duplicated work happening here, were decoded_traces was being built in `execute_tests`, when this already happens for each individual test. This vec was unused.
Remove it.
=> chore(forge): do not re-build decoded traces for all tests

crates/anvil/src/eth/otterscan/api.rs, crates/anvil/src/eth/otterscan/types.rs, crates/anvil/tests/it/otterscan.rs
Otterscan expects the `ots_blockDetails` function to return either a list of transaction hashes, an empty list, or for the field to not exist internally. This is defined by the formatter `transactions: Formatter.allowNull(Formatter.arrayOf(Formatter.hash), [])` in the typescript code.
Currently, we are returning the full transactions, which is causing the `block/{id}` page in Otterscan to crash. These changes will modify the response to only include the list of transaction hashes, allowing the Otterscan page to function normally.
=> fix(anvil): Fix ots_blockDetails

crates/evm/src/executor/inspector/cheatcodes/parse.rs, testdata/repros/Issue5808.t.sol
Resolve #5808 to enable disambiguous numeric hex string parsing
* Explicitly check that numeric strings being parsed via `*parseInt` or `*parseUint` cheats don't contain any non-numeric characters
* Throw if the above does not hold
* Modify test added in #5809 to verify new behavior
=> fix: enforce 0x prefix for numeric hex strings

Dockerfile
Upgrades the alpine image we're using to 3.18. 3.16 is around a year old already and seems to be causing issues with c-kzg.
=> chore(dockerfile): upgrade alpine to 3.18

Cargo.toml
Strings for `profile.debug` were recently added (in the last year, I don't know when, at least after 1.66) which makes older cargo versions fail to parse manifest, which in turn makes them not notify the user about the minimum `rust-version`
=> chore: use boolean for profile.debug for backwards compatibility

crates/anvil/core/src/eth/transaction/mod.rs
closes #5917
Note this will also be mitigated once we unify rpc types with 
https://github.com/paradigmxyz/reth/blob/7024e9a8e91e9546ffd20b5aae65e85888f591a6/crates/rpc/rpc-types/src/eth/call.rs#L109-L111
which already supports both variants
=> fix: add input alias

Cargo.lock, Cargo.toml, crates/chisel/Cargo.toml, crates/chisel/src/dispatcher.rs, crates/chisel/src/executor.rs, crates/chisel/src/runner.rs
Switches `chisel` to use `alloy` types. There's only a stray `ethers::types::Log` and `ethers::solc` types. the former will be removed once https://github.com/alloy-rs/core/pull/271 is merged, but these are not blockers for now.
=> feat: chisel migration

Cargo.lock, crates/cast/bin/cmd/estimate.rs, crates/cli/Cargo.toml, crates/cli/src/opts/transaction.rs, crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/test/mod.rs
Closes #5913
Closes #5923
@Evalir this is a cast bug because clap here goes via typeid not types and since this
https://github.com/foundry-rs/foundry/blob/master/crates/cli/src/utils/mod.rs#L81-L84
is still on ethers U256 this currently bugs out
fixed by updating the value parser for forge
added test for other crates that will catch these issues
=> test: add fuzz-seed tests

crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/doc.rs, crates/forge/bin/cmd/init.rs, crates/forge/bin/cmd/install.rs, crates/forge/bin/cmd/update.rs, crates/forge/tests/cli/cmd.rs
`forge init --template` would clone a repo, then delete the entire `.git` directory so that it could re-initialize the repository with a single commit in its history.
This clobbers submodule tracking and commits entire recursed submodules directly to the git tree.
Closes #5925
Instead of cloning the template repository:
- initialize the git repository
- fetch just the head of the specified template repository branch
- prepare a new commit using the commit at `FETCH_HEAD`
- `git reset` the branch to the prepared commit, leaving only a single commit in the history
The template test now checks that the `.git/modules` directory is intact when initializing from a template.
=> fix(forge):`forge init --template` correctly handles submodules

crates/chisel/src/executor.rs, testdata/cheats/Fs.t.sol
Let's get main CI back to green—this fixes some tests.
Fixes the failing tests:
- `testFsMetadata`: failing due to silly file endings on windows
- `chisel` cache tests: still investigating, but probably `create_dir_all` failures. Trying with installing a different solc version first.
=> chore(`ci`): fix some flaky tests

.github/scripts/matrices.py
The aarch64 tests are failing because the test binaries are ARM, but GitHub can't execute them. I don't think there is a "reverse Rosetta", i.e. a way to run ARM binaries on x86 mac, so I think the best thing to do for now is to disable.
This should be fine since the operating systems are still the same; the APIs are the same, so if it builds and works for x86, it should also build and work for ARM, provided no external deps are missing. Obviously, running the tests would still be more robust.
This should bring CI back to green on main
=> ci: disable aarch64 mac tests

crates/evm/src/fuzz/error.rs, crates/evm/src/fuzz/invariant/error.rs, crates/evm/src/fuzz/mod.rs
Resolves https://github.com/foundry-rs/foundry/issues/5891
Do not bomb on failing to create a counter example, rather just return raw trace. This seems like the a more suitable behaviour, regardless of the issues introduced with `targetInterface`. 
This is still not perfect, as we would want to decode the input when using `targetInterface`, but that would require a lot more changes to propagate the associated interfaces to the tracer.
=> fix(forge): BaseCounterExample for targetInterface

crates/forge/bin/cmd/script/transaction.rs
While working on metropolis, I found that create2 constructor arguments were not being deserialized and put in the `tx.arguments` array of the broadcast artifacts
Simply include a 32 byte offset (to remove the salt) and re-use the logic from CREATE transaction decoding
=> fix(script): decode create2 constructor args

crates/cast/bin/main.rs, crates/cast/bin/opts.rs
=> test: add sig test case

deny.toml
We've got a new security advisory for `tungstenite`, which is used on the current version of `axum` we run on anvil. We should eventually update axum to solve this, but the advisory is, for the most part, not too concerning to us. I think it's acceptable to just bypass it until we update `axum` which will entirely solve the problem
Update `deny.toml` to ignore tungstenite.
=> fix(`ci`): ignore tungstenite in deps for anvil

crates/abi/abi/HEVM.sol, crates/abi/src/bindings/hevm.rs, crates/evm/src/executor/inspector/cheatcodes/ext.rs, testdata/cheats/Time.t.sol, testdata/cheats/UnixTime.t.sol, testdata/cheats/Vm.sol
Fixes #5937.
For long-running scripts it is sometimes useful to measure certain parts and analyze their performance in order to optimize running time. `block.timestamp` does not provide a real-time system timestamp, and using `date` via `ffi` is not granular enough due to Mac OS lack of milliseconds support.
This feature will return an accurate timestamp, in milliseconds since unix epoch, as `uint`.
I've added the usual cheatcode components:
- Added function to `HEVM.sol`
- Generated abi bindings
- Added implementation to `foundry-evm` (specifically, `ext.rs`)
- Added Solidity tests in `testdata`
Implementation details:
- Using `SystemTime::now().duration_since(UNIX_EPOCH)`, following the [example from the docs](https://doc.rust-lang.org/std/time/struct.SystemTime.html#impl-SystemTime)
- …
=> Add vm.unixTime() cheatcode

Cargo.lock, Cargo.toml
We can come back to using the main revm branch instead of using my fork, as https://github.com/bluealloy/revm/pull/724 was merged.
=> feat(`deps`): use main revm branch

crates/cast/src/lib.rs
it would be great to be able to use cast to-unit with the rest of the ether units kwei, mwei, microether and milliether. The reason being for easy command-line decimal conversion of certain smart contract calls, e.g. USDC's balanceOf, which has a decimals of 6 rather than the standard 18
I have added the kwei , mwei , microether and miliether to the unit conversion. These are the conversion units that i have used. 
1. kwei - 3
2. mwei - 6
3. microether - 12
4. milliether - 15
If there are more things to add to the changes , please let me know. I would very much happy to help.
=> Support all ether units in to-unit #5962

crates/debugger/src/lib.rs
Currently, debugger highlights the 32-byte memory word that is being read/write in cyan/red when an
MLOAD/MSTORE is encountered, respectively.
But there are quite a few instructions that access memory, e.g. CALL, CALLDATACOPY, SHA3...
This update is to colorize the memory region (which may be of any size) for all of them.
This is an enhancement relevant to #4440. A related work #4681 was to highlight unaligned memory.
All instructions that access memory are considered. Memory regions are highlighted in cyan/red for
read/write, consistent with MLOAD/MSTORE. Also, memory regions that are just written by the previous
instruction is highlighted in green. Memory regions may be any length.
=> feat(debugger): Highlight memory region for any instruction

crates/anvil/src/eth/otterscan/api.rs, crates/anvil/tests/it/otterscan.rs, crates/debugger/src/debugger.rs, crates/evm/src/executor/mod.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs
Closes #5883
this fixes a bad fuzz filter check when debugger is enabled resulting in misconfiguration of the testrunner.
the filter function we're using to check if the target function is a fuzz function was only checking contracts not functions
tested against repro of #5883
=> fix: incorrect fuzz filter check

crates/cast/bin/cmd/run.rs, crates/common/src/constants.rs, crates/evm/src/executor/backend/mod.rs
closes #5987
this adds some fixes to replay, currently we don't support replaying system transactions, so this adds an error when the user attempts to replay a system transaction.
otherwise system txs are simply skipped for now, although we might be able to add support for OP system transactions now that revm has some OP support
=> fix: add missing checks for system transactions

crates/forge/bin/cmd/coverage.rs, crates/forge/tests/cli/coverage.rs
The change was made to close #5886 which would allow users to include a `--report-file` option on the `forge coverage --report lcov` command, that would let them choose the path for generating `lcov.info`
All I did was add the `report-file` field to the `CoverageArgs` struct and also the required imports like `use::clap::ValueHint` and `use std::path::PathBuf` to the `coverage.rs` file, then I added a `match` in the part of the code that previously generated the `lcov.info` file that would use path provided by the user to generate the file or just generate it in root if a path is not provided:
```rust
match self.report_file {
Some(_) => return LcovReporter::new(&mut fs::create_file(root.join(self.report_file.as_ref().unwrap()))?).report(&report),
None =>  return LcovReporter::new(&mut …
```
=> added report-file option and new coverage test

Cargo.lock, Cargo.toml
`revm` has recently received a bunch of changes that we've had to incorporate with using patches to keep track of master. Now this is all merged in, including alloy, so there's no point to use a patch now, meaning we can switch to the latest release.
=> chore(`deps`): use latest revm release instead of patch

Cargo.lock, crates/evm/src/executor/inspector/cheatcodes/ext.rs, crates/evm/src/executor/inspector/cheatcodes/mod.rs, crates/forge/Cargo.toml, crates/forge/tests/it/config.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6006.t.sol
Closes #6006
only checking for "e" is valid because this is a json::number
incorrect scientific notation check
=> fix: correct check for scientific notation

crates/cast/bin/cmd/run.rs
I was trying to get traces from a transaction on moonbeam by running the following command
```
cast run --rpc-url https://1rpc.io/glmr  0xc8ab251113930754a43389dcae3750469fe2deb38ee6ab5c4869e5ea50615c1f  
```
I was hit with the error
Similar to https://github.com/foundry-rs/foundry/issues/4232 (fixed in #4238) I had to change the `prevrandao` config variable for `cast run`
With the following branch, i ran `foundryup` with my branch and was able to successfully run the command
=> fix(`cast`) fix `prevrando` config for `cast run`

crates/cast/bin/cmd/run.rs
Every time `cast run` was called, it would create an unnecessary `block.json` file.
=> fix(`cast`) Remove `block.json` file write for `cast run`

crates/evm/src/executor/inspector/cheatcodes/ext.rs
Spotted this in my terminal after running `foundryup`. I assume it got left in accidentally. 
Remove leftover println.
=> fix: remove println in get_env function

Cargo.lock, Cargo.toml
```log
Updating git repository `https://github.com/gakonst/ethers-rs`
Updating crates.io index
Updating aho-corasick v1.1.1 -> v1.1.2
Updating alloy-dyn-abi v0.4.1 -> v0.4.2
Updating alloy-json-abi v0.4.1 -> v0.4.2
Updating alloy-primitives v0.4.1 -> v0.4.2
Updating alloy-sol-macro v0.4.1 -> v0.4.2
Updating alloy-sol-type-parser v0.4.1 -> v0.4.2
Updating alloy-sol-types v0.4.1 -> v0.4.2
Updating errno v0.3.4 -> v0.3.5
Removing errno-dragonfly v0.1.2
Updating linux-raw-sys v0.4.8 -> v0.4.10
Updating proc-macro2 v1.0.68 -> v1.0.69
Adding ring v0.17.2
Updating rustix v0.38.17 -> v0.38.18
Adding spin v0.9.8
Updating syn-solidity v0.4.1 -> v0.4.2
Updating tokio v1.32.0 -> v1.33.0
Adding untrusted v0.9.0
Updating webpki v0.22.2 -> v0.22.4
```
=> chore(deps): bump Alloy to crates.io 0.4.2

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/proof/mod.rs, testdata/cheats/Fork2.t.sol
this fixes at least the rlp encoding bugs for proof nodes
ref #5004
still no idea what the bug with the proof is.
maybe @rkrasiuk can figure this out, 
maybe something here 
https://github.com/foundry-rs/foundry/blob/master/crates/anvil/src/eth/backend/mem/state.rs#L44-L44
but idk, this entire thing is giga cursed
=> fix: get_proof encoding bug

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/backend/db.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/genesis.rs, crates/anvil/src/eth/backend/mem/fork_db.rs, crates/anvil/src/eth/backend/mem/in_memory_db.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs
As per https://github.com/foundry-rs/foundry/issues/5805, picking up work back from https://github.com/foundry-rs/foundry/pull/5834.
`Box` the `dyn Db` so that the size is known at compile time. However, I'm stumped on how to actually swap one Boxed Db with another and would appreciate help with this.
=> feat(anvil): resume work on anvil reset starting a fork

crates/anvil/src/eth/api.rs, testdata/cheats/Fork2.t.sol
ref https://github.com/foundry-rs/foundry/issues/6036
eth_call can potentially blocking for a bit, so best to spawn this on a blocking task
=> chore: spawn eth call on blocking task

crates/forge/bin/cmd/test/mod.rs
When compiling with `sparse_mode = true` and `--silent` the compiler output is still not suppressed.
Similarly, it is expected that `--json` will result in only JSON output that can be piped to `jq` or saved as a file. Currently it has to be used as `--json --silent`. 
Expand the logic to cover all permutations of `--json, `sparse_mode` and `--silent`.
=> fix(forge): correctly suppress compiler output

Cargo.lock, crates/anvil/Cargo.toml, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/otterscan/api.rs, crates/anvil/src/eth/otterscan/types.rs, crates/anvil/tests/it/otterscan.rs
The otterscan `ots_getInternalOperations` was given incorrect values and
fully crashing when a `SELFDESTRUCT` was present.
The `type` field in the response for this endpoint is incorrectly serialized.
Wasn't handling `CREATE2` correctly.
* Use the `MinedTransaction` instead of a parity traces to have more
granular control on the specific transactions that we want to filter
out in the internal operations and the specific parameters that we want
to have access to.
* Fix the serialization for the`type` field in the response.
* Handle `CREATE2` generation.
* Add more tests for this endpoint.
=> feat(anvil): Fix `ots_getInternalOperations`

crates/cast/bin/opts.rs
`from-bin` command description is displayed with quotes.
```sh
$ cast --help | grep from-bin
from-bin               "Convert binary data into hex data." [aliases: --from-bin, from-binx, fb]
```
```sh
$ cast --help | grep from-bin
from-bin               Convert binary data into hex data. [aliases: --from-bin, from-binx, fb]
```
=> chore(cast): update `from-bin` command description

crates/forge/bin/cmd/verify/etherscan/mod.rs
Etherscan verification for non-mainnet chains requires a question mark at the end of the verifier url in order to prevent a forward slash from being added to the url which trips a cloudflare rule on requests from ec2 boxes.
Verification on both Goerli and Sepolia fails without this character present.
Hardhat-verify does not add the extra forward slash to the verifier url and has no issues verifying contracts on etherscan.
Fixes #4865, #5251, #5741
Fix etherscan contract verification on non-mainnet chains.
Add a question mark to the end of the verifier url.
=> fix(forge): fix `verify-contract` etherscan cloudflare bug

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/anvil_api.rs
closes #6096
this removes an outdated hack, that is no longer necessary and lead to wrong revert+1 block timestamps
=> fix: wrong subtract timestamp

crates/fmt/src/formatter.rs, crates/fmt/testdata/FunctionDefinitionWithFunctionReturns/fmt.sol, crates/fmt/testdata/FunctionDefinitionWithFunctionReturns/original.sol, crates/fmt/tests/formatter.rs
closes #4080
this adds a hardcoded check for function pointer return values, because they are formatting using the built-in formatter which means indents are applied twice.
maybe the better fix would be to check for this when actually formatting the argument chunk, but it looks like this issue is only limited to function return arguments.
=> fix: function returns formatting

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/anvil_api.rs
It seems that https://github.com/foundry-rs/foundry/pull/6097 wasn't sufficient to properly revert the block environment (latest block) after a snapshot revert. A simple `eth_call` that would return the latest block timestamp would show that it wasn't properly reverted.
I update the whole `self.env.block` to the past block-env, so that all fields for the current "latest" block are correct.
I also added a test, which calls the already on-chain deployed Multicall contract.
=> anvil: Fix snapshot revert not updating block-env correctly

crates/anvil/src/eth/backend/mem/mod.rs
Smol followup from #5986. Formats and pretty prints the `DynSolValues` we get from brute-force-decoding errors on anvil. This was previously done automatically by `Token`, but must now be done manually with DynSolValue.
=> fix(`anvil`): format DynSolValues for printing on anvil errors

Cargo.lock, crates/evm/Cargo.toml, crates/evm/src/fuzz/strategies/param.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6115.t.sol
Closes #6115
This fix should stop invalid `bytesX` values from being generated.
In general, we should refactor this part of the fuzzer to be able to handle errors more gracefully.
=> fix(`evm`): properly generate `bytesX` values with `arbitrary_from_type`

crates/evm/src/executor/inspector/cheatcodes/ext.rs
Added short blurbs on Rust's BTreeMap crate ordering system, specifying the caveat that Solidity structs must be declared alphabetically *except that uppercase and lowercase strings are treated differently where uppercase characters precede lowercase ones.
This should add clarity for developers using Foundry's nifty json parsing :)
++Typo/grammar fixes
=> Document BTreeMap lexicographical order

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/backend/mem/storage.rs
refactors how olds transactions are cleared, and clears all of them, also from the block.
=> perf: clear all transactions if exceeds configured keeper

crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/init.rs, crates/forge/tests/cli/cmd.rs
#6108 
Forge init --template fails when passing a directory that's different than the CWD since a git command is not ran in the correct context.
Change Git::fetch to a method and use the context from the instantiate Git object
=> Modified git fetch command to method to use correct root folder.

crates/forge/bin/cmd/create.rs
Alloy's `alloy_json_abi::Constructor` does not concat the bytecode to calls like `ethabi`, so we need to do it manually.
It'd be nice to have this on Alloy, so made an issue: https://github.com/alloy-rs/core/issues/388
=> fix(`create`): concat bytecode and constructor call to match old ethabi behavior

crates/forge/tests/cli/create.rs, crates/forge/tests/fixtures/can_create_with_constructor_args.stdout
test for https://github.com/foundry-rs/foundry/pull/6134
=> test: add forge create test

crates/common/src/abi.rs
Closes #6135 
Alloy's `Function` only parses functions without their return arguments and without the `function` prefix. We can use `AbiItem::parse` to parse them as human-readable abi strings and get a `Function` in return.
=> fix(`common`): properly parse functions in their usual form

crates/evm/traces/src/lib.rs
ref https://github.com/foundry-rs/foundry/issues/6139
removes the unreachable
=> fix: print decoded output value

crates/evm/core/src/decode.rs
closes #6144
should check selector not signature since signature is the abi signature and the 4 prefix is the selector
=> fix: use selector not signature

crates/anvil/src/eth/api.rs
treats invalid opcode as revert
closes #6138
=> fix: treat invalid opcode as revert

crates/cast/bin/main.rs, crates/config/src/utils.rs, crates/forge/bin/main.rs
we were loading the config before installing the error hook.
when we're loading the config we try to determine the project dir via git, if this results in an error (which we gracefully handle), eyre auto install an error hook if there isn't one set already
https://github.com/foundry-rs/foundry/blob/master/crates/config/src/utils.rs#L36-L36
fixed by installing error hook first
=> fix: always install error hook first

foundryup/foundryup
Issue https://github.com/foundry-rs/foundry/issues/6152
Fix the `foundryup` URI scheme to match that of GitHub's releases.
`https://github.com/foundry-rs/foundry/releases/download/<TAG>/foundry_<VERSION (no SHA)>_<PLATFORM>_<ARCH>.<EXT>`
**Metadata**
closes #6152
=> fix: `foundryup` URI scheme

crates/evm/traces/src/identifier/local.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/gas_report.rs
Closes #6019
ref #6129
refactors the gas reporter slightly.
also increases the diff matching used for matching contract codes
cc @mds1
=> fix: gas report threshold

crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/types.rs
adds support for block number as string in forking params
=> fix: support block number as string

crates/forge/bin/cmd/script/build.rs
ref https://github.com/foundry-rs/foundry/issues/6154
use foundry-fs for reading the file and add some context to the error
=> chore: use foundry fs

crates/evm/traces/src/decoder.rs
Fixes #6121.
This bug happened because we were only adding labels for unindexed params. We now need to restore the order of the indexed and unindexed params as alloy returns them separately, to be able to assign the labels properly.
=> fix: use both indexed and unindexed params when decoding logs

crates/cast/bin/cmd/send.rs
I have just wasted some ETH by running command `cast send --value X --rpc-url mainnet` without `to` param :(
`cast send --help` has the following statement:
```
Arguments:
[TO]
The destination of the transaction.
If not provided, you must use cast send --create.
```
However, by default, `cast send` without `to` will send transaction to zero address
Raise error when `cast send` is called without both `to` and `--create`
=> Raise error when neither `to` nor `--create` are present

crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/init.rs, crates/forge/bin/cmd/install.rs, crates/forge/bin/cmd/update.rs, crates/forge/tests/cli/cmd.rs
`forge update` recursively updates submodules, which causes submodules with out-of-date dependencies to become out-of-sync with their remote. This can lead to non-deterministic builds and a messy git working directory.
This PR makes the default behavior only to update root-level dependencies, while still recursively fetching any updated sub-dependencies.
It also adds a `--recursive` flag to mimic the old behavior, if for some reason it is desired.
Closes #5926.
Unfortunately, as I'm not familiar with this codebase or Rust generally – I'm not sure the best way to go about testing this. Would appreciate input and guidance.
- add `recursive` flag to `Git::submodule_update`
- add `submodule_foreach` to `Git`
- add `recursive` flag to `forge update`
- when `recursive` is false, initialize …
=> fix(forge): make  recursive `forge update` optional via `--recursive` flag

crates/common/src/evm.rs, crates/common/src/provider.rs, crates/evm/core/src/fork/multi.rs, crates/evm/core/src/opts.rs
Rebases #6085 to use the new file structure and refactor—couldn't rebase online on github and it was going to be a pain. Thanks @gr4yha7!
=> refactor(cheatcode): use rate limit args in create fork cheatcode

crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/invariant/mod.rs, crates/forge/src/runner.rs, crates/forge/tests/it/invariant.rs, testdata/fuzz/invariant/common/InvariantHandlerFailure.t.sol
Fixes #5726, fixes #6082, fixes #6024 
`fail_on_revert` was not getting respected correctly after a recent refactor, in which we stopped populating the `error` in `InvariantFailures`. This was causing mainly failures in handlers to not be detected leading to erroneous `[PASS]` states.
We were also collecting the logs and traces of the last error _twice_, which is not necessary as we replay the entire run. This could lead to situations where it seems an invariant gets called twice, but it's just the error log popping up twice.
=> fix(`invariants`): respect `fail_on_revert` properly and do not populate logs/traces twice

Cargo.lock
Bumps foundry-block-explorers to get the latest chains added.
Should fix the issue of users trying to verify with scroll.
=> chore: bump foundry-block-explorers

crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/mod.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/cli/coverage.rs
Improve forge coverage reporting of functions called during test `setUp`. This allows initializer functions, but not ctors, called during setUp (ex: https://github.com/foundry-rs/foundry/issues/4553) to be covered.
The `TestSetup` is extended to include coverage info. The `setUp` coverage is then merged with `HitMaps` generated by test runners.
Consider the coverage reporting of the `CounterTest:test_Increment` test generated by `forge init`. Prior to this change, we see that `Counter.setNumber` isn't covered because it's only called during `setUp`:
With this patch, we get full test coverage in `Counter.sol`:
=> fix(forge): add coverage to test setUp

crates/common/src/selectors.rs
Currently `forge selectors upload` command does not upload errors and events.
Closes #5924, #5241 and maybe #5012
Upload errors and events also. openchain.xyz API does not have a separate field for errors, so functions and errors are uploaded together. Same solution is used by openchain.xyz ["Import" page](https://openchain.xyz/signatures/import), so it seems to be considered a correct way which does not pollute the database.
=> Add support for events and errors in `forge selectors upload`

crates/cast/bin/cmd/wallet/mod.rs
I lacked the generation of multiple wallets as well as convenient output, so that parse values afterwards would be quite easy.
Added two parameters: json and number, whose values are initially set to false and 1 respectively.
=> feat: cast wallet generation - json output and many wallets generation

Cargo.lock, crates/anvil/Cargo.toml, crates/anvil/src/cmd.rs, crates/cast/bin/cmd/wallet/mod.rs
Added some new options in Anvil and Cast to ease mnemonic generation.
Added a "new-mnemonic" (or `nm`) option to generate a new mnemonic and generate a requested number of accounts from the mnemonic.
Example: `cast wallet nm --words 12 --accounts 6`
Generates a 12 words mnemonic and displays the first 6 accounts derived from that mnemonic.
Added 2 options:
- `mnemonic-random` to start Anvil with a randomly generated mnemonic 
- `mnemonic-seed` to provide a seed that generates a mnemonic. Useful for testing so that the base accounts are always the same
Examples:
```
anvil --mnemonic-seed 42
anvil --mnemonic-random
```
=> feat(anvil/cast): mnemonic generation

crates/evm/fuzz/src/lib.rs
=> fix(`fuzz`): remove harcoded hex prefix from calldata

crates/cast/bin/cmd/create2.rs
=> perf: better cast create2

.github/workflows/release.yml
If one fails, don't block the others from finishing
=> ci: don't fail-fast on release

crates/anvil/core/src/eth/utils.rs, crates/cast/bin/cmd/logs.rs, crates/cast/bin/cmd/wallet/vanity.rs, crates/cli/src/opts/ethereum.rs, crates/common/src/abi.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/traces/src/identifier/etherscan.rs, crates/forge/bin/cmd/script/transaction.rs
=> chore: more alloy cleanups

.config/nextest.toml, .github/workflows/heavy-integration.yml
Heavy integration tests ci is broken because the `local` profile doesn't exist
Create a `heavy` profile which is simple rn but we can modify later if we change this workflow
=> fix(`ci`): create heavy profile for heavy integration tests

crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/types.rs, crates/anvil/src/eth/api.rs, crates/anvil/tests/it/anvil_api.rs
Closes #6221. ref @antazoey
Adds the `anvil_metadata` method, which is the anvil equivalent of [`hardhat_metadata`](https://hardhat.org/hardhat-network/docs/reference#hardhat_metadata).
The instance ID is random and changes on every node boot, or when `anvil_reset` is called.
=> feat(`anvil`): `anvil_metadata`

crates/cli/src/utils/cmd.rs
=> fix: add arbitrum sepolia to list of networks with diff gas calc and batch support

crates/forge/bin/cmd/script/build.rs, crates/forge/tests/cli/script.rs
currently, when running `forge script` without the `--target-contract`/`--tc` argument, forge will fail to identify the expected target contract if interfaces are declared in the same file, like in the following example:
```solidity
// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.22;
contract Script {
function run() external {}
}
interface Interface {}
```
error:
```
Multiple contracts in the target path. Please specify the contract name with `--tc ContractName
```
the ux can be improved by ignoring artifacts with zero-length bytecode.
=> 🚸 script: ignore interfaces when inferring target

crates/cast/bin/main.rs
=> fix(`cast`): use selector() instead of signature for cast event-sig

Cargo.lock, crates/cheatcodes/src/env.rs, crates/cheatcodes/src/json.rs, crates/cheatcodes/src/string.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue5808.t.sol, testdata/repros/Issue6070.t.sol
The static encoder is too inflexible for this task. We can still use it for defaults tho.
Closes https://github.com/foundry-rs/foundry/issues/6070
Closes https://github.com/foundry-rs/foundry/pull/6268
Closes #6265 via alloy-rs/core#410
=> refactor(cheatcodes): rewrite string parsing with dyn abi

crates/cli/src/opts/build/core.rs, crates/config/src/lib.rs, crates/forge/bin/cmd/flatten.rs, crates/forge/tests/cli/cache.rs
while the config supported a `cache: bool` value already, it was effectively ignored.
this adds a `--no-cache` bool to the build args and uses the config's `cache` value when a project is configured.
=> feat: add --no-cache and respect cache config value

.github/workflows/test.yml, crates/anvil/tests/it/otterscan.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/lib.rs, crates/forge/tests/cli/ext_integration.rs, crates/test-utils/src/macros.rs, crates/test-utils/src/util.rs, testdata/cheats/UnixTime.t.sol
=> fix: trace decoding off-by-one

crates/forge/tests/cli/cmd.rs, crates/forge/tests/cli/doc.rs, crates/forge/tests/cli/ext_integration.rs, crates/test-utils/src/util.rs
Windows is here to ruin the day
I just want green CI for once
<https://github.com/foundry-rs/foundry/actions/runs/6824376973>
=> ci: fix windows external tests

crates/test-utils/src/util.rs
=> fix: windows ci part 69

Cargo.lock, crates/common/src/calc.rs, crates/common/src/fmt.rs, crates/evm/core/src/decode.rs, crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/fuzz/Cargo.toml, crates/evm/fuzz/src/lib.rs, crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/cli/cache.rs, crates/forge/tests/cli/script.rs, crates/forge/tests/it/core.rs
- use Debug for strings
- add exponential notation hint to signed integers too
- use `"assertion failed"` instead of `"<no data>"` when assertions fail in fuzz tests
=> feat: improve error decoding and value formatting

crates/doc/src/builder.rs, crates/doc/src/document.rs, crates/doc/src/preprocessor/contract_inheritance.rs, crates/doc/src/preprocessor/git_source.rs, crates/forge/bin/cmd/doc.rs
Closes #5761 and adds ability to generate docs for external dependencies via `--include-libraries` flag
List of documents now always contains all `.sol` files found in lib directories. They are getting filtered out if `--include-libraries` is off when the mdbook is generated.
- `ContractInheritance` preprocessor captures inherited contracts from external libraries only if `--include-libraries` is on
- `GitSource` preprocessor never generates git source links for contracts from external libraries
- `InheritDoc` always includes contracts from external libs when matching `@inheritdoc` statements
=> feat(doc): Include extrernal libraries into forge doc scope

crates/evm/core/src/backend/mod.rs, testdata/cheats/loadAllocs.t.sol
The `loadAllocs` cheatcode currently does not persist loaded account information if it is called in the `setUp` function. This is because none of the loaded accounts were marked as touched during the loading process.
Touch each account that is loaded into the `revm` journal in the `load_allocs` function in the DB backend.
Added a regression test for the fixed bug, asserting that the loaded accounts are persisted when the cheatcode is called in `setUp`.
=> fix(forge): `loadAllocs` cheatcode doesn't persist when called in `setUp`

crates/forge/tests/cli/test_cmd.rs, crates/forge/tests/it/config.rs, crates/forge/tests/it/test_helpers.rs, crates/test-utils/src/fd_lock.rs, crates/test-utils/src/lib.rs, crates/test-utils/src/util.rs, testdata/.gitignore
Previously, the first N tests, which start concurrently, would all compile testdata/ and write cache independently. Now, the first test will compile it, and the rest will read from cache.
=> test: compile testdata/ only once

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/defs/src/vm.rs, crates/cheatcodes/src/utils.rs, testdata/cheats/Vm.sol
Closes #6270
add `computeCreateAddress` and `computeCreate2Address` to cheatcodes.
As suggested in [comment](https://github.com/foundry-rs/foundry/issues/6270#issuecomment-1807187525), I transformed these code in [forge-std](https://github.com/foundry-rs/forge-std/blob/37a37ab73364d6644bfe11edf88a07880f99bd56/src/StdUtils.sol#L97-L134) to cheatcodes.
I am very new to rust, please correct me if any thing is wrong.
=> feat(`cheatcodes`): add computeCreateAddress cheatcodes

crates/cast/tests/cli/main.rs, crates/common/src/selectors.rs
This PR fix a bug on `cast upload-signature` with error prefix.
#6311 
the code should add error signature to function field.
=> fix(cast): upload error signature

Cargo.lock, crates/anvil/core/Cargo.toml
just making the optional dep non optional in dev-deps isn't sufficient
=> chore: enable anvil-core serde feature by default in tests

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/cast/bin/cmd/run.rs, crates/common/src/evm.rs, crates/common/src/provider.rs
=> docs: update cups link

Cargo.lock, crates/anvil/Cargo.toml, crates/anvil/core/Cargo.toml, crates/anvil/server/Cargo.toml, crates/anvil/server/src/handler.rs, crates/anvil/server/src/lib.rs, crates/anvil/server/src/ws.rs
And `fdlimit`
The only breaking change is that only one extractor can consume the response body, so the handler has to come before the response in the HTTP handler function.
Additionally, the [Axum changelog recommends](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#extractors) changing `Extension` to `State`.
cc @mattsse
=> chore(deps): bump axum to 0.6

crates/forge/bin/cmd/script/mod.rs
Per the new [canyon hard fork](https://blog.oplabs.co/canyon-hardfork/), push0 is supported on all superchain testnet networks.
Remove the warning
(Eventually we should have a better way to add/remove these warnings rather than a static list, but we can think about this later)
=> chore(`script`): remove PUSH0 warnings for superchain testnets

Cargo.lock, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/tests/it/otterscan.rs
RLP decoding is incomplete: `rlp.data()` decodes a header and returns the next `header.num` bytes, but this is always 0 if the raw rlp data already starts with a tx type
See also Reth impl and docs https://github.com/paradigmxyz/reth/blob/0b46e16dcdc9012810726bee410047fea8be7cf9/crates/primitives/src/transaction/mod.rs#L1317C1-L1347C2
=> fix(anvil): TypedTransaction rlp decode, bump k256

crates/cast/bin/cmd/storage.rs, crates/common/src/compile.rs, crates/forge/bin/cmd/inspect.rs, crates/forge/bin/cmd/selectors.rs, crates/forge/src/gas_report.rs
=> chore: tables cleanup

testdata/cheats/ExpectRevert.t.sol
Ref https://github.com/foundry-rs/foundry/issues/6331
=> test: add an expectRevert test

crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/error.rs
`eyre::Report` on library code is not good.
Use `TransportError`.
Note that this introduces a few panics, all marked with TODOs, for which we need a nice way to make a custom error with TransportError.
=> feat: use `TransportError` on Anvil

crates/anvil/core/src/eth/mod.rs, crates/anvil/tests/it/genesis.rs
Tests were commented to avoid the compiler tripping up. Now this isn't needed as these are fixed
uncomment, also fix up smol genesis test
=> fix(`anvil`): uncomment serde tests, fix genesis test

crates/common/src/runtime_client.rs
Hi, this is my first contribution to foundry so hello everyone :wave: ! The explanation for this simple fix is pretty long, so please bear with me 😅 , because performance is greatly increased.
I was looking at issue #6204 and noticed the profiler logs that @DaniPopes provided:
https://github.com/foundry-rs/foundry/issues/6204#issuecomment-1798317194
> Can reproduce as well. Profiling shows that 80% of the time is spent in `rustls_native_certs::load_native_certs`: https://share.firefox.dev/463tYIx
`rustls_native_certs::load_native_certs` will load the root TLS certificates of the system in order to use them when making HTTPs requests. This happens when we build our HTTP request provider for `ethers_providers` using `reqwest` inside the `RuntimeClient` (and coincidentally, where my fix is …
=> fix: Improve `cast` performance on macos - Only load root TLS certificates with HTTPs rpc-url

foundryup/foundryup
Fixes #6329
TIL that using `||` on a function disables the global `set -e` for the function. lol.
5:18
https://youtu.be/30YWsGDr8mA?si=FfN-Fdbadxu_yJnZ&t=318
=> fix(foundryup): actually make `set -e` work

Cargo.lock, crates/anvil/Cargo.toml
This k256 version breaks revm, as documented in
https://github.com/RustCrypto/elliptic-curves/issues/988, which breaks foundry.
While I would instead wait to bump revm, foundry nightly (the only supported version per the provided GH action) is broken and I'd rather correct it ASAP.
Foundry nightly is broken.
Revert the k256 bump until revm supports k256 0.13.2.
=> Revert k256 bump

crates/anvil/src/eth/api.rs, crates/cast/bin/cmd/create2.rs
See #6353 for full motivation.
The `--caller` flag just picks the first 20 bytes (address) of the salt to be used in different CREATE2 factories that require such a protection.
closes #6353 
The salt generation will now start from the 24th byte of the 32 byte salt, instead of the first byte.
If the flag is empty, the first 20 bytes of the salt will be left empty. If not, the first 20 bytes will be filled with the address and the next 4 bytes will always be empty (the pointer offset is 24 and not 20 so the address of the `usize` object it's being cast to stays aligned)
I have also written unit tests for this flag.
Also, @DaniPopes please double check that the program remains memory safe. The loop should still need to fill up an entire u32/u64 object in order to overflow, like in the …
=> feat(`cast create2`): Added `--caller` flag

crates/anvil/core/src/types.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/anvil_api.rs
I need external access to the list of anvil snapshots
my use case: I want to expose snapshot/revert functionality on [Iron wallet](http://github.com/iron-wallet/iron), but it should be able to support snapshots created outside of it too. there's currently no way to get a list of snapshots unless I control their creation too
Adding them to the `anvil_metadata` endpoint seemed like the intuitive solution. Not sure if there are unintended side-effects behind this? I  can move to a dedicated endpoint if needed
=> Adds snapshot map to anvil metadata

crates/cheatcodes/src/env.rs
Closes #6374
prevents leaking env value via `alloy::parser::Error`
=> fix: don't leak env parser error

crates/evm/core/src/fork/backend.rs
Remove an old `U64::to` cast (the returned type is no longer `U64`)
=> fix: remove stray cast

crates/cheatcodes/spec/src/vm.rs
Global attribute applies to every item, while we only want it for the contract.
=> chore: generate less sol! abi implementations

crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/script/transaction.rs, crates/forge/tests/cli/script.rs, testdata/cheats/Broadcast.t.sol
Right now `AdditionalContract.init_code` is written with `0x` prefix and deserialized with `"hex"` which is not able to parse '0x' prefix.
This makes impossible resuming any deployments which have non-empty `additionalContracts` for any transaction.
Change type to `alloy_primitives::Bytes`
=> Additional contracts serialization fix

Cargo.lock, Cargo.toml, crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/eth/state.rs, crates/anvil/core/src/eth/transaction/ethers_compat.rs, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/otterscan/types.rs, crates/anvil/src/lib.rs, crates/anvil/src/pubsub.rs, crates/anvil/tests/it/anvil.rs, crates/anvil/tests/it/anvil_api.rs, crates/anvil/tests/it/api.rs, crates/anvil/tests/it/gas.rs, crates/anvil/tests/it/logs.rs, crates/anvil/tests/it/main.rs, crates/anvil/tests/it/otterscan.rs, crates/anvil/tests/it/proof/mod.rs, crates/anvil/tests/it/pubsub.rs, crates/anvil/tests/it/sign.rs, crates/anvil/tests/it/transaction.rs, crates/anvil/tests/it/txpool.rs, crates/anvil/tests/it/wsapi.rs, crates/evm/core/src/utils.rs, crates/utils/src/types.rs
=> chore(`anvil`): fix tests

crates/forge/bin/cmd/script/multi.rs
Fixes bug introduced in #6271 which causes all multichain scripts ran with `--verify` flag to exit after broadcasting first sequence.
Bug happens because in the following match statement when `self.verify` is true, `return` statement returns from the function and skips all left sequences
```rust
Ok(_) => {
if self.verify {
return sequence.verify_contracts(config, verify.clone()).await
}
Ok(())
}
```
=> Fix multichain scripts with verify

crates/doc/src/builder.rs, crates/doc/src/document.rs, crates/doc/src/writer/as_doc.rs
Closes #6386
we used the hardcoded default output dir when computing the relative path for `Inherits: <path>`
this now uses the configured output target
=> fix: derive Inherit relative link properly

crates/anvil/src/hardfork.rs
Closes #6392
anvil supports cancun already
this just enables it via `--hardfork cancun`
left some todos in there that we need to fill once settled, but the code isn't actually used.
Motivation for this is to unblock uniswap dev like we did with the temp cancun option for forge even though solc doesn't have it yet
=> chore: enable cancun hardfork

crates/chisel/src/dispatcher.rs, crates/chisel/src/executor.rs, crates/chisel/src/runner.rs, crates/debugger/src/lib.rs, crates/evm/core/src/debug.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/evm/src/inspectors/chisel_state.rs, crates/evm/evm/src/inspectors/debugger.rs, crates/evm/evm/src/inspectors/stack.rs, crates/evm/traces/src/inspector.rs, crates/evm/traces/src/lib.rs
likely fixes #6396
we were recording Sharedmemory which is very excessive.
This only records the context memory
=> perf: dont record sharedmemory

crates/cheatcodes/src/inspector.rs, crates/chisel/src/executor.rs, crates/chisel/src/runner.rs, crates/evm/evm/src/inspectors/logs.rs, crates/evm/traces/src/lib.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/script/runner.rs, crates/forge/src/multi_runner.rs, crates/utils/src/lib.rs, crates/utils/src/types.rs
=> chore: impl To* traits for Bytes

crates/cast/bin/opts.rs
ref https://github.com/foundry-rs/book/pull/1052
=> test: add cast proof test

crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/eth/serde_helpers.rs
Needed to port some serde helpers to support proper serialization.
Ports some needed serde helpers, and also fixes up some serde tests which had multiline strings from them getting commented.
=> fix(anvil): port serde helpers, remove multiline jsons

crates/fmt/src/formatter.rs, crates/fmt/testdata/ArrayExpressions/fmt.sol, crates/fmt/testdata/ArrayExpressions/original.sol, crates/fmt/testdata/FunctionCall/bracket-spacing.fmt.sol, crates/fmt/testdata/FunctionCall/fmt.sol, crates/fmt/testdata/FunctionCall/original.sol, crates/fmt/testdata/FunctionType/fmt.sol, crates/fmt/testdata/FunctionType/original.sol, testdata/cheats/Prank.t.sol, testdata/cheats/RecordAccountAccesses.t.sol
The formatter currently doesn't handle `new` expressions, which leads to https://github.com/foundry-rs/foundry/issues/4619.
This PR fixes that by adding the relevant case in the formatter. The tests have been adjusted to reflect this. They do not pass without the fix, but pass with the fix added.
Please note that the existing test cases had `new uint[](length)` in several places, where the type is not normalized to `uint256`. In my opinion, the behavior after the fix (convert those to `uint256`) is correct, and the test files were wrong.
Thus, I adjusted all occurences of `new uint[]` in the `fmt.sol` files.
A new test case for `new Contract()` expressions has been added to the `FunctionCall` test, since those expression can be seen as a function call to the constructor.
NOTE: cargo fmt …
=> fix(forge): format `new` expressions

crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/eth/transaction/ethers_compat.rs, crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/genesis.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/genesis.rs, crates/anvil/src/lib.rs, crates/anvil/src/pubsub.rs, crates/anvil/tests/it/api.rs, crates/anvil/tests/it/gas.rs, crates/anvil/tests/it/otterscan.rs, crates/anvil/tests/it/proof/mod.rs, crates/anvil/tests/it/transaction.rs, crates/common/src/lib.rs, crates/common/src/provider/mod.rs
This removes some glue that was added from the RPC types by adding alloy types all over anvil unless they're internal types, which we can do later.
Remove glue, cleanup warnings on anvil.
=> chore(`anvil`): extend alloy types until entry lib, cleanup warnings

Cargo.lock, Cargo.toml, crates/anvil/core/src/eth/transaction/ethers_compat.rs, crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/backend/mem/state.rs, crates/anvil/src/eth/otterscan/types.rs, crates/anvil/src/genesis.rs, crates/cheatcodes/src/evm/fork.rs, crates/cli/Cargo.toml, crates/common/src/provider/alloy.rs, crates/common/src/provider/ethers.rs, crates/evm/core/src/fork/init.rs, crates/evm/core/src/fork/multi.rs, crates/evm/core/src/opts.rs, crates/forge/tests/cli/script.rs, crates/forge/tests/fixtures/can_create_template_contract.stdout, crates/forge/tests/fixtures/can_create_using_unlocked.stdout, crates/forge/tests/fixtures/can_create_with_constructor_args.stdout
no need for local pinning anymore
pin to branch, resolve any related CI errors
=> chore: pin alloy providers to repo & test fixup

crates/anvil/tests/it/optimism.rs
deposit transactions are no longer allowed post regolith
pins the hardfork in test to Paris.
this requires a followup to clean up regolith/revm op error handling and support for OP hardforks
=> chore: set hardfork explicitily for deposit tests

crates/config/src/fmt.rs
Missed on https://github.com/foundry-rs/foundry/pull/6417
Set it as default
=> fix(`config`): actually set remove as default for `hex` underscores in `fmt`

Cargo.lock, crates/cast/Cargo.toml, crates/cast/bin/cmd/create2.rs
There is currently no way to randomize the initial nonce since it always starts at 0.
Randomize the nonce by default, with an optional `--seed`. This randomization can be disabled with `--no-random`.
Also fix a panic with `-j0`.
=> feat(cast): add options to randomize initial nonce

crates/forge/bin/cmd/create.rs
* adds `show_standard_json_input` to `forge create --verify`
=> chore: add --show-standard-json to forge create --verify

Cargo.lock, crates/forge/Cargo.toml
new watchexec releases appear to violate semver
breaks build if lockfile is removed
pin relevant crates for now
ref #6446
=> chore: pin watchexec

crates/forge/bin/cmd/bind.rs
add hint to skip cargo.toml consistency check in forge bind
=> chore: add hint to --skip-cargo-toml

crates/evm/core/src/backend/fuzz.rs, crates/evm/core/src/backend/mod.rs, crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/mod.rs, crates/forge/src/runner.rs, crates/forge/tests/it/repros.rs, crates/forge/tests/it/test_helpers.rs, testdata/repros/Issue6355.t.sol
closes probably #6355
Some background:
due to ds-test legacy behaviour failures are stored in a state variable.
Prior to https://github.com/foundry-rs/foundry/pull/4974
> Fuzzing was having soundness issues with snapshot failures. This is because snapshot failures were not being persisted throughout fuzz runs, and when the Fuzz Backend Wrapper we use was dropped, this information was lost, leading to inconsistent test PASS states.
because we were using a Cow of the `Backend` so regular fuzz runs don't need to clone it per fuzz call, however as #4974 highlighted this is unsound for snapshots because we lose state that contains the the state variable that tracks errors
#4974 tried to fix this by persisting snapshot failures in an AtomicBool. But this is also unsound because this is …
=> feat: use non atomic tracker for snapshot reverts

crates/common/src/provider.rs
if 127.0.0.1:8545 is provided, the URL will be a file, resulting in obscure OS errors.
since this input is very common, like localhost, prefix it with http
=> feat: prefix local address with http scheme

crates/cast/src/lib.rs, crates/forge/tests/cli/create.rs
ref #6332
wasn't able to reprocude this manually with a simple test case.
Though, I noticed after the crate refactor we can no longer use e2e tests for both forge and cast binary because they are in separate crates.
at least revised the error for empty contract.
=> chore: revise contract empty error

Cargo.lock, crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs, crates/anvil/tests/it/main.rs, crates/anvil/tests/it/optimism.rs, crates/common/src/types.rs
fixes most tests failures in #6219, which mainly happened due to us returning full blocks instead of non-full blocks when non-full blocks were requested. It also enables fork tests again which pass after fixing some edge cases regarding uncles.
The tests which are expected to fail are `ws` and `ipc`-related tests, as they still haven't been implemented.
=> [Alloy providers migration]: Fix tests

crates/cli/src/utils/cmd.rs
Moonbeam introduced MBIP-5 in which gas estimation deviated from Ethereum. The reasoning is that now storage changes are reflected now on gas estimation. This is to prevent spamming the network with junk data. This is a problem on a lot of cheap-to-transact networks
Solution was simple, just add Moonbeam-based networks to the `has_different_gas_calc` function (like with Arbitrum) [here](https://github.com/foundry-rs/foundry/compare/master...albertov19:foundry:albertov19/use-rpc-gas-estimation-moonbeam)
If this function returns `true` then gas estimation is done using the actual provider URL and `eth_estimateGas`.
=> RPC-based Gas Estimation for Moonbeam-based Networks

crates/forge/bin/cmd/create.rs
As described in #6466 , `forge create --verify` could not be called using `foundry.toml`
Update the etherscan API key from the Config in the information that is checked in the preflight. This means if no `ETHERSCAN_API_KEY` is set as an env var or flag, the config files will be used as opposed to failing the preflight check.
If a test is needed here, I might need my handheld. Very new to Rust, so also unsure if it's okay here to make `verify` mutable.
=> fix: forge create to use config values for verify preflight check

Cargo.toml
When you build the project, if you follow the rust version of the Cargo.toml, the project won't compile because of alloy-sol-macro not compiling.
The solution is simply to update rust version to 1.74
=> chore: update required version in the Cargo.toml

crates/debugger/src/lib.rs
Motivation can be found in #6472. This fixes a crash of the debugger when accessing memory offset or size for read/writes that are bigger than usize::MAX. The case presented in 6472 is now solved with this PR.
Also applied some formatting from rustfmt.
Closes #6472
Change the call to `to()` on `Uint256` to a call to `saturing_to()`.
=> fix: overflow of memory offset or size in debugger

crates/anvil/src/eth/backend/db.rs, crates/anvil/src/eth/backend/mem/fork_db.rs, crates/anvil/src/eth/backend/mem/in_memory_db.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs, crates/evm/core/src/backend/mod.rs, crates/evm/core/src/backend/snapshot.rs, crates/evm/core/src/fork/database.rs
this fixes an inconsistency highlited by #6463
fork db snapshots were always kept on revert, but state snapshots were always removed, the intended behaviour (ganache, hardhat compat) is to remove a snapshot on evm_revert
also related 
https://github.com/foundry-rs/foundry/pull/6366
=> chore: remove fork db snapshot

crates/anvil/core/src/eth/mod.rs
=> chore: add refs to ganache spec

crates/config/README.md
supersedes #6489 and improves it
=> docs: fix typos

crates/cast/src/lib.rs, crates/common/src/abi.rs, crates/evm/fuzz/src/strategies/param.rs, crates/forge/bin/cmd/script/mod.rs
Since 0.5, double-parse workaround is not needed anymore. 
Ref bad error message in #6497
=> chore: better parse error messages

crates/cli/src/utils/cmd.rs, crates/debugger/src/tui/builder.rs, crates/debugger/src/tui/context.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs, crates/evm/core/src/debug.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/bin/cmd/test/mod.rs
Slowly untangle the draw code. Will require yet another follow-up to clean up the actual implementation to not overload the diff of this PR.
Implement the draw functions as methods on the context.
=> refactor(debugger): use context when drawing

crates/cli/src/utils/mod.rs, crates/forge/bin/cmd/install.rs, crates/forge/tests/cli/cmd.rs, crates/test-utils/src/util.rs
Closes #6519 
Check if there are any submodules at all in the repo, and only update if so.
=> fix(`forge`): pre-emptively create `lib` dir if it doesn't exist for updating submodules

crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/script/verify.rs
per #6426
for script/create we want to skip is verified check (often false positives due to similar bytecode) and always try verification
=> chore: skip is verified check for script/create deployments

crates/evm/traces/src/decoder/mod.rs
Fixes bug introduced in #6504 which breaks decoding of function outputs
=> Fix function output decoding

crates/cheatcodes/src/inspector.rs, testdata/cheats/RecordAccountAccesses.t.sol
Deployed address is incorrect when broadcasting. Fixes https://github.com/foundry-rs/foundry/issues/6514.
The EVM behavior is slightly different when broadcast, `vm.startBroadcast()`, is enabled. During broadcast, the deployer address is set to the configured wallet. Previously, the record access cheatcode would always use the current EVM caller to compute the created address. This patch ensures that the appropriate caller is used.
=> fix(cheatcodes): recorded created account during broadcast

crates/evm/core/src/backend/mod.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6032.t.sol
Closes #6032
There was an edge case where the initialization function incorrectly replaced the AccountInfo of created accounts with the account info fetched from the fork.
The reason this function exists, is so we can reinitialize accounts that were touched before a fork was active with the account info of the fork. This is required so that the fork can use real accounts even if the account has been loaded previously. for example a getNonce check.
However, newly created accounts should be exempt from this check.
=> fix: don't reinitialize created accounts

.cargo/config.toml, Cargo.lock, crates/cli/src/utils/cmd.rs, crates/debugger/Cargo.toml, crates/debugger/src/lib.rs, crates/debugger/src/op.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs, crates/forge/bin/cmd/script/build.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/tests/cli/debug.rs, crates/forge/tests/cli/main.rs, crates/forge/tests/it/cheats.rs, crates/forge/tests/it/config.rs, crates/forge/tests/it/core.rs, crates/forge/tests/it/fork.rs, crates/forge/tests/it/fs.rs, crates/forge/tests/it/fuzz.rs, crates/forge/tests/it/inline.rs, crates/forge/tests/it/invariant.rs, crates/forge/tests/it/spec.rs, crates/forge/tests/it/test_helpers.rs
Debugger refactor finale.
Previous PRs:
- https://github.com/foundry-rs/foundry/pull/6491
- https://github.com/foundry-rs/foundry/pull/6494
- https://github.com/foundry-rs/foundry/pull/6495
- https://github.com/foundry-rs/foundry/pull/6520
=> refactor(debugger): rewrite draw code

crates/evm/core/src/fork/cache.rs
a better solution to the problem.
check any missing fields using the default
=> chore: solve breakin serde env changes once and for all

crates/debugger/src/tui/mod.rs, crates/forge/bin/cmd/test/mod.rs
Closes #6546
cc @iFrostizz I'm not sure why `debug` is disabled on fuzz tests? Added in https://github.com/foundry-rs/foundry/pull/5753
=> fix(debugger): don't panic when arena is empty

Cargo.lock, crates/common/Cargo.toml, crates/common/src/traits.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/test/filter.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs, crates/forge/tests/it/config.rs, crates/forge/tests/it/core.rs, crates/forge/tests/it/fork.rs, crates/forge/tests/it/fuzz.rs, crates/forge/tests/it/inline.rs, crates/forge/tests/it/invariant.rs, crates/test-utils/src/filter.rs
Starting to clean up the mess that is test code.
=> refactor: only use channel to return test results

crates/common/src/compile.rs
ref https://github.com/foundry-rs/foundry/issues/6541
convert panic into meaningful error
=> chore: better error for missing contract bytecode

crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/inspector.rs, testdata/cheats/RecordAccountAccesses.t.sol, testdata/cheats/Vm.sol
`vm.startStateDiffRecording` should track the `BALANCE` and `EXTCODE*` family of opcodes, since they affect account warmth
Closes #6544 
Adds 4 more values to the `AccountAccessKind` enum and watches for those 4 opcodes as part of `step`.
=> feat(forge): account access cheatcode accounts for extcode* and balance opcodes

crates/cheatcodes/src/env.rs, testdata/repros/Issue6070.t.sol
Small env values could make it ugly
https://github.com/foundry-rs/foundry/pull/6555 followup
=> fix(cheatcodes): env error formatting

flake.lock, flake.nix
This PR adds a nix flake definition for a dev shell that provides the necessary components to building and testing foundry.
In order to compile and test successfully, the workspace requires Rust nightly, solc and libusb. These dependencies must be installed by users and could be provided system wide. However, it's a good idea to provide nix users with a pre-configured devShell that includes all these dependencies.
A nix flake is a deterministic definition file that configures the required nix packages that must be present in the PATH when developing a project.
The shell can be activated with the `nix develop` command and provides the rust toolchain on nightly with clippy and rustfmt, the solidity compiler at v0.8.20 and libusb1.
=> chore: add nix flake for dev shell

crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/local.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/tests/cli/test_cmd.rs, crates/forge/tests/fixtures/repro_6531.stdout, crates/test-utils/src/util.rs
Currently, while decoding result of function execution in traces, the following is done:
1. If function appears in ABIs of some contract seen during execution and identified by it's bytecode, ABI is taken from this contract bytecode.
2. Otherwise, ABI is fetched from openchain.xyz
This works fine for decoding inputs, however, openchain.xyz does not (and can not) tell anything about output types of a function.
Due to this, outputs for any calls to external contract accessed by an interface in forked environment are not decoded at the moment.
An example of this behavior is following test:
```solidity
pragma solidity 0.8.20;
import {Test} from "forge-std/Test.sol";
interface IERC20 {
function balanceOf(address) external view returns (uint256);
}
contract TestTracing is Test {
function test() …
```
=> tracing: Improve decoding of functions output

crates/config/src/fs_permissions.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6554.t.sol
Closes #6554
make permission checking more granular.
allows adding deviating rules for sub-folders.
before we found the first matching permission.
now this finds the deepest matching permission.
For example, for path "./cache/file.txt" with
```
fs_permissions = [{ access = "read", path = "./"}, { access = "write", path = "./cache"}]
```
this will use `{ access = "write", path = "./cache"}`
=> feat: support overlapping permissions

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm.rs, crates/evm/core/src/backend/fuzz.rs, crates/evm/core/src/backend/mod.rs, crates/evm/core/src/snapshot.rs, testdata/cheats/Snapshots.t.sol, testdata/cheats/Vm.sol
ref #6411
since we're persisting snapshots on `revertTo` we have unbounded memory growth.
We want to keep them for convenience, so we need additional cheatcodes to handle cleanup:
* revertToAndDelete (I picked this one over overloading `revertTo`, not sure what would be the best UX, but we could add an overloaded function as well (id, bool))
* deleteSnapshot
* deleteSnapshots
FYI @maa105 @karlb
=> feat: add additional snapshot cheatcodes

crates/anvil/tests/it/ipc.rs, crates/anvil/tests/it/main.rs
=> feat(`ipc`): enable anvil ipc tests

crates/anvil/src/eth/backend/mem/mod.rs, crates/evm/core/src/backend/mod.rs, crates/evm/core/src/fork/init.rs
Fixes the failing moonbeam test.
=> fix(`anvil`): ensure prevrandao is set

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/common/src/types.rs
Finishes enabling all pre-existing trace support, using reth tracers.
=> feat: re-enable `debug_traceTransaction` support

crates/forge/tests/cli/test_cmd.rs, crates/forge/tests/fixtures/include_custom_types_in_traces.stdout
ref #6579
add a test to ensure traces include custom types
=> test: add test for custom type decoding

crates/forge/bin/cmd/script/runner.rs, crates/forge/src/runner.rs
I have accidentally shadowed `sender_nonce` parameter while implementing #6300
Ref #6571
cc @mds1
=> Fix sender_nonce shadowing

crates/chisel/src/executor.rs
#4455 implemented the printing of event selectors (the hash of the event signature, similar to function selectors). During the migration to Alloy, this seems to have been accidentally removed / replaced.
This PR re-implements the printing of event signatures.
See `Selector` in the output below.
```
Welcome to Chisel! Type `!help` to show available commands.
➜ event SomeEvent(address addr);
➜ SomeEvent
Type: event
├ Name: SomeEvent(address addr)
├ Signature: "SomeEvent(address)"
└ Selector: 0x62e1088ac332ffa611ac64bd5a2aef2c27de42d3c61c686ec5c53753c35c7f68
```
=> feat: re-implement event selector printing

crates/anvil/tests/it/anvil_api.rs, crates/forge/README.md
GM!
I'm replacing two outdated external links with updated versions. One of them is pointing to GnosisSafe FAQ, second one to Foundry docs/book. Motivation is to keep external resources approachable.
The solution is self-explanatory in the changed files.
=> fix: update outdated links to external resources

crates/forge/bin/cmd/script/broadcast.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/bin/cmd/script/multi.rs, crates/forge/bin/cmd/script/sequence.rs, crates/forge/tests/cli/multi_script.rs
#4892 removed RPCs from general broadcast data and moved them to ./cache. However, for multichain sequences, RPC endpoints weren't saved anywhere which made resuming multichain scripts impossible
Save RPC endpoints used by multichain sequences to ./cache.
Ref #5047
=> Fix multichain scripts resume functionality

crates/chisel/src/executor.rs
Now that we have `alloy`, `chisel` can display information about the size of `uint` / `int` types.
**Metadata**
closes #5705
=> feat(chisel): add bit size information to `int` & `uint` types

crates/forge/bin/cmd/coverage.rs
`forge coverage` ignores the `config.toml` file for invariant tests. 
Invariant testing in coverage mode thus uses the default 256 runs which is small, making coverage for big invariant tests noisy/useless. This is not the case for regular (non-invariant) tests. 
This would bring us closer to having invariant tests as contributing fully to coverage (#4007).
Fixes #6565.
The coverage runner now takes the correct `config` given when running tests. 
This is my first time writing Rust ever, so do feel free to ignore/rewrite completely.
=> fix(forge): Don't ignore config.toml when running invariant tests for coverage

Cargo.lock, Cargo.toml, crates/cast/Cargo.toml, crates/evm/coverage/src/lib.rs, crates/forge/Cargo.toml, crates/forge/bin/cmd/coverage.rs, crates/forge/src/coverage.rs
The coverage testing in foundry is useful, but has many outstanding issues, eg those mentioned here:
https://github.com/foundry-rs/foundry/issues/1961
The barrier to entry in addressing these issues is relatively high, as the pipeline used to generate the reports is somewhat complex:
```
1.    build code ->
2.    execute tests recording EVM instruction level coverage ->
3.    construct mapping from bytecode addresses to source level coverage items -> 
4.    apply the mapping to the instruction level coverage to generage an abstract CoverageReport ->
5.    process  the CoverageReport to generate user friendly output as requested
```
and there is no useful visibility into the interior stages of this pipeline.
This PR adds a new coverage report, that provided human readable bytecode level …
=> Bytecode level coverage reporting

crates/fmt/src/comments.rs, crates/fmt/src/formatter.rs, crates/fmt/testdata/BlockComments/fmt.sol, crates/fmt/testdata/BlockComments/original.sol, crates/fmt/tests/formatter.rs
fixes a formatting bug where forge fmt would format with an additional new line before the function body
```
/**
* @dev See {IERC721-balanceOf}.
*/
function test_Increment() public {
counter.increment();
assertEq(counter.number(), 1);
}
```
=> fix: tightly pack doc comments

Cargo.lock, crates/doc/Cargo.toml, crates/doc/src/builder.rs, crates/doc/src/document.rs, crates/doc/src/preprocessor/infer_hyperlinks.rs, crates/doc/src/preprocessor/mod.rs, crates/doc/src/writer/as_doc.rs, crates/forge/bin/cmd/doc/mod.rs
Closes #4541
This replaces `{<Contract>-identifier}([display name])?` with a link to the referenced item if it can be found.
There are likely some edge cases that I've missed but we can fix them once they get reported.
wdyt @PaulRBerg
=> feat(doc): inline doc links

crates/fmt/src/formatter.rs, crates/fmt/testdata/EnumVariants/fmt.sol, crates/fmt/testdata/EnumVariants/original.sol, crates/fmt/tests/formatter.rs
Closes #6631
use indent based formatting for all variants
=> fix(fmt): properly format enums

crates/forge/bin/cmd/test/mod.rs
Closes #5528 
Closes #6613 
We were exiting before processing & printing traces. We wanna exit after.
=> fix(`forge`): fail fast after processing traces

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm/fork.rs, testdata/cheats/Vm.sol
"shadowed name" warnings on <0.8.0 for `addr` and `accesses`
=> fix(cheatcodes): silence warnings for older Solidity versions

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, testdata/cheats/Vm.sol
https://github.com/foundry-rs/forge-std/pull/487:
- `cool` is not done yet
- `AccountAccessKind` was accidentally stabilized in forge-std with a different order than its respective implementation here
=> fix(cheatcodes): update cool status, fix AccountAccessKind ordering

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs
Closes #6640
we used the basefee of the forked block on `reset` but we should use the `next basefee(forked_block)`
=> fix: use next base fee of forked block +1 on reset

crates/forge/tests/cli/ext_integration.rs
add sablier-v2 repo to external forgetests https://github.com/sablier-labs/v2-core
this is a useful test target to check nodejs deps
cc @PaulRBerg
=> test: add sablier-v2

crates/config/README.md
this link relative path is broken
replace those links
=> docs(crates/config): correct README.md link path

crates/evm/traces/src/decoder/mod.rs
Closes #6696 
Always omits the pk on addr, instead of doing so conditionally.
=> fix(cheatcodes): always omit pk on `addr`

Cargo.lock, crates/chisel/Cargo.toml, crates/chisel/bin/main.rs, crates/chisel/src/dispatcher.rs, crates/chisel/src/executor.rs
Closes #6610
adds more debug! and emits error if -vvv
=> chore: more chisel debug and print compile error

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, testdata/cheats/Vm.sol
Closes #6695 
Should be marked as `view`.
=> chore(`cheatcodes`): mark `getLabel` as view

crates/cheatcodes/src/config.rs, crates/cheatcodes/src/inspector.rs, crates/cheatcodes/src/utils.rs, crates/cli/src/utils/cmd.rs, crates/config/src/lib.rs, crates/evm/evm/src/inspectors/stack.rs, crates/forge/tests/cli/config.rs
Inspecting & testing transactions that require multiple address labels is quite painful at this point because it makes the cast command or test script unnecessarily verbose.
```bash
$ cast run <tx> \
--label 0x1F98431c8aD98523631AE4a59f267346ea31F984:"Uniswap V3: Factory" \
--label 0xC36442b4a4522E871399CD717aBDD847Ab11FE88:"Uniswap V3: Positions NFT" # ...
```
```solidity
vm.label(address(0x1F98431c8aD98523631AE4a59f267346ea31F984), "Uniswap V3: Factory");
vm.label(address(0xC36442b4a4522E871399CD717aBDD847Ab11FE88), "Uniswap V3: Positions NFT");
// ...
}
```
Add `labels` section in foundry config that allows to pre-label frequently used addresses. Most evm addresses are used as the same purpose across multiple chains, so the config is considered standalone …
=> feat(cast/forge): add label addresses in foundry config

Cargo.lock, crates/cast/Cargo.toml, crates/cast/bin/main.rs, crates/cast/bin/opts.rs, crates/cast/src/lib.rs
Sometimes, you don't have the source code/ABI for the contract but want to determine which functions exist, having only the deployed bytecode.
I am the author of the [EVMole](https://github.com/cdump/evmole) library, which addresses this problem. The library includes [reproducible benchmarks](https://github.com/cdump/evmole/tree/master#benchmark) for accuracy and speed, along with a comparison with other existing tools.
In this PR, I have added the `selectors` command to the `cast` tool, which uses my library for the task.
Example of using `cast code` to obtain the bytecode of the USD-T contract and `cast selectors` to extract selectors and arguments:
```sh
$ cast selectors $(cast code 0xdAC17F958D2ee523a2206206994597C13D831ec7)
0x06fdde03
0x0753c30c      address
0x095ea7b3 …
```
=> feat(cast): add `selectors` command to extract function selectors and arguments from bytecode

crates/cast/src/lib.rs
Fix unit logic which was untested due to code not compiling
=> fix: parse unit logics

Cargo.lock, crates/common/src/compile.rs
closes https://github.com/foundry-rs/foundry/issues/6707
supports parsing evmVersion
=> chore: bump foundry-compilers 0.1.3

crates/chisel/src/dispatcher.rs, crates/config/src/endpoints.rs, crates/config/src/lib.rs
related to #6532
add RpcEndpointConfig as described in the issue
=> feat: add rpc endpoint config

crates/common/src/fmt/ui.rs
`cast block <x>` does not display the transactions root of the block.
The block display format is updated to include the transactionsRoot. This also allows the only tx root to be specified via the `-f` flag.
=> feat(cast): Add transasctionsRoot to block fmt

crates/anvil/src/eth/backend/mem/inspector.rs
#6219 regression
closes #6733
this restores the previous behaviour and doesn't record steps by default which caused the mem spikes
=> fix: dont record step tracing by default

crates/cli/src/utils/cmd.rs, crates/common/src/contracts.rs, crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/fuzz/src/invariant/filters.rs, crates/evm/fuzz/src/invariant/mod.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/mod.rs, crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs
=> chore: remove JsonAbi import renames

crates/cheatcodes/src/inspector.rs, crates/evm/core/src/utils.rs, crates/evm/evm/src/inspectors/debugger.rs
=> chore(evm): use method instead of get_create_address util

crates/cast/bin/cmd/storage.rs, crates/common/src/contracts.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs, crates/evm/core/src/ic.rs, crates/evm/core/src/lib.rs, crates/evm/core/src/utils.rs, crates/evm/coverage/src/anchors.rs, crates/evm/traces/src/lib.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/script/executor.rs
=> chore: new-type IC/PC maps

crates/chisel/src/runner.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/evm/src/inspectors/stack.rs, crates/evm/fuzz/src/lib.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/script/runner.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs
=> chore: unify label map types to standard HashMap

crates/fmt/src/formatter.rs, crates/fmt/testdata/ConstructorModifierStyle/fmt.sol, crates/fmt/testdata/ConstructorModifierStyle/original.sol, crates/fmt/tests/formatter.rs
Closes #5633
This is a bit horrible and there can be edge cases because we can't know for certain if a modifier is actually a modifier or an inherited contract, so we do our best by checking inherited bases and assume lowercase is modifier
=> fix: dont strip empty () on constructors

crates/common/src/provider/retry.rs
new retry error unlocked
https://github.com/foundry-rs/foundry/actions/runs/7466523925/job/20318067711?pr=6750
=> chore: new retryable ratelimit error

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/db.rs, crates/anvil/src/eth/backend/mem/fork_db.rs, crates/anvil/src/eth/backend/mem/in_memory_db.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/main.rs, crates/anvil/tests/it/state.rs
Closes #5460
captures the BlockEnv when dumping the state and reinitializes it when reloading from file
=> feat: include block env in --dump state

crates/evm/core/src/backend/mod.rs, crates/evm/core/src/fork/multi.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6759.t.sol
closes #6759
this removes the URL hack and instead makes forks unique on the id level while also reusing existing backends.
This means forkIds are always unique but they can reuse existing backends
=> fix: make ForkIds unique

Cargo.lock, crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs
The `eth_getBlockReceipts` method is not implemented in `anvil`.
```json
{
"jsonrpc": "2.0",
"id": 0,
"method": "eth_getBlockReceipts",
"params": [
"0xdee810"
]
}
```
```json
{
"jsonrpc": "2.0",
"id": 0,
"error": {
"code": -32601,
"message": "Method not found"
}
}
```
- https://github.com/ethereum/execution-apis/pull/438
- https://github.com/ethereum/go-ethereum/pull/27702
- https://github.com/ledgerwatch/erigon/pull/1735
- https://github.com/paradigmxyz/reth/pull/3321
Fixed some issues in `alloy`, added `eth_getBlockReceipts` method implementation to `anvil` with unit tests.
- https://github.com/alloy-rs/alloy/pull/103
- https://github.com/alloy-rs/alloy/pull/104
=> feat(anvil): support eth_getBlockReceipts method

Cargo.lock, crates/anvil/core/Cargo.toml, crates/anvil/core/src/eth/subscription.rs
Part of #6715.
Removed all the unneeded types, and only `SubscriptionId` remains. Just use alloy/rand for this instead of pulling it from ethers.
=> chore(`anvil`): remove ethers usage on subscription

Cargo.lock, crates/anvil/core/src/eth/transaction/ethers_compat.rs, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/core/src/eth/utils.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/evm/evm/Cargo.toml, crates/evm/evm/src/inspectors/access_list.rs
Part of #6715.
Removes `EthTransactionRequest` usage everywhere where its capability to produce `TypedTransaction`s is not required, as this type will be migrated later along with typed receipt, and the block types. This removes a bunch of conversions throughout the API / in-mem backend. Also migrates the `AccessListTracer`.
=> chore(`anvil`): mostly remove EthTransactionRequest usage, migrate AccessListTracer

crates/anvil/core/src/eth/transaction/ethers_compat.rs, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/cheats.rs, crates/anvil/src/eth/backend/mem/mod.rs
Part of #6715. 
Migrates the cheats manager and pushes any conversions straight to the signing step, which will then be removed once signers are migrated. While it doesn't remove many conversions, it makes easier to remove them later with the new signers.
=> chore(`anvil`): migrate cheatsmanager to alloy

Cargo.lock, Cargo.toml, crates/cheatcodes/Cargo.toml, crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/assets/cheatcodes.schema.json, crates/cheatcodes/spec/src/cheatcode.rs, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/base64.rs, crates/cheatcodes/src/lib.rs, testdata/cheats/Base64.t.sol, testdata/cheats/Vm.sol
=> feat: `bytes` to base64 encoding in VM

crates/evm/fuzz/src/strategies/int.rs, crates/evm/fuzz/src/strategies/uint.rs
=> fmt: restore whitespace in fuzz files

Cargo.lock, crates/evm/core/Cargo.toml, crates/evm/core/src/backend/mod.rs, crates/evm/core/src/fork/multi.rs, crates/evm/core/src/opts.rs, crates/evm/core/src/utils.rs
I don't know why these are not Alloy, but for now they can be scoped down to just ethers-core and ethers-providers.
=> chore: don't use ethers in evm-core

crates/anvil/src/eth/backend/fork.rs, crates/anvil/tests/it/fork.rs
test case for https://github.com/foundry-rs/foundry/issues/6795
we still need to change how we track the best number for arbitrum forks and decouple it from env.blocknumber because those are L1 vs L2
=> test: add arbitrum fork test

crates/cast/bin/cmd/wallet/mod.rs
support cast wallet get-private-key from `mnemonic` and `mnemonic_index`
And I think `derive-private-key` would be more appropriate.
This PR implemented the feature request from issue #6729. 
Closes #6729 
mnemonic_index would be 0 by default. 
```
cast wallet derive-private-key "ten able puppy cart gadget change health must creek human bracket above"  
- Account:
Address:     0x688DB4fC60816A5838485d0ab9b4ef358f849c35
Private key: 0x9a900f2e6171a60dfd7871226c8a2a55e754678e62765d1ab189097e62dee418
```
```
cast wallet derive-private-key "ten able puppy cart gadget change health must creek human bracket above" 1
- Account:
Address:     0x81EbdaCabf245849412183f13cb83E9a7ffF2da4
Private key: 0x5fcd6ddc5471acbe3c0f48b43c5a0c4ca364b137a0340f01e38efbb85e7ce0ac
```
=> feat(cast): support `cast wallet derive-private-key`

Cargo.lock, crates/anvil/src/eth/backend/fork.rs, crates/common/src/provider/tower.rs
this fixes retry issues that previously didn't capture all error cases because the ResponsePacket can also be an error
=> fix: handle all payload errors

crates/forge/assets/CounterTemplate.s.sol, crates/forge/assets/CounterTemplate.t.sol, crates/forge/assets/generated/TestTemplate.t.sol
There is no reason to use `console2` anymore.
=> feat: stop using console2

crates/fmt/src/helpers.rs, crates/forge/bin/cmd/inspect.rs, crates/forge/tests/cli/cmd.rs
Closes #6816
formatted abi needs a name
=> fix: use provided name for inspect pretty

crates/evm/evm/src/executors/invariant/error.rs
closes #6666
there's an underflow bug in the invariant shrinking powerset call, resulting in vec alloc issues.
@brockelmore ptal
I used the repro example in #6666 to track this down
=> fix: capacity overflow on invariant shrinking

.github/scripts/prune-prereleases.js
Pruning rules:
1. only keep the earliest release of the month
2. to keep the newest 3 nightlies
Fixes #6732
Here is my local testing:
```
import { Octokit, App } from "octokit";
// Create a personal access token at https://github.com/settings/tokens/new?scopes=repo
const octokit = new Octokit({ });
// In case node 21 is not used.
function groupBy(array, keyOrIterator) {
var iterator;
// use the function passed in, or create one
if(typeof keyOrIterator !== 'function') {
const key = String(keyOrIterator);
iterator = function (item) { return item[key]; };
} else {
iterator = keyOrIterator;
}
return array.reduce(function (memo, item) {
const key = iterator(item);
memo[key] = memo[key] || [];
memo[key].push(item);
return memo;
}, {});
}
async function separateReleases({ github, context }) { …
```
=> Update prune-prereleases.js pruning rules

Cargo.lock, crates/debugger/Cargo.toml, crates/debugger/src/tui/context.rs, crates/debugger/src/tui/draw.rs, crates/evm/core/Cargo.toml, crates/evm/core/src/debug.rs, crates/evm/core/src/utils.rs, crates/evm/evm/Cargo.toml, crates/evm/evm/src/inspectors/debugger.rs, crates/forge/Cargo.toml, crates/forge/bin/cmd/script/transaction.rs
Replace `CallKind` in Foundry with the one from `revm-inspectors`. Might be worth extracting the type into Alloy, although I'm unsure where it would fit (since it's not used in Alloy at all) to avoid crates depending on `revm-inspectors` for that type only.
Closes #6725
=> refactor: replace internal `CallKind`

Cargo.lock, crates/chisel/Cargo.toml, crates/chisel/bin/main.rs, crates/chisel/src/dispatcher.rs, crates/chisel/src/session.rs, crates/chisel/tests/cache.rs
This is never `None` and `errored` is based on the result
Review without whitespace
=> refactor(chisel): remove 'errored', make session_source non-optional

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm.rs, testdata/cheats/Vm.sol, testdata/cheats/dumpState.t.sol
Closes https://github.com/foundry-rs/foundry/issues/6810
We would like to be able to use deploy scripts to generate genesis states that can be used by client implementations.
This same genesis generation could be used for in memory testing, so that the exact same genesis state is used in both production networks as well as the unit tests.
Implements a cheatcode `vm.dumpState(string)` that dumps the current revm state to disk in the same format as the "allocs" field in a geth style `genesis.json`. This can dump state that can be read in by `vm.loadAllocs(string)`.
The implementation of the cheatcode skips dumping system contracts. It includes various test coverage.
=> feat: vm.dumpState

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/assets/cheatcodes.schema.json, crates/cheatcodes/spec/src/cheatcode.rs, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/base64.rs, testdata/cheats/Vm.sol
cc @mds1
- https://github.com/foundry-rs/forge-std/pull/496#issuecomment-1894764835
- https://github.com/foundry-rs/foundry/pull/6785#discussion_r1452529590
=> chore(cheatcodes): remove base64 group, add string overloads

crates/cli/src/opts/ethereum.rs
To improve transaction inclusion guarantees Flashbots offers a [fast](https://docs.flashbots.net/flashbots-protect/quick-start#faster-transactions) endpoint that shares the transaction with all [registered builders](https://github.com/flashbots/dowg/blob/main/builder-registrations.json).
To prevent introducing unnecessary breaking changes whilst offering major benefits I suggest using Flashbots' fast route.
A future solution could be to allow the user to define their own `BUILDER_RPC_URL` (separate from the `ETH_RPC_URL`). and get rid of the vendor lock-in naming of `flashbots` to something more neutral like `private`.
=> feat(cli): Update Flashbots URL to use `fast` endpoint to improve transaction inclusion guarantees

crates/evm/core/src/backend/mod.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6538.t.sol
closes #6538
see docs for more context.
TLDR: we need to update the env.block to the transaction's block so we can transact it in the block env it was mined in
=> fix: update env in transact cheatcode

crates/fmt/src/comments.rs, crates/fmt/src/formatter.rs, crates/fmt/testdata/BlockCommentsFunction/fmt.sol, crates/fmt/testdata/BlockCommentsFunction/original.sol, crates/fmt/tests/formatter.rs
closes #6812
don't write trailing white space for empty doc lines
=> fix: skip trailing white space for doc comments

crates/common/src/provider/tower.rs
=> chore: better retry tracing

crates/anvil/src/eth/api.rs
The result returned by `anvil` `web3_sha3` does not include the "0x" prefix in the hexadecimal string.
Comparing `geth` and `anvil` outputs, with the same parameter, we can see the difference:
```bash
$ curl -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "web3_sha3", "params": ["0x68656c6c6f20776f726c64"], "id": 74}' http://localhost:8545
{"jsonrpc":"2.0","id":74,"result":"0x47173285a8d7341e5e972fc677286384f802f8ef42a5ec5f03bbfa254cb01fad"}
$ curl -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "web3_sha3", "params": ["0x68656c6c6f20776f726c64"], "id": 74}' http://localhost:8545
{"jsonrpc":"2.0","id":74,"result":"47173285a8d7341e5e972fc677286384f802f8ef42a5ec5f03bbfa254cb01fad"}
```
Add the `0x` prefix to the result of sha3.
=> fix: format `web3_sha3` result as an hexadecimal string

crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/script/verify.rs, crates/forge/bin/cmd/verify/mod.rs
When you `forge create --via-ir`, you cannot verify later with `forge verify-contract`, which does not support the `--via-ir` flag.
Introduces a `--via-ir` flag into `verify-contract` which causes the standard json-input passed to etherscan to include `"viaIR":true`, which fixes verification.
Fixes the original problem in #3507, although that issue seems to have evolved to include #6780.
=> [forge] verify-contract: support --via-ir flag

Cargo.lock, Cargo.toml
Add Support for PUSH0 opcode when using `--disassemble` flag in `cast code`
closes: https://github.com/foundry-rs/foundry/issues/6840
See: https://github.com/ckoopmann/evm-disassembler/pull/10
=> chore(cast): Bump evm-disassembler dependency to add PUSH0 support

crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/verify/etherscan/mod.rs
Closes https://t.me/foundry_support/49077
Review without whitespace
=> chore: error instead of panic on create fork failure

crates/cheatcodes/spec/src/lib.rs, crates/chisel/benches/session_source.rs, crates/chisel/bin/main.rs, crates/chisel/src/session_source.rs, crates/chisel/tests/cache.rs, crates/evm/core/src/fork/backend.rs, testdata/cheats/Vm.sol
By default chisel injects the test Vm interface into the default REPL contract, but this doesn't work with older Solc versions because the interface only supports >=0.8.4.
Closes https://github.com/foundry-rs/foundry/issues/6850
Add `--no-vm` to disable the Vm injection, toggled by default for unsupported versions.
=> feat(chisel): add --no-vm option, enabled by default for old Solc versions

crates/common/src/selectors.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/signatures.rs, crates/evm/traces/src/lib.rs
supersedes #6719
fyi @cdump please don't open PRs from your master branch :)
I made only a few stylistic changes
=> feat: resolve multiple function/event selectors in one openchain.xyz request

crates/cast/bin/main.rs, crates/cast/bin/opts.rs
4byte selector lookups for `cast selectors` was requested in comments https://github.com/foundry-rs/foundry/pull/6684#issuecomment-1878139763
Add optional selectors resolving (`--resolve`, default=false).
After the https://github.com/foundry-rs/foundry/pull/6719 has been merged, we don't have a problem with a lot of openchain API calls.
```
$ cast selectors --resolve $(cast code 0xdAC17F958D2ee523a2206206994597C13D831ec7)
0x06fdde03                              name()
0x0753c30c      address                 deprecate(address)
0x095ea7b3      address,uint256         approve(address,uint256)
0x0e136b19                              deprecated()
0x0ecb93c0      address                 addBlackList(address)
0x23b872dd      address,address,uint256 transferFrom(address,address,uint256)
...
``` …
=> feat(cast/selectors): add optional selectors resolving

crates/common/src/selectors.rs
`cast 4byte-decode` is broken, using the command from [reference example](https://book.getfoundry.sh/reference/cast/cast-4byte-decode#examples):
on [Nightly (2023-12-02)](https://github.com/foundry-rs/foundry/releases/tag/nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a):
```
$ cast 4byte-decode 0x1F1F897F676d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e7
Error:
Could not decode response:
{"ok":true,"result":{"event":{},"function":{"0x1F1F897F":null,"0x1f1f897f":[{"name":"fulfillRandomness(bytes32,uint256)","filtered":false}]}}}
.
Error: invalid type: null, expected a sequence at line 1 column 61
```
on master:
```
$ cast 4byte-decode 0x1F1F897F676d00000000000000000000000000000000000000000000000000000000000000000 …
```
=> fix(cast) lowercase selectors before send API request to openchain.xyz

crates/cast/bin/cmd/wallet/mod.rs
[book scripts](https://github.com/foundry-rs/book/blob/master/scripts/gen_output/help.py#L194) are broken after adding the new `cast wallet derive-private-key` in https://github.com/foundry-rs/foundry/pull/6774 because of missing description
Add the description to the command
=> fix(cast): add description to 'cast wallet derive-private-key'

deny.toml
We've got an advisory complaining on the deny check for `shlex`, which is used in mdbook. We can wait for mdbook to patch this, and we shouldn't avoid the CI being green for this in the meanwhile
Ignore it
=> chore(`deny`): ignore shlex

Cargo.lock, crates/evm/core/Cargo.toml, crates/evm/core/src/opts.rs
With this and #6880, the evm crate is ethers free.
=> feat(`evm`): use alloy provider to fetch chain id, remove `ethers-providers`

crates/debugger/src/tui/draw.rs
optimistically closes #6878
see https://github.com/foundry-rs/foundry/issues/6878#issuecomment-1904903566
this should fix an off by one here:
https://github.com/foundry-rs/foundry/blob/master/crates/debugger/src/tui/draw.rs#L281-L281
but tbh I don't know for sure without a repro, perhaps @ethever can try?
FYI @brockelmore
=> fix: fix off by one debugger draw

Cargo.lock, Cargo.toml, crates/cheatcodes/Cargo.toml, crates/cheatcodes/src/evm.rs, crates/evm/core/Cargo.toml, crates/evm/core/src/backend/fuzz.rs, crates/evm/core/src/backend/mod.rs
Migrates to using alloy genesis instead of ethers core types for genesis utils.
Removes ethers core, migrates to alloy genesis. 
The `loadAllocs` cheatcode was modified to try reading from a json file which only contains allocs, if the allocs read from the genesis file is empty. This is because now `Genesis` can be deserialized as default, and will not fail if the `alloc` field is missing.
=> feat(`evm`): migrate to `alloy-genesis`, rm `ethers-core`

Cargo.toml, crates/cli/src/handler.rs
And always show backtraces on panics.
This is a 10% size increase (40M -> 44M) for much better debugging panics. See below.
<details><summary><strong>Benchmarks</strong></summary>
<p>
NOTE: `forge-<strip = >-<panic = >`
```
------------- PANIC= ./forge-debuginfo-abort
Message:  test
Location: crates/forge/bin/main.rs:25
8: forge::main::hd66a31dbefd0b4bf
9: std::sys_common::backtrace::__rust_begin_short_backtrace::h621274431205cf82
10: …
```
=> feat: keep debug symbols in release builds

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/string.rs, testdata/cheats/StringUtils.t.sol, testdata/cheats/Vm.sol
closes #6818 
The following string utils cheatcodes have been created:
=> native string utils cheatcodes

docs/dev/cheatcodes.md
original link is broken
replace with correct link
=> docs(docs/dev): correct cheatcodes.rs's md link path

config
Old foundry config files point to /config which was moved to /crates/config.
=> chore: symlink config to crates/config for visibility

.gitattributes, rustfmt.toml
=> chore: update .gitattributes and rustfmt.toml

Cargo.lock, Cargo.toml, crates/config/src/lib.rs, crates/config/src/providers/mod.rs, crates/config/src/utils.rs
this deprecates the tmp cancun config value and supports new `EvmVersion::Cancun`
blocked by svm 0.8.24 release
=> chore: use EvmVersion::Cancun

crates/evm/core/src/decode.rs
The `trimmed_hex` function turns a slice of bytes into a hex string, trimming the output if the slice is longer than 32 bytes. If longer, an ellipsis is inserted in the middle, and the number of bytes is rendered into the output. Currently, this number actually corresponds to the length of the hex string, i.e. it's twice the number of bytes.
Render the length of the original slice instead of the hex string. I also slightly changed the code so only the visible parts of the slice are encoded as hex, which saves a bit of allocation.
=> fix: print actual length in bytes in `trimmed_hex`

crates/forge/bin/cmd/verify/etherscan/mod.rs, crates/forge/tests/cli/verify.rs
This fixes a bug in the compiler_version detection if there are more artifacts in a single file.
This now checks if the versions of an artifact are unique
=> fix: improve compiler version check in create --verify

crates/common/src/compile.rs
Currently `ProjectCompiler` exits with "Nothing to compile" if `project.paths` does not have any input files. However, this is incorrect as we may have non-empty `files` field on it.
The usecase is to compile an arbitrary set of files which does necessarily form a correct foundry project layout.
We are `mem:take`'ing `files` field in `compile`, so I moved a "Nothing to compile" check there.
=> fix(`forge`): Small fix for `ProjectCompiler`

crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/executor.rs, crates/anvil/tests/it/transaction.rs
Closes #6931
if gas is missing estimate the appropriate value
see also 
https://github.com/ethereum/go-ethereum/blob/bc0b87ca196f92e5af49bd33cc190ef0ec32b197/internal/ethapi/transaction_args.go#L111-L132
=> fix: estimate gas if missing for eth_sendTransaction

Cargo.toml
- `debug = 1` for debug builds: this is a minor loss (about 10% or 4s, from ~40s to ~44s) in a clean dev build for much better backtraces (including normal errors with FOUNDRY_DEBUG=1).
- `debug = "line-tables-only"` for optimized builds: negligible binary size increase (<100KB) for source locations in backtraces, see [the profiles reference](https://doc.rust-lang.org/cargo/reference/profiles.html#debug)
<details><summary><strong>Measurements dump</strong></summary>
<p>
```
--- DEBUG = 0 ---
Timing report saved to /home/doni/github/foundry-rs/foundry/target/cargo-timings/cargo-timing-20240129T180147Z.html
Finished dev [unoptimized] target(s) in 39.50s
Command being timed: "cargo b --bin forge -p forge --timings"
User time (seconds): 452.77
System time (seconds): 37.59
Percent of CPU this …
```
=> chore: tweak `debug` config for all profiles

crates/cast/bin/cmd/call.rs, crates/cli/src/utils/cmd.rs, crates/debugger/src/tui/mod.rs
`cast call --trace --verbose` functionality was removed in https://github.com/foundry-rs/foundry/pull/6219 (it didn't do anything), but it wasn't removed as a flag and it was incorrectly passed instead of `--debug`'s value when calling `handle_traces`.
Drive-by: fix double terminal clear in case of debugger panics, and fix a debugger panic by hoisting a check to before creating the internal context.
Closes https://github.com/foundry-rs/foundry/issues/6938
=> fix(cast/call): remove --verbose, fix --debug

crates/forge/bin/cmd/script/transaction.rs
More debug for https://github.com/foundry-rs/foundry/issues/3229#issuecomment-1864001358
Review without whitespace
=> refactor: TransactionWithMetadata decode fns

crates/common/src/glob.rs
`GlobMatcher` stores the unparsed glob already
=> chore: halve the size of GlobMatcher

crates/common/src/compile.rs, crates/common/src/glob.rs, crates/forge/bin/cmd/build.rs, crates/forge/bin/cmd/test/filter.rs, crates/forge/bin/cmd/test/mod.rs
=> chore: only use a compiler filter if not empty

.github/workflows/release.yml, crates/anvil/Cargo.toml, crates/cast/Cargo.toml, crates/chisel/Cargo.toml, crates/forge/Cargo.toml
Closes https://github.com/foundry-rs/foundry/issues/6678
=> feat: add asm-keccak feature

Cargo.lock, Cargo.toml, crates/forge/tests/it/repros.rs, testdata/repros/Issue6966.t.sol
Related https://github.com/foundry-rs/foundry/pull/6358
Closes https://github.com/foundry-rs/foundry/issues/6966
Nice
=> chore: revert k256 bump (again)

crates/cast/bin/cmd/storage.rs, crates/config/src/etherscan.rs, crates/config/src/lib.rs
closes #6965
etherscan provider was invoked incorrectly in #6918
=> fix: fix etherscan api parsing again

.github/scripts/matrices.py, .github/workflows/docker-publish.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> ci: update runners (part 2)

.github/scripts/matrices.py, .github/workflows/release.yml
=> ci: update runners (part 3) (final)

.github/scripts/matrices.py, crates/cast/bin/cmd/call.rs, crates/forge/bin/cmd/install.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/verify/etherscan/mod.rs
=> fix: actually run all unit tests in CI

Cargo.lock, Cargo.toml, crates/forge/bin/cmd/flatten.rs
Ref https://github.com/foundry-rs/compilers/pull/52
Full rewrite of flattening utilizing native solc AST.
- Closes #6539 
- Fixes #6022 
- Fixes #4034 
- Fixes #3678 
- Fixes #3265 
- Fixes #2545 
- Fixes #2378 
- Fixes #2344
It seems that we don't have any tests for `forge flatten` but creating PR with patched dep to run CI just in case.
=> feat(`forge`): new `flatten` implementation

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/tests/it/transaction.rs
Related to #6980
Added overrides arg and taking into account when computing the call.
=> added arg and computing state in function of some overrides

crates/config/src/error.rs
=> chore: add new solidity warning code

crates/cast/bin/cmd/storage.rs, crates/cast/tests/cli/main.rs
`cast storage` currently passes `None` to `provider.get_storage_at()` for `block`, rather than the block number if provided by the user. This causes storage for the latest block to always be pulled, regardless of what the user provides.
Pass the `block` (already a flag for `storage` and parsed as `BlockId` ) along to `provider.get_storage_at()`.
=> fix(cast): pass blocknum to cast storage rather than always using latest

crates/common/src/provider/retry.rs
Closes #6913 
We should not retry custom errors at all. I think it's still okay to retry `MissingBatchResponse` errors as it could be the server derping out.
=> fix(`foundry-common`): Do not retry custom errors

crates/config/src/lib.rs
ref #7014
This is not quite perfect, but is better than before.
If a solc version is provided in foundry.toml but no evm-version, we normalize the config's evm-version.
This does not affect solc compilation because this is also in foundry-compilers before invoking solc.
This can be improved by:
emitting warnings if user configures both evm_version and solc that are incompatible.
cc @0xalpharush
=> fix: normalize default evm version if solc configured

crates/chisel/src/session_source.rs, crates/chisel/tests/cache.rs
Addresses part of https://github.com/foundry-rs/foundry/issues/7014 as a follow on to https://github.com/foundry-rs/foundry/pull/7018
=> fix(chisel): validate that EVM version is compatible with solc version

crates/cast/bin/cmd/wallet/mod.rs
Attach more context to the error message for canonicalize, which caused some confusion for users.
We could also just create the dir ourselves, but the current behavior [matches geth's](https://github.com/foundry-rs/foundry/pull/1713).
=> chore(`cast`): improve `cast wallet new`

crates/anvil/README.md
An error occurs when Anvil is compiled from the `crates/` directory as instructed. The error message states that the `base_fee_per_blob_gas` and `blob_gas_used_ratio` fields are missing in the `alloy_rpc_types::FeeHistory` initializer. This error is caused by recent changes made to the `FeeHistory` struct in `alloy-rs` [`fee.rs`](https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types/src/eth/fee.rs).
Here is the error message for reference:
```
Compiling anvil v0.2.0 (/Users/benji/Develop/blockchain/foundry/crates/anvil)
error[E0063]: missing fields ﻿base_fee_per_blob_gas and ﻿blob_gas_used_ratio in initializer of ﻿alloy_rpc_types::FeeHistory
--> crates/anvil/src/eth/[api.rs:1312](http://api.rs:1312/):28
|
1312 |         let mut response = FeeHistory {
| …
```
=> fix (anvil): error E0063 when compile on macOS due to alloy-rs

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/test/expect.rs, testdata/cheats/MemSafety.t.sol, testdata/cheats/Vm.sol
https://github.com/foundry-rs/forge-std/pull/503#issuecomment-1930357988
cc @clabby
=> feat(`cheatcodes`): `stopExpectSafeMemory`

crates/chisel/src/dispatcher.rs
closes #7035
this doesn't prevent all cases, but should catch the most
I get why we have this regex, so we don't run into incorrect checksum errors, so this regex makes it more convenient.
The safe approach would be to not use the regex at all...
=> chore: improve address regex

crates/evm/traces/src/decoder/mod.rs
Fixes issue of private keys not being redacted in traces.
Previously there was a [logical error](https://github.com/foundry-rs/foundry/issues/6995#issuecomment-1932377769) causing inputs to not correctly be redacted.
Closes #6995 
This change should cover all cheatcode cases where a `private key` is passed (directly or through the `Wallet` struct) or is returned.
This includes missing cases:
- `createWallet(...)`
- `getNonce(Wallet)`
- `signP256(uint256,bytes32)`
- `sign(Wallet,bytes32)`
I've added a parameterized test to verify all cases (incl. exceptions) and in a way so it is easy to maintain.
To be able to quickly check the proposed fixes I've created a minimal repo: https://github.com/zerosnacks/foundry-pr-6995
PS: dummy data included in the test was generated using the dummy private …
=> (fix): correctly redact private keys in traces #6995

crates/common/src/contracts.rs
I don't know if we have any noticable problems with `diff_score` atm, but I was just looking at some code using it and noticed that current implementation is a little bit strange.
With current impl contracts having similar starting bytes would have pretty low diff score, and with enough immutables in the longer contract we may get a false positive.
IMO diff_score should be affected by the differences in contracts length as it's very unlikely that the contract would greatly change its length after modifying immutables
=> fix(`forge`): more precise diff_score

crates/debugger/src/tui/draw.rs
The debugger sometimes panics with an out-of-range error when slicing an array.
Reproduction is tricky because the error depends on the height of the debugger window.
Ensure that `start_line` is always strictly less than `before.len()`.
Closes #7029
=> fix(forge): fix debugger out-of-range panic

Cargo.lock, crates/config/Cargo.toml, crates/config/src/fs_permissions.rs, crates/forge/tests/cli/config.rs
see https://github.com/foundry-rs/foundry/issues/6981
- resolve configured `fs_permissions` symlinks paths when finding permissions
- could write a test for unix family  that creates sym link in temp dir and check permissions, didn't find this approach in project, pls advise
=> #6981: `fs_permissions` find permission also sym links

crates/forge/bin/cmd/verify/sourcify.rs
closes #7051
use `Url::join` to ensure the url is <verifier-url>/path
=> fix: use join for check-by-address path

crates/forge/tests/it/invariant.rs
let's see what value we're actually getting now
=> test: use assert_eq

Cargo.lock, Cargo.toml, crates/config/README.md, crates/config/src/lib.rs, crates/forge/bin/cmd/verify/etherscan/flatten.rs, crates/forge/tests/cli/cmd.rs, crates/forge/tests/cli/config.rs
Related to: https://github.com/foundry-rs/foundry/issues/1200
Adding `ignored_file_paths` field and parsing it.
=> parsing file paths from foundry.toml

Cargo.lock, Cargo.toml, crates/anvil/core/src/eth/mod.rs, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/api.rs, crates/anvil/tests/it/fork.rs, crates/anvil/tests/it/transaction.rs, crates/cheatcodes/src/inspector.rs, crates/common/src/types.rs, crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/bin/cmd/script/transaction.rs
Previously we were using `CallRequest`, and an in-house `TransactionRequest`.
Switches to using `TransactionRequest` everywhere.
Depends on https://github.com/alloy-rs/alloy/pull/178
=> refactor: use `TransactionRequest` everywhere

crates/common/src/compile.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs, crates/evm/traces/src/identifier/etherscan.rs, crates/forge/bin/cmd/script/build.rs, crates/forge/bin/cmd/test/mod.rs
Summary from #7043:
> [ContractSources](https://github.com/foundry-rs/foundry/blob/725c9a95b1331c67b55facd4da1598cbc8e03112/crates/common/src/compile.rs#L276) is a mapping of name -> id -> (source code, bytecode)
> 
> In src_map, the source for the contract is [looked up by name](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L331). Since this may return multiple contracts with the same name, the entries are iterated over and the SourceElement's index is compared to the file_id of the current contract source. [If they match, the source code is returned](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L353).
> 
> The problem is that this will never return …
=> fix(forge): debugger should load sourcemaps by file_id

crates/forge/bin/cmd/script/mod.rs, crates/forge/tests/cli/script.rs
Closes: https://github.com/foundry-rs/foundry/issues/2508
Currently there is an issue where script errors get skipped if `--json` is passed to `forge script` as the execution path lacks the `success` check.
Adds missing success check and two test cases to check equivalency of behaviour.
Similar to `show_traces` the error check is performed at the end so that useful stdout logs can still be captured.
=> fix(`forge`): forge script --json always returns zero exit code #2508

crates/forge/bin/cmd/verify/etherscan/mod.rs
Closes #7042
Current `EtherscanVerificationProvider::cache_entry` always looks for contract in cache by name, even if path present, this PR fixes it and uses path where possible.
=> fix(`forge`): fix cache search for verification

crates/anvil/src/eth/fees.rs
This removes an outdated multiplier to the suggested priority fee, which was excessive
instead this now uses a simple constant, the existing suggested priority fee.
I'll open an issue to get support for proper fee sampling, though for dev node this is fine.
closes #7070
=> chore: rm high priority fee adjustment

Cargo.lock, Cargo.toml, crates/anvil/Cargo.toml, crates/cast/Cargo.toml, crates/chisel/Cargo.toml, crates/forge/Cargo.toml
Every user who builds Foundry from source has git installed.
Use the `"gitcl"` feature to make `vergen` use the `git` binary in the `PATH` instead of depending on `libgit2`.
=> chore(deps): remove build-time dependency on libgit2

Cargo.toml, crates/cheatcodes/src/lib.rs
Removes 280_854 LLVM lines in `foundry-evm` (1_868_826 to 1_587_972, -15%)
With the next Revm update this should go down a further 30-40%, as currently basically all of revm is parameterized across 16 evm specs and 2 dbs of our own.
This should significantly improve compile times and compile memory usage.
Raw data (random `cargo llvm-lines --lib --release -p ...` and `cargo bloat --bin forge --release`): [bloat.zip](https://github.com/foundry-rs/foundry/files/14233578/bloat.zip)
=> perf: add a dyn Cheatcode trait to reduce generated code

crates/forge/tests/cli/ext_integration.rs, crates/test-utils/src/util.rs
Instead of automatically detecting based on the files in the root.
This was not done initially because adding args to the macro was annoying.
Should fix external test "ran out of space" error by not running unnecessary installing commands.
=> test: manually add install commands

crates/test-utils/src/util.rs
Merged https://github.com/foundry-rs/foundry/pull/7090 too quickly.
=> test: don't fail on canonicalize

crates/common/src/contracts.rs
Don't clone the entire code object to get only the bytes out of it.
=> perf: touch up flatten_contracts

crates/evm/core/src/fork/backend.rs
Would rather ignore these tests tbh.
=> test: don't hardcode an endpoint

Cargo.lock, Cargo.toml, crates/forge/bin/cmd/script/build.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/bin/cmd/script/executor.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/src/link.rs, crates/forge/src/multi_runner.rs, testdata/linking/cycle/Cycle.t.sol
The way current linking implementation works is by linking _each_ individual artifact in an isolated way. For each artifact `post_link` hook is getting called with the following data (`PostLinkInput`).
- `id` of the linked artifact
- `contract` containing linked contract artifact
- `known_contracts` which seems to be just a mutable reference getting passed around
- `dependencies` - vector of libraries that needs to be deployed for the given artifact
The `dependencies` vector contents is explained here:
https://github.com/foundry-rs/foundry/blob/2cf84d9f3ba7b6f4a9296299e7036ecc24cfa1da/crates/forge/src/link.rs#L580-L583
The thing which highlights the downside of this approach is that for different artifact `dependencies` may include different libraries with different nonces. This is …
=> feat: Linking rewrite

crates/common/src/types.rs
=> chore(`common`): remove unneeded ethers conversions

.github/workflows/test.yml
Halves the size of target/, which currently with debug=1, all target, clean build, is 12gb.
Should fix CI issues with out of space.
=> ci: disable debuginfo for tests

crates/forge/bin/cmd/script/build.rs, crates/forge/src/link.rs, crates/forge/src/multi_runner.rs
Currently linker links and returns all artifacts, this process involves cloning. This cloning is performed for every single artifact when building `MultiContractRunner`.
New impl only returns library addresses and bytecode for libraries that has to be predeployed, linker users may use helper methods on `Linker` struct to link separate or all artifacts.
=> perf: improve linker performance

crates/cast/bin/cmd/storage.rs, crates/forge/bin/cmd/inspect.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/link.rs, crates/forge/src/multi_runner.rs
Follow-up to https://github.com/foundry-rs/foundry/pull/7115
=> perf: don't clone artifacts when building multi runner

crates/cli/src/utils/cmd.rs, crates/common/src/contracts.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/local.rs
Supersedes https://github.com/foundry-rs/foundry/pull/7091
cc @mds1 @klkvr
=> refactor: local trace decoder and identifier

crates/debugger/src/tui/context.rs, crates/debugger/src/tui/draw.rs, crates/evm/core/src/debug.rs, crates/evm/evm/src/inspectors/debugger.rs
It's often useful to see what data is actually in calldata/returndata, as well as see which regions are being operated on.
Closes #5492.
- Add calldata and returndata to `DebugStep`
- Add `active_buffer` to `DebuggerContext`
- `get_memory_access` -> `get_buffer_accesses`; note which buffer is being read from, if any; simplify return type
- `draw_memory` -> `draw_buffer`; compare read/writes to current active buffer 
- add `b` ("buffer") operator to debugger to cycle Memory -> Calldata -> Returndata buffers in the "buffer" panel view
- add `b` to help string; update references of "memory" to "buffer"
Unsure of where debugger tests live (if anywhere), but draw logic seems to handle edge cases well; I'd be most concerned about potential performance issues or highlighting regions in the wrong …
=> feat(forge): add calldata and returndata views to debugger

crates/debugger/src/tui/draw.rs
Was a bit late pushing my last commit to #7110, apologies cc @DaniPopes 
The check on `read_accesses` should check both that it's Some and that the active buffer matches, else writes to the memory buffer won't get highlighted.
This doesn't feel particularly elegant, so let me know if there's a better way to check if a member is Some and check against a member of _that_ member in the same conditional.
As noted in a comment in the previous PR, behavior should be tweaked in the future to allow simultaneous read+write highlights for MCOPY
=> fix(forge): fix debugger buffer-write highlight else-if fallthrough

Cargo.lock, Cargo.toml, crates/anvil/src/eth/backend/fork.rs, crates/common/Cargo.toml, crates/common/src/ens.rs, crates/common/src/lib.rs, crates/config/Cargo.toml, crates/evm/core/src/fork/backend.rs
We need a foundry-specific utility to resolve ens names at the CLI level.
Adds `NameOrAddress` for CLI use, which can resolve itself to an address, or error.
Part of #7106
=> feat(`foundry-common`): NameOrAddress ENS util

crates/forge/bin/cmd/script/build.rs, crates/forge/tests/cli/script.rs
Ref #7120
Currently we are exiting with error if we've found more than one artifact for provided contract path, however, we may have several artifacts for the same contract compiled with different solc versions.
Only exit early if we've found contract with different name
It's not a regression as this issue existed long before recent linking updates, so not sure if #7120 will get closed by this
=> fix(`forge`): correctly find script artifact when compiling with multiple versions

Cargo.lock, crates/common/src/contracts.rs, crates/evm/traces/Cargo.toml, crates/evm/traces/src/identifier/local.rs
I think we still want this. cc @klkvr
Implementation modified from https://github.com/foundry-rs/foundry/pull/7105,
see that PR for more information.
I modified it to use binary search on the sorted id array to find the minimum index, then iterating starting from that point instead of filtering which would search the entire array.
See main thread performance in the following profiles:
- https://github.com/foundry-rs/foundry/pull/7109 @ https://github.com/foundry-rs/foundry/pull/7109/commits/7e18213b19cb45504e04c132a1cc35bc163a7637: <https://share.firefox.dev/3uAtEV2>
- This PR on top of the commit above <https://share.firefox.dev/48bovQY>
=> perf: improve LocalTraceIdentifier performance

crates/debugger/src/tui/draw.rs
MCOPY is a new opcode and the Forge debugger neither supports it nor highlighting multiple ranges in the same buffer view.
Support multiple range highlights, including overlap for MCOPY
Normal MCOPY:
MCOPY with overlap:
=> feat(forge): support mcopy buffer highlighting in debugger

crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/error.rs, crates/common/src/contracts.rs, crates/evm/core/src/decode.rs, crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/traces/src/decoder/mod.rs, crates/forge/bin/cmd/script/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs
Eagerly hash selectors once instead of on every call to `decode_revert`. This improves performance when decoding lots of traces with lots of contracts as decoding custom errors is now trivial.
Diff is kinda bad but the decoding logic is unchanged (review with "hide whitespace").
Closes https://github.com/foundry-rs/foundry/issues/7119
See `render_trace_arena`, from ~2000 to ~750 samples for the same task (`FOUNDRY_PROFILE=lite forge t -vvvvv --nmc Fork` in [sablier/v2-core](https://github.com/sablier-labs/v2-core)):
- before https://share.firefox.dev/3UG8Mq3
- after https://share.firefox.dev/4bAwwBV
=> feat: add a revert decoder to eagerly hash error selectors

crates/forge/src/result.rs, crates/test-utils/src/util.rs
Closes https://github.com/foundry-rs/foundry/issues/7132
=> feat: print total duration in final test summary

crates/forge/bin/cmd/init.rs, crates/forge/bin/cmd/install.rs
Currently dependencies are being installed in 3 steps:
1. Clone dependency
2. Clone its submodules
3. Checkout to the given or found tag, if any.
We need to swap 2 and 3 here as checked out commit might have more submodules than master and vice versa.
Because of that our CI failing right now as when installing forge-std, we are firstly cloning master which don't have ds-test dependency, and then checking out v1.7.6, which has it and requires it to compile normally
cc @mds1
=> fix(forge): update submodules after dependency checkout

crates/cast/bin/main.rs, crates/cast/bin/opts.rs, crates/cast/src/lib.rs, crates/common/src/abi.rs
Blocked by #7149 
Useful to calculate `abi.encodePacked` without `chisel`.
Update `alloy-dyn-abi` to make use of fixed `abi_encode_packed` https://github.com/alloy-rs/core/pull/517
=> feat(cast): abi-encode-packed 

crates/common/src/provider/runtime_transport.rs
Closes #7131 
We are basically blocking all async requests through provider rn by aquiring write lock before making a request.
Use read lock
=> fix(providers): remove locks on requests

crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/optimism.rs
This should be camelcase rather than snake case. A quirk when using other fields. Closes #7026 
use camelcase.
=> fix(`anvil`): properly set deposit nonce key on mined tx receipt

crates/evm/traces/src/identifier/local.rs
Closes https://github.com/foundry-rs/foundry/issues/7144
Also re-added the threshold present before refactoring: https://github.com/foundry-rs/foundry/blob/e911d2256393190c0ff5e9f72653d5ea359ac40f/crates/evm/traces/src/identifier/local.rs#L41-L49
=> fix: only early-return if an exact bytecode match is found

crates/evm/core/src/fork/multi.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6616.t.sol
closes #6616 
proposed solution for solving https://github.com/foundry-rs/foundry/issues/6616, slightly different than suggested https://github.com/foundry-rs/foundry/issues/6616#issuecomment-1935844158 (in the sense that `url@latest` fork id was made obsolete and instead `url@latest_block` is recorded)
- if no block provided then fork is created using latest block for fork id (`url@latest_block`). if block provided then fork id is url@provided_block (this means there'll no longer be a `url@latest` fork id but always `url@block`)
- after creation of fork the id is checked if in inserted forks. If it doesn't exist then it's inserted, otherwise the existing backend is reused and a new fork `url@latest_block-1` recorded
- changed `CreatedFork::inc_senders` to increment number of senders and …
=> #6616: createSelectFork does not fork latest block number if you sleep

foundryup/install
Ref https://github.com/foundry-rs/foundry/discussions/6915
=> fix(foundryup): address shellcheck in installer

Cargo.lock, crates/chisel/Cargo.toml, crates/chisel/src/executor.rs, crates/chisel/src/session_source.rs, crates/forge/bin/cmd/verify/mod.rs
Fixes https://github.com/foundry-rs/foundry/issues/7050
=> fix(chisel): enum min and max

crates/evm/traces/src/lib.rs
Fixes https://github.com/foundry-rs/foundry/issues/7041
This is already fixed in [evm-inspectors](https://github.com/paradigmxyz/evm-inspectors/blob/a2a908aeb61318cd7df92b51444755cea338d49c/src/tracing/writer.rs#L219)
=> fix: show return data length instead of calldata for CREATE traces

crates/evm/evm/src/executors/invariant/mod.rs, crates/forge/bin/cmd/script/broadcast.rs, crates/forge/bin/cmd/script/multi.rs, crates/forge/bin/cmd/script/sequence.rs
Closes https://github.com/foundry-rs/foundry/issues/6697 since we don't even use this unwrap
=> fix: don't panic when iterating over script sequence txs

crates/forge/src/multi_runner.rs
Closes #7182
Previous linker impl filtered out artifacts without abi during linking https://github.com/foundry-rs/foundry/blob/7116e2429434ecb1b8ea71fd1dc90a5ab6e0968c/crates/forge/src/link.rs#L182
I don't known in which cases solc emits artifacts without an abi, would be nice to get a repro and add a test case for this
=> fix(forge): do not error when artifact does not have an abi

crates/cheatcodes/src/inspector.rs, crates/cheatcodes/src/json.rs, crates/evm/core/src/backend/error.rs, crates/evm/core/src/backend/fuzz.rs, crates/evm/core/src/backend/mod.rs
Ref https://github.com/foundry-rs/foundry/issues/6652
=> chore: improve DatabaseError error messages

crates/cast/bin/cmd/wallet/mod.rs, crates/wallets/src/error.rs, crates/wallets/src/wallet.rs
Closes https://github.com/foundry-rs/foundry/issues/6794
Open to naming changes
=> feat(cast): add `wallet sign --no-hash`

crates/anvil/src/eth/api.rs, crates/anvil/src/eth/fees.rs, crates/anvil/src/lib.rs
closes #7084
This fixes the bug by creating a fee entry to the best block at launch:
```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" -d '{"id": 1, "jsonrpc": "2.0", "method": "eth_feeHistory", "params": ["0x5", "latest", [20,30]]}'
```
```json
{"jsonrpc":"2.0","id":1,"result":{"baseFeePerGas":["0x3b9aca00","0x342770c0"],"gasUsedRatio":[0.0],"oldestBlock":"0x0","reward":[["0x0","0x0"]]}}
```
The baseFeePerGas has two entries because this is supposed to also include the next block's base fee which can be derived from the current block
=> fix: include base fee per gas for next block

crates/forge/bin/cmd/watch.rs
Fixes https://github.com/foundry-rs/foundry/issues/5824
=> fix: --watch short arg detection

crates/chisel/src/executor.rs
Fixes https://github.com/foundry-rs/foundry/issues/5737
=> fix(chisel): correct some FixedBytes expressions' types

crates/chisel/src/executor.rs, crates/wallets/src/multi_wallet.rs
Follow-up fix for https://github.com/foundry-rs/foundry/pull/7173
max and min are of the input type, we should only default for enums
Also add msg.gas and block.blobbasefee
Ref also https://github.com/foundry-rs/foundry/issues/5705
=> fix(chisel): min and max for all types

crates/cast/bin/cmd/storage.rs, crates/cast/tests/cli/main.rs
additional fix for #6319 
tested with https://github.com/foundry-rs/foundry/issues/6319#issuecomment-1902693003 not sure though how to add a unit test for it, please advise
- the sliced storage value should be used as tail when returning the value of the storage slot.
=> issue 6319: copy raw sliced value as tail in new value to be converted

crates/cheatcodes/src/config.rs, crates/cheatcodes/src/inspector.rs, crates/common/src/evm.rs, crates/config/README.md, crates/config/src/lib.rs, crates/evm/core/src/opts.rs, crates/forge/tests/cli/config.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue5529.t.sol
#5529 
Resolves #5529 by adding logic to allow the default create2 factory to be used in tests and non-broadcasting scripts. I chose to make this change non-breaking by introducing a new config option / CLI flag `always_use_create_2_factory`, which must be set to `true` to enable this behavior.
In the future, this option could be removed or changed relatively easily to make using the create2 factory the default behavior if a breaking change is acceptable.
=> fix(forge): Optionally use create2 factory in tests and non-broadcasting scripts

Cargo.lock, crates/cast/bin/cmd/wallet/list.rs, crates/cast/bin/cmd/wallet/mod.rs, crates/cast/tests/cli/main.rs, crates/wallets/Cargo.toml, crates/wallets/src/multi_wallet.rs, crates/wallets/src/wallet_signer.rs
- added new options for list command, default list local keystore
```
Options:
--dir [<DIR>]                List all the accounts in the keystore directory. Default keystore directory is used if no path provided
-l, --ledger                     List accounts from a Ledger hardware wallet
-t, --trezor                     List accounts from a Trezor hardware wallet
-m, --max-senders <MAX_SENDERS>  Max number of addresses to display from hardware wallets [default: 3]
--aws                        List accounts from AWS KMS
--all                        List all configured accounts
-h, --help                       Print help
```
- for ledger display 3 addresses for each ledger live and legacy HD
- for trezor display 3 addresses for trezor live HD path
- for AWS display all keys configured
- for …
=> feat(`cast wallet list`) issue #6958: Include HW wallets in cast wallet ls

crates/cast/bin/cmd/wallet/mod.rs
#7088 broke `cast wallet verify`. The following worked previously and no longer works:
```
cast wallet verify --address 0x28A4F420a619974a2393365BCe5a7b560078Cc13 hello $(cast wallet sign --private-key 0x678d52cc9fdedbf5be1cd9b479725aab5ed8b9fbfbfeff9b660dff8b5766bf2a hello)
```
Error:
```
Odd number of digits
```
This PR reverts a subset of the PR above which fixes the issue. Happy to take suggestions on alternative paths. Thanks!
Closes #7088
=> [cast] Fix cast wallet verify

.github/scripts/matrices.py, crates/config/src/lib.rs, crates/forge/tests/cli/ext_integration.rs, crates/forge/tests/cli/test_cmd.rs
=> test: move forge-std test to external tests

crates/cheatcodes/src/inspector.rs, crates/forge/tests/it/repros.rs, testdata/repros/Issue6634.t.sol
#6634
Adds logic to include the call to the create2 factory in the results returned by the `vm.stopAndReturnStateDiff()` cheat code in all cases where it is used.
This is a follow-up to #6656, which was recently merged and allows the default create2 factory to be used in tests and non-broadcasting scripts. The logic in this PR integrates with those changes so that the call to the create2 factory is properly recorded in all situations, including when the `always_use_create_2_factory` option is enabled.
=> fix(cheatcodes): Record call to create2 factory in state diff

crates/anvil/server/src/lib.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/error.rs, crates/anvil/tests/it/fork.rs
closes https://github.com/foundry-rs/foundry/issues/7023
this converts an error received from the fork properly, by converting it to an rpc err if it is an rpc error
=> fix: handle rpc error response

crates/forge/bin/cmd/test/mod.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/fixtures/can_check_snapshot.stdout, crates/forge/tests/fixtures/can_run_test_in_custom_test_folder.stdout, crates/forge/tests/fixtures/can_test_repeatedly.stdout, crates/forge/tests/fixtures/can_use_libs_in_multi_fork.stdout, crates/forge/tests/fixtures/include_custom_types_in_traces.stdout, crates/forge/tests/fixtures/repro_6531.stdout, crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.1.stdout, crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.2.stdout, crates/test-utils/src/util.rs
Since both individual suites (contracts) and tests can run in parallel, the sum of their individual durations can be different from the actual wall clock time taken executing them
=> fix(forge): total duration is not the sum of individual runs

Cargo.lock, Cargo.toml, crates/forge/bin/cmd/bind.rs
closes #7181
Additionally, I ran into issues with the serde derives because they also are not compatible with `[T; >32]`. 
To address #7181, this PR updates ethers deps to include fix from https://github.com/gakonst/ethers-rs/pull/2743.
To address the issue with the serde derives, this PR adds a flag `--skip-extra-derives`, which skips adding the serde derives and the serde dep to the generated crate. Not sure if this is the best fix since it 1) extends the api for `bind` 2) might be better to fix the issue in the abigen logic
I manually verified that `forge bind` now generates valid rust bindings for the solidity source code mentioned in #7181
=> feat(forge bind): add option to skip json derives

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm.rs, crates/cheatcodes/src/inspector.rs, testdata/cheats/RecordAccountAccesses.t.sol, testdata/cheats/Vm.sol
Closes #6632 
The call depth was already recorded in the `cheatcodes::inspector::AccountAccess` wrapper. This PR removes that wrapper type in favor of only using `cheatcodes::vm::AccountAccess`, which now has a depth field.
Credit to ercembu in #6667 for the initial implementation. I decided to pick this up since it's important to us at Sphinx, and that PR appears to be abandoned. I recommend closing that once this is merged.
=> feat: Add call depth to `vm.stopAndReturnStateDiff()` results

crates/common/src/fmt/ui.rs
fix(cast): fix to address reveal problem in cast receipt
cast receipt 
```shell
cast receipt 0xb07ed701975427442edb04dfe576ea145829744f6ce297ead59032b0f150ac13 --rpc-url=https://rpc.ankr.com/eth
```
output: 
```shell
blockHash               0x4869a5890a55c1ae4cdddf43481210b50826bae1d1b40135557f08ff4e8f4420
blockNumber             19323316
contractAddress         
cumulativeGasUsed       859206
effectiveGasPrice       49687020650
from                    0x259F3683692caEA205495742fd2eFE47539857Dc
gasUsed                 54436
logs                    [{"address":"0x3419875b4d3bca7f3fdda2db7a476a79fd31b4fe","topics":["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0x000000000000000000000000259f3683692caea205495742fd2efe47539857dc","0x0000000000000000000000005c9321e92ba4eb …
```
=> fix(cast): fix to address reveal problem in cast receipt

foundryup/install
Addresses #6487 .
Use `fish_add_path` - more idiomatic way to add to path for fish shell.
=> fix(foundryup): use fish_add_path in fish shell

crates/evm/evm/src/executors/invariant/error.rs, crates/forge/tests/it/invariant.rs, testdata/fuzz/invariant/common/InvariantShrinkWithAssert.t.sol
see https://github.com/foundry-rs/foundry/issues/6683#issuecomment-1966794329
Atm shrinking doesn't apply for invariants using asserts but only for invariants that reverts (require)
- when deciding if a sequence can fail test check if test failed (instead if reverted only)
- added test with assert and require to ensure they shrink at same len
=> invariant shrink #6683: check if test failed instead revert

crates/common/src/provider/retry.rs
this is also possible:
```
Deserialization Error: unknown field `code`, expected one of `id`, `jsonrpc`, `result`, `error`, `params`, `method` at line 1 column 7. Response: {"code":-32007,"message":"20/second request limit reached - reduce calls per second or upgrade your account at quicknode.com"}
```
=> fix: also try error payload response

crates/config/src/lib.rs
Some time ago, after this PR https://github.com/foundry-rs/foundry/commit/4ae40da76e9a1dbb56c136db509dc3e7eab703c8#diff-61de971a1475be0209ee9896ce71d6b3424904b26eb2ea0227d1ff23ee4e6e6bL585-L587
the rpc cache location was changed from 
`~/.foundry/cache/rpc/[chain]/[blockNumber]/storage.json` 
to 
`~/.foundry/cache/rpc/[chain]/[blockNumber]`
However the `cache ls` function was not updated with this change.
This resulted `forge cache ls` listing very old caches that are not used anymore, but ignoring the newer caches as they are not directories.
Example:
Running `forge cache ls` with forge 0.2.0 (43b4e23 2024-02-25T00:21:15.546682000Z)
Note that the RPC caches are ignored in above output and the total sizes are do not include them.
Don't ignore files that are numeric only in their names …
=> fix(forge): list cache files that are saved as block numbers for `cache ls`

crates/common/src/compile.rs
Follow up fix to https://github.com/foundry-rs/foundry/pull/7197
.path is the path to the JSON artifact file.
=> fix: use ArtifactId.source instead of .path

crates/common/src/compile.rs, crates/evm/evm/src/executors/builder.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/lib.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs, crates/forge/tests/it/cheats.rs, crates/forge/tests/it/config.rs, crates/forge/tests/it/core.rs, crates/forge/tests/it/fork.rs, crates/forge/tests/it/fuzz.rs, crates/forge/tests/it/inline.rs, crates/forge/tests/it/invariant.rs, crates/forge/tests/it/test_helpers.rs
Same as https://github.com/foundry-rs/foundry/pull/7283 plus more refactors
=> refactor(forge/test): cache initial executor, don't clone options

crates/common/src/provider/alloy.rs, crates/common/src/provider/retry.rs, crates/common/src/provider/runtime_transport.rs, crates/common/src/provider/tower.rs
Fixes up some docs on providers on `foundry-common`.
=> chore(`common`): doc fixes and unused fns removal

crates/config/src/fuzz.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/strategies/calldata.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/evm/fuzz/src/strategies/mod.rs, crates/evm/fuzz/src/strategies/param.rs, crates/forge/tests/it/config.rs, crates/forge/tests/it/invariant.rs, testdata/fuzz/invariant/common/InvariantCalldataDictionary.t.sol
Atm there's no way to configure calldata fuzzed params behavior - this could in particular be an issue when fuzzing addresses as there's little to no chance the same address is reused.
For invariant testing this is a bigger issue as one would often want to randomly reuse addresses when calling different handler selectors (see https://github.com/foundry-rs/foundry/issues/5868). Some projects maintains an array of addresses in handlers and fuzz the indexes / prank with users from array of addresses - that's a little bit hard to mantain and cannot scale for too many addresses.
This PR introduce an additional config for the dictionary of addresses used in calldata fuzzing.
```
[invariant]
max_calldata_fuzz_dictionary_addresses=100
```
- added …
=> feat invariant (#5868) - configure calldata fuzzed addresses dictionary

crates/config/src/error.rs, crates/config/src/lib.rs
The warning generated by solc when compiling code that uses the new `tstore/tload` opcodes is not particularly useful or productive. The solc team has shown [no interest in removing the warning from the compiler](https://github.com/ethereum/solidity/pull/14819).
Default Forge behavior should be to ignore this warning, as no other (non-deprecated) opcodes get this treatment.
=> Add transient storage warning to default `ignored_error_codes`

crates/common/src/evm.rs, crates/config/src/lib.rs, crates/evm/core/src/fork/init.rs, crates/evm/core/src/opts.rs, crates/evm/evm/src/inspectors/stack.rs, crates/forge/tests/cli/config.rs, crates/forge/tests/cli/test_cmd.rs
ref disscussion in https://github.com/foundry-rs/foundry/pull/7186#issuecomment-1972131061
Right now those gas limit reverts will still be breaking for some codebases, because this flag is not enabled by default. And if we want to make it a default, we should probably change API to `--enable-block-gas-limit`. Let's discuss here if we want this to be a breaking change or keep the previous behavior
=> feat(forge): --disable-block-gas-limit flag

crates/config/src/invariant.rs, crates/evm/evm/src/executors/invariant/mod.rs
Not really a meaningful settings dependency, see https://github.com/foundry-rs/foundry/issues/7303#issuecomment-1976466685
=> closes #7303 - apply `preserve_state` even when `fail_on_revert` is false

crates/anvil/README.md
Otherwise cargo throws error when installing on a clean Rust installation 
```
error: failed to load source for dependency `ethers`
Caused by:
Unable to update https://github.com/gakonst/ethers-rs?rev=73e5de211c32a1f5777eb5194205bdb31f6a3502#73e5de21
Caused by:
can't checkout from 'https://github.com/gakonst/ethers-rs': you are in the offline mode (--offline)
```
=> Remove --offline flag from cargo install command

crates/config/src/invariant.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/forge/src/runner.rs, crates/forge/tests/it/invariant.rs, crates/forge/tests/it/test_helpers.rs, testdata/fuzz/invariant/common/InvariantAssume.t.sol
Closes #4190 
Catch reverts with `MAGIC_ASSUME`, regenerate latest calldata and increase `assume_rejects_counter`. Once counter goes beyond configured `max_assume_rejects`, test fails.
I've changed `InvariantFuzzError` to be an enum, because we don't need data it holds right now for `MaxAssumeRejects` failures.
Also changed `invariant_strat` a bit, currently it always returns Vec with one element, it seemed a bit confusing at first glance, so I changed it to return just a single input.
=> fix(invariants): support `vm.assume` in invariant tests

Cargo.lock, Cargo.toml, crates/forge/Cargo.toml, crates/forge/bin/cmd/script/build.rs, crates/forge/bin/cmd/script/cmd.rs, crates/forge/src/lib.rs, crates/forge/src/multi_runner.rs, crates/linking/Cargo.toml, crates/linking/src/lib.rs
=> refactor: extract linking logic to separate crate

crates/config/src/lib.rs
resolving etherscan entries is a bit complex because we have several ways to configure this:
* etherscan as alias or key
* chain id
previously the configured chain id was not considered when looking up the etherscan table, now this does `chain.or(self.chain)`
this also unifies the two functions, need to check separately if the return values can be unified, I believe we did this because these are beneficial under certain circumstances
=> chore: unify etherscan resolve functions

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/backend/mem/mod.rs
Addresses #7245 
Ref: https://github.com/foundry-rs/foundry/issues/7245#issuecomment-1978532399
Added `--slots-in-an-epoch` arg to anvil cli. Default is `32`.
=> feat(anvil): configure slots_in_an_epoch

Cargo.lock, crates/anvil/Cargo.toml, crates/anvil/src/anvil.rs
Closes #7220
Currently implementation lacks evaluation of environment variables inside of `foundry.toml`, see thread.
Implements `load_dotenv` from `foundry-cli`, as we do in `cast`, `chisel` and `foundry`. This uses `dotenvy` to evaluate the environment variables.
=> fix(anvil): evaluate environment variables

crates/cast/src/lib.rs, crates/cast/tests/cli/main.rs, crates/cast/tests/fixtures/interface.json
closes https://github.com/alloy-rs/core/issues/555
remove constructor from the abi before generating the interface
=> fix: remove constructor when generating interface

crates/anvil/src/config.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/backend/mem/mod.rs
ref #7245
inject the genesis hash into the db, this should make it accessible from inside the evm
=> fix: insert genesis hash into db

crates/evm/core/src/backend/cow.rs, crates/evm/core/src/backend/mod.rs, crates/evm/evm/src/executors/mod.rs, crates/forge/src/multi_runner.rs
Name what it is not what it's used for, or something like that
=> chore: rename `FuzzBackendWrapper` to `CowBackend`

crates/config/src/lib.rs
Closes #6859
Not sure why it was `cached && build_info`, probably was meant to only write build info if we are writing any artifacts
=> fix(forge): correctly write build info

crates/forge/tests/it/repros.rs, testdata/fixtures/Json/Issue4402.json, testdata/fixtures/Toml/Issue4402.toml, testdata/foundry.toml, testdata/repros/Issue4402.t.sol
Closes #4402, no longer an issue, no changes required.
To make sure recent TOML cheatcodes work correctly on empty arrays, given that #4402 reportedly had issues at one time.
Adds a reproduction test to make sure this issue was indeed fixed and won't arise again.
=> fix(cheatcodes): add repro test for once reported issues around empty JSON arrays

crates/config/src/fuzz.rs, crates/config/src/invariant.rs, crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/lib.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/gas_report.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/it/test_helpers.rs
Closes #7313
Now the output of the `test --gas-report` from the [repro](https://github.com/aelmanaa/test-forge-gas-internal-tx/tree/main) is the following:
```
| test/Inv.t.sol:ContractA contract |                 |       |        |        |         |
|-----------------------------------|-----------------|-------|--------|--------|---------|
| Deployment Cost                   | Deployment Size |       |        |        |         |
| 154332                            | 534             |       |        |        |         |
| Function Name                     | min             | avg   | median | max    | # calls |
| increment                         | 48554           | 48554 | 48554  | 48554  | 1       |
| setNumber                         | 48795           | 68117 | 49077  | 103999 | 256 …
```
=> feat(test): include data from fuzz/invariant runs in gas reports

crates/config/src/lib.rs
Closes #4981
It seems that build-info is expected to always contain build info for all artifacts, and we can't aquire it from cached artifacts, so we enforce recompilation of all sources
=> fix: disable cache if build-info is requested

crates/forge/tests/cli/cmd.rs, crates/forge/tests/cli/config.rs, crates/forge/tests/fixtures/can_create_template_contract.stdout, crates/forge/tests/fixtures/can_create_using_unlocked.stdout, crates/forge/tests/fixtures/can_create_with_constructor_args.stdout, crates/forge/tests/fixtures/can_test_repeatedly.stdout, crates/forge/tests/fixtures/can_use_libs_in_multi_fork.stdout, crates/forge/tests/fixtures/repro_6531.stdout
new forge-std release broke some tests+fixtures
=> chore: update tests after new forge-std

crates/anvil/src/config.rs, crates/anvil/src/eth/backend/db.rs, crates/anvil/src/eth/backend/mem/fork_db.rs, crates/anvil/src/eth/backend/mem/in_memory_db.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/fork.rs, crates/evm/core/src/utils.rs
Closes #6749 
- use `storage.best_number` for `eth_blockNumber` call
- make sure best number is not overwritten when new blocks are mined
- dump and load `best_number` from state file
- fix issue reported with Arbitrum chain specifics not applied if `--chain-id` missing https://github.com/foundry-rs/foundry/issues/6749#issuecomment-1986961842 by calling `apply_chain_and_block_specific_env_changes` after chain id fetched from provider
=> fix(anvil): return correct block number for Arbitrum fork

crates/forge/bin/cmd/doc/mod.rs
While solving the issue #7331, I tested the `forge doc` on a sample contract.
Example to reproduce the issue:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;
interface IERC20 {
/**
* @notice Mints `amount` token to `recipient`.
* @param  recipient The address of the account receiving minted token.
* @param  amount    The amount of token to mint.
*/
function mint(address recipient, uint256 amount) external;
}
contract Test is IERC20 {
/// @inheritdoc IERC20
function mint(someType recipient, someType amount) external onlyOwner {}
}
```
Here you can some issues like `someType` is not a valid variable type and also `onlyOwner` isn't defined. But if we run `forge doc` here, it runs successfully without giving any errors and gives an output like this.
```markdown …
```
=> fix: compile contracts before generating docs

crates/debugger/src/tui/draw.rs, crates/evm/core/src/debug.rs, crates/evm/evm/src/inspectors/debugger.rs
ref #7382
use Bytes.clone to store calldata for opcode
=> chore: use Bytes to store calldata

crates/common/src/provider/retry.rs
ref https://github.com/alloy-rs/alloy/blob/09e90e8a76542aaffb3ac0c551a678f2e4fa2890/crates/transport-http/src/hyper.rs#L43-L47
ensures we can retry 429 errors
https://github.com/foundry-rs/foundry/actions/runs/8256007930/job/22583747756?pr=7383
=> chore: retry 429 errors

crates/evm/core/src/debug.rs, crates/evm/core/src/lib.rs, crates/evm/core/src/opcodes.rs, crates/evm/evm/src/inspectors/debugger.rs
ref https://github.com/foundry-rs/foundry/issues/7382
checks if the previously recorded step/opcode did not modify the memory, if so reuse the recorded memory from the previous step
https://bluealloy.github.io/revm/crates/interpreter/memory.html#opcodes
=> chore: reuse unmodified step memory

crates/common/src/provider/alloy.rs
Fixes #7381 
On ` ./target/debug/anvil.exe` gives me:
```bash 
Listening on 127.0.0.1:8545
```
And on `./target/debug/anvil.exe --fork-url 127.0.0.1:8545 --port 6969` gives me:
```bash
Fork
==================
Endpoint:       127.0.0.1:8545
Block number:   0
Block hash:     0x579aa11e37a4f00c05e15e9cbdba31cbb3cb6c32e990e510bab1e38635764261
Chain ID:       31337
Listening on 127.0.0.1:6969
```
=> feat: supports socket address as --rpc-url input

Cargo.lock, Cargo.toml, crates/cheatcodes/Cargo.toml, crates/cheatcodes/src/inspector.rs, crates/common/Cargo.toml, crates/common/src/compile.rs, crates/common/src/evm.rs, crates/evm/core/Cargo.toml, crates/evm/core/src/fork/backend.rs, crates/evm/core/src/ic.rs, crates/evm/coverage/Cargo.toml, crates/evm/coverage/src/analysis.rs, crates/evm/evm/src/executors/mod.rs, crates/forge/Cargo.toml, crates/forge/bin/cmd/coverage.rs, crates/forge/src/runner.rs
Ref https://github.com/foundry-rs/foundry/issues/7382
=> perf: use fxhash in maps when the key is small

crates/evm/core/src/ic.rs
And make it a bit more legibile.
=> chore: factor out common ic-pc code

Cargo.lock, Cargo.toml
Cancun adds three new opcodes (MCOPY, TLOAD, TSTORE) that we want to support when disassembling smart contract code from binary to human readable opcodes. 
Add new opcodes to the `evm-disassembler` library (see [pr](https://github.com/ckoopmann/evm-disassembler/pull/11)) and bump dependency (this pr)
=> Bump evm-disassembler dependency to support Cancun opcodes

crates/test-utils/src/util.rs
We often occur ci failures like that one: https://github.com/foundry-rs/foundry/actions/runs/8256390549/job/22584995567#step:12:362
basically, for some reason we are missing data from template project.
I think it might happen because of the race condition we have in `initialize` function which this PR addresses
=> chore: fix race condition on test project initialization

crates/test-utils/src/util.rs
CI for #7415 failed with this error again, it seems that the issue in fact is happening because process initializing template might fail, but will write "1" to lock file anyway: https://github.com/foundry-rs/foundry/actions/runs/8315673331/job/22754269551#step:12:127 - here it failed while running `forge build` with "Text file busy (os error 26)", not sure why exactly.
We should only write "1" to lockfile after we've successfuly copied template to its location, thus this PR just changes order of things.
=> chore: fix test project initialization

crates/common/src/compile.rs, crates/forge/tests/cli/build.rs
ref https://github.com/foundry-rs/forge-std/issues/522
ref https://github.com/foundry-rs/forge-std/pull/523
ignores all forge-std artifacts when `--build --sizes`
=> fix: ignore forge-std artifacts in build --sizes

Cargo.lock, Cargo.toml, crates/anvil/Cargo.toml, crates/anvil/tests/it/ganache.rs, crates/anvil/tests/it/geth.rs, crates/anvil/tests/it/otterscan.rs, crates/anvil/tests/it/revert.rs, crates/anvil/tests/it/traces.rs, crates/anvil/tests/it/utils.rs, crates/forge/Cargo.toml, crates/forge/tests/cli/svm.rs
closes #7405
becuase of breaking changes in svm, this replaces ethers-solc with foundry-compilers and adds some (temp) compat helpers until we fully migrate to alloy
=> chore: solc 0.8.25

crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/fuzz/src/error.rs, crates/forge/src/runner.rs
This should be valid because db commit on a new empty db with no forks has no side effects
=> chore: don't create a backend unnecessarily in ensure_success

Cargo.lock, Cargo.toml, crates/config/Cargo.toml, crates/config/src/inline/mod.rs, crates/config/src/inline/natspec.rs, crates/forge/src/lib.rs, crates/forge/tests/it/inline.rs
Fixes https://github.com/foundry-rs/foundry/issues/7310
=> feat: parse inline config with solang

crates/cast/bin/cmd/run.rs
closes #7426
this is not perfect, but should take care of cancun
=> fix: check for cancun in cast run

crates/common/src/evm.rs
we want to allow this because these settings can be used during cheatcode forking:
https://github.com/foundry-rs/foundry/blob/master/crates/cheatcodes/src/evm/fork.rs#L361-L366
=> fix: allow fork related cli args without forkurl

crates/forge/bin/cmd/bind.rs
=> fix: ignore build info in forge bind

crates/common/src/provider/runtime_transport.rs, crates/config/src/etherscan.rs
Closes https://github.com/foundry-rs/foundry/issues/7430
Ref https://github.com/foundry-rs/foundry/issues/6204
=> perf: load TLS certs only for https

crates/evm/fuzz/src/strategies/int.rs, crates/evm/fuzz/src/strategies/uint.rs
int strategy complicate can overflow
```
Message:  overflow
Location: crates/evm/fuzz/src/strategies/int.rs:71
8: <foundry_evm_fuzz::strategies::int::IntValueTree as proptest::strategy::traits::ValueTree>::complicate::h8a9032e00b3a6ca5
9: <proptest::strategy::unions::TupleUnionValueTree<(proptest::strategy::lazy::LazyValueTree<A>,core::option::Option<proptest::strategy::lazy::LazyValueTree<B>>)> as proptest::strategy::traits::ValueTree>::complicate::hdc78563564ff1e33 …
```
=> fix(fuzz): prevent int strategy to overflow when complicate

crates/anvil/core/src/eth/mod.rs
fixes: https://github.com/foundry-rs/foundry/issues/7433
* block_number in ots_getBlockDetails is a list so appropriate deserializer would be `lenient_block_number_seq`.
=> use correct deserializer for `ots_getBlockDetails`

crates/evm/traces/src/lib.rs, crates/forge/tests/fixtures/include_custom_types_in_traces.stdout, crates/forge/tests/fixtures/repro_6531.stdout
Displays the instruction result (AKA `EvmError: <...>`) alongside the return value in call traces. Example from https://github.com/foundry-rs/foundry/issues/7463:
---
See companion PR in evm-inspectors for more examples: https://github.com/paradigmxyz/evm-inspectors/pull/75
=> feat: write instruction result when displaying call traces

crates/debugger/src/tui/draw.rs, crates/evm/core/src/debug.rs, crates/evm/evm/src/inspectors/debugger.rs
I don't find this particularly useful and it complicates any potential upstreaming or code anywhere else
=> chore: remove Instruction enum in debug steps

crates/evm/fuzz/src/strategies/invariants.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantReentrancy.t.sol
Closes #4245 
```
Message:  no entry found for key
Location: crates/evm/fuzz/src/strategies/invariants.rs:29
8: core::option::expect_failed::hc85eb6037a3050f7
9: <proptest::strategy::map::Map<S,F> as proptest::strategy::traits::ValueTree>::current::h5c49d6f755e96fbf
10: <proptest::strategy::flatten::Flatten<S> as proptest::strategy::traits::Strategy>::new_tree::hd1899ce2fdb532df
11: …
```
=> fix(invariant): call override strategy panic

crates/debugger/src/tui/context.rs, crates/forge/bin/cmd/test/mod.rs
Helps with https://github.com/foundry-rs/foundry/issues/7386
We still have to clone it when flattening
=> perf(debugger): don't clone debug info twice

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/pool/mod.rs, crates/anvil/src/eth/pool/transactions.rs, crates/anvil/tests/it/anvil_api.rs
Context: #7250 
Adds `anvil_removePoolTransactions` method that removes pool transactions by sender origin.
=> feat(anvil): remove all txs from tx pool by sender origin

crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/tests/it/logs.rs
Before this PR, `eth_getTransactionReceipt` returns wrong `logIndex` in the logs. `logIndex` is supposed to be the position of the log in the entire block.
The fix is very straightforward so please refer to it directly. Also updated a test case to cover this piece.
=> [anvil] correct log index for getTransactionReceipt

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs
Currently anvil can running into error "EVM error MemoryLimitOOG"  closes https://github.com/foundry-rs/foundry/issues/7478
We add here a way to custom the memory limit for anvil node.
The default assigned here is 100 and can be changed if it's not the right default number.
EDIT: changed default value for memory-limit to 10000 after seeing all test related to anvil failling
=> feat(anvil): Add memery limit to anvil node

crates/anvil/src/cmd.rs, crates/anvil/src/config.rs
=> chore: move var to evm args

crates/config/src/inline/natspec.rs
inline config is not properly parsed when multiple tests in same file, for a file with 2 tests like
```Solidity
// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity >=0.8.0;
import "ds-test/test.sol";
contract FuzzInlineConf is DSTest {
/// forge-config: default.fuzz.runs = 1
function testInlineConfFuzz1() {}
}
contract FuzzInlineConf2 is DSTest {
/// forge-config: default.fuzz.runs = 2
function testInlineConfFuzz2() {}
}
```
the natspec parsed for `FuzzInlineConf2` is
```bash
{ 
contract: "inline/FuzzInlineConf2.t.sol:FuzzInlineConf2",
function: "testInlineConfFuzz2", line: "0:0:0",
docs: "forge-config: default.fuzz.runs = 1\nforge-config: default.fuzz.runs = 2" 
}
```
instead
```bash
{ 
contract: "inline/FuzzInlineConf2.t.sol:FuzzInlineConf2",
function: "testInlineConfFuzz2", …
```
=> fix(config): inline config intermingled

crates/anvil/src/eth/backend/executor.rs, crates/cast/bin/cmd/wallet/mod.rs, crates/forge/tests/it/test_helpers.rs, crates/script/src/artifacts.rs, crates/script/src/execute.rs, crates/script/src/simulate.rs, testdata/default/cheats/RpcUrls.t.sol, testdata/default/repros/Issue2956.t.sol, testdata/default/repros/Issue3221.t.sol, testdata/default/repros/Issue3223.t.sol, testdata/default/repros/Issue3674.t.sol
Ref https://github.com/foundry-rs/foundry/pull/7493#issuecomment-2020713999 cc @mattsse
=> chore: fix clippy and remove goerli usage from tests

Cargo.lock, crates/evm/fuzz/Cargo.toml, crates/evm/fuzz/src/strategies/state.rs
Closes #7503 
see https://github.com/foundry-rs/foundry/issues/7503#issuecomment-2022143142
=> perf(fuzz): use default std hasher for fuzz dict states

.github/workflows/release.yml, Cargo.lock, Cargo.toml, crates/anvil/Cargo.toml, crates/anvil/src/anvil.rs, crates/cast/Cargo.toml, crates/cast/bin/main.rs, crates/chisel/Cargo.toml, crates/chisel/bin/main.rs, crates/forge/Cargo.toml, crates/forge/bin/main.rs
We should be able to enable this on unix and x64. Cannot enable on:
- anvil: parity dependencies have something cursed going on that depend on the global allocator being the system one, otherwise it segfaults
- https://github.com/foundry-rs/foundry/issues/5754
- https://github.com/foundry-rs/foundry/issues/5756
- linux arm: incompatible page sizes, macos arm should be fine
- https://github.com/foundry-rs/foundry/issues/5832
=> perf: use `jemalloc` as the global allocator on unix (try 2)

crates/evm/fuzz/src/strategies/state.rs
=> chore: remove misleading/unneeded FxIndexSet type

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm.rs, crates/cheatcodes/src/utils.rs, crates/forge/tests/cli/script.rs, crates/test-utils/src/script.rs, testdata/cheats/Vm.sol, testdata/default/cheats/Broadcast.t.sol
Closes #7446
Adds `vm.sign(bytes32 digest)` determining signer in a similar way `vm.broadcast()` and `vm.startBroadcast()` do.
Adds `vm.sign(address signer, bytes32 digest)` similar to `vm.broadcast(address)`
Also added more docs to explain the way we choose signer for `vm.broadcast()` and it seems pretty complicated tbh. Afaik we still don't even have a reliable way to fetch signer address besides `vm.broadcast()` -> `vm.readCallers()`, perhaps we should reconsider and document that?
Also those cheatcodes are not compatible with tests right now. We can probably allow that by running tests with empty `ScriptWallets`. That way tests will be able to inject private keys via `vm.rememberKey`
=> feat: `vm.sign` for scripts

crates/anvil/src/eth/api.rs
Closes #7490 and changes code to avoid duplication of error handling logic between initial estimation vs binary search steps.
Adds `GasEstimationCallResult` which takes care of matching errors occured during call and fully covers all potential `InstructionResult`s to distinguish between out of gas errors, reverts and unexpected failures.
=> fix(anvil): clean up `eth_estimateGas`

crates/evm/coverage/src/analysis.rs, crates/evm/coverage/src/anchors.rs, crates/forge/bin/cmd/coverage.rs
Closes #7054
Closes #2567
Closes #4854
Closes #4654
Currently we're collecting anchors via the following steps:
1. Walk the AST for each contract definition to find coverage items contained in it along with its base contracts and potentially libraries.
2. Collect mapping from contract_id to coverage items contained in it itself or its base contracts/libraries.
3. Try to find anchors for each coverage item found in step 2.
This approach requires us to be able to reliably find libraries used by a contract which turned out to be non-trivial.
One possible approach could be to reuse some of #6936 code to walk through typed AST and find all contracts/libs used by a given contract. However, this might be breaking due to typed AST not working for some solc versions and this approach is also [not …
=> fix: coverage for libraries

flake.lock, flake.nix
Currently, nix builds fail due to usage of old nightly compiler and outdated dependencies in the lockfile.
```
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs:211:21:
not implemented: Shouldn't expect a placeholder type in implied bounds (yet)
```
Upgrade deps & migrate to stable.
=> chore: upgrade nix deps & migrate to stable

crates/forge/tests/cli/script.rs, crates/script/src/lib.rs
Having script function with many arguments can be annoying as you have to write stuff like `forge script --sig run(address,uint256,(address,uint256)...`
With this PR if only function name is provided as `--sig` argument and there is exactly one function with such name in the script ABI, then it will be used. Example above becomes just `forge script --sig 'run' 'ARG 1' 'ARG 2'`
cc @mds1 I remember we had discussion related to script UX and you mentioned that such UX improvements might result in footguns, so curious to know what you think about this
=> feat: allow supplying function name via `forge script --sig`

crates/forge/benches/test.rs
Closes #7531
see https://github.com/foundry-rs/foundry/issues/7531#issuecomment-2029209895 tests of project used could fail but it shouldn't panic test benchmark
use `cmd.print_output()` when benchmark (to also give an insight re tests execution outcome) instead assuming tests are executed with success
=> fix(bench): avoid panic if test benchmark execution not success

crates/anvil/src/lib.rs
Closes #7525 
Using the default IPC path:
```bash
./target/debug/anvil.exe --ipc \\.\pipe\anvil.ipc
IPC path: \\.\pipe\anvil.ipc
Listening on 127.0.0.1:8545
```
=> feat: print IPC path

crates/forge/bin/cmd/coverage.rs
Ref https://github.com/foundry-rs/foundry/pull/7510#issuecomment-2028893064
#7510 introduced bug which resulted in broken coverage reports for projects with multiple solc versions used.
We were collecting coverage items separately for each version, however, anchors search was done for each artifact, thus we were always overriding anchors data for all artifacts with data from last seen version.
=> fix: coverage bug

Cargo.lock, crates/common/Cargo.toml, crates/common/src/compile.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/linking/src/lib.rs, crates/script/src/build.rs, crates/script/src/execute.rs
Closes #7038
Rewrite `Linker` a bit to use `CompactContractBytecodeCow` as there is actually no need for linker to own artifacts in most of the cases
Changes test runner flow to keep library addresses used for the test run and link contracts before running the debugger.
=> fix: debugger doesn't work with external libraries

Cargo.lock, Cargo.toml, crates/config/Cargo.toml, crates/verify/src/etherscan/mod.rs
Closes #7485 
Incorporate the `chain_id` parameter while building etherscan client
=> feat(verify): multichain verification for etherscan

crates/common/src/compile.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs
Supersedes #7536
Allow keeping more than one bytecode for each source file id
=> fix: debugger breaks when source file has multiple contract definitions

crates/fmt/src/formatter.rs, crates/fmt/testdata/Repros/fmt.sol, crates/fmt/testdata/Repros/original.sol, testdata/default/cheats/RecordAccountAccesses.t.sol
Closes #7549 
apply indentation on closing parenthesis too
=> fix(fmt): fix indent closing parenthesis enclosed in { }

crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/inspector.rs, crates/evm/fuzz/src/strategies/calldata.rs, crates/evm/fuzz/src/strategies/mod.rs, crates/evm/fuzz/src/strategies/param.rs, crates/evm/fuzz/src/strategies/state.rs, crates/forge/src/runner.rs
Currently data collected during individual fuzz/invariant run (e.g. logs, storage writes) persists in fuzz dictionary resulting in large dictionary sizes due to it being flooded by data dependent on fuzz inputs. In #7551 case it resulted in dictionary accumulating log topics which directly contained fuzz inputs thus decreasing a chance of picking actually useful value from push byte as a fuzz input.
For fuzz tests we now don't call `collect_state_from_call` at all making calldata choice completely stateless.
For invariant tests I've refactored `EvmFuzzState` to keep track of all newly added keys and an option to remove them via `revert` fn. Thus, on invariant runs we accumulate and persist dictionary between separate calls, but it is getting cleared after each invariant sequence run. …
=> fix: do not flood dictionary with data dependent on fuzz inputs

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/string.rs, testdata/cheats/Vm.sol, testdata/default/cheats/StringUtils.t.sol
Closes #7487
It is my first time adding a cheatcode so let me know if I have done something wrong.
```bash
Ran 1 test for default/cheats/StringUtils.t.sol:StringManipulationTest
[PASS] testIndexOf() (gas: 7144)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 6.98ms (3.82ms CPU time)
Ran 1 test suite in 57.78ms (6.98ms CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```
=> Feat: Index cheatcode for Strings

crates/forge/tests/cli/script.rs, crates/script/src/execute.rs
Similar with https://github.com/foundry-rs/foundry/pull/7559 but for scripts
```
Error: 
script failed: custom error 31fec19b:
```
- use execution_artifacts revert decoder to decode result / show proper message
=> fix(script): decode custom error in script fail message

crates/forge/bin/cmd/test/mod.rs
Closes #7569
Always include all source files into compiler input when running tests to ensure that `getCode` can use artifacts from `src` without workarounds.
=> fix: always compile sources when running tests

crates/forge/bin/cmd/test/filter.rs, crates/forge/tests/cli/test_cmd.rs
Closes #7578
#7334 moved tests filtering to `TestArgs::get_sources_to_compile` which does not strip project root from paths opposed to `MultiContractRunner` which keeps them stripped. Thus, `--match-path` and `--no-match-path` filters are now broken.
Strip project root when filtering in `ProjectPathsAwareFilter`. Also added a test for this flag, it seems that we didn't have any
=> fix: `--match-path` is broken

crates/script/src/broadcast.rs, crates/script/src/lib.rs
Make batch size as a option.
We are developing a network based on zkevm - a new evm platform. We are trying to increase compatibility of MUD Framework and zkevm. We found that with the default batch size of 100, zkevm may not be able to handle it, with the --slow option the waiting time is too long. 
So we added batch size as an option to increase customization compatibility with many chains.
=> Make batch size as a option

crates/common/src/compile.rs
=> chore(forge): kB to B in build --sizes

crates/cheatcodes/src/config.rs, crates/cheatcodes/src/fs.rs, crates/chisel/src/executor.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/tests/it/cheats.rs, crates/forge/tests/it/test_helpers.rs, crates/script/src/execute.rs, crates/script/src/lib.rs, testdata/default/cheats/GetCode.t.sol, testdata/multi-version/Counter.sol, testdata/multi-version/Importer.sol, testdata/multi-version/cheats/GetCode.t.sol, testdata/multi-version/cheats/GetCode17.t.sol
One more fix after #7334 
If we've found multiple matching artifacts for `vm.getCode` and exactly one of them matches version of the currently running test/script source, return that.
Ref https://t.me/foundry_support/52016
This changes test runner flow a bit so we now create executor for each `ContractRunner` to alter cheatcodes config with running contract version
=> fix: smarter `getCode` validation

crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantCustomError.t.sol
Closes #4178 
- atm failed invariant case revert reason with custom error is decoded only with Invariant contract ABIs, hence showing reason as `FAIL. Reason: custom error d14cf5d4:]`
- fix by using also target contracts abis to decode revert reason
=> fix(invariant): decode custom error with target contract abis

crates/cast/bin/cmd/logs.rs
Removed all the ethers-rs components used for `cast logs`. 
Use `resolve()` to convert arguments to DynSolType, replacing the previous `kind` property.
Previously could use `event.filter()` to convert indexed arguments into topic hashes, now explicitly calling abi-encode on provided arguments. Defaulting to an empty topic if the argument is empty.
Updated the unit tests and tried locally using my bash history for `cast logs`.
=> refactor cast logs to use alloy

Cargo.lock, crates/anvil/Cargo.toml, crates/anvil/src/eth/fees.rs
=> chore: use alloy calc next block base fee

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/fs.rs, testdata/cheats/Vm.sol, testdata/default/cheats/Prompt.t.sol
Closes #5509 
cc @mattsse 
In case of parse failure, it fails with these errors:
```bash
[FAIL. Reason: failed parsing "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293B" as type `address`: parser error:
0x3C44CdDdB6a900fa2b585dd299e03d12FA4293B
^
Odd number of digits] testPrompt_Address() (gas: 2948)
```
```bash 
[FAIL. Reason: failed parsing "-1" as type `uint256`: parser error:
-1
^
expected at least one digit] testPrompt_Uint() (gas: 3008)
```
=> feat(forge): prompt address and uint cheatcodes

crates/anvil/core/src/eth/block.rs
ref #7621
dont set withdrawals root hash,
maybe we should set empty_root hash
=> fix: dont set withdrawals root

crates/cheatcodes/src/inspector.rs
Closes #7603
This logic was added in #7207 and it doesn't make much as sense as the CREATE2 is still being performed on the same call depth, it will be on depth+1 only when broadcasted onchain which is out of scope of state diff
=> fix: state diff for broadcasted CREATE2 deployments

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/pool/mod.rs, crates/anvil/src/eth/pool/transactions.rs
Fixes #7249
Added a new rpc method, and added the corresponding implementation in the mod.rs file for pool.
=> Adds rpc method for anvil to drop all pending transactions

crates/anvil/src/eth/backend/executor.rs, crates/anvil/src/eth/backend/mem/mod.rs
=> fix: set OP enveloped tx field

crates/forge/bin/cmd/coverage.rs
Closes #6853
Add `--include-libs` flag to `forge coverage` which results in command also collecting coverage data for libraries.
=> feat: allow including libraries into coverage report

crates/verify/src/bytecode.rs
Ref #7667.
Improve error handling for unset etherscan API key. Report error instead of panicking.
=> fix(verify): improve err handling for unset etherscan api key

crates/evm/traces/src/identifier/etherscan.rs
Closes #7558 
Currently the resolved Etherscan traces are only applied to the first occurrence of an address due to the resolved addresses not being captured and returned, see:
https://github.com/foundry-rs/foundry/blob/ee47bb01ee8aa042639cc9ae86a2a3cf6ab9d037/crates/evm/traces/src/identifier/etherscan.rs#L114-L118
Reproducible by running minimal repro: https://github.com/zerosnacks/foundry-repro-7558
Implementation is largely pragmatic, emphasis on minimal changes - open to feedback
=> fix(traces): Etherscan traces are only resolved for first instance of test run

crates/evm/core/src/backend/mod.rs, testdata/default/cheats/Fork.t.sol
Solves #7633
Adds the following line to `update_current_env_with_fork_env()`:
```rust
current.tx.chain_id = fork.tx.chain_id;
```
Apologies if this breaks or leads to unforeseen behavior as I'm _relatively_ new to fork testing. 
I'm always happy to hear how this can be improved!
=> chore(fork): adjust `chain_id` when updating local env with fork

crates/common/src/contracts.rs, crates/evm/coverage/src/analysis.rs, crates/evm/coverage/src/lib.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/strategies/state.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/local.rs, crates/evm/traces/src/lib.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/src/coverage.rs, crates/forge/src/multi_runner.rs, crates/script/src/artifacts.rs, crates/script/src/build.rs, crates/script/src/execute.rs, crates/script/src/lib.rs, crates/script/src/simulate.rs, crates/script/src/transaction.rs, crates/script/src/verify.rs
Closes #3453
Closes #1963
This PR includes general refactor of code using `ContractsByArtifacts` extending it to contain both creation and runtime code. Currently it can only fit one bytecode type thus resulting in script code generating different `ContractsByArtifacts` object for different purposes making code a bit harder to navigate. This allowed to add more context to `MultiContractRunner::known_contracts` and simplify scripting code a bit by storing `ContractsByArtifacts` directly instead of generating each time.
Added creation code to `ContractsByArtifacts` allowed us to map collected hitmaps for creation codes to artifacts via `find_by_creation_code` fn, thus extending coverage to also process creation code just required duplicating anchors discovery and processing logic
=> feat: coverage for constructors

crates/cli/src/opts/build/core.rs, crates/forge/tests/cli/config.rs
Closes #7488 
Adds `--no-metadata` as CLI option, equivalent to passing `--no-cbor-metadata  --metadata-hash none` to `solc` or defining:
```
bytecode_hash = "none"
cbor_metadata = false
```
in `foundry.toml`.
Considering the requirement for deterministic builds is common I think it makes sense to add a CLI option that bundles the two as requested.
For comparison between `forge build` and `forge build --no-metadata`: https://jsoncompare.com/#!/diff/id=f0200fd7445202aefdf057a353664f29/
Open to feedback, it may make more sense to decouple the two, contrary to the proposal, and allow users to pass `--no-cbor-metadata --bytecode-hash="none"`.
=> feat(forge-cli): Add `--no-metadata` as CLI compiler option 

Cargo.lock, crates/debugger/Cargo.toml, crates/debugger/src/tui/context.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs
Update ratatui from 0.24 to 0.26, the only observable breaking change is Layout builder method params were moved to the `new` method.
Use builtin `List` widget to handle printing opcodes. This fixes a bunch of logic errors with that code that nobody wants to debug by removing it.
Differences:
- the highlight symbol is before the index instead of the opcode name
- 1 opcode padding instead of whatever that code did, meaning the highlight will stop 1 before the end
- this would just go off screen if the box was too small
- the highlight spans across the entire box rather than just behind the text
Some other misc fixes:
- generate the opcode list after the event has been handled. Fixes a small bug when changing call context as the opcode list would be the wrong one until another event was …
=> feat(debugger): update ratatui, use `List`

crates/evm/coverage/src/analysis.rs
Closes #3489
Visit modifiers when collecting coverage items. I've excluded placeholder statements (`_;`) from coverage reports because they never get referenced in source maps thus we can't really provide any coverage info for them.
=> feat: coverage for modifiers

crates/cheatcodes/src/inspector.rs, testdata/default/cheats/MemSafety.t.sol
Fixes the `stopExpectSafeMemory` cheatcode by allowing for the memory allocation of the `stopExpectSafeMemory` selector as well as the potentially out-of-bounds read performed in the `CALL` operation to the cheatcode contract.
Currently, forge reports incorrectly that memory safety was violated in a memory safe region of a test, if the free memory pointer was updated to `[exclusiveUpperBound-31, exclusiveUpperBound]` during execution and is followed by a `stopExpectSafeMemory` call.
To fix this, we allow for `MSTORE` operations that store the selector bytes for `stopExpectSafeMemory`, as well as `CALL` operations that are to the cheatcode address and contain the `stopExpectSafeMemory` selector in the first 4 bytes of the call arguments, even if they write/read from outside of the allowed …
=> fix(cheatcodes): `expectSafeMemory` + `stopExpectSafeMemory`

Cargo.lock, crates/anvil/Cargo.toml, crates/cast/Cargo.toml, crates/cast/bin/cmd/logs.rs, crates/forge/Cargo.toml
closes #7682
use builtin transport if --subscribe
also enables missing features
=> fix: hotfix cast logs subscribe

crates/config/src/lib.rs
reverts #4427 
closes #7689
> PR https://github.com/foundry-rs/foundry/pull/4427 ignores optimizer_details if optimizer is disabled. However, optimizer = false [doesn't completely disable optimizations](https://github.com/ethereum/solidity/blob/bbb7f58be026fdc51b0b4694a6f25c22a1425586/docs/using-the-compiler.rst?plain=1#L282-L284), and in order to so [additional optimizer details have to be provided](https://github.com/ethereum/solidity/blob/bbb7f58be026fdc51b0b4694a6f25c22a1425586/docs/using-the-compiler.rst?plain=1#L293-L294).
=> fix: always set optimizer details

foundryup/foundryup
Ref https://github.com/ethereum-optimism/optimism/pull/10180 where the default flags appear to cause issues
=> build(foundryup): allow caller to override rust flags

Cargo.lock, Cargo.toml, crates/cli/src/utils/cmd.rs, crates/common/Cargo.toml, crates/common/src/compile.rs, crates/config/src/lib.rs, crates/forge/bin/cmd/create.rs, crates/forge/bin/cmd/flatten.rs, crates/forge/bin/cmd/selectors.rs, crates/forge/tests/fixtures/can_create_template_contract.stdout, crates/forge/tests/fixtures/can_create_using_unlocked.stdout, crates/forge/tests/fixtures/can_create_with_constructor_args.stdout, crates/script/src/build.rs
Currently when running `forge script <contract_name>` or `forge script <contract_path>` we will recompile entire project, this is true for `forge create` and `forge selectors` as well.
Use already existing files filter on `ProjectCompiler` when path is provided, use solang AST to find source file when only contract name is provided.
=> feat: optimize compilation by reading AST

crates/cheatcodes/src/config.rs, crates/cheatcodes/src/fs.rs, crates/common/src/contracts.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/traces/src/lib.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/it/repros.rs, crates/forge/tests/it/test_helpers.rs, crates/script/src/build.rs, crates/script/src/execute.rs, crates/script/src/lib.rs
Follow-up to #7661 extending usage of `ContractsByArtifact`
Closes #4876
Rewrite `getCode` logic to directly use compilation artifacts instead of reading them from filesystem. This makes it possible to use `getCode` in tests which were compiled without writing artifacts (which is happening in coverage for example).
This also separates `known_contracts` per each test contract. This is needed because different test contracts might be linked with different libraries, thus having a single `known_contracts` object is incorrect and might result in invalid `getCode` output or identifiers failing to identify contracts. This introduces overhead of cloning compiler output for each running test which shouldn't affect performance much I believe.
Related to #1161 and #4049 but not resolves in full …
=> fix: better artifacts management for `getCode`

crates/cast/bin/cmd/run.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/evm/src/inspectors/stack.rs
Partially reverts https://github.com/foundry-rs/foundry/pull/7437
Use revm's printer which looks an expanded version of the one we had before
=> feat: temporarily re-introduce custom trace printer

crates/cheatcodes/src/config.rs
allows ipc paths as fork url
tested locally
```
uint256 anotherFork = vm.createSelectFork("/tmp/reth.ipc");
console.log(vm.getBlockNumber());
```
=> feat: support ipc path as rpc url

crates/anvil/core/src/eth/block.rs, crates/anvil/core/src/eth/transaction/mod.rs
Closes #7698
Implement `Encodable2718` for `TypedTransaction` and use correct encoding for transactions root calculation.
alloy does not expose methods for encoding transaction types other than `TxEnvelope::encode_2718`, so currently this impl clones txs to construct `TxEnvelope`. We should probably expose `encode_with_signature` methods used [here](https://github.com/alloy-rs/alloy/blob/09241dc647def90423210a89f896b967cb2aa890/crates/consensus/src/transaction/envelope.rs#L252) to avoid this
=> fix: use 2718 encoding for transactions trie root calculation

crates/cheatcodes/src/fs.rs, crates/common/src/contracts.rs, crates/evm/traces/src/identifier/local.rs, crates/script/src/execute.rs, crates/script/src/lib.rs, crates/script/src/transaction.rs, crates/script/src/verify.rs
Closes #7702
Exclude artifacts with present but empty bytecode from `ContractsByArtifact`. Such contracts are usually abstract contracts or interfaces. Also adds additional safety check to `VerifyArgs`
=> fix: exclude empty artifacts from `ContractsByArtifact`

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/evm.rs, testdata/cheats/Vm.sol, testdata/default/cheats/Prevrandao.t.sol, testdata/default/cheats/Setup.t.sol, testdata/default/cheats/Snapshots.t.sol
fix: #7693
change Vm.prevrandao type
=> fix: Type parameter of Vm.prevrandao as uint256

Cargo.lock
details: https://cxsecurity.com/cveshow/CVE-2024-32650/
> `rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input. When using a blocking rustls server, if a client send a `close_notify` message immediately after `client_hello`, the server's `complete_io` will get in an infinite loop. This vulnerability is fixed in 0.23.5, 0.22.4, and 0.21.11.
The version of `rustls` foundry depends on both 0.21.10 and 0.22.3, so by upgrading them to 0.21.11 and 0.22.4 will solve the problem
=> chore(deps): update rustls to 0.21.11 and 0.22.4 for security reason

crates/script/src/build.rs
Closes #7732, similar to #7572
I believe we should add a way for files to "import" other sources into compiler input other than Solidity imports to allow such setups with `getCode`. Something like https://github.com/foundry-rs/foundry/issues/7025 should work (but I don't really like this exact approach)
=> fix: always compile sources when running scripts

crates/common/src/compile.rs, crates/forge/bin/cmd/build.rs, crates/forge/tests/cli/cmd.rs, crates/verify/src/bytecode.rs
Closes https://github.com/foundry-rs/foundry/issues/7730
keep root path and try matching stripped path as well
=> fix: correctly process relative paths as `--skip` values

crates/forge/tests/cli/script.rs, crates/script/src/lib.rs
Closes #4822
We now do not require users to explicitly provide senders for `--unlocked` and resolve them from collected transactions instead: https://github.com/foundry-rs/foundry/blob/30f145ff677eb01361f7f05c3233c133d1fd0d5b/crates/script/src/broadcast.rs#L207
=> fix: do not require `--sender` with `--unlocked`

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/env.rs, testdata/cheats/Vm.sol, testdata/default/cheats/Env.t.sol
Inside some of my tests I need to have a pretty advanced environment configuration with potential forks yet I cannot just do it in a clean way as if I load a environment variable that doesn't exists it will reverts. So currently I am using a vm.ffi to bypass this problem and use bash instead to check if the environment variable exists.
Add a cheatcode that can tell if a environment variable exists or not
=> feat: add envExists cheatcode to check if a environment variable exists

crates/forge/bin/cmd/coverage.rs
Currently `forge coverage` does not print any data if tests are failing. This is not really great UX if tests are running for long time and might result in coverage generating incomplete/empty reports without any feedback.
include `TesetArgs` into `CoverageArgs` and invoke `run_tests` on it.
=> fix: print test results while running coverage

crates/anvil/src/eth/otterscan/api.rs, crates/anvil/tests/it/otterscan.rs
Anvil currently returns a transaction object from `ots_getTransactionBySenderAndNonce`, but both the Otterscan execution specs (https://otterscan.github.io/execution-apis/api-documentation/) and the Foundry Book itself (https://book.getfoundry.sh/reference/anvil/) say it should return the transaction hash. Users can't navigate by sender nonce in Anvil-backed Otterscan instances because if this mistake.
Simply return the transaction hash rather than the complete transaction object.
Fixes #7740 
I wasn't aware of some extra requirements to run the tests, namely:
Setup:
* Install `gcc`
* Install `make`
* Install `solc`
* Install `libopenssl-dev`
And for formatting:
```
rustup toolchain install nightly
```
It would be helpful if these instructions were added to or linked from the contributing …
=> fix(anvil): Return transaction hash in ots_getTransactionBySenderAndNonce

crates/cast/bin/cmd/wallet/list.rs
Don't filter out files with extensions
Fixes https://github.com/foundry-rs/foundry/issues/7520
=> fix(cast): list all files in the keystore directory

crates/cast/bin/main.rs, crates/cast/src/lib.rs, crates/cast/tests/cli/main.rs, crates/common/src/ens.rs
The classic no tests were present for these commands
The bug was in `get_resolver` using "eth" always instead of the given name/address
Fixes https://github.com/foundry-rs/foundry/issues/7759
=> fix(cast): ENS commands

crates/anvil/src/eth/api.rs
We wrongly compare specified limit with MAX_BLOCK_COUNT, it is even possible to specify 2000 and receive huge response.
Fixes https://github.com/foundry-rs/foundry/issues/7778
Change max to min
=> fix(anvil): take block count limit in fee history into account

crates/anvil/src/config.rs
Closes https://github.com/foundry-rs/foundry/issues/7789
=> fix: set gas limit to `u64::MAX`

crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/fees.rs, crates/anvil/tests/it/gas.rs
Closes #7769 
Logic for determining pending block base fee is currently different in `eth_feeHistory` handler and miner itself. Thus, using value for pending block base fee returned by `feeHistory` will result in errors as it will be lower than actual base fee
This PR contains 2 changes:
1. Correctly process empty genesis block, thus base fee for 1st block is `87500000000` by default as genesis block is always empty.
2. Use alloy calculation fn in `eth_feeHistory`.
=> fix: `eth_feeHistory`

crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/funcs.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantShrinkFailOnRevert.t.sol
Currently if `fail_on_revert` set to true we fail to shrink sequence due to
- `func` is an `Option` in `FailedInvariantCaseData` but not set / available when `fail_on_revert`
https://github.com/foundry-rs/foundry/blob/1fc4aa34c4331c12aaa8ee831b16b80b7d5a446f/crates/evm/evm/src/executors/invariant/mod.rs#L739-L743
so not available to check invariant when replaying / shrinking sequence
https://github.com/foundry-rs/foundry/blob/1fc4aa34c4331c12aaa8ee831b16b80b7d5a446f/crates/evm/evm/src/executors/invariant/error.rs#L273
- calls in failing sequence are not checked for reverts when shrinking, so sequence cannot be identified as failing
https://github.com/foundry-rs/foundry/blob/1fc4aa34c4331c12aaa8ee831b16b80b7d5a446f/crates/evm/evm/src/executors/invariant/error.rs#L261-L265
- always pass …
=> fix(invariant): shrink when fail-on-revert set to true

crates/forge/bin/main.rs
continuation of https://github.com/foundry-rs/foundry/pull/7809 
Realized that we allow configuring fuzz cache dir to point to a dir outside of proj root, it is safer to delete only paths relative to proj root to avoid any confusion / unexpected behavior.
=> chore(fuzz): delete fuzz dir relative to proj root

crates/config/src/lib.rs, crates/config/src/macros.rs
closes #7715
a lot of cast commands make use of `Config::from(RpcOpts)` which always resolved remappings.
This introduces a way to configure what kind of providers should be invoked when populating `Config -> Figment`
The `impl_figment_convert_cast` now skips remappings.
This could be further improved by adding more settings, but should be good enough
=> perf: support FigmentProviders settings

crates/anvil/src/eth/otterscan/api.rs, crates/anvil/src/eth/otterscan/types.rs, crates/anvil/tests/it/otterscan.rs
Fixes #7516.
Anvil's `ots_searchTransactionsBefore` and `ots_searchTransactionsAfter` are not compliant to the specification, making transaction navigation in Otterscan buggy when using an Anvil backend.
This PR fixes multiple bugs in the `ots_searchTransactionsBefore` and `ots_searchTransactionsAfter` implementations, namely fulfilling that
* Results must be given in reverse chronological order for both functions
* `firstPage` indicates that the results include the most recent transaction
* `lastPage` indicates that the results include the oldest transaction
* Scanning must continue even after the page of results is filled in order to check whether this is the first/last page
* Results should only include transactions before/after the block number provided as a parameter, rather than …
=> fix(anvil): Otterscan searchTransactions behavior

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/tests/it/sign.rs
As per [Ethereum JSON-RPC API Specification](https://ethereum.github.io/execution-apis/api-documentation), the `eth_signTransaction` method should return an RLP encoded transaction payload. Anvil is just returning the signature.
Also the parameters of the transaction MUST be part of a sequence.
This PR returns the signed payload in `eth_signTransaction` request and also configures the deserializer to deserialize params using a sequence.
A happy path test was also added in `tests/it/sign.rs` (Was not sure if I should put the test there or in `tests/it/transaction.rs`)
Thank you!
=> Fix `eth_signTransaction` request and response

crates/anvil/src/eth/otterscan/api.rs, crates/anvil/tests/it/otterscan.rs
Closes #7836 
Fixes `ots_getTransactionError` behavior in the case where there is no transaction error or one can't be found (e.g., out of gas). API reference: https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_gettransactionerror
Return `0x` (an empty Bytes object) instead of null.
=> fix(anvil): `ots_getTransactionError` default return

crates/evm/core/src/decode.rs, crates/evm/core/src/utils.rs, crates/evm/traces/src/decoder/mod.rs, crates/forge/tests/cli/script.rs
Closes https://github.com/foundry-rs/foundry/issues/7833
Overriden `create` handler was returning `FrameResult::Create` when reverting on missing CREATE2 deployer which caused it to be received by `insert_create_outcome` hook of default handler register which was panicking because it never seen the initial call.
Return `FrameResult::Call` and change order of things a bit so that stack of create2 register is correct once we receive revert in `insert_call_outcome`
=> fix: avoid panic on missing CREATE2 deployer

crates/anvil/src/eth/backend/mem/mod.rs
4844 tx simulation would fail due to `blob_hashes` being set to empty, despite being present in the request. 
Include `blob_version_hashes` from tx req into revm `TxEnv`
=> fix(anvil): include blob hashes in call env

crates/anvil/src/eth/error.rs
Currently mapping to `revm::InvalidTransaction::BlobVersionNotSupported` to `BlobVersionedHashesNotSupported`, which is wrong.
Should be mapped to `BlobVersionNotSupported`
=> fix(anvil): correctly use `BlobVersionNotSupported`

crates/anvil/src/eth/api.rs
I think a transfer w/ an empty value is still technically valid? Viem's tests are failing with the latest foundry and reporting `21001` gas instead of `21000` for empty value transfer.
Ref: https://github.com/wevm/viem/actions/runs/8946647082/job/24580052493#step:5:2857
=> fix: transfer check

crates/evm/evm/src/executors/invariant/mod.rs, testdata/default/fuzz/invariant/targetAbi/TargetArtifactSelectors.t.sol, testdata/default/fuzz/invariant/targetAbi/TargetArtifactSelectors2.t.sol
- consistent naming `FuzzArtifactSelector` instead `FuzzAbiSelector`
=> chore(invariant) - rename TargetAbiSelector

Cargo.lock, Cargo.toml, crates/anvil/Cargo.toml, crates/cast/Cargo.toml, crates/cheatcodes/src/evm/fork.rs, crates/cheatcodes/src/utils.rs, crates/chisel/Cargo.toml, crates/chisel/src/dispatcher.rs, crates/chisel/src/executor.rs, crates/cli/Cargo.toml, crates/cli/src/utils/mod.rs, crates/common/Cargo.toml, crates/common/src/lib.rs, crates/evm/core/Cargo.toml, crates/evm/core/src/opts.rs, crates/evm/core/src/utils.rs, crates/evm/evm/src/executors/tracing.rs, crates/evm/traces/Cargo.toml, crates/evm/traces/src/identifier/etherscan.rs, crates/forge/Cargo.toml, crates/forge/bin/cmd/test/mod.rs, crates/forge/bin/main.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs, crates/script/src/execute.rs, crates/verify/Cargo.toml, crates/wallets/Cargo.toml
Not necessary, we're always in a tokio runtime, and even if we weren't, we don't want to create and destroy a runtime on every call.
=> chore: stop using RuntimeOrHandle

crates/config/README.md, crates/config/src/invariant.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/forge/tests/cli/ext_integration.rs, crates/forge/tests/it/invariant.rs, crates/forge/tests/it/test_helpers.rs
Closes #7268 
Closes #4994 
Remove `preserve_state` config and commit call by default - this will enable using `vm.warp` and `vm.roll` in invariants tests without any additional config (which is expected behavior)
From test result it can be seen there is a slightly penalty from persisting cheatcode state (not something to worry about IMO).
Results were collected by performing different number of runs and depth on a test contract with:
- handler that advance block timestamp by 100 and increments block number on each call by using `vm.warp` and `vm.roll`  (worst case scenario as persisting cheatcode states is now done by default)
- target contract with single selector that makes several state updates
<details>
<summary>Test contract</summary>
```solidity
contract CommitState {
uint256 …
```
=> chore(invariant): remove persist_state config, commit by default

crates/config/README.md, crates/config/src/invariant.rs, crates/config/src/lib.rs, crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/invariant/replay.rs, crates/evm/evm/src/executors/invariant/shrink.rs, crates/forge/tests/it/test_helpers.rs, testdata/foundry.toml
-  remove `shrink_sequence` config (same as `shrink_run_limit = 0 `)
=> chore(invariant): remove shrink_sequence config

crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/backend/mem/mod.rs
When a tx is sent, upon validation we are checking the `tx.gas_price()` against the `block.basefee`. The value returned from `tx.gas_price()` is `max_fee_per_blob_gas` in case of a 4844 tx, which would more often than not be less than that of 1559 basefee, especially on startup. 
This would cause the transaction to be failed with error `InvalidTransactionError::FeeCapTooLow` even though `max_fee_per_gas` would have been set correctly.
Check which type of tx is incoming and associate `gas_price` correctly.
=> fix(anvil): `tx.gas_price()` return val

Cargo.lock, crates/cast/Cargo.toml, crates/cast/bin/cmd/bind.rs, crates/wallets/src/utils.rs
Can already be replicated using two different commands: `cast etherscan-source` and `forge bind`.
=> chore: remove `cast bind`

crates/cheatcodes/src/evm.rs, crates/cheatcodes/src/evm/fork.rs, crates/cheatcodes/src/inspector.rs, crates/cheatcodes/src/script.rs, crates/forge/tests/cli/script.rs, crates/script/src/runner.rs
Current approach with nonce correction is not really straightforward as nonce is getting corrected only when invoking certain cheats.
Currently this results in issues when executing the following example:
```solidity
contract SimpleScript is Script {
function setUp() external {
uint256 initialFork = vm.activeFork();
vm.createSelectFork("<url>");
vm.selectFork(initialFork);
}
function run() external {
assert(vm.getNonce(msg.sender) == 0);
}
}
```
Specifically, the issue is in this line:
https://github.com/foundry-rs/foundry/blob/503792a1dbadd901a4c02f6fcd1de1caff1573ff/crates/cheatcodes/src/evm/fork.rs#L119-L122
We assume here that we've either corrected nonce on the current fork or will not come back to it. This could've been fixed by adding `correct_sender_nonce` invocation but imo …
=> fix: nonce correction logic

crates/cast/bin/main.rs, crates/cast/bin/opts.rs, crates/cast/src/lib.rs
foundry `cast` implements command `cast from-utf8` but no features like `cast to-utf8`. 
This PR aims to provide the function `cast to-utf8`. 
// 你好 means "Hello"
```shell
cast --from-utf8 "你好"
0xe4bda0e5a5bd
```
```shell
cast --to-utf8 0xe4bda0e5a5bd
你好
```
=> feat(cast): support convert hex data to a utf-8 string

crates/cast/bin/cmd/wallet/mod.rs, crates/cast/tests/cli/main.rs
After integrating `cast wallet import` and using it for a while, some users might want to get the private key for an account back through decryption of the keystone, so we're just making it easy for them in the same cli they created the keystore.
Added an extra command `DecryptKeystore` to the `WalletSubcommands` enum, alongside the implementation where we verify the file exists, prompt for the password (they can also send it in clear text from the cli call if they wish to), decrypt the keystore to instantiate a `LocalWallet` and then make it an alloy `B256` so it formats properly in the print.
=> feat(cast): wallet keystore decrypting

crates/config/src/lib.rs, crates/evm/evm/src/executors/mod.rs, crates/forge/tests/cli/config.rs, crates/forge/tests/cli/script.rs, crates/linking/src/lib.rs, crates/script/src/build.rs, crates/script/src/execute.rs, crates/script/src/lib.rs, crates/script/src/runner.rs, crates/test-utils/src/script.rs
Closes #4810
ref https://github.com/foundry-rs/foundry/pull/7027#discussion_r1481556804
This PR introduces a new approach to library linking for scripts. If CREATE2 deployer is present on target chain, ibraries are deployed through it, and only if they have not been deployed before. This makes it possible for users to run scripts without ever thinking about library deployment and need to provide addresses in `foundry.toml` or via `--libraries` args.
Salt for deployments can be configured through `create2_library_salt`.
It is not possible to link libraries with cyclic dependencies in such way, so we are still falling back to default linking algo if error occurs.
=> feat: library deployments though CREATE2

crates/verify/src/provider.rs
To add support for the OKLink explorer contract verification. since the OKLink use almost the same API as the etherscan does for the contract verification part. the only difference is that the OKLink requires the Ok-Access-Key pass in the header, while etherscan requires the x-apiKey pass in the header. 
To make the OKLink API more similar to the Etherscan API, the oklink backend decide to handle the API_KEY the same as etherscan does. so, we basically only add an entry point as blockscout does. 
Reference
- https://www.oklink.com/docs/zh/#explorer-rpc-api-contract-verifysourcecode
Closes https://github.com/foundry-rs/foundry/issues/7724
closes https://github.com/foundry-rs/foundry/pull/7586
=> forge(verify): OKLink support

crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/fuzz/types.rs, crates/forge/tests/cli/test_cmd.rs
**Closes #7928  #3843 **
when using fuzz test, `console.log` doesn't work as expected(display console log info). this PR is to fix `console.log` in fuzz test
current version of foundry only keep the logs for failed fuzz test case. so in this PR, added `logs` to keep logs in every `CaseOutcome` and display logs for every run case in a fuzz test.
=> fix: fuzz console log

crates/evm/evm/src/executors/fuzz/mod.rs, crates/evm/evm/src/executors/fuzz/types.rs, crates/forge/tests/cli/test_cmd.rs
This reverts commit a470d635cfcdce68609e9dc5762a3584351bacc1.
https://github.com/foundry-rs/foundry/pull/7781 adds ability to log during all fuzz runs, but it introduces unexpected behavior due to the bound result being logged in forge-std, see 
https://github.com/foundry-rs/foundry/pull/7781#issuecomment-2115828404
- revert commit and check if any special reason for forge-std logging bound results before adding back
=> Revert "fix: fuzz console log (#7781)"

crates/forge/src/lib.rs, crates/forge/tests/cli/test_cmd.rs
Closes #4139 
if I am not missing something here, there is no need to run additional shrinks for fuzz failed cases because
- for single standard fuzz test we already have the counterexample (one call) to break the test
- for invariant tests we do shrunk sequence outside proptest
`TestRunner.run` calls `TestRunner.run_in_process_with_replay` which in turn execute our test by calling `call_test`
https://github.com/proptest-rs/proptest/blob/63ef67c71ff050b473d2137fd3abce6115d0216b/proptest/src/test_runner/runner.rs#L713-L752
the result is matched and then shrunked in a loop until strategy cannot simplify it anymore or up to `max_shrink_iters` (since it is  not specified it defaults to `std::u32::MAX`)
https://github.com/proptest-rs/proptest/blob/63ef67c71ff050b473d2137fd3abce6115d0216b/propte …
=> fix(fuzz): do not exceed configured runs

crates/forge/bin/cmd/test/filter.rs, crates/forge/bin/cmd/test/mod.rs
Currently when running `forge test` all files under `./test` will be passed to compiler on initial ABI-only run. This might be an issue if files being filtered out can't be compiled for some reason.
Apply test filter as sparse output filter in a similar way `forge build --skip` works
=> fix: apply `--no-match-test` when invoking compiler

crates/config/src/lib.rs, crates/forge/tests/cli/config.rs
This adds a `prague = true` option to foundry.toml which enables Prague SpecId.
This is a temp measure that will get phased out once solc recognizes the prague version, until then the solc target and evm can be configured independently
=> feat: add tmp prague config value

crates/config/src/lib.rs, crates/forge/tests/cli/config.rs
cancun has been marked as deprecated
can remove setting now, warning should make this obvious
=> chore: remove cancun setting

crates/config/src/providers/mod.rs
1. it would literally try to match `"<profile>.<key>"`, which doesn't match any set deprecated key
2. it would not recurse into the current profile so `profile.default.cancun` never gets visited
=> fix(config): deprecated key warnings

crates/cheatcodes/src/fs.rs, crates/config/src/lib.rs, crates/forge/tests/cli/config.rs
Closes https://github.com/foundry-rs/foundry/issues/7973
With `unchecked_cheatcode_artifacts`, we are relying on old `getCode` behavior when `getCode("Contract")` is being mapped to artifact path in the form of `out/Contract.sol/Contract.json`. This logic is currently incorrect as we look for just `Contract.sol/Contract.json`
=> fix: unchecked getCode

crates/debugger/src/tui/draw.rs
Either our PC-IC map or the source map is wrong, in either case it should not panic.
Fixes https://github.com/foundry-rs/foundry/issues/7801
=> fix(debugger): don't panic on pc-ic / sourcemap mismatch

crates/cast/bin/cmd/access_list.rs, crates/cast/bin/cmd/call.rs, crates/cast/bin/cmd/estimate.rs, crates/cast/bin/cmd/mktx.rs, crates/cast/bin/cmd/send.rs, crates/cast/bin/tx.rs, crates/cli/src/utils/abi.rs
Refactor `build_tx` used in cast send and cast mktx
ref #7965
closes https://github.com/foundry-rs/foundry/issues/7959
Implement `CastTxBuilder` as a replacement for `build_tx`.
It is implemented as a stateful builder because we require `tx_kind` to be known before resolving calldata.
=> refactor: clean-up cast send

crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/invariant/replay.rs, crates/evm/evm/src/executors/invariant/result.rs, crates/evm/evm/src/executors/mod.rs
Closes #7308 
- fail test case instead panic if 
- No input generated to call fuzzed target
- Could not make raw evm call
- unwrap changeset and remove misleading comment: `state_changeset` is Some also when call is committed (`call_raw_committing` -> `call_raw_with_env` -> `convert_executed_result` which sets `state_changeset: Some(state_changeset)`)
- remove duped `expect("invariant should have no inputs")` as we already ensure no input when  `invariant_fuzz`
https://github.com/foundry-rs/foundry/blob/83e6aec038760a58dbab1acd992ed5ce18b9d90b/crates/evm/evm/src/executors/invariant/mod.rs#L138-L146
=> fix(invariant) - do not panic when evm call fails

foundryup/foundryup
I needed to build foundry from an active PR. The build failed repeatedly on my machine due to overruns on system resources.
(Process expanded to eat all ram, eventual build failures or system crashes. Ubuntu 22, 16GB ram, for what it's worth). 
I added a `--jobs` flag to foundryup, which is passed to the `cargo build` command. This is effectively a throttle on the build process. My local build worked fine after specifying `-j 2`. With no flag, foundryup uses `nproc` to recover the prior default behaviour of using all available CPUs.
Also, I clarified the `usage` string to indicate commands that build from source vs installing via compiled binaries.
=> feat(foundryup): add a `--jobs` flag while building from source

crates/common/src/contracts.rs
ref #8014
Since #7937 `ContractData` stored entire `CompactBytecode` instead of just bytecode bytes. `CompactBytecode` includes source maps and thus results in increased memory usage to store those in `known_contracts` when running tests.
Introduce separate `BytecodeData` struct which does not keep source maps as we don't need them for bytecode identification.
cc @grandizzy
=> perf: exclude source maps from `ContractData`

crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/fees.rs, crates/anvil/tests/it/transaction.rs
Removing the constant and instead calculating the capacity in eth api.
I'm not yet sure of the realisation, so needs review. For now I'm just getting the lowest value from the cache history, since in itself it should already be filtered by percentiles.
=> feat: Priority fee suggestion

crates/cast/bin/cmd/run.rs, crates/cli/src/utils/cmd.rs, crates/script/src/broadcast.rs, crates/script/src/lib.rs, crates/script/src/progress.rs, crates/script/src/receipts.rs
Closes https://github.com/foundry-rs/foundry/issues/8017
Adds `ScriptProgress` managing multiple `SequenceProgress` instances drawing progress bars for sequences. 
Current structure should allow managing progress bars for concurrently sent sequences which is something I want to bring back at some point as https://github.com/foundry-rs/foundry/pull/6271 was a bit of an overkill imo (we can still deploy in parallel if no chain ids overlap)
https://github.com/foundry-rs/foundry/assets/62447812/900905cb-1e16-4f76-a003-f643578d0da0
=> feat: better run feedback for scripts

crates/script/src/receipts.rs
Currently script transactions are never considered dropped because by default alloy's `PendingTransactionBuilder` does not contain a timeout.
Add 120s timeout for pending transactions
=> fix: use timeouts for script transactions

crates/evm/core/src/backend/mod.rs, crates/forge/bin/cmd/coverage.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/src/result.rs, crates/forge/src/runner.rs, crates/forge/tests/it/core.rs, crates/forge/tests/it/fuzz.rs, crates/forge/tests/it/repros.rs, crates/linking/src/lib.rs, crates/script/src/build.rs
Closes https://github.com/foundry-rs/foundry/issues/1161 
Closes https://github.com/foundry-rs/foundry/issues/6120
Closes https://github.com/foundry-rs/foundry/issues/8014
Keeping #4049 open as this still won't work in scripts.
Instead of linking each contract separately and keeping separate `libs_to_deploy` for each test contract we now link entire project output and keep single `libs_to_deploy` and `known_contracts`. That way, we reduce memory usage and by deploying all needed libraries unblock usage of `getCode`/`getDeployedCode` with artifacts requiring linking.
To avoid nonce of the `sender` being affected by the number of external libraries used in project, I've inroduced separate `LIBRARY_DEPLOYER` which deploys all libraries, that way, test contract will always have the same …
=> refactor: deploy all libraries when running tests

crates/evm/coverage/src/anchors.rs
The refactor of coverage code (#8025) is casting a shadow over `pc` variable for the first branch and results in invalid branch coverage reports.
Fix branch coverage reports.
Use a different name for the jump `pc` variable to prevent shadowing it for use in the first branch anchor.
=> Fix shadowed branch coverage PC variable

crates/evm/fuzz/src/strategies/state.rs
Fuzz dict tracks newly collected values and addresses in order to remove them at the end of each invariant run. Since they are already inserted in index sets it can be optimized to record only the indexes of newly added values and swap them by index when run completed.
=> perf(fuzz): store dict values once, track newly inserted indexes

crates/evm/evm/src/executors/invariant/result.rs
`is_success` would get called on all targets even when the result would not be used.
Also invert the condition to make it more readable.
Makes invariant runs ~10% faster on solmate.
=> perf(invariant): only compute success when necessary

crates/anvil/src/eth/backend/mem/mod.rs, crates/evm/core/src/backend/in_memory_db.rs, crates/evm/core/src/backend/mod.rs, crates/evm/core/src/constants.rs, crates/evm/core/src/utils.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/mod.rs
Default code hash is `KECCAK_EMPTY`, and it will get re-computed in `CacheDB::insert_contract` because code is not empty.
Set it as something that is neither `KECCAK_EMPTY` nor zero, so as to not mess up anything (not verified but better safe than sorry).
=> perf: manually set code hash when inserting cheatcodes account

crates/cheatcodes/src/utils.rs
No point since an invalid signature would mean the underlying cryptography is broken, and we would panic anyway.
This signature recovery accounts for 70% of the time spent in `vm.sign`.
=> perf(cheatcodes): don't recover verify signature after signing

crates/cheatcodes/src/evm/fork.rs, crates/forge/tests/it/repros.rs, testdata/default/repros/Issue8004.t.sol
Fixes #8004 
Test contract that manage forks (create / select / roll) should be made persistent, otherwise their state can be lost
- ensure caller is persistent for create, select and roll fork cheatcodes
=> fix(forge): ensure contract managing fork is  persistent

Dockerfile
Fixes https://github.com/foundry-rs/foundry/issues/7925
This is needed to ensure that we have computed the trailing checksum for the index. 
`index.skipHash=true` speeds up index writes by not computing a trailing checksum[^1].
This is a result of having `features.manyFiles` enabled and cargo computing this for fingerprint[^2].
Confirmed on macos-arm64 `ea2eff95b@master`
---
[^1]: see <https://git-scm.com/docs/git-config#Documentation/git-config.txt-featuremanyFiles>
[^2]: see <https://doc.rust-lang.org/nightly/nightly-rustc/cargo/core/compiler/fingerprint/index.html>
=> fix(docker build): update index checksum

.github/scripts/matrices.py
`macos-latest` is now on aarch64.
=> ci: switch macos test runner to use aarch64

.github/workflows/release.yml
(hopefully) fixes https://github.com/foundry-rs/foundry/issues/7936
=> ci: release x86_64 darwin binaries with macos-12 runner

crates/common/src/compile.rs, crates/forge/src/multi_runner.rs, crates/linking/src/lib.rs
Keep the cow in `Linker::link`, leaving it up to the caller to clone it
I think we may still clone anyway because of eager `to_mut().link()`, which could return false
=> perf(link): keep around the cow for a bit longer

crates/evm/fuzz/src/strategies/state.rs
- no need to collect push bytes multiple times for the same contract / address
- collect push bytes only if address is not already in dict
=> perf(invariant): collect push bytes only once

Cargo.lock, Cargo.toml, crates/evm/evm/src/executors/mod.rs, crates/evm/fuzz/Cargo.toml, crates/evm/fuzz/src/inspector.rs, crates/evm/fuzz/src/strategies/param.rs, crates/evm/fuzz/src/strategies/state.rs, crates/forge/tests/cli/test_cmd.rs
Plus some cleanups.
Note that collecting push bytes still accounts for ~40% of total invariant runtime. What about reducing the max analysis? I don't really know how to improve this further @grandizzy
=> perf(fuzz): use ahash for state

crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/mod.rs, crates/anvil/src/eth/fees.rs
introduced in #7984
there's an edge case where this can return 0
closes #8035
this ensures the suggested fee is at least 1e9 as it was previously
=> fix: ensure suggested prio fee is at least 1e9

crates/verify/src/bytecode.rs
Fixes an issue where if multiple ABI files were located in the `out/Contract.sol/**` directory it would fetch the first ABI file or the one where the solidity version matched on the first round without matching the `name` of the ABI file with the contract being verified. 
This would lead to fetching the wrong file from cache. 
For example, if the bytecode being verified is for the `PSMVariant1Actions` contract, the `out/PSMVariant1Actions.sol` tree looks like:
```bash
├── PSMVariant1Actions.sol
│   ├── GemJoinLike.json
│   ├── PSMVariant1Actions.json
│   └── PSMVariant1Like.json
```
It would lead to `GemJoinLike.json` being fetched from cache instead of `PSMVariant1Actions.json`
Strongly check the `name` of the abi file and then the solidity version.
=> fix(verify-bytecode): check contract name in cache

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, crates/cheatcodes/src/fs.rs, crates/evm/traces/src/decoder/mod.rs, testdata/cheats/Vm.sol, testdata/default/cheats/Prompt.t.sol
As explained in #7939, there's no reliable way to currently obfuscate dynamically entering a private key in the terminal. 
This PR adds `promptSecretUint(string calldata)(uint)` to aid, reusing the `prompt_password` helper introduced in https://github.com/foundry-rs/foundry/pull/7012.
I can raise followup PRs on forge-std & book if this gets in.
=> feat(cheatcode): promptSecretUint

crates/evm/core/src/backend/mod.rs
Fixes https://github.com/foundry-rs/foundry/issues/8077
`initialize` function determines contract whis is being called or deployed and sets it as persistent. However, for calculating `CREATE` address it is using `env.tx.nonce.unwrap_or_default())` which is incorrect because we are never setting `env.tx.nonce` in `build_test_env`: https://github.com/foundry-rs/foundry/blob/0248a62892bb958c986b43d2444d318f960ad99b/crates/evm/evm/src/executors/mod.rs#L534
Use correct nonce
=> fix: update persistent accounts handling

crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/eth/backend/executor.rs, crates/anvil/src/eth/backend/mem/mod.rs
Closes https://github.com/foundry-rs/foundry/issues/8073
Similarly to https://github.com/foundry-rs/foundry/pull/7718 implements `Encodable2718` and `Decodable2718` for `TypedReceipt`.
Also improved handling of optimism-specific fields.
Receipt root calculation verified against random optimism blocks.
=> fix(anvil): receipts root calculation

crates/evm/fuzz/src/strategies/state.rs
Regression introduced in https://github.com/foundry-rs/foundry/pull/8043, new fuzz dict values collected are not completely removed at the end of each run. This happens due to keeping indexes of new values and use them to remove values by calling `swap_remove_index`. However, after the indexset is altered the stored indexes to remove are no longer relevant.
The issue was noticed when re running invariant benchmarks (DSChief test case), would be nice to have it as a test but it needs 1000 runs to be replicated and will considerably slow down the CI. Will work on setting up a different project / CI to run daily benchmarks and make sure these regressions are automatically caught.
- ~keep new values (instead their index) and remove them by calling `swap_remove` (alternatively we could still …
=> fix(invariant): prevent new values leaking between runs

crates/script/src/build.rs
Needed to support `deployCode` for Vyper contracts in scripts
=> fix: include Vyper sources when compiling scripts

Cargo.lock, Cargo.toml, crates/common/src/compile.rs, crates/wallets/Cargo.toml, crates/wallets/src/error.rs, crates/wallets/src/raw_wallet.rs, crates/wallets/src/wallet.rs, crates/wallets/src/wallet_signer.rs
Closes: https://github.com/foundry-rs/foundry/issues/8095
With specifying `GCP_PROJECT_ID`, `GCP_LOCATION`, `GCP_KEYRING`, `GCP_KEY_NAME`, `GCP_KEY_VERSION` env variables, you can sign with Google Cloud KMS by enabling `--gcp` flag
=> Support GCP KMS Signer

crates/cast/bin/cmd/interface.rs, crates/cast/src/lib.rs, crates/fmt/src/formatter.rs, crates/fmt/src/helpers.rs, crates/fmt/src/lib.rs, crates/forge/bin/cmd/fmt.rs, crates/forge/bin/cmd/geiger/error.rs, crates/forge/bin/cmd/geiger/find.rs
Also print the raw ABI string regardless if formatting fails
Fixes https://github.com/foundry-rs/foundry/issues/8099
=> chore: propagate fmt parser errors

crates/evm/evm/src/executors/invariant/mod.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantExcludedSenders.t.sol
Closes #4163 
- exclude  `CHEATCODE_ADDRESS`, `HARDHAT_CONSOLE_ADDRESS` and `DEFAULT_CREATE2_DEPLOYER` from senders
=> fix(invariant): exclude default addresses from senders

crates/cast/bin/cmd/wallet/mod.rs, crates/cast/tests/cli/main.rs
Currently `derive-private-key` implements its own wallet init code with hardcoded derivation path. Replacing it with existing `WalletOpts` allows to reduce code duplication and also:
- specify custom derivation path
- use encrypted keystore
- use the same mnemonic flags as in other cast commands improving consistency
The command still supports explicitly specifying mnemonic and index as arguments.
Output format was changed to print private key only, allowing it to be used in shell scripts.
Breaking!! The command was renamed from `derive-private-key` to `private-key` and assigned `pk` alias. The old name is too verbose. The renaming is done in a separate commit, so it can be easily excluded from this PR if maintainers decide so.
=> Support WalletOpts in `cast wallet derive-private-key` command

crates/evm/core/src/backend/mod.rs, crates/evm/evm/src/inspectors/stack.rs, crates/forge/tests/it/repros.rs, testdata/default/repros/Issue8006.t.sol
Closes #8006 accounts state marked as persistent is overwritten in `rollFork(tx)` and `transact` calls
- add `persistent_accounts` arg in `update_state` helper. Update state only if account is not marked as persistent
- `persistent_accounts` is some when called from `commit_transaction` (used by `rollFork` / transact)
- `persistent_accounts` is none when update state from stack
=> fix(forge): preserve state of persisted accounts on rollFork(tx) / transact

crates/forge/Cargo.toml
Since the support for aws was put behind a feature flag the `--aws` flag in forge no longer functions. 
This PR will add a feature to the `forge` crate to fix this.
=> fix(forge): needs a aws-kms feature to allow for continued support of the --aws flag

Cargo.lock, Cargo.toml, crates/common/src/compile.rs, crates/debugger/src/tui/draw.rs, crates/debugger/src/tui/mod.rs, crates/evm/traces/src/identifier/etherscan.rs, crates/forge/bin/cmd/bind.rs, crates/forge/bin/cmd/test/mod.rs, crates/forge/src/multi_runner.rs, crates/forge/tests/cli/build.rs, crates/forge/tests/fixtures/compile_json.stdout, crates/script/src/build.rs, crates/test-utils/src/util.rs, crates/verify/src/etherscan/flatten.rs
Closes https://github.com/foundry-rs/foundry/issues/2704
ref https://github.com/foundry-rs/compilers/pull/140
=> bump compilers

crates/debugger/src/tui/draw.rs
When using the debugger mode (i.e., `forge script XXX --debug`), the source code panel/area does not clear the previous content. It will make the output quite messy.  
For example, when debugging [uniswapv2.zip](https://github.com/user-attachments/files/15797549/uniswapv2.zip) with the command `forge script script/run.sol --debug`.
All the grey text is rendered in the previous tick. A correct one should look as follows.
This commit adds padding to the source code, ensuring all the previous content could be cleared.
=> fix(forge): fix the bug where source code incorrectly overlaps during debugging

Cargo.lock, Cargo.toml, crates/anvil/core/src/eth/transaction/mod.rs, crates/anvil/src/config.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/executor.rs, crates/anvil/src/eth/backend/fork.rs, crates/anvil/src/eth/otterscan/api.rs, crates/anvil/src/tasks/mod.rs, crates/anvil/tests/it/anvil.rs, crates/anvil/tests/it/anvil_api.rs, crates/anvil/tests/it/api.rs, crates/anvil/tests/it/eip4844.rs, crates/anvil/tests/it/fork.rs, crates/anvil/tests/it/gas.rs, crates/anvil/tests/it/traces.rs, crates/anvil/tests/it/transaction.rs, crates/cast/Cargo.toml, crates/cast/bin/cmd/run.rs, crates/cast/bin/main.rs, crates/cast/src/lib.rs, crates/common/Cargo.toml, crates/common/src/fmt/ui.rs, crates/common/src/provider/retry.rs, crates/common/src/transactions.rs, crates/evm/core/src/fork/backend.rs, crates/script/src/receipts.rs, crates/verify/src/bytecode.rs
The latest version is required at https://github.com/foundry-rs/foundry/pull/8098. 
According to the update, fixed some codes based on the following changes on the alloy side.
- https://github.com/alloy-rs/alloy/pull/840
- https://github.com/alloy-rs/alloy/pull/848
=> chore(deps): Bump alloy 14ed25d

crates/config/src/soldeer.rs
The URL in the soldeer config should be optional otherwise it will result in crash. 
Made the URL optional in the `SoldeerDependency`
=> fix: Soldeer: Fixed the url bug, it should be optional

Cargo.lock, crates/common/Cargo.toml, crates/common/src/compile.rs, crates/debugger/src/tui/draw.rs, crates/evm/traces/Cargo.toml, crates/evm/traces/src/identifier/etherscan.rs, crates/forge/bin/cmd/test/mod.rs, crates/script/src/build.rs
Closes https://github.com/foundry-rs/foundry/issues/7060
=> feat: display source name in debugger

crates/config/src/lib.rs
Closes https://github.com/foundry-rs/foundry/issues/7379
Since https://github.com/foundry-rs/compilers/pull/140 we provide enough data to match each cached artifact with build info which produced it, so workaround from https://github.com/foundry-rs/foundry/pull/7358 is not needed anymore
=> fix: enable cache when `--build-info` is enabled

crates/cast/bin/cmd/send.rs, crates/sol-macro-gen/src/sol_macro_gen.rs
1. Invalid deps format in `Cargo.toml` when version is not specified. 
2. Checking unformatted code for consistency can lead to failures even though code might be the same. 
1. Remove extra braces 
2. Format code before checking for consistency
=> fix(forge-bind): alloy deps and file consistency check

crates/anvil/core/src/eth/mod.rs, crates/anvil/src/eth/api.rs, crates/anvil/tests/it/transaction.rs, crates/cast/bin/cmd/send.rs
Closes #8152
I'm not exactly sure about @mattsse reply:
> this includes endpoints:
> * `debug_getRawTransaction`
> * `eth_getRawTransactionByHash`
> * `eth_getRawTransactionByBlockHashAndIndex`
> * `eth_getRawTransactionByBlockNumberAndIndex`
Since, as shown here: https://ethereum.org/en/developers/docs/apis/json-rpc/ and here: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth, non-eth endpoints should not have `eth_` prefix. Maybe move them to `debug_`?
=> feat: debug_getRawTransaction RPC endpoint

crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/invariant/filters.rs, crates/evm/fuzz/src/invariant/mod.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/evm/fuzz/src/strategies/mod.rs, crates/evm/fuzz/src/strategies/state.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantSelectorsWeight.t.sol
Closes #2986 
In addition to [issue explanation](https://github.com/foundry-rs/foundry/issues/2986#issue-1353388549) we're using `proptest::sample::Selector` strategy which according to docs `Initially, the selection is roughly uniform, with a very slight bias towards items earlier in the iterator.`
Note: test is a little bit flaky in CI (locally it gives the same results for same seed constantly) might consider to ignore if failures start to pop up
Test with 3 handlers / 10 selectors (per handler: 1 selector, 5 selectors and 4 selectors), 1 run and depth of 500, result of hits / selector:
| | s1 | s2 | s3 | s4 | s5 | s6 | s7 | s8 | s9 | s10 |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | …
=> fix(invariant): weight invariant selectors by number of selectors

crates/cli/src/opts/build/core.rs, crates/forge/bin/cmd/build.rs, crates/forge/tests/cli/cmd.rs
Follow-up for #8149. Allows `forge build <dir>` invocations
=> fix: make `paths` a positional argument

crates/evm/evm/src/executors/invariant/error.rs, crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/invariant/mod.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/evm/fuzz/src/strategies/state.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantShrinkWithAssert.t.sol
Move some methods to a TargetedContracts new-type to be able to borrow from it nicely
To avoid collecting `fuzzed_functions` I re-added proptest `Selector` in `invariant_strat`, should still be OK, PTAL @grandizzy
=> perf: new-type TargetedContracts

Cargo.lock, crates/cast/bin/main.rs, crates/cast/bin/opts.rs, crates/cast/src/lib.rs, crates/common/src/compile.rs, crates/forge/bin/cmd/flatten.rs
Closes https://github.com/foundry-rs/foundry/issues/7352
Implements small refactor in https://github.com/foundry-rs/compilers/pull/143 to avoid duplicating compilation logic.
Also extracts part of `ProjectCompiler` into `with_compilation_reporter` to allow displaying progress even if compilation is invoked by another entity (e.g. `Flattener`).
=> feat: cast etherscan-source --flatten

crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/fuzz/src/invariant/mod.rs, crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/target/ExcludeSelectors.t.sol
Closes #4352 
After merged will follow up with forge-std and foundry book PRs
- add `excludeSelectors` function, collect excluded selectors in `TargetedContract.excluded_functions`
- check if function is not in `exclude_functions` when returning abi functions to fuzz
=> feat(invariant): add excludeSelectors() filter

crates/cheatcodes/src/inspector.rs, testdata/default/cheats/MockCall.t.sol
Fixes #8066 
Use `call.bytecode_address`. This handles both static and delegate calls. Whereas `call.target_address` will not handle delegate call as it is the address the call is being sent to i.e the `to` address, and not the address whose bytecode is being executed.
=> fix(cheatcodes): use `call.bytecode_address` in mockCalls

crates/evm/evm/src/executors/invariant/replay.rs, crates/evm/traces/src/decoder/mod.rs, crates/evm/traces/src/identifier/local.rs, crates/evm/traces/src/lib.rs, crates/forge/src/runner.rs
There's no need to go through the entire `CallTraceDecoder` machinery (and its instatiation, which is expensive) when all we care about are contract names and ABI
=> perf: optimize load_contracts

crates/forge/tests/it/invariant.rs, testdata/default/fuzz/invariant/common/InvariantSelectorsWeight.t.sol
- `test_invariant` is a catch-all for invariant tests, however some tests require their own configuration (specific seed / runs / depth) so they could fail when executing this way. Since tests are performed twice (once by `test_invariant` and once by their own execution)  there are situations when a failure is persisted on 1st run and then 2nd run fails with unexpected message when replayed,
- remove `test_invariant` catch all test and add individual tests (should also speed up tests as they'll be executed only once)
- cleanup runners test setup, remove individual failure persist dirs
- changed invariant selectors weight to assert exact hits of selector
=> chore: fix flaky invariant tests

crates/verify/src/bytecode.rs
Ref #8012 
We currently use `.starts_with` to match local bytecode with onchain bytecode. This is not ideal as it will return true if the prefix needle matches. 
Use strong equality. 
@mattsse @mds1 ptal. This was an oversight on my end, and it is a breaking change. As users could've made the mistake of assuming that their bytecode checks out even though it didn't.
=> fix(verify-bytecode): use strong equality `==`,  not `.starts_with`

crates/cheatcodes/src/evm.rs, crates/cheatcodes/src/evm/mapping.rs, crates/cheatcodes/src/evm/mock.rs, crates/cheatcodes/src/inspector.rs
Outlining (and marking as `cold`) the `Inspector::step` cold paths in the cheatcodes inspector (so gas metering, mapping etc) makes the function trivial to inline as it becomes just a few checks, as well as way more cache-friendly as it won't have to jump around thousands of bytes on the common case where all or most of the conditions are false.
Overall this makes forge 5% to 20% faster depending on the workload
=> perf(cheatcodes): outline cold paths in inspector step

crates/cheatcodes/assets/cheatcodes.json, crates/cheatcodes/spec/src/vm.rs, testdata/default/cheats/RandomUint.t.sol
Addresses https://github.com/foundry-rs/foundry/pull/7960#discussion_r1619015391 and https://github.com/foundry-rs/foundry/pull/7960#discussion_r1618868613
I just edited the docstring in both `cheatcodes.json` and `vm.rs` manually, but I think one of them is supposed to be autogenerated somehow?
=> chore: fix docstring and add tests for random cheats

crates/forge/src/runner.rs
Labels are missing when replay an invariant failure, including it on the spot for now but going to follow up with a bigger PR to refactor `TestResult` creation as part of  `TestResult` struct
(CI failure unrelated)
=> fix(invariant): show labels when failure replay

Cargo.lock, Cargo.toml
Bumps Alloy to latest version
- remove `anvil` patch
- update to `0.1.2`
- ran `cargo update`
Compatibility with `revm-inspectors` should be fine given that it is marked as `0.1.*`: https://github.com/paradigmxyz/revm-inspectors/blob/4fe17f08797450d9d5df315e724d14c9f3749b3f/Cargo.toml#L26
=> chore(deps): bump alloy to `0.1.2`, remove patch

crates/anvil/core/src/eth/transaction/optimism.rs, crates/anvil/src/eth/api.rs, crates/anvil/src/eth/backend/mem/inspector.rs, crates/evm/evm/src/inspectors/stack.rs
mark `Some(inspector) {}` blocks as cold to optimize the dispatching
Similar to https://github.com/foundry-rs/foundry/pull/8197. The `inline(always)` makes the closure just give the `cold` hint for the dispatching, and we want it inlined to avoid a call indirection when we do actually hit the inspector (eg cheatcodes is almost always enabled)
any instruction saved in step and step_end goes a long way since they're as hot as the interpreter itself
=> perf: optimize inspector stack dispatching

crates/forge/src/result.rs, crates/forge/src/runner.rs
Creation of `TestResult` is handled in multiple places, PR is meant to consolidate that in `TestResult` struct and remove duped code from test runner
=> chore: consolidate TestResult logic

crates/anvil/server/src/config.rs, crates/anvil/server/src/lib.rs
Add a `--no-request-size-limit` option to anvil cli to optionally disable RPC body request size limits
When using the [anvil_loadState](https://book.getfoundry.sh/reference/anvil/#custom-methods) RPC methods on localhost to re-hydrate state for local testing, if that hex string is >2mb then the request fails with:
```
2024-06-20T05:23:32.699724Z  WARN request{method=POST uri=/ version=HTTP/1.1}: rpc: invalid request err=BytesRejection(FailedToBufferBody(LengthLimitError(LengthLimitError(Error { inner: LengthLimitError }))))
```
See [axum::extract::DefaultBodyLimit](https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html) for details on the 2mb default limit [and how to disable](https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html#method.disable)
Add a cli …
=> feat: add --no-request-size-limit option to anvil

crates/common/src/contracts.rs
ref https://github.com/foundry-rs/foundry/issues/6875#issueacomment-2180523566
Update `find_by_{deployed,creation}_code` to not exit after first diff_score < 0.1, but instead try matching until the minimal diff score is found.
cc @grandizzy this fixes the issue for https://github.com/grandizzy/forge-coverage-bug/tree/master though not sure about other repos
=> fix: update bytecode matching for coverage

Cargo.toml, clippy.toml, crates/forge/bin/cmd/fmt.rs
=> chore: enable redundant-lifetimes lint

crates/evm/core/src/opts.rs, crates/evm/evm/src/executors/builder.rs, crates/evm/evm/src/executors/mod.rs
Values higher than `u64::MAX` would panic in `local_evm_env`/`build_test_env`.
=> chore(evm): use u64 for gas limit

crates/cli/src/utils/mod.rs, crates/common/src/compile.rs, crates/common/src/traits.rs, crates/evm/coverage/src/analysis.rs, crates/forge/src/gas_report.rs, crates/forge/src/multi_runner.rs, crates/forge/src/runner.rs
Introduce `TestFunctionKind` enum to be able to match on the kind / test multiple kinds at once, instead of having long `if` / `||` / `&&` chains on methods.
Clarify what a test is by renaming functions to be specific of what kind they're targetting (unit, fuzz, invariant). Previously `is_test` or `is_test_fail` also included fuzz tests, but not invariant tests, and `is_fuzz_test` only worked in combination with `is_test`.
Only functional changes are for tracing spans, and expanding some "is this contract a ds-test / forge-std / known test contract" checks to include previously-ignored invariants or new config functions.
=> feat: improve test function classification

crates/anvil/src/eth/sign.rs
closes #8241
fixes api misuse when creating the signed tx which incorrectly used the sig hash as the tx hash
=> fix: use tx.into_signed directly

crates/cheatcodes/src/utils.rs, testdata/default/cheats/RandomUint.t.sol
Don't overflow `max - min` by rejecting `max > min`. CC @yash-atreya @mds1
=> fix: overflow in randomUint

crates/anvil/src/eth/backend/mem/mod.rs
closes #8242
fixes an edge cases where the logs for the block we forked off are not fetched from remote.
we need to fetch them if the from is before or the fork block
=> fix: use inclusive check for logs range fetch in fork

crates/evm/evm/src/executors/invariant/mod.rs, crates/evm/evm/src/executors/invariant/result.rs
- atm after invariant is asserted and if it failed, we only exit current run (by breaking current run depth loop) but we don't interrupt the whole test. This results in unnecessary runs performed after invariant failed (e.g. if we have 1000 runs configured and run 500 breaks the invariant, there will still be 1000 runs performed)
- exit invariant test and do not perform remaining runs if test cannot continue
=> fix(invariant): do not continue test runs if invariant fails
