foundry-rs/foundry

crates/evm/evm/src/executors/invariant/error.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/forge/tests/cli/test_cmd.rs

- invariant test does not exit if failed in initial state but perform test runs
- check if there is any failure right after initial check and return Err with revert reason
- cleanup
- remove unused `broken_invariants_count` (there could be only one broken invariant per test)
- correct `InvariantTest.has_errors` check: `is_some` instead of `is_none`

fix(invariant): exit early if invariant fails in initial state

---

crates/cheatcodes/src/config.rs
crates/cheatcodes/src/test/assert.rs
crates/config/src/lib.rs
crates/forge/tests/cli/config.rs

Updating code for 100+ impls would've been painful, so decided to clean this up with a macro
`legacy_assertions` doesn't print any info about failure at the moment, just returns successful result
To print logs we'd need #8181 to push them to `LogCollector`. We could've collected a separate logs list on `Cheatcodes`, but it's unclear how to ensure correct ordering

refactor: reduce code duplication for assertion cheats and introduce `legacy_assertions` flag

---

crates/forge/bin/cmd/coverage.rs

Fixes https://github.com/foundry-rs/foundry/issues/3900

feat(coverage): exit early if tests failed

---

crates/evm/evm/src/executors/fuzz/mod.rs

This information is already present in surrounding spans

chore: remove an unnecessary debug log

---

crates/evm/evm/src/inspectors/stack.rs

After #8181 cheatcodes are called separately in `InspectorStack::call` and currently depth for its invocation is not adjusted while in isolation, resulting in failing test-isolate CI job https://github.com/foundry-rs/foundry/actions/runs/9688379922
Adjust depth separately for `Cheatcodes` call

fix: correctly adjust depth when calling cheatcodes with `--isolate`

---

crates/test-utils/src/util.rs

Logs with -vvvvv are not helpful, and github is having hard time loading them in UI

chore: reduce verbosity for ext tests

---

.github/scripts/prune-prereleases.js

Fixes https://github.com/foundry-rs/foundry/issues/8000
I want to use nightly releases in a CI pipeline, but they currently get pruned, which forces me to wait for the next month before upgrading my tooling with new features. 
This is just a hacky solution where we keep 30 nightlies around instead of just 3.
The better implementation would actually only keep all the nightlies of the current month, which is prob not that hard to implement actually, but want to see what you guys think before putting effort into this.

Update prune-prereleases.js to keep 30 nightlies around

---

.github/workflows/nextest.yml
crates/forge/tests/cli/ext_integration.rs

Required for https://github.com/foundry-rs/foundry/pull/8274

test: update snekmate rev

---

crates/config/README.md
crates/config/src/lib.rs
crates/config/src/utils.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/tests/cli/ext_integration.rs

Makes it easier to catch infinite loops
Closes https://github.com/foundry-rs/foundry/issues/3629

feat: reduce default gas limit to ~1B

---

crates/forge/tests/fixtures/can_test_repeatedly.stdout
crates/forge/tests/fixtures/include_custom_types_in_traces.stdout
crates/forge/tests/fixtures/repro_6531.stdout

chore: update fixtures after forge-std release

---

crates/forge/bin/cmd/flatten.rs

closes #8312
invoke solc quietly

fix: suppress compile reporting for forge flatten

---

crates/config/src/lib.rs

`vyper --version` is pretty slow, avoid calling it when vyper compiler won't be needed

perf: only instantiate Vyper when necessary

---

flake.lock
flake.nix

Updated to latest Rust toolchain version (v1.79). The rust overlay doesn't use `flake-utils` anymore. Switched to solc 0.8.23 since that's the default for the tests. Moved around the deps to be more in line with recommendations (`buildInputs` for things that get linked and `nativeBuildInputs` for what's needed during compilation only, `packages` for things that are not needed at compile time). `libusb` shouldn't be needed in the `buildInputs` since it's already included via the definition of the `LD_LIBRARY_PATH` environment variable.
Project doesn't compile with the rust toolchain version from the lockfile.
Updated the lockfile and cleaned up the flake.

chore: update dev shell flake

---

crates/anvil/src/eth/backend/mem/mod.rs

block productions needs a db write lock which competes with regular requests eth_call/eth_estimate etc...
this now computes the header.timestamp after we acquired the db lock and right before execution.

fix: set next block timestamp as late as possible

---

Cargo.toml
crates/cli/src/handler.rs

line-tables-only
```
debug=                   strip=            `stat -c%s`  backtrace effect
debug=0                  strip=true         67,790,640  no backtraces
debug="line-tables-only" strip=true         67,742,176  no backtraces (somehow smaller?)
debug=0                  strip="debuginfo"  85,458,608  backtraces, no file/line (except for the exact panic location)
debug="line-tables-only" strip="debuginfo"  85,539,392  backtraces, no file/line (except for the exact panic location)
debug=0                  strip=false        97,679,800  backtraces, no file/line (except for the exact panic location)
debug="line-tables-only" strip=false       391,022,576  full backtraces
```
Looks like "line-tables-only" does nothing if stripping at least on linux. Keeping anyway since it might work …

chore: tweak profiles once more

---

crates/anvil/src/eth/miner.rs

if we forked off a tx hash, we don't want to mine a new block immediately and instead only inject the txs when the miner returns its first batch

fix: only force include txs on first ready poll

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/logging.rs

Closes https://github.com/foundry-rs/foundry/issues/7681
Thisadds an option to disable `LogCollector` via `--disable-console-log` flag. Also sets `target` for traces captured by `LogCollector` to `node::console` to allow easier filtering of such logs through `RUST_LOG`

feat(anvil): more flexible configuration `LogCollector`

---

crates/script/src/receipts.rs

increases the timeout we wait for a tx to be mined, 
testnets have highly fluctuating prices so this function is problematic on testnets
in a next step we should check if the tx still exists and start over

chore: increase tx timeout

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/soldeer.rs

Upgrading to soldeer 0.2.17
In this release, fixed 2 bugs reported by our users and added a flag to skip warnings if soldeer is used in a CI env.
More info 
https://github.com/mario-eth/soldeer/releases/tag/v0.2.17
<!--
Explain the context and why you're making that change. What is the problem
you're trying to solve? In some cases there is not a problem and this can be
thought of as being the motivation for your change.

Soldeer release v0.2.17

---

crates/config/src/lib.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/replay_last_run_failures.stdout

Closes #4000 
- add new option `--run-failures` in filter args to run only test failures from last run
- persist filter with failures of last run in file (if any), defaults to `cache/test-failures` file. File path can be configured in toml `test_failures_file = path/to/file` and is removed on `forge clean` 
- cleanup: move `--show-progress` in test args

feat(forge): option to replay last test run failures only

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs

closes #8322
personal_sign has different args order
https://docs.metamask.io/wallet/reference/personal_sign/

fix: order of personal sign

---

crates/cheatcodes/src/utils.rs
testdata/default/cheats/RandomUint.t.sol

`randomUint(0, -1)` panics with division by zero due to overflow in `rand() % (-1 - 0 + 1)`

fix(cheatcodes): overflow in randomNumber w/range

---

crates/forge/tests/cli/cmd.rs
crates/test-utils/src/util.rs

this test is flaky due to some nginx proxy issues:
https://github.com/foundry-rs/foundry/actions/runs/9807607407/job/27081719593?pr=8367
we can skip if we see 502 in stdout

test: ignore 502 in can_clone_keep_directory_structure

---

crates/cast/bin/tx.rs

optimistically closes #7764
according to the eth api spec the tx input field is named "input", however it used to be "data", now this is a bit of a mess where you don't know if a client supports input or only data.
so we simply send both, 
since #7764 didn't surface any serialization issues, we can assume unknown request values are simply ignored. so this change should not have any downsides (besides including the data twice -.-)

fix: set both tx input fields

---

crates/evm/core/src/lib.rs
crates/evm/core/src/precompiles.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/traces/src/decoder/mod.rs
crates/evm/traces/src/decoder/precompiles.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/invariant.rs
testdata/default/fuzz/invariant/common/InvariantShrinkWithAssert.t.sol

Closes #4287 
Closes #7530 
- extract precompiles addresses into own module
- extend list of excluded senders with precompiles (#4287)
- add labels to display along traces when precompile is not decoded (#7530) + test

feat(invariant): exclude precompiles from senders

---

crates/anvil/README.md

Fix install command in anvil readme
Current command from readme gives this error
```
error: multiple packages with binaries found: anvil, cast, chisel, forge. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/foundry-rs/foundry anvil`.
```
adding `anvil` to the command enables correct install

chore(anvil): fix install cmd in README

---

crates/config/src/fuzz.rs
crates/evm/evm/src/executors/fuzz/mod.rs
crates/evm/evm/src/executors/fuzz/types.rs
crates/evm/fuzz/src/lib.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/test_helpers.rs

As discussed in  #3844 , when using fuzz test, console.log doesn't work as expected(display console log info). This PR added a new fuzz config `show_execution_logs`, with which user could decide if the full console log should be displayed. by defaut, the value is `false`, so it won't affect any fuzz test prior to this change will be made.
A `logs` field is added to `CaseOutcome` to keep track of logs that generated in a single fuzz test. And collect logs in `FuzzTestData` after each fuzz test finished. then use the config `show_logs` in `FuzzConfig` to decide if full console log output should be displayed. if not, the `console.log` behavior is the same as what it is now.
Also, you can use `/// forge-config: default.fuzz.show-logs = true` to enable fuzz test console log per test.
4 test …

fuzz console log & test cases

---

crates/forge/src/result.rs
crates/forge/tests/it/config.rs
crates/forge/tests/it/fuzz.rs
crates/forge/tests/it/repros.rs

Logs collected during tests are decoded twice:
- in `TestResult` functions (regardless verbosity) e.g.
https://github.com/foundry-rs/foundry/blob/2ba3400c76f3a6e9b9a5d5595ac2ebd38b4bce58/crates/forge/src/result.rs#L441
https://github.com/foundry-rs/foundry/blob/2ba3400c76f3a6e9b9a5d5595ac2ebd38b4bce58/crates/forge/src/result.rs#L453
- when test results displayed, if `verbosity >= 2`
https://github.com/foundry-rs/foundry/blob/2ba3400c76f3a6e9b9a5d5595ac2ebd38b4bce58/crates/forge/bin/cmd/test/mod.rs#L454-L465
Avoid unnecessary logs decoding in `TestResult` struct

chore: decode test logs only once and if needed

---

Cargo.lock
crates/anvil/src/eth/otterscan/api.rs
crates/anvil/tests/it/otterscan.rs
crates/forge/tests/it/repros.rs
deny.toml

Locking 45 packages to latest compatible versions
Updating alloy-consensus v0.1.3 -> v0.1.4
Updating alloy-contract v0.1.3 -> v0.1.4
Updating alloy-dyn-abi v0.7.6 -> v0.7.7
Updating alloy-eips v0.1.3 -> v0.1.4
Updating alloy-genesis v0.1.3 -> v0.1.4
Updating alloy-json-abi v0.7.6 -> v0.7.7
Updating alloy-json-rpc v0.1.3 -> v0.1.4
Updating alloy-network v0.1.3 -> v0.1.4
Updating alloy-primitives v0.7.6 -> v0.7.7
Updating alloy-provider v0.1.3 -> v0.1.4
Updating alloy-pubsub v0.1.3 -> v0.1.4
Updating alloy-rpc-client v0.1.3 -> v0.1.4
Updating alloy-rpc-types v0.1.3 -> v0.1.4
Updating alloy-rpc-types-anvil v0.1.3 -> v0.1.4
Updating alloy-rpc-types-engine v0.1.3 -> v0.1.4
Updating alloy-rpc-types-eth v0.1.3 -> v0.1.4
Updating alloy-rpc-types-trace v0.1.3 -> v0.1.4
Updating …

chore(deps): cargo update

---

Cargo.lock
crates/forge/Cargo.toml
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/snapshot.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/cmd/watch.rs
deny.toml

Supersedes https://github.com/foundry-rs/foundry/pull/6446
~~I don't know how to handle the update args case for `forge test`, otherwise it probably works (untested)~~
Mostly copied from watchexec's own CLI, simplified because less options

chore(deps): bump watchexec to 4

---

crates/common/src/retry.rs
crates/script/src/sequence.rs
crates/verify/src/etherscan/mod.rs

The `ProxyAdmin` contract from OpenZeppelin cannot be verified for some reason and this also prevents verification of other contracts (process just terminates with exit code 1). 
https://github.com/foundry-rs/foundry/issues/6023#issuecomment-2212541094
Instead of terminating process a new method `run_async_until_break` has been introduced, which allows to continue retrying or instantly exit with an error. Also added counter of successfully verified smart contracts.
Deploying contracts on testnet:
- before: [deploy logs 1](https://gist.github.com/StackOverflowExcept1on/deb09c438afb820c8ab7169b17f12e81)
`Program` contract is not verified because the process terminates on ProxyAdmin verification (2 / 4)
- after: [deploy logs 2](https://gist.github.com/StackOverflowExcept1on/e1baebcbf1a2043754 …

fix(verify-etherscan): continue verification even if errors occur

---

crates/cast/bin/tx.rs

Closes https://github.com/foundry-rs/foundry/issues/8418
we didn't respect `chain.is_legacy()` when setting `maxFeePerGas`

fix(cast): correctly handle legacy chains

---

crates/evm/traces/src/decoder/mod.rs

When a function was not known, the revert data was never decoded. Make sure we always decode revert data.
Closes https://github.com/foundry-rs/foundry/issues/7265

fix(evm): always decode EVM reverts

---

crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs
crates/test-utils/src/lib.rs

The line hit is reported doubled in lcov report. That can be repro with a contract 
```Solidity
contract AContract {
int256 public i;
function foo() public {
i = 1;
}
}
```
and test
```Solidity
contract AContractTest is Test {
function testFoo() public {
AContract a = new AContract();
a.foo();
}
}
```
running
`forge coverage --report lcov && genhtml lcov.info -o report  && firefox report/index.html` will generate report below
That happens because the generated lcov report contains `DA:8,1` line 2 times (`DA: line number, hit count`)
- avoid adding line hit count twice (as a line and also as a statement)

fix(coverage): lcov avoid double reporting for line hit

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/anchors.rs
crates/evm/coverage/src/lib.rs
crates/forge/tests/cli/coverage.rs

Closes #4310 
Closes #4315 
Closes #4309 
Closed #7784 
- fix first branch instruction  (comment `The first branch is the opcode directly after JUMPI` but was + 2)
- handle false body, add coverage item with proper source code location if exists, otherwise use same branch 0, in order to have consistent display when false body missing
and if both bodies
- code cleanup
- added tests for gh reports

fix(coverage): proper branch handling for if statement

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/genesis.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/fork.rs
crates/evm/core/src/backend/error.rs

Closes https://github.com/foundry-rs/foundry/issues/4173
Caching genesis accounts state is not really correct because we might reset fork to a forked block where account nonce is lower than the one we cached and inserted during reset. This would cause `eth_getTransactionCount` to return nonce lower than the one actually stored in the db
This PR removes caching of genesis accounts state, which makes `anvil_reset` a bit slower
Another approach could be to instead serve overriden data over `getTransactionCound`/`getBalance` etc, but I don't think that it's great to mess with the actual forked state

fix: correctly apply genesis

---

crates/anvil/src/eth/fees.rs
crates/anvil/src/lib.rs
crates/anvil/tests/it/gas.rs

Closes https://github.com/foundry-rs/foundry/issues/3762
When creating fee history record, we are using `FeeManager` to obtain gas fees which already contains updated gas prices for next block. Because of that, base fee value for block X is always representing the actual base fee of block X+1.
Use data from block header when creating records, and don't rely on `FeeManager` at all.
#3762 had further discussion not related to this specific issue, not sure if we want to track it separately

fix(anvil): return correct values for `eth_feeHistory`

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Closes #4311 
`NodeType::FunctionCall` can have different kinds (`functionCall`, `typeConversion`, `structConstructorCall`, others?)
- check function call kind and add coverage only if `functionCall` kind

fix(coverage): add coverage only for function call kind

---

crates/cheatcodes/src/evm.rs

fixes https://github.com/foundry-rs/foundry/issues/8426. Use `BTreeMap` to enforce ordering

fix: vm dumpState consistent ordering 

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/test/expect.rs
crates/forge/tests/it/repros.rs
testdata/cheats/Vm.sol
testdata/default/repros/Issue7457.t.sol

closes #7457, closes #7545
--
*From #7545*:
> Add support for a new cheatcode: vm.expectEmitAnonymous(bool checkTopic0, bool checkTopic1, bool checkTopic2, bool checkTopic3, bool checkData) (and corresponding equivalent overloads).
> The rationale is that vm.expectEmit always checks topic0, which is the event signature, and checking everything else is optional. But with an anonymous event, you don't have an event signature, so it doesn't make sense to still force the user to check topic0.
This PR introduces the `vm.expectEmitAnonymous` cheatcode and corresponding overloads. Additionally, it disallows matching anonymous events with no indexed topics via `vm.expectEmit`. If the anonymous has at least one indexed event, it's impossible to differentiate from a non-anonymous event. 
The …

feat(cheatcodes): add event expecter which supports anonymous events

---

Cargo.lock
Cargo.toml
crates/config/src/soldeer.rs
crates/forge/bin/cmd/soldeer.rs
crates/forge/tests/cli/soldeer.rs

We added new functionality to Soldeer, using a git repo as a dependency.
https://github.com/mario-eth/soldeer/issues/48
This feature has been requested even tho I do not encourage abusing it but it can be used for various unpublished repos.
Now we can use git to pull dependencies. It supports github and gitlab
Example:
```bash
forge soldeer install test-project~v1 git@github.com:test/test.git
forge soldeer install test-project~v1 git@gitlab.com:test/test.git
```
```bash
forge soldeer install test-project~v1 https://github.com/test/test.git
forge soldeer install test-project~v1 https://gitlab.com/test/test.git
```
Or using custom commit hashes
```bash
forge soldeer install test-project~v1 git@github.com:test/test.git 345e611cd84bfb4e62c583fa1886c1928bc1a464
```

Updated the soldeer version to 0.2.18 and added extra CLI tests

---

crates/verify/src/bytecode.rs

Fixes #8255 
Printing wrong `verification_type` in json result. 
WIP 
Print the correct verification_type from the result. 
This is only a partial fix though, since the runtime doesn't even match partially with the onchain runtime code. Though it was supposed to in the case of https://github.com/foundry-rs/foundry/issues/8255#issuecomment-2218930365.
Upon investigating, I observed that; the runtime code that we generate locally by forking has trailing zeros and the onchain runtime code  doesn't
Onchain runtime code:
```
0x60806040523480156200001157600080fd5b5060043610620000875760003560e01c8063c4d66de81162000062578063c4d66de81462000135578063ce5ac90f146200014e578063e78cea921462000165578063ee9a31a2146200018657600080fd5b806354fd4d50146200008c578063896f93d114620000e15780638cf0629c146200011e575b …
```

fix(verify-bytecode): use local creation code for fork deployment

---

crates/evm/evm/src/executors/invariant/result.rs
crates/forge/tests/it/invariant.rs
testdata/default/fuzz/invariant/common/InvariantSequenceNoReverts.t.sol

When running invariants with `fail_on_revert = false` (default) the counterexample is created with all calls (including reverts). In this case the reverts are not relevant for reproducing the failure but will be considered and tested in shrinking phase, which is not efficient. 
- remove call from inputs if call reverted and `fail_on_revert = false`
- test

perf(invariant): do not include reverts in counterexample

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/backend/db.rs
crates/anvil/src/eth/backend/mem/fork_db.rs
crates/anvil/src/eth/backend/mem/in_memory_db.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs

Fixes #8213 
Closes:  https://github.com/foundry-rs/foundry/issues/7955
This PR adds the mined transactions that are already part of the memory storage to the file produced by `--dump-state` and loaded by `--load-state`.
If transactions are not persisted and loaded, queries for full blocks fail.

feat(anvil): add mined transactions to state dump

---

crates/evm/core/src/backend/mod.rs
crates/evm/core/src/fork/multi.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue8168.t.sol

Closes #8168 
Fork's block number and timestamp can be changed using `vm.warp` and `vm.roll` but they're not preserved in a multifork setup when a different fork is selected.
- save current env block number and ts in active fork env

fix(fork): preserve block number and timestamp when changing fork

---

Cargo.lock
Cargo.toml
crates/anvil/src/hardfork.rs
crates/common/src/compile.rs
crates/config/src/lib.rs
crates/debugger/src/op.rs
crates/debugger/src/tui/context.rs
crates/debugger/src/tui/draw.rs
crates/evm/traces/src/lib.rs
crates/forge/bin/cmd/coverage.rs
crates/forge/tests/cli/config.rs
crates/test-utils/src/util.rs
crates/verify/src/etherscan/standard_json.rs

Forwards `eofVersion` key from compilers to foundry.toml, allowing native usage of https://github.com/ipsilon/solidity for compiling EOF contracts
Adds `Prague` and `PragueEOF` variants for anvil's `Hardfork` allowing to run EOF-enabled Anvil
Adds debugger support for EOF opcodes

feat: better EOF/Prague support

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/error.rs
crates/anvil/src/eth/fees.rs
crates/anvil/tests/it/eip7702.rs
crates/anvil/tests/it/main.rs

Builds on top of https://github.com/foundry-rs/foundry/pull/8471

feat: support for EIP-7702 in Anvil

---

crates/cast/bin/cmd/mktx.rs
crates/cast/bin/cmd/send.rs

After learning about `mktx` (see https://github.com/foundry-rs/foundry/pull/8472 😅) I wanted to use it to create a blob tx, but received this error:
```
error: unexpected argument '--path' found
```
Or this error w/o `--path`:
```
Error:
server returned an error response: error code -32003: blob transaction missing blob hashes
```
I replicated the same missing logic from `send` in `mktx`.  I also fixed the `--path` help showing up under `Wallet options` on both commands.  I also considered moving `path` into `TransactionOpts` but that's used in enough other spots I assumed there was a good reason it wasn't there already.
Anyways, it works now:
```
> cargo run --bin cast -- mktx --private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d …
```

fix(cast): mktx: add missing --path argument for blob txs

---

crates/cheatcodes/src/inspector.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue8383.t.sol

Closes #8383 
- when ending execution frame, reset interpreter gas to the value of gas spent during frame

fix(cheatcodes): reset interpreter gas to the value of gas spent

---

crates/cast/bin/cmd/call.rs

closes https://github.com/foundry-rs/foundry/issues/6937
call --trace executes an eth_call locally, usually for eth_call the gas limit is way higher and  checks are disabled.
this makes the example pass
Transaction successfully executed.
Gas used: 38683717

fix: disable block gas limit for call --trace

---

crates/config/src/inline/conf_parser.rs
crates/forge/tests/cli/test_cmd.rs

This got lost in https://github.com/foundry-rs/foundry/pull/8388
Also disables couple tests for test-isolate job

fix: respect profiles in inline configs

---

crates/cast/bin/main.rs
crates/cast/bin/opts.rs
crates/common/fmt/src/dynamic.rs
crates/common/fmt/src/lib.rs

- When using `cast calldata-decode` and similar functions in a script, it's helpful to have the output be in json so that it can be used with tools like `jq`.
- Adds `--json` or `-j` flag to `cast calldata-decode`,  to print output as json array
- Adds `--json` flag to `cast 4byte-decode`
- Adds `--json` flag to `cast abi-decode`
```bash
$ cargo run calldata-decode "transfer(address,uint256)" -j \
0xa9059cbb000000000000000000000000e78388b4ce79068e89bf8aa7f218ef6b9ab0e9d0000000000000000000000000000000000000000000000000008a8e4b1a3d8000 | jq
[
"0xE78388b4CE79068e89Bf8aA7f218eF6b9AB0e9d0",
"39000000000000000"
]
```
```bash
$ cargo run 4byte-decode -j 0x095ea7b30000000000000000000000001111111254eeb25477b68fb85ed929f73a9605820000000000000000000000000000000000000000000f0664af93dce3ad1d31f9
[ …
```

feat(cast,common): calldata-decode, abi-decode, and 4byte-decode json flag

---

Cargo.lock
crates/common/src/abi.rs
crates/verify/Cargo.toml
crates/verify/src/bytecode.rs

Cleans up code a bit, removing redundant `Result` and preferring checking `match_type.is_none()` instead of keeping a separate bool.
Also removes `--verification-type` flag as it doesn't make much sense because user'd expect us to determine match type during comparison.
Closes #8505. The cause is etherscan bug - it returns invalid constructor arguments for mentioned contract.
I've updated logic to not rely on etherscan constructor args if `--constructor-args` are passed.
Also updated `--constructor-args` to expect multiple values and abi-encode them similarly to `forge create` as this seems to be the expected UX at least by the author of #8505. I've kept an option for abi-encoded args as `--encoded-constructor-args`

fix: some verify-bytecode fixes

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/anchors.rs
crates/forge/tests/cli/coverage.rs

Re https://t.me/foundry_support/55383
PR https://github.com/foundry-rs/foundry/pull/8414 fixed the branch coverage report (issue reported in #7784 ) by properly mapping if/else source bodies
https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/analysis.rs#L236-L241
but it also made the wrong assumption that the first branch opcode after JUMPI should be `pc + 1`
https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/anchors.rs#L149-L153
This is not true because the evaluation is done for the opcode before JUMPI (so JUMPI is `pc + 1` and next opcode is `pc + 2`)
https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/anchors.rs#L134-L …

fix(coverage): proper instruction for 1st branch anchor

---

crates/script/src/lib.rs

This PR updates the `preprocess()` function's visibility to `pub` so that projects using Foundry as a dependency can preprocess script args.

Update `ScriptArgs::preprocess()` visibility to `pub`

---

crates/script/src/execute.rs

Removes incorrect check from `ExecutedState::build_trace_decoder`. It is redundant as `with_etherscan` will already set etherscan identifier to `None` if no key is found. 
This check always used `etherscan_api_key` and didn't take `[etherscan]` section into account, thus causing script traces not being identified unless `--etherscan-api-key` was set.

fix: etherscan identifier for scripts

---

crates/common/src/traits.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue1543.t.sol

Closes #8485
Closes #1543 
Atm unit / fuzz tests are performed only against the state resulting from `setup` call, but would be nice to support configuration of other txes / state modification for individual tests. This PR adds the possibility of per unit / fuzz test configuration of before test selectors / txes.
Configuration can be specified by implementing `beforeTestSetup` function
```Solidity
function beforeTestSetup(bytes4 testSelector) public pure returns (bytes[] memory beforeTestCalldata)
```
where
- `bytes4 testSelector` is the selector of the test that will run on before txes modified state
- `bytes[] memory beforeTestCalldata` is an array of arbitrary calldatas that will be applied before test run
E.g. for configuring `testC` to be executed on state modified by `testA` and …

feat(test): allow custom txes before unit and fuzz test

---

crates/cheatcodes/src/test/expect.rs
crates/evm/core/src/decode.rs

Sometimes revert data happens to be valid UTF-8 but not in any meaningful way. By restricting to ASCII it's more likely that the revert is actually human-readable.

chore: decode only ASCII reverts

---

Cargo.lock
Cargo.toml
crates/config/src/lib.rs
crates/config/src/utils.rs
crates/forge/tests/cli/config.rs

Removes `prague` flag from config and maps `EvmVersion::Prague` to `SpecId::PRAGUE_EOF`

chore(deps): bump foundry-compilers

---

Cargo.lock
crates/cheatcodes/Cargo.toml
crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/build.rs
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/test.rs
testdata/cheats/Vm.sol
testdata/default/cheats/GetFoundryVersion.t.sol

Closes #8036 
Implement a new cheatcode to get the foundry version: `vm.getFoundryVersion`.
The current versioning scheme incorporates the cargo version, the git SHA and the UTC timestamp of the build to simplify differentiating by version number until v1 is released.
The version format follows this structure: `<cargo_version>+<git_sha>+<build_timestamp>`.
For example, a typical version might look like this: `0.2.0+faa94c384+202407110019`.
Install `forge` locally.
```bash
cargo install --path ./crates/forge --profile release --force --locked
alias forgedev="$(pwd)/target/release/forge" 
```
Run `GetFoundryVersion` test.
```bash
$ pushd testdata
$ forgedev test --match-contract GetFoundryVersion
[⠢] Compiling 1 files with Solc 0.8.18
[⠆] Solc 0.8.18 finished in 101.72ms …
```

feat(cheatcodes): add `vm.getFoundryVersion()`

---

crates/cheatcodes/src/test/expect.rs

One of my tests which called `vm.expectRevert()` was failing with `FAIL. Reason: call did not revert as expected`, even though it was still reverting (with the expected reason) when I removed the call to `vm.expectRevert()`; for a while, I couldn't figure out why.
It took me a bit of time before realizing that the docs specify that `vm.expectRevert()` must be placed *immediately before* the call that is expected to revert. Part of my confusion was that I had another test that had a call to `vm.expectRevert()` followed by `vm.prank()`, and calls to other cheatcodes are ignored (so because that test was working, I thought I could just put `vm.expectRevert()` at the top of the test).
https://book.getfoundry.sh/cheatcodes/expect-revert
I updated the error message in the `vm.expectRevert()` …

fix(cheatcodes): clarify vm.expectRevert error message

---

crates/verify/src/bytecode.rs

Closes https://github.com/foundry-rs/foundry/issues/8545
If Etherescan returned incorrect constructor arguments, replace them with latest bytes of on-chain creation code, based on the length of local creation code. This should work well as long as metadata settings are same for both local and on-chain contracts (either both contain metadata, or both don't contain).

fix(`verify-bytecode`): extract constructor arguments from creation code

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/fork.rs

Closes #8537 
in #7360 Arbitrum block number returned by `eth_blockNumber` was fixed but chain specifics weren't applied to other calls ( like `eth_getBlockByNumber`)
- used best block for block number and apply chain specifics when converting block to eth api conform format

fix(anvil): apply Arbitrum specifics to API block

---

crates/cli/src/utils/cmd.rs

Closes #8509 
Uses the existing `estimate_via_rpc` flow to make sure the RPC estimates the gas preventing the reported issue
Sorts the match list to keep it maintainable

fix: add `Mantle` + `Mantle testnet` as exceptions for gas calculation during deployment

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/lib.rs
crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs

Follow up for #8512
proper handling of empty if/else statements and empty single if statement
Consistent behavior for `IfStatement` without else statement with `YulIf` 
- do not add branch coverage item when if/else does not have statements or when single if doesn't have statements
- introduce CoverageItemKind::SinglePathBranch kind for single if statement - lookup anchor instruction from ic/pc map instead using `find_anchor_branch` logic (that assume there are 2 branches to execute / results in 2 anchors) 
- fix failing tests, add test for single path branch

fix(coverage): proper single path branch support

---

Cargo.lock
crates/forge/tests/cli/main.rs
crates/forge/tests/cli/verify_bytecode.rs
crates/verify/Cargo.toml
crates/verify/src/bytecode.rs

Closes https://github.com/foundry-rs/foundry/issues/8555
Instead of relying on `Config` to determine whether we need to strip metadata, we now just look at the end of the bytecode and try decoding it into CBOR as suggested by @mds1 in https://github.com/foundry-rs/foundry/issues/8555#issuecomment-2256902230. If decoding succeeds, we strip the suffix
I've also added tests and a helper to add them. Tests are simply running `cast etherscan-source --flatten` and then try to verify compiled downloaded source against on-chain bytecode.

fix(verify-bytecode): fix metadata extraction and add tests

---

Cargo.lock
Cargo.toml
crates/cli/src/utils/cmd.rs

Resolves: https://github.com/foundry-rs/foundry/pull/8553#issuecomment-2257883866
Closes: https://github.com/foundry-rs/foundry/issues/8509
The exception appears to still be required, adding the new `MantleSepolia` entry
Verified correctness by deploying. Was able to succesfully deploy: https://explorer.sepolia.mantle.xyz/tx/0x1542c9760767afa1fbae82179f3ab62eff07d2ef47cb320edba26cbbfffa9ce7
Log:
```
forge script script/Counter.s.sol --rpc-url https://rpc.sepolia.mantle.xyz --keystore ~/.foundry/keystores/staging --broadcast -vvvv
[⠢] Compiling...
Enter keystore password:
Traces:
[90165] CounterScript::run()
├─ [0] VM::startBroadcast()
│   └─ ← [Return] 
├─ [49499] → new Counter@0x70C6E67b14e0daA3cB2e629bB42e351d113E4799
│   └─ ← [Return] 247 bytes of …
```

fix: error `intrinsic gas too low` when deploying contract on Mantle / Mantle Sepolia (follow-up)

---

Cargo.lock
crates/wallets/Cargo.toml
crates/wallets/src/error.rs
crates/wallets/src/wallet_signer.rs

Closes #7592 
When executing `forge script` with the `--account` and `--sender` flags, users are prompted to input their keystore password. If an incorrect password is entered, the command fails, producing a cryptic `Mac Mismatch` error.
A more user-friendly error message, such as `Failed to decrypt keystore: incorrect password` would be more helpful and informative for users.
<details>
<summary>Click to expand</summary>
Start anvil.
```bash
anvil
```
Create a keystore.
```bash
cast wallet import anvilDefaultKey --unsafe-password aaaa --private-key <pk>
```
Set up a small foundry project.
```bash
pushd /tmp
forge init hello_world
pushd hello_world
forge build
```
</details>
<details>
<summary>Click to expand</summary>
```bash
$ forge --version
forge 0.2.0 (26a755975 …
```

docs(`forge script`): improve `Mac Mismatch` error referring to failure to decrypt of keystore

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/core/src/eth/transaction/optimism.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/optimism.rs

tx hash calculation for deposit tx for `anvil --optimism` was different from [specs](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type). this made it difficult to deterministically generate the L2 tx hash from the L1 deposit transaction.
- the EIP-2718 tx type was not included when calculating hash
- encoding was slightly different from [spec](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type) 
- nonce was included in the rlp encoding
- order of fields was different from spec
- calculate tx hash after encoding in eip-2718 envelope format
- fix order of fields / remove nonce when RLP encoding / decoding
- added tests - checks against a op-sepolia tx hash / fields to make sure that the hash / encoding is consistent
the following …

fix(anvil): fix incorrect op-stack deposit tx hashes 

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/FunctionDefinitionWithFunctionReturns/fmt.sol
crates/fmt/testdata/FunctionDefinitionWithFunctionReturns/original.sol

Closes #7920 
- if fn with returns format is disabled, surround returned params in `returns ()` to produce valid Solidity

fix(fmt): surround with returns in fn with format disabled

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/InlineDisable/fmt.sol
crates/fmt/testdata/InlineDisable/original.sol

Closes #3790 
Closes #3789 
-  do not format fn attrs and returns if disabled
- handle special case where body fn starts on a disabled line: determine first enabled statement and write raw code until
- add test variations of disable fn declaration
- add test for https://github.com/foundry-rs/foundry/issues/3789
TBD: follow ups on moving logic in `visit_body` fn  - should solve issues with disabling first / last lines of blocks as in https://github.com/foundry-rs/foundry/issues/3830

fix(fmt): preserve function declaration if fmt disabled

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/api.rs

This PR fixes #8590, a race condition entering `do_mine_block` while another block is already being mined. Overlapping mining attempts would result in unexpected block state.
Add a lock to `do_mine_block` so that block mining is consecutive.

fix(anvil): support overlapping anvil_mine calls

---

crates/cli/src/opts/build/core.rs

Closes: https://github.com/foundry-rs/foundry/issues/3306
`--compiler-version` is accepted as part of the `forge verify-contract` flow
`--use` is the same flag used in `forge create` but does not accept `--compiler-version` to be set
When passing the `--verify` flag the two intersect yielding an incorrect error message recommending users to use the `--compiler-version` flag when it is not available. This PR adds the `--compiler-version` as an alias, fixing it in a non-breaking way.

fix: add `--compiler-version` as alias of `use` in `forge create` 

---

crates/common/fmt/src/ui.rs

I was debugging some blob txs and used `cast tx` to print them, only to learn that `cast` was only outputting the "legacy" fields for transactions.
match on the `transaction_type` and output the correct fields.
NOTE: it currently panics w/ a `todo!` for unknown tx types, but we could have it fall back to the `Some(0) | None` case instead.  I figured the panic would make it more likely for the new tx types to get implemented in a timely manner :)

feat(cast) tx: pretty print new transaction fields

---

crates/forge/bin/cmd/inspect.rs

(*edited) 
Closes #7947
Revise the output of the `forge inspect <contract> events` command to display events signatures along with their topics. The previous version of the command was not useful because it displayed the signatures twice.
Before:
```bash
$ forge inspect ERC20 events                                                                                                                                                            
{
"Approval(address,address,uint256)": "\"Approval(address,address,uint256)\"",
"Transfer(address,address,uint256)": "\"Transfer(address,address,uint256)\""
}
```
After:
```bash
$ forge inspect ERC20 events …
```

feat(forge): modify `events` in `forge inspect` to return event signature

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Closes #8605 
- statements in if/else could be blocks but also single statements without brackets
- update `has_statements` fn to account  if/else statements types without brackets

fix(coverage): account if/else statements without brackets

---

.github/workflows/release.yml
Cargo.lock

Releases 0.1.2 and 0.1.3 added support for aarch64 Linux and MSVC, among others. See:
- https://github.com/DaniPopes/keccak-asm/pull/5
- https://github.com/DaniPopes/keccak-asm/pull/6
- https://github.com/DaniPopes/keccak-asm/pull/8

ci: enable asm-keccak on more platforms

---

.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml

Makes it easier to identify new tickets that require labeling
Adds the `T-needs-triage` label to the default forms for ticket creation

feat: add default `T-needs-triage` label to default feature / bug form

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/anchors.rs
crates/evm/coverage/src/lib.rs
crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs

Closes #8604 
Atm for branches we determine instruction anchors for both if / else statements. This works OK but in some edge cases like https://github.com/foundry-rs/foundry/issues/8604#issuecomment-2270443031 where last JUMPI instruction within if block triggers replacement of anchor properly / previously identified. 
- for if blocks with statements the anchor is always the opcode of first statement: introduce `is_first_opcode` flag for `Branch` coverage item kind. Set flag to true for if with statements and test flag when finding branch anchors. If set as first opcode then find instruction from source map /  ic-pc map (`find_anchor_simple`), otherwise by looking up last JUMPI instruction (`find_anchor_branch`). 
- tests (fixed test for single statement coverage false path where all …

fix(coverage): use first opcode for if block with statements

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/lib.rs
crates/forge/src/coverage.rs

`SinglePathBranch` kind is the same with `Branch` kind with `first_op_code` flag set to true
- remove `SinglePathBranch` and use `Branch` with `first_op_code=true`

chore(coverage): remove SinglePathBranch kind, use Branch kind

---

crates/common/src/provider/mod.rs

we currently don't configure a chain specific poll interval and this would fallback to 7s if not local in alloy's default impl.
we can use the chain if it's known or assume some reasonable default

perf: configure provider poll interval

---

crates/cast/bin/cmd/call.rs
crates/cast/src/lib.rs

- Adds `-j` or `--json` flag to `cast call` to have JSON formatted output. This is helpful when using `cast call` in scripts with tools like `jq`.
```bash
$ cargo run call -r https://rpc.ankr.com/eth 0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2 "rollupIDToRollupData(uint32)(address,uint64,address,uint64,bytes32,uint64,uint64,uint64,uint64,uint64,uint64,uint8)" 1 -j
[
"0x519E42c24163192Dca44CD3fBDCEBF6be9130987",
"1101",
"0x0775e11309d75aA6b0967917fB0213C5673eDf81",
"9",
"0x51c3cc08917f8837e12cca778e6d636a3eb467e31e006d58db6c6022f4551199",
"2086321",
"2086269",
"0",
"0",
"2001442",
"3",
"0"
]
```

feat(cast): call json flag

---

crates/forge/tests/it/invariant.rs
testdata/default/fuzz/invariant/common/InvariantShrinkWithAssert.t.sol

failures from https://github.com/foundry-rs/foundry/issues/4438#issuecomment-2275407139 are caused by `test_invariant_assert_shrink` being SIGed and not STDERR failures,
```
TRY 3 SIG 7 [   1.084s] forge::it invariant::test_invariant_assert_shrink
```
which likely is caused by running it with default runs / depth of 500.
Since test was introduced to make sure asserts in invariant tests are treated the same as requires (and therefore can shrink to same len - see https://github.com/foundry-rs/foundry/issues/6683#issuecomment-1966794329) we can simplify the test and reduce to 1 run and depth of 15

chore: simplify assert/require shrink test

---

crates/common/fmt/src/ui.rs

closes #8635
some rpc return `"accessList": null,`

fix: bad unwrap for pretty fmt

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/FunctionDefinition/all.fmt.sol
crates/fmt/testdata/FunctionDefinition/params-first.fmt.sol

Closes #7721 
`params_first`  for fns with single params doe not write param on its own line, as per docs :
"params_first" - Break the function header into multiple lines, with each parameter on its own line. The function name stays on the first line.
- write single param multiline if setting to params first

fix(fmt): write single param on multiline if `params_first`

---

crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/8591
We didn't print logs correctly for `eth_call` and `eth_estimateGas` requests

fix(anvil): correctly print logs

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs

Most of the times, devs don't want to set any particular code size limit but rather disable the whole thing. Previously `--code-size-limit=10000000` was required.
Introduce new anvil flag: `--disable-code-size-limit` that sets size limit to uint::max.

Add --disable-code-size-limit flag for anvil

---

crates/config/src/fix.rs

```
error: the `Err`-variant returned from this function is very large
--> crates/config/src/fix.rs:76:10
|
76 |     ) -> Result<(), InsertProfileError> {
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 200 bytes
|
= help: try reducing the size of `fix::InsertProfileError`, for example by boxing large elements or replacing it with `Box<fix::InsertProfileError>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
= note: `-D clippy::result-large-err` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::result_large_err)]`
```
https://github.com/foundry-rs/foundry/actions/runs/10370884407/job/28709851170?pr=8632
add `#[allow(clippy::result_large_err)]`

fix: allow result large err

---

crates/common/src/contracts.rs
crates/forge/tests/cli/coverage.rs

repro of issue https://github.com/grandizzy/coverage-immutables-repro
Coverage not properly match by deployed bytecode when contract has  immutables
- parametrize accepted score, keep 0.1 for creation code and bump to 0.15 for deployed code (in provided repro matched score of 0.11235)

fix(coverage): relax deployed bytecode accepted score

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/Repros/fmt.sol
crates/fmt/testdata/Repros/original.sol

Closes #8650 
- apply single_line_statement_blocks to else block

fix(fmt): apply multi statement block config to else block

---

crates/cast/bin/main.rs
crates/cast/src/lib.rs

Closes #8652 
This PR contains two things:
1. A fix of `cast --to-ascii` to remove any trailing whitespace before converting the value to ascii.
```bash
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | cast to-ascii
Error: 
Invalid character '\n' at position 192
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | cast to-ascii
USDT
```
3. A fix of `cast call` to remove the additional break line.
```bash
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004555344540000000000000000000000000000000000000000000000000 …
```

fix: `cast --to-ascii` does not work if input has trailing whitespaces

---

crates/anvil/src/eth/api.rs

Results for `eth_getTransactionCount`  do not use the local cache when forking. This significantly slows down any fork tests that use `ethers.js` in combination with `anvil`. 
Update `predates_fork_inclusive` to `predates_fork` as with most other operations.

fix(anvil): get_transaction_count forking

---

Cargo.lock
crates/cheatcodes/Cargo.toml
crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/crypto.rs
testdata/cheats/Vm.sol

Closes https://github.com/foundry-rs/foundry/issues/7908
Adds cheatcode for deriving public key for P256 private key

feat: `vm.publicKeyP256`

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/run.rs
crates/common/src/evm.rs
crates/config/src/lib.rs
crates/config/src/utils.rs
crates/evm/core/src/lib.rs
crates/evm/core/src/opts.rs
crates/evm/core/src/precompiles.rs
crates/evm/core/src/utils.rs
crates/evm/evm/src/executors/trace.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/src/multi_runner.rs
crates/forge/tests/cli/config.rs
crates/script/src/lib.rs
crates/verify/src/bytecode.rs

Adds `--alphanet` flag to `EvmArgs` and `alphanet` config option, enabling P256 precompile.
Added `is_alphanet` fn to `InspectorExt` trait which is checked when configuring new EVM.

feat: `--alphanet` flag and config option

---

crates/common/src/evm.rs

After typing `forge script --help`, the help message of `--sender`  is:
```
The address which will be executing tests.
```
It's a bit confusing because `forge script` is not executing tests.

fix comment of `--sender`

---

crates/common/fmt/src/console.rs

Closes https://github.com/foundry-rs/foundry/issues/8700
There are several issues:
1. We attempt parsing `FormatSpec` and thus consume some characters even if there are no values to format. Those characters are not pushed to resulted string. Solution is to skip parsing `FormatSpec` if there are no characters left.
2. On parser failure, we only push a single character instead of all consumed. Solution is to return `String` in `Err` variant with all consumed chars.
3. There are probably some more issues because of `&mut chars` being wrapped into `chain` and `Peekable` thus making it a bit hard to follow on how many times it was actually advanced. Solution is to use a single iterator everywhere

fix: console.log formatting

---

crates/evm/coverage/src/inspector.rs
crates/forge/tests/cli/coverage.rs

- for contracts that are not already created the hash in interpreter is 0x. This leads to recording coverage for 0x hash instead of contract hash (and if multiple contracts created in same test then only the first one will have constructor covered).
- in coverage collector, if hash is 0 then recalculate it from contract bytecode

fix(coverage): ensure contract hash to record coverage for is not zero

---

crates/cast/bin/main.rs
crates/cast/bin/opts.rs
crates/cast/tests/cli/main.rs

Calculates an Ethereum-specific hash in [EIP-191 format](https://eips.ethereum.org/EIPS/eip-191): 
```
keccak256("\x19Ethereum Signed Message:\n" + len(message) + message))
```
Add subcommand `hash-message` to `cast`.
```
cast hash-message 'Hello World'
0xa1de988600a42c4b4ab089b619297c17d53cffae5d5120d82d8a92d0bb3b78f2
cast hash-message 0x48656c6c6f20576f726c64
0xa1de988600a42c4b4ab089b619297c17d53cffae5d5120d82d8a92d0bb3b78f2
cast hm hello
0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750
```

feat(cast): add `cast hash-message`

---

crates/forge/bin/cmd/watch.rs

Issue Link -> https://github.com/foundry-rs/foundry/issues/8664
Currently the following command was being attempted to be executed:
forge test --match-path test/Counter.t.sol -w
But by default it can be done without the --math-path, since the command adds it by itself
--match-path does not work with watch mode: cannot be used multiple times 
`error: the argument '--match-path <GLOB>' cannot be used multiple times
Usage: forge test [OPTIONS]
For more information, try '--help'.
[Command exited with 2, lasted 10.7375ms]`
My motivation is to continue contributing to tools like Foundry, to learn from them and how they work in Open Source environments. I really like to always be in constant practice and what better way to do it than by practicing and helping the community.
Currently when …

Issue #8664 | Bug 🐛: --match-path does not work with watch mode: cannot be used multiple times #8664

---

crates/cast/bin/cmd/send.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/config/src/lib.rs
crates/forge/bin/cmd/create.rs
crates/forge/tests/cli/config.rs
crates/script/src/broadcast.rs
crates/script/src/lib.rs
crates/script/src/progress.rs
crates/script/src/receipts.rs

Closes https://github.com/foundry-rs/foundry/issues/8667
Adds `--timeout` option to `forge create`, `forge script` and `cast send`. Also supports `transaction_timeout` config key and `ETH_TIMEOUT` env var

feat: add transaction timeout config

---

Cargo.lock
crates/forge/tests/cli/build.rs
crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/create.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs
crates/test-utils/Cargo.toml
crates/test-utils/src/lib.rs
crates/test-utils/src/util.rs

Use `SNAPSHOTS=overwrite` to generate all assertions except for coverage.
We want assertions to be as much as possible auto generated, rather than writing manually `[...]` and the other catch-all filters everywhere.

test: add builtin redactions to snapbox assertions

---

crates/cast/bin/cmd/create2.rs

Compute the address that would result from a `CREATE2` operation with the given `deployer`, `salt` and either `initCode` or `initCodeHash`.
The following is a test script using `ethers.js`: 
Add argument `salt` to `create2` command.
```
cast create2 --deployer=0x8ba1f109551bD432803012645Ac136ddd64DBA72 --salt=0x7c5ea36004851c764c44143b1dcb59679b11c9a68e5f41497f6cf3d480715331 --init-code=0x6394198df16000526103ff60206004601c335afa6040516060f3
0x533ae9d683B10C02EbDb05471642F85230071FC3
cast create2 --deployer=0x8ba1f109551bD432803012645Ac136ddd64DBA72 --salt=0x7c5ea36004851c764c44143b1dcb59679b11c9a68e5f41497f6cf3d480715331 --init-code-hash=0x9fd9ed530ad2d3bac509a72be6fb4b53ff252bef5702e88e99a0718cf4433d02
0x533ae9d683B10C02EbDb05471642F85230071FC3
```

feat(cast): get create2 address

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/otterscan/api.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/common/src/contracts.rs
crates/common/src/evm.rs
crates/common/src/provider/runtime_transport.rs
crates/doc/src/parser/mod.rs
crates/doc/src/preprocessor/contract_inheritance.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/invariant/shrink.rs
crates/evm/fuzz/src/lib.rs
crates/evm/fuzz/src/strategies/param.rs
crates/fmt/src/visit.rs
crates/forge/tests/cli/test_cmd.rs

closes #5564
closes #6294 - tested with https://github.com/grandizzy/foundry-issue-6294
closes #4523 - optimistically closing, tested with various combinations and wasn't able to repro the big discrepancy anymore (though there's still a difference of ~ 2750 consumed gas by pause / resume calls)
tbd:
#4370 - should be fixed by refunding gas spent by pause / resume calls (similar with diff seen in #4523)
- keep track of current execution frame paused gas in `paused_frame_gas` vec  
- push paused gas when
- new frame entered (interpreter init) and `pause_gas_metering` flag is true (scenario when gas meter was paused in a prev frame)
- during interpreter step if `pause_gas_metering` and no gas recorded for current frame (scenario when gas meter was paused in current frame)
- pop paused gas …

fix(cheatcodes): rework gas metering pause/resume

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/repros.rs
testdata/default/cheats/GasMetering.t.sol

Follow-up https://github.com/foundry-rs/foundry/pull/8736
Move the gas pop to step_end, and trigger when the instruction result is not continue
Ideally this would be in something like a destroy_interpreter hook
- https://github.com/foundry-rs/foundry/pull/8744: Fixes #4370

chore(cheatcodes): make pauseGasMetering more robust

---

crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test/expect.rs
testdata/default/repros/Issue7457.t.sol

ref https://github.com/foundry-rs/foundry/pull/8429#discussion_r1677178655

fix: throw error if `vm.expectEmit` is used on anonymous event

---

Cargo.lock

```
Locking 13 packages to latest compatible versions
Updating alloy-chains v0.1.27 -> v0.1.29
Updating bytemuck v1.17.0 -> v1.17.1
Updating c-kzg v1.0.2 -> v1.0.3 (latest: v2.0.0)
Updating cc v1.1.14 -> v1.1.15
Updating clap_complete v4.5.23 -> v4.5.24
Updating foundry-block-explorers v0.5.1 -> v0.5.2
Updating prettyplease v0.2.21 -> v0.2.22
Updating proc-macro-crate v3.1.0 -> v3.2.0
Updating ratatui v0.28.0 -> v0.28.1
Updating rustls-webpki v0.102.6 -> v0.102.7
Updating svm-rs v0.5.5 -> v0.5.6
Updating svm-rs-builds v0.5.5 -> v0.5.6
Removing toml_edit v0.21.1
Updating tonic v0.12.1 -> v0.12.2
Removing winnow v0.5.40
```
Mainly alloy-chains, svm-rs, proc-macro-crate (removes old toml-edit+winnow)

chore(deps): midweek bumps

---

crates/forge/bin/cmd/selectors.rs

- Closes #8726 
```sh
forge selectors find 0xdd62ed3e 
```
Supports partial inputs as well:
```sh
forge selectors find dd  # lists all functions/events/errors with selector starting with `dd`
```

feat(`forge selectors`): add `find` command

---

crates/config/src/fmt.rs
crates/fmt/src/formatter.rs
crates/fmt/testdata/FunctionDefinition/all.fmt.sol
crates/fmt/testdata/FunctionDefinition/params-multi.fmt.sol

Closes #8761 - introduced breaking change for `params_first`
As suggested in https://github.com/foundry-rs/foundry/issues/8761#issuecomment-2314199656
`params_first` Writes function parameters multiline first regardless number of params
`params_first_multiline` new option added which only splits parameters onto their own line when there is more than one param

fix(fmt): `params_first_multi` split if more than one param

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test/expect.rs
crates/forge/tests/cli/test_cmd.rs
testdata/cheats/Vm.sol

Closes #3725 
Closes #7629 
`vm.expectRevert(bytes4)` cheatcode checks for revert data to fully match whereas only the first 4 bytes should be checked. As suggested in #3725, for backwards compatibility reasons a new `vm.expectPartialRevert(bytes4)` cheatcode is introduced which checks only the first 4 bytes of reverted data.
- add `ExpectedRevert.partial_match` and compare only the first 4 bytes actual / expected reverts if set to true
- add new `expectPartialRevert` cheatcode that sets `ExpectedRevert.partial_match` to true

feat(cheatcodes): add expectPartialRevert cheatcode

---

crates/verify/src/bytecode.rs
crates/verify/src/utils.rs

Ref https://github.com/foundry-rs/foundry/issues/8722#issuecomment-2306849788 
Verification will fail if the contract is expecting constructor args but none are provided by the user using `--constructor-args` and the explorer also doesn't return any (in case of predeploys).
Add a check that bails and notifies the user.

fix(forge vb): bail when args expected but none provided

---

crates/forge/bin/cmd/test/mod.rs

This PR tries to fix [this issue](https://github.com/foundry-rs/foundry/issues/8742), users can now simply type `forge test path_to_sol` to run test.

support positional `--mp` parameter for `forge test`

---

crates/anvil/src/eth/error.rs
crates/cast/bin/cmd/access_list.rs
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/estimate.rs
crates/cast/bin/cmd/mktx.rs
crates/cast/bin/cmd/send.rs
crates/cast/bin/tx.rs

Added handling for all revm error variants to anvil, caught a panic while testing EIP-7702.
Updated `CastTxBuilder` to allow omitting `to` if there's no value being transferred and tx is an EIP-7702 tx to allow doing just `cast --auth <authotization>`

fix(eip7702): small fixes

---

crates/cheatcodes/src/json.rs

Hi, I'm here trying to solve #8778.
This is my first time contributing here, and also my first time writing Rust on a real project. Please let me know if the approach I took is wrong here. Thanks!
Fix #8778 as it seemed like a small issue I could take on, and the current behaviour bugged me today as well.
Use the already imported `alloy_dyn_abi` crate to try and parse addresses when the passed in `DynSolType` is an address. We do some minimal validation on the passed in string, and handle it with the underlying crate.

fix(cheatcodes): fail when trying to parse malformatted strings as addresses

---

crates/forge/src/lib.rs
crates/forge/tests/it/fuzz.rs

- properly apply `max_global_rejects` config to proptest runner config

fix(fuzz): apply inline max-test-rejects config

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test.rs
crates/cheatcodes/src/test/assume.rs
crates/forge/tests/cli/test_cmd.rs
testdata/cheats/Vm.sol

Closes #4090 
Closes #7246 
Similar with `assume` cheatcode, but for discarding inputs in fuzz runs that reverts:
```Solidity
/// Discard this run's fuzz inputs and generate new ones if next call reverted.
function assumeNoRevert() external pure;
```
- split assume* cheatcodes in separate mod
- in call_end, if assumeNoRevert cheatcode set, discard run if we're at the same depth as cheatcode and call reverted by returning result with MAGIC_ASSUME output (caught by fuzz and invariant tests and discarded). If call didn't revert then reset chetcode state and continue test
- unit tests

feat(cheatcodes): add vm.assumeNoRevert for fuzz tests

---

crates/cast/src/lib.rs
crates/forge/bin/cmd/selectors.rs

Fix small issues.
1. `cast max-uint`
2. `forge selectors find` typo: `Event` -> `Error`
```
cast maxu uint8
255
cast maxu uint16
65535
cast maxu uint256
115792089237316195423570985008687907853269984665640564039457584007913129639935
```

fix: small issues

---

crates/forge/tests/cli/test_cmd.rs

- `test_assume_no_revert` CI on master fails sometimes with more runs than 256 - this could happen if there are persisted failures which are replayed
- add deterministic seed, make test faster by limiting runs to 100, ignore number of runs as we're only interested in test to pass

chore: fix `test_assume_no_revert` failing test

---

crates/forge/bin/cmd/bind.rs

Alloy has been released and is ready for production. `forge bind` still defaults to `ethers`
Default to alloy, opening the prospect of removing `ethers` dependency completely in the future

fix(`forge bind`): default to alloy

---

Cargo.lock
crates/cast/Cargo.toml
crates/cast/bin/main.rs
crates/cast/src/lib.rs

The new version of EVMole can extract function state mutability with [high accuracy](https://github.com/cdump/evmole?tab=readme-ov-file#function-state-mutability). Let's use it in `cast selectors`
Upgrade EVMole to 0.4.1 and show state mutability in the `cast selectors` output
```
$ cast selectors $(cast code 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
0x06fdde03                              view
0x095ea7b3      address,uint256         nonpayable
0x18160ddd                              view
0x23b872dd      address,address,uint256 nonpayable
0x2e1a7d4d      uint256                 nonpayable
0x313ce567                              view
0x70a08231      address                 view
0x95d89b41                              view
0xa9059cbb      address,uint256         nonpayable
0xd0e30db0 …
```

feat(cast/selectors): show function state mutability

---

crates/anvil/src/eth/backend/mem/mod.rs

closes #8814
mirrors usually node behaviour

fix: ignore nonce in call evm env

---

crates/cast/bin/cmd/interface.rs
crates/cli/src/opts/build/core.rs
crates/cli/src/opts/build/paths.rs
crates/cli/src/utils/mod.rs
crates/config/src/lib.rs
crates/config/src/macros.rs
crates/config/src/utils.rs
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/clone.rs
crates/forge/bin/cmd/doc/mod.rs
crates/forge/bin/main.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/it/test_helpers.rs

Removes the git command spawn by using `Path::ancestors` + impl cleanup
Saves a few ms on all commands startup because these functions are called multiple times

chore: improve git/project root pathfinding

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/fork.rs

Fixes #8684 
Resetting from an existing fork to another fork would not update underlying `ForkedDatabase`, resulting in an invalid state for the new fork. 
reset the underlying the `ForkedDatabase` using `node_config.setup_fork_db_and_config`

fix(`anvil`): reset from fork to another fork

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/evm/mock.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/utils.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/tests/it/cheats.rs
testdata/cheats/Vm.sol
testdata/default/cheats/ArbitraryStorage.t.sol
testdata/default/cheats/CopyStorage.t.sol
testdata/default/cheats/MockFunction.t.sol

- #4072 : 
- added `copyStorage(address from, address to)`
- added `setArbitraryStorage(address target)`
- added `mockFunction(address callee, address target, bytes calldata data)`
To be followed up with a PR for adding remaining `expect*Call` and `fresh*` cheatcodes.
- `setArbitraryStorage(address target)`:
- added in `Utilities` group
- when called, the `target` address is added in `arbitrary_storage` vec
- in cheatcode `inspector.step_end`, generate random value if target address is marked as arbitrary storage, current opcode is SLOAD and storage slot untouched (cold `ensure_arbitrary_storage` fn added)
- apply same logic to `vm.load` cheatcode
- tests and kontrol ported tests added
- `copyStorage(address from, address to)`:
- added in `Utilities` group
- when called, from and to …

feat(cheatcodes): additional cheatcodes to aid in symbolic testing

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/test.rs
crates/evm/core/src/constants.rs
crates/evm/core/src/decode.rs
crates/evm/evm/src/executors/fuzz/mod.rs
crates/evm/evm/src/executors/invariant/error.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/fuzz/src/error.rs
crates/evm/fuzz/src/lib.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/ScriptVerify.sol
crates/forge/tests/it/fuzz.rs
crates/forge/tests/it/invariant.rs
crates/test-utils/src/util.rs
testdata/cheats/Vm.sol

Adds `vm.skip(bool,string)` for an optional string reason which shows up in the output.
Unfortunately not super straight forward for fuzz tests because we have to decode the encoded reason again to properly propagate it 
\+ tweaks to a few error messages and cleanups
Can be added to https://github.com/foundry-rs/foundry/pull/8852

feat: add support for test skip reasons

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/utils.rs

re https://github.com/foundry-rs/foundry/pull/8807#discussion_r1755012005

chore(cheatcodes): ArbitraryStorage as option

---

Cargo.lock
crates/common/src/shell.rs
crates/forge/Cargo.toml
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/test_cmd.rs

closes #7004 
- add junit xml report support using quick-junit crate
- testsuites timestamp is UTC at the moment report generated; for passed test the test output is added in `<system-out>`, for failed in `<system-err>`; currently only logs displayed if running with verbosity > 2(traces not decoded, will be added with refactoring code and reusing code for json output as well)
- tests covering pass, fail, and skip tests

feat(forge): support junit xml test reports

---

crates/forge/tests/it/repros.rs

Flaky polygon RPCs, even in alchemy: <https://github.com/foundry-rs/foundry/actions/runs/10837501747/job/30073602758>
> Failed to send/recv `storage` err=failed to get storage for 0x7aB0b2835f71ad2a31056007F651C897E5EE148A at 43: server returned an error response: error code -32000: execution aborted (timeout = 10s) address=0x7aB0b2835f71ad2a31056007F651C897E5EE148A index=43

test: ignore 3703

---

crates/common/src/transactions.rs
crates/forge/tests/cli/script.rs
crates/script/src/lib.rs
crates/script/src/simulate.rs
crates/script/src/transaction.rs

Closes https://github.com/foundry-rs/foundry/issues/8817 + some cleanup
Right now we don't fill metadata for transactions at all if `--skip-simulation` is passed. However, most of the metadata can't be obtained without simulation. I've updated logic to only use simulated `ScriptResult` to fill `tx.gas` and `additional_contracts`
Also added a warning + prompt in cases when script attempts to broadcast a zero-value transaction to address without code. It should provide protection for cases when contract was deployed outside of `broadcast` block

fix(script): correctly fill metadata + prompt on noop transactions

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/cmd.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/db.rs
crates/anvil/src/eth/backend/mem/fork_db.rs
crates/anvil/src/eth/backend/mem/in_memory_db.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/tests/it/state.rs

Ref #8518
Adds a new flag `--preserve-historical-states` (default: false) to be used with `--dump-state`. If this flag is enabled anvil will dump `InMemoryBlockStates` into the state file. 
Behind the scenes it uses `StateSnapshot` of corresponding `StateDb` and serializes it for dumping. 
This brings a breaking change to the anvil API `anvil_dump_state(&self)` -> `anvil_dump_state(&self, preserve_historical_states: bool)` 
These `historical_states` are then loaded into `InMemoryBlockStates` when called with `--load-state`
This enables users to make RPC calls at a particular `block` (preceding the state dump block) that existed in the previous anvil instance.

feat(`anvil`): optionally preserve historical states on dump_state

---

crates/cheatcodes/src/evm/mock.rs

Fixes #8556
Use `apply_stateful` to access and update `acc.code` in case empty.

fix(`cheatcodes`): apply_stateful in mockCallRevert

---

crates/cheatcodes/src/inspector.rs
crates/evm/evm/src/inspectors/stack.rs
testdata/default/cheats/Nonce.t.sol

closes #8811 take2
- do not reset account nonce when running with isolate
- explicitly increment nonce in cheatcode inspector only if calls are not isolated
- `cargo test --all --features=isolate-by-default` pass

fix(test): increment nonce for calls too when isolate

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test/expect.rs
crates/evm/core/src/decode.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/fuzz.rs
testdata/cheats/Vm.sol
testdata/default/cheats/ExpectRevert.t.sol

Closes #5299 
Closes https://github.com/foundry-rs/book/issues/945
https://github.com/foundry-rs/foundry/issues/5299#issuecomment-1623838745
- added `expectRevert` cheatcodes with reverter (expects an error on next call from the given address)
```Solidity
function expectRevert(bytes calldata revertData, address reverter) external;
function expectRevert(bytes4 revertData, address reverter) external;
function expectRevert(address reverter) external;
function expectPartialRevert(address reverter) external;
```
- when reverter arg passed then process expected revert for next call, at any depth. If address of contract that reverted the call (call's target address) is different than the expected reverter, then fail test with `Reason: Reverter != expected reverter` reason.
- code refactoring: …

feat(cheatcodes): expectRevert with specific reverter address

---

crates/forge/tests/cli/ext_integration.rs

- since nonce is now incremented when running in isolated mode, following tests are failing in https://github.com/reflexer-labs/geb ext isolate integration
```
[FAIL] testCoinAddress() (gas: 13269)
[FAIL] testDomain_Separator() (gas: 18385)
```
```Solidity
assertEq(address(token), address(0x0b7108E278c2E77E4e4f5c93d9E5e9A11AC837FC));
...
assertEq(token.DOMAIN_SEPARATOR(), 0x77670640b7d855b91efc63703e88e4850fd7233ae2085484ff5d87a6518b46c8);
```
ref https://github.com/reflexer-labs/geb/blob/1a59f16a377386c49f520006ed0f7fd9d128cb09/src/test/shared/Coin.t.sol#L364-L374
This happens due to token deployed at different address.
- do not run geb ext integration test for test-isolate CI

chore(forge): fix isolate ext integration tests

---

Cargo.toml

Re-enabling symbols in release since it's useful for backtraces

chore: reduce size further

---

crates/common/fmt/src/console.rs

Rewrite the `ConsoleFmt` (`console.log`) format string parser to be more resilient and extensible.

refactor: rewrite the console.log format string parser

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/json.rs
crates/cheatcodes/src/toml.rs
testdata/cheats/Vm.sol
testdata/default/cheats/Toml.t.sol
testdata/fixtures/Toml/nested_toml_struct.toml
testdata/fixtures/Toml/test.toml

Closes #8810 
Mostly a copy/paste of #8345.
Minor: removal of references of `json` in `testdata/default/cheats/Toml.t.sol` and use of `toml` instead.

feat: implement `parseTomlType` cheats

---

crates/evm/core/src/backend/mod.rs
crates/evm/core/src/lib.rs

Gets rid of revm monomorphization of NoopInspector (1/6 in forge)

chore: use dyn InspectorExt in Backend

---

crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs

Gets rid of a few more revm monomorphizations (2/6 + 1 with https://github.com/foundry-rs/foundry/pull/8919)
Negligible perf impact since Db access is rare and cost of dynamic dispatch is minimal compared to hashmap lookups or network requests that the db does

chore(evm): use dyn DatabaseExt in inspect

---

crates/evm/traces/src/folded_stack_trace.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/test_cmd.rs

Stacked on top of https://github.com/foundry-rs/foundry/pull/8929
Deprecate --debug and --decode-internal 's regex argument in favor of using --match-*

chore: deprecate --debug regex argument

---

crates/cast/tests/cli/main.rs
crates/forge/tests/it/inline.rs

more fixes in the effort to make `cargo test --all --all-features` run clean
- cast `receipt_revert_reason`: use next http endpoint for 2nd call to avoid rate limits
- cast `send_requires_to` and `mktx_requires_to`: panicd `error sending request for url (http://localhost:8545/)`, pass `--chain=1` to avoid such
- `inline_config_run_fuzz`: make sure fresh runner so there's no failed fuzz persisted / needed to rerun
TBD: there's still occasionally failing tests (seen in cast and soldeer) e.g.
```
thread 'storage' panicked at crates/cast/tests/cli/main.rs:1021:10:
Expected success, was 101
```

chore: fixes for --all-features tests

---

crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/gas.rs
crates/anvil/tests/it/proof.rs
crates/anvil/tests/it/traces.rs
crates/cast/tests/cli/main.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/verify_bytecode.rs

more fixes for `cargo test --all --all-features` clean run
- send shutdown signal for long running tests that spawns anvil, fixing
```
failed to spawn node: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
- avoid RPC URL rate limit for storage test
- avoid etherscan rate limit for `verify_bytecode` tests, fixing
```
Error: 
Received error response: status=0,message=NOTOK, result=Some("Max calls per sec rate limit reached (5/sec)")
failures:
verify_bytecode::can_verify_bytecode_with_metadata
```
- remove `DAPP_REMAPPINGS` env var from `can_override_config` test, fixing
```
thread 'config::can_override_config' panicked at crates/forge/tests/cli/config.rs:210:5:
assertion failed: `(left == …
```

chore: more fixes for --all-features tests

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/pool/transactions.rs
crates/anvil/tests/it/fork.rs

Fixes #8940 
Change `TryFrom` implementations of `PoolTransaction` and `TypedTransaction` to use `WithOtherFields<RpcTransaction>` instead of `RpcTransaction`

fix(`anvil`): handle OP deposit txs in `TypedTransaction` and `PoolTransaction` conversion

---

Cargo.lock
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/run.rs
crates/cli/src/utils/cmd.rs
crates/evm/traces/src/lib.rs

Closes https://github.com/foundry-rs/foundry/issues/8906.
Prints the contract creation bytecodes in the trace when `--verbose` is passed to `cast run`.
I'm not sure if there are tests for this parts of the code, so I haven't added or changed any.
Formatting was a big mystery to me, I did my best manually, but I don't understand what's the correct approach. I haven't found any guide in `.md` files, but there is a `rustfmt.toml` file and the code seems formatted, but running `cargo fmt` alters dozens of files across the whole project, which apparently are not automatically formatted.

feat(cast): add contract creation bytecodes to traces

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/lib.rs
crates/anvil/tests/it/fork.rs
crates/anvil/tests/it/gas.rs
crates/anvil/tests/it/transaction.rs
crates/test-utils/src/rpc.rs

#8759 and others I believe were mostly afflicted by the fact that most eth_call requests do not typically fill out the `gas` field on call requests (including alloy bindings), and if you weren't in forking mode, with `disable_block_gas_limit`, any incoming call without this field would be limited to 30M gas, 
as you can see on line 1209 we try to get the requests gas field to setup the tx env, but its likely not there https://github.com/foundry-rs/foundry/blob/a592f7a9b93c7cc099341e6e9dfee3f2bb0b8748/crates/anvil/src/eth/backend/mem/mod.rs#L1205-L1231
so on line 1230 we set the tx.env.gas_limit to the block gas limit, however even when we set the`disable_block_gas_limit` flag, this block gas limit defaults to `30_000_000` as seen …

fix: #8759, default (low) gas limit set even when disabled, use custom gas_limit on forks

---

crates/evm/coverage/src/analysis.rs

potentially fix for #8957 (wasn't able to reproduce locally): determine source location start by using char_indices and avoid panic when slicing source

fix(coverage): better find of loc start byte position

---

crates/anvil/src/lib.rs
crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/gas.rs
crates/anvil/tests/it/proof.rs
crates/anvil/tests/it/traces.rs
crates/forge/tests/cli/config.rs

ref https://github.com/foundry-rs/foundry/pull/8946#pullrequestreview-2324741096

chore: fire shutdown signal on anvil node handle drop

---

crates/cheatcodes/spec/src/vm.rs
crates/evm/core/src/decode.rs

These are unreachable because `expectRevert*` selectors never appear in return data, so there is no point in checking for them.

chore(traces): remove unreachable decoding of expectRevert

---

crates/evm/evm/src/executors/invariant/shrink.rs
crates/forge/tests/it/invariant.rs

- fuzzed inputs rejected by `assume` are discarded during fuzz runs so they cannot end up in a failed sequence
https://github.com/foundry-rs/foundry/blob/9dbfb2f1115466b28f2697e158131f90df6b2590/crates/evm/evm/src/executors/invariant/mod.rs#L336-L338
- when a failed sequence is identified, it is shrunken and persisted to be replayed (by using the `check_sequence` fn)
- if a failed sequence is persisted and then replayed by a changed test driver (which introduce a new assume) then replay will fail in assume revert (and show up in traces) which is not desirable. Instead the sequence should be replayed and if no failure then move forward with new campaign.
Reproducible sample, starting from
```Solidity
contract ReplHandler is Test {
function fuzzMe(uint256 a) public {
require(a > 500, …
```

fix(`invariant`): replay should not fail for magic assume

---

crates/verify/src/retry.rs

bumps to 3mins, there's probably an argument to leave this uncapped, but 3min should be reasonable

chore: bump max allowed verification delay

---

Cargo.lock
Cargo.toml
crates/forge/bin/cmd/inspect.rs
crates/forge/tests/cli/cmd.rs

closes #8977 
Bump foundry compilers, add test for extra output (and file) check

fix(forge): generate `evm.legacyAssembly` extra output

---

crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/debug.rs
crates/forge/tests/cli/script.rs

Temporarily fixes flaky behavior of `tag` being displayed for failing CI as seen here: https://github.com/foundry-rs/foundry/actions/runs/11139687639/job/30956872092 to unblock the CI
Snapbox trips over space before `[..]` being included when installed with tag but not without
Related: https://github.com/foundry-rs/foundry/issues/7225
Related: https://github.com/foundry-rs/foundry/pull/8308
We are intending to pin to `forge-std` tagged releases but this doesn't work correctly I think, related to https://github.com/zerosnacks/foundry-bug-7225-repro - prioritizing https://github.com/foundry-rs/foundry/issues/7225 to fix it properly

fix(ci): flexibly handle forge-std being installed with tag or untagged

---

crates/wallets/src/multi_wallet.rs

Closes #9001 
Clarify that you should point to a keystore by its filename but it can be in a custom directory

docs: clarify keystore path should point to a filename

---

crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/utils.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/lib.rs
crates/evm/core/src/utils.rs
crates/evm/evm/src/inspectors/logs.rs
crates/evm/evm/src/inspectors/stack.rs

Unblocks and finishes https://github.com/foundry-rs/foundry/pull/8924
Was working on a fix for https://github.com/foundry-rs/foundry/issues/8971 and ended up with lifetime issues which should be avoidable after this PR
Looks like the main blocker is that when using `&mut dyn DatabaseExt` we end up needing to alter `'life` in `dyn InspectorExt<&'life mut dyn DatabaseExt>` in places where we recursively create EVMs. I don't think there's an easy way to express the covariance of inspector over DB lifetime via bounds, so we need some kind of trait which is able to produce inspectors for any db generic.
This PR adds a `get_inspector` fn to `InspectorExt` which allows to get `InspectorExt<&'b>` (basically just change the inner database lifetime). The impl is pretty much always just returns …

feat: use `dyn DatabaseExt`

---

crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/evm/fork.rs
crates/cheatcodes/src/evm/mock.rs
crates/cheatcodes/src/evm/prank.rs
crates/cheatcodes/src/fs.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/inspector/utils.rs
crates/cheatcodes/src/lib.rs
crates/cheatcodes/src/script.rs
crates/cheatcodes/src/test.rs
crates/cheatcodes/src/test/assert.rs
crates/cheatcodes/src/test/assume.rs
crates/cheatcodes/src/test/expect.rs
crates/cheatcodes/src/utils.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/lib.rs
crates/evm/core/src/utils.rs
crates/evm/evm/src/inspectors/logs.rs
crates/evm/evm/src/inspectors/stack.rs

Closes https://github.com/foundry-rs/foundry/issues/8404

chore: use dyn DatabaseExt everywhere

---

crates/forge/tests/cli/alphanet.rs

looks like running docker inside of macos runners is not supported https://github.com/orgs/community/discussions/69211#discussioncomment-7242133

fix: only test `--eof` on linux

---

crates/evm/core/src/backend/mod.rs
crates/forge/tests/cli/script.rs

Closes #8993 
- `transact_from_tx` throws `transact_from_tx: No `to` field found` if tx doesn't have to field set
- this conflicts with EIP-2470 https://eips.ethereum.org/EIPS/eip-2470#deployment-transaction
- if to is None then set as TxKind::Create

fix(cheatcodes): handle create2 deployer with broadcastRawTransaction

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/state.rs

Fixes #9017 
We were not setting the `best_hash` in storage after setting `best_number` leading to invalid `eth_getBlockByNumber` responses but valid `eth_blockNumber` responses.
Load all blocks and transactions to storage first then sets the `best_hash` and `best_block_number`

fix(`anvil`): set `storage.best_hash` while loading state

---

crates/cheatcodes/src/lib.rs

Move default trait methods from the trait to `impl dyn DynCheatcode` to reduce the size of the vtable.

chore: reduce size of DynCheatcode vtable

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/evm/fork.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/utils.rs

We already have a Tx -> revm::Env for cast, use this in vm.transact too
Also add missing EIP-4844 and EIP-7702 tx members

chore: unify tx env filling + add missing members

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil.rs

closes #9031
rf2822 panics with more than 4 digits

fix: handle large years

---

crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/eip712.rs
crates/forge/tests/cli/eip712.rs
crates/forge/tests/cli/main.rs

Closes https://github.com/foundry-rs/foundry/issues/9027
We didn't account for subtypes deeper than depth 1. Also, renames weren't applied correctly to struct names when appending subtypes to resulted string.

fix(`forge eip712`): fix handling of subtypes

---

crates/chisel/src/session_source.rs
crates/chisel/tests/cache.rs

Closes https://github.com/foundry-rs/foundry/issues/8978
Currently if latest installed solc is <0.8.18, running `chisel` would result in an error unless `chisel --evm-version london` is specified
There's no need in throwing this error. We already silently normalize EVM version during usual compilation, so for chisel this should be fine too

fix: normalize EVM version in chisel

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
testdata/cheats/Vm.sol

Closes: https://github.com/foundry-rs/foundry/issues/9043
Marks `vm.breakpoint` as `pure` as no EVM state is actually modified
Still using `apply_stateful` as we require the EVM state for the `&ccx.caller`
Relatively sure this won't have side effects but cc @DaniPopes to double check
Manually tested with the debugger to ensure there was no regression

fix(`cheatcodes`): mark `vm.breakpoint` as `pure` 

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/src/result.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/SimpleContractTestNonVerbose.json
crates/forge/tests/fixtures/SimpleContractTestVerbose.json

Closes: https://github.com/foundry-rs/foundry/issues/6922
Part of a larger meta-ticket: https://github.com/foundry-rs/foundry/issues/8794
Enable and includes traces in JSON output when `forge test` is ran with `--json` enabled (and verbosity >= 3)
Includes Snapbox tests
Future improvements could include making `TraceWriter` in `revm-inspectors` JSON compatible so we return decoded traces and well as https://github.com/foundry-rs/foundry/issues/7813 once that is added.
This should not impact the JUnit XML reports as that follows a strict schema already

fix: include `traces` field when running `forge test -vvvv --json`

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
testdata/cheats/Vm.sol
testdata/default/cheats/CloneAccount.t.sol

Closes #4893 
- add `copy_account` to `DatabaseExt` trait and reuse impl in `load_allocs`
- `cloneAccountCall` to copy account and mark target as persistent

feat(cheatcodes): add vm.cloneAccount() cheatcode

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/fees.rs

Closes: https://github.com/foundry-rs/foundry/issues/9033
Prefers a simple boolean flag to disable the enforcement rather than allowing the user to pass a priority fee of 0
Adds a new flag to disable min suggested priority fee: `--disable-min-priority-fee`
```
anvil --gas-price 0 --block-base-fee-per-gas 0 --disable-min-priority-fee
```
```
cast gas-price
```
Now yields `0` when the `--disable-min-priority-fee` is set
Without it still yields the `MIN_SUGGESTED_PRIORITY_FEE`:
https://github.com/foundry-rs/foundry/blob/eb046653de4047a27b181394338732e597965257/crates/anvil/src/eth/fees.rs#L36

fix(`anvil`): eth_gasPrice returned `1000000000` with `--block-base-fee-per-gas 0`, adds new `--disable-min-priority-fee` to return `0`

---

Cargo.lock
Cargo.toml
crates/forge/Cargo.toml
crates/forge/bin/cmd/soldeer.rs
crates/forge/bin/main.rs
crates/forge/tests/cli/soldeer.rs

We finally have the version 0.4.0 ready. 
In 0.4.0 we kinda did a rewrite to have it more rust idiomatic and solved also bugs that were waiting to be fixed.
https://github.com/mario-eth/soldeer/pull/202 
Full description of the release! 
Important mention:
we did split the project into 3 crates:
- cli - used only for `soldeer` alone
- commands - used for commands alone
- core - core crate
We did not publish the crates yet as we are waiting for feedback here beforehand.

feat: update to Soldeer v0.4.0

---

crates/evm/evm/src/executors/invariant/mod.rs
crates/forge/tests/it/invariant.rs

Closes #9054 
- atm in invariant tests we're committing the state of fuzzed selector, regardless it is a magic assume result
- assume rejections should discard the current fuzzed input and increment rejection counter but without modifying state (similar with a call that doesn't happen). Further more the assume input is popped from call sequence, so won't be available in a failed call sequence (still could change state)
- do not commit state if call result is MAGIC_ASSUME

fix(invariant): do not commit state if assume returns

---

Cargo.lock
crates/cast/Cargo.toml
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/evm/core/src/ic.rs

right now `cast disassemble` does not handle EOF opcodes and their immediate bytes
Reuse `immediate_size` helper from revm-inspectors (should we move it to revm?), and implement a native helper for decoding bytecode.

fix: support EOF opcodes in `cast da`

---

crates/evm/evm/src/executors/invariant/mod.rs
crates/forge/tests/it/invariant.rs

Closes #9066 
- do not add contract as fuzzed target if `targetSelector/excludeSelector` called with empty selectors

fix(`forge`): avoid panic when empty fuzz selectors in invariants

---

crates/evm/traces/src/decoder/mod.rs

Whilst it is generally recommended and easier to configure aliases in `foundry.toml` w/ an `.env` and reference by alias in the tests it can occur that a user directly passes an RPC URL. 
```toml
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
```
```solidity
vm.createSelectFork("mainnet");
```
Like private keys we should redact these fields if not referenced by alias to prevent leaking API keys in CIs
```solidity
vm.createSelectFork("https://eth-mainnet.g.alchemy.com/v2/api-key");
```
should render as
```
<rpc url>
```
Closes: https://github.com/foundry-rs/foundry/issues/9069
Example output (redacted by API key):
```solidity
function test_rpc_urls() public {
vm.createFork("https://eth-mainnet.g.alchemy.com/v2/api-key");
vm.createFork("https://eth-mainnet.g.alchemy.com/v2/api-key", …
```

fix: redact RPC URLs in traces if URL is passed in directly

---

crates/cli/src/utils/mod.rs
crates/forge/tests/cli/cmd.rs

Some people just ignore the message if it's too long and decide to go on telegram and ask people to read it to them instead

chore: reduce length of a common error message

---

Dockerfile

Get latest stable alpine version in Dockerfile.
Bump alpine version to `3.20.3`

feat: bump alpine to `3.20.3`

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/crypto.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs
testdata/cheats/Vm.sol

Closes #8225 + Closes https://github.com/foundry-rs/foundry/issues/7950
Introduces cheatcodes to derive and save multiple wallets/signers in the script env. 
```solidity
function rememberKeys(string calldata mnemonic, string calldata derivationPath, uint32 count) external returns (address[] memory keyAddrs);
function rememberKeys(string calldata mnemonic, string calldata derivationPath, string calldata language, uint32 count) external returns (address[] memory keyAddrs);
```
Under the hood these cheatcodes save the derived wallets in `ScriptWallets` such that they are persisted throughout the script environment.
Moreover, to aid in the testing of scripts (as in `forge test DeployScript.t.sol`) these cheatcodes will initialize `ScriptWallets` in the `CheatsConfig` if not already …

feat(`cheatcodes`): vm.rememberKeys

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/config.rs
crates/cheatcodes/src/crypto.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/lib.rs
crates/cheatcodes/src/script.rs
crates/chisel/src/executor.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/src/multi_runner.rs
crates/forge/tests/cli/script.rs
crates/script/src/broadcast.rs
crates/script/src/build.rs
crates/script/src/execute.rs
crates/script/src/lib.rs
crates/script/src/simulate.rs
testdata/cheats/Vm.sol

refactor(`cheatcodes`): mv `ScriptWallets` into `Cheatcode`

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/Repros/fmt.sol
crates/fmt/testdata/Repros/original.sol

Closes #9113 
- handle case when no named parameter passed

fix(fmt): do not panic when no named arg

---

Cargo.lock
crates/cast/bin/tx.rs
crates/cli/Cargo.toml
crates/cli/src/opts/transaction.rs
crates/cli/src/utils/mod.rs

Right now for read-only requests we skip both `--access-list` and `--auth` making it impossible to call `eth_call` or `eth_estimateGas` with those
Reorder things a bit and respect those flags. Also moved the parsing logic to cli crate.

fix: respect `--auth` in `cast call` and `cast estimate`

---

crates/forge/bin/cmd/compiler.rs
crates/forge/tests/cli/compiler.rs

closes #9125 
- show max supported EVM version when running `forge compiler resolve -v` 
- start from default and normalize on solc version
- for vyper will always show default evm version
- tests redacted as evm default version is a moving target

feat(forge): add max supported EVM version in compiler -vv

---

crates/cast/bin/main.rs
crates/cast/tests/cli/main.rs

- attempts to use `cast hm` to create flashbot sig failed, eventually used `chisel eval` to generate such
```bash
chisel eval 'keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n66","'$payload_keccak'"))'
```
https://github.com/pcaversaccio/white-hat-frontrunning/blob/main/go.sh#L62
- fix cast to not hex decode message to hash but use it as it is to create EIP-191 final message `"\x19Ethereum Signed Message:\n" + message. length + message` which is then hashed

fix(cast): do not strip 0x / hex decode message before EIP-191 hashing

---

crates/anvil/core/src/eth/mod.rs

`wallet_sendTransaction` is not part of the EIP-5792 spec. 
Alias it as `odyssey_sendTransaction`, preparing `wallet_sendTransaction` for removal soon

chore: alias wallet_sendTransaction

---

crates/cast/bin/cmd/wallet/mod.rs
crates/cast/tests/cli/main.rs

Closes #9138 
```bash
$ castdev wallet new-mnemonic --entropy 0xdf9bf37e6fcdf9bf37e6fcdf9bf37e3c --accounts 3 --json
[
{
"mnemonic": "test test test test test test test test test test test junk",
"accounts": [
{
"address": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
"private_key": "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
},
{
"address": "0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
"private_key": "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
},
{
"address": "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc",
"private_key": "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
}
]
}
]
```
```bash
$ castdev wallet new-mnemonic --entropy 0xdf9bf37e6fcdf9bf37e6fcdf9bf37e3c --accounts 3 --json | jq '.[0].mnemonic'
"test test test …
```

feat(cast): add `json` flag in `cast wallet new-mnemonic`

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/fork.rs

Closes #9152 
While mining blocks on arbitrum forks set the `env.block.number` using `storage.best_number` as `env.block.number` actually represents `l1BlockNumber` and not the arbitrum block number.

fix(`anvil`): arb fork mining

---

crates/cheatcodes/src/error.rs

Closes #8908 
follow up on https://github.com/foundry-rs/foundry/pull/8936#pullrequestreview-2321724224 not sure what's the best solution here but I hit this while doing some tests, the issue is with wrapped errors that are not displaying entirely when failed from cheatcodes and propagated to test result, https://github.com/foundry-rs/foundry/pull/8936 could be a better solution as will handle all other cases if any...
- with this approach:
- with https://github.com/foundry-rs/foundry/pull/8936 approach
- current
@yash-atreya @mattsse @klkvr

fix(cheatcodes): improve fork cheatcodes messages

---

crates/anvil/src/eth/backend/time.rs
crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/fork.rs

Closes #9142 + Closes #7931 
Replace the check `next_timestamp <= last_timestamp` with `next_timestamp < last_timestamp`. 
Anvil can now mine blocks with the same timestamp as the previous block timestamp. This aids in running forks or testing chains that have sub-second block times, wherein `block.timestamp` stays constant until exactly one second has passed. 
Added relevant tests.

feat(`anvil`): support mining with same block.timestamp

---

crates/evm/evm/src/executors/mod.rs
crates/forge/tests/cli/script.rs

in #9161 message presented to user was
```
Error:
Failed to deploy script:
backend: failed while inspecting
```
then foundry code was looked up to figure out it was failing with `Header(PrevrandaoNotSet)`
- chain EvmError messages, add test

chore: format chained error for EvmError

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/traces.rs

State overrides are very useful when trying to simulate transactions. However, the `debug_traceCall` implementation did not apply the provided state overrides.
The solution was to apply the state overrides similarly to the `eth_call` logic. I've also included a small test to verify that the patch is effective.

fix(anvil): Apply state overrides in debug_traceCall

---

crates/config/src/fmt.rs
crates/fmt/src/formatter.rs
crates/fmt/testdata/FunctionDefinition/all-params.fmt.sol

Closes #9173 
- for backward compatibility reasons `multiline_func_header="all` fmt does not write single params on new line (at param level there's `params_first` which writes on new line regardless number of params and `params_first_multi` which writes only multi params on new lines)
- add a new config `multiline_func_header="all_params` to write params on new lines even if there's a single param (adding such won't break existing formatters)

feat(fmt): add `all_params` config - same as `all` but split single param too

---

crates/chisel/src/dispatcher.rs

Closes #4393 
- exit with command failed only on failures: show traces and failed are handled in same branch 
https://github.com/foundry-rs/foundry/blob/2044faec64f99a21f0e5f0094458a973612d0712/crates/chisel/src/dispatcher.rs#L704
and both results now in command failed as `failed` bool is not checked
https://github.com/foundry-rs/foundry/blob/2044faec64f99a21f0e5f0094458a973612d0712/crates/chisel/src/dispatcher.rs#L722-L726

fix(chisel): on edit fail command only if execution failed

---

crates/common/src/io/shell.rs

Inline won't matter for performance, we're locking a mutex and syscalling

chore: cleanup shell module

---

crates/evm/core/src/backend/mod.rs

Closes #9184 
Temp fix
Set the revm `env` specId to `Cancun` if the tx has blob hashes.

fix(`evm`): detect blob tx and set evm version

---

crates/evm/core/src/backend/mod.rs

`blob_excess_gas_and_price` was not being set. 
Set it if `block.header.excess_blob_gas` is present.

fix(`evm`): set blob_excess_gas_and_price

---

Makefile
crates/cast/bin/cmd/access_list.rs
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/create2.rs
crates/cast/bin/cmd/estimate.rs
crates/cast/bin/cmd/find_block.rs
crates/cast/bin/cmd/interface.rs
crates/cast/bin/cmd/logs.rs
crates/cast/bin/cmd/mktx.rs
crates/cast/bin/cmd/rpc.rs
crates/cast/bin/cmd/run.rs
crates/cast/bin/cmd/send.rs
crates/cast/bin/cmd/storage.rs
crates/cast/bin/cmd/wallet/list.rs
crates/cast/bin/cmd/wallet/mod.rs
crates/cast/bin/cmd/wallet/vanity.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/cast/src/rlp_converter.rs

Enforces `common::shell` as added in https://github.com/foundry-rs/foundry/pull/9109 for the `cast` binary
Splits out the enforcement of the common shell per binary / large crate to avoid huge diffs making reviews easier

chore(`cast`): enforce `common::shell` for cast binary

---

crates/cli/src/utils/cmd.rs

Etherlink is an EVM-compatible L2 running on Tezos. As some other EVM-compatible chains, it has a specific gas computation, hence `forge script` will fail to inject transactions as they gas computed internally is different (and generally not enough).
Following other chains that have a different gas calculation, `Etherlink` and `EtherlinkTestnet` are added as exception to force gas estimation from the node.

fix(cli): etherlink needs eth_estimateGas for gas calculation

---

crates/fmt/src/formatter.rs
crates/fmt/testdata/FunctionDefinition/all-params.fmt.sol

Follow-up for #9176. Spec is defined in https://github.com/foundry-rs/foundry/pull/9176#discussion_r1814710251
- When `all_params` is selected, multiline the single parameter only when the full function definition takes more than a single line (i.e. multilined).

fix(fmt): multiline single param only if func definition is multiline for `all_params`

---

crates/chisel/bin/main.rs
crates/chisel/src/dispatcher.rs
crates/chisel/src/executor.rs
crates/chisel/src/lib.rs
crates/chisel/src/session_source.rs

Enforces `common::shell` as added in https://github.com/foundry-rs/foundry/pull/9109 for the `chisel` binary
Splits out the enforcement of the common shell per binary / large crate to avoid huge diffs making reviews easier

chore(`chisel`): enforce `common::shell` for chisel binary

---

crates/anvil/core/src/eth/transaction/mod.rs

Closes: https://github.com/foundry-rs/foundry/issues/9194
Mark legacy transaction type as `0x0` or `Some(0)` rather than `None`
This is in line with how Alloy marks legacy transactions
Steps to test:
```
1. make build
2. ./target/debug/anvil --block-time 12 --port 8545 --fork-url <SEPOLIA_API_KEY>
```
In other window send a new transaction w/ default Anvil keys):
```
3. cast send 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 0x --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --legacy
4. cast tx <TX_HASH> --json | jq
```
To verify the fix run step 2 with latest `anvil` install
Will now correctly yield:
```json
{
"hash": "0x4dd5234b264e33221ef96a782163da179dcdc86a33f36f368aff8464ff17baa8",
"nonce": "0x2f9a",
"blockHash": …
```

fix(`anvil`): tag newly created legacy transactions on shadow fork as `Some(0)` (`0x0`) rather than `None`

---

crates/anvil/core/src/eth/block.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/storage.rs

ref https://github.com/foundry-rs/foundry/issues/9198#issuecomment-2439707092
Right now `parent_beacon_block_root`, `withdrawals_root` and `requests_hash` are always being set to `None`. They are indeed always empty but we should set empty values if corresponding hardfork is enabled.

fix(anvil): correctly set hardfork-specific block fields

---

Cargo.lock
crates/forge/Cargo.toml
crates/forge/tests/cli/script.rs
crates/script/src/transaction.rs

Closes https://github.com/foundry-rs/foundry/issues/9204
Right now we are detecting additional contracts but never add them to the transaction

fix(script): correctly detect additional contracts

---

crates/cast/tests/cli/main.rs
crates/common/fmt/src/ui.rs

Right now we are not printing some of the cancun and prague fields

fix(`cast block`): ensure to print all fields

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs

feat(cast): add --int flag to from-rlp

---

crates/cli/src/opts/dependency.rs
crates/forge/bin/cmd/install.rs

Closes #5996 
Right now is hard to determine what `@` is used to delimiter (if org, ref, etc.)
Introduce `@tag=` `@branch=` `@rev=` to specify ref type (and be able to handle `/` in tag / branch name without changing current behavior)

feat(`forge install`): add `@tag=` `@branch=` `@rev=` specific refs

---

crates/forge/bin/cmd/create.rs

Closes #9219 
I am not sure if any good reason to create `forge_verify::VerifyArgs` with `skip_is_verified_check: false` for `forge create`
https://github.com/foundry-rs/foundry/blob/a428ba6ad8856611339a6319290aade3347d25d9/crates/forge/bin/cmd/create.rs#L353
when in `get_verify_args` fn they are set to true
https://github.com/foundry-rs/foundry/blob/a428ba6ad8856611339a6319290aade3347d25d9/crates/script/src/verify.rs#L149
changing this for consistency and to solve the issue where `forge create` always prints "is already verified. Skipping verification." without performing verification. @klkvr @yash-atreya can you please chime in?

fix(forge create): set skip_is_verified_check: true

---

crates/forge/bin/cmd/create.rs

replace if let some with transpose and unwrap_or

style: smol refactor

---

crates/forge/src/gas_report.rs
crates/forge/tests/cli/cmd.rs

Per feedback: https://github.com/foundry-rs/foundry/pull/9216#issuecomment-2445386251
I had originally not included the empty signature as it differs from the regular `--gas-report` Markdown output
Looks as follows after passing through `| jq`:
It does not render `pretty` formatted in the terminal by itself
```json
[
{
"contract": "src/Contracts.sol:ContractOne",
"deployment": {
"gas": 103375,
"size": 255
},
"functions": {
"foo()": {
"calls": 1,
"min": 45387,
"mean": 45387,
"median": 45387,
"max": 45387
}
}
},
{
"contract": "src/Contracts.sol:ContractThree",
"deployment": {
"gas": 103591,
"size": 256
},
"functions": {
"baz()": {
"calls": 1,
"min": 260712,
"mean": 260712,
"median": 260712,
"max": 260712
}
}
},
{
"contract": "src/Contracts.sol:ContractTwo",
"deployment": {
"gas": 103375, …
```

fix(`--gas-report`): add back signatures, even if empty, avoid nesting multiple selectors

---

crates/anvil/src/eth/backend/fork.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/state.rs

Closes #9053 + Closes https://github.com/foundry-rs/foundry/issues/8493
This arises when `--fork-url` and `--load-state` are used together.
- ~Introduce `account_at` in `ForkedStorage` which stores the state of accounts at specific block numbers.~
- ~Populate `account_at` using the provided state file.~ 
Solution is a lot simpler.
- We are correctly loading the data to the db: https://github.com/foundry-rs/foundry/blob/4012adefd376bd618d1348398c1da07224d2dace/crates/anvil/src/eth/backend/mem/mod.rs#L925
- However, the `storage.best_number` i.e head of the chain is not correctly set when `--load-state` is used with `--fork-url`. We continue to set `storage.best_number = state.block.number` which is incorrect as the `best_number` should be `fork_block_number`. 
- This issue is observed when …

fix(`anvil`): set `storage.best_number` correctly

---

crates/cheatcodes/src/evm.rs

ref https://t.me/foundry_support/57540
right now all recorded steps stay in memory until the end of tests execution which is not neccesarry

fix: remove steps after steps tracing cheatcodes are done

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/tests/cli/main.rs

When I'm debugging some transactions that we reverted, what I got from the tx's trace as below:
```json
{
"from": "0x7567d83b7b8d80addcb281a71d54fc7b3364ffed",
"gas": "0x0",
"gasUsed": "0x0",
"to": "0x5ff0bea4603b68c7e80b8a973a666b9840db248c",
"input": "0x6a76120200000000000000000000000034053113b5ddc6fb368e4d028c1bbbcb85c14ef1...",
"output": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303235000000000000000000000000000000000000000000000000000000",
"error": "execution reverted",
"calls": [
{
"from": "0x5ff0bea4603b68c7e80b8a973a666b9840db248c",
"gas": "0xbbf0",
"gasUsed": "0x24cc",
"to": "0x632cd990566bc2cc888f75c9bbe8b9185a91d24d",
"input": …
```

feat(cast): add string-decode to decode string

---

crates/script/src/simulate.rs

This small section seems to have some leftover unnecessary `mut`, even tho no field of `transaction` is changed. 
I believe this was not removed after [moving `ScriptSequence`](https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description)
Cleanup `mut` qualifier and related `tx_mut()` method usage in favor of `tx()`

chore: avoid unnecessary `mut`

---

crates/anvil/src/eth/api.rs
crates/anvil/tests/it/anvil_api.rs
crates/cast/src/lib.rs

Closes #8962 
- when `anvil_mine` jump to next timestamp before mining new block so the timestamp of first block mined respect interval

fix(anvil): on anvil_mine jump to next timestamp before mine new block

---

crates/common/src/io/shell.rs

Formatting a style with `:#` (alternate format) emits the reset code for the style, or nothing if the style is empty.
Should close https://github.com/foundry-rs/foundry/issues/9240, but I couldn't reproduce.

fix: reset shell colors based on the input style

---

crates/common/src/io/macros.rs
crates/common/src/io/shell.rs

cc @zerosnacks  https://github.com/foundry-rs/foundry/pull/9244#discussion_r1825804403

fix: avoid deadlock in nested shell calls

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs

Some fields were missing for some HF, leading to an invalid Genesis block hash.
This is linked to https://github.com/foundry-rs/foundry/pull/9202

anvil: Correctly set HF fields for Genesis block

---

crates/common/src/provider/mod.rs

when we create the provider for cast, we don't necessarily know the chain (no foundry.toml) in which case we'd default to mainnet settings.
so for cast send this would always set a poll interval of ~7s which is not useful.
this now caps to `3s * 0.6` which should improve UX for all chains ~3s blocktime

perf: cap default poll interval

---

crates/script/src/receipts.rs

ref https://github.com/foundry-rs/foundry/issues/9239
we should only continue trying if we've got a timeout, all other errors (like deser error) should be fatal

fix: better error handling when waiting for receipt

---

crates/anvil/src/anvil.rs
crates/cast/bin/main.rs
crates/chisel/bin/main.rs
crates/cli/src/handler.rs
crates/common/src/io/shell.rs
crates/forge/bin/main.rs

`Display` might not include complete context for errors. e.g eyre's `wrap_err` only includes top-level message in `Display` impl. `cargo run` uses `Debug` when formatting errors from `main` as well

fix: use `Debug` when formatting errors

---

crates/doc/src/parser/comment.rs
crates/doc/src/writer/as_doc.rs

Display custom natspec tag when generating documentation with `forge doc`.
- Follow up of #9075.
- Address this [comment](https://github.com/foundry-rs/foundry/pull/9075#issuecomment-2451451919).
Custom natspec comments are now preceded by their tag.

fix(`forge doc`): display custom natspec tag

---

crates/cast/bin/args.rs
crates/cast/bin/cmd/access_list.rs
crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/create2.rs
crates/cast/bin/cmd/interface.rs
crates/cast/bin/cmd/logs.rs
crates/cast/bin/cmd/send.rs
crates/cast/bin/cmd/wallet/mod.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/cast/tests/cli/main.rs
crates/cli/src/opts/shell.rs
crates/common/src/io/shell.rs
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/create.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/main.rs
crates/forge/tests/cli/build.rs
crates/forge/tests/cli/cmd.rs
crates/script/src/lib.rs
crates/verify/src/bytecode.rs
crates/verify/src/utils.rs

Related: https://github.com/foundry-rs/foundry/issues/8794
Adds a global `--json` flag on the `Shell` level
Ideally we would have a `FormatChoice` similar to `ColorChoice` but to avoid breaking changes the current approach is preferred.
Whilst JSON output is currently not supported everywhere this makes it easier to support it going forward. A future PR aims to correct the flag compatibility for all arguments making support / non-support explicit to the user.

feat: add global `--json` flag

---

clippy.toml
crates/cast/bin/cmd/create2.rs
crates/forge/bin/cmd/bind.rs
crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/cache.rs
crates/forge/bin/cmd/clone.rs
crates/forge/bin/cmd/compiler.rs
crates/forge/bin/cmd/create.rs
crates/forge/bin/cmd/doc/server.rs
crates/forge/bin/cmd/eip712.rs
crates/forge/bin/cmd/flatten.rs
crates/forge/bin/cmd/fmt.rs
crates/forge/bin/cmd/geiger/mod.rs
crates/forge/bin/cmd/generate/mod.rs
crates/forge/bin/cmd/inspect.rs
crates/forge/bin/cmd/install.rs
crates/forge/bin/cmd/remappings.rs
crates/forge/bin/cmd/remove.rs
crates/forge/bin/cmd/selectors.rs
crates/forge/bin/cmd/snapshot.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/cmd/test/summary.rs
crates/forge/bin/cmd/watch.rs
crates/forge/src/coverage.rs
crates/forge/src/gas_report.rs
crates/forge/src/progress.rs
crates/forge/src/result.rs
crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/verify.rs
crates/test-utils/src/macros.rs

Enforces `common::shell` as added in https://github.com/foundry-rs/foundry/pull/9109 for the `forge` crate
Includes minor fix preferring prepending / appending `\n` in favor of an empty `sh_println!()`
Adds `#[allow(clippy::disallowed_macros)]` to test macros as preparation for enabled clippy enforcement allow you to still use `println`, etc.. in tests. In some specific cases you may need to add  `#[allow(clippy::disallowed_macros)]` above helpers.
Splits out the enforcement of the common shell per binary / large crate to avoid huge diffs making reviews easier

chore(`forge`): enforce `common::shell` for `forge` crate

---

crates/config/src/providers/remappings.rs
crates/forge/tests/cli/config.rs

Closes #9146 
check if name of new remapping to be added starts with existing remapping name instead the other way around
e.g. if `@utils` remapping is already added in proj root then `@utils/libraries` from lib should not be added

fix(remappings): check if remapping to add starts with existing remapping name

---

crates/anvil/src/cmd.rs

The alias of `auto-impersonate` is no diff of the original value:
```bash
$ anvil --help 
--auto-impersonate
Enable autoImpersonate on startup
[aliases: auto-impersonate]
```
And as `--unlocked` has different meanings in `cast`(ref https://github.com/foundry-rs/foundry/pull/5335#discussion_r1257186166)
So let's add `auto-unlock` as an alias of this argument.

fix(anvil): set auto-unlock an alias of auto-impersonate

---

crates/config/src/providers/remappings.rs
crates/forge/tests/cli/config.rs

This reverts commit 455ba9b1b736766232d84ba1790ac9ba6ca944de.
Fix added in https://github.com/foundry-rs/foundry/pull/9246 affects existing projects compilation 
The changed code (checking remappings to add against existing) doesn't account scenario where `@openzeppelin/contracts` is already added and `@openzeppelin/contracts-upgradeable` remapping will be discarded (as remapping to add name starts with existing)
Revert and investigate failures
Closes #9271
Closes #9272

Revert "fix(remappings): check if remapping to add starts with existing remapping name (#9246)"

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/test_cmd.rs

Closes #9285
- when persisting test failures there's no check if failure is a test kind, hence `setUp` is also recorded
- check if function is test when recording failure to rerun. if there are tests failing due to setup failure then they'll be recorded and replayed, if they don't depend on setup then won't fail and won't be replayed

fix(`forge test`): record only test fns in test failures

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Closes #9270 
- do not count empty constructor as coverage function
- receive anchor can now properly found, enable coverage report for
- tests

fix(coverage): do not report empty constructors, enable reports for `receive`

---

crates/forge/tests/cli/cmd.rs
crates/script/src/receipts.rs
crates/test-utils/src/util.rs

The `common::shell` interferes with `cargo test`. In internals like this it is fine to add an exception. Instead of rendering to `stderr` we render to regular `stdout` as this is collected and presented to the user at the end as a built-in.
Previously:
```
initializing /tmp/gas_report_with_fallback-0HtVf2k
- initializing template dir in /tmp/template-1hIkWtV
executing cd "/tmp/template-1hIkWtV" && NO_COLOR="1" "/home/george/work/foundry/target/debug/forge" "init" "--force"
executing cd "/tmp/template-1hIkWtV" && NO_COLOR="1" "/home/george/work/foundry/target/debug/forge" "build" "--use" "0.8.27"
- copying template dir from /tmp/foundry-forge-test-template
executing cd "/tmp/gas_report_with_fallback-0HtVf2k" && NO_COLOR="1" "/home/george/work/foundry/target/debug/forge" "test" "--mt" …
```

fix: use regular `println` in internal test utils to avoid interfering with `cargo test` runner

---

crates/cast/bin/cmd/run.rs
crates/cast/tests/cli/main.rs
crates/evm/core/src/opts.rs
crates/test-utils/src/rpc.rs

Closes #3473 
- fix `get_remote_chain_id`: do not assume mainnet chain if `mainnet` in RPC URL (Alchemy has `opt-mainnet`, `arb-mainnet` etc.)
- add `--etherscan-api-key` for `cast run`
- test

 feat(`cast run`): add `--etherscan-api-key`  to resolve contract names

---

crates/cast/bin/args.rs
crates/cast/bin/cmd/artifact.rs
crates/cast/bin/cmd/constructor_args.rs
crates/cast/bin/cmd/creation_code.rs
crates/cast/bin/cmd/mod.rs
crates/cast/bin/main.rs
crates/cast/tests/cli/main.rs

Building up on https://github.com/foundry-rs/foundry/pull/9029 , this PR adds `artifact` method. It produces a JSON file that can be used with `sol!` macro to deploy contracts locally.
```
cast artifact 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --etherscan-api-key $API_KEY --rpc-url $ETH_RPC_URL -o weth.json
```

feat(cast): add artifact method

---

crates/evm/core/src/backend/mod.rs
crates/forge/tests/cli/test_cmd.rs

Closes #9297 
- if no `excess_blob_gas` header then don't update env block `block.blob_excess_gas_and_price`
- @zerosnacks @yash-atreya @klkvr this change pass tests but not sure if there are other side effects

fix(fork): set block blob_excess_gas_and_price only if `excess_blob_gas header` is Some

---

crates/evm/core/src/decode.rs

ref https://t.me/foundry_rs/37822
Don't think custom errors data could be too big for needed to be trimmed and this could be helpful in cases like attached ref, e.g.
instead

chore: do not trim decoded generic custom error

---

crates/forge/src/gas_report.rs
crates/forge/tests/cli/cmd.rs

Closes #9300 
re https://github.com/foundry-rs/foundry/pull/9301#issuecomment-2472860010
- always add contract deployment size (should record sizes for for contracts created in nested calls as well)

fix(forge): always report deployment size in gas reports

---

crates/forge/bin/cmd/eip712.rs
crates/forge/tests/cli/eip712.rs

fix(`forge eip712`): handle recursive types

---

crates/forge/bin/cmd/build.rs
crates/forge/tests/cli/cmd.rs

Closes #9304 
Opted to fail (instead warn) if no source file matches provided build paths

feat(forge build): err if no source file in specified paths

---

crates/common/Cargo.toml
crates/common/src/compile.rs
crates/common/src/lib.rs
crates/common/src/reports.rs
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/src/gas_report.rs
crates/forge/tests/cli/build.rs
crates/forge/tests/cli/cmd.rs

Related: https://github.com/foundry-rs/foundry/issues/8794
- Adds JSON compatible outputs + tests
- Generalizes report type in `foundry::common` between SizeReport / GasReport (and other future reports)

feat(`forge build`): add `--sizes` and `--names` JSON compatibility

---

crates/forge/tests/cli/build.rs
crates/forge/tests/cli/cmd.rs

update new tests added for cancun PR
Fixes new tests that were not picked up in https://github.com/foundry-rs/foundry/pull/9131

chore: update test values to cancun

---

crates/sol-macro-gen/src/sol_macro_gen.rs

Debugging https://github.com/foundry-rs/foundry/issues/5847

chore: add some more debugging to forge bind

---

crates/forge/src/runner.rs
crates/forge/tests/it/core.rs

These errors are shown as part of `setUp` in the logs anyway

chore: remove redundant 'setup failed' in setup errors

---

crates/config/src/resolve.rs
testdata/default/cheats/RpcUrls.t.sol

Before: ``[FAIL: setup failed: vm.createSelectFork: Failed to resolve env var `ETH_NODE_URI_MAINNET` in `${ETH_NODE_URI_MAINNET}`: environment variable not found] setUp() (gas: 0)``
After: ``[FAIL: setup failed: vm.createSelectFork: environment variable `ETH_NODE_URI_MAINNET` not found] setUp() (gas: 0)``

chore: make environment variable error nicer

---

crates/test-utils/src/rpc.rs

- use `next()` fn to pick up a provider url by index

chore: pick provider urls by next index

---

foundryup/install

**Description:**
This pull request addresses a small issue in the script where there was a typographical error in the line:
```bash
FOUNDRY_DIR="${FOUNDRY_DIR-"$BASE_DIR/.foundry"}"
```
The correct syntax for setting a default value using parameter expansion should be:
```bash
FOUNDRY_DIR="${FOUNDRY_DIR:-"$BASE_DIR/.foundry"}"
```
- The original code incorrectly used `{"` instead of `:-`, which is the correct syntax for default value assignment in Bash parameter expansion.
- This error would prevent the script from correctly setting the `FOUNDRY_DIR` variable if it wasn't previously defined.
- The fix ensures that if `FOUNDRY_DIR` is not set, it will default to `"$BASE_DIR/.foundry"`, which is the intended behavior.
By correcting this, the script now functions as expected, ensuring proper …

fix: correct shell substitution in installer

---

.github/workflows/test.yml
crates/test-utils/src/rpc.rs

- inherit secrets in nextest workflow
- remove unusable keys
- secrets are not available on external PRs, use alchemy as default

chore(ci): proper read of archive nodes

---

Cargo.lock
crates/cast/bin/cmd/create2.rs
crates/cast/tests/cli/main.rs
crates/cli/Cargo.toml
crates/cli/src/opts/global.rs
crates/config/README.md
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/cmd.rs
crates/script/src/lib.rs

Closes https://github.com/foundry-rs/foundry/issues/8408

feat: add global -j, --threads

---

crates/common/src/transactions.rs
crates/forge/tests/cli/script.rs
crates/script/src/broadcast.rs

We should not require signers for presigned transactions

fix: `vm.broadcastRawTransaction`

---

crates/config/src/lib.rs
crates/forge/bin/cmd/test/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/9375
With #8668 we now resolve the `Graph` when creating project as we need data about all sources for restrictions. This caused `forge test` to fail in CI if there are any missing dependencies which were being installed only after call to `config.project()`
This PR changes order of operations so that we always install dependencies first. Also I've added an optimization to skip graph resolution if user did not specify any restrictions

fix(forge test): install missing dependencies before creating `Project`

---

Cargo.lock
Cargo.toml
crates/chisel/Cargo.toml
crates/chisel/src/dispatcher.rs
crates/chisel/src/executor.rs
crates/chisel/src/solidity_helper.rs

Ref https://github.com/foundry-rs/foundry/issues/9317

chore(chisel): replace solang with solar in SolidityHelper

---

crates/chisel/src/executor.rs

fix(chisel): uint/int full word print

---

crates/cast/src/lib.rs
crates/evm/core/src/ic.rs

This PR fixes #9389
Use `Result` to handle oob.

fix: bail incomplete bytecode sequence disassemble

---

crates/verify/src/verify.rs

Closes #4555 
- display Compiler version, Optimisations and Constructor args (if any) of the contract to be verified

feat(forge): show additional details of contract to verify

---

crates/common/src/evm.rs

Closes: https://github.com/foundry-rs/foundry/issues/4693
Declared as visible alias for backwards compatibility
Also mirrors 
```rust
#[arg(long, visible_alias = "no-gas-limit")]
pub disable_block_gas_limit: bool,
```

fix: remove duplicate `gas_limit` / `block_gas_limit` field, declare as alias

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/tests/cli/main.rs

Closes #6511 
Makes consistent `decode-` naming, keeping existing as aliases

feat(cast): add decode-event sig data

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/anchors.rs
crates/evm/coverage/src/lib.rs
crates/forge/bin/cmd/coverage.rs
crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs

Ref: https://github.com/foundry-rs/foundry/pull/9366#issuecomment-2498169059
- Introduces `SourceIdentifier` which wraps both `build_id` and `source_id`.
- `SourceIdentifier` replaces `source_id` as a key identifier for source files in report and analysis.

fix(`coverage`): account for `build_id` in source identification 

---

crates/chisel/bin/main.rs
crates/forge/bin/cmd/config.rs
crates/forge/bin/cmd/debug.rs
crates/forge/bin/cmd/mod.rs
crates/forge/bin/cmd/test/mod.rs
crates/script/src/execute.rs
crates/script/src/lib.rs

We have `EvmArgs` and `EvmOpts` struct, so rename `evm_opts: EvmArgs` to `evm_args: EvmArgs`, make the code more readable.

chore: rename the arg name of EvmOpts from evm_opts to evm_args

---

foundryup/install

This pull request addresses a minor but important syntax issue in the conditional statement used to check for the presence of `libusb` on macOS. Specifically, the original condition:
```bash
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
```
contains a logical expression within a single pair of square brackets `[[ ... ]]` that includes two independent checks joined by `&&`. This can potentially lead to incorrect interpretation or unexpected behavior.
The `[[ ... ]]` syntax in bash doesn't support nested square brackets directly. The correct approach is to separate the two conditions into individual `[[ ... ]]` blocks for clarity and to ensure they are evaluated independently.
The …

Fix conditional syntax issue in macOS libusb check

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/cli/src/utils/cmd.rs

Follow-up for https://github.com/foundry-rs/foundry/pull/9430, can be merged before or after
Use the `alloy-chains` `is_arbitrum` built-in
Follow-up for https://github.com/foundry-rs/foundry/pull/9430/files#diff-a0d1dbafd7eaf82b3fd4d30722d2c7e369394883a704e8b41554d0a31b43629f to use `is_arbitrum` consistently

chore: use alloy-chains' `is_arbitrum`

---

crates/cast/bin/cmd/call.rs
crates/cast/bin/cmd/run.rs
crates/cheatcodes/src/inspector.rs
crates/common/src/evm.rs
crates/config/src/lib.rs
crates/evm/core/src/constants.rs
crates/evm/core/src/lib.rs
crates/evm/core/src/opts.rs
crates/evm/core/src/utils.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/executors/trace.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/src/multi_runner.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/script.rs
crates/script/src/build.rs
crates/script/src/lib.rs
crates/script/src/runner.rs
crates/script/src/simulate.rs
crates/script/src/transaction.rs
crates/test-utils/src/script.rs
crates/verify/src/utils.rs
testdata/default/cheats/Broadcast.t.sol

Currently when deploy contracts using CREATE2 method, it is default to https://github.com/foundry-rs/foundry/blob/fcaa2a7dc4212c270e7c6a40e88948c42c136a5f/crates/evm/core/src/constants.rs#L44
But in some circumstances, we can't access or deploy the 0x4e59b44847b379578588920ca78fbf26c0b4956c contract, may be caused of not able to send the pre EIP155 raw transaction. So try to introduce a env to change the default create2 deployer.
1. add `--create2-deployer` to the `forge script` argument
2. add `create2_deployer` to the `foundry.toml` config file

feat(script): support custom create2 deployer

---

Cargo.lock
crates/evm/coverage/src/analysis.rs
crates/forge/bin/cmd/coverage.rs
crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs
crates/test-utils/Cargo.toml
crates/test-utils/src/util.rs

`fallback`, `receive`, and `constructor` have an empty `name` in the AST. Use the `kind` as the name instead.

fix(coverage): special functions have no name

---

crates/cheatcodes/src/config.rs
crates/cli/src/opts/build/core.rs
crates/cli/src/utils/mod.rs
crates/config/src/lib.rs
crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/doc/mod.rs
crates/forge/bin/cmd/fmt.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/cmd/update.rs
crates/forge/bin/cmd/watch.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/it/repros.rs
crates/script/src/simulate.rs

Unnecessary wrapper which causes unnecessary churn everywhere.

chore(config): remove RootPath

---

Cargo.lock
crates/cheatcodes/src/string.rs

Fixes https://github.com/foundry-rs/foundry/issues/9433.

chore(deps): bump foundry-compilers 0.12.4

---

crates/evm/coverage/src/lib.rs
crates/forge/bin/cmd/coverage.rs
crates/forge/src/coverage.rs

- use `u32` and `HashMap`s instead of `usize`/`u64` and `BTreeMap`
- simplify `HitMaps::merge`
Lots of time spent in `merge` for inserting in the right order, but the order was never checked (`consistent_bytecode` is unused and `HitMap::merge` returned `Result`, presumably this was removed at a certain point)
`forge coverage` on solmate from 29s to 16s

perf(coverage): improve HitMap merging and internal repr

---

crates/evm/coverage/src/inspector.rs
crates/evm/evm/src/inspectors/stack.rs

I don't remember why this is not computed/cached in revm, but we can do it ourselves
Few more secs saved in solmate on top of https://github.com/foundry-rs/foundry/pull/9456

perf(coverage): cache computed bytecode hash in CoverageCollector

---

crates/evm/coverage/src/analysis.rs
crates/forge/tests/cli/coverage.rs

Fixes https://github.com/foundry-rs/foundry/issues/9444.
Ignore them for now until we can figure out https://github.com/foundry-rs/foundry/issues/9458.

fix(coverage): also ignore empty fallbacks and receives

---

crates/forge/bin/cmd/coverage.rs
crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs

In https://github.com/foundry-rs/foundry/pull/9438, it turns out that the `end_line` is a breaking change as it was added in 2.0, whereas I interpreted the documentation that the "old" format referred to pre-2.0.
Adds `--lcov-version major[.minor]` to `forge coverage`. Defaults to "1" for backwards compatibility. See the flag's documentation for differences between versions.
The original version issue (https://github.com/foundry-rs/foundry/issues/8281) is still fixed even with `--version 1` because the error was "missing corresponding lines" (DA), which are now always added with https://github.com/foundry-rs/foundry/pull/9438.
Fixes https://github.com/foundry-rs/foundry/issues/9461.

fix/feat(coverage): add --lcov-version

---

crates/forge/bin/cmd/coverage.rs

Forgot to push in https://github.com/foundry-rs/foundry/pull/9462, doesn't actually change anything, just for docs

chore: set --lcov-version default to 1

---

crates/anvil/src/eth/backend/mem/fork_db.rs
crates/anvil/tests/it/fork.rs

Re: https://t.me/foundry_rs/38080
Currently `maybe_as_full_db` isn't implemented for `ForkedDatabase` hence queries that run over a specific state in forked mode would fail with `Required data unavailable` 
Implement `maybe_as_full_db` for `ForkedDatabase`.

fix(`anvil`): impl `maybe_as_full_db` for `ForkedDatabase`

---

crates/cli/src/utils/mod.rs
crates/forge/bin/cmd/install.rs

Closes #7225.
Current while installing a dep are checking for the deps branch in project root, which is incorrect as the tagged branch, if it exists, will be in the directory of the dep i.e `lib/dep-name` 
Check whether the branch exists in the correct dir i.e `lib/dep-name`
Tested this on @zerosnacks's repro https://github.com/zerosnacks/foundry-bug-7225-repro, correctly writes the `branch = 0.8` in `.gitmodules`

fix(`forge`): run `dep.has_branch` in correct dir 

---

crates/forge/tests/cli/ext_integration.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs

Related failing workflow: https://github.com/foundry-rs/foundry/actions/workflows/test-isolate.yml
passing CI from PR branch https://github.com/foundry-rs/foundry/actions/runs/12137509972
Disabled snekmate in isolate as was slow https://github.com/foundry-rs/foundry/actions/runs/12091812051/job/33720682089#step:12:424

chore: fix test isolate

---

crates/evm/coverage/src/inspector.rs

Follow-up https://github.com/foundry-rs/foundry/pull/9469

docs: CoverageCollector comments

---

crates/cast/tests/cli/main.rs
crates/cli/src/opts/ethereum.rs

Closes #9476 
Currently, when inserting the passed `chain` into figment dict we don't differentiate between `ChainKind::Id` and `ChainKind::NamedChain`, even though they hold different types underneath; `u64` and `String` respectively.
Insert `Chain` into dict according to `Id` or `NamedChain`

fix(`cli`): handle id and named chain_id's correctly

---

crates/cast/bin/cmd/send.rs
crates/cheatcodes/src/error.rs
crates/common/src/errors/mod.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/opts.rs
crates/evm/evm/src/executors/mod.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/test_cmd.rs

A very common pattern in errors is displaying `some message: {inner}`, so when chaining we end up with `some message: {inner}; {inner}...`.
```diff
- backend: failed while inspecting; transaction validation error: call gas cost exceeds the gas limit; call gas cost exceeds the gas limit; 
+ EVM error; transaction validation error call gas cost exceeds the gas limit
```

feat: dedup error messages

---

Cargo.lock
crates/cli/src/opts/global.rs
crates/forge/bin/cmd/coverage.rs

- https://github.com/foundry-rs/compilers/pull/231

chore(deps): bump foundry-compilers 0.12.6

---

Cargo.lock
Cargo.toml
crates/cast/src/lib.rs

New version of evmole has been released, the old API has been deprecated.
Upgraded to new version and migrated to new style API.

chore(cast): upgrade evmole to 0.6.1, use new style API

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/test/expect.rs
testdata/cheats/Vm.sol
testdata/default/cheats/ExpectRevert.t.sol

Closes #509 
Implement `expectRevert` overloads with the `count` arg. Negative assertions can be made by setting `count` to `0`
```solidity
/// Expects a `count` number of reverts from the upcoming calls with any revert data or reverter.
function expectRevert(uint64 count) external;
/// Expects a `count` number of reverts from the upcoming calls that match the revert data.
function expectRevert(bytes4 revertData, uint64 count) external;
/// Expects a `count` number of reverts from the upcoming calls that exactly match the revert data.
function expectRevert(bytes calldata revertData, uint64 count) external;
/// Expects a `count` number of reverts from the upcoming calls from the reverter address.
function expectRevert(address reverter, uint64 count) external;
/// Expects a `count` number …
```

feat(`cheatcodes`): count assertion for `expectRevert`

---

crates/verify/src/verify.rs

Closes #9510 
Similarly with https://github.com/foundry-rs/foundry/pull/9483
Try to retrieve artifacts from cache by version without build metadata too if cached artifacts and artifact not found by version arg.

fix(verify): cached artifacts by version

---

crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/cli/test_cmd.rs

Closes #9531 
- skip suite if setup is skipped

feat(cheatcodes): skip test suite in setup

---

crates/config/README.md

I think this comment is incorrect. Based off my reading of [this solidity page](https://docs.soliditylang.org/en/latest/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode), it seems that this flag prevents the appending of the CBOR encoded file to the bytecode
changing the comment

Update incorrect documentation in the READ.me

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/state.rs

…rk activated
Closes #9539 
`storage.best_number` should be set to `max(state.block.number, fork_block_number)` while loading state with fork activated

fix(`anvil`): set `best_number` to `state.block.number` if greater

---

crates/cast/bin/cmd/run.rs
crates/cast/tests/cli/main.rs
crates/common/src/constants.rs

Closes #9541 
Reset `env.tx.caller` to `tx.from` for impersonated txs

fix(`cast`): reset `env.tx.caller` for impersonated txs

---

crates/cast/bin/cmd/run.rs
crates/evm/core/src/backend/mod.rs
crates/evm/core/src/utils.rs
crates/verify/src/bytecode.rs

impersonated_txs should be accounted for in `configure_tx_env` 
Handle impersonated txs while configuring env and reset `env.tx.caller`.

fix: account for impersonated tx in configure_tx_env

---

crates/cheatcodes/src/config.rs
crates/cheatcodes/src/evm/fork.rs
crates/cheatcodes/src/test.rs
crates/chisel/src/dispatcher.rs
crates/common/src/provider/mod.rs
crates/config/src/endpoints.rs
crates/config/src/lib.rs
crates/evm/core/src/fork/multi.rs
crates/evm/core/src/opts.rs
crates/forge/tests/it/test_helpers.rs

Closes #9162 - Set retry config (backoff, max retries) from rpc configuration when a fork is created using cheatcodes
Idea - https://github.com/foundry-rs/foundry/issues/9162#issuecomment-2535586933
Implementation:
Use two structs `RpcEndpoint` and `ResolvedRpcEndpoint` that both contain the same data, with the exception that environment variables are resolved to their values in `ResolvedRpcEndpoint`.
Extract shared fields out into a common struct field `RpcEndpointConfig` that doesn't need environment variable resolution.

fix: read rpc config when using fork cheatcodes

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/cast/tests/cli/main.rs

`cast impl` has no easy way to read the implementation for `BeaconProxy` like contract
Add a `--beacon` flag to `cast impl` that changes which storage slot is read to fetch the implementation address.
I added cast tests for both cases of `cast impl` ~~however they are both using actively used proxies, if someone has addresses for an `EIP1967Proxy` and a `BeaconProxy` that will never be upgraded it would prevent those tests breaking in the future~~

feat(cast): add support for beacon proxies in cast impl

---

.github/workflows/release.yml
foundryup/README.md
foundryup/foundryup

- install option renamed from `-v, --version` to
```
-i, --install   Install a specific version from built binaries
```
- new options added
```
-l, --list      List versions installed from built binaries
-u, --use       Use a specific installed version from built binaries
```
- install multiple versions (with `foundryup -i`) (last one becomes active)
```bash
$ foundryup -i nightly-f089dff1c6c24d1ddf43c7cbefee46ea0197c88f
$ foundryup -i nightly-e5dbb7a320c2b871c4a4a1006ad3c15a08fcf17b
```
- versions are extracted in `~/.foundry/versions/` dir and can be listed with `foundryup -l`
```bash
$ foundryup -l
foundryup: nightly-e5dbb7a320c2b871c4a4a1006ad3c15a08fcf17b
foundryup: - forge 0.2.0 (e5dbb7a 2024-12-03T00:24:42.577356416Z)
foundryup: - cast 0.2.0 (e5dbb7a 2024-12-03T00:24:42.537035487Z) …
```

feat(foundryup): allow multiple installed versions

---

crates/forge/assets/workflowTemplate.yml

`foundry-toolchain` will soon update users to default to `stable`, this PR removes explicit pinning to `nightly` in favor of the default of `foundry-toolchain` (now nightly, becoming stable).

Update CI workflow template to unpin from `nightly` explicitly, relying on `foundry-toolchain` default

---

crates/forge/src/runner.rs
crates/forge/tests/cli/test_cmd.rs

Ref https://github.com/foundry-rs/foundry/pull/9574#discussion_r1892489392 for `0.3`
Warn if `testFail*` has been used. One warning per test suite

chore: testFail* deprecation warning

---

foundryup/foundryup

As a preparation for major breaking changes `foundryup` should default to the latest `stable` release by default. This will allow users to not have to deal immediately with breaking changes introduced in the nightly builds.
Default to `stable` release.
Users are still able to install the latest `nightly` by running `foundryup --install nightly`.

chore(`foundryup`): default to stable if no specific version is passed in

---

crates/common/fmt/src/ui.rs

Let the `hash` and `type` fields indent with the other fields

chore(fmt): tx fields indent with the same whitespaces

---

crates/cli/src/opts/ethereum.rs

This PR adds a comment to the `-r` option about default value, otherwise users may wonder how `cast send` like below works:
```bash
cast send 0xf16FE8a2BA6bfaACf11c8bbf16E5Ccc2f718474b --value 10000000000000000000000 --private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
```

add comment to `-r` option about default value

---

crates/anvil/server/src/ipc.rs

Fix https://github.com/foundry-rs/foundry/issues/9203
As reth will append a `\n` at the end of the stream: 
```rust
impl Default for Separator {
fn default() -> Self {
Self::Byte(b'\n')
}
}
impl tokio_util::codec::Encoder<String> for StreamCodec {
type Error = io::Error;
fn encode(&mut self, msg: String, buf: &mut BytesMut) -> io::Result<()> {
let mut payload = msg.into_bytes();
if let Separator::Byte(separator) = self.outgoing_separator {
payload.push(separator);
}
buf.extend_from_slice(&payload);
Ok(())
}
}
```
https://github.com/paradigmxyz/reth/blob/343bee568fa8f496a07e8849cb5dad726ba15f41/crates/rpc/ipc/src/stream_codec.rs#L44-L48
https://github.com/paradigmxyz/reth/blob/343bee568fa8f496a07e8849cb5dad726ba15f41/crates/rpc/ipc/src/stream_codec.rs#L128-L139

fix(anvil): ipc append a newline

---

crates/cli/src/handler.rs
crates/common/src/errors/mod.rs
crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/config.rs

Follow-up https://github.com/foundry-rs/foundry/pull/9481 to errors returned in main

chore: dedup errors in eyre handler

---

crates/evm/core/src/precompiles.rs
crates/evm/core/src/utils.rs

Currently the `P256Verify` is injected at the wrong address i.e `0x14`.
Inject it at `0x100` according to the spec: https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md#specification. 
Maintains backward compatibility by also injecting it at 0x14.

fix(`evm`):  P256Verify address

---

crates/cast/bin/cmd/storage.rs
crates/common/src/ens.rs

When I'm querying the balance of my account, but by mistake missing the last char, the cast return as below:
```
cast balance  0xFacbDEcF714f55d65ABF5be2054a8127880405c`missing one char`
Error: Failed to get resolver from the ENS registry: buffer overrun while deserializing
```
this error seems a little misleading, so let's check if the address contains a `.` or not, then to resolve the ens.

fix(ens): don't resolve addr if doesn't contain .

---

testdata/default/cheats/RecordAccountAccesses.t.sol

- fixes test isolate, successful run from branch https://github.com/foundry-rs/foundry/actions/runs/12704793888

chore: fix test isolate, different address for caller

---

Cargo.toml

closes #9662 
relates to a rustc bug w/  `--profile maxperf` and `lto = "fat"` for 1.84.0 only (stable)

fix: set debug none for release profile

---

crates/anvil/src/eth/otterscan/api.rs
crates/cli/src/opts/dependency.rs
crates/config/src/invariant.rs
crates/doc/src/builder.rs
crates/forge/bin/cmd/test/mod.rs
crates/verify/src/utils.rs

fix clippy https://github.com/foundry-rs/foundry/actions/runs/12722126159/job/35465821957?pr=9655#step:5:1228

chore(clippy): use next_back instead of last for DoubleEndedIterator

---

crates/common/src/retry.rs
crates/script/src/receipts.rs

closes #9636 
- use `Retry` utility. add `Continue` variant to preserve number of retries (without decrementing)
- use `Continue` on watcher timeout err if tx is still known to the node (won't count as a retry). For all other errs use `Retry`
- tested with 100 txes on base sepolia

fix: error handling with retries when waiting for receipt

---

crates/forge/tests/cli/script.rs
crates/script/src/broadcast.rs
crates/script/src/lib.rs

Closes #9661 
- Use `evm_opts.fork_block_number` while fetching the sender nonce that is to be set in `ScriptConfig`.

fix(`script`): use fork_block_number for init sender nonce

---

foundryup/foundryup

Add a `--self-update` command to update foundryup itself.

feat(foundryup): add foundryup self-update

---

Cargo.lock
crates/common/src/io/shell.rs
crates/evm/traces/src/lib.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/fixtures/colored_traces.svg
crates/test-utils/Cargo.toml

So that --color=always works with traces.

fix: propagate color config to TraceWriter

---

foundryup/foundryup

supersede https://github.com/foundry-rs/foundry/pull/7970
- Reuse proposed `check_bins_in_use` and call it when `--install` and `--use`
- add fallback to warning message if pgrep not installed

feat(foundryup): check for running processes

---

crates/config/src/lib.rs
crates/forge/bin/cmd/config.rs
crates/forge/tests/cli/config.rs

Closes #9688 
- move optimizer settings normalization in helper fn and reuse when generating configs
- add tests for default configs and optimizer options

fix(config): normalize optimizer settings

---

Cargo.lock

Fixes https://github.com/foundry-rs/foundry/issues/9682. See https://github.com/alloy-rs/svm-rs/pull/150.

chore(deps): bump svm 0.5.10

---

crates/script/src/verify.rs

closes #9698 
- strip profile from contract name when creating verify args

fix(verify): strip profile from contract name

---

Cargo.lock
crates/chisel/Cargo.toml
crates/chisel/src/session_source.rs

closes #9647 
- check if in foundry project / any forge-std remapping and search proper path to Vm.sol

feat(chisel): determine proper path to Vm.sol based on proj remappings

---

Cargo.lock
crates/common/Cargo.toml
crates/common/src/provider/runtime_transport.rs

For now passed `User-Agent` header is rewritten to `foundry/version`, but it should not
Fix header existence check condition (`HeaderName` is lowercased and do not contains `:`)

Fix rewrite of User-Agent header

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/cmd/test/summary.rs

- invariant metrics are usually recorded with key containing full path to contracts (e.g. `src/universal/Proxy.sol:Proxy.changeAdmin`)
- there are scenarios where contract name does not contain artifact path (therefore metrics are recorded with keys as `SystemConfig.setGasLimit`) - see https://github.com/ethereum-optimism/optimism/blob/opcm-up/upgrade-asr/packages/contracts-bedrock/test/invariants/SystemConfig.t.sol#L22 Current logic handles only contracts with full path and does not display any metric in this case:
- handle metrics keys without artifact path
- refactor  `print_invariant_metrics` fn to `format_invariant_metrics_table`
- add test

fix(invariant): handle simple contract names in metrics table

---

crates/config/src/providers/remappings.rs

closes https://github.com/foundry-rs/foundry/issues/6706

feat: allow remapping of solidity files

---

crates/forge/bin/cmd/coverage.rs
crates/forge/tests/cli/coverage.rs

Closes #8840 
Saves coverage artifacts and build-info to a separate directory `out/coverage` and `out/coverage/build-info` respectively. This prevents users from mistakenly deploying unoptimized contracts, see: https://github.com/foundry-rs/foundry/issues/8840#issuecomment-2390792012
Artifacts generated by `forge coverage` are written to `out/coverage`.

fix(`forge`): disable artifacts for coverage

---

crates/common/src/evm.rs

We need this so that it doesn't override the config value if not provided

fix: respect `disable_block_gas_limit` config key

---

crates/common/build.rs

`PROFILE` only captures release or debug / dev, however we have custom profiles that should show up here
This uses the `OUT_DIR` which can capture custom build profiles

fix: use custom build profile in --version

---

crates/forge/bin/cmd/inspect.rs
crates/forge/tests/cli/cmd.rs

Closes #5165 
- Removes the `--pretty` flag and makes that behavior the default. 
- Generate table layout for `abi`, `method-identifiers`, `errors`, and `events` by default, json can be obtained using the `--json`. 
- For artifacts fields that are not table-friendly, generate `json` by default.

feat(`forge`): inspect - default to pretty output

---

crates/common/src/contracts.rs
crates/evm/evm/src/executors/invariant/mod.rs

- closes #9731 (https://github.com/foundry-rs/foundry/issues/9731#issuecomment-2606388722)

fix(invariant): lookup fuzz interface abi by name or identifier

---

foundryup/foundryup

- closes #9740 
- add custom versions in `~/.foundry/versions` with version format: `($author)-(branch|pr|commit)-($branch-name)|($pr_number)|($commit-sha)` e.g.
- from repo `foundry-rs/foundry` with commit: `foundry-rs-commit-049dbe5e96b36236d629bb953c786c1c6ed27e7a`
- from repo `author1/foundry` with branch `issue/fix-9146`: `author1-branch-issue-fix-9146`
- from repo `foundry-rs/foundry` with PR 9746: `foundry-rs-pr-9746`
- `/` is replaced with `-` in branch names
- move check for default path of the binary in `use`
- remove duplicate code and use `use` fn when installing from binaries and source

feat(foundryup): manage custom built versions

---

crates/cast/bin/args.rs
crates/cast/bin/cmd/bind.rs
crates/cast/bin/main.rs
crates/cast/src/lib.rs
crates/cast/tests/cli/main.rs
crates/forge/tests/cli/verify_bytecode.rs

Closes #4776 
- Rename command from `cast etherscan-source` to `cast source`
- Add args `explorer_url: Option<String>` and `explorer_api_url: Option<String>` that can be used to specify alternative block explorers.
- Test

feat(`cast source`): support alternative explorers

---

Cargo.lock
clippy.toml
crates/anvil/src/anvil.rs
crates/cheatcodes/src/error.rs
crates/cli/Cargo.toml
crates/cli/src/handler.rs
crates/common/src/retry.rs
crates/evm/core/src/fork/init.rs
crates/evm/core/src/opts.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/forge/tests/cli/test_cmd.rs

So that `display_chain` is used rather than the default which only displays the first error message.

feat: override the eyre display handler globally

---

crates/config/src/lib.rs
crates/forge/bin/cmd/coverage.rs

Point 3 in https://github.com/ethereum/solidity/issues/15775

fix(coverage): keep EVM version when normalizing for ir-minimum

---

Dockerfile.cross

- install git and create foundry user inside Docker image - needed to build a project mounted inside container
- use same alpine image as regular Dockerfile
https://github.com/foundry-rs/foundry/blob/2509ce26e12979cfa694b1ea820a405479ce7998/Dockerfile#L33-L42

chore: install deps and create foundry user in cross built image

---

crates/forge/tests/cli/config.rs

- isolate fails in default config test due to `isolate = true` https://github.com/foundry-rs/foundry/actions/runs/13021808208/job/36323864836#step:12:309
- do not run test if isolate

chore: fix isolate tests

---

crates/anvil/src/config.rs

Optimistically marking as resolved: https://github.com/foundry-rs/foundry/issues/7068
Related: https://github.com/foundry-rs/foundry/issues/9752
Originally part of https://github.com/foundry-rs/foundry/pull/9753, split out due to some nuances in that PR that need to be untangled further
- Fixes `gas_limit` as reported by Anvil
When forking Sonic, has 1 billion gas limit: `anvil --fork-url https://rpc.soniclabs.com`
Previously reported:
```
Gas Limit
==================
30000000
```
Fixed:
```
Gas Limit
==================
1000000000
```

fix: correctly set `gas_limit` reported by Anvil

---

Dockerfile.cross

- regression in docker images introduced by https://github.com/foundry-rs/foundry/pull/9775
- commands fail with `/bin/sh: forge: not found` / `/bin/sh: anvil: not found`
- roll back to ubuntu (was changed in https://github.com/foundry-rs/foundry/commit/f3548cb4d06b5eec81f2482e9fc3c16e58f7efe5)
- install git and create foundry user, set default foundry user
Tested forge commands from image built from `fix-docker` branch as:
- create new project `forge init hello-world && cd hello-world`
- forge install:
```sh
docker run --rm -it \
-v "$(pwd)":/workspace \
-w /workspace \
-u 1000:1000 \
ghcr.io/foundry-rs/foundry:fix-docker \
-c "forge install"
```
- forge clean and build:
```sh
docker run --rm -it \
-v "$(pwd)":/workspace \
-w /workspace \
-u 1000:1000 \ …
```

fix(docker): revert to use ubuntu:22.04 as base image

---

crates/anvil/tests/it/anvil_api.rs
crates/anvil/tests/it/transaction.rs
crates/common/fmt/src/ui.rs
crates/fmt/src/buffer.rs
crates/forge/src/coverage.rs
crates/wallets/src/multi_wallet.rs

chore: fix clippy

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/core/src/types.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/anvil_api.rs

Adds `anvil_rollback` RPC method. This method allows users to undo blocks that already been produced.
The existing `anvil_reorg` doesn't allow you to actually remove blocks, only to re-org in place. 
The code is  similar to `anvil_reorg`, we simply skip the mining step.

feat(anvil): implement `anvil_rollback`

---

crates/config/src/lib.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/config.rs

Closes: https://github.com/foundry-rs/foundry/issues/9734
Unblocks: https://github.com/foundry-rs/foundry/issues/9697 / https://github.com/foundry-rs/foundry/pull/9710
Maintains backwards compatibility of `FORGE_SNAPSHOT_CHECK` with the added restriction of it requiring a boolean value (`FORGE_SNAPSHOT_CHECK=true`) in accordance to the other configuration items.
Evaluates in the following order:
Default is false
- We check whether `FORGE_SNAPSHOT_CHECK=true` is set
- We check whether `gas_snapshot_check=true` is set in the config
- Last we check `--gas-snapshot-check=<bool>` which takes preference over all, both `true` and `false`
Marked as minor breaking due to `FORGE_SNAPSHOT_CHECK` now explicitly checking for truthiness, not just existence

feat: add `gas_snapshot_check` flag to config, fix `FORGE_SNAPSHOT_CHECK` behavior

---

crates/forge/tests/cli/ext_integration.rs

- on win solady fails to build due to `"tload" instruction is only available for Cancun-compatible VMs (you are currently compiling for "paris").` https://github.com/foundry-rs/foundry/actions/runs/13068792712/job/36465786880#step:12:70
- this happens since we bumped git commit and skip is defined as `skip = ["/*Transient*", "*/ext/ithaca/*", "*/ext/zksync/*"]` https://github.com/Vectorized/solady/blob/main/foundry.toml
- on win `"/*Transient*"` is not picked up, changing to `"*/*Transient*"` works
- will follow up with checking why this happens on win only / or solady PR to fix pattern

chore: ignore solady CI failure in win

---

crates/anvil/core/src/eth/mod.rs

Currently, Anvil’s `trace_filter` only accepts an object, while Geth and Erigon support an object or an **array with one object** - the filter in both cases. This causes compatibility issues with tools that expect both formats to be valid - in my case `graph-node`, which utilizes the `rust-web3` crate, and always packages up params in an array.
For example, Anvil will only accept:
```bash
curl -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":{"fromBlock":"0x0","toBlock":"0x0"},"id":1}' \
-H "Content-Type: application/json" http://localhost:8545
```
But it **rejects**:
```bash
curl -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x0","toBlock":"0x0"}],"id":1}' \
-H "Content-Type: application/json" http://localhost:8545
```
with the error: …

fix(trace_filter): allow params to be object or array with len 1

---

crates/cast/src/lib.rs

- Add new Polygon PoS testnet chain (amoy) and remove the deprecated one (mumbai).
- Add two Polygon zkevm chains (mainnet and cardona testnet).
```bash
$ cast block 0 --rpc-url https://rpc-amoy.polygon.technology/ --json | jq -r '.hash'
0x7202b2b53c5a0836e773e319d18922cc756dd67432f9a1f65352b61f4406c697
```
For reference: https://www.okx.com/web3/explorer/amoy/block/0
```bash
$ cast block 0 --rpc-url https://zkevm-rpc.com --json | jq -r '.hash'
0x81005434635456a16f74ff7023fbe0bf423abbc8a8deb093ffff455c0ad3b741
```
For reference: https://zkevm.polygonscan.com/block/0
```bash
$ cast block 0 --rpc-url https://rpc.cardona.zkevm-rpc.com --json | jq -r '.hash'
0x676c1a76a6c5855a32bdf7c61977a0d1510088a4eeac1330466453b3d08b60b9
```
For reference: https://cardona-zkevm.polygonscan.com/block/0

feat(cast): update polygon testnet chain and add polygon zkevm chains

---

Cargo.lock
Cargo.toml
crates/anvil/Cargo.toml
crates/anvil/core/Cargo.toml
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/core/src/eth/transaction/optimism.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/sign.rs

we've since moved this back to op-alloy

chore: replace maili with op-alloy

---

crates/config/src/lib.rs
crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/coverage.rs
crates/forge/bin/cmd/eip712.rs
crates/forge/bin/cmd/flatten.rs
crates/forge/tests/cli/coverage.rs

- Tweak wording
- mention that viaIR gets disabled as well
- move second warning inside the else branch so as to not emit 2 warnings with a similar message on --ir-minimum

chore: tweak coverage warnings

---

crates/forge/bin/cmd/init.rs
crates/forge/tests/cli/cmd.rs

fixes: #4215 
I am motivating by learning rust and using foundry as a means to do so.
I sought out some easy issues and landed on this comment: https://github.com/foundry-rs/foundry/issues/4215#issuecomment-2413695613 which should close that issue.
Still allow the cloning of the repo but before making the commit, check to see the value `--no-commit` and adhere.

fix(forge): allow `forge init --template` to work with `--no-commit`

---

crates/evm/fuzz/src/lib.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/it/invariant.rs

- suggested by @forkforkdog
- it is useful to show the original len of failed case vs the optimized counterexample len
- added info in failed test output

feat(invariant): on failures show original and current sequence len

---

crates/cast/bin/tx.rs
crates/cast/tests/cli/main.rs

- closes #9789 
- opened for visibility and initial feedback
- try decode custom error with SignaturesIdentifier if code 3 and append to output e.g.
```
Error: server returned an error response: error code 3: execution reverted: custom error 0x6786ad34: ..., data: "...": AddressInsufficientBalance(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266, 1000)
```

fix(cast): try decoding custom errors when execution reverted in cast send

---

.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
Makefile
crates/cast/Cargo.toml
crates/chisel/Cargo.toml
crates/cli/Cargo.toml
crates/common/Cargo.toml
crates/config/Cargo.toml
crates/forge/Cargo.toml
crates/wallets/Cargo.toml
deny.toml

I don't think these were ever used. We always use rustls, so remove these features and always enable rustls.

chore: remove rustls/openssl features

---

crates/cli/src/utils/cmd.rs

fix: mark metis as different gas calc

---

crates/doc/static/book.toml

Crypto is a math heavy field, and adding math in documentation should be easy. Latex is the de-facto standard mechanism for writing math.
Add mathjax support to the mdbook config for forge doc. See https://rust-lang.github.io/mdBook/format/mathjax.html for examples and reasoning.
An alternative solution is to add an extra key to the foundry `[doc]` section, but I see no reason to _not_ have this enabled by default, and this PR is _far_ easier.
Happy to add these as needed. I don't think any of them apply.

feat: add mathjax support to forge doc mdbook config

---

foundryup/foundryup

- re https://t.me/foundry_support/59421 tried to install in win with `Foundry User` user and foundryup failed due to wrong paths

fix(foundryup): install for user names with empty space

---

crates/config/src/invariant.rs
crates/evm/evm/src/executors/invariant/replay.rs
crates/evm/fuzz/src/lib.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/it/invariant.rs
crates/forge/tests/it/test_helpers.rs

- closes #8117 
- generate solidity sequence output
- current output is hard to parse and translate in solidity LOCs, usually projects create their own custom scripts to parse and generate such  
- `show_solidity` config added to invariant section, disabled by default
- can switch between different outputs, for same test. Can configure inline per test or globally.
- persisted failures adhere to config
- added tests

feat(invariant): generate failed call sequence as solidity

---

crates/forge/bin/cmd/bind.rs
crates/sol-macro-gen/src/sol_macro_gen.rs

Closes: https://github.com/foundry-rs/foundry/issues/9844
Fixes:
When a user previously would run `cargo build` in the `out/bindings/` directory and re-run `forge bind` it would panic with:
```
Message:  Ident is not allowed to be empty; use Option<Ident>
Location: crates/sol-macro-gen/src/sol_macro_gen.rs:36
8: proc_macro2::fallback::validate_ident::h9f587f7b233989e3
9: forge_sol_macro_gen::sol_macro_gen::SolMacroGen::get_sol_input::h533d8cfab70c8dcc
10: …
```

feat: add `--alloy-rev` and fix `forge bind` re-run on built project

---

crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/test_cmd.rs

Closes #9864 
- add `-s/suppress_successful_traces` arg to `forge test` and hide logs and traces for successful tests. Can be set as `FORGE_SUPPRESS_SUCCESSFUL_TRACES` env var too
- show traces for all tests by default
- test

feat(forge): add option to suppress successful tests traces

---

.github/workflows/release.yml

>This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
`macos-12-large` has been deprecated and now unavailable as a runner causing releases to partially fail:
- https://github.com/foundry-rs/foundry/actions/runs/13253147519
- https://github.com/foundry-rs/foundry/actions/runs/13275161837
Closes: https://github.com/foundry-rs/foundry/issues/9867
According to https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#about-macos-larger-runners the `Intel` architecture should be available on `macos-latest-large`.

chore: fix release flow

---

.github/workflows/release.yml

Addresses: https://github.com/foundry-rs/foundry/pull/9869#issuecomment-2653632006 by pinning to `macos-13-large`
cc @DaniPopes 
Pins to `macos-13-large`  to support old SDK versions

fix: pin to `macos-13-large` for release flow to support old SDK versions

---

crates/anvil/src/eth/backend/mem/mod.rs

when getting transactions from the API (eth_getTransactionByHash or eth_getBlockByHash with tx true), deposit transactions don't include nonce or signature information.
https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type
>Does not include signature information, and makes the from address explicit. API responses contain zeroed signature v, r, s values for backwards compatibility.
return a zeroed signature and nonce when `transaction_build` to craft an RPC transaction

fix(anvil): return nonce and signature for deposit tx type

---

crates/forge/src/multi_runner.rs
crates/forge/tests/cli/inline_config.rs

Previously `/// forge-config: default.isolate = true` did not work as expected as it was not implemented
Implements it, clean up / clarify + add test
Added test that tests whether gas isolation is enabled without hardcoding gas
Like `config_inline_evm_version` it uses `forgetest_init!`, arguably this could be better done w/ `forgetest` directly but out of scope in this ticket.
I noticed we haven't documented the isolate mode well in the Foundry book, added a follow-up ticket for me here: https://github.com/foundry-rs/book/issues/1454

fix: add support for inline `isolate` configuration

---

Dockerfile

Closes #9906 
Update alpine version to the most recent one (`3.21`).
Update `Dockerfile`.

feat: bump `alpine=3.21` in Dockerfile

---

crates/cast/bin/main.rs

Closes: https://github.com/foundry-rs/foundry/issues/9899
Example:
```
cast age --rpc-url https://eth.merkle.io
```
Before: `Tue Feb 18 13:35:59 2025`
After: `Tue Feb 18 13:35:35 2025 UTC`
Before (as noted in ticket):
```
date +%s -d "`cast age 15537394 --rpc-url https://eth.merkle.io`"
1663216979
```
After (correct):
```
date +%s -d "`cast age 15537394 --rpc-url https://eth.merkle.io`"
1663224179
```

feat(`cast age`): clarify block timestamp is UTC to allow for `date` compatibility

---

crates/anvil/src/eth/error.rs
crates/anvil/tests/it/transaction.rs

this is a new error introduced with 7623 in prague that we need to treat as gas too high in ethestimate which happens if the calldata cost exceeds the gas limit 
the error naming here is super inconsistent so it's debatable whether this is gas to low or gas to high, map this is treated as "out of gas"

fix: map 7623 to gas too high

---

crates/cast/bin/args.rs
crates/cast/bin/main.rs
crates/cast/tests/cli/selectors.rs

Related: https://github.com/foundry-rs/foundry/issues/9926#issuecomment-2672039964
Change `4byte-decode` to `4byte-calldata` (`4c`, `4bc`) in non breaking way in line with `4byte-event`.  `4byte-decode` and its shorthands (`4d`, `4bd`) are hidden aliases
Manually tested + updated test to cover hidden alias
Related book PR: https://github.com/foundry-rs/book/pull/1456

chore(`cast`): add `4byte-calldata` alias

---

crates/evm/evm/src/inspectors/stack.rs
crates/forge/tests/cli/inline_config.rs

On every `with_stack` call we are invoking `mem::take` on `&mut Cheatcodes` which results in invocation of `CheatsConfig::default()` https://github.com/foundry-rs/foundry/blob/c609884bdb13b9846fe9ddc5f08d99cf30c53695/crates/evm/evm/src/inspectors/stack.rs#L701
https://github.com/foundry-rs/foundry/blob/c609884bdb13b9846fe9ddc5f08d99cf30c53695/crates/cheatcodes/src/inspector.rs#L498-L502
Which then invokes `ProjectPathsConfigBuilder` resulting in remappings resolution happening on every call and significantly degrading performance https://github.com/foundry-rs/foundry/blob/c609884bdb13b9846fe9ddc5f08d99cf30c53695/crates/cheatcodes/src/config.rs#L217
Solution is to reuse the `CheatsConfig` we already have as its `Arc`'ed and we don't really care about this temporary value.
This improves …

fix(--isolate): avoid remappings lookups

---

crates/cast/bin/cmd/wallet/mod.rs
crates/cast/tests/cli/main.rs

Closes: #9911 
Adds an account name option to `cast wallet new`, allowing the keystore file to be named using the provided string (optionally). If multiple wallets are generated, it appends `_{wallet_num}` to the provided name account name, e.g., `account_1`, `account_2`, etc.

feat: add option to store keystore file with custom account name

---

crates/config/src/invariant.rs
crates/forge/src/runner.rs
crates/forge/tests/it/invariant.rs

- closes #9965 
- persist test driver bytecode together with generated counterexample
- when loading persisted failure, compare test bytecodes and ignore / warn user if doesn't match
- canonicalize failure path, remove invariant config clones

fix(invariant): ignore persisted failure if different test contract

---

.github/workflows/nextest.yml

CI is failing because test fixtures depend on vyper version.

ci: pin vyper

---

Cargo.toml
crates/anvil/core/src/eth/mod.rs
crates/anvil/core/src/types.rs
crates/cast/bin/tx.rs
crates/doc/src/document.rs
crates/doc/src/parser/item.rs
crates/evm/evm/src/executors/fuzz/types.rs
crates/evm/fuzz/src/lib.rs
crates/script-sequence/src/reader.rs

Unblock CI due to breaking Clippy changes
Applies Clippy fixes including suggestion for optimization
Adds `result_large_err = "allow"` to `Cargo.toml` as exception
Selectively applies `#[allow(clippy::large_enum_variant)]` where required, can be used later to look into for optimization - see https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err

fix(`ci`): clippy, allow result too large

---

.github/workflows/release.yml

Moved from 12AM (00:00) to 6AM (06:00) UTC for improved monitoring of the nightly release process.
Should still be early enough for most users who update their installation in the morning.

chore: move nightly build to 6 AM UTC for improved monitoring of release process

---

crates/cast/tests/cli/main.rs
crates/common/src/transactions.rs

When calling `cast receipt`, the failure reason is generated via `eth_call`. However, the `from` address during this call is not correctly set to the one in the transaction. This leads to spurious "Ownable: caller is not the owner" errors, which do not represent the true failure reason for the transaction. 
This PR fixes the above issue by setting  the `from` value correctly, before invoking `eth_call`. Included is a unit test for a transaction on Sepolia to demonstrate the difference. Without the PR, the revert reason was incorrectly reported as "Ownable: caller is not the owner" instead of the actual revert reason "Counter is too large".
~- [ ] Added Documentation~
~- [ ] Breaking changes~

fix(receipt): use `from` address

---

crates/cast/bin/cmd/run.rs

In Ronin ([1]) and BSC ([2]), there are system transactions which have gas limit higher than block gas limit. This commit adds --disable-block-gas-limit flag to cast run so that user can trace those transactions.
[1]: https://app.roninchain.com/tx/0x8323b1843da7e8c61be697b35885bf492f8ec30e4413aa32b629371733df60d7
[2]: https://bscscan.com/tx/0x2362c464510d39247b0718d661224c5b5d369e543a88eefb260c798dcda2624e

fix(cast): allow user to disable block gas limit check in cast run

---

crates/cheatcodes/src/evm.rs

- closes #9983
- test within issue is fuzzing bytes to etch which results in invalid bytecode and panic
- use new_raw_checked instead new_raw when creating bytecode and present err to user

fix(forge): avoid etch panic on invalid bytecode

---

crates/verify/src/etherscan/mod.rs

- closes #9976 
- blockscout chiado returns response with status 0 and err message "The address is not a smart contract", hence we don't retry but exit
- retry if resp status 0 and "The address is not a smart contract" message

fix(verfy): add blockscout exception for resp status 0 when contract not indexed

---

crates/cast/bin/cmd/call.rs

The usage of `cast call --data` wasn't clear for me, probably for others too.
Extended the docs.

fix(cast): clarify docs for the cast call --data flag

---

crates/evm/traces/src/debug/sources.rs
crates/forge/tests/cli/script.rs

- closes #9068 
- closes #10024 
- warn if source file for artifacts already built are no longer available

fix(forge): warn if file for artifact no longer exists

---

crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/evm/prank.rs
crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/script.rs
crates/forge/tests/cli/test_cmd.rs

- closes #5521 
- record pranks at depth they're added
- retrieve prank at current depth or first prank recorded at a lower depth (if any)

fix(forge): stack pranks, restore pranks at earlier call depths

---

.github/workflows/docker-publish.yml

- closes #10032 
- install cross main (using cargo) instead 0.2.5 (using taiki-e/install-action@cross) (see https://github.com/cross-rs/cross/issues/1639#issuecomment-2708228372) to prevent ring 0.17.13 crate issue https://github.com/briansmith/ring/issues/2463
- update docker runner to 22.04
- optimize CI runs, update docker workflow to be triggered only through release workflow or manually (no need to be individually scheduled)
- release from branch tested and passed in https://github.com/foundry-rs/foundry/actions/runs/13738406294

fix(docker): use cross main, build docker only on release

---

crates/verify/src/bytecode.rs
crates/verify/src/etherscan/mod.rs

- address provider base url display issue from #10029 (https://github.com/foundry-rs/foundry/issues/10029#issuecomment-2708899816)

fix(forge): base url for verification providers other than etherscan

---

.github/workflows/nextest.yml

- bump python gh setup version to fix https://github.com/foundry-rs/foundry/actions/runs/13785778800/job/38553502465

chore: fix ci, bump python setup version

---

crates/verify/src/etherscan/mod.rs
crates/verify/src/provider.rs

- closes #10056  : since Sourcify is default now it should check also if an API Key was provided. If so, then should not verify on Sourcify but continue checking and will eventually be set as etherscan
- the test suites (that deploy and verify contracts) are not performed by CI as they need private keys, so should be run locally (might look into running them with gh secrets as part of CI but would add additional time and effort to manage those accounts)

fix(forge): use etherscan verifier if key provided

---

.github/scripts/matrices.py
.github/workflows/release.yml

Add binaries `x86_64-musl` and `aarch64-musl` targets.
Closes #9974 
Add `musl` targets in release.yml file.

feat: add `x86_64-musl` and `aarch64-musl` release targets

---

crates/forge/bin/cmd/coverage.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/bin/cmd/watch.rs

Closes: https://github.com/foundry-rs/foundry/issues/10079
Related: https://github.com/foundry-rs/book/pull/1477
Instead of panicking we instead should bail cleanly
```
Error: Can not supply both --match-path and |path|
```

fix(`forge test --debug`): do not panic when user specifies both `--match-path` and `<PATH>` , bail instead

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/genesis.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/tests/it/genesis.rs

Closes https://github.com/foundry-rs/foundry/issues/10080 by setting the genesis block number from the genesis.json file correctly
- Introduced `genesis.number` in `GenesisConfig` to store the genesis block number.
- Added `get_genesis_number` method to retrieve the genesis number.
- Updated `setup` function to initialize the genesis number.
- Modified `BlockchainStorage` and `Blockchain` constructors to accept and utilize the genesis number.
- Adjusted tests to reflect the new genesis number functionality.

feat(anvil): add genesis number to configuration and update related structures

---

crates/cast/bin/cmd/mktx.rs
crates/cast/bin/tx.rs
crates/cast/tests/cli/main.rs
crates/forge/bin/cmd/bind_json.rs
crates/forge/bin/cmd/geiger.rs

Closes #9741 
- Add `--raw-unsigned` flag to `mktx`
- If `--raw-unsigned` flag is provided, it relaxes the signer requirement but still requires `--from` to correctly build unsigned tx.
- Returns RLP-encoded unsigned tx

feat(`cast`): make unsigned raw txs

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/lib.rs
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
crates/cheatcodes/src/inspector.rs
testdata/cheats/Vm.sol
testdata/default/cheats/AccessList.t.sol
testdata/default/cheats/StorageSlotState.t.sol

- closes #10101 
- new cheatcodes added
```Solidity
/// An EIP-2930 access list item.
struct AccessListItem {
/// The address to be added in access list.
address target;
/// The storage keys to be added in access list.
bytes32[] storageKeys;
}
/// Utility cheatcode to set an EIP-2930 access list for all subsequent transactions.
function accessList(AccessListItem[] calldata accessList) external;
/// Utility cheatcode to remove any EIP-2930 access list set by `accessList` cheatcode.
function noAccessList() external;
/// Utility cheatcode to mark specific storage slot as warm, simulating a prior read.
function warm(address target, bytes32 slot) external;
/// Utility cheatcode to mark specific storage slot as cold, simulating no prior read.
function cold(address target, bytes32 slot) …
```

feat(forge): add accessList and cold/warm cheatcodes

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm.rs
testdata/cheats/Vm.sol
testdata/default/cheats/StorageSlotState.t.sol

- follow up on https://github.com/foundry-rs/foundry/pull/10112
- ref https://github.com/foundry-rs/foundry/pull/10112#issuecomment-2739330438
- cheatcodes changed to
```Solidity
/// Utility cheatcode to mark specific storage slot as warm, simulating a prior read.
function warmSlot(address target, bytes32 slot) external;
/// Utility cheatcode to mark specific storage slot as cold, simulating no prior read.
function coolSlot(address target, bytes32 slot) external;
```

chore: rename vm.coolSlot/warmSlot, fix flaky test

---

.github/workflows/test.yml
crates/anvil/Cargo.toml
crates/anvil/core/Cargo.toml
crates/anvil/core/src/eth/block.rs
crates/anvil/core/src/eth/mod.rs
crates/anvil/core/src/eth/serde_helpers.rs
crates/anvil/core/src/eth/subscription.rs
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/core/src/types.rs
crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/db.rs
crates/test-utils/Cargo.toml

Features in anvil-core are useless, and remove unused ones.
Add --each-feature to cargo hack in CI and fix it.
This job should still be faster than the current slowest jobs so PR CI total time is unmodified.

chore: clean up features, add features in CI

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs

- due to forge-std script issue, the cheatcodes marked as experimental are not included (so `vm.cool` wasn't ever exposed)
- remove experimental from `vm.cool` and the newly added cheatcodes and follow up with a better way to handle `forge-std` experimental cheatcodes

chore: remove experimental from cheatcodes

---

crates/test-utils/src/rpc.rs

increases weight for our own urls and checks for `ip:8545`

test: increase weight for urls

---

crates/cli/src/opts/build/core.rs
crates/forge/tests/cli/config.rs

Closes https://github.com/foundry-rs/foundry/issues/10103

feat(forge build): add `--use-literal-content` CLI flag

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

- ref https://github.com/foundry-rs/foundry/pull/10158#issuecomment-2746049653
- update release runners to Linux-22.04
- build `aarch64-unknown-linux-gnu` with cross (tested locally, no other config required)
- use cross 0.2.5 for docker release

chore: release for latest cargo updates

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/fs.rs
testdata/cheats/Vm.sol
testdata/default/cheats/DeployCode.t.sol

- add cheatcodes to deploy from artifact code with msg.value and salt
```Solidity
function deployCode(string calldata artifactPath, uint256 value) external returns (address deployedAddress);
function deployCode(string calldata artifactPath, bytes calldata constructorArgs, uint256 value) external returns (address deployedAddress);
function deployCode(string calldata artifactPath, bytes32 salt) external returns (address deployedAddress);
function deployCode(string calldata artifactPath, bytes calldata constructorArgs, bytes32 salt) external returns (address deployedAddress);
function deployCode(string calldata artifactPath, uint256 value, bytes32 salt) external returns (address deployedAddress);
function deployCode(string calldata artifactPath, bytes calldata constructorArgs, uint256 value, …
```

feat(forge): add vm.deployCode cheats with msg.value and salt

---

crates/test-utils/src/rpc.rs

- drpc chose from public nodes and lately seen many timeouts for bsc testnet test
- hardcode bsc testnet rpc url to https://bsc-testnet-rpc.publicnode.com/ to avoid picking other nodes that could timeout

chore: bsc testnet rpc url

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/tests/it/genesis.rs

Closes #10238 
- Properly fixes chain-id precedence before backend initialization
- Order of precedence: --chain-id > fork-chain-id > genesis config > default.
- test depicting precedence

fix(`anvil`): fix chain-id precedence

---

crates/anvil/tests/it/eip4844.rs

---- eip4844::can_bypass_sidecar_requirement stdout ----
thread 'eip4844::can_bypass_sidecar_requirement' panicked at \src\fmt\mod.rs:1244:16:
Unable to install global subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")      
In the can_bypass_sidecar_requirement test, tracing_subscriber::fmt::init() was called directly, 
which caused conflict with other initializations of the global trace handler.
The fix replaces the direct tracing initialization call with the use of 
of the crate::init_tracing() built-in function, which avoids the error 
"a global default trace dispatcher has already been set".
The error occurred due to an attempt to set multiple global 
trace handlers in a single application, which is not allowed by the tracing-subscriber …

fix(anvil): Fix tracing-subscriber initialization conflict in EIP4844 test

---

deny.toml

sha1 used by gitoxide, doesn't affect foundry's usage

chore: update advisories

---

crates/common/src/contracts.rs
crates/forge/tests/cli/coverage.rs

- closes #10172 
- we properly get hitmaps but fail to match the contract based on creation code
- update find by creation code logic to strip ctor args if they can be decoded with current artifact

fix(forge): coverage for contracts with ctor with args

---

crates/chisel/src/dispatcher.rs

Error messages in Chisel's dispatcher were uninformative in some cases, making it difficult for users to understand what went wrong and how to fix the issue. Simple messages like "Failed to load session!" or "Invalid fork URL!" didn't provide enough context for users to troubleshoot effectively.
Improved several error messages in the Chisel dispatcher by adding more context and guidance to make them more helpful and actionable. The changes maintain the existing code logic and message format while providing clearer details about what went wrong and potential fixes.
For example:
- "Too many arguments supplied!" → "Too many arguments supplied! Please check command syntax."
- "Failed to load session!" → "Failed to load session! The session ID may not exist or might be corrupted."
- "Invalid …

feat: improve uninformative error messages

---

crates/evm/traces/src/identifier/local.rs

- closes #8465 
- tested with https://github.com/worldcoin/world-chain/tree/osiris/buffer-overrun-poc/contracts (see https://github.com/foundry-rs/foundry/issues/8465#issuecomment-2766941472). Too large to include as a unit test
- similar with https://github.com/foundry-rs/foundry/pull/10270 but checking ctor args in trace identify code

fix(forge): trace identify by creation code with stripped args

---

crates/evm/core/src/utils.rs

- Includes Rootstock network in workaround due to missing `block.prevrandao` (mix_hash) field in block header
- Rootstock (Bitcoin sidechain) is EVM-compatible but operates under a different consensus mechanism due to which mix_hash / block.prerandao semantics does not apply on Rootstock
Merging this PR will successfully fix the following error: 
```
Error: Failed to deploy script:
EVM error; header validation error: `prevrandao` not set
```
Merging this PR will unblock developers to use latest foundry version with Rootstock as Rootstock supports the EVM version (cancun) which is default version in foundry with the exception of prevrandao semantics which does not apply on rootstock network.

Force `prevrandao` on Rootstock network

---

crates/evm/abi/src/console/ds.rs

TODO in the file. 
Implemented the TODO to use UIfmt for DSTest console logs in the ds.rs file.
- Added import for UIfmt from foundry_common_fmt
- Updated display attributes to use UIfmt::pretty() for values formatting
- Applied UIfmt to both regular values and array elements
- Improved formatting consistency across all console log events

feat(abi): Implement UIfmt for DSTest console logs

---

Cargo.lock
crates/sol-macro-gen/Cargo.toml
crates/sol-macro-gen/src/sol_macro_gen.rs

closes #9482 ?
This adds a very! hacky workaround until we have this natively in SolInput, but since this is currently broken for unlinked artifacts this should work.
tested with this workaround 
https://github.com/foundry-rs/foundry/issues/9482#issuecomment-2794365323
```
~/git/rust/foundry/target/debug/forge bind --alloy --bindings-path crates/utils/src/slashing/middleware --overwrite --root ./crates/operator_sets_contracts/lib/eigenlayer-middleware --module --select RegistryCoordinator --libraries ./crates/operator_sets_contracts/lib/eigenlayer-middleware/src/libraries/QuorumBitmapHistoryLib.sol:QuorumBitmapHistoryLib:0x0000000000000000000000000000000000000001 --libraries ./crates/operator_sets_contracts/lib/eigenlayer-middleware/src/libraries/SignatureCheckerLib.sol:SignatureCheckerLib …
```

fix: add workaround for unlinked artifacts

---

crates/cheatcodes/src/inspector.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue10302.t.sol

fix(forge): do not set balance as apparent value in delegate prank

---

Makefile

- closes #10065 
- images built from branch https://github.com/foundry-rs/foundry/pkgs/container/foundry/392697416?tag=docker-aarch64
- x86_64 flags: https://github.com/foundry-rs/foundry/actions/runs/14376428844/job/40309860705#step:10:59
- aarch64 flags: https://github.com/foundry-rs/foundry/actions/runs/14376428844/job/40309860705#step:10:184

fix(docker): build docker aarch64 without jemalloc

---

crates/evm/core/src/backend/mod.rs
crates/forge/tests/cli/test_cmd.rs

- closes #10296 
- when select fork, makes sure that persisted accounts are starting with init state

fix(forge): ensure selected fork contains init state for persisted accounts

---

crates/anvil/src/eth/api.rs

this does mostly cpu work and especially in forking mode can be blocking for a while so we should spawn this like we do ethcall
https://github.com/foundry-rs/foundry/blob/master/crates/anvil/src/eth/api.rs#L1098-L1107

chore(anvil): spawn estimate on blocking task

---

crates/common/src/preprocessor/data.rs
crates/common/src/preprocessor/deps.rs
crates/forge/tests/cli/test_optimizer.rs

- closes #10312 
- current `ConstructorArgs` struct could conflict, change to `FoundryPpConstructorArgs` struct

fix(forge): avoid preprocessor constructor args struct name conflict

---

crates/cast/src/args.rs
crates/cast/src/lib.rs
crates/cast/src/opts.rs
crates/cast/tests/cli/main.rs

Currently, `cast tx` only works by passing the `tx_hash`. We can leverage the `eth_getTransactionBySenderAndNonce` RPC endpoint by adding `--from` and `--nonce` optional flags.
- Make `tx_hash` optional
- Add `from` and `nonce` args to the subcommand (also optional)
- Make raw_request to `eth_getTransactionBySenderAndNonce`

feat(`cast`): getTransactionBySenderAndNonce

---

Cargo.lock
Cargo.toml
crates/anvil/src/args.rs
crates/cast/Cargo.toml
crates/cast/src/args.rs
crates/chisel/src/args.rs
crates/cli/Cargo.toml
crates/cli/src/utils/mod.rs
crates/forge/src/args.rs
crates/forge/tests/it/test_helpers.rs
crates/wallets/Cargo.toml
deny.toml

closes #10326 
https://github.com/foundry-rs/foundry/pull/10158 introduced aws-lc-rs which broke this default:
ref https://github.com/snapview/tokio-tungstenite/issues/353#issuecomment-2455100010
> if exactly one of the two providers is available (that is, your application and all its dependencies only select either via features), it will be the default one.
the proper way of doing this is installing the default crypto provider manually.

fix: force install default crypto provider

---

crates/sol-macro-gen/src/sol_macro_gen.rs

closes #10317 
Add derive `serde::Serialize` and `serde::Deserialize` to generated rust binding when generate via `forge bind`. Won't add derive if use with flag `--skip-extra-derives`.

feat: add serde derive to forge bind

---

crates/evm/traces/src/debug/mod.rs
crates/forge/tests/cli/test_optimizer.rs

- for a preprocessed test contract like
```Solidity
contract CounterTest is Test {
Counter public counter;
create_counter(0);
}
function test_Increment() public {
create_counter(0);
counter.increment();
assertEq(counter.number(), 1);
}
function create_counter(uint256 number) internal {
counter = new Counter();
counter.setNumber(number);
}
}
```
running with `--decode-internal` flag panics with
```bash
Message:  byte index 671 is out of bounds of `// SPDX-License-Identifier: UNLICENSED
import {Test, console} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";
contract CounterTest is Test {
Counter public counter;
`[...]
Location: crates/evm/traces/src/debug/mod.rs:204
```
This happens because …

fix(forge): avoid panic on internal decoding of linked tests

---

Cargo.lock
Cargo.toml
crates/test-utils/Cargo.toml
crates/test-utils/src/lib.rs

See https://docs.rs/crate/idna_adapter/latest. We use Cargo.toml pinning instead of Cargo.lock since any `cargo update` would update to the latest version

chore(deps): use unicode-rs as the idna backend

---

.config/nextest.toml
Cargo.lock
crates/chisel/Cargo.toml
crates/chisel/tests/cache.rs

`serial_test` does not work with nextest.
See https://nexte.st/docs/configuration/test-groups.

test: move serial_tests to nextest test groups

---

crates/verify/src/bytecode.rs
crates/verify/src/utils.rs

chore: metadata hash extraction cleanup

---

Cargo.lock
Cargo.toml
crates/common/Cargo.toml
crates/common/src/serde_helpers.rs
crates/forge/Cargo.toml
crates/forge/src/result.rs
crates/forge/tests/fixtures/SimpleContractTestNonVerbose.json
crates/forge/tests/fixtures/SimpleContractTestVerbose.json

The format is the same as humantime. Also add it to the inner `duration` in `TestResult`.
Before:
```json
{"test/Counter.t.sol:CounterTest":{"duration":"6ms 306us 765ns","test_results":{"testFuzz_SetNumber(uint256)":{"status":"Success","reason":null,"counterexample":null,"logs":[],"decoded_logs":[],"kind":{"Fuzz":{"first_case":{"calldata":"0x5c7f60d70000000000000000000000000000000000000000000000000000000000001477","gas":53570,"stipend":21216},"runs":256,"mean_gas":31965,"median_gas":32354}},"traces":[],"labeled_addresses":{},"duration":{"secs":0,"nanos":4319680},"breakpoints":{},"gas_snapshots":{}},"test_Increment()":{"status":"Success","reason":null,"counterexample":null,"logs":[],"decoded_logs":[],"kind":{"Unit":{"gas":31851}},"traces":[],"labeled_addresses":{},"duration":{"secs":0,"nano …
```

chore(deps): replace humantime with jiff

---

Cargo.lock
Cargo.toml
crates/anvil/Cargo.toml
crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/evm.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mod.rs
crates/anvil/src/eth/error.rs
crates/anvil/src/eth/pool/transactions.rs
crates/anvil/src/lib.rs
crates/anvil/tests/it/fork.rs
crates/evm/core/Cargo.toml
crates/evm/core/src/env.rs
crates/evm/core/src/fork/init.rs
crates/evm/core/src/opts.rs
crates/evm/evm/src/executors/mod.rs

Adds OP Support to anvil using revm 21 
To be merged into #10361 
- Introduce `EitherEvm` which is an enum with EthEvm and OpEvm as its variants
- Impl `alloy_evm::Evm` for `EitherEvm` which delegates the transact request to the correct EVM depending on whether `--optimism` has been enabled
- impl `Evm` works over vanilla eth `TxEnv` but the transact results are mapped to `OpHaltReason` and `EVMError<DBError, OpTransactionError>`. Opted for OP result and error types as they are supersets of the eth types.

feat(`anvil`): op support revm 21

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/traces.rs

`from_block` and `to_block` can be equal. That is not invalid.
Fix the check.

fix(anvil): trace_filter same to and from block range is valid

---

crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs

After transition to `alloy_evm::EthEvm` in https://github.com/foundry-rs/foundry/pull/10412. We should be using `transact` from the `alloy_evm::Evm` trait and not transact from `revm::ExecuteEvm`.
- Use `alloy_evm::Evm::transact` which calls the inspector before transacting. 
This is the reason why the panic had disappeared, it is now back.

fix: use `transact` from alloy-evm

---

crates/forge/src/coverage.rs
crates/forge/tests/cli/coverage.rs

- closes #10422 
- https://github.com/foundry-rs/foundry/commit/5b8416363c7c1aab6d3cda0da6e7c65594ad8a12 fixed an issue where lcov reports were doubled due to adding them both as lines and as statements, by not accounting statement hits
- turns out this breaks do / while report for block statements
- added back the DA line from statement if it wasn't already generated as line statement - this prevents doubling it but also properly generate lcov report if only statements recorded
- added test to prevent regression

fix(forge): show lcov hits for do while statements

---

Cargo.lock
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mod.rs
crates/evm/core/Cargo.toml
crates/evm/core/src/either_evm.rs
crates/evm/core/src/lib.rs

Move `EitherEvm` to `foundry_evm_core` from anvil
Prep for adding OP support to forge
Next steps:
1. EitherEvm integration into the Cow Backend and InspectorStack
- Move `EitherEvm` 
- Rename type Aliases

chore: mv EitherEvm to foundry_evm

---

Cargo.lock
Cargo.toml
crates/anvil/tests/it/fork.rs
crates/cast/src/cmd/artifact.rs
crates/cast/src/cmd/constructor_args.rs
crates/cast/src/cmd/creation_code.rs
crates/cast/src/cmd/interface.rs
crates/cast/src/cmd/run.rs
crates/cast/src/cmd/storage.rs
crates/cast/src/tx.rs
crates/cast/tests/cli/main.rs
crates/cli/Cargo.toml
crates/cli/src/opts/rpc.rs
crates/cli/src/utils/abi.rs
crates/common/src/abi.rs
crates/config/src/etherscan.rs
crates/config/src/lib.rs
crates/forge/src/cmd/clone.rs
crates/forge/src/cmd/create.rs
crates/forge/src/cmd/test/mod.rs
crates/forge/tests/cli/cmd.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/cli/verify_bytecode.rs
crates/script/Cargo.toml
crates/script/src/lib.rs
crates/test-utils/src/rpc.rs
crates/verify/src/bytecode.rs
crates/verify/src/etherscan/mod.rs
crates/verify/src/provider.rs
crates/verify/src/verify.rs

- closes #9196
- builds on top of https://github.com/foundry-rs/foundry/pull/10298
- single `Etherscan` provider, default to V2; custom verifier providers use V1
- `foundry.toml` config as
```toml
[etherscan]
sepolia = { key = "$KEY"}
optimisim = { key = "$KEY" }
base-sepolia = { key = "$KEY_V1", api-version="v1" }
```
or `etherscan_api_version = "v2"` in top level foundry.toml
- new `--etherscan-api-version` to forge and cast commands (added for v1 compatibility), defaults to v2
- chisel supports v2 only (for fetch commands)

feat: Etherscan V2 support

---

crates/cast/src/cmd/send.rs
crates/cast/tests/cli/main.rs

closes #9918
adds manual checks for conflicting create missing to types
ref https://github.com/alloy-rs/alloy/pull/2412

fix: add check for conflicting create

---

crates/cast/src/base.rs

There was an existing `// TODO: test for octal` in the `test_format_neg` unit test. This change implements that test by properly setting the base to octal and validating the output of `NumberWithBase::format()` for negative integers.
- Implemented octal formatting for negative numbers using `NumberWithBase::from(i).set_base(Octal).format()`.
- Removed the `TODO` comment as the test is now complete.
- Ensured consistency with other format base tests (binary, decimal, hex).
---

test(`cast`): add and enable negative octal formatting test

---

crates/anvil/src/eth/api.rs

ref #10452
mining a block is a blocking operation as far as tokio is concerned, because this can take a relatively long time even in non-forking mode and in forking mode this can be significantly worse due to all the db lookups=rpc requests.
hence we should spawn these request handlers as blocking tasks.
it's possible that recent db change handling made this process a bit more expensive which could have caused #10452

perf: spawn mining on blocking

---

crates/cheatcodes/src/script.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue10477.t.sol

fix(forge): Set empty code if the 7702 delegation address is 0x

---

crates/anvil/core/src/types.rs
crates/anvil/src/eth/api.rs

this type is also part of alloy rpc types and can be imported from there

chore: rm work type

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/env.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/src/eth/backend/mod.rs
crates/anvil/src/eth/backend/validate.rs
crates/cast/src/cmd/run.rs
crates/evm/core/src/env.rs
crates/evm/core/src/fork/init.rs
crates/evm/core/src/opts.rs
crates/evm/core/src/utils.rs
crates/evm/evm/src/executors/mod.rs

Related: https://github.com/foundry-rs/foundry/pull/10183
>we should keep the logic for setting enveloped_tx
https://github.com/foundry-rs/foundry/pull/10183#discussion_r2079573383
>could we introduce a separate type for anvil that would store OpTransaction instead of TxEnv here to fix it?
https://github.com/foundry-rs/foundry/pull/10183#discussion_r2079585533
- Adds separate Anvil specific `Env` with an `OpTransaction` field, implements `AsEnvMut` to convert to Foundry's `Env`
- Adds back `enveloped_tx` setting

chore: avoid leaking Anvil specific optimism fields into evm/core

---

crates/common/src/preprocessor/deps.rs
crates/forge/tests/cli/test_optimizer.rs

- closes #10492 
- create helper fn for new expressions
- reuse in `visit_stmt` if statement is try. Continue control flow if deps extracted.
For try contract creation
```Solidity
try new Counter(1) {} catch {}
```
generate source as
```Solidity
try VmContractHelper(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D).deployCode({_artifact: "src/Counter.sol:Counter", _args: encodeArgs23(DeployHelper23.FoundryPpConstructorArgs(1))})` {} catch {}
```
- tests

fix(forge): support preproc with try contract creation

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/sign.rs
crates/anvil/tests/it/eip7702.rs

we were missing 7702 variant for the ethsendtransaction endpoint

feat: add 7702 support to eth-sendtransaction

---

crates/anvil/src/eth/backend/mem/storage.rs
crates/anvil/tests/it/state.rs

ensure blocks are sorted so that last is always highest, otherwise this can be nondeterministic
ref #10488
cc @naps62

fix: sort blocks by number

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/backend/mem/storage.rs

Alternative fix to #10505 , which is itself a fix for https://github.com/foundry-rs/foundry/pull/10488
this works by finding the latest block when loading state, instead of performing a full block sort when saving, which adds unnecessary overhead
cc/ @mattsse @grandizzy

perf: find latest block for next-base-fee. replaces #10505

---

crates/anvil/src/eth/api.rs

the number of auths impacts the min gas, so we should respect that when picking the lowest gas during ethestimate

chore: account for auths in 7702 min estimated gas

---

crates/fmt/src/buffer.rs

Fix: #10519.
Changing the `index+1` to `index+ch.len_utf8()`, Since Unicode space is not just one byte, the index should be adjusted based on UTF-8 length.
Check the implementation of the `is_whitespace` in std lib:
https://github.com/rust-lang/rust/blob/414482f6a0d4e7290f614300581a0b55442552a3/library/core/src/char/methods.rs#L891-L896
and https://en.wikipedia.org/wiki/Non-breaking_space

fix: fix formating crash caused by non-breaking space in comment.

---

Makefile

Fix #10525
use explicitly `nightly` toolchain in Makefile `lint-foundry` target.

fix(`Makefile`): update `lint-foundry` target to explicitly use nightly

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/script.rs
testdata/cheats/Vm.sol
testdata/default/cheats/AttachDelegation.t.sol

- closes #10517 
- add sigs with `crossChain` arg (sets nonce to 0)
```Solidity
function signDelegation(address implementation, uint256 privateKey, bool crossChain) external returns (SignedDelegation memory signedDelegation);
function attachDelegation(SignedDelegation calldata signedDelegation, bool crossChain) external;
function signAndAttachDelegation(address implementation, uint256 privateKey, bool crossChain) external returns (SignedDelegation memory signedDelegation);
```

feat(forge): cheatcodes to crosschain sign and attach delegation

---

crates/common/src/contracts.rs
crates/forge/tests/cli/cmd.rs

Closes #10531 
- There maybe multiple contracts with the same name in a project. 
- `find_contract_path` from compilers: https://github.com/foundry-rs/compilers/blob/b1b9e58d276b8b2635149ede841dce96b10b79f4/crates/compilers/src/lib.rs#L409 would fail in this case as it is geared towards finding a path using only the contract name.
- Try to find the target using the path if present, fallback to `find_contract_path`

fix(`common`): find target by path if present

---

crates/forge/src/cmd/inspect.rs
crates/forge/tests/cli/cmd.rs

We need a stable way of getting the standard JSON input from a foundry project. There is also an existing related issue for this https://github.com/foundry-rs/book/issues/1350.
Add a new field option to `forge inspect` command to allow it to output the standard JSON input retrieved from the project.

Add standard-json as inspect output field

---

Cargo.lock
Cargo.toml
crates/fmt/src/formatter.rs
crates/fmt/src/solang_ext/ast_eq.rs
crates/fmt/src/solang_ext/loc.rs
crates/fmt/src/solang_ext/mod.rs
crates/fmt/src/visit.rs
crates/fmt/testdata/VariableDefinition/fmt.sol
crates/fmt/testdata/VariableDefinition/original.sol
crates/fmt/testdata/VariableDefinition/override-spacing.fmt.sol
crates/fmt/tests/formatter.rs
crates/forge/src/cmd/fmt.rs

Hotpatch to foundry-solang-parser maintained at https://github.com/danipopes/solang (branch new-features) ([diff](https://github.com/hyperledger-solang/solang/compare/main...DaniPopes:solang:new-features)) for the following fixes:
- fixes #9088
- fixes #10244
note that this does not support more than just number literals in "layout at" due to a bug in solang-parser / lalrpop (build script runs forever if we allow any expression in that position)

fix: patch solang-parser

---

crates/cheatcodes/src/evm.rs
crates/forge/tests/cli/test_cmd.rs

- closes #10544
- mark all storage slots cold instead cleaning storage - prevent panic in revm when we have storage changed but value does not exists anymore https://github.com/bluealloy/revm/blob/c725ef791161a5ea3014191a73127392021c5371/crates/revm/src/journaled_state.rs#L402

fix(forge): vm.cool mark cold instead storage cleaning

---

crates/cast/src/cmd/wallet/mod.rs

closes #10424
Adds some extra logging to the signing of a transaction.
I simply added two logs at the end of signing. 
I wonder if this might be considered a breaking change? If some tools rely on the cli output to only return the signature, they would need to add extra parsing... 
We could add a verbosity flag, open to ideas

feat(cast): Verbose signing output

---

Cargo.lock
Cargo.toml
crates/fmt/testdata/NonKeywords/fmt.sol
crates/fmt/testdata/NonKeywords/original.sol
crates/fmt/tests/formatter.rs

Unfortunately it looks like it's the only one we can special case without blowing up the solang-parser build script, same limitation as in only allowing number literals in "layout at" specifiers.
Fixes https://github.com/foundry-rs/foundry/issues/10554.

fix(fmt): 'at' is not a keyword

---

crates/sol-macro-gen/src/sol_macro_gen.rs

Closes: https://github.com/foundry-rs/foundry/issues/10321
Noticed Alloy bindings by default would add `Serde` derives but would not add `serde` as a dependency.
If the `--skip-extra-derives` flag is passed we won't add it.
Was able to reproduce `forge bind` prior to 1.0 bump would fail to build as noted here: https://github.com/foundry-rs/foundry/issues/10321#issuecomment-2811885228
Manually confirmed `forge bind` to now run succesfully post-1.0 with this fix.

fix(`forge bind`): add `serde` as a dependency to generated `Cargo.toml` if `Serde` is being derived in bindings

---

Cargo.lock
Cargo.toml

fixes a regression with bloom filters for eth_getLogs

chore: bump alloy 1.0.5

---

crates/evm/core/src/backend/mod.rs
crates/forge/tests/cli/test_cmd.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue10552.t.sol

- closes #10552 
- prev fix for https://github.com/foundry-rs/foundry/issues/10296 didn't account all changes and introduced regression due to replacing entire persistent accounts when new fork selected
- make sure all persistent accounts on the newly selected fork reflect same state as the active db. It can get out of sync when first action in test is to select a different fork than the one used in `setUp` to change the persistent contract

forge(fix): update persistent storage from active db

---

Cargo.lock
Cargo.toml
crates/anvil/src/evm.rs
crates/evm/core/src/either_evm.rs
crates/evm/core/src/evm.rs

Closes: https://github.com/foundry-rs/foundry/issues/10562
Bumps to `alloy-evm` and `alloy-op-evm` to 0.9.1 which includes https://github.com/alloy-rs/evm/pull/93
Applies changes, minor nit to use `OpSpecId::default` instead of hardcoding to `Isthmus` in test that asserts defaults

chore: avoid unnecessary use of `inspector_mut`, `precompiles_mut` in precompile injection

---

Cargo.lock
Cargo.toml
crates/cast/Cargo.toml
crates/cast/src/args.rs
crates/cast/src/cmd/da_estimate.rs
crates/cast/src/cmd/mod.rs
crates/cast/src/opts.rs
crates/cast/tests/cli/main.rs

on opstack the sequencer may enforce a DA limit per block, this new command displays the total estimated size of a da block
adds a new cast subcommand that estimates the DA size of an opstack block

feat: add cast da-estimate

---

crates/evm/evm/src/inspectors/revert_diagnostic.rs

hotfix to address @DaniPopes' latest round of feedback on the already merged PR:
- https://github.com/foundry-rs/foundry/pull/10446#event-17751721722

fix: refactor `step` and `step_end` for clarity

---

crates/evm/core/src/utils.rs

- Includes Rootstock testnet in workaround due to missing `block.prevrandao` (mix_hash) field in block header
- Rootstock (Bitcoin sidechain) is EVM-compatible but operates under a different consensus mechanism due to which mix_hash / block.prerandao semantics does not apply on Rootstock
Merging this PR will successfully fix the following error: 
```
Error: Failed to deploy script:
EVM error; header validation error: `prevrandao` not set
```
Merging this PR will unblock developers to use latest foundry version with Rootstock testnet as Rootstock supports the EVM version (cancun) which is default version in foundry with the exception of prevrandao semantics which does not apply on rootstock network. 
Previously this fix was applied in …

Force `prevrandao` on Rootstock testnet

---

crates/lint/src/sol/info/mixed_case.rs
crates/lint/testdata/MixedCase.sol
crates/lint/testdata/MixedCase.stderr

as raised on:
- https://github.com/foundry-rs/foundry/issues/10599
`forge lint` currently flags any functions which do not stick to mixedCase. This PR modifies `fn is_mixed_case()` to disable warnings on function names that start with `test*`, `invariant*`, and `statefulFuzz*`.

fix(forge lint): do not flag `fn test*` and `fn invariant*`

---

crates/cast/src/cmd/wallet/mod.rs
crates/cast/tests/cli/main.rs

closes #10613
sign does this:
https://github.com/foundry-rs/foundry/blob/17db1eacd422c3023b74c17a6a34ecc85ec41d0c/crates/cast/src/cmd/wallet/mod.rs#L458-L458
while verify didn't
this adds the same call to verify, although I'm not 100% sure we can do this without causing side-effects

fix: make sign and verify symmetrical

---

crates/cast/src/tx.rs

closes #10204
this was caused by outdated legacy match in chains which incorrectly determined that bsc only supports legacy txs, updated here: https://github.com/alloy-rs/chains/pull/165
this fix in this pr works independently because this now also checks the auth field together with `is_legacy`

fix: check for auth when deriving legacy

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/tests/it/fork.rs

Adds an `addBalance` anvil endpoint as a convenience endpoint to bring on par with Tenderly endpoints https://docs.tenderly.co/virtual-testnets/admin-rpc#tenderly_addbalance
Simple fetch of current balance and increase using the existing `setBalance` endpoint.

feat: implement add_balance endpoint

---

Cargo.lock
crates/sol-macro-gen/Cargo.toml
crates/sol-macro-gen/src/sol_macro_gen.rs

The file names generated by `forge bind` currently use `CamelCase`/`PascalCase`, which goes against Rust’s convention of using `snake_case` for file names. Closes #10524 .
Replaced `.to_lowercase()` with `.to_snake_case()` using the [`heck`](https://docs.rs/heck/latest/heck/) crate, so that contract names are correctly transformed to `snake_case` when generating Rust binding file names.

fix(bindings): ensure forge bind generates snake_case file names

---

crates/cast/src/cmd/mktx.rs
crates/cast/tests/cli/main.rs

Resolve #10629 by adding "--ethsign" option to `cast mktx` command.
- Sign transactions using "eth_signTransaction" on local node with unlocked accounts.
- Same TX building logic as in "cast send --unlocked".
- Added a test case to validate the new functionality.
This new "--ethsign" option conflicts with "--raw-unsigned", this is properly declared in the Clap macro.

feat(cast mktx): add support for "--ethsign" option

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/tests/it/anvil_api.rs

Closes #10652 
Return `Prague` as the default/latest hardfork in `get_hardfork`

fix(`anvil`): latest evm version should be prague

---

Cargo.lock
Cargo.toml
crates/fmt/testdata/NonKeywords/fmt.sol
crates/fmt/testdata/NonKeywords/original.sol
crates/fmt/tests/formatter.rs

Same as https://github.com/foundry-rs/foundry/pull/10556, but still doesn't allow `layout` everywhere due to limitations described in previous PRs (only `layout = x;` is not allowed, but `uint layout = x;` and everywhere else is).
With this PR, this is the most we can allow of the new not-actually-keyword keywords.
Fixes https://github.com/foundry-rs/foundry/issues/10654.

fix(fmt): 'layout' is not a keyword

---

Cargo.lock
Cargo.toml
crates/fmt/testdata/NonKeywords/fmt.sol
crates/fmt/testdata/NonKeywords/original.sol
crates/fmt/tests/formatter.rs
crates/test-utils/src/rpc.rs

- backport https://github.com/foundry-rs/foundry/pull/10656
- fix ci:  backport https://github.com/foundry-rs/foundry/pull/10592 to use optimisim mainnet
- chore: bump version to 1.2.2

fix(fmt): 'layout' is not a keyword (backport to 1.2.2)

---

crates/forge/src/cmd/lint.rs
crates/lint/src/sol/gas/keccak.rs
crates/lint/src/sol/mod.rs
crates/lint/testdata/Keccak256.sol
crates/lint/testdata/Keccak256.stderr

closes: https://github.com/foundry-rs/foundry/issues/10663
- disable gas-related lints for test and script files
- reduce the amount of false positives for keccak256
previously, any time keccak256 was used, it would be flag as an unoptimized usage.
with this change, those hashes which simply hash a single literal (i.e. `keccak256("hello")` or `keccak256(1234)`) won't be flagged, as the compiler should inline its hash.

fix(forge lint): gas lints

---

crates/anvil/src/eth/backend/mem/mod.rs

we didn't populate the txhash and blockhash fields for the logs in the simulated block response

fix: populate missing fields for eth simulate

---

crates/anvil/tests/it/anvil_api.rs
crates/forge/tests/it/fuzz.rs
testdata/default/repros/Issue10527.t.sol

- fix fuzz timeout test by bumping the max rejects value (test finished in 537.34ms when timeout is set to 1s) https://github.com/foundry-rs/foundry/actions/runs/15410116103/job/43360205142#step:12:704
- attempt to fix anvil reorg test by using http provider instead ws https://github.com/foundry-rs/foundry/actions/runs/15414283452/job/43373308903#step:12:207
- fix flaky 10527 repro test https://github.com/foundry-rs/foundry/actions/runs/15410116103/job/43360205150#step:12:413

chore: fix flaky test, bump timeout max rejects, use http provider

---

crates/script/src/lib.rs

feat: added disable-code-size-limit flag in forge script

---

crates/evm/core/src/utils.rs

closes #10706
this is a legacy revm style bug where the txenv isn't fully updated
we should consider adapting more alloy-evm style oneshot `tx -> txenv` conversion patterns for this

fix: always update auth txenv var

---

crates/anvil/src/eth/backend/mem/mod.rs

fix: guard against the blockchain advancing while checking latest block
- backport fix for https://github.com/foundry-rs/foundry/issues/10709 to v1.2.3

fix(anvil): guard against the blockchain advancing while checking latest block (backport to v1.2.3)

---

crates/script/src/broadcast.rs
crates/script/src/receipts.rs

This PR removes hardcoded `ETH` symbol on tx broadcast and show native token symbol from the chain. The reason is currently hardcoded symbol `ETH` is used which does reflect the correct token symbol on every chain. This PR makes it dynamic as per chain on which tx is being broadcasted., 
```
Script ran successfully.
==========================
Chain 31
Estimated gas price: 0.004878086 gwei
Estimated total gas used for script: 217644
Estimated amount required: 0.000001061686149384 tRBTC
==========================
✅  [Success] Hash: 0xb1ba7f566d61a40d2edca28067215bf2e276800ea10dde294d72ab24debace86
Contract Address: 0xD888957bA1Bf2B5a99901965469430b5F8dfcA9F
Block: 6491436
Paid: 0.000000816684280034 tRBTC (167419 gas * 0.004878086 gwei) …
```

show native token symbol on tx broadcast

---

crates/forge/src/cmd/coverage.rs

- add option to exclude tests from generated coverage report
- keep default behavior, no breaking
- e.g. for morpho blue running without flag
vs running with `--exclude-tests`

feat(forge): `--exclude-tests` option from coverage

---

.github/workflows/test.yml

Likely was pinned because of a bug at the time, should be unpinned now

chore: unpin `rustfmt` nightly

---

crates/anvil/src/eth/otterscan/api.rs

I've upstreamed these helpers to alloy directly so we can reuse them here instead
https://github.com/alloy-rs/alloy/blob/c9438a15e3fddfdcaf0f6d30af323b83def51608/crates/rpc-types-trace/src/otterscan.rs#L100-L100
https://github.com/alloy-rs/alloy/blob/c9438a15e3fddfdcaf0f6d30af323b83def51608/crates/rpc-types-trace/src/parity.rs#L247-L257

chore: use native alloy functions for otterscan helpers

---

crates/anvil/tests/it/anvil_api.rs
crates/forge/tests/cli/script.rs

---
**Description:**  
- Fixed a typo in the test identifier: `can_remember_keys` (was `can_rember_keys`)
---

Fix typos in test identifiers and improve timestamp assertions

---

crates/cast/src/cmd/send.rs

cargo build raises the below warning:
```
> warning: this function depends on never type fallback being `()`
>    --> crates/cast/src/cmd/send.rs:89:5
>     |
> 89  |     pub async fn run(self) -> eyre::Result<()> {
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = help: specify the types explicitly
> note: in edition 2024, the requirement `for<'de> !: Deserialize<'de>` will fail
>    --> crates/cast/src/cmd/send.rs:157:26
>     |
> 157 |                         .raw_request(
>     |                          ^^^^^^^^^^^
> help: use `()` annotations to avoid fallback changes
>     |
> 157 |                         .raw_request::<_, ()>(
>     |                                     +++++++++
>
```

cast: rm expect dependency_on_unit_never_type_fallback

---

crates/anvil/core/src/eth/transaction/mod.rs
crates/anvil/src/eth/api.rs
crates/anvil/src/eth/miner.rs
crates/anvil/tests/it/anvil_api.rs

Resolved several minor typos and inconsistencies across the Anvil crate:
- Changed agan to again in mod.rs
- Corrected endppoints to endpoints in api.rs
- Fixed minner to miner in miner.rs
-Renamed test function test_mine_blks_with_same_timestamp to test_mine_blk_with_same_timestamp for consistency with its purpose
These improvements enhance code readability and maintain naming clarity.

Fix typos in Anvil module comments, docs, and test names

---

crates/cast/src/opts.rs
crates/cast/tests/cli/main.rs
crates/forge/src/opts.rs
crates/forge/tests/cli/cmd.rs

this goes to 404 page
```bash
echo -e '\e]8;;https://getfoundry.sh/forge/overview\ahttps://getfoundry.sh/forge/overview\e]8;;\a'
```
<https://getfoundry.sh/forge/overview>

fix(links): update foundry book links

---

crates/forge/src/cmd/doc/server.rs

Closes: https://github.com/foundry-rs/foundry/issues/10850
Confirming https://github.com/foundry-rs/foundry/issues/9931 has been fixed.
Panic was due to a breaking change in Axum, not allowing nesting services at the root. For our simple usecase of serving files from the root `/` we can use the fallback_service instead.
Manually tested in combination w/ #9931

fix: forge doc panic

---

Cargo.lock
Cargo.toml

Closes: https://github.com/foundry-rs/foundry/issues/10904
There is currently an issue with `alloy-chains` `0.2.5` that causes duplicate `chainid` fields to be set in the query causing requests to fail. A fix is in place here: https://github.com/foundry-rs/block-explorers/pull/93
Ref: https://github.com/alloy-rs/chains/pull/174
Ref: https://github.com/foundry-rs/foundry/issues/10904#issuecomment-3028860350
With `alloy-chains` `0.2.5` this would previously throw:
```
cast source --chain polygon 0x794a61358D6845594F94dc1DB02A252b5b4814aD --etherscan-api-key <API_KEY>
Error: Received error response: status=0,message=NOTOK, result=Some("Missing or unsupported chainid parameter (required for v2 api), please see https://api.etherscan.io/v2/chainlist for the list of supported chainids")
```
Now …

fix(`cast`): bump alloy-chains to 0.2.5 for Ethereum V2 API compatility w/ `cast`

---

crates/evm/core/src/evm.rs

- The `test_revert_wrong_chainid` was failing becuase revm introduced a chain id and transaction validation which is set to false by default.
- Enable the chain-id check upon evm instantiation

fix(`evm`): enable tx_chain_id_check

---

crates/config/src/fuzz.rs
crates/evm/evm/src/executors/fuzz/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/stack.rs
crates/forge/tests/cli/config.rs
crates/forge/tests/it/fuzz.rs
crates/forge/tests/it/test_helpers.rs

Closes #10878 
- add `fail_on_revert` for FuzzConfig, defaults to true
- record address of reverter in `RawCallResult`
- on fuzz tests do not fail test if `fail_on_revert=false` and call reverted by different address than cheatcode or test

feat(forge): apply fail_on_revert for fuzz tests too

---

crates/cast/tests/cli/main.rs
crates/cli/src/utils/abi.rs
crates/common/src/abi.rs

Closes https://github.com/foundry-rs/foundry/issues/10947
Closes https://github.com/foundry-rs/foundry/issues/10947. 
Issue was that the function selector was prefixed to the arguments on create calls.
Added function `encode_function_args_raw`, which encodes function args without prefixing the function selector.
This is now used in `parse_function_args` when the to field is none, indicating a create call.
I don't really know if tests are needed for this, but I don't mind adding one for create calls in general since the current ones aren't really sufficient.

fix(cast call/estimate/send): omit function selector from arguments on create calls

---

foundryup/foundryup

Follow up for: https://github.com/foundry-rs/foundry/pull/10902
It occurred to me last night that because we versioned `foundryup` we can inform the user their installation is out of date by matching it against the version of the current version on `master`
You can test the functionality by changing `FOUNDRYUP_INSTALLER_VERSION="1.3.0"` to `FOUNDRYUP_INSTALLER_VERSION="1.0.0"`
If the version of the installer is greater than the one on `master` we proceed without informing.
Note that this update will only inform / warn users when they run `foundryup`. It does not result in a hard error.

feat(`foundryup`): compare installed versus remote version of `foundryup` and inform user update of `foundryup` is available

---

crates/evm/core/src/evm.rs

Revm 27 introduces the `InspectorHandler` which overrides the `Handler` implementation. 
- Since foundry is always inspecting we can remove the vanilla `Handler` impl and only keep the `InspectorHandler`

fix(`evm`): remove Handler impl for `FoundryHandler`

---

crates/chisel/src/runner.rs

- Completed an unfinished inline comment explaining the gas limit reset logic in the executor environment.
- Updated the docstring for the run function to remove the misleading word "Optionally," reflecting that the function always returns a tuple on success.
- These changes improve code clarity and ensure documentation accurately describes the function's behavior.

docs: Clarify comments in ChiselRunner: fix incomplete and misleading docstrings

---

crates/config/src/lib.rs
crates/config/src/utils.rs
crates/evm/core/src/opts.rs
crates/forge/tests/cli/config.rs

We currently allow users to specify as:
```toml
block_timestamp = 100123
block_number = 12345678
```
but serialize (when running `forge config`) / work internally with:
```toml
block_number = "0xbc614e"
block_timestamp = "0x1871b"
```
which is difficult to read / not in a format users regularly encounter when looking at a block explorer
We have a serialization method that attempts to fit the number in a `u64`, else serializing in `U256` per suggestion by @DaniPopes in https://github.com/foundry-rs/foundry/pull/10838#discussion_r2198134471
`foundry.toml` set as:
```toml
block_number = 12345678
block_timestamp = 100123
```
serializes as:
```toml
block_number = 12345678
block_timestamp = 100123
```
`foundry.toml` set as:
```toml
block_number = "0x732143"
block_timestamp = "0x123123"
``` …

feat(`revm bump`): add serialization method that serializes as `u64` if fits or `U256` if not

---

crates/anvil/src/eth/backend/mem/inspector.rs
crates/evm/evm/src/inspectors/logs.rs

we dont need these bounds
this will make #11005 easier
cc @Soubhik-10

chore: relax tracer bounds

---

CONTRIBUTING.md

This PR fixes multiple dead and outdated links found across the Foundry codebase, improving documentation quality and user experience.
- **CONTRIBUTING.md**:
- Updated Rust Code of Conduct link to current location
- Fixed GitHub documentation links (help.github.com → docs.github.com)
-  **Documentation links**: Updated to current GitHub docs structure
-  **Code of Conduct**: Updated to official Rust website
---

docs: Fix dead links across the codebase

---

crates/cheatcodes/src/evm/prank.rs
crates/cheatcodes/src/inspector.rs

Fixes: https://github.com/foundry-rs/foundry/issues/11021
Follow up of https://github.com/foundry-rs/foundry/pull/11023
Instead of only marking the account as touched when it `create`'s a new contract we should always mark it as `touched` when `pranked` so that account state (like `nonce`) is accurately tracked.
I don't see a realistic way `journaled_account` could error unless there is an actual issue with the underlying database / memory corruption.
The performance impact should be minimal, we already do this on many other cheatcodes and we do not load code or storage keys.

fix: ensure account is always loaded and marked as touched when pranked

---

.codespellrc
.github/workflows/test.yml
Makefile
crates/cli/src/utils/mod.rs
crates/forge/src/cmd/install.rs
crates/forge/src/cmd/update.rs
crates/forge/src/lockfile.rs
crates/forge/tests/cli/install.rs
crates/lint/src/linter/mod.rs
typos.toml

We still regularly get typo fix PRs because codespell doesn't catch as many as it should. Typos is better.

chore: migrate from codespell to typos

---

crates/cast/src/args.rs
crates/cast/src/opts.rs

Added an optional `chain_id: Option<u64>` field to the `ToCheckSumAddress` subcommand. The checksum conversion now uses the `chain_id` if provided; otherwise, it defaults to `None`, preserving current behavior. This enables support for both standard `EIP-55` and chain-aware `EIP-1191` checksum formats.

feat(cast): add checksum address with chain id

---

crates/anvil/src/config.rs
crates/anvil/src/eth/backend/executor.rs
crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/evm/traces/src/decoder/mod.rs

closes #11064
this uses the foundry signatures identifier cache if print-traces is enabled, we could extend this next with local ABIs.

feat: use signatures identifier for --print-traces

---

crates/lint/src/linter/mod.rs
crates/lint/src/sol/mod.rs

`fn solar_pcx_from_build_opts` calls `solar_pcx_from_solc_project` with `add_source_files = true`. Therefore, there is no need to load the sources, as they are already available on the pcx.
https://github.com/foundry-rs/foundry/blob/450f2c761f052d32ca2236009ef64d2e7910df93/crates/cli/src/opts/build/utils.rs#L70-L84
the fix is necessary —other than for performance reasons—, because otherwise the language and version filters done by `fn solar_pcx_from_build_opts` are useless.

fix: avoid reloading files to pcx

---

crates/anvil/src/eth/backend/mem/inspector.rs
crates/cheatcodes/src/inspector.rs
crates/evm/core/src/utils.rs
crates/evm/coverage/src/inspector.rs
crates/evm/evm/src/inspectors/script.rs
crates/evm/evm/src/inspectors/stack.rs
crates/evm/fuzz/src/inspector.rs

Removes overhead of `InspectorStackMutRef` for step/step_end, the rest of the functions are fine for code dedup.
About ~25-30% faster test execution speed.

perf: improve InspectorStack

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/evm/fork.rs
testdata/cheats/Vm.sol
testdata/default/cheats/GetRawBlockHeader.t.sol

A previous PR added `--raw` to `cast block` #11027. It would be even more useful if this functionality were available as a native cheatcode, eliminating the need for vm.ffi.
- Added `vm.getRawBlockHeader(blockNumber)` cheatcode that returns the RLP encoded block header corresponding to `blockNumber`.

feat(`cheats`): add `vm.getRawBlockHeader(blockNumber)`

---

crates/cheatcodes/src/inspector.rs
crates/evm/evm/src/executors/invariant/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/stack.rs
crates/evm/fuzz/src/inspector.rs

Reduces the size of `InspectorStack` and simplifies the `if let Some` checks to be simple null pointer checks. The one time memory allocation/deallocation cost is negligible compared to the gains from these small improvements.
~5-10% improvement on `forge test`.

perf: box inspectors in InspectorStack

---

crates/cast/tests/cli/selectors.rs
crates/evm/traces/src/identifier/signatures.rs

Reverts foundry-rs/foundry#11127
Reopens https://github.com/foundry-rs/foundry/issues/11125
Reverts this because we were previously caching non-matching selectors preventing excessive lookups on selectors we know we don't match. This was either implicit, accidental or not documented. Regardless this behavior is preferred over aggressive calling.
Looking to re-implement this but with the inclusion of a 1 hour cache on non-matching selectors. This requires some more consideration as users will have an old cache that is populated. Any change in the JSON structure could have serious side effects and the change needs to be backwards compatible.
Draft here: https://github.com/foundry-rs/foundry/compare/master...zerosnacks/add-selectors-cache-expiry-non-matching

Revert "fix(`cast`): unknown signatures are cached as an empty string"

---

crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/src/eth/error.rs

Closes: https://github.com/foundry-rs/foundry/issues/11128
Previously resulted in:
```
eth_simulateV1
Message:  called `Option::unwrap()` on a `None` value
Location: crates/anvil/src/eth/backend/mem/mod.rs:1729
8: core::panicking::panic::h4a11c031239f36a8
9: core::option::unwrap_failed::h62317944fa5dc382
10: anvil::eth::backend::mem::Backend::simulate::{{closure}}::{{closure}}::h4f7a2c0dde92fd30
11: …
```

fix(`anvil`): unwrap panic in `eth/backend/mem/mod.rs`

---

crates/anvil/core/src/eth/transaction/mod.rs

closes #11169
this should be okay, because this will get enforced by the evm and then bubbles up the appropriate error

fix: use empty 7702 auths

---

crates/anvil/src/eth/backend/db.rs
crates/anvil/tests/it/state.rs

Optimistically closes: https://github.com/foundry-rs/foundry/issues/11176
Implements backwards compatibility for loading Anvil state dumps generated with v1.2
Previously:
```
error: invalid value '<old state file>' for '--load-state <PATH>': failed to parse json file: "<old state file>": invalid type: string "0x1c9c380", expected u64 at line 1 column 129
```
now succeeds loading

fix(`anvil`): v1.2 state load compatibility

---

crates/evm/coverage/src/analysis.rs
crates/evm/coverage/src/lib.rs
crates/forge/tests/cli/coverage.rs

Add `.{index}` at the end of the function name if there are multiple with the same name in the same contract. This is easier than computing the function signature. Although we could also do that, I believe it's fine since usually it's not displayed but just an internal identifier.
Fixes https://github.com/foundry-rs/foundry/issues/11183.

fix(coverage): disambiguate duplicate function names

---

crates/evm/coverage/src/lib.rs
crates/forge/src/coverage.rs

Less clutter and useless information

chore(coverage): improve debug report

---

crates/anvil/src/tasks/block_listener.rs

Finished the previously incomplete doc comment for the BlockListener struct. The comment now clearly states that the future executes a given task for each new block that arrives on the stream, improving code clarity and documentation quality. No logic was changed.

Complete doc comment for BlockListener struct

---

crates/config/src/error.rs

Added a missing mapping for the `TooManyWarnings` error.
Mapping fetched from [here](https://github.com/foundry-rs/foundry/blob/master/crates/config/src/error.rs#L195)

chore: add missing error mapping

---

Cargo.lock
Cargo.toml
crates/forge/tests/cli/script.rs

Fixes https://github.com/foundry-rs/foundry/issues/11213
Pins revm to https://github.com/bluealloy/revm/tree/interpreter-is-end-flag which includes a fix for code that previously segfaulted
Bumping to revm 28 requires more work due to boxing changes in revm-inspectors, ref: https://github.com/foundry-rs/foundry/pull/11217

fix(`forge script`): repeated `vm.createSelectFork` with same RPC causes segfault

---

crates/anvil/src/eth/backend/mem/inspector.rs
crates/anvil/src/eth/backend/mem/mod.rs

fix(anvil): print traces for `eth_simulateV1`

---

crates/forge/tests/cli/script.rs
crates/script/src/lib.rs

Fix #11240
Default `sig` arg value form `run()` to `run`

fix(forge): makes forge script match correctly `run` function signature from source

---

crates/chisel/src/dispatcher.rs

The Fork command was displaying a misleading error message that mentioned
"session ID" when it actually expects a URL or RPC alias. This change
updates the error message to correctly indicate that the command requires
a URL or RPC alias as an argument, improving user experience and reducing
confusion.
- Fixes error message in ChiselCommand::Fork
- Changes "Must supply a session ID as the argument" to 
"Must supply a URL or RPC alias as the argument"

fix: correct error message in Fork command

---

crates/anvil/src/cmd.rs
crates/anvil/src/config.rs
crates/anvil/src/eth/backend/mem/mod.rs
crates/anvil/tests/it/txpool.rs

Close #11239
Add option to disable pool balance checks in EVM configuration.

feat(anvil): add option to disable pool balance checks in EVM configuration

---

crates/anvil/src/eth/error.rs

This PR corrects several minor typos in error message:
- `th` → `the`
These fixes help enhance readability and eliminate minor distractions during development and code reviews.
No logic or functionality has been modified.

fix: correct typos in error message

---

foundryup/foundryup

The manpage download step in `foundryup` installer was marked as "optional" but could actually crash the entire installation process due to `set -e -o pipefail` behavior. If the manpage archive was unavailable or corrupted, the `download | tar` pipeline would fail and terminate the script, even though binaries were already successfully installed.
Wrap the manpage download pipeline in an error check to make it truly optional:
- Add `if ! ...; then warn ...; fi` around the download/extract command
- Log a warning instead of crashing when manpage archive is unavailable
- Allow installation to complete successfully even if manpages fail

fix: make manpage download truly optional in foundryup installer

---

Dockerfile

Alpine image 3.22 is now labeled as latest.
Just to use latest base image.

chore(docker): bump alpine version to 3.22

---

crates/macros/src/cheatcodes.rs

`proc_macro_error2` only emits warnings when feature "nightly" is enabled, which we can't practically enable. This wasn't the case with `proc_macro_error`, which enabled it based on a build.rs that detected nightly version automatically.
Upgrade them to errors so they are actually shown.

chore: fix foundry-macros warnings

---

crates/evm/core/src/fork/init.rs

disables EIP-7825 gas limit cap by default
osaka is upcoming so we can bypass this entirely for the time being, but ideally this is also made a setting

fix: disable tx gas limit cap

---

crates/cheatcodes/src/evm.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue11353.t.sol

closes #11353
revm has a new check for txtype before returning the blobhash
this forces the tx to 4844 when we set blobhashes

fix: force 4844 txtype in blobhashes setter

---

Cargo.lock
Cargo.toml
crates/cheatcodes/src/evm.rs
crates/common/src/contracts.rs
crates/evm/core/src/fork/init.rs
crates/evm/traces/src/identifier/etherscan.rs
crates/forge/src/cmd/build.rs
crates/forge/src/lockfile.rs
crates/forge/tests/cli/lint.rs
crates/forge/tests/it/repros.rs
testdata/default/repros/Issue11353.t.sol

Fixes:
- fix for https://github.com/foundry-rs/foundry/issues/11219 (https://github.com/foundry-rs/foundry/pull/11224)
- fix for https://github.com/foundry-rs/foundry/issues/11234 also reported as https://github.com/foundry-rs/foundry/issues/11352 (https://github.com/foundry-rs/foundry/pull/11247)
- fix for https://github.com/foundry-rs/foundry/issues/11353 als reported as https://github.com/foundry-rs/foundry/issues/11362 (https://github.com/foundry-rs/foundry/pull/11355)
- fix for https://github.com/foundry-rs/foundry/issues/11351 (https://github.com/foundry-rs/foundry/pull/11356)
- fix for Osaka tx gas limit (https://github.com/foundry-rs/foundry/pull/11347)
- fix for https://github.com/foundry-rs/foundry/issues/11359 (https://github.com/foundry-rs/foundry/pull/11360)
Other:
- …

v1.3.2 backports

---

crates/cast/src/cmd/wallet/vanity.rs
crates/common/src/provider/mod.rs
crates/forge/tests/cli/cmd.rs
crates/script/src/build.rs
crates/script/src/verify.rs
crates/sol-macro-gen/src/sol_macro_gen.rs
crates/wallets/src/wallet.rs

This PR aggregates changes from the following PRs:
- Closes #11145 by @\Galoretka
- Closes #11294 by @\phrwlk
- Closes #11320 by @\ANtutov
- Closes #11379 by @\bethoffman

chore: aggregate PRs

---

crates/evm/traces/src/identifier/etherscan.rs

Base on the [conversation ](https://github.com/foundry-rs/foundry/pull/11373#issuecomment-3210079259)
The TODO here is not needed. Deleted the TODO

feat: Remove unneeded TODO in EtherscanIdentifier

---

crates/wallets/src/wallet.rs

Mention keystore, orders it to disincentivize use of raw private keys

chore(docs): mention keystore in wallet error message, improve readability

---

crates/cli/src/utils/mod.rs
crates/forge/src/cmd/update.rs
crates/forge/tests/cli/install.rs

Currently, `forge update owner/repo@branch` doesn't work correctly, as it fails to sync the branch with the remote and only updates it to the latest local commit of that branch. 
- If we're updating the lib to a branch, then we should fetch it from remote to make sure it has the latest commits, and then checkout the submodule.
- Update lockfile accordingly

fix(`forge`): sync branch with remote on update

---

crates/cheatcodes/src/evm.rs

Ref: https://github.com/foundry-rs/foundry/pull/11276#issuecomment-3205034758
The current approach would not identify storage changes on proxy contracts. 
- Identify whether the account being accessed is a proxy or not.
- We can do this by checking whether the bytecode contains one of the two `EIP1967_IMPL_SLOT` or `EIP1822_PROXIABLE_SLOT`
- Find the artifact accordingly
- Unify `get_contract_name` into `get_contract_data` since they do the same thing

fix(`cheatcodes`): identify common proxies in state diffs

---

crates/anvil/src/eth/backend/mem/mod.rs

Anvil block production should be deterministic to allow for more convenient integration testing on top of anvil.
Avoid using a random value for `prevandao`.
Fixes https://github.com/foundry-rs/foundry/issues/9570

fix(anvil): deterministic block production

---

crates/forge/src/cmd/test/mod.rs
crates/script/src/execute.rs
crates/script/src/lib.rs

Similar to `cast call`, add a `--disable-labels` flag to disable fetching the labels in the output of `forge script` and `forge test`.

feat(forge): add --disable-labels for forge script and test

---

crates/forge/tests/cli/lint.rs

- closes #11392 
- bug fixed by solar bump in https://github.com/foundry-rs/foundry/pull/11371
- adds test for prev failing scenario

chore: add lint test for constant params

---

crates/common/src/contracts.rs
crates/forge/src/multi_runner.rs
crates/forge/tests/cli/coverage.rs

- closes #11432 
- regression introduced https://github.com/foundry-rs/foundry/pull/11204/files#diff-7cf15eff5ea54b62e8810f2f11d2285a2783dc88ceb867ca0618a73487f1df60R522-R525 we need to create contracts by artifact from linked contracts
- introduce builder to create `ContractsByArtifact` from contracts iter and enrich with storage layouts (if available)

fix(coverage): contracts by artifact from linked contracts

---

crates/cheatcodes/assets/cheatcodes.json
crates/cheatcodes/spec/src/vm.rs
crates/cheatcodes/src/json.rs
crates/cheatcodes/src/toml.rs
testdata/cheats/Vm.sol
testdata/default/cheats/Json.t.sol
testdata/default/cheats/Toml.t.sol

last week we introduced `writeJsonUpsert` and `writeTomlUpsert`, which were 2 new cheatcodes that added the ability to not only update (like the previously existing `writeJson` and `writeToml` cheats), but also to add new k-v pairs:
- https://github.com/foundry-rs/foundry/pull/11414
after internal discussion, and given the fact that there were several community members asking for that feature:
- https://github.com/foundry-rs/foundry/issues/7232
this PR consolidates both cheatcodes into one: keeps the original name, but the new implementation with upsert capabilities

feat(cheats): json/toml --> consolidate `write` and `writeUpsert`

---

.github/workflows/test.yml

`force_orphan` makes it so that the branch always gets reset.
This job runs on-push, so every `git pull` on the repository will reset the `gh-pages` branch and pull everything from the remote, currently about ~20,000 files and ~20MiB, which is slow and useless. Let's try removing this option to see if it fixes this problem.

ci: drop force_orphan

---

crates/config/src/lib.rs
crates/forge/src/cmd/eip712.rs
crates/forge/tests/cli/eip712.rs

Towards https://github.com/foundry-rs/foundry/issues/11456.

chore(forge eip712): use solar from compiler output

---

Cargo.lock
Cargo.toml
crates/config/src/lib.rs

The call to solc when compiling involves parsing and analysis, which is the minimum work the compiler will do if nothing is requested, but this is still slow on the order of 100s of ms to a few seconds. We want to avoid this as much as possible because it's completely unused, as we're requesting nothing and we just want to run the pipeline to get the in-memory `solar` compiler from the output.
Together with updating foundry-compilers for a cache bug fix (https://github.com/foundry-rs/compilers/pull/312), this makes `solar_project` almost never call to solc.
Currently only used by `forge eip712` (https://github.com/foundry-rs/foundry/pull/11458), but will see more usage with https://github.com/foundry-rs/foundry/issues/11456.

feat: switch solar_project to use cache

---

crates/anvil/core/src/eth/transaction/mod.rs

feat: add missing eip7702 support

---

.github/workflows/npm.yml
npm/@foundry-rs/forge-darwin-amd64/package.json
npm/@foundry-rs/forge-linux-amd64/package.json
npm/@foundry-rs/forge-linux-arm64/package.json
npm/@foundry-rs/forge-win32-amd64/package.json
npm/scripts/prepublish.ts
npm/scripts/publish.ts

closes https://github.com/foundry-rs/foundry/issues/4337
verified working published version:
https://www.npmjs.com/package/@foundry-rs/forge-linux-amd64/v/1.3.2-nightly.20250902.99514b6
test:
```sh
bun x @foundry-rs/forge@1.3.2-nightly.20250902.99514b6 --help
```
related:
- https://github.com/oven-sh/bun/pull/22332
next:
- short docs mention of this install option,
- support for `anvil`, `cast`, and `chisel`
bonus: now handles `nightly` releases too.

chore: tweak `npm` publish & handle `nightly` releases

---

crates/evm/fuzz/src/lib.rs
crates/forge/src/result.rs
crates/forge/src/runner.rs
crates/forge/tests/it/table.rs

- closes #11066 
- addresses logs and coverage (https://github.com/foundry-rs/foundry/issues/11066#issuecomment-3264650676)

fix(forge): show logs and coverage for table tests

---

crates/common/src/contracts.rs
crates/common/src/utils.rs
testdata/default/cheats/RecordAccountAccesses.t.sol

Changes `find_by_deployed_code_exact` to also ignore the metadata hash at the end of bytecode. Review with "Hide whitespace"

feat: make `find_by_deployed_code_exact` smarter

---

crates/cheatcodes/src/toml.rs
testdata/default/cheats/Toml.t.sol
testdata/fixtures/Toml/test.toml

Fixes a potential panic when converting TOML float values containing `NaN`, `+inf`, or `-inf` to JSON format.
**Problem:**
- `serde_json::Number::from_f64()` returns `None` for non-finite values
- The code used `.unwrap()` which would panic on valid TOML input
- TOML spec allows these values, but JSON doesn't support them
**Solution:**
- Replace `unwrap()` with safe pattern matching
- Convert non-finite floats to string representation (`"NaN"`, `"inf"`, `"-inf"`)
- Maintains type safety and prevents unexpected crashes

Fix panic on NaN/Inf values in TOML to JSON conversion

---

crates/config/src/lib.rs
crates/forge/tests/cli/verify.rs
crates/verify/src/provider.rs
crates/verify/src/verify.rs

- closes #11430 
- config should not throw on non etherscan verifiers when chain not known by etherscan - issue introduced in https://github.com/foundry-rs/foundry/pull/11194/files#diff-0f348074359029c2930eb72b52f482c2e0f4495dc61b95bc919f155a8d2fd82cR1437-R1444. Instead should just continue as unknown etherscan chains could be supported by other verifiers like blockscout and sourcify.
- in place fix, needs a broader refactoring to reflect same code is used by etherscan-like verifiers and more tests for non-etherscan supported verifiers 
- consider backport to v1.3.3

fix(forge): custom verifiers should not throw on unknown etherscan chains

---

crates/evm/evm/src/executors/mod.rs
crates/forge/tests/cli/script.rs
crates/script/src/runner.rs

Currently, when we persist calls during simulation, we do not account for EIP-7702 authorization items.
This change implements an alternative path for 7702 transactions, just like we do for the non-persisting path.
Closes #11483

fix: persist auth items during simulation

---

crates/anvil/src/cmd.rs

**Security Issue Fixed**: Removed silent fallback to the well-known test mnemonic `"test test test test test test test test test test test junk"` when invalid word count is provided to `--mnemonic-random`.
When users specified an invalid word count (e.g., `anvil --mnemonic-random 13`), the code would silently fall back to `DEFAULT_MNEMONIC`, which is a publicly known test phrase. This created a security risk where users might unknowingly use predictable, insecure accounts.
- **Added warning logging** when invalid word count is detected
- **Generate secure random 12-word mnemonic** as fallback instead of using the test phrase
- **Preserve user intent** of having a random mnemonic while ensuring security

Fix: Replace unsafe mnemonic fallback with secure random generation

---

crates/common/src/evm.rs

Add #[serde(skip_serializing_if = "Option::is_none")] to EvmArgs.compute_units_per_second. Without this, the CLI provider serialized a null value into Figment, which overrides lower-precedence config values (e.g., foundry.toml or endpoint configs). This caused valid configured CUPS to be cleared and defaulted to 330 during extraction. Skipping serialization when None preserves downstream configuration precedence and aligns with how other Option fields in EvmArgs are handled.

chore(common): add serde skip for compute_units_per_second in EvmArgs

---

crates/config/src/lib.rs
crates/forge/tests/cli/config.rs

Add a log if `evm_version` is not compatible with the `solc` version, to avoid the confusion of the user.

chore: check compatibility of evm_version and solc

---

crates/common/src/provider/runtime_transport.rs

- Remove Error from #[derive(Clone, Debug, Error)] on RuntimeTransport to align semantics and avoid thiserror conflicts with manual Display.
- Delete unused RuntimeTransportError::LockError variant and its message; there are no call sites and tokio::RwLock here doesn’t produce such failures.

chore(common): clean RuntimeTransport derive and remove dead LockError

---

crates/anvil/src/config.rs

Replaces hardcoded `max_transactions: 1_000` with dynamic calculation based on block gas limit.
- Add `calculate_max_transactions_from_gas_limit()` function
- Auto-update `max_transactions` when gas limit changes
- Set reasonable cap at 10,000 transactions
- Add tests
- Formula: `gas_limit / 21_000` (min transaction gas)
- Default (30M gas): 1,428 transactions
- Capped at 10,000 for performance

feat(anvil): calculate max_transactions based on block gas capacity

---

crates/debugger/src/tui/mod.rs

- Remove unused tick_rate/last_tick and “Force update” code from event_listener.
- Switch to blocking event::read() and forward events via channel.
- This change eliminates dead/incomplete tick logic that never sent tick events, which could confuse maintainers and suggests behavior that doesn’t exist. Since the UI updates only on user input and doesn’t require periodic redraws, blocking read is the correct, simpler model. This reduces complexity and prevents misleading comments from implying periodic ticks.

feat(debugger): remove dead tick polling; use blocking read and forward

---

crates/debugger/src/tui/mod.rs

Similar to #11674, the event loop is entirely unneeded, so we don't need to spin up a separate thread.
Remove the event loop.

refactor: remove event loop from debugger

---

crates/config/src/lib.rs
crates/forge/tests/cli/eip712.rs

We need to request something so that we populate the artifacts in the cache in case it is the first compiler invocation. Requesting nothing at all will not return anything in the output, and so we would have no artifacts in the cache entry, resulting in incorrect "nothing to compile" results after the first run.
This is slightly slower due to extra serde but the actual work done by solc remains the same. Again ideally this doesn't call solc at all but this is a decent start.

fix: request ABI in solar_project

---

crates/anvil/src/eth/api.rs
crates/anvil/tests/it/fork.rs

closes #11714
fixes this again, also fixes bad log output because we didnt forward to the correct function

fix: ethgetaccinfo

---

crates/forge/src/cmd/generate/mod.rs
crates/forge/src/opts.rs

This command is very simplistic and does not achieve much other than a simple template replacement. This can easily be implemented in your editor or extension of choice as a macro, fitting your stylistic needs.

feat(forge): deprecate `generate`

---

crates/common/src/term.rs

The spinner used an invalid ANSI CSI introducer: \x33[2K (literal '3') instead of ESC \x1B[2K. As a result, terminals printed over shorter updates, leaving trailing characters from previous messages.
Correct sequence per ANSI/ECMA-48: ESC 0x1B (aka \x1B or \033), then [2K to erase the entire line.
before change: 
after:

fix(common): use proper ESC in spinner erase-line sequence

---

crates/forge/src/cmd/inspect.rs
crates/forge/tests/cli/cmd.rs

Its useful to be able to inspect which libraries a contract needs to dynamically link to.
Uses the `link_references` mapping already available on the artifact.

feat(forge-inspect): add ability to inspect libraries

---

crates/common/src/compile.rs
crates/common/src/term.rs
crates/forge/src/cmd/flatten.rs

fixes #11738
Added project_root argument in `SpinnerReported::spawn` to avoid computing project_root on every call

chore: pass project root to spinner

---

Cargo.toml

warning: profile package spec `solar` in profile `dev` did not match any packages

chore: profile.dev cargo warning

---

crates/evm/evm/src/executors/fuzz/mod.rs
crates/forge/tests/it/fuzz.rs

- closes #11787 
- decrement test runs when assume rejects run

fix(forge): decrement runs when fuzz input rejected

---

crates/evm/evm/src/executors/mod.rs
crates/forge/src/cmd/coverage.rs
crates/forge/src/cmd/snapshot.rs
crates/forge/src/cmd/test/mod.rs
crates/forge/src/multi_runner.rs
crates/forge/src/result.rs

Coverage was calling a low level function of forge test args, which does not setup stuff like config.fuzz.gas_report_samples, EvmArgs, etc., as well as missing options in the test runner builder etc.
This means that `forge coverage` falls out of sync gradually with `forge test`. One of the options which was thus missed, `gas_report_samples`, controls how many traces are saved from fuzz and invariant tests, which with the recent addition of tracing for backtraces means we are storing a lot of traces unnecessarily, massively increasing memory usage.

fix(coverage): sync implementation with forge test

---

.config/nextest.toml
.github/scripts/matrices.py

https://depot.dev/docs/github-actions/runner-types#macos-runners
There is no macos-latest-XX

ci: rm cores from depot macos runner

---

.github/workflows/release.yml

- use 22.04
- bump linux and windows from 2 to 16 cores

ci: update release runners

---

crates/common/src/comments/mod.rs
crates/fmt/src/state/common.rs
crates/fmt/src/state/mod.rs
crates/fmt/src/state/sol.rs
crates/fmt/testdata/ReprosCalls/110.fmt.sol
crates/fmt/testdata/ReprosCalls/120.fmt.sol
crates/fmt/testdata/ReprosCalls/80.fmt.sol
crates/fmt/testdata/ReprosCalls/original.sol
testdata/default/cheats/AttachDelegation.t.sol
testdata/default/cheats/GetCode.t.sol
testdata/default/repros/Issue3703.t.sol

closes: 
this PR introduces 2 fixes:
- when estimating the size of a snippet, only account for line breaks that are preceeded by a line that ends with a semicolon.
- track block depth so that, when estimating the space left, we can account for all of them rather than just contracts and funcs

fix(fmt): estimate size + account for all blocks

---

crates/anvil/rpc/src/error.rs

Hi! I found dead link in code and fixed their.
https://github.com/MetaMask/eth-rpc-errors/blob/main/src/error-constants.ts

chore(anvil): fixed broken link

---

crates/anvil/src/tasks/mod.rs

- **Summary**: `TaskManager::spawn_blocking` now returns a `JoinHandle<()>`, aligning it with `spawn` and enabling callers to await, cancel, or observe task failures.
- **Rationale**: Previously the handle was dropped, making it impossible to control or inspect spawned blocking tasks, which could lead to leaks and harder shutdown/error handling.
- **Change**: Function signature updated and docs expanded. 
- **Breaking change**: Yes — call sites must handle the returned `JoinHandle`.
- **Migration**:
```rust
// Before
task_manager.spawn_blocking(async { /* work */ });
// After
let handle = task_manager.spawn_blocking(async { /* work */ });
// Optionally:
handle.abort(); // or: let _ = handle.await;
```

anvil: return JoinHandle from `TaskManager::spawn_blocking` for proper task control

---

crates/common/src/fs.rs

Problem: In write_json_gzip_file, after GzEncoder::finish() we did not flush the inner BufWriter. Errors on the final buffered write can be silently ignored in Drop, causing undetected partial writes or I/O failures.
Why: BufWriter does not report errors on Drop. Without an explicit flush(), final write errors are lost. Additionally, we mapped finish() errors to WriteJson (serde) instead of I/O.
Fix: Capture the inner writer from finish() and call flush() on it. Map both finish() and flush() errors via FsPathError::write to provide correct path-contextual I/O errors.
Context: This gzip-to-disk path is only used by evm::executors::corpus when corpus_gzip is enabled. Other gzip usage (anvil state dump) targets Vec<u8> and doesn’t require flush(). Non-gzip JSON writers already call flush() …

fix(fs): flush BufWriter after GzEncoder::finish() in write_json_gzip_file

---

crates/evm/core/src/utils.rs

I make some tests in Gnosis network:
```solidity
string memory RPC_URL = vm.envString("GNOSIS_MAINNET_RPC");
vm.createSelectFork(RPC_URL, 21_120_284 - 1);
```
Then I get that error:
```bash
[FAIL: EVM error; header validation error: `prevrandao` not set]
```
I find the relevant issues: https://github.com/foundry-rs/foundry/issues/4232
Here is the provider I use:
```bash
https://weathered-silent-panorama.xdai.quiknode.pro/xxxxxxxxxxxx
```
Just add `Gnosis`
btw I am not sure how to run the test. Could u kindly provide a demo so that I could test it in my side? And then I could add a test case in this PR.

fix(prevrandao not set): support gnosis network

---

crates/common/src/selectors.rs

Replace unwrap() with error propagation in decode_calldata when parsing the first 4-byte selector from calldata. Previously, invalid hex (user-provided via CLI) could cause a process panic. Now we return an error instead, aligning with the function’s eyre::Result signature and with pretty_calldata which already uses ? for selector parsing. This prevents unexpected crashes on malformed input and improves UX while keeping behavior consistent across APIs.

fix(common): avoid panic on invalid calldata selector by propagating parse error

---

crates/forge/src/cmd/fmt.rs
crates/forge/tests/cli/fmt.rs

- closes #11871
- always return formatted when source read from stdin (and no other args `check` or `raw` passed)
- vscode plugin use stdin and replace content with `forge fmt` output

fix(fmt): always return formatted when source read from stdin

---

crates/cast/src/lib.rs
crates/common/src/utils.rs
crates/forge/src/cmd/flatten.rs
crates/verify/src/etherscan/flatten.rs

- closes #11754 use consistent flatten for `forge flatten`, `forge verify-contract` and `cast src`

fix(forge): same way to flatten for all commands

---

crates/forge/src/cmd/fmt.rs
crates/forge/tests/cli/fmt.rs

- fmt `--raw` should output raw formatted code in stdin modes
https://github.com/foundry-rs/foundry/blob/fe10724f648a9e034f00e67dbd96539721b44bfe/crates/forge/src/cmd/fmt.rs#L41-L43

fix(fmt): return formatted code when stdin and `--raw`

---

.github/workflows/benchmarks.yml
.github/workflows/nextest.yml
.github/workflows/test.yml

Don't need a name for a simple install action. it also doesn't run anything, it installs it.

ci: remove name from sccache action

---

crates/config/src/providers/warnings.rs
crates/forge/tests/cli/config.rs

- `solc_version` is a backward compatible config (replaced by `solc`) and removed from dict, should not warn if in config
https://github.com/foundry-rs/foundry/blob/4d07808d1615421746a32a7d2ab8f4a9983a4bc3/crates/config/src/providers/ext.rs#L299-L303

fix(forge): do not warn on backward compatible `solc_version` config

---

benches/LATEST.md
benchmark.sh

- Benchmark v1.3.6 (stable) against v1.4.0 (release candidate)
- Adds a `benches/benchmark.sh` script to easily reproduce the benchmark
- bench

chore: v1.4.0 benches

---

crates/anvil/core/src/eth/mod.rs
crates/anvil/src/eth/api.rs

The codebase had three RPC handler methods (protocol_version, hashrate, author) that were implemented in EthApi but were effectively dead code because they were not exposed through the JSON-RPC interface. These methods existed with proper documentation indicating they were handlers for standard Ethereum RPC calls (eth_protocolVersion, eth_hashrate, eth_coinbase), but they were never wired up in the EthRequest enum or the execute() dispatcher. This meant clients expecting these standard RPC endpoints would receive "method not found" errors, reducing Anvil's compatibility with Ethereum tooling and clients.
1. Adding missing EthRequest variants in crates/anvil/core/src/eth/mod.rs:
- EthProtocolVersion(()) for eth_protocolVersion
- EthHashrate(()) for eth_hashrate
- EthCoinbase(()) for …

feat(anvil): wire eth_protocolVersion, eth_hashrate, eth_coinbase RPCs

---

crates/fmt/src/state/common.rs
crates/fmt/testdata/Repros/fmt.sol
crates/fmt/testdata/Repros/original.sol
crates/fmt/testdata/Repros/sorted.fmt.sol
crates/fmt/testdata/Repros/tab.fmt.sol

closes #8557 
since we ended up deciding that it was better for solar to use a new `SpannedOption<T>` which only added the position of uninformed elements, rather than `Spanned<T>` that would wrap both `Some(T) + None` and inform their surrounding separators, the fix introduces a workaround that:
1. peeks at a comment before the next item
2. checks if the span from the cursor to the cmnt is disabled
3. gets the snippet from the sourcemap and checks if it has any commas
**NOTE:** i know we shouldn't rely on the sm, but imo the workaround is acceptable, as this path seems quite unlikely to be triggered frequently

fix(fmt): preserve comment position in disabled lines

---

crates/anvil/src/eth/backend/mem/mod.rs

Improves performance of log query operations by optimizing how data is passed between internal functions. Refactoring reduces redundant operations by passing additional context that's already available at call sites, resulting in measurable performance improvements particularly for range queries. 
Internal optimization only.

perf(anvil): optimize internal data passing in log queries

---

testdata/foundry.toml

I don't think this is used anyway

chore: trim testdata config file

---

docs/dev/lintrules.md

Describes how you can use Solar's HIR and AST dumping to develop lint rules.

docs: explain solar workflow for lint rules

---

crates/evm/evm/src/executors/fuzz/mod.rs
crates/forge/tests/it/fuzz.rs

- closes #11927 
- do not replay failure if current test selector is different than test that created counterexample
- extra: replayed failure does not count as a run, so if logic changes to vm.assume then should not decrement total runs

fix(forge): replay fuzz failure only if same test selector

---

crates/evm/evm/src/executors/fuzz/mod.rs
crates/forge/tests/it/fuzz.rs

- backport PR https://github.com/foundry-rs/foundry/pull/11947 (fix for https://github.com/foundry-rs/foundry/issues/11927) in 1.4

fix(forge): 1.4 backport replay fuzz failure only if same test selector (#11947)

---

crates/anvil/src/hardfork.rs

Remove an unused `BlockNumberOrTag` import from the `tests` module in `crates/anvil/src/hardfork.rs`. The import is not referenced and was suppressed with `#[allow(unused_imports)]`. Removing it reduces noise and avoids hiding useful warnings.

anvil: remove unused BlockNumberOrTag import in hardfork tests

---

crates/config/src/fs_permissions.rs

Close #11937 
- merged `find_all_permissions` logic into `find_permission`
- Refactored `find_permission` to return the highest privilege permission based on the longest matching path.
- Updated tests

refactor(config): simplify fs permission retrieval logic

---

crates/cast/src/cmd/storage.rs

Close #11975
clearer code / better maintainability
- Remove useless/unclear `pretty` args for `fetch_and_print_storage` && `print_storage`
- Directly call `shell::is_json()` and shell::is_markdown() in `print_storage`

chore(cast): remove unclear `pretty` arg for `print_storage`

---

crates/anvil/src/eth/backend/mem/mod.rs

Introduces `get_block_with_hash` and `convert_block_with_hash` to avoid redundant hash computation.
When fetching blocks, we already have the hash (from parameters or storage lookups), but `convert_block` calls `hash_slow()` to recompute it. The new helpers pass the hash through instead, saving a lot cycles per query.

refactor(anvil): introduce get_block_with_hash and convert_block_with_hash

---

.github/workflows/release.yml

Current `release` workflow does not correctly open an issue, this is because `create-an-issue` was pinned to the latest commit on `main` which does not include the `dist` directory. Instead it should refer to a commit made on a release tag that does: https://github.com/JasonEtco/create-an-issue/releases/tag/v2.9.2
Original commit does not include dist directory, tag commit does: https://github.com/JasonEtco/create-an-issue/commit/1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5, pinned it to that commit
It may be possible that Dependabot falsely will prompt for an update, if that is the case we can consider pinning this to the tag `v2.9.2` instead

fix(`ci`): `create-an-issue` in release workflow is pinned to incorrect hash

---

.github/workflows/release.yml

Somehow macos is harder to get right than windows

ci: use gha runner for macos arm releases
